### PR TITLE
Update npm packages

### PR DESCRIPTION
**Pull request by irahopkinson**
- security: `npm audit fix` for `express`
- update patch and some minor versions
- remove unused `package-lock.json` files

- - -
This change is [Reviewable](https://reviewable.io/reviews/paranext/paranext-core/815)

### CODE REVIEW

**Review by tjcouch-sil — DISMISSED** [review]
:lgtm: looks like [the problem is still there](https://github.com/paranext/paranext-core/blob/ea96b20540f65c22e2ec32dec85e47ef599d001b/lib/platform-bible-react/dist/index.js#L1013), but this is a great update nonetheless :) thanks!

> Reviewed 13 of 13 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/815#-:-Ntr8uvM-Doh97pb6iIA:b30qx8w)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Review by tjcouch-sil — CHANGES_REQUESTED** [review]
If I remember correctly, at some point previously, the `extensions/package-lock.json` and each extension's `package-lock.json` were removed. However, that meant that every extension was guaranteed to have a conflict while updating from template every time packages changed. As such, I suggest we keep them in. Would be glad to discuss if you'd like!

I believe the `package-lock.json` files in the `lib` subfolders can be safely deleted.

Would you mind making the same dependency updates to the templates as well? Thanks!

> Reviewed 17 of 22 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/815#-:-Nu4lU1S6lbndcI8a0FM:bglq3e6)* status: 20 of 25 files reviewed, all discussions resolved

**Review by irahopkinson — COMMENTED** [review]
Yes, you are correct, however, when you recently changed the repo to be a workspace that means that all that info is now contained in the root `package-lock.json` file (have a look inside to confirm) and all the `package-lock.json` of the workspace packages are now redundant. You can tell this from the fact that although I updated dependencies in the `package.json`, the corresponding `package-lock.json` files didn't change - just the root one changed. This is one of the main advantages of a workspace - that you can change all the individual dependencies and one `npm i` will update and resolve conflicts for all but still allow differences if required.

As for the templates, I should actually update them first. If you are happy with this change let me know and I'll updtae the templates first then merge them into this PR.

> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/815#-:-Nu5rSj08KeLhNnAh4T6:b7n1pcb)* status: 20 of 25 files reviewed, all discussions resolved

**Review by tjcouch-sil — COMMENTED** [review]
Right, if we keep the workspaces thing, the `package-lock.json` files shouldn't ever be modified again as part of our repo. In my mind, that's an even more optimal situation for pulling from the templates :) maybe we should even replace the current `package-lock.json` files with the ones from the template directly so we will then never again have a conflict because of `package-lock.json` differences while updating from templates! But if we completely delete the `package-lock.json` files, every single change to the templates' `package-lock.json` files will make a conflict with each extension. It's very tedious to work out all those conflicts every time we want to update from templates.

I'm happy with the other changes :)

> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/815#-:-Nu5tviq4vkuJKhtYP8F:bbcg9nq)* status: 20 of 25 files reviewed, all discussions resolved

**Review by irahopkinson — COMMENTED** [review]
I've merged in from the templates. However, I decided to leave the `package-lock.json` files deleted. If the npm packages are updated in the templates there would still be merge conflicts with the lock files here. So with the lock files removed your merge options are simply "_keep modifed version_", "_delete the file_", or "_keep the base version_". The right option is to delete it but either way there is no actual merge conflict to resolve. If this doesn't work out we can choose "_keep modifed version_" later.

> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/815#-:-NuWQ67D9mJFppcoMYrt:b-zgvhi0)* status: 14 of 25 files reviewed, all discussions resolved (waiting on @tjcouch-sil)

**Review by tjcouch-sil — COMMENTED** [review]
I'm not understanding your suggestion - shall we discuss on a call soon? Thanks!

> Reviewed 6 of 6 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/815#-:-NujDs0933kV0VTmejIr:bnxb5vh)* status: 20 of 25 files reviewed, all discussions resolved

**Review by tjcouch-sil — APPROVED** [review]
> Reviewed 5 of 22 files at r2.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/815)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Pull request merged**
