### PR TITLE
Populate local user dir with project

### LINKED ISSUE #440: Populate "<home_dir>/.platform.bible" with plausible defaults in dev
As a Platform.Bible developer, I would like my dev environment to be initially populated with sensible data so that I can test/use PAPI without having to create settings and data files on my own first.

---

Right now we aren't populating the .platform.bible directory with anything.  That means, for example, we don't have a way for users to try out ProjectDataProviders unless they figure out how to migrate an existing project and create a `meta.json` file with the right values on their own.

Make sure to fix the spots like https://github.com/paranext/paranext-core/blob/388-dialog-service/src/main/main.ts#L311 where testing is waiting for a project

### PR DESCRIPTION
**Pull request by rolfheij-sil**
Resolves #440 

This change is [Reviewable](https://reviewable.io/reviews/paranext/paranext-core/687)

### CODE REVIEW

**Review by rolfheij-sil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/687)* status: 0 of 5 files reviewed, 1 unresolved discussion

___
*[`src/extension-host/services/project-lookup.service-host.ts` line 99 at r1](https://reviewable.io/reviews/paranext/paranext-core/687#-Nm1wiXW6OvLr1CPbgIe:-Nm1wiXW6OvLr1CPbgIf:b-utjf3k) ([raw file](https://github.com/paranext/paranext-core/blob/ce9c34d199159ba04b0af66ee087b3df4dab57c8/src/extension-host/services/project-lookup.service-host.ts#L99)):*
> ```XML
> 
> async function getMetadataForAllProjects(): Promise<ProjectMetadata[]> {
>   // await initialize();
> ```

Note to self: this needs to be discussed

**Review by tjcouch-sil — COMMENTED** [review]
Thanks for this good work! Just a couple little things.

> Reviewed 4 of 5 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/687#-:-Nm3TJkGAkOEEdITFCXj:bmjzipy)* status: all files reviewed, 2 unresolved discussions (waiting on @rolfheij-sil)

___
*[`c-sharp/Projects/LocalParatextProjects.cs` line 206 at r2](https://reviewable.io/reviews/paranext/paranext-core/687#-Nm3RC6LATemTSKG6sv2:-Nm3RC6LATemTSKG6sv3:b-xu3nn5) ([raw file](https://github.com/paranext/paranext-core/blob/7764a9f1789fb954a86289b97d1097e9a454711b/c-sharp/Projects/LocalParatextProjects.cs#L206)):*
> ```Smalltalk
>     private IEnumerable<ProjectDetails> LoadAllProjectDetails()
>     {
>         Console.WriteLine(ProjectRootFolder);
> ```

I imagine this is debug and should be removed :)
___
*[`src/extension-host/services/project-lookup.service-host.ts` line 99 at r1](https://reviewable.io/reviews/paranext/paranext-core/687#-Nm1wiXW6OvLr1CPbgIe:-Nm3RPY86U0zuKpzs8tx:b-ivbdiv) ([raw file](https://github.com/paranext/paranext-core/blob/ce9c34d199159ba04b0af66ee087b3df4dab57c8/src/extension-host/services/project-lookup.service-host.ts#L99)):*
<details><summary><i>Previously, rolfheij-sil wrote…</i></summary><blockquote>

Note to self: this needs to be discussed
</blockquote></details>

I think it would probably be best long-term to watch the directory for changes and to run `reloadMetadata` when changes occur. However, I personally don't think we need to do that right now... Maybe we could file an issue on it or just leave it for whenever it becomes a problem.

I think the idea here to my understanding is to make sure to get the new project if the C# is making one, right? If so, it would be best to accomplish this without running `reloadMetadata` a bunch of extra times unnecessarily. I have one idea at the moment: do you think you could add logic in here similar to the logic used in the C# side to just wait for the C# to create the project? Maybe you can `await initialize()`, check to see if `localProjects` has any entries, return stuff if so, and just `wait(...)` for a second or however long is appropriate (waiting for the C# side to create a project) and run `reloadMetadata()` if not.

I suppose another option would be to create a network event and send it out on the C# side when the project is created and run `reloadMetadata()` here. But then that brings up the need for a subscription for getting project metadata, so that's probably not worth doing right now.

**Review by lyonsil — COMMENTED** [review]
> Reviewed 4 of 5 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/687)* status: all files reviewed, 4 unresolved discussions (waiting on @rolfheij-sil)

___
*[`c-sharp/Projects/LocalParatextProjects.cs` line 72 at r2](https://reviewable.io/reviews/paranext/paranext-core/687#-Nm79URL7R95QGaqF77q:-Nm79URL7R95QGaqF77r:b-uvfxw8) ([raw file](https://github.com/paranext/paranext-core/blob/7764a9f1789fb954a86289b97d1097e9a454711b/c-sharp/Projects/LocalParatextProjects.cs#L72)):*
> ```Smalltalk
>     }
> 
>     private void SetUpSampleProject()
> ```

Please move this to the "Private properties and methods" region in this file.
___
*[`c-sharp/Projects/LocalParatextProjects.cs` line 89 at r2](https://reviewable.io/reviews/paranext/paranext-core/687#-Nm7A859CafzsNXI2Av1:-Nm7A859CafzsNXI2Av2:bs66r7l) ([raw file](https://github.com/paranext/paranext-core/blob/7764a9f1789fb954a86289b97d1097e9a454711b/c-sharp/Projects/LocalParatextProjects.cs#L89)):*
> ```Smalltalk
>         CreateDirectory(projectFolder);
>         CreateDirectory(Path.Join(projectFolder, PROJECT_SUBDIRECTORY));
>         CreateDirectory(Path.Join(projectFolder, PROJECT_SUBDIRECTORY, EXTENSIONS_SUBDIRECTORY));
> ```

I think all subdirectories will be created along the way, so you don't need to explicitly create `projectFolder` and `PROJECT_SUBDIRECTORY` as separate calls.  You can just create the extensions and Paratext subdirectories.

**Review by rolfheij-sil — COMMENTED** [review]
Thanks TJ!

> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/687#-:-Nm6Y6f87xm9V8etFilg:b-7z3n2f)* status: all files reviewed, 3 unresolved discussions (waiting on @lyonsil and @tjcouch-sil)

___
*[`c-sharp/Projects/LocalParatextProjects.cs` line 72 at r2](https://reviewable.io/reviews/paranext/paranext-core/687#-Nm79URL7R95QGaqF77q:-Nm7JA0O0AbTjOvW6071:b-896fix) ([raw file](https://github.com/paranext/paranext-core/blob/7764a9f1789fb954a86289b97d1097e9a454711b/c-sharp/Projects/LocalParatextProjects.cs#L72)):*
<details><summary><i>Previously, lyonsil (Matt Lyons) wrote…</i></summary><blockquote>

Please move this to the "Private properties and methods" region in this file.
</blockquote></details>

Done.
___
*[`c-sharp/Projects/LocalParatextProjects.cs` line 89 at r2](https://reviewable.io/reviews/paranext/paranext-core/687#-Nm7A859CafzsNXI2Av1:-Nm7J3H86AOsjohmw0h9:b-kwviq5) ([raw file](https://github.com/paranext/paranext-core/blob/7764a9f1789fb954a86289b97d1097e9a454711b/c-sharp/Projects/LocalParatextProjects.cs#L89)):*
<details><summary><i>Previously, lyonsil (Matt Lyons) wrote…</i></summary><blockquote>

I think all subdirectories will be created along the way, so you don't need to explicitly create `projectFolder` and `PROJECT_SUBDIRECTORY` as separate calls.  You can just create the extensions and Paratext subdirectories.
</blockquote></details>

Done. Thanks for pointing that out!
___
*[`c-sharp/Projects/LocalParatextProjects.cs` line 206 at r2](https://reviewable.io/reviews/paranext/paranext-core/687#-Nm3RC6LATemTSKG6sv2:-Nm6Xqpb4iZaaKSiaGeY:b-896fix) ([raw file](https://github.com/paranext/paranext-core/blob/7764a9f1789fb954a86289b97d1097e9a454711b/c-sharp/Projects/LocalParatextProjects.cs#L206)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

I imagine this is debug and should be removed :)
</blockquote></details>

Done.
___
*[`src/extension-host/services/project-lookup.service-host.ts` line 99 at r1](https://reviewable.io/reviews/paranext/paranext-core/687#-Nm1wiXW6OvLr1CPbgIe:-Nm7K3ed1QRMZmkdC54d:b-1rswf8) ([raw file](https://github.com/paranext/paranext-core/blob/ce9c34d199159ba04b0af66ee087b3df4dab57c8/src/extension-host/services/project-lookup.service-host.ts#L99)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

I think it would probably be best long-term to watch the directory for changes and to run `reloadMetadata` when changes occur. However, I personally don't think we need to do that right now... Maybe we could file an issue on it or just leave it for whenever it becomes a problem.

I think the idea here to my understanding is to make sure to get the new project if the C# is making one, right? If so, it would be best to accomplish this without running `reloadMetadata` a bunch of extra times unnecessarily. I have one idea at the moment: do you think you could add logic in here similar to the logic used in the C# side to just wait for the C# to create the project? Maybe you can `await initialize()`, check to see if `localProjects` has any entries, return stuff if so, and just `wait(...)` for a second or however long is appropriate (waiting for the C# side to create a project) and run `reloadMetadata()` if not.

I suppose another option would be to create a network event and send it out on the C# side when the project is created and run `reloadMetadata()` here. But then that brings up the need for a subscription for getting project metadata, so that's probably not worth doing right now.
</blockquote></details>

`wait` is an easy solution indeed. But it feels kinda hacky. I also think watching the directory seems like the best solution. I could try to do that, or do you think that that would take too much time?

**Review by lyonsil — COMMENTED** [review]
Looking good - once we resolve how to update the Node.js side when projects are created it seems ready to go.

> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/687#-:-Nm7S7kB1V1Xi8hwVNzz:b-sdkuqk)* status: all files reviewed, 2 unresolved discussions (waiting on @tjcouch-sil)

___
*[`src/extension-host/services/project-lookup.service-host.ts` line 99 at r1](https://reviewable.io/reviews/paranext/paranext-core/687#-Nm1wiXW6OvLr1CPbgIe:-Nm7RawrD1f42RW6tXTr:b-3zyalb) ([raw file](https://github.com/paranext/paranext-core/blob/ce9c34d199159ba04b0af66ee087b3df4dab57c8/src/extension-host/services/project-lookup.service-host.ts#L99)):*
<details><summary><i>Previously, rolfheij-sil wrote…</i></summary><blockquote>

`wait` is an easy solution indeed. But it feels kinda hacky. I also think watching the directory seems like the best solution. I could try to do that, or do you think that that would take too much time?
</blockquote></details>

I agree the `wait` seems pretty hacky.  I think a time boxed effort (cap it to half a day?) to watch the directory would make sense.

**Review by tjcouch-sil — COMMENTED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/687)* status: all files reviewed, 1 unresolved discussion (waiting on @lyonsil and @rolfheij-sil)

___
*[`src/extension-host/services/project-lookup.service-host.ts` line 99 at r1](https://reviewable.io/reviews/paranext/paranext-core/687#-Nm1wiXW6OvLr1CPbgIe:-Nm7TGAt5twu4VvCObQP:b-s4dkkf) ([raw file](https://github.com/paranext/paranext-core/blob/ce9c34d199159ba04b0af66ee087b3df4dab57c8/src/extension-host/services/project-lookup.service-host.ts#L99)):*
<details><summary><i>Previously, lyonsil (Matt Lyons) wrote…</i></summary><blockquote>

I agree the `wait` seems pretty hacky.  I think a time boxed effort (cap it to half a day?) to watch the directory would make sense.
</blockquote></details>

A few thoughts:

1. Using `chokidar` to watch the project directory and run `reloadMetadata` wouldn't be that hard. We already are using `chokidar` in the extension service.
2. If you did that here instead of a `wait` so it does it if there are no `localProjects` and waits to return until after `localProjects` receives an update, I think that wouldn't be particularly difficult. Not a great solution, but it's a bit less hacky than `wait`.
3. If you don't want to force this method to wait until the projects directory gets an update (like adding the default project), that's a lot more work. Currently, this method is just getting project metadata. There is no mechanism to subscribe to updates on the metadata or anything like that. I think possibly the easiest way to add such a mechanism would be to change this service into a data provider so it has all the subscription code built in. Then you'd have to rework all the React and other code calling this function to subscribe to updates. It's a lot of work to make this work completely properly.

I suggested `wait` because list item 2 feels only somewhat less hacky than `wait` to me (though it is a bit better) and list item 3 feels like "the right way to do it" but is way too much out of scope work for this issue. Though `wait` or list item 2 are not the best options, I'm trying to find a good compromise between great coding and time spent on this issue on things that aren't really part of this issue in my mind.

**Review by rolfheij-sil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/687)* status: all files reviewed, 1 unresolved discussion (waiting on @tjcouch-sil)

___
*[`src/extension-host/services/project-lookup.service-host.ts` line 99 at r1](https://reviewable.io/reviews/paranext/paranext-core/687#-Nm1wiXW6OvLr1CPbgIe:-NmBwFw_68AuexVF-_xQ:bwjxezt) ([raw file](https://github.com/paranext/paranext-core/blob/ce9c34d199159ba04b0af66ee087b3df4dab57c8/src/extension-host/services/project-lookup.service-host.ts#L99)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

A few thoughts:

1. Using `chokidar` to watch the project directory and run `reloadMetadata` wouldn't be that hard. We already are using `chokidar` in the extension service.
2. If you did that here instead of a `wait` so it does it if there are no `localProjects` and waits to return until after `localProjects` receives an update, I think that wouldn't be particularly difficult. Not a great solution, but it's a bit less hacky than `wait`.
3. If you don't want to force this method to wait until the projects directory gets an update (like adding the default project), that's a lot more work. Currently, this method is just getting project metadata. There is no mechanism to subscribe to updates on the metadata or anything like that. I think possibly the easiest way to add such a mechanism would be to change this service into a data provider so it has all the subscription code built in. Then you'd have to rework all the React and other code calling this function to subscribe to updates. It's a lot of work to make this work completely properly.

I suggested `wait` because list item 2 feels only somewhat less hacky than `wait` to me (though it is a bit better) and list item 3 feels like "the right way to do it" but is way too much out of scope work for this issue. Though `wait` or list item 2 are not the best options, I'm trying to find a good compromise between great coding and time spent on this issue on things that aren't really part of this issue in my mind.
</blockquote></details>

Alright, should we merge this work then, and maybe create a new ticket for creating some sort of subscription mechanism?

**Review by tjcouch-sil — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/687)* status: all files reviewed, 1 unresolved discussion (waiting on @lyonsil and @rolfheij-sil)

___
*[`src/extension-host/services/project-lookup.service-host.ts` line 99 at r1](https://reviewable.io/reviews/paranext/paranext-core/687#-Nm1wiXW6OvLr1CPbgIe:-NmESIk9-Hj2MbsH1hxl:bnjzo05) ([raw file](https://github.com/paranext/paranext-core/blob/ce9c34d199159ba04b0af66ee087b3df4dab57c8/src/extension-host/services/project-lookup.service-host.ts#L99)):*
<details><summary><i>Previously, rolfheij-sil wrote…</i></summary><blockquote>

Alright, should we merge this work then, and maybe create a new ticket for creating some sort of subscription mechanism?
</blockquote></details>

I'm down to get this in.  Since this would happen

**Review by tjcouch-sil — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/687)* status: all files reviewed, 1 unresolved discussion (waiting on @lyonsil and @rolfheij-sil)

___
*[`src/extension-host/services/project-lookup.service-host.ts` line 99 at r1](https://reviewable.io/reviews/paranext/paranext-core/687#-Nm1wiXW6OvLr1CPbgIe:-NmETPrl9zx-74n-hhd_:b-qoqw0v) ([raw file](https://github.com/paranext/paranext-core/blob/ce9c34d199159ba04b0af66ee087b3df4dab57c8/src/extension-host/services/project-lookup.service-host.ts#L99)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

I'm down to get this in.  Since this would happen
</blockquote></details>

Sorry, I'm on my phone because I'm sick in bed 😂 and I honestly don't know how that submitted. Anyway I'd be down to get this in if you don't mind adding a comment on the wait explaining that this is just a temporary solution to make sure that we can read the one test project that is automatically added. And we should create an issue about actually watching for changes and mention that issue in the comment too so we keep track of the work.

I can try to keep an eye out to continue reviewing this PR tomorrow if you want to make the issue, or I can make it in the new year if you prefer I make it. Thanks!

**Review by rolfheij-sil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/687)* status: 4 of 5 files reviewed, 1 unresolved discussion (waiting on @lyonsil and @tjcouch-sil)

___
*[`src/extension-host/services/project-lookup.service-host.ts` line 99 at r1](https://reviewable.io/reviews/paranext/paranext-core/687#-Nm1wiXW6OvLr1CPbgIe:-NmGKmVO11MhGZ1lOiNL:bhk6iof) ([raw file](https://github.com/paranext/paranext-core/blob/ce9c34d199159ba04b0af66ee087b3df4dab57c8/src/extension-host/services/project-lookup.service-host.ts#L99)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

Sorry, I'm on my phone because I'm sick in bed 😂 and I honestly don't know how that submitted. Anyway I'd be down to get this in if you don't mind adding a comment on the wait explaining that this is just a temporary solution to make sure that we can read the one test project that is automatically added. And we should create an issue about actually watching for changes and mention that issue in the comment too so we keep track of the work.

I can try to keep an eye out to continue reviewing this PR tomorrow if you want to make the issue, or I can make it in the new year if you prefer I make it. Thanks!
</blockquote></details>

I've added a comment and created [a new issue](https://github.com/paranext/paranext-core/issues/691)

**Review by tjcouch-sil — APPROVED** [review]
:lgtm: thanks for getting this in!

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/687#-:-NmHcnmUCnRq10ia4gyf:b-dnoiy3)* status: 4 of 5 files reviewed, all discussions resolved (waiting on @lyonsil)

___
*[`src/extension-host/services/project-lookup.service-host.ts` line 99 at r1](https://reviewable.io/reviews/paranext/paranext-core/687#-Nm1wiXW6OvLr1CPbgIe:-NmHckjvBEnPYzR1AO4W:b-x8asnv) ([raw file](https://github.com/paranext/paranext-core/blob/ce9c34d199159ba04b0af66ee087b3df4dab57c8/src/extension-host/services/project-lookup.service-host.ts#L99)):*
<details><summary><i>Previously, rolfheij-sil wrote…</i></summary><blockquote>

I've added a comment and created [a new issue](https://github.com/paranext/paranext-core/issues/691)
</blockquote></details>

Thank you!! Looks great

**Review by tjcouch-sil — APPROVED** [review]
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/687)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Pull request merged**
