### PR TITLE
Remove redundant sender ID from the "registerRequest" command

### PR DESCRIPTION
**Pull request by lyonsil**
This change is [Reviewable](https://reviewable.io/reviews/paranext/paranext-core/692)

### CODE REVIEW

**Review by tjcouch-sil — CHANGES_REQUESTED** [review]
This is great! Thank you :) just a couple things to discuss

> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/692#-:-NnFeDakB7WNuUp913AX:b75578i)* status: all files reviewed, 4 unresolved discussions (waiting on @lyonsil)

___
*[`src/shared/services/network.service.ts` line 427 at r1](https://reviewable.io/reviews/paranext/paranext-core/692#-NnFdId6-VTU7bFyFeiH:-NnFdId70G2udP2VQ7AN:bj6ldfb) ([raw file](https://github.com/paranext/paranext-core/blob/4df59b9f4f9b0002568a0d8188f03a39347abb7b/src/shared/services/network.service.ts#L427)):*
> ```XML
>  * client
>  *
>  * @param requestType The type of request on which to unregister the handler
> ```

This JSDoc needs updating
___
*[`src/shared/services/network.service.ts` line 434 at r1](https://reviewable.io/reviews/paranext/paranext-core/692#-NnFd2a47Z8I2bcWtm0p:-NnFd2a47Z8I2bcWtm0q:bjweruj) ([raw file](https://github.com/paranext/paranext-core/blob/4df59b9f4f9b0002568a0d8188f03a39347abb7b/src/shared/services/network.service.ts#L434)):*
> ```XML
>   request: ComplexRequest<SerializedRequestType[]>,
> ): Promise<ComplexResponse<undefined>> => {
>   const requestType = request.contents[0];
> ```

I think I'd currently prefer to just rip the bandaid off and use `ComplexRequest<SerializedRequestType>` here and make a `platform-changes` announcement about this since we're still so early. Or actually maybe we could make it `ComplexRequest<SerializedRequestType[] | SerializedRequestType>` and handle the array or just one string so the bandaid isn't being ripped off completely. Or just leave it... If we leave the option to pass in an array either way, I think it would be best to document that only the first entry in the array is respected for now.

Same with `registerRemoteRequestHandler`
___
*[`src/shared/services/network.service.ts` line 467 at r1](https://reviewable.io/reviews/paranext/paranext-core/692#-NnFeHtW4UBIJ3z5ibgu:-NnFeHtX1AsPJCnvT6l3:bj6ldfb) ([raw file](https://github.com/paranext/paranext-core/blob/4df59b9f4f9b0002568a0d8188f03a39347abb7b/src/shared/services/network.service.ts#L467)):*
> ```XML
>  * client
>  *
>  * @param requestType The type of request on which to register the handler
> ```

This JSDoc needs updating
___
*[`src/shared/utils/papi-util.ts` line 91 at r1](https://reviewable.io/reviews/paranext/paranext-core/692#-NnFcV6P30PqZtBYTh8m:-NnFcV6P30PqZtBYTh8n:b3bplwj) ([raw file](https://github.com/paranext/paranext-core/blob/4df59b9f4f9b0002568a0d8188f03a39347abb7b/src/shared/utils/papi-util.ts#L91)):*
> ```XML
> type ComplexResponseSuccess<TReturn = unknown> = {
>   /** The one who sent the response */
>   senderId: number;
> ```

Since [the connection service already puts `senderId` on responses from the network service (and overwrites if there is already one)](https://github.com/paranext/paranext-core/blob/486-multi-extension-template/src/shared/services/connection.service.ts#L154), I think it might be best not to move `senderId` to the `ComplexResponse`s. Seems it unnecessarily increases complexity and isn't used. What do you think about moving this back to the `InternalResponse` types?

**Review by lyonsil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/692)* status: all files reviewed, 4 unresolved discussions (waiting on @tjcouch-sil)

___
*[`src/shared/services/network.service.ts` line 434 at r1](https://reviewable.io/reviews/paranext/paranext-core/692#-NnFd2a47Z8I2bcWtm0p:-NnFlEJi9Fp-w3CVthk1:bfyezzy) ([raw file](https://github.com/paranext/paranext-core/blob/4df59b9f4f9b0002568a0d8188f03a39347abb7b/src/shared/services/network.service.ts#L434)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

I think I'd currently prefer to just rip the bandaid off and use `ComplexRequest<SerializedRequestType>` here and make a `platform-changes` announcement about this since we're still so early. Or actually maybe we could make it `ComplexRequest<SerializedRequestType[] | SerializedRequestType>` and handle the array or just one string so the bandaid isn't being ripped off completely. Or just leave it... If we leave the option to pass in an array either way, I think it would be best to document that only the first entry in the array is respected for now.

Same with `registerRemoteRequestHandler`
</blockquote></details>

If we make it not an array input argument, where are you thinking that the items on the array would be pulled out?  This function is just being added to a map, and the types aren't known at runtime.  Are you thinking some requests will pass arrays of arguments while others will pass a structured object?  I was assuming the actual network messages would still pass arrays.
___
*[`src/shared/utils/papi-util.ts` line 91 at r1](https://reviewable.io/reviews/paranext/paranext-core/692#-NnFcV6P30PqZtBYTh8m:-NnFm6vB-h7NwkeVhtuq:b6doapm) ([raw file](https://github.com/paranext/paranext-core/blob/4df59b9f4f9b0002568a0d8188f03a39347abb7b/src/shared/utils/papi-util.ts#L91)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

Since [the connection service already puts `senderId` on responses from the network service (and overwrites if there is already one)](https://github.com/paranext/paranext-core/blob/486-multi-extension-template/src/shared/services/connection.service.ts#L154), I think it might be best not to move `senderId` to the `ComplexResponse`s. Seems it unnecessarily increases complexity and isn't used. What do you think about moving this back to the `InternalResponse` types?
</blockquote></details>

Ok - I was trying to keep the `ComplexRequest` and `ComplexResponse` type definitions parallel with each other.  but I can take it off here.

**Review by tjcouch-sil — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/692)* status: all files reviewed, 4 unresolved discussions (waiting on @lyonsil)

___
*[`src/shared/services/network.service.ts` line 434 at r1](https://reviewable.io/reviews/paranext/paranext-core/692#-NnFd2a47Z8I2bcWtm0p:-NnJtFM65tLqKxBXoTXJ:b-50n3f0) ([raw file](https://github.com/paranext/paranext-core/blob/4df59b9f4f9b0002568a0d8188f03a39347abb7b/src/shared/services/network.service.ts#L434)):*
<details><summary><i>Previously, lyonsil (Matt Lyons) wrote…</i></summary><blockquote>

If we make it not an array input argument, where are you thinking that the items on the array would be pulled out?  This function is just being added to a map, and the types aren't known at runtime.  Are you thinking some requests will pass arrays of arguments while others will pass a structured object?  I was assuming the actual network messages would still pass arrays.
</blockquote></details>

Ahh I was just thinking about how you can technically make the `content` whatever you want if you use this complex request type. However, I see now that the request function is built to work with an array of arguments. Every other request we have has an array for its content type. As such, it would be really unwieldy to change how requesting works in TS just for this one thing (though I guess we could change `requestUnsafe` to `requestRawUnsafe` just in this one place... ehh not work breaking consistency and backward compatibility). Ok then, I get it now; I'd say just leave it then.

I think we should make this explicit in the type, though: `request: ComplexRequest<[SerializedRequestType]>`. And might be nice to change this line to `const [requestType] = request.contents` to look a bit cleaner and more like we usually write it (this is a stylistic choice more than anything, though, so feel free to ignore).

Also would still be best to carefully document this :)

**Review by lyonsil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/692)* status: 1 of 5 files reviewed, 4 unresolved discussions (waiting on @tjcouch-sil)

___
*[`src/shared/services/network.service.ts` line 427 at r1](https://reviewable.io/reviews/paranext/paranext-core/692#-NnFdId6-VTU7bFyFeiH:-NnKs1hIEWHCeTIm3fjb:b-896fix) ([raw file](https://github.com/paranext/paranext-core/blob/4df59b9f4f9b0002568a0d8188f03a39347abb7b/src/shared/services/network.service.ts#L427)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

This JSDoc needs updating
</blockquote></details>

Done.
___
*[`src/shared/services/network.service.ts` line 434 at r1](https://reviewable.io/reviews/paranext/paranext-core/692#-NnFd2a47Z8I2bcWtm0p:-NnKupGM1QPgOaY-atLU:b-mjhufu) ([raw file](https://github.com/paranext/paranext-core/blob/4df59b9f4f9b0002568a0d8188f03a39347abb7b/src/shared/services/network.service.ts#L434)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

Ahh I was just thinking about how you can technically make the `content` whatever you want if you use this complex request type. However, I see now that the request function is built to work with an array of arguments. Every other request we have has an array for its content type. As such, it would be really unwieldy to change how requesting works in TS just for this one thing (though I guess we could change `requestUnsafe` to `requestRawUnsafe` just in this one place... ehh not work breaking consistency and backward compatibility). Ok then, I get it now; I'd say just leave it then.

I think we should make this explicit in the type, though: `request: ComplexRequest<[SerializedRequestType]>`. And might be nice to change this line to `const [requestType] = request.contents` to look a bit cleaner and more like we usually write it (this is a stylistic choice more than anything, though, so feel free to ignore).

Also would still be best to carefully document this :)
</blockquote></details>

Docs have been updated.  I went ahead and updated the syntax as you suggested, too.  It doesn't feel natural given my work in other languages, but I think it's important to try to stick with what standard approaches are in TS, so thanks for pointing this out.
___
*[`src/shared/services/network.service.ts` line 467 at r1](https://reviewable.io/reviews/paranext/paranext-core/692#-NnFeHtW4UBIJ3z5ibgu:-NnKvcaX4BIJk-YxFUf_:b-896fix) ([raw file](https://github.com/paranext/paranext-core/blob/4df59b9f4f9b0002568a0d8188f03a39347abb7b/src/shared/services/network.service.ts#L467)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

This JSDoc needs updating
</blockquote></details>

Done.
___
*[`src/shared/utils/papi-util.ts` line 91 at r1](https://reviewable.io/reviews/paranext/paranext-core/692#-NnFcV6P30PqZtBYTh8m:-NnL1wOpAYPPhwdRBUAI:b-896fix) ([raw file](https://github.com/paranext/paranext-core/blob/4df59b9f4f9b0002568a0d8188f03a39347abb7b/src/shared/utils/papi-util.ts#L91)):*
<details><summary><i>Previously, lyonsil (Matt Lyons) wrote…</i></summary><blockquote>

Ok - I was trying to keep the `ComplexRequest` and `ComplexResponse` type definitions parallel with each other.  but I can take it off here.
</blockquote></details>

Done.

**Review by tjcouch-sil — APPROVED** [review]
:lgtm:

> Reviewed 4 of 4 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/692#-:-NnLbMVSBaIQCD0sqODP:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Pull request merged**
