### PR TITLE
Event more attributes about network objects when they are registered

### PR DESCRIPTION
**Pull request by lyonsil**
This change is [Reviewable](https://reviewable.io/reviews/paranext/paranext-core/698)

### CODE REVIEW

**Review by tjcouch-sil — COMMENTED** [review]
Looks good! Just a couple little things here and there. Thanks!

> Reviewed 16 of 16 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/698#-:-Nnf8b_h6OBNCoMNXiQ-:bg2fegg)* status: all files reviewed, 3 unresolved discussions (waiting on @lyonsil)

___
*[`c-sharp/Messages/MessageEventProjectDataProviderCreated.cs` line 62 at r1](https://reviewable.io/reviews/paranext/paranext-core/698#-NnejaMh9PthA2jWPgDu:-NnejaMh9PthA2jWPgDv:b-5ruv5h) ([raw file](https://github.com/paranext/paranext-core/blob/ec088636ce58ccb0e15cfde59c59b23e6be1ce43/c-sharp/Messages/MessageEventProjectDataProviderCreated.cs#L62)):*
> ```Smalltalk
> {
>     public string? ProjectId { get; set; }
>     public string? ProjectStorageType { get; set; }
> ```

I think we may not want to publicly associate a project storage type with a PDP. Currently, we're passing it in as the second argument to `pdpFactory.getProjectDataProviderId` in `project-data-provider.service.ts`'s `get` function as a temporary measure for getting the `psi` from a predetermined network id formula, but I believe that will be replaced with passing in the PSI's id at some point. `storageType` theoretically isn't relevant to the PDP, I don't think.
___
*[`src/shared/services/data-provider.service.ts` line 585 at r1](https://reviewable.io/reviews/paranext/paranext-core/698#-Nnf47kr7TWVx4PQJrF5:-Nnf47kr7TWVx4PQJrF6:bqfpll0) ([raw file](https://github.com/paranext/paranext-core/blob/ec088636ce58ccb0e15cfde59c59b23e6be1ce43/src/shared/services/data-provider.service.ts#L585)):*
> ```XML
>   providerName: DataProviderName,
>   dataProviderEngine: IDataProviderEngine<DataProviderTypes[DataProviderName]>,
>   dataProviderType: string = 'dataProvider',
> ```

Please add JSDoc for these :)
___
*[`src/shared/services/data-provider.service.ts` line 646 at r1](https://reviewable.io/reviews/paranext/paranext-core/698#-Nnf5GaV0h8YibEct6Lo:-Nnf5GaV0h8YibEct6Lp:b-ph1h44) ([raw file](https://github.com/paranext/paranext-core/blob/ec088636ce58ccb0e15cfde59c59b23e6be1ce43/src/shared/services/data-provider.service.ts#L646)):*
> ```XML
> 
> /**
>  * Create a mock local data provider object for connecting to the remote data provider
> ```

Iiiiif you're feeling particularly charitable while you're updating the JSDoc, would you mind changing this whole JSDOC to the following please (and adding your new `param`s as well)? Looks like this whole JSDoc got diced up and mixed with the following function's JSDoc - wonder if it was in the early stages of using the JSDoc formatter plugin or something. Oops... Sorry :grimacing:

```typescript
/**
 * Creates a data provider to be shared on the network layering over the provided data provider
 * engine.
 *
 * @type `TDataTypes` - The data provider data types served by the data provider to create.
 *
 *   This is not exposed on the papi as it is a helper function to enable other services to layer over
 *   this service and create their own subsets of data providers with other types than
 *   `DataProviders` types using this function and {@link getByType}
 *
 * @param providerName Name this data provider should be called on the network
 * @param dataProviderEngine The object to layer over with a new data provider object
 *
 *   WARNING: registering a dataProviderEngine mutates the provided object. Its `notifyUpdate` and
 *   `set` methods are layered over to facilitate data provider subscriptions.
 * @returns The data provider including control over disposing of it. Note that this data provider
 *   is a new object distinct from the data provider engine passed in.
 */
```

Obviously this is not your problem to fix, so feel free to ignore.
___
*[`src/shared/services/data-provider.service.ts` line 670 at r1](https://reviewable.io/reviews/paranext/paranext-core/698#-NnerezBAoyhxALY4-f7:-NnerezBAoyhxALY4-f8:b-181ofg) ([raw file](https://github.com/paranext/paranext-core/blob/ec088636ce58ccb0e15cfde59c59b23e6be1ce43/src/shared/services/data-provider.service.ts#L670)):*
> ```XML
> // Seems TypeScript doesn't like using a generic string to index DataProviderDataTypes
> // eslint-disable-next-line @typescript-eslint/no-explicit-any
> export async function registerEngineByType<TDataTypes extends DataProviderDataTypes>(
> ```

I think we need to add the new `registerEngine` arguments to this function as well so the TypeScript side can set these properly in `registerProjectDataProvider` and (in the future) whatever we do for registering PSIs.

And please update the JSDoc appropriately :)

**Review by lyonsil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/698)* status: 13 of 16 files reviewed, 3 unresolved discussions (waiting on @tjcouch-sil)

___
*[`c-sharp/Messages/MessageEventProjectDataProviderCreated.cs` line 62 at r1](https://reviewable.io/reviews/paranext/paranext-core/698#-NnejaMh9PthA2jWPgDu:-Nniq8dMA91vYDnqcff1:b-14ktev) ([raw file](https://github.com/paranext/paranext-core/blob/ec088636ce58ccb0e15cfde59c59b23e6be1ce43/c-sharp/Messages/MessageEventProjectDataProviderCreated.cs#L62)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

I think we may not want to publicly associate a project storage type with a PDP. Currently, we're passing it in as the second argument to `pdpFactory.getProjectDataProviderId` in `project-data-provider.service.ts`'s `get` function as a temporary measure for getting the `psi` from a predetermined network id formula, but I believe that will be replaced with passing in the PSI's id at some point. `storageType` theoretically isn't relevant to the PDP, I don't think.
</blockquote></details>

What this class is saying is that a particular PDP happens to be using a particular storage type.  If we update it later with PSI, the same metadata still exists.  It could be represented this way or by giving a PSI object that contains the storage type.

I guess I'm not sure what you mean by "relevant."  In my mind, a PDP has to be using project data that is saved somewhere, and that somewhere is the storage type.  It's just metadata, but potentially helpful for power users I would think.  Having said that, if you really want it removed I can remove it.  It just doesn't make sense to me why we'd want to remove metadata that will always exist in some form.
___
*[`src/shared/services/data-provider.service.ts` line 585 at r1](https://reviewable.io/reviews/paranext/paranext-core/698#-Nnf47kr7TWVx4PQJrF5:-Nnisj-WBBipXy1hieAz:b-896fix) ([raw file](https://github.com/paranext/paranext-core/blob/ec088636ce58ccb0e15cfde59c59b23e6be1ce43/src/shared/services/data-provider.service.ts#L585)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

Please add JSDoc for these :)
</blockquote></details>

Done.
___
*[`src/shared/services/data-provider.service.ts` line 646 at r1](https://reviewable.io/reviews/paranext/paranext-core/698#-Nnf5GaV0h8YibEct6Lo:-Nniu_TLB8VXeej87LBa:bb6un1j) ([raw file](https://github.com/paranext/paranext-core/blob/ec088636ce58ccb0e15cfde59c59b23e6be1ce43/src/shared/services/data-provider.service.ts#L646)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

Iiiiif you're feeling particularly charitable while you're updating the JSDoc, would you mind changing this whole JSDOC to the following please (and adding your new `param`s as well)? Looks like this whole JSDoc got diced up and mixed with the following function's JSDoc - wonder if it was in the early stages of using the JSDoc formatter plugin or something. Oops... Sorry :grimacing:

```typescript
/**
 * Creates a data provider to be shared on the network layering over the provided data provider
 * engine.
 *
 * @type `TDataTypes` - The data provider data types served by the data provider to create.
 *
 *   This is not exposed on the papi as it is a helper function to enable other services to layer over
 *   this service and create their own subsets of data providers with other types than
 *   `DataProviders` types using this function and {@link getByType}
 *
 * @param providerName Name this data provider should be called on the network
 * @param dataProviderEngine The object to layer over with a new data provider object
 *
 *   WARNING: registering a dataProviderEngine mutates the provided object. Its `notifyUpdate` and
 *   `set` methods are layered over to facilitate data provider subscriptions.
 * @returns The data provider including control over disposing of it. Note that this data provider
 *   is a new object distinct from the data provider engine passed in.
 */
```

Obviously this is not your problem to fix, so feel free to ignore.
</blockquote></details>

Done
___
*[`src/shared/services/data-provider.service.ts` line 670 at r1](https://reviewable.io/reviews/paranext/paranext-core/698#-NnerezBAoyhxALY4-f7:-NniudJj3XmBrT4fEear:b-896fix) ([raw file](https://github.com/paranext/paranext-core/blob/ec088636ce58ccb0e15cfde59c59b23e6be1ce43/src/shared/services/data-provider.service.ts#L670)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

I think we need to add the new `registerEngine` arguments to this function as well so the TypeScript side can set these properly in `registerProjectDataProvider` and (in the future) whatever we do for registering PSIs.

And please update the JSDoc appropriately :)
</blockquote></details>

Done.

**Review by tjcouch-sil — COMMENTED** [review]
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/698)* status: all files reviewed, 2 unresolved discussions (waiting on @lyonsil)

___
*[`c-sharp/Messages/MessageEventProjectDataProviderCreated.cs` line 62 at r1](https://reviewable.io/reviews/paranext/paranext-core/698#-NnejaMh9PthA2jWPgDu:-Nnj1x8m78ilaqoKJmgt:bh5o44o) ([raw file](https://github.com/paranext/paranext-core/blob/ec088636ce58ccb0e15cfde59c59b23e6be1ce43/c-sharp/Messages/MessageEventProjectDataProviderCreated.cs#L62)):*
<details><summary><i>Previously, lyonsil (Matt Lyons) wrote…</i></summary><blockquote>

What this class is saying is that a particular PDP happens to be using a particular storage type.  If we update it later with PSI, the same metadata still exists.  It could be represented this way or by giving a PSI object that contains the storage type.

I guess I'm not sure what you mean by "relevant."  In my mind, a PDP has to be using project data that is saved somewhere, and that somewhere is the storage type.  It's just metadata, but potentially helpful for power users I would think.  Having said that, if you really want it removed I can remove it.  It just doesn't make sense to me why we'd want to remove metadata that will always exist in some form.
</blockquote></details>

I don't know that we should tell the PDP which `storageType` the PSI it uses will be moving forward... I guess we could always just leave it as is and add the PSI's id as another parameter :) but the intent is that `storageType` is not something the PDP will need to use for anything whatsoever, hence "relevant". But maybe we will think of some reason it would be helpful that doesn't break the design at some point, so we can leave it.

Right now, [the second parameter to `getProjectDataProviderId` is actually called `projectStorageInterpreterId`](https://github.com/paranext/paranext-core/blob/c752f0bbe8fcaeb48f88d2e4e124d3e5205418e7/src/shared/services/project-data-provider.service.ts#L36) (though it is just [being passed the `storageType`](https://github.com/paranext/paranext-core/blob/c752f0bbe8fcaeb48f88d2e4e124d3e5205418e7/src/shared/services/project-data-provider.service.ts#L128) at the moment). As such, theoretically we are not passing the `storageType` to the `registerProjectDataProvider` and we would not be able to set the `storageType` on the metadata. I don't think we have any code exercising this PSI-related stuff right now, so I think it would be easy to fix it so the second argument is actually the PSI id with #367 (and maybe we could also add a third argument which is the `storageType` if desired) with your changes from this PR in place.
___
*[`src/shared/services/data-provider.service.ts` line 585 at r1](https://reviewable.io/reviews/paranext/paranext-core/698#-Nnf47kr7TWVx4PQJrF5:-Nnj2yrbDRtJS3mAXJ8n:b-ucfknh) ([raw file](https://github.com/paranext/paranext-core/blob/ec088636ce58ccb0e15cfde59c59b23e6be1ce43/src/shared/services/data-provider.service.ts#L585)):*
<details><summary><i>Previously, lyonsil (Matt Lyons) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Thanks!
___
*[`src/shared/services/data-provider.service.ts` line 646 at r1](https://reviewable.io/reviews/paranext/paranext-core/698#-Nnf5GaV0h8YibEct6Lo:-Nnj32Nm5LIK6bBomoLq:b-ucfknh) ([raw file](https://github.com/paranext/paranext-core/blob/ec088636ce58ccb0e15cfde59c59b23e6be1ce43/src/shared/services/data-provider.service.ts#L646)):*
<details><summary><i>Previously, lyonsil (Matt Lyons) wrote…</i></summary><blockquote>

Done
</blockquote></details>

Thanks!
___
*[`src/shared/services/data-provider.service.ts` line 670 at r1](https://reviewable.io/reviews/paranext/paranext-core/698#-NnerezBAoyhxALY4-f7:-Nnj343V408bsgOhpQvz:b-ucfknh) ([raw file](https://github.com/paranext/paranext-core/blob/ec088636ce58ccb0e15cfde59c59b23e6be1ce43/src/shared/services/data-provider.service.ts#L670)):*
<details><summary><i>Previously, lyonsil (Matt Lyons) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Thanks!
___
*[`src/shared/services/project-data-provider.service.ts` line 61 at r2](https://reviewable.io/reviews/paranext/paranext-core/698#-Nnj3Ws_4n4_O7JWvzPv:-Nnj3Ws_4n4_O7JWvzPw:bvjqryr) ([raw file](https://github.com/paranext/paranext-core/blob/ccf72b7d10b42665a94a5c5c590a993cb4de7fea/src/shared/services/project-data-provider.service.ts#L61)):*
> ```XML
>       throw new Error('projectDataProviderEngine must implement "MandatoryProjectDataTypes"');
>     const pdpId: string = `${newNonce()}-pdp`;
>     const pdp = await registerEngineByType<ProjectDataTypes[ProjectType]>(
> ```

I believe we need to add metadata for PDPs in here. Sorry I didn't make this clear before in my previous comment.

**Review by lyonsil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/698)* status: 12 of 17 files reviewed, 1 unresolved discussion (waiting on @tjcouch-sil)

___
*[`c-sharp/Messages/MessageEventProjectDataProviderCreated.cs` line 62 at r1](https://reviewable.io/reviews/paranext/paranext-core/698#-NnejaMh9PthA2jWPgDu:-NnjPTENAIuKKAV65x74:b3cqvq3) ([raw file](https://github.com/paranext/paranext-core/blob/ec088636ce58ccb0e15cfde59c59b23e6be1ce43/c-sharp/Messages/MessageEventProjectDataProviderCreated.cs#L62)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

I don't know that we should tell the PDP which `storageType` the PSI it uses will be moving forward... I guess we could always just leave it as is and add the PSI's id as another parameter :) but the intent is that `storageType` is not something the PDP will need to use for anything whatsoever, hence "relevant". But maybe we will think of some reason it would be helpful that doesn't break the design at some point, so we can leave it.

Right now, [the second parameter to `getProjectDataProviderId` is actually called `projectStorageInterpreterId`](https://github.com/paranext/paranext-core/blob/c752f0bbe8fcaeb48f88d2e4e124d3e5205418e7/src/shared/services/project-data-provider.service.ts#L36) (though it is just [being passed the `storageType`](https://github.com/paranext/paranext-core/blob/c752f0bbe8fcaeb48f88d2e4e124d3e5205418e7/src/shared/services/project-data-provider.service.ts#L128) at the moment). As such, theoretically we are not passing the `storageType` to the `registerProjectDataProvider` and we would not be able to set the `storageType` on the metadata. I don't think we have any code exercising this PSI-related stuff right now, so I think it would be easy to fix it so the second argument is actually the PSI id with #367 (and maybe we could also add a third argument which is the `storageType` if desired) with your changes from this PR in place.
</blockquote></details>

I wasn't taking TS into account since we don't create any PDPs from there.  Since we have unexercised code that can do it, though, I made this adjustment.  If someone wants to see the storage type they still can, but they'll have to join attributes from the PDP with attributes in the corresponding PSI.
___
*[`src/shared/services/project-data-provider.service.ts` line 61 at r2](https://reviewable.io/reviews/paranext/paranext-core/698#-Nnj3Ws_4n4_O7JWvzPv:-NnjPEWAB2_MjcJGCmlT:b15ag8f) ([raw file](https://github.com/paranext/paranext-core/blob/ccf72b7d10b42665a94a5c5c590a993cb4de7fea/src/shared/services/project-data-provider.service.ts#L61)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

I believe we need to add metadata for PDPs in here. Sorry I didn't make this clear before in my previous comment.
</blockquote></details>

Done - Sorry I missed this previously.  I was looking at code that is actually getting used, and nothing is calling this yet.

**Review by tjcouch-sil — DISMISSED** [review]
:lgtm: thanks for the hard work on this! Just one little optional thing.

> Reviewed 5 of 5 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/698#-:-NnjYG17AzkIM2P0qp4p:b2h4nam)* status: all files reviewed, 1 unresolved discussion (waiting on @lyonsil)

___
*[`src/shared/models/network-object.model.ts` line 74 at r4](https://reviewable.io/reviews/paranext/paranext-core/698#-NnjXYBlDrjC-tqxj9Sp:-NnjXYBmCIihC-uicj5O:b-t85vjp) ([raw file](https://github.com/paranext/paranext-core/blob/1b7753259e2c15af6acdf197306c4ca363b12227/src/shared/models/network-object.model.ts#L74)):*
> ```XML
>  * Data about an object shared on the network
>  *
>  * @param id ID of the network object that processes use to reference it
> ```

Looks like these `@param` docs need to be split up into individual JSDocs on each property in this type to make them work with `type` syntax. Sorry I didn't catch this before. Feel free to resolve this and merge, and we can grab it sometime in another PR.

**Review by lyonsil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/698)* status: 15 of 17 files reviewed, all discussions resolved (waiting on @tjcouch-sil)

___
*[`src/shared/models/network-object.model.ts` line 74 at r4](https://reviewable.io/reviews/paranext/paranext-core/698#-NnjXYBlDrjC-tqxj9Sp:-Nnjao6Y-hsDWTUWhA-D:b-886gsx) ([raw file](https://github.com/paranext/paranext-core/blob/1b7753259e2c15af6acdf197306c4ca363b12227/src/shared/models/network-object.model.ts#L74)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

Looks like these `@param` docs need to be split up into individual JSDocs on each property in this type to make them work with `type` syntax. Sorry I didn't catch this before. Feel free to resolve this and merge, and we can grab it sometime in another PR.
</blockquote></details>

Fixed

**Review by tjcouch-sil — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/698#-:-NnjkQUfDaCknbARfBez:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Pull request merged**
