### PR TITLE
Add 'npm stop' script and clean up some more processes

### PR DESCRIPTION
**Pull request by lyonsil**
This change is [Reviewable](https://reviewable.io/reviews/paranext/paranext-core/274)

### CODE REVIEW

**Review by FoolRunning — CHANGES_REQUESTED** [review]
> Reviewed 2 of 3 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/274)* status: all files reviewed, 1 unresolved discussion (waiting on @lyonsil)

___
*[`package-lock.json` line 43649 at r2](https://reviewable.io/reviews/paranext/paranext-core/274#-NZRHSHO1yrDCt1xpL_z:-NZRHSHO1yrDCt1xpLa-:b-qpdhfx) ([raw file](https://github.com/paranext/paranext-core/blob/47253a9f65c234db42e7fb191d656dc4bf0f6829/package-lock.json#L43649)):*
> ```JSON
>       "resolved": "https://registry.npmjs.org/which/-/which-2.0.2.tgz",
>       "integrity": "sha512-BLI3Tl1TW3Pvl70l3yq3Y64i+awpwXqsGBYWkkqMtnbXgrMD+yj7rhW0kuEDxzJaYXGjEW5ogapKNMEKNMjibA==",
>       "dev": true,
> ```

There are a bunch of these removals. I just want to make sure that was on purpose since I would think orphaned processes would only be a developer problem.

**Comment by tjcouch-sil** [comment]
*[`package-lock.json` line 43649 at r2](https://reviewable.io/reviews/paranext/paranext-core/274#-NZRHSHO1yrDCt1xpL_z:-NZRLShgBpbbOiJmJmiC:b-iyfaz0) ([raw file](https://github.com/paranext/paranext-core/blob/47253a9f65c234db42e7fb191d656dc4bf0f6829/package-lock.json#L43649)):*
<details><summary><i>Previously, FoolRunning (Tim Steenwyk) wrote…</i></summary><blockquote>

There are a bunch of these removals. I just want to make sure that was on purpose since I would think orphaned processes would only be a developer problem.
</blockquote></details>

Ooh good catch. Looks like `fkill` was installed as a dependency, not a devDependency. Matt, would you mind uninstalling `fkill` and reinstalling with `npm install fkill --save-dev` or `npm install -D fkill` (shorthand)? Since `fkill` isn't used in production, we only need it as a `devDependency`, meaning it is indicated to run only on build steps and dev stuff and such things.

**Review by lyonsil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/274)* status: 3 of 5 files reviewed, 1 unresolved discussion (waiting on @FoolRunning)

___
*[`package-lock.json` line 43649 at r2](https://reviewable.io/reviews/paranext/paranext-core/274#-NZRHSHO1yrDCt1xpL_z:-NZROIZo5C4xiQ7kJaVC:b-896fix) ([raw file](https://github.com/paranext/paranext-core/blob/47253a9f65c234db42e7fb191d656dc4bf0f6829/package-lock.json#L43649)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

Ooh good catch. Looks like `fkill` was installed as a dependency, not a devDependency. Matt, would you mind uninstalling `fkill` and reinstalling with `npm install fkill --save-dev` or `npm install -D fkill` (shorthand)? Since `fkill` isn't used in production, we only need it as a `devDependency`, meaning it is indicated to run only on build steps and dev stuff and such things.
</blockquote></details>

Done.

**Review by FoolRunning — APPROVED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/274)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @lyonsil)

**Pull request merged**
