### PR TITLE
update dependencies

### PR DESCRIPTION
**Pull request by irahopkinson**
- update from templates
- `npm audit fix`
- update `webpack-dev-server`
- update minor & patch versions
- update some major versions
- note updating `sass` to v1.79.4 kills `npm start`

- - -
This change is [Reviewable](https://reviewable.io/reviews/paranext/paranext-core/1197)

### CODE REVIEW

**Review by lyonsil — CHANGES_REQUESTED** [review]
> Reviewed 38 of 38 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/1197)* status: all files reviewed, 1 unresolved discussion (waiting on @irahopkinson)

___
*[`extensions/src/hello-someone/README.md` line 5 at r1](https://reviewable.io/reviews/paranext/paranext-core/1197#-O8MjnIsDMwup4Z8slnW:-O8MjnIsDMwup4Z8slnX:bewx4p2) ([raw file](https://github.com/paranext/paranext-core/blob/9cc4d9d3dc6a49d33a45ea959713e5c663049d73/extensions/src/hello-someone/README.md#L5)):*
> ```Markdown
> Simple hello someone extension for Platform.Bible
> 
>

**Review by tjcouch-sil — APPROVED** [review]
:lgtm:

What do you mean by "note updating `sass` to v1.78.4 kills `npm start`"?

> Reviewed 38 of 38 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/1197#-:-O8N0e8xDr3VIr3ohBgA:b-gy7i8d)* status: all files reviewed, 1 unresolved discussion (waiting on @lyonsil)

___
*[`extensions/src/hello-someone/README.md` line 5 at r1](https://reviewable.io/reviews/paranext/paranext-core/1197#-O8MjnIsDMwup4Z8slnW:-O8N-n2j0w0l914A918L:b-qnwvsq) ([raw file](https://github.com/paranext/paranext-core/blob/9cc4d9d3dc6a49d33a45ea959713e5c663049d73/extensions/src/hello-someone/README.md#L5)):*
<details><summary><i>Previously, lyonsil (Matt Lyons) wrote…</i></summary><blockquote>

If we're going to leave in these "Template Info" sections of the `README.md` files,, can we comment them out as suggested in the `Hide Template Info` section?
</blockquote></details>

Looks to me like it is :) also note there was a bug introduced to it during the hackathon where it doesn't comment out quite everything, but I have a commit fixing that in my template PR that will be merged soon

**Review by lyonsil — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/1197)* status: all files reviewed, 1 unresolved discussion (waiting on @irahopkinson)

___
*[`extensions/src/hello-someone/README.md` line 5 at r1](https://reviewable.io/reviews/paranext/paranext-core/1197#-O8MjnIsDMwup4Z8slnW:-O8Nk0hPAWW7VtqVJXXj:b-au9re4) ([raw file](https://github.com/paranext/paranext-core/blob/9cc4d9d3dc6a49d33a45ea959713e5c663049d73/extensions/src/hello-someone/README.md#L5)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

Looks to me like it is :) also note there was a bug introduced to it during the hackathon where it doesn't comment out quite everything, but I have a commit fixing that in my template PR that will be merged soon
</blockquote></details>

If you navigate to https://github.com/paranext/paranext-core/tree/security/extensions/src/hello-someone you'll see that it isn't commented out fully.

**Review by lyonsil — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/1197)* status: all files reviewed, 1 unresolved discussion (waiting on @irahopkinson)

___
*[`extensions/src/hello-someone/README.md` line 5 at r1](https://reviewable.io/reviews/paranext/paranext-core/1197#-O8MjnIsDMwup4Z8slnW:-O8NkRyu9yw_Nc9yR36r:byqolsa) ([raw file](https://github.com/paranext/paranext-core/blob/9cc4d9d3dc6a49d33a45ea959713e5c663049d73/extensions/src/hello-someone/README.md#L5)):*
<details><summary><i>Previously, lyonsil (Matt Lyons) wrote…</i></summary><blockquote>

If you navigate to https://github.com/paranext/paranext-core/tree/security/extensions/src/hello-someone you'll see that it isn't commented out fully.
</blockquote></details>

I guess maybe what I'm seeing is the bug you're talking about. But I guess even if that bug is fixed there will need to be a closing `-->` at the end of this block.

**Review by tjcouch-sil — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/1197)* status: all files reviewed, 1 unresolved discussion (waiting on @lyonsil)

___
*[`extensions/src/hello-someone/README.md` line 5 at r1](https://reviewable.io/reviews/paranext/paranext-core/1197#-O8MjnIsDMwup4Z8slnW:-O8Ns9I63t_WhOpUomsr:bcgwwvf) ([raw file](https://github.com/paranext/paranext-core/blob/9cc4d9d3dc6a49d33a45ea959713e5c663049d73/extensions/src/hello-someone/README.md#L5)):*
<details><summary><i>Previously, lyonsil (Matt Lyons) wrote…</i></summary><blockquote>

I guess maybe what I'm seeing is the bug you're talking about. But I guess even if that bug is fixed there will need to be a closing `-->` at the end of this block.
</blockquote></details>

I fixed the bug by replacing the `>` in the `-->` with a `&gt;` to make it not close the comment. The comment is multi-line, so it keeps going until it finds another `-->`, which is down at the end of the closing comment indicator:

```
<!-- Closing comment tag for Template Info Section -->
```

So it fully comments out the whole "Template Info" section.

**Review by lyonsil — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/1197)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

___
*[`extensions/src/hello-someone/README.md` line 5 at r1](https://reviewable.io/reviews/paranext/paranext-core/1197#-O8MjnIsDMwup4Z8slnW:-O8X8bgJAC9Cu_KMPpkf:b8vnxdl) ([raw file](https://github.com/paranext/paranext-core/blob/9cc4d9d3dc6a49d33a45ea959713e5c663049d73/extensions/src/hello-someone/README.md#L5)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

I fixed the bug by replacing the `>` in the `-->` with a `&gt;` to make it not close the comment. The comment is multi-line, so it keeps going until it finds another `-->`, which is down at the end of the closing comment indicator:

```
<!-- Closing comment tag for Template Info Section -->
```

So it fully comments out the whole "Template Info" section.
</blockquote></details>

I was thinking that XML comments were nested, but I'm wrong about that. The `<!--` at the start of the final line was throwing me off in addition to the bug.

**Pull request merged**
