### PR TITLE
Deduped `@emotion/react`

### LINKED ISSUE #594: Fix "@emotion/react" problem when using MUI in extensions
**Describe the bug**
When a standalone extension imports MUI directly and PAPI, the following warning is printed in the dev tools console when the extension's webviews are displayed:
```
You are loading @emotion/react when it is already loaded. Running multiple instances may cause problems. This can happen if multiple versions are used, or if multiple builds of the same version are used.
```

**To Reproduce**
The Psalms: Layer by Layer extension uses MUI, so you can just load that extension into the platform to see the problem.  Alternatively, include some MUI component in an existing, standalone extension and load it into the platform.

**Expected behavior**
We should not have any warnings or errors when an extension wants to use MUI components directly.

Here is a Discord thread discussion the topic: https://discord.com/channels/1064938364597436416/1165051606623080548

### PR DESCRIPTION
**Pull request by tjcouch-sil**
- Moved most of `platform-bible-react`'s `peerDependencies` to `dependencies` because that makes more sense
- Updated from templates

Resolves #594

- - -
This change is [Reviewable](https://reviewable.io/reviews/paranext/paranext-core/730)

### CODE REVIEW

**Review by irahopkinson — DISMISSED** [review]
:lgtm: I have 2 non-blocking questions.

> Reviewed 13 of 13 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/730#-:-NonZgKM9Pibz03tEheZ:b-1hb8s4)* status: all files reviewed, 2 unresolved discussions (waiting on @tjcouch-sil)

___
*[`extensions/package.json` line 57 at r1](https://reviewable.io/reviews/paranext/paranext-core/730#-NonWa-b13IHgERP3FaI:-NonWa-b13IHgERP3FaJ:bno2z5p) ([raw file](https://github.com/paranext/paranext-core/blob/43e60de25ac70896fa27a81f417f7157d832144a/extensions/package.json#L57)):*
> ```JSON
>     "glob": "^10.3.3",
>     "papi-dts": "file:../lib/papi-dts",
>     "platform-bible-react": "file:../lib/platform-bible-react",
> ```

I'm wondering why this is in `devDependencies` when extensions use the react components. Is that because any extension that uses a component will list it in its own `dependencies` (but they don't seem to)?



_Code quote:_
```JSON
platform-bible-react
```
___
*[`extensions/src/hello-someone/src/main.ts` line 264 at r1](https://reviewable.io/reviews/paranext/paranext-core/730#-NonXpIs2E4dX-G2ooFz:-NonXpIs2E4dX-G2ooG-:bwb2ey5) ([raw file](https://github.com/paranext/paranext-core/blob/43e60de25ac70896fa27a81f417f7157d832144a/extensions/src/hello-someone/src/main.ts#L264)):*
> ```XML
> };
> 
> const peopleWebViewType2 = 'helloSomeone.peopleViewer2';
> ```

BTW if this wasn't test code I'd have a problem with this added section of code using the name `people` when there are no people anywhere near. Is there a better word to use here?

**Comment by irahopkinson** [comment]
BTW if this got merged with a **Squash and merge** that would cleanup the repo a lot, but feel free to do what makes most sense to you.

**Review by tjcouch-sil — COMMENTED** [review]
I would love to do that, too. Unfortunately, howver, the way git does subtrees, it actually uses the commit descriptions to track where the subtrees are. As such, updating from templates must be done non-destructively :/ that's why there are `git-subtree-dir` and `git-subtree-split` lines all over the commits.

> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/730#-:-NoqoE0G8vzh10_xetl-:bwu7xyn)* status: 11 of 13 files reviewed, 1 unresolved discussion (waiting on @irahopkinson)

___
*[`extensions/package.json` line 57 at r1](https://reviewable.io/reviews/paranext/paranext-core/730#-NonWa-b13IHgERP3FaI:-NoqgyfvEciaViEu1uj-:bls6j9m) ([raw file](https://github.com/paranext/paranext-core/blob/43e60de25ac70896fa27a81f417f7157d832144a/extensions/package.json#L57)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

I'm wondering why this is in `devDependencies` when extensions use the react components. Is that because any extension that uses a component will list it in its own `dependencies` (but they don't seem to)?
</blockquote></details>

It's in `devDependencies` because we bundle it into each webview (unfortunately). If you remember, we don't currently have a way to apply the styles from this package when a webview imports it. #215 tracks this work.

npm does not install `devDependencies` of a package when you install that package. Since `platform-bible-react` is bundled into the distributed files and does not need to be present in the environment when "using" this extension, we put it in `devDependencies`.
___
*[`extensions/src/hello-someone/src/main.ts` line 264 at r1](https://reviewable.io/reviews/paranext/paranext-core/730#-NonXpIs2E4dX-G2ooFz:-Noqhu5x7d0W80xSGC60:b-pk5hm2) ([raw file](https://github.com/paranext/paranext-core/blob/43e60de25ac70896fa27a81f417f7157d832144a/extensions/src/hello-someone/src/main.ts#L264)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

BTW if this wasn't test code I'd have a problem with this added section of code using the name `people` when there are no people anywhere near. Is there a better word to use here?
</blockquote></details>

Ahh I just copied and pasted the other one 100% and didn't look at all. Changed.

**Review by lyonsil — APPROVED** [review]
> Reviewed 11 of 13 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/730)* status: all files reviewed, 1 unresolved discussion (waiting on @irahopkinson)

**Pull request merged**
