### PR TITLE
#448 Open resource viewer to selected project

### PR DESCRIPTION
**Pull request by tombogle**
This change is [Reviewable](https://reviewable.io/reviews/paranext/paranext-core/606)

### CODE REVIEW

**Review by tjcouch-sil — CHANGES_REQUESTED** [review]
Awesome! Thanks for the great work. Just a few things.

> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/606#-:-Ni5PJFUCbOm8k1c3jxG:bsy0wdg)* status: all files reviewed, 3 unresolved discussions (waiting on @tombogle)

___
*[`extensions/src/resource-viewer/resource-viewer.ts` line 99 at r1](https://reviewable.io/reviews/paranext/paranext-core/606#-Ni5OXvF8-baz539QdTf:-Ni5OXvF8-baz539QdTg:b-iyz9dd) ([raw file](https://github.com/paranext/paranext-core/blob/7d0c58756245a97d7f550352913070ad0f50f43a/extensions/src/resource-viewer/resource-viewer.ts#L99)):*
> ```XML
>   // if one already exists. The webview that already exists could have been created by anyone
>   // anywhere; it just has to match `webViewType`.
>   papi.webViews.getWebView(resourceWebViewType, undefined, { existingId: '?' });
> ```

We should remove this so the resource viewer doesn't always come up when you start. :)
___
*[`extensions/src/resource-viewer/resource-viewer.web-view.tsx` line 159 at r1](https://reviewable.io/reviews/paranext/paranext-core/606#-Ni5OzOT27xsf2wcLCHh:-Ni5OzOT27xsf2wcLCHi:b-2ld45g) ([raw file](https://github.com/paranext/paranext-core/blob/7d0c58756245a97d7f550352913070ad0f50f43a/extensions/src/resource-viewer/resource-viewer.web-view.tsx#L159)):*
> ```XML
>   useWebViewState,
> }: WebViewProps): JSX.Element {
>   logger.info('Preparing to display the Resource Viewer');
> ```

Maybe this can be removed now since there's another log with more info. Nice to have one for now so we can see what's up, but probably don't need both.
___
*[`src/renderer/components/platform-bible-menu.data.ts` line 24 at r1](https://reviewable.io/reviews/paranext/paranext-core/606#-Ni5P6xb-iKWLQtldzHx:-Ni5P6xb-iKWLQtldzHy:b-8m1eh6) ([raw file](https://github.com/paranext/paranext-core/blob/7d0c58756245a97d7f550352913070ad0f50f43a/src/renderer/components/platform-bible-menu.data.ts#L24)):*
> ```XML
>         },
>         {
>           name: 'Open Resource Viewer...',
> ```

I would have thought we would just put this command for the "Open" menu item for now, but I dunno. @lyonsil what do you think for the tech demo?

**Review by katherinejensen00 — DISMISSED** [review]
:lgtm:
I agree with the things TJ said, but he already said them so I will go ahead and approve it. Thanks for your good work on this!

> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/606#-:-Ni5Q9GkAgo1F3olQ-Xc:bp32p9e)* status: all files reviewed, 3 unresolved discussions (waiting on @tombogle)

**Review by tombogle — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/606)* status: 3 of 6 files reviewed, 2 unresolved discussions (waiting on @katherinejensen00 and @tjcouch-sil)

___
*[`extensions/src/resource-viewer/resource-viewer.ts` line 99 at r1](https://reviewable.io/reviews/paranext/paranext-core/606#-Ni5OXvF8-baz539QdTf:-Ni5Xf-eDEJfG4LgZBiF:b-896fix) ([raw file](https://github.com/paranext/paranext-core/blob/7d0c58756245a97d7f550352913070ad0f50f43a/extensions/src/resource-viewer/resource-viewer.ts#L99)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

We should remove this so the resource viewer doesn't always come up when you start. :)
</blockquote></details>

Done.

**Review by katherinejensen00 — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/606#-:-Ni5ZEX3-BO13IWaoxre:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @tjcouch-sil and @tombogle)

**Review by tjcouch-sil — APPROVED** [review]
Awesome! Thanks for the quick follow-up. Let's wait for Matt to chime in on menu items, then we can close this up.

> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/606#-:-Ni5Zmn29XzWHWUY_ZIa:bxclb6p)* status: all files reviewed, 1 unresolved discussion (waiting on @tombogle)

**Review by lyonsil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/606)* status: all files reviewed, 1 unresolved discussion (waiting on @tjcouch-sil)

___
*[`src/renderer/components/platform-bible-menu.data.ts` line 24 at r1](https://reviewable.io/reviews/paranext/paranext-core/606#-Ni5P6xb-iKWLQtldzHx:-Ni5ZutKAkGOwT4yAlHm:bc885t8) ([raw file](https://github.com/paranext/paranext-core/blob/7d0c58756245a97d7f550352913070ad0f50f43a/src/renderer/components/platform-bible-menu.data.ts#L24)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

I would have thought we would just put this command for the "Open" menu item for now, but I dunno. @lyonsil what do you think for the tech demo?
</blockquote></details>

For the tech demo, I like the extra text.  I'm going to verbally walking people through what I'm doing, and it's more obvious when I'm going to click on something that says "Open Resource Viewer" than if I click on something that says "Open".  Either would work.  It's just less I have to explain on the fly.

**Review by tjcouch-sil — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/606)* status: all files reviewed, 1 unresolved discussion (waiting on @lyonsil)

___
*[`src/renderer/components/platform-bible-menu.data.ts` line 24 at r1](https://reviewable.io/reviews/paranext/paranext-core/606#-Ni5P6xb-iKWLQtldzHx:-Ni5_IrXAaB0SaBN0SMP:b-soeg3m) ([raw file](https://github.com/paranext/paranext-core/blob/7d0c58756245a97d7f550352913070ad0f50f43a/src/renderer/components/platform-bible-menu.data.ts#L24)):*
<details><summary><i>Previously, lyonsil (Matt Lyons) wrote…</i></summary><blockquote>

For the tech demo, I like the extra text.  I'm going to verbally walking people through what I'm doing, and it's more obvious when I'm going to click on something that says "Open Resource Viewer" than if I click on something that says "Open".  Either would work.  It's just less I have to explain on the fly.
</blockquote></details>

The extra text sounds good. Thanks for waiting, Tom!

**Review by tjcouch-sil — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/606)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
