### PR TITLE
Update the icons with the new official icon. Removed pt-summit icon.

### PR DESCRIPTION
**Pull request by FoolRunning**
This change is [Reviewable](https://reviewable.io/reviews/paranext/paranext-core/414)

### CODE REVIEW

**Review by rolfheij-sil — APPROVED** [review]
That was fast, nice work!
Would it be a good idea to rename them to `pb-*`? I guess `pt` still refers to Paratext

> Reviewed 9 of 9 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/414#-:-Ndf9rL5EQDWSqyYUewT:b82k0jb)* status: all files reviewed, 2 unresolved discussions (waiting on @FoolRunning)

___
*[`assets-excluded/logo/pt-react.png` line 0 at r1](https://reviewable.io/reviews/paranext/paranext-core/414#-NdfAARe4osCQPLnSAG8:-NdfAARe4osCQPLnSAG9:be674hr) ([raw file](https://github.com/paranext/paranext-core/blob/01fd408041a8c19f283b10b751447a4b65157925/assets-excluded/logo/pt-react.png#L0)):*
The new image is smaller, is that okay?
It's 256*256 instead of 1024*1024
___
*[`c-sharp/icon.ico` line 0 at r1](https://reviewable.io/reviews/paranext/paranext-core/414#-NdfAbVe1aeMVxFk_iBB:-NdfAbVfCGNgY-U5zKab:bjohd47) ([raw file](https://github.com/paranext/paranext-core/blob/01fd408041a8c19f283b10b751447a4b65157925/c-sharp/icon.ico#L0)):*
This one is smaller too.
It's 256*256 instead of 1024*1024

**Review by FoolRunning — COMMENTED** [review]
Good point. I just removed the prefix.

> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/414#-:-NdfGVy183wVO6l0HKKf:bnfvf78)* status: 5 of 12 files reviewed, 2 unresolved discussions (waiting on @rolfheij-sil)

___
*[`c-sharp/icon.ico` line  at r1](https://reviewable.io/reviews/paranext/paranext-core/414#-NdfAbVe1aeMVxFk_iBB:-NdfAxzGDhwEJizsT4uX:b-ivk68s) ([raw file](https://github.com/paranext/paranext-core/blob/01fd408041a8c19f283b10b751447a4b65157925/c-sharp/icon.ico#L)):*
<details><summary><i>Previously, rolfheij-sil wrote…</i></summary><blockquote>

This one is smaller too.
It's 256*256 instead of 1024*1024
</blockquote></details>

256x256 is the biggest we have. That should be big enough (at least for now).
___
*[`assets-excluded/logo/pt-react.png` line  at r1](https://reviewable.io/reviews/paranext/paranext-core/414#-NdfAARe4osCQPLnSAG8:-NdfAqBt654izs01T2pI:b-ivk68s) ([raw file](https://github.com/paranext/paranext-core/blob/01fd408041a8c19f283b10b751447a4b65157925/assets-excluded/logo/pt-react.png#L)):*
<details><summary><i>Previously, rolfheij-sil wrote…</i></summary><blockquote>

The new image is smaller, is that okay?
It's 256*256 instead of 1024*1024
</blockquote></details>

256x256 is the biggest we have. That should be big enough (at least for now).

**Review by rolfheij-sil — APPROVED** [review]
:lgtm:

> Reviewed 7 of 7 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/414#-:-NdfVg2U2YLZoYsRk5En:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by irahopkinson — CHANGES_REQUESTED** [review]
> Reviewed 5 of 9 files at r1, 7 of 7 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/414)* status: all files reviewed, 2 unresolved discussions (waiting on @FoolRunning)

___
*[`assets/icon.svg` line 1 at r2](https://reviewable.io/reviews/paranext/paranext-core/414#-Ndfpu1F4cPnG4dkRPcC:-Ndfpu1F4cPnG4dkRPcD:b-kokws4) ([raw file](https://github.com/paranext/paranext-core/blob/60be436987d9c988c1340579e4678886b347b9f3/assets/icon.svg#L1)):*
> ```SVG
> <?xml version="1.0" encoding="UTF-8" standalone="no"?>
> ```

I think you will find this file gets used in production for the macOS release.
___
*[`c-sharp/icon.ico` line 0 at r2](https://reviewable.io/reviews/paranext/paranext-core/414#-NdfrrAvDutnHaFGzSvV:-NdfrrAvDutnHaFGzSvW:b-hrm2rv) ([raw file](https://github.com/paranext/paranext-core/blob/213159922967374d6f0e8b4016de4f7484f7ad01/c-sharp/icon.ico#L0)):*
Is this an `.ico` containing several different sizes (the same sizes contained int he old one)?

**Comment by irahopkinson** [comment]
*[`assets/icon.svg` line 1 at r2](https://reviewable.io/reviews/paranext/paranext-core/414#-Ndfpu1F4cPnG4dkRPcC:-NdgT3AZBMEJGaK_jyei:b-oewonm) ([raw file](https://github.com/paranext/paranext-core/blob/60be436987d9c988c1340579e4678886b347b9f3/assets/icon.svg#L1)):*
<details><summary><i>Previously, FoolRunning (Tim Steenwyk) wrote…</i></summary><blockquote>

I searched all files and could find no reference to any .svg file, but maybe I missed something?
</blockquote></details>

[electron-builder](https://github.com/electron-userland/electron-builder) doesn't refer to it directly - it just expects it to exist with that filename (I think you can specify it which, in hind-sight, would be a better setup to make it more obvious it's being used). However, I'm not remembering correctly and the file I'm thinking of is the `.icns` file (not this one). See https://www.electron.build/icons.

**Comment by irahopkinson** [comment]
*[`assets/icon.svg` line 1 at r2](https://reviewable.io/reviews/paranext/paranext-core/414#-Ndfpu1F4cPnG4dkRPcC:-Ne3rd4K-kvkDAx7zL1p:bc8xply) ([raw file](https://github.com/paranext/paranext-core/blob/60be436987d9c988c1340579e4678886b347b9f3/assets/icon.svg#L1)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

[electron-builder](https://github.com/electron-userland/electron-builder) doesn't refer to it directly - it just expects it to exist with that filename (I think you can specify it which, in hind-sight, would be a better setup to make it more obvious it's being used). However, I'm not remembering correctly and the file I'm thinking of is the `.icns` file (not this one). See https://www.electron.build/icons.
</blockquote></details>

We still might want to keep this file since it's the only format that we can use in a browser that doesn't need the different sizes cached. Perhaps move it into `assets-excluded` until it is used?

**Review by tjcouch-sil — APPROVED** [review]
:lgtm:

> Reviewed 5 of 9 files at r1, 7 of 7 files at r2, 8 of 8 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/414#-:-NfHnPb311rWvoiXimoj:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @FoolRunning and @irahopkinson)

**Review by irahopkinson — APPROVED** [review]
:lgtm:

The main window icon is lower res than the rest (panel icons) but we can fix that up as we go along rather than hold this up.

> Reviewed 8 of 8 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/414#-:-NfIU37gDUqmpVuiKrrI:b-gpn2fw)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
