### PR TITLE
Rework extensions folder to use `paranext-multi-extension-template`

### PR DESCRIPTION
**Pull request by tjcouch-sil**
Reworked `extensions` folder to use the multi-extension template. Primary changes:
- Each extension that uses TypeScript is now templated from the extension template. The files were restructured so the main file is now `src/main.ts` and all code is now in `src` under the extension. The types are now in `src/types/<extension_name>.d.ts`. There are a bunch more files in each extension folder now, which pretty much only means the folder now supports opening it directly in VSCode and editing just the one extension (the files are there mainly because each extension is from the template now)
- Webpack now generates the main and types files in the same place in the dist folder to avoid great confusion
- There are a couple new npm scripts in `extensions` that help with making new extensions and updating from the template
- Moved `usxeditor` `devDependency` from inside `resource-viewer` up to `extensions` to make life easier since it doesn't really seem to provide much benefit to put it lower

More information on the templates can be found at https://github.com/paranext/paranext-multi-extension-template/pull/1 and https://github.com/paranext/paranext-extension-template/pull/55

- - -
This change is [Reviewable](https://reviewable.io/reviews/paranext/paranext-core/693)

### CODE REVIEW

**Review by rolfheij-sil — APPROVED** [review]
Great work! With so many files I couldn't do an in depth review, but I figure a lot of it was just moving files to a different location. I disabled auto-merge because I have some non-blocking questions, but I thought it would be wise to not merge immediately

> Reviewed 153 of 153 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/693#-:-NnJj17G5u7AAOXRAGJ8:b-fc0gep)* status: all files reviewed, 6 unresolved discussions (waiting on @tjcouch-sil)

___
*[`LICENSE` line 3 at r1](https://reviewable.io/reviews/paranext/paranext-core/693#-NnJXQj7D46KYOBCvRCW:-NnJXQj7D46KYOBCvRCX:bpu9ty4) ([raw file](https://github.com/paranext/paranext-core/blob/790e4a444b39a21bc63eca375c341d13ee4f3f4d/LICENSE#L3)):*
> ```
> MIT License
> 
> Copyright (c) 2022-2023 SIL International
> ```

2024 now? Or is this no longer relevant today?
___
*[`extensions/.stylelintrc.cjs` line 2 at r1](https://reviewable.io/reviews/paranext/paranext-core/693#-NnJXpfw2lCayXwRnXli:-NnJXpfx0C8VQkL82JJh:b910fss) ([raw file](https://github.com/paranext/paranext-core/blob/790e4a444b39a21bc63eca375c341d13ee4f3f4d/extensions/.stylelintrc.cjs#L2)):*
> ```JavaScript
> module.exports = {
>   extends: ['stylelint-config-recommended', 'stylelint-config-sass-guidelines'],
> ```

Since we're no longer using a central `stylelintrc`, should we add a comment that we want to keep the various `stylelint.rc`s in sync? Or is that not a necessity?
___
*[`extensions/LICENSE` line 3 at r1](https://reviewable.io/reviews/paranext/paranext-core/693#-NnJY3DjAq9FQEXWbPS1:-NnJY3DjAq9FQEXWbPS2:b-8k8812) ([raw file](https://github.com/paranext/paranext-core/blob/790e4a444b39a21bc63eca375c341d13ee4f3f4d/extensions/LICENSE#L3)):*
> ```
> MIT License
> 
> Copyright (c) 2022-2023 SIL International
> ```

2024?
___
*[`extensions/README.md` line 11 at r1](https://reviewable.io/reviews/paranext/paranext-core/693#-NnJYR2bEa6cuUro72HA:-NnJYR2cACxoTE1wEkYw:bf3zqad) ([raw file](https://github.com/paranext/paranext-core/blob/790e4a444b39a21bc63eca375c341d13ee4f3f4d/extensions/README.md#L11)):*
> ```Markdown
> - `src/` contains the source code for all extensions
>   - Each sub-folder in `src/` with a `manifest.json` in it is an extension
>     - `package.json` contains information about this extension's npm package. It is required for Platform.Bible to use the extension properly. It is copied into the build folder
> ```

I see we're starting to mix `paranext` and `platform.bible` now. For example, it still says `Paranext` at line 3. Do we already have a task to change all occurences of `paranext` to `platform.bible`? And update repo names etc?
___
*[`extensions/README.md` line 81 at r1](https://reviewable.io/reviews/paranext/paranext-core/693#-NnJYzux8fVyKHg4jFla:-NnJYzux8fVyKHg4jFlb:b6lhqql) ([raw file](https://github.com/paranext/paranext-core/blob/790e4a444b39a21bc63eca375c341d13ee4f3f4d/extensions/README.md#L81)):*
> ```Markdown
> ```
> 
> Then follow [the instructions for customizing the new extension](https://github.com/paranext/paranext-extension-template#customize-extension-details).
> ```

Just an idea: Can't we build some interactive script that prompts the user to provide a name for their extension, and maybe some additional info, and updates all files and filenames accordingly? Instead of our users having to go through these instructions and doing it by hand?
___
*[`lib/papi-dts/LICENSE` line 3 at r1](https://reviewable.io/reviews/paranext/paranext-core/693#-NnJirCR0rHyinqqw5Mw:-NnJirCR0rHyinqqw5Mx:b-n94koa) ([raw file](https://github.com/paranext/paranext-core/blob/790e4a444b39a21bc63eca375c341d13ee4f3f4d/lib/papi-dts/LICENSE#L3)):*
> ```
> MIT License
> 
> Copyright (c) 2022-2023 SIL International
> ```

Also, why is `present` not acceptable anymore?

**Review by tjcouch-sil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/693)* status: all files reviewed, 3 unresolved discussions (waiting on @rolfheij-sil)

___
*[`LICENSE` line 3 at r1](https://reviewable.io/reviews/paranext/paranext-core/693#-NnJXQj7D46KYOBCvRCW:-NnKRHqYAwJv3IaEdakz:bvodq8m) ([raw file](https://github.com/paranext/paranext-core/blob/790e4a444b39a21bc63eca375c341d13ee4f3f4d/LICENSE#L3)):*
<details><summary><i>Previously, rolfheij-sil wrote…</i></summary><blockquote>

2024 now? Or is this no longer relevant today?
</blockquote></details>

Aaaagh I didn't see that coming. Wrote this last year. Good catch
___
*[`extensions/.stylelintrc.cjs` line 2 at r1](https://reviewable.io/reviews/paranext/paranext-core/693#-NnJXpfw2lCayXwRnXli:-NnKb7Kr5lALENN17YlS:bo6p9xi) ([raw file](https://github.com/paranext/paranext-core/blob/790e4a444b39a21bc63eca375c341d13ee4f3f4d/extensions/.stylelintrc.cjs#L2)):*
<details><summary><i>Previously, rolfheij-sil wrote…</i></summary><blockquote>

Since we're no longer using a central `stylelintrc`, should we add a comment that we want to keep the various `stylelint.rc`s in sync? Or is that not a necessity?
</blockquote></details>

Good point; made some updates to the templates and will propagate them around via updating from template
___
*[`extensions/README.md` line 11 at r1](https://reviewable.io/reviews/paranext/paranext-core/693#-NnJYR2bEa6cuUro72HA:-NnKbGeUEaJbo4ZTi4EQ:bijbh9n) ([raw file](https://github.com/paranext/paranext-core/blob/790e4a444b39a21bc63eca375c341d13ee4f3f4d/extensions/README.md#L11)):*
<details><summary><i>Previously, rolfheij-sil wrote…</i></summary><blockquote>

I see we're starting to mix `paranext` and `platform.bible` now. For example, it still says `Paranext` at line 3. Do we already have a task to change all occurences of `paranext` to `platform.bible`? And update repo names etc?
</blockquote></details>

Indeed they are getting all mixed up. Ira asked me to change the occurrences in the templates when I was making the PRs for them, and they propagated over here. I honestly don't want to redo all of them throughout this repo right now; that would be a lot of work. We do have an issue for this: #481
___
*[`extensions/README.md` line 81 at r1](https://reviewable.io/reviews/paranext/paranext-core/693#-NnJYzux8fVyKHg4jFla:-NnKb_rA3JFWB7SBUT8P:b-f0tg18) ([raw file](https://github.com/paranext/paranext-core/blob/790e4a444b39a21bc63eca375c341d13ee4f3f4d/extensions/README.md#L81)):*
<details><summary><i>Previously, rolfheij-sil wrote…</i></summary><blockquote>

Just an idea: Can't we build some interactive script that prompts the user to provide a name for their extension, and maybe some additional info, and updates all files and filenames accordingly? Instead of our users having to go through these instructions and doing it by hand?
</blockquote></details>

Actually I thought about doing this too! Sounds really nice. But unfortunately it's more work than I cared to put into it for now. It seems it's actually not the simplest thing to get input from the command line in Node since it is built very carefully to prevent blocking the thread from running. Feel free to file an issue in the idea bucket if you'd like to see this one day :)
___
*[`lib/papi-dts/LICENSE` line 3 at r1](https://reviewable.io/reviews/paranext/paranext-core/693#-NnJirCR0rHyinqqw5Mw:-NnKbv7240L_Etqy6e2e:b-1g1kg3) ([raw file](https://github.com/paranext/paranext-core/blob/790e4a444b39a21bc63eca375c341d13ee4f3f4d/lib/papi-dts/LICENSE#L3)):*
<details><summary><i>Previously, rolfheij-sil wrote…</i></summary><blockquote>

Also, why is `present` not acceptable anymore?
</blockquote></details>

Matt and I discussed on one of the other PRs. Basically putting `present` is probably less meaningful for copyright statements than putting the most recent year you have worked on it since `present`  doesn't *really* mean anything particular. It's also not very conventional. I don't remember how `present` got there, but we decided to take it out.

**Review by lyonsil — DISMISSED** [review]
:lgtm: Thanks for dealing with the myriad of merges here, TJ.  I'm sure it wasn't your favorite programming task ever.

As Rolf said, this is a really big review, and lots of files are duplicates or near duplicates between the extensions.  I'm not doing an in depth review because of the amount of time required for what seems like relatively low payoff given that most of the code is coming from other things reviewed in the not too distant past.

What you have here does a good job at pulling together the extensions we already have into the new multi-extension template. As discussed in Discord a few weeks ago, I think there is a good chance people (us included) will gravitate over time to having "chunky" extensions rather than "lean" extensions.  That is, people will want to put more functionality into one extension to minimize the amount of near-duplication of files and merges when it comes to working with build files, dev tools, etc. that are configured for each extension.

> Reviewed 153 of 153 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/693#-:-NnKnzxv6QxMJsuiZAg8:blz484d)* status: all files reviewed, 3 unresolved discussions (waiting on @rolfheij-sil and @tjcouch-sil)

___
*[`extensions/README.md` line 81 at r1](https://reviewable.io/reviews/paranext/paranext-core/693#-NnJYzux8fVyKHg4jFla:-NnK9Tu35rJQslJNdJAk:bm80g2m) ([raw file](https://github.com/paranext/paranext-core/blob/790e4a444b39a21bc63eca375c341d13ee4f3f4d/extensions/README.md#L81)):*
<details><summary><i>Previously, rolfheij-sil wrote…</i></summary><blockquote>

Just an idea: Can't we build some interactive script that prompts the user to provide a name for their extension, and maybe some additional info, and updates all files and filenames accordingly? Instead of our users having to go through these instructions and doing it by hand?
</blockquote></details>

If we're going to go down that route, we'd probably want to consider doing something like [what VSCode does with yeoman](https://code.visualstudio.com/api/get-started/your-first-extension).

**Review by rolfheij-sil — DISMISSED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/693#-:-NnNrNzH0Rx9MtctYG0N:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @lyonsil and @tjcouch-sil)

___
*[`extensions/README.md` line 81 at r1](https://reviewable.io/reviews/paranext/paranext-core/693#-NnJYzux8fVyKHg4jFla:-NnNtQQv0IVjJpBS9b6Z:b-3tr49n) ([raw file](https://github.com/paranext/paranext-core/blob/790e4a444b39a21bc63eca375c341d13ee4f3f4d/extensions/README.md#L81)):*
<details><summary><i>Previously, lyonsil (Matt Lyons) wrote…</i></summary><blockquote>

If we're going to go down that route, we'd probably want to consider doing something like [what VSCode does with yeoman](https://code.visualstudio.com/api/get-started/your-first-extension).
</blockquote></details>

Created [695](https://github.com/paranext/paranext-core/issues/695)

**Review by tjcouch-sil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/693)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

___
*[`extensions/README.md` line 81 at r1](https://reviewable.io/reviews/paranext/paranext-core/693#-NnJYzux8fVyKHg4jFla:-NnP-WVH0ryoNqZcBILI:bxtkknm) ([raw file](https://github.com/paranext/paranext-core/blob/790e4a444b39a21bc63eca375c341d13ee4f3f4d/extensions/README.md#L81)):*
<details><summary><i>Previously, rolfheij-sil wrote…</i></summary><blockquote>

Created [695](https://github.com/paranext/paranext-core/issues/695)
</blockquote></details>

Thank you, Rolf!

**Review by rolfheij-sil — APPROVED** [review]
:lgtm:

> Reviewed 52 of 57 files at r2, 6 of 6 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/693#-:-NnPONswEaDQLwLmDv7K:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @tjcouch-sil)

___
*[`extensions/src/hello-someone/LICENSE` line 3 at r3](https://reviewable.io/reviews/paranext/paranext-core/693#-NnPOs4n6Gk2ue0H6G8O:-NnPOs4n6Gk2ue0H6G8P:bu613n0) ([raw file](https://github.com/paranext/paranext-core/blob/8a5f4eb1c91a5d7c1200ee98513f785860866a4f/extensions/src/hello-someone/LICENSE#L3)):*
> ```
> MIT License
> 
> Copyright (c) 2023-2024 SIL International
> ```

At a previous job we configured beautifier (which is an alternative to prettier) to automatically update these things when you'd apply your styling settings (i.e. on saving the file). Can we do something similar? Doing all these things by hand is very error prone and honestly I don't feel like searching for and manully updating numbers like these when I'm coding.

**Review by tjcouch-sil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/693)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

___
*[`extensions/src/hello-someone/LICENSE` line 3 at r3](https://reviewable.io/reviews/paranext/paranext-core/693#-NnPOs4n6Gk2ue0H6G8O:-NnPoXrhBPBKuJ_4GLRz:b-9rqolk) ([raw file](https://github.com/paranext/paranext-core/blob/8a5f4eb1c91a5d7c1200ee98513f785860866a4f/extensions/src/hello-someone/LICENSE#L3)):*
<details><summary><i>Previously, rolfheij-sil wrote…</i></summary><blockquote>

At a previous job we configured beautifier (which is an alternative to prettier) to automatically update these things when you'd apply your styling settings (i.e. on saving the file). Can we do something similar? Doing all these things by hand is very error prone and honestly I don't feel like searching for and manully updating numbers like these when I'm coding.
</blockquote></details>

Sounds pretty nice - might be worth filing an issue ;) I'm going to resolve this for the sake of getting the PR in, but feel free to continue the conversation

**Pull request merged**
