### PR TITLE
Add a placeholder overview page to Storybook

### PR DESCRIPTION
**Pull request by merchako**
Add a new **Intro** page to Storybook. This does not describe a specific component—the first of it's kind. 

Screenshot 2024-01-23 at 5 38 34 PM

Goals of this PR
* Example standalone Storybook page to practice and show others
* My first PR in this repo. I needed to fix some setup issues.

- - -
This change is [Reviewable](https://reviewable.io/reviews/paranext/paranext-core/732)

### CODE REVIEW

**Review by tjcouch-sil — APPROVED** [review]
Looks good. Thanks for doing this! I will say I am not really much of a fan of embedding code into a markdown document like mdx, but I guess it doesn't really matter much right now; whatever works. It seems to me that mdx is hard to maintain and is not as well supported as a full tsx file.

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/732#-:-NosmSgaDRIEWi9vInpv:bb9uf2)* status: all files reviewed, 2 unresolved discussions (waiting on @merchako)

___
*[`src/stories/Intro.mdx` line 7 at r1](https://reviewable.io/reviews/paranext/paranext-core/732#-NoslhIk0eYTrohGqTEz:-NoslhIk0eYTrohGqTF-:br7aiak) ([raw file](https://github.com/paranext/paranext-core/blob/7087ded41478c49f4697e3451d72c6ab6cfe3bb3/src/stories/Intro.mdx#L7)):*
> ```MDX
> Welcome to the Bible Platform Design System. This system serves as the cornerstone for crafting seamless, intuitive, and inclusive Bible translation apps. We've rooted our design philosophy in these core: expansive and extensible, open, cooperative, and opportunity-focused. The design choices, from shapes to colors, reflect these principles.
> 
> This Design System is created and maintained by the Paratext UX Team. It is an early draft not ready to be distributed or used as a reference. In case of questions or comments you may contact us through the [UX channel](https://discord.com/channels/1064938364597436416/1082713526780575845) on the Platform.Bible Discord server.
> ```

Should this be "Platform.Bible UX Team"? Feel free to resolve if not; I dunno the current state of all this kind of stuff
___
*[`src/stories/Intro.mdx` line 84 at r1](https://reviewable.io/reviews/paranext/paranext-core/732#-NosmJZL3RbAvhKWgMxl:-NosmJZL3RbAvhKWgMxm:bc4948j) ([raw file](https://github.com/paranext/paranext-core/blob/7087ded41478c49f4697e3451d72c6ab6cfe3bb3/src/stories/Intro.mdx#L84)):*
> ```MDX
> ```
> 
> ```jsx
> ```

Should this be `typescript` or `tsx`?

**Review by tjcouch-sil — DISMISSED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/732)* status: all files reviewed, 1 unresolved discussion (waiting on @merchako)

___
*[`src/stories/Intro.mdx` line 84 at r1](https://reviewable.io/reviews/paranext/paranext-core/732#-NosmJZL3RbAvhKWgMxl:-Now0u12BKae7jZQPFZh:b-ucfknh) ([raw file](https://github.com/paranext/paranext-core/blob/7087ded41478c49f4697e3451d72c6ab6cfe3bb3/src/stories/Intro.mdx#L84)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

Should this be `typescript` or `tsx`?
</blockquote></details>

Thanks!

**Comment by merchako** [comment]
Thanks for the review, @tjcouch-sil 

> not really much of a fan of embedding code into a markdown document

I'd like to hear more about this stance; it's the first I've heard it. 

As far as I can tell, TS(X) is the primary file format for Storybook Stories using [Autodocs](https://storybook.js.org/docs/writing-docs/autodocs).  is the recommended file format for Storybook these days, with [MDX](https://storybook.js.org/docs/writing-docs/mdx) and Docs blocks being options for extending. I chose an MDX file here because this file isn't associated with a component. I'm also exploring how I might enable non-coding designers to make (relatively) direct contributions to Storybook as a shared Source of truth, and Markdown was way more approachable than Typescript. I'm still learning about the pros and cons of that approach.

**Comment by merchako** [comment]
Should I be merging this commit myself? Who takes the next step?

**Review by Sebastian-ubs — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/732)* status: all files reviewed, 2 unresolved discussions (waiting on @merchako)

___
*[`src/stories/Intro.mdx` line 1 at r2](https://reviewable.io/reviews/paranext/paranext-core/732#-Np-GuyF4gOP2S_HLpQ9:-Np-GuyF4gOP2S_HLpQA:b-3s3dj1) ([raw file](https://github.com/paranext/paranext-core/blob/0bf5cfedbd25c981edfb363bfa7505108f496672/src/stories/Intro.mdx#L1)):*
> ```MDX
> Building a design system for a Bible translation app for an organization such as SIL requires a deep understanding of the organization's values, mission, and the people who will be using the system. Below is a comprehensive plan for the design system, tailored to communicate our core values and help users interact with the app effectively.
> ```

when mentioning SIL we should also mention UBS

**Comment by merchako** [comment]
> when mentioning SIL we should also mention UBS

Right. This is placeholder just to see what it can look like. I fully intend to rewrite the entire page.

**Comment by merchako** [comment]
*[`src/stories/Intro.mdx` line 1 at r2](https://reviewable.io/reviews/paranext/paranext-core/732#-Np-GuyF4gOP2S_HLpQ9:-Np0BA0LEchsAb-gEwg8:b2s5jzc) ([raw file](https://github.com/paranext/paranext-core/blob/0bf5cfedbd25c981edfb363bfa7505108f496672/src/stories/Intro.mdx#L1)):*
<details><summary><i>Previously, Sebastian-ubs wrote…</i></summary><blockquote>

when mentioning SIL we should also mention UBS
</blockquote></details>

Done. Removed mention of organizations.

**Review by tjcouch-sil — APPROVED** [review]
:lgtm: Usually the work flow is that, once you have approval, you're welcome to merge your own stuff in. :)

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/732#-:-Np1GkjkANy54hayr5g6:b-h5matb)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Pull request merged**
