### PR TITLE
Adjust Extension Toggle

### PR DESCRIPTION
**Pull request by jolierabideau**
Changes:
- Separate extension card into its own element and use it in Toggle so that it's possible to create cards without `<Switch />` as action
- Add prop that puts an icon in the card
- Add prop that makes the cards appear in a gallery and not a list
- Show two lists in the tab to example a list without icons and gallery with icons.

- - -
This change is [Reviewable](https://reviewable.io/reviews/paranext/paranext-core/417)

### CODE REVIEW

**Review by rolfheij-sil — CHANGES_REQUESTED** [review]
Nice work! This looks really good

> Reviewed 7 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/417#-:-Nei882n7CKAy9DvrlyM:bz1urde)* status: all files reviewed, 2 unresolved discussions (waiting on @jolierabideau)

___
*[`src/renderer/components/extension-manager/extension-card.component.tsx` line 19 at r1](https://reviewable.io/reviews/paranext/paranext-core/417#-Nei0xf7Cqib5Zt4bex6:-Nei0xf7Cqib5Zt4bex7:b-twt1w2) ([raw file](https://github.com/paranext/paranext-core/blob/9091e43a0a4c321799fee215c1a268448d126c8a/src/renderer/components/extension-manager/extension-card.component.tsx#L19)):*
> ```XML
>    * Optional flag to set if you want an icon (Avatar) to appear for the extension
>    */
>   hasIcon?: boolean;
> ```

Wouldn't it make more sense to create an `icon` prop that can take an image, or a filepath to an image or whatever? And if this prop isn't provided, we can assume that the card has no icon
___
*[`src/renderer/components/extension-manager/extension-card.component.tsx` line 24 at r1](https://reviewable.io/reviews/paranext/paranext-core/417#-Nei1nMD2LSXQfrrcUNS:-Nei1nMD2LSXQfrrcUNT:bs90bp6) ([raw file](https://github.com/paranext/paranext-core/blob/9091e43a0a4c321799fee215c1a268448d126c8a/src/renderer/components/extension-manager/extension-card.component.tsx#L24)):*
> ```XML
>    * Content to provide for a header action that appears in the top right of the Card
>    */
>   headerAction?: ReactNode;
> ```

I don't think this is used right now. ExtensionToggle doesn't seem to connect to this prop. Do we want to keep it? If so we should drill the prop up to the ExtensionManagerTab level, right?

**Review by jolierabideau — COMMENTED** [review]
Thank you! And thank you for your review

> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/417#-:-Nemb-nY-OzOEhIeacD1:bz119fv)* status: all files reviewed, 2 unresolved discussions (waiting on @rolfheij-sil)

___
*[`src/renderer/components/extension-manager/extension-card.component.tsx` line 19 at r1](https://reviewable.io/reviews/paranext/paranext-core/417#-Nei0xf7Cqib5Zt4bex6:-NeixgbXD3PKKbUpBmaq:b-p8t5sq) ([raw file](https://github.com/paranext/paranext-core/blob/9091e43a0a4c321799fee215c1a268448d126c8a/src/renderer/components/extension-manager/extension-card.component.tsx#L19)):*
<details><summary><i>Previously, rolfheij-sil wrote…</i></summary><blockquote>

Wouldn't it make more sense to create an `icon` prop that can take an image, or a filepath to an image or whatever? And if this prop isn't provided, we can assume that the card has no icon
</blockquote></details>

That does make sense, but it could be possible that sometimes we don't want icons on all cards for a specific list? I kind of remedied this by adding a `hasIcons` prop to the list and a `iconFilePath` prop to the `ExtensionCard`, and the two communicate. The `<Avatar>` is only produced if `iconFilePath` is defined (this is still a stub of sorts so this is something that can be fine tuned later when the behavior of icons is defined). If you think it would be better to stick with just the `icon` prop I can do that as well.
___
*[`src/renderer/components/extension-manager/extension-card.component.tsx` line 24 at r1](https://reviewable.io/reviews/paranext/paranext-core/417#-Nei1nMD2LSXQfrrcUNS:-Nemjsf6C4b4q-wDNrGf:bnez28g) ([raw file](https://github.com/paranext/paranext-core/blob/9091e43a0a4c321799fee215c1a268448d126c8a/src/renderer/components/extension-manager/extension-card.component.tsx#L24)):*
<details><summary><i>Previously, rolfheij-sil wrote…</i></summary><blockquote>

I don't think this is used right now. ExtensionToggle doesn't seem to connect to this prop. Do we want to keep it? If so we should drill the prop up to the ExtensionManagerTab level, right?
</blockquote></details>

I think we should keep it because some mockups I've seen from UX show we might want to use it later. For now, I moved it up and added a button in the gallery example.

**Review by rolfheij-sil — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/417)* status: all files reviewed, 2 unresolved discussions (waiting on @jolierabideau)

___
*[`src/renderer/components/extension-manager/extension-card.component.tsx` line 19 at r1](https://reviewable.io/reviews/paranext/paranext-core/417#-Nei0xf7Cqib5Zt4bex6:-Nes5e34BlE_UGJ8pzTt:b55f6ek) ([raw file](https://github.com/paranext/paranext-core/blob/9091e43a0a4c321799fee215c1a268448d126c8a/src/renderer/components/extension-manager/extension-card.component.tsx#L19)):*
<details><summary><i>Previously, jolierabideau wrote…</i></summary><blockquote>

That does make sense, but it could be possible that sometimes we don't want icons on all cards for a specific list? I kind of remedied this by adding a `hasIcons` prop to the list and a `iconFilePath` prop to the `ExtensionCard`, and the two communicate. The `<Avatar>` is only produced if `iconFilePath` is defined (this is still a stub of sorts so this is something that can be fine tuned later when the behavior of icons is defined). If you think it would be better to stick with just the `icon` prop I can do that as well.
</blockquote></details>

Ah yes, I think I get what your saying.
Maybe this would be good behavior:
- The list controls if avatars are shown or not, with the `hasIcons` prop
- The card has the `iconFilePath` that can be used to get the desired icon.
- If `iconFilePath` is not set, and avatar is generated using the 1st letter of the extension name.
___
*[`src/renderer/components/extension-manager/extension-list.component.tsx` line 31 at r2](https://reviewable.io/reviews/paranext/paranext-core/417#-Nes6oRZ9NxQ5ILJRqD5:-Nes6oRZ9NxQ5ILJRqD6:b-1kozuj) ([raw file](https://github.com/paranext/paranext-core/blob/5bd95399c9a93070bedc4824d0b653a568331c66/src/renderer/components/extension-manager/extension-list.component.tsx#L31)):*
> ```XML
>    * File path to the extensions icon
>    */
>   filePath?: string;
> ```

Is this just used for the icon? If so, maybe better to name it `iconFilePath` too?

**Review by jolierabideau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/417)* status: all files reviewed, 2 unresolved discussions (waiting on @rolfheij-sil)

___
*[`src/renderer/components/extension-manager/extension-card.component.tsx` line 19 at r1](https://reviewable.io/reviews/paranext/paranext-core/417#-Nei0xf7Cqib5Zt4bex6:-NesGljl0Bb6D7VnQWf6:by29tmp) ([raw file](https://github.com/paranext/paranext-core/blob/9091e43a0a4c321799fee215c1a268448d126c8a/src/renderer/components/extension-manager/extension-card.component.tsx#L19)):*
<details><summary><i>Previously, rolfheij-sil wrote…</i></summary><blockquote>

Ah yes, I think I get what your saying.
Maybe this would be good behavior:
- The list controls if avatars are shown or not, with the `hasIcons` prop
- The card has the `iconFilePath` that can be used to get the desired icon.
- If `iconFilePath` is not set, and avatar is generated using the 1st letter of the extension name.
</blockquote></details>

Sounds good! Fixed
___
*[`src/renderer/components/extension-manager/extension-list.component.tsx` line 31 at r2](https://reviewable.io/reviews/paranext/paranext-core/417#-Nes6oRZ9NxQ5ILJRqD5:-NesGh0A1Ifc30PxPkqj:b25841t) ([raw file](https://github.com/paranext/paranext-core/blob/5bd95399c9a93070bedc4824d0b653a568331c66/src/renderer/components/extension-manager/extension-list.component.tsx#L31)):*
<details><summary><i>Previously, rolfheij-sil wrote…</i></summary><blockquote>

Is this just used for the icon? If so, maybe better to name it `iconFilePath` too?
</blockquote></details>

Yes it is. Fixed

**Review by rolfheij-sil — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/417#-:-NevsJJk8m_nRw5B1-lC:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
