### PR TITLE
Add web view state service and corresponding React hook

### PR DESCRIPTION
**Pull request by lyonsil**
This change is [Reviewable](https://reviewable.io/reviews/paranext/paranext-core/545)

### CODE REVIEW

**Review by tjcouch-sil — CHANGES_REQUESTED** [review]
Wow!! Thanks for all the hard work on this! I really appreciate it. Looking forward to having this in! We're so close to being able to open a selected project in the resource viewer!!

> Reviewed 9 of 9 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/545#-:-NgZP5qa2LoNdBhl56Wm:b5nln8h)* status: all files reviewed, 8 unresolved discussions (waiting on @lyonsil)

___
*[`src/renderer/hooks/papi-hooks/use-webview-state.ts` line 4 at r1](https://reviewable.io/reviews/paranext/paranext-core/545#-NgZB__FDqh9icfQlnzP:-NgZB__FDqh9icfQlnzQ:bmyy2tz) ([raw file](https://github.com/paranext/paranext-core/blob/c3f35aa767e901d42c935da31f9176de90f9b676/src/renderer/hooks/papi-hooks/use-webview-state.ts#L4)):*
> ```XML
> 
> // See src/shared/global-this.model.ts for normal hook documentation
> // We don't add this to PAPI directly like other hooks because `this` has to be bound to a web view's iframe context
> ```

Since this doesn't go on the `papi`, I wonder if we should move it up a folder so people don't get confused and add it into the papi-exposed hooks on accident. No big deal either way.
___
*[`src/renderer/hooks/papi-hooks/use-webview-state.ts` line 5 at r1](https://reviewable.io/reviews/paranext/paranext-core/545#-NgZKVfZ6Jd3QmtAMd6S:-NgZKVfZ6Jd3QmtAMd6T:bwwqtxh) ([raw file](https://github.com/paranext/paranext-core/blob/c3f35aa767e901d42c935da31f9176de90f9b676/src/renderer/hooks/papi-hooks/use-webview-state.ts#L5)):*
> ```XML
> // See src/shared/global-this.model.ts for normal hook documentation
> // We don't add this to PAPI directly like other hooks because `this` has to be bound to a web view's iframe context
> export default function useWebViewState(
> ```

As it is currently coded, I believe the web view service and this hook don't support using the same key in two `useWebViewState` hooks in two different places. Probably not a problem right now, but it might be worth improving in the future. I made an issue https://github.com/paranext/paranext-core/issues/548 for it since it seems like we don't really need it right now.
___
*[`src/renderer/hooks/papi-hooks/use-webview-state.ts` line 12 at r1](https://reviewable.io/reviews/paranext/paranext-core/545#-NgZD2Fb5qThEhOYOXXb:-NgZD2Fb5qThEhOYOXXc:b681wae) ([raw file](https://github.com/paranext/paranext-core/blob/c3f35aa767e901d42c935da31f9176de90f9b676/src/renderer/hooks/papi-hooks/use-webview-state.ts#L12)):*
> ```XML
>   stateKey: string,
> ): [webViewState: string, setWebViewState: Dispatch<SetStateAction<string>>] {
>   const startingState: Record<string, string> = this.getWebViewState();
> ```

Because this is just a part of the function that is this hook, this will currently run every render. We could wrap this in a `useMemo` to make it only grab it once, but there is a more efficient way:

`useState` can take a function that returns the default state instead of just taking the default state itself, so I suggest this `this.getWebViewState` be moved into a function that is the argument for `useState`.

Do note, though, that `setState` only gets the initial value one time. You will also need a `useEffect` listening for changes to the `stateKey` that get the webview state again if the key changes. You can see an example of this in `useSetting`.
___
*[`src/renderer/hooks/papi-hooks/use-webview-state.ts` line 13 at r1](https://reviewable.io/reviews/paranext/paranext-core/545#-NgZDhHE5QPE4HJOKBUM:-NgZDhHE5QPE4HJOKBUN:b2fy4kh) ([raw file](https://github.com/paranext/paranext-core/blob/c3f35aa767e901d42c935da31f9176de90f9b676/src/renderer/hooks/papi-hooks/use-webview-state.ts#L13)):*
> ```XML
> ): [webViewState: string, setWebViewState: Dispatch<SetStateAction<string>>] {
>   const startingState: Record<string, string> = this.getWebViewState();
>   const [state, setState] = useState(startingState[stateKey] ?? '');
> ```

This hook should be generic to accept the type for the state and should accept a `defaultState` parameter (the generic type can be inferred from the `defaultState` type, so people won't need to enter it).

`useSetting` has a good model for grabbing the initial value from somewhere and then setting to `defaultState` if it doesn't exist.

(Note that I discussed making web view state generic in comments on `web-view-state.service.ts` which would enable this to use generics as well)
___
*[`src/renderer/hooks/papi-hooks/use-webview-state.ts` line 15 at r1](https://reviewable.io/reviews/paranext/paranext-core/545#-NgZEnFoE5GOOc01wLou:-NgZEnFoE5GOOc01wLov:bp1leqz) ([raw file](https://github.com/paranext/paranext-core/blob/c3f35aa767e901d42c935da31f9176de90f9b676/src/renderer/hooks/papi-hooks/use-webview-state.ts#L15)):*
> ```XML
>   const [state, setState] = useState(startingState[stateKey] ?? '');
>   // Whenever the webview state changes, save the updated value
>   useEffect(() => {
> ```

Putting this in a `useEffect` causes it to happen another render later and causes it to happen when it shouldn't (it will set the state if you change the `stateKey`, which shouldn't happen). The recommended way to do this is to middle-man the `setState` function and do whatever background updates are needed in that middle-man function. You can see this in `useSetting` with `setSettingInternal`  vs the `setSetting` that is returned.
___
*[`src/renderer/services/web-view-state.service.ts` line 13 at r1](https://reviewable.io/reviews/paranext/paranext-core/545#-NgZFatm-dwoObMpgTeX:-NgZFatm-dwoObMpgTeY:bb4o0o0) ([raw file](https://github.com/paranext/paranext-core/blob/c3f35aa767e901d42c935da31f9176de90f9b676/src/renderer/services/web-view-state.service.ts#L13)):*
> ```XML
> 
>   const entries = JSON.parse(serializedState) as [[string, Record<string, string>]];
>   entries.forEach((item) => {
> ```

Generally when you're looping through this type of entries, it is best to use `[key, value]` or something along those lines in place of the parameter `item` - basically destructuring the entry into its constituent parts. Then it's easier to read what's going on.

like `entries.forEach(([key, value]) => {`
___
*[`src/renderer/services/web-view-state.service.ts` line 40 at r1](https://reviewable.io/reviews/paranext/paranext-core/545#-NgZJLCvDeCj2uSSB_bI:-NgZJLCvDeCj2uSSB_bJ:b-tedwct) ([raw file](https://github.com/paranext/paranext-core/blob/c3f35aa767e901d42c935da31f9176de90f9b676/src/renderer/services/web-view-state.service.ts#L40)):*
> ```XML
> 
> /** Set the web view state object associated with the given ID
>  *  To avoid breaking references to existing state, call `getWebViewState` and modify the returned state object instead of setting a new state object
> ```

It took me a while to understand what this meant, and I could see people not implementing this correctly and getting problems. It makes me think these functions should probably also work with key/value pairs instead of web view state as a whole as it works in `useWebViewState`. I'd recommend going ahead and making that change now if that's ok since it would hopefully be a quick but very helpful change. It would also make https://github.com/paranext/paranext-core/issues/548 easier to do in the future (since it probably will require doing this work).

However, this could go in a follow-up issue if you don't want to do it that way. Let me know either way, and I can file an issue if you prefer (or maybe I'll just add it to https://github.com/paranext/paranext-core/issues/548)...?
___
*[`src/renderer/services/web-view-state.service.ts` line 42 at r1](https://reviewable.io/reviews/paranext/paranext-core/545#-NgZHI8bEKrAzKBt1JBM:-NgZHI8bEKrAzKBt1JBN:b-ur9owe) ([raw file](https://github.com/paranext/paranext-core/blob/c3f35aa767e901d42c935da31f9176de90f9b676/src/renderer/services/web-view-state.service.ts#L42)):*
> ```XML
>  *  To avoid breaking references to existing state, call `getWebViewState` and modify the returned state object instead of setting a new state object
>  */
> export function setWebViewState(id: string, state: Record<string, string>): void {
> ```

Imposing that all the values are strings seems to cause issues with using web view state. It seems you encountered some difficulties in the hello world web view with clicks, which naturally should have been a number. Based on the code in this service, it seems the only restriction on the value types is that they should be JSON stringifiable, which is practically implied at this point since we impose that almost everywhere (but it probably would be worth noting in the JSDocs for webview-state-related functions, but our documentation on this requirement is pretty spotty already and wouldn't be a big deal if it isn't mentioned here).

I think it would be best to make these functions generic and have the state be the generic type. Then you can say it must be an object and default to `Record<string, any>`. Something like this:

`function setWebViewState<TState extends object = Record<string, any>>(id: string, state: TState)`

Then that would enable the `useWebViewState` hook to do its generics as I mentioned in comments on that file (Of course, the function signature I suggested assumes you don't change these functions to use key/value pairs).
___
*[`src/shared/global-this.model.ts` line 36 at r1](https://reviewable.io/reviews/paranext/paranext-core/545#-NgZAn0V0IPrjAlnuwQd:-NgZAn0V0IPrjAlnuwQe:bndf5c4) ([raw file](https://github.com/paranext/paranext-core/blob/c3f35aa767e901d42c935da31f9176de90f9b676/src/shared/global-this.model.ts#L36)):*
> ```XML
>   var useWebViewState: (
>     stateKey: string,
>   ) => [webViewState: string, setWebViewState: Dispatch<SetStateAction<string>>];
> ```

We should add `getWebViewState` and `setWebViewState` here since they are exposed in the `imports` string in `web-view.service.ts` and may be used in WebView code, particularly if people want to use plain HTML webviews instead of React.

**Review by lyonsil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/545)* status: all files reviewed, 5 unresolved discussions (waiting on @tjcouch-sil)

___
*[`src/renderer/hooks/papi-hooks/use-webview-state.ts` line 4 at r1](https://reviewable.io/reviews/paranext/paranext-core/545#-NgZB__FDqh9icfQlnzP:-Ng_81ZI0ZS_ntoK9g1f:bb6un1j) ([raw file](https://github.com/paranext/paranext-core/blob/c3f35aa767e901d42c935da31f9176de90f9b676/src/renderer/hooks/papi-hooks/use-webview-state.ts#L4)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

Since this doesn't go on the `papi`, I wonder if we should move it up a folder so people don't get confused and add it into the papi-exposed hooks on accident. No big deal either way.
</blockquote></details>

Done
___
*[`src/renderer/hooks/papi-hooks/use-webview-state.ts` line 12 at r1](https://reviewable.io/reviews/paranext/paranext-core/545#-NgZD2Fb5qThEhOYOXXb:-Ng_Oajm6srSdGUhPgDQ:b-896fix) ([raw file](https://github.com/paranext/paranext-core/blob/c3f35aa767e901d42c935da31f9176de90f9b676/src/renderer/hooks/papi-hooks/use-webview-state.ts#L12)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

Because this is just a part of the function that is this hook, this will currently run every render. We could wrap this in a `useMemo` to make it only grab it once, but there is a more efficient way:

`useState` can take a function that returns the default state instead of just taking the default state itself, so I suggest this `this.getWebViewState` be moved into a function that is the argument for `useState`.

Do note, though, that `setState` only gets the initial value one time. You will also need a `useEffect` listening for changes to the `stateKey` that get the webview state again if the key changes. You can see an example of this in `useSetting`.
</blockquote></details>

Done.
___
*[`src/renderer/hooks/papi-hooks/use-webview-state.ts` line 13 at r1](https://reviewable.io/reviews/paranext/paranext-core/545#-NgZDhHE5QPE4HJOKBUM:-Ng_On_G-pqbKXizVSfd:b-896fix) ([raw file](https://github.com/paranext/paranext-core/blob/c3f35aa767e901d42c935da31f9176de90f9b676/src/renderer/hooks/papi-hooks/use-webview-state.ts#L13)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

This hook should be generic to accept the type for the state and should accept a `defaultState` parameter (the generic type can be inferred from the `defaultState` type, so people won't need to enter it).

`useSetting` has a good model for grabbing the initial value from somewhere and then setting to `defaultState` if it doesn't exist.

(Note that I discussed making web view state generic in comments on `web-view-state.service.ts` which would enable this to use generics as well)
</blockquote></details>

Done.
___
*[`src/renderer/hooks/papi-hooks/use-webview-state.ts` line 15 at r1](https://reviewable.io/reviews/paranext/paranext-core/545#-NgZEnFoE5GOOc01wLou:-Ng_UE782M_tOGdewo3H:buxm6qz) ([raw file](https://github.com/paranext/paranext-core/blob/c3f35aa767e901d42c935da31f9176de90f9b676/src/renderer/hooks/papi-hooks/use-webview-state.ts#L15)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

Putting this in a `useEffect` causes it to happen another render later and causes it to happen when it shouldn't (it will set the state if you change the `stateKey`, which shouldn't happen). The recommended way to do this is to middle-man the `setState` function and do whatever background updates are needed in that middle-man function. You can see this in `useSetting` with `setSettingInternal`  vs the `setSetting` that is returned.
</blockquote></details>

Everything seems to work properly with the code as it is.  If `stateKey` does change (which I agree shouldn't happen generally) then this probably should save to the new key, shouldn't it?

I see what is done in `useSetting`, but I don't see how adding another middle-man actually helps anything here.  It just seems like extra complexity.  That might be different if there was a subscription involved (as it in `useSetting`), but there isn't at this point.
___
*[`src/renderer/services/web-view-state.service.ts` line 13 at r1](https://reviewable.io/reviews/paranext/paranext-core/545#-NgZFatm-dwoObMpgTeX:-NgZ_7qzEiPESiYYd27x:bb6un1j) ([raw file](https://github.com/paranext/paranext-core/blob/c3f35aa767e901d42c935da31f9176de90f9b676/src/renderer/services/web-view-state.service.ts#L13)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

Generally when you're looping through this type of entries, it is best to use `[key, value]` or something along those lines in place of the parameter `item` - basically destructuring the entry into its constituent parts. Then it's easier to read what's going on.

like `entries.forEach(([key, value]) => {`
</blockquote></details>

Done
___
*[`src/renderer/services/web-view-state.service.ts` line 40 at r1](https://reviewable.io/reviews/paranext/paranext-core/545#-NgZJLCvDeCj2uSSB_bI:-NgZctxW0n0yC7zsc3rK:bb6un1j) ([raw file](https://github.com/paranext/paranext-core/blob/c3f35aa767e901d42c935da31f9176de90f9b676/src/renderer/services/web-view-state.service.ts#L40)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

It took me a while to understand what this meant, and I could see people not implementing this correctly and getting problems. It makes me think these functions should probably also work with key/value pairs instead of web view state as a whole as it works in `useWebViewState`. I'd recommend going ahead and making that change now if that's ok since it would hopefully be a quick but very helpful change. It would also make https://github.com/paranext/paranext-core/issues/548 easier to do in the future (since it probably will require doing this work).

However, this could go in a follow-up issue if you don't want to do it that way. Let me know either way, and I can file an issue if you prefer (or maybe I'll just add it to https://github.com/paranext/paranext-core/issues/548)...?
</blockquote></details>

Done
___
*[`src/renderer/services/web-view-state.service.ts` line 42 at r1](https://reviewable.io/reviews/paranext/paranext-core/545#-NgZHI8bEKrAzKBt1JBM:-NgZmmKZ20jjaI3LDMs1:bln0anv) ([raw file](https://github.com/paranext/paranext-core/blob/c3f35aa767e901d42c935da31f9176de90f9b676/src/renderer/services/web-view-state.service.ts#L42)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

Imposing that all the values are strings seems to cause issues with using web view state. It seems you encountered some difficulties in the hello world web view with clicks, which naturally should have been a number. Based on the code in this service, it seems the only restriction on the value types is that they should be JSON stringifiable, which is practically implied at this point since we impose that almost everywhere (but it probably would be worth noting in the JSDocs for webview-state-related functions, but our documentation on this requirement is pretty spotty already and wouldn't be a big deal if it isn't mentioned here).

I think it would be best to make these functions generic and have the state be the generic type. Then you can say it must be an object and default to `Record<string, any>`. Something like this:

`function setWebViewState<TState extends object = Record<string, any>>(id: string, state: TState)`

Then that would enable the `useWebViewState` hook to do its generics as I mentioned in comments on that file (Of course, the function signature I suggested assumes you don't change these functions to use key/value pairs).
</blockquote></details>

Made this generic
___
*[`src/shared/global-this.model.ts` line 36 at r1](https://reviewable.io/reviews/paranext/paranext-core/545#-NgZAn0V0IPrjAlnuwQd:-Ng_kuzhByK546DPbo87:b-o5fde1) ([raw file](https://github.com/paranext/paranext-core/blob/c3f35aa767e901d42c935da31f9176de90f9b676/src/shared/global-this.model.ts#L36)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

We should add `getWebViewState` and `setWebViewState` here since they are exposed in the `imports` string in `web-view.service.ts` and may be used in WebView code, particularly if people want to use plain HTML webviews instead of React.
</blockquote></details>

Done, but it doesn't make Intellisense work in the HTML web view code if that's what you had in mind.

**Review by tjcouch-sil — DISMISSED** [review]
Some more react stuff to look at, but we can just make a follow-up issue if you prefer :) thanks for all the hard work on this! Great revisions!!

> Reviewed 8 of 8 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/545#-:-Nga9mNk7i_RfrqJSgIP:b-susb1o)* status: :shipit: complete! all files reviewed, all discussions resolved

___
*[`src/renderer/services/web-view-state.service.ts` line 42 at r1](https://reviewable.io/reviews/paranext/paranext-core/545#-NgZHI8bEKrAzKBt1JBM:-Nga9glmCLgMAzP1PclF:b-ry3u02) ([raw file](https://github.com/paranext/paranext-core/blob/c3f35aa767e901d42c935da31f9176de90f9b676/src/renderer/services/web-view-state.service.ts#L42)):*
<details><summary><i>Previously, lyonsil (Matt Lyons) wrote…</i></summary><blockquote>

Made this generic
</blockquote></details>

Great!! Thank you :)
___
*[`src/shared/global-this.model.ts` line 36 at r1](https://reviewable.io/reviews/paranext/paranext-core/545#-NgZAn0V0IPrjAlnuwQd:-Nga0uGe8Qem43ijINxB:b-8e7wol) ([raw file](https://github.com/paranext/paranext-core/blob/c3f35aa767e901d42c935da31f9176de90f9b676/src/shared/global-this.model.ts#L36)):*
<details><summary><i>Previously, lyonsil (Matt Lyons) wrote…</i></summary><blockquote>

Done, but it doesn't make Intellisense work in the HTML web view code if that's what you had in mind.
</blockquote></details>

It appears you put them in `renderer/global-this.model.ts`, but that unfortunately doesn't get carried into `papi.d.ts`; just this one in `shared`. However, since HTML web views don't currently have TypeScript support, maybe we can just mention to make this fix in https://github.com/paranext/paranext-core/issues/492 (I went ahead and made a note). Anyone who wants to use webview state in a ts file can probably get by with the hook for the time being.
___
*[`src/renderer/hooks/papi-hooks/use-webview-state.ts` line 15 at r1](https://reviewable.io/reviews/paranext/paranext-core/545#-NgZEnFoE5GOOc01wLou:-Nga7h8T-MPhhiEkKRmN:b-vl1lg5) ([raw file](https://github.com/paranext/paranext-core/blob/c3f35aa767e901d42c935da31f9176de90f9b676/src/renderer/hooks/papi-hooks/use-webview-state.ts#L15)):*
<details><summary><i>Previously, lyonsil (Matt Lyons) wrote…</i></summary><blockquote>

Everything seems to work properly with the code as it is.  If `stateKey` does change (which I agree shouldn't happen generally) then this probably should save to the new key, shouldn't it?

I see what is done in `useSetting`, but I don't see how adding another middle-man actually helps anything here.  It just seems like extra complexity.  That might be different if there was a subscription involved (as it in `useSetting`), but there isn't at this point.
</blockquote></details>

Yes, saving new state when you set state works properly as-is. However, because of how the React rendering process works, `useEffect`s run during the render once you set state. They don't happen immediately when you set the state. They are less efficient than simply executing code in functions, and I think (not absolutely confident) there is room for things to change such that the effect doesn't even run (like the component unmounting) so we would lose saving that state.

[This section](https://react.dev/learn/you-might-not-need-an-effect#chains-of-computations) of the React docs about chaining computations pretty much explains what I'm talking about, but it's a lot more exaggerated than this situation.

I also expect we would get, not set, state when the stateKey changes. Turns out the hook is currently such that both happen in two different `useEffect`s, which is confusing. However, it's not the end of the world to have a little bug, so we can make an issue on this if you'd prefer not to make further changes.

**Review by irahopkinson — APPROVED** [review]
:lgtm:

> Reviewed 2 of 9 files at r1, 8 of 8 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/545#-:-NgaOKRCBuGUTGZ8OyT6:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by lyonsil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/545)* status: 9 of 10 files reviewed, all discussions resolved (waiting on @irahopkinson and @tjcouch-sil)

___
*[`src/shared/global-this.model.ts` line 36 at r1](https://reviewable.io/reviews/paranext/paranext-core/545#-NgZAn0V0IPrjAlnuwQd:-NgdXj83EDsWR3w1Pkk3:bch5u4d) ([raw file](https://github.com/paranext/paranext-core/blob/c3f35aa767e901d42c935da31f9176de90f9b676/src/shared/global-this.model.ts#L36)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

It appears you put them in `renderer/global-this.model.ts`, but that unfortunately doesn't get carried into `papi.d.ts`; just this one in `shared`. However, since HTML web views don't currently have TypeScript support, maybe we can just mention to make this fix in https://github.com/paranext/paranext-core/issues/492 (I went ahead and made a note). Anyone who wants to use webview state in a ts file can probably get by with the hook for the time being.
</blockquote></details>

You're right, that's my mistake.  I mixed up the two `global-this-model.ts` files.  Since it's mentioned in the ticket you referenced and HTML web views can't even use the types, I'll just let it be for now.
___
*[`src/renderer/hooks/papi-hooks/use-webview-state.ts` line 15 at r1](https://reviewable.io/reviews/paranext/paranext-core/545#-NgZEnFoE5GOOc01wLou:-NgdZBmf62NvL3oneKbC:bxfv3gn) ([raw file](https://github.com/paranext/paranext-core/blob/c3f35aa767e901d42c935da31f9176de90f9b676/src/renderer/hooks/papi-hooks/use-webview-state.ts#L15)):*
After pondering this a bit more, I'm going back to the previous version of this hook (except that I'm using your change for initialization).  The second `useEffect` isn't really needed and just makes things more complex.  This also aligns with [other](https://designcode.io/react-hooks-handbook-uselocalstorage-hook) [examples](https://blog.logrocket.com/using-localstorage-react-hooks/) online.  I know you made the following comment earlier, but I'm having a hard time seeing when/how this can happen and will cause a problem.  I tested with multiple calls to the hook, and the unique values are loading and being set properly.

> Do note, though, that `setState` only gets the initial value one time. You will also need a `useEffect` listening for changes to the `stateKey` that get the webview state again if the key changes. You can see an example of this in `useSetting`.

**Review by tjcouch-sil — APPROVED** [review]
Thanks for the hard work! So excited for this :)

> Reviewed 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/545#-:-NgeG7gF3dpPFjHsxbzg:b-659s3n)* status: :shipit: complete! all files reviewed, all discussions resolved

___
*[`src/shared/global-this.model.ts` line 36 at r1](https://reviewable.io/reviews/paranext/paranext-core/545#-NgZAn0V0IPrjAlnuwQd:-NgeDCn-0jK6I30iRMo9:b-da45st) ([raw file](https://github.com/paranext/paranext-core/blob/c3f35aa767e901d42c935da31f9176de90f9b676/src/shared/global-this.model.ts#L36)):*
<details><summary><i>Previously, lyonsil (Matt Lyons) wrote…</i></summary><blockquote>

You're right, that's my mistake.  I mixed up the two `global-this-model.ts` files.  Since it's mentioned in the ticket you referenced and HTML web views can't even use the types, I'll just let it be for now.
</blockquote></details>

Thanks for going ahead and moving it! Sorry to bother...

**Pull request merged**
