### PR TITLE
Remove unused mui components

### PR DESCRIPTION
**Pull request by rolfheij-sil**
This change is [Reviewable](https://reviewable.io/reviews/paranext/paranext-core/1156)

### CODE REVIEW

**Review by tjcouch-sil — COMMENTED** [review]
> Even now the axe is laid to the root of the trees.

A reckoning is upon us.

> Reviewed 16 of 16 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/1156#-:-O7jkKOz8VZGyF4Bpmx_:b-dmg9dm)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Review by tjcouch-sil — COMMENTED** [review]
> Reviewed 15 of 15 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/1156#-:-O7oKutY1enaKVl7yBUm:bli9js9)* status: all files reviewed, 1 unresolved discussion (waiting on @rolfheij-sil)

___
*[`extensions/src/hello-world/src/web-views/hello-world.web-view.tsx` line 257 at r2](https://reviewable.io/reviews/paranext/paranext-core/1156#-O7oJtmo3Fml1DYtzo-h:-O7oJtmo3Fml1DYtzo-i:b-oyujm3) ([raw file](https://github.com/paranext/paranext-core/blob/225f6ea1ca2f2467607c9fc0bfe40a7da964f29a/extensions/src/hello-world/src/web-views/hello-world.web-view.tsx#L257)):*
> ```XML
>       <div>
>         <TextField label="Test Me" />
>         <Checkbox /> {/* no label available */}
> ```

Is `title` available? That's the normal HTML field for tooltip. I don't know why it's called that. I also don't know what "label" used to do, so I dunno if I'm even close here

**Review by rolfheij-sil — COMMENTED** [review]
:joy: 

> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/1156#-:-O7oSrLg19k-Kt6uLtXM:bneqptx)* status: all files reviewed, 1 unresolved discussion (waiting on @tjcouch-sil)

___
*[`extensions/src/hello-world/src/web-views/hello-world.web-view.tsx` line 257 at r2](https://reviewable.io/reviews/paranext/paranext-core/1156#-O7oJtmo3Fml1DYtzo-h:-O7oStDlBq0WXtjYyNUw:b-w9f2ky) ([raw file](https://github.com/paranext/paranext-core/blob/225f6ea1ca2f2467607c9fc0bfe40a7da964f29a/extensions/src/hello-world/src/web-views/hello-world.web-view.tsx#L257)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

Is `title` available? That's the normal HTML field for tooltip. I don't know why it's called that. I also don't know what "label" used to do, so I dunno if I'm even close here
</blockquote></details>

The MUI checkbox used to have a text label attached to it, I think. The shadcn checkbox is just a checkbox.

**Review by tjcouch-sil — APPROVED** [review]
> Reviewed 5 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/1156)* status: all files reviewed, 1 unresolved discussion

**Review by tjcouch-sil — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/1156)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Review by tjcouch-sil — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/1156)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Pull request merged**
