### PR TITLE
Fix inconsistent spelling of papi namespaces

### PR DESCRIPTION
**Pull request by rolfheij-sil**
This change is [Reviewable](https://reviewable.io/reviews/paranext/paranext-core/648)

### CODE REVIEW

**Review by tjcouch-sil — CHANGES_REQUESTED** [review]
Awesome! Thanks for the thorough revision. This is great. Just one thing that needs to be adjusted for accuracy

> Reviewed 14 of 14 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/648#-:-NjgxHwg0oauQE4unLeU:bq7tx8y)* status: all files reviewed, 1 unresolved discussion (waiting on @rolfheij-sil)

___
*[`src/shared/services/graphql.service.ts` line 67 at r1](https://reviewable.io/reviews/paranext/paranext-core/648#-NjgwSYJ-jIR6GJNHozA:-NjgwSYJ-jIR6GJNHozB:b-pactgj) ([raw file](https://github.com/paranext/paranext-core/blob/eab64b92f087f3d1c78d6ec1981eae5ec710dd3a/src/shared/services/graphql.service.ts#L67)):*
> ```XML
>   const existingPdp = paratextProjectMap.get(projectId);
>   if (existingPdp) return { pdp: existingPdp, verseRef: parsedVerseRef };
>   const pdp = await get<'ParatextStandard'>('ParatextStandard', projectId);
> ```

Oops! Thanks for fixing this one that I missed. Side note: you can remove the `<'ParatextStandard'>` generic parameter specification now that you have it in the argument. But we don't need to; just fyi for future ease of use :)
___
*[`src/shared/services/project-data-provider.service.ts` line 117 at r1](https://reviewable.io/reviews/paranext/paranext-core/648#-NjgwoyW9I7xaxYSr-vX:-NjgwoyW9I7xaxYSr-vY:b6pdug9) ([raw file](https://github.com/paranext/paranext-core/blob/eab64b92f087f3d1c78d6ec1981eae5ec710dd3a/src/shared/services/project-data-provider.service.ts#L117)):*
> ```XML
>   if (projectType && projectType !== projectTypeFromMetadata)
>     logger.warn(
>       `Project type for project ${projectId} is ${projectTypeFromMetadata}, but the 'get' function on the ProjectDataProvider was run with mismatching projectType ${projectType}. This could cause issues`,
> ```

Unfortunately this is not correct. The mismatching project types here are from the PDP (`projectTypeFromMetadata`) and from what is put into this `papi.projectDataProviders.get` function as the first argument (`projectType`). The `get` function on the PDP has not been run yet. I recommend revising to something along these lines:

```typescript
`Project type for project ${projectId} is ${projectTypeFromMetadata}, but `papi.projectDataProviders.get` was run with mismatching projectType ${projectType}. This could cause issues`
```

**Review by lyonsil — DISMISSED** [review]
Looks good to me other than the things TJ pointed out.

> Reviewed 14 of 14 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/648#-:-NjiMetg1b7Qm5k5ekB3:bpuzvm1)* status: all files reviewed, 1 unresolved discussion (waiting on @rolfheij-sil)

**Review by rolfheij-sil — COMMENTED** [review]
Thanks guys!

> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/648#-:-NjlmmDY1wzf3I7kEhbN:b7n8lk7)* status: all files reviewed, 1 unresolved discussion (waiting on @tjcouch-sil)

___
*[`src/shared/services/graphql.service.ts` line 67 at r1](https://reviewable.io/reviews/paranext/paranext-core/648#-NjgwSYJ-jIR6GJNHozA:-NjlmytHCQzeP7JADn1H:bb6un1j) ([raw file](https://github.com/paranext/paranext-core/blob/eab64b92f087f3d1c78d6ec1981eae5ec710dd3a/src/shared/services/graphql.service.ts#L67)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

Oops! Thanks for fixing this one that I missed. Side note: you can remove the `<'ParatextStandard'>` generic parameter specification now that you have it in the argument. But we don't need to; just fyi for future ease of use :)
</blockquote></details>

Done
___
*[`src/shared/services/project-data-provider.service.ts` line 117 at r1](https://reviewable.io/reviews/paranext/paranext-core/648#-NjgwoyW9I7xaxYSr-vX:-NjlnDSB01qkRlt-1Aec:b-896fix) ([raw file](https://github.com/paranext/paranext-core/blob/eab64b92f087f3d1c78d6ec1981eae5ec710dd3a/src/shared/services/project-data-provider.service.ts#L117)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

Unfortunately this is not correct. The mismatching project types here are from the PDP (`projectTypeFromMetadata`) and from what is put into this `papi.projectDataProviders.get` function as the first argument (`projectType`). The `get` function on the PDP has not been run yet. I recommend revising to something along these lines:

```typescript
`Project type for project ${projectId} is ${projectTypeFromMetadata}, but `papi.projectDataProviders.get` was run with mismatching projectType ${projectType}. This could cause issues`
```
</blockquote></details>

Done.

**Review by tjcouch-sil — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/648#-:-NjmZShB-q1_HluzuXKF:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
