### PR TITLE
More C# tests and testing framework

### PR DESCRIPTION
**Pull request by FoolRunning**
- - -
This change is [Reviewable](https://reviewable.io/reviews/paranext/paranext-core/611)

### CODE REVIEW

**Review by tjcouch-sil — DISMISSED** [review]
:star_struck: :star_struck: :star_struck: :star_struck: This is awesome!! Thanks a ton for the great work on this!

> Reviewed 18 of 18 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/611#-:-NiBx8tc8W9SeDCMOskc:b-jd73b5)* status: all files reviewed, 1 unresolved discussion (waiting on @FoolRunning)

___
*[`c-sharp/Projects/ParatextProjectStorageInterpreter.cs` line 233 at r1](https://reviewable.io/reviews/paranext/paranext-core/611#-NiBxIlxDEvDTGUCHhKm:-NiBxIlxDEvDTGUCHhKn:b-cpdf1o) ([raw file](https://github.com/paranext/paranext-core/blob/3352805b27dadbdadfa6e6f760a08bcb2da8006e/c-sharp/Projects/ParatextProjectStorageInterpreter.cs#L233)):*
> ```Smalltalk
>         {
>             return scrText.FileManager.OpenFileForRead(
>                 $"extensions/{scope.ExtensionName}/{scope.DataQualifier}"
> ```

I don't mind this personally, and I don't remember what the arguments were either. I kinda feel like it might be good to use the same extensions folder as the folder Paratext uses for Plugins (I don't know what that is) since this is literally the "paratextFolders" storage type, but it's not necessarily something to do this issue.

Also, I think it would probably be nice to bump the project folder up one so there isn't `<short_name>_<project_id>/project/paratext/*stuff here*` anymore but just `<short_name>_<project_id>/project/*stuff here*` if we merge this change as you have done. Also not necessarily something that has to be done right this minute, but it would be a nice touch.
___
*[`c-sharp-tests/DummyScrLanguage.cs` line 11 at r1](https://reviewable.io/reviews/paranext/paranext-core/611#-NiBvgPa1Iv0AQEbxR8r:-NiBvgPbC6wM9-tOacuE:bz9kp58) ([raw file](https://github.com/paranext/paranext-core/blob/3352805b27dadbdadfa6e6f760a08bcb2da8006e/c-sharp-tests/DummyScrLanguage.cs#L11)):*
> ```Smalltalk
>     /// Replaces a ScrLanguage for use in testing. Does not use the file system to save/load data. 
>     /// </summary>
>     /// <remarks>Shamelessly copied from Paratext tests.</remarks>
> ```

For shaaaaame

/s

**Review by lyonsil — COMMENTED** [review]
Overall I think this is a good addition.  I am against moving the extensions folder into the Paratext directory, though, for reasons I mention further down.  Moving the extensions folder into the Paratext directory could work, but it creates the potential for a new class of problems in PT and P.B that we can completely avoid if we leave it where it is.

> Reviewed 18 of 18 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/611#-:-NiFp3GN7Krhxce-yL-A:b5era47)* status: all files reviewed, 7 unresolved discussions (waiting on @FoolRunning and @tjcouch-sil)

___
*[`c-sharp/Projects/ParatextProjectStorageInterpreter.cs` line 179 at r1](https://reviewable.io/reviews/paranext/paranext-core/611#-NiFPDkFCaQNdcphusC3:-NiFPDkFCaQNdcphusC4:b-r0npcz) ([raw file](https://github.com/paranext/paranext-core/blob/3352805b27dadbdadfa6e6f760a08bcb2da8006e/c-sharp/Projects/ParatextProjectStorageInterpreter.cs#L179)):*
> ```Smalltalk
>             return ResponseToRequest.Failed("Must provide a data qualifier");
> 
>         var dataStream = GetExtensionReader(scope);
> ```

With this refactor, it would be better to adjust this to be something like:
```c-sharp
using (var dataStream = GetExtensionReader(scope))
{
  return (dataStream == null)
      ? ResponseToRequest.Failed("Extension data not found")
      : ResponseToRequest.Succeeded(dataStream.ReadToEnd());
}
```

I probably should have done that before, but definitely now it makes more sense to be to scope the `using` block when the stream gets created.
___
*[`c-sharp/Projects/ParatextProjectStorageInterpreter.cs` line 196 at r1](https://reviewable.io/reviews/paranext/paranext-core/611#-NiFQig96HuvzaEWkv0n:-NiFQig96HuvzaEWkv0o:bt9ccxy) ([raw file](https://github.com/paranext/paranext-core/blob/3352805b27dadbdadfa6e6f760a08bcb2da8006e/c-sharp/Projects/ParatextProjectStorageInterpreter.cs#L196)):*
> ```Smalltalk
>             return ResponseToRequest.Failed("Must provide a data qualifier");
> 
>         var dataStream = GetExtensionWriter(scope);
> ```

Same as above, this should probably go into a `using` block.
___
*[`c-sharp/Projects/ParatextProjectStorageInterpreter.cs` line 200 at r1](https://reviewable.io/reviews/paranext/paranext-core/611#-NiFQpiPDwC1RqxFK-EY:-NiFQpiPDwC1RqxFK-EZ:b-yylsif) ([raw file](https://github.com/paranext/paranext-core/blob/d9f006cc8c2a483f4a88b8975be2763897bec406/c-sharp/Projects/ParatextProjectStorageInterpreter.cs#L200)):*
> ```Smalltalk
>                     if (!writeLock.Active)
>                         throw new Exception("Write lock is not active");
>                     dataStream.SetLength(0);
> ```

Why did you drop this?  If you don't do this, every write just append data to the end of the file instead of overwriting it.
___
*[`c-sharp/Projects/ParatextProjectStorageInterpreter.cs` line 233 at r1](https://reviewable.io/reviews/paranext/paranext-core/611#-NiBxIlxDEvDTGUCHhKm:-NiFmRWA21_uvUHQ-l4i:ba37mt3) ([raw file](https://github.com/paranext/paranext-core/blob/3352805b27dadbdadfa6e6f760a08bcb2da8006e/c-sharp/Projects/ParatextProjectStorageInterpreter.cs#L233)):*
We had a lot of back and forth on this in https://github.com/paranext/paranext-core/pull/427 and I think in meetings.  I think this is one of those times where we disagree with each other.

I think it's a very bad idea to insert new files or directories into another program's folder structure unless this is only ever going to be a one-way migration of projects (i.e., PT9 -> P.B).  Using the existing structure (i.e., the `pluginData` subdirectory) for our extensions is probably even worse than making a new subdirectory since Paratext may now or in the future try to parse the files there and have errors because they don't meet other implied requirements (e.g., naming structure, backing code for the given name, etc.)

From what Tim said in the other PR:
> Projects have a **pluginData** folder which contains folders for the plugins. Unfortunately, because of the way plugin unique identifiers were defined in Paratext, it usually looks double-nested (e.g. Transcelerator's directory is `{project}\pluginData\Transcelerator\Transcelerator`).

Are we trying to enforce whatever Transcelerator extension we'll have reads and writes the exact same data in the PT9 project in the same place?  What if the versions in PT and P.B don't match?

If we ever need to support shared projects that PT9 and P.B can both work on without a migration step, the safest choice is for P.B's extension data to live outside of the space that PT9 uses, and for PT9 to save plugin data somewhere that P.B ignores.  I can't think of a situation where having the extensions folder outside of the Paratext project directory can cause a problem with Paratext, but I can think of plenty where having it inside can cause problems.

Say that I build a house, and I know my brother uses it on the weekends.  Then one day I decide I want to remodel the family room, and he says "sorry, but you can't do that because I bought a couch that fits perfectly, and you can't change anything."

Core project data (i.e., the USFM files) needs to be interoperable between PT9 and P.B.  But extensions only ever make sense in P.B, and plugins only ever make sense in PT9.  PT "built the house", so it completely avoids the potential for their future changes to affect us if we keep our custom stuff outside of it.
___
*[`c-sharp-tests/PapiTestBase.cs` line 9 at r1](https://reviewable.io/reviews/paranext/paranext-core/611#-NiFUFcr0FYOYT_WKYyu:-NiFUFcr0FYOYT_WKYyv:b2v6qh) ([raw file](https://github.com/paranext/paranext-core/blob/3352805b27dadbdadfa6e6f760a08bcb2da8006e/c-sharp-tests/PapiTestBase.cs#L9)):*
> ```Smalltalk
> using Paratext.Data;
> using PtxUtils;
> using Newtonsoft.Json;
> ```

Putting `System.Text.Json` and `Newtonsoft.Json` into the same file can lead to unexpected behavior because they have identically named classes.  It would be better to pick one or the other for any given file.  Unfortunately they each are better at different things. :frowning: 
___
*[`c-sharp-tests/Projects/ParatextDataProviderTests.cs` line 45 at r1](https://reviewable.io/reviews/paranext/paranext-core/611#-NiFfjjq7gH-Fx_4hFL4:-NiFfjjq7gH-Fx_4hFL5:basuvwa) ([raw file](https://github.com/paranext/paranext-core/blob/3352805b27dadbdadfa6e6f760a08bcb2da8006e/c-sharp-tests/Projects/ParatextDataProviderTests.cs#L45)):*
> ```Smalltalk
>             Message result = Client.FakeMessageFromServer(new MessageRequest(requestType, requesterId, serverMessage)).First();
> 
>             // TODO: Handle this better
> ```

I think it would be sufficient to make sure the result is an error.  I don't think we need to verify the exact error message here.
___
*[`c-sharp-tests/Projects/ParatextProjectDataProviderFactoryTests.cs` line 54 at r1](https://reviewable.io/reviews/paranext/paranext-core/611#-NiFhnP87Jqy6AcbCFnC:-NiFhnP87Jqy6AcbCFnD:befv3si) ([raw file](https://github.com/paranext/paranext-core/blob/3352805b27dadbdadfa6e6f760a08bcb2da8006e/c-sharp-tests/Projects/ParatextProjectDataProviderFactoryTests.cs#L54)):*
> ```Smalltalk
>             Assert.That(result.Type, Is.EqualTo(MessageType.Response));
>             MessageResponse response = (MessageResponse)result;
>             Assert.That(response.ErrorMessage, Is.EqualTo("Not enough arguments provided when calling PDP Factory for ParatextStandard"));
> ```

Same as earlier - I don't know how important it is to check error messages when the wrong number of parameters are sent.  It's more important to make sure the response is a failure (i.e., "success" isn't provided and there is an error message).
___
*[`c-sharp-tests/Projects/ParatextProjectDataProviderFactoryTests.cs` line 65 at r1](https://reviewable.io/reviews/paranext/paranext-core/611#-NiFi54L-6S2uYv3eOpM:-NiFi54L-6S2uYv3eOpN:b-qgdrjv) ([raw file](https://github.com/paranext/paranext-core/blob/3352805b27dadbdadfa6e6f760a08bcb2da8006e/c-sharp-tests/Projects/ParatextProjectDataProviderFactoryTests.cs#L65)):*
> ```Smalltalk
>             const int requesterId = 47281;
> 
>             Projects.FakeAddProject(CreateProjectDetails(projId, "Monkey Soup"));
> ```

https://media.tenor.com/ngV9qFsFHrkAAAAC/monkey-brains-indiana-jones.gif

**Review by lyonsil — COMMENTED** [review]
Oh - this is probably failing on macOS because of the ICU problems.  Notice in `c-sharp/ParatextUtils/ParatextGlobals.cs` that `Initialize` returns immediately if you're on macOS.  You basically can't use `scrText` objects on macOS until we fix the ICU issue (and anything else behind it that we can't see because we trip up on that first).

We'll need to insert some sort of conditional check so we skip the new tests if we're on macOS.

> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/611#-:-NiFtgxj20Iy-10g85mW:b-ylsj12)* status: all files reviewed, 7 unresolved discussions (waiting on @FoolRunning and @tjcouch-sil)

**Review by tjcouch-sil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/611)* status: all files reviewed, 7 unresolved discussions (waiting on @FoolRunning and @lyonsil)

___
*[`c-sharp/Projects/ParatextProjectStorageInterpreter.cs` line 233 at r1](https://reviewable.io/reviews/paranext/paranext-core/611#-NiBxIlxDEvDTGUCHhKm:-NiFsQMRDGT1XMvCjaVa:bgzmrt6) ([raw file](https://github.com/paranext/paranext-core/blob/3352805b27dadbdadfa6e6f760a08bcb2da8006e/c-sharp/Projects/ParatextProjectStorageInterpreter.cs#L233)):*
<details><summary><i>Previously, lyonsil (Matt Lyons) wrote…</i></summary><blockquote>

We had a lot of back and forth on this in https://github.com/paranext/paranext-core/pull/427 and I think in meetings.  I think this is one of those times where we disagree with each other.

I think it's a very bad idea to insert new files or directories into another program's folder structure unless this is only ever going to be a one-way migration of projects (i.e., PT9 -> P.B).  Using the existing structure (i.e., the `pluginData` subdirectory) for our extensions is probably even worse than making a new subdirectory since Paratext may now or in the future try to parse the files there and have errors because they don't meet other implied requirements (e.g., naming structure, backing code for the given name, etc.)

From what Tim said in the other PR:
> Projects have a **pluginData** folder which contains folders for the plugins. Unfortunately, because of the way plugin unique identifiers were defined in Paratext, it usually looks double-nested (e.g. Transcelerator's directory is `{project}\pluginData\Transcelerator\Transcelerator`).

Are we trying to enforce whatever Transcelerator extension we'll have reads and writes the exact same data in the PT9 project in the same place?  What if the versions in PT and P.B don't match?

If we ever need to support shared projects that PT9 and P.B can both work on without a migration step, the safest choice is for P.B's extension data to live outside of the space that PT9 uses, and for PT9 to save plugin data somewhere that P.B ignores.  I can't think of a situation where having the extensions folder outside of the Paratext project directory can cause a problem with Paratext, but I can think of plenty where having it inside can cause problems.

Say that I build a house, and I know my brother uses it on the weekends.  Then one day I decide I want to remodel the family room, and he says "sorry, but you can't do that because I bought a couch that fits perfectly, and you can't change anything."

Core project data (i.e., the USFM files) needs to be interoperable between PT9 and P.B.  But extensions only ever make sense in P.B, and plugins only ever make sense in PT9.  PT "built the house", so it completely avoids the potential for their future changes to affect us if we keep our custom stuff outside of it.
</blockquote></details>

Yes, you have a good point. Using the existing plugin folder is probably a waste of effort and unhelpful. The point of having a PSI is that we can get stuff from wherever we like, so trying to match up plugins and extensions in the general case is probably at best a waste of effort and at worst quite destructive. Keeping them separate in the general case sounds good.

If we have a subfolder like this, though, I still think it would be nice to remove the `paratext` subdirectory ;)

I am beginning to wonder if we are having an argument without enough information about what this will look like long-term. It is almost guaranteed that we will have a conversion step when working with PT9 project data long-term, so I don't know that we will even need to have a "paratextFolders" PSI long-term. We will probably want a "paratext9Zipped" PSI (or something along those lines) so we can read from PT9 resources but not projects, but P.B extension data might not even be relevant in that case; it might be that resources can't have additional extension data anyway since they're a read-only zipped final package (so we would just have to make our extensions use the data in the `pluginData` folder as appropriate like with Transcelerator). Regardless, this is all stuff we haven't really quite worked out yet; I'm continually concerned more about whether we will be able to use `ScrText` at all if we change data model (or data source)... Maybe by the time we're done with #540, we will have a better idea what this will look like. Then we will be able to make a better-informed decision.
___
*[`c-sharp-tests/PapiTestBase.cs` line 9 at r1](https://reviewable.io/reviews/paranext/paranext-core/611#-NiFUFcr0FYOYT_WKYyu:-NiFvd1Q3oivg1kK5roG:b-wmtd1l) ([raw file](https://github.com/paranext/paranext-core/blob/3352805b27dadbdadfa6e6f760a08bcb2da8006e/c-sharp-tests/PapiTestBase.cs#L9)):*
<details><summary><i>Previously, lyonsil (Matt Lyons) wrote…</i></summary><blockquote>

Putting `System.Text.Json` and `Newtonsoft.Json` into the same file can lead to unexpected behavior because they have identically named classes.  It would be better to pick one or the other for any given file.  Unfortunately they each are better at different things. :frowning:
</blockquote></details>

Should we instead make our own class that handles JSON in whatever way we want it to from the two libraries inside it but then we use that class everywhere we want to touch JSON? Then we don't have to worry about being careful about which libraries we import where except in that one file.

**Review by lyonsil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/611)* status: all files reviewed, 7 unresolved discussions (waiting on @FoolRunning and @tjcouch-sil)

___
*[`c-sharp/Projects/ParatextProjectStorageInterpreter.cs` line 233 at r1](https://reviewable.io/reviews/paranext/paranext-core/611#-NiBxIlxDEvDTGUCHhKm:-NiG10Gw6c1piO2hsQ1_:bnl2l4e) ([raw file](https://github.com/paranext/paranext-core/blob/3352805b27dadbdadfa6e6f760a08bcb2da8006e/c-sharp/Projects/ParatextProjectStorageInterpreter.cs#L233)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

Yes, you have a good point. Using the existing plugin folder is probably a waste of effort and unhelpful. The point of having a PSI is that we can get stuff from wherever we like, so trying to match up plugins and extensions in the general case is probably at best a waste of effort and at worst quite destructive. Keeping them separate in the general case sounds good.

If we have a subfolder like this, though, I still think it would be nice to remove the `paratext` subdirectory ;)

I am beginning to wonder if we are having an argument without enough information about what this will look like long-term. It is almost guaranteed that we will have a conversion step when working with PT9 project data long-term, so I don't know that we will even need to have a "paratextFolders" PSI long-term. We will probably want a "paratext9Zipped" PSI (or something along those lines) so we can read from PT9 resources but not projects, but P.B extension data might not even be relevant in that case; it might be that resources can't have additional extension data anyway since they're a read-only zipped final package (so we would just have to make our extensions use the data in the `pluginData` folder as appropriate like with Transcelerator). Regardless, this is all stuff we haven't really quite worked out yet; I'm continually concerned more about whether we will be able to use `ScrText` at all if we change data model (or data source)... Maybe by the time we're done with #540, we will have a better idea what this will look like. Then we will be able to make a better-informed decision.
</blockquote></details>

Overall, keeping our extensions directory outside of the Paratext folder has nothing really to do with PSIs.  It's more about ownership.  In my view, we don't own a Paratext project directory.  If we start creating new files or subdirectories inside, we're muddying up the ownership.  Even though it might not cause a problem today, creating an extensions folder inside of something we don't own could cause a problem tomorrow or next week or next year.  If we keep it outside the Paratext folder, Paratext doesn't need to know about it, and it can't cause conflicts.  I recognize that odds are probably better than not that this wouldn't cause a problem, but it costs us nothing to keep it separate.  Why would we want to willingly take on some compatibility risk with PT if we don't need to?
___
*[`c-sharp-tests/PapiTestBase.cs` line 9 at r1](https://reviewable.io/reviews/paranext/paranext-core/611#-NiFUFcr0FYOYT_WKYyu:-NiG06lI-U8CpS97ZBHo:b7fwvju) ([raw file](https://github.com/paranext/paranext-core/blob/3352805b27dadbdadfa6e6f760a08bcb2da8006e/c-sharp-tests/PapiTestBase.cs#L9)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

Should we instead make our own class that handles JSON in whatever way we want it to from the two libraries inside it but then we use that class everywhere we want to touch JSON? Then we don't have to worry about being careful about which libraries we import where except in that one file.
</blockquote></details>

If we can rework the network protocol so we don't have to parse parts of messages multiple times, I think that will help just eliminate the need to pull in any JSON libraries in so many places.  I was kind of banking on that in the back of my head as something we'd want to do before/instead of reworking JSON handling in more places.

**Review by FoolRunning — COMMENTED** [review]
Ah! I forgot about that. I'll make the tests conditional.

> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/611#-:-Ni_TuUL3qex7REqWYEY:b167ajx)* status: all files reviewed, 7 unresolved discussions (waiting on @lyonsil)

___
*[`c-sharp/Projects/ParatextProjectStorageInterpreter.cs` line 179 at r1](https://reviewable.io/reviews/paranext/paranext-core/611#-NiFPDkFCaQNdcphusC3:-Ni_OBbk9lxXTJsn0knt:bctpdcc) ([raw file](https://github.com/paranext/paranext-core/blob/3352805b27dadbdadfa6e6f760a08bcb2da8006e/c-sharp/Projects/ParatextProjectStorageInterpreter.cs#L179)):*
<details><summary><i>Previously, lyonsil (Matt Lyons) wrote…</i></summary><blockquote>

With this refactor, it would be better to adjust this to be something like:
```c-sharp
using (var dataStream = GetExtensionReader(scope))
{
  return (dataStream == null)
      ? ResponseToRequest.Failed("Extension data not found")
      : ResponseToRequest.Succeeded(dataStream.ReadToEnd());
}
```

I probably should have done that before, but definitely now it makes more sense to be to scope the `using` block when the stream gets created.
</blockquote></details>

Makes sense. Done.
___
*[`c-sharp/Projects/ParatextProjectStorageInterpreter.cs` line 196 at r1](https://reviewable.io/reviews/paranext/paranext-core/611#-NiFQig96HuvzaEWkv0n:-Ni_OW-z-A5iP8yKunKu:b-896fix) ([raw file](https://github.com/paranext/paranext-core/blob/3352805b27dadbdadfa6e6f760a08bcb2da8006e/c-sharp/Projects/ParatextProjectStorageInterpreter.cs#L196)):*
<details><summary><i>Previously, lyonsil (Matt Lyons) wrote…</i></summary><blockquote>

Same as above, this should probably go into a `using` block.
</blockquote></details>

Done.
___
*[`c-sharp/Projects/ParatextProjectStorageInterpreter.cs` line 200 at r1](https://reviewable.io/reviews/paranext/paranext-core/611#-NiFQpiPDwC1RqxFK-EY:-Ni_OYsb5YEqHX4g8bsZ:busrjlp) ([raw file](https://github.com/paranext/paranext-core/blob/d9f006cc8c2a483f4a88b8975be2763897bec406/c-sharp/Projects/ParatextProjectStorageInterpreter.cs#L200)):*
<details><summary><i>Previously, lyonsil (Matt Lyons) wrote…</i></summary><blockquote>

Why did you drop this?  If you don't do this, every write just append data to the end of the file instead of overwriting it.
</blockquote></details>

When opening the file for writing, the TextWriter overwrites the full file and doesn't append (so it defaults to an empty file). TextWriter doesn't even have a way to do this without somehow getting the underlying stream.
And even for FileStreams, I think you have to specifically open it in append-mode for it to append.

Either way, I'm going to revert these changes, so it doesn't matter. 😁
___
*[`c-sharp/Projects/ParatextProjectStorageInterpreter.cs` line 233 at r1](https://reviewable.io/reviews/paranext/paranext-core/611#-NiBxIlxDEvDTGUCHhKm:-Ni_QbCx9RWoiuyEeNT7:b-xdzyil) ([raw file](https://github.com/paranext/paranext-core/blob/3352805b27dadbdadfa6e6f760a08bcb2da8006e/c-sharp/Projects/ParatextProjectStorageInterpreter.cs#L233)):*
<details><summary><i>Previously, lyonsil (Matt Lyons) wrote…</i></summary><blockquote>

Overall, keeping our extensions directory outside of the Paratext folder has nothing really to do with PSIs.  It's more about ownership.  In my view, we don't own a Paratext project directory.  If we start creating new files or subdirectories inside, we're muddying up the ownership.  Even though it might not cause a problem today, creating an extensions folder inside of something we don't own could cause a problem tomorrow or next week or next year.  If we keep it outside the Paratext folder, Paratext doesn't need to know about it, and it can't cause conflicts.  I recognize that odds are probably better than not that this wouldn't cause a problem, but it costs us nothing to keep it separate.  Why would we want to willingly take on some compatibility risk with PT if we don't need to?
</blockquote></details>

I'm just going to revert these changes (I made them in a separate commit so they'd be easy to revert). I did it this way since it was by far the easiest change to get the tests to work. I'll go the more-work route and get them working with the previous system.
___
*[`c-sharp-tests/PapiTestBase.cs` line 9 at r1](https://reviewable.io/reviews/paranext/paranext-core/611#-NiFUFcr0FYOYT_WKYyu:-Ni_RD8h5A__HPWIpMBM:b-ituq80) ([raw file](https://github.com/paranext/paranext-core/blob/3352805b27dadbdadfa6e6f760a08bcb2da8006e/c-sharp-tests/PapiTestBase.cs#L9)):*
<details><summary><i>Previously, lyonsil (Matt Lyons) wrote…</i></summary><blockquote>

If we can rework the network protocol so we don't have to parse parts of messages multiple times, I think that will help just eliminate the need to pull in any JSON libraries in so many places.  I was kind of banking on that in the back of my head as something we'd want to do before/instead of reworking JSON handling in more places.
</blockquote></details>

Newtonsoft.Json was only added for escaping a JSON string. I should be able to remove it (assuming .Net has a built-in way to escape JSON strings).
___
*[`c-sharp-tests/Projects/ParatextDataProviderTests.cs` line 45 at r1](https://reviewable.io/reviews/paranext/paranext-core/611#-NiFfjjq7gH-Fx_4hFL4:-Ni_T6os0dQxteRTWyJi:b-a6o0io) ([raw file](https://github.com/paranext/paranext-core/blob/3352805b27dadbdadfa6e6f760a08bcb2da8006e/c-sharp-tests/Projects/ParatextDataProviderTests.cs#L45)):*
<details><summary><i>Previously, lyonsil (Matt Lyons) wrote…</i></summary><blockquote>

I think it would be sufficient to make sure the result is an error.  I don't think we need to verify the exact error message here.
</blockquote></details>

See my comment below.
___
*[`c-sharp-tests/Projects/ParatextProjectDataProviderFactoryTests.cs` line 54 at r1](https://reviewable.io/reviews/paranext/paranext-core/611#-NiFhnP87Jqy6AcbCFnC:-Ni_Rvcm2WQ3a2Itqdpj:b19a3ua) ([raw file](https://github.com/paranext/paranext-core/blob/3352805b27dadbdadfa6e6f760a08bcb2da8006e/c-sharp-tests/Projects/ParatextProjectDataProviderFactoryTests.cs#L54)):*
<details><summary><i>Previously, lyonsil (Matt Lyons) wrote…</i></summary><blockquote>

Same as earlier - I don't know how important it is to check error messages when the wrong number of parameters are sent.  It's more important to make sure the response is a failure (i.e., "success" isn't provided and there is an error message).
</blockquote></details>

I mostly agree with you, but we've come across situations when working on Paratext where a bug was introduced that caused an unrelated error - so the tests still ended up passing, but if we had checked the error we'd have caught the new bug. If we had access to the exception itself, I would probably just check to make sure it's the correct type, but here all we get back is a message. Thus, I'd prefer to keep it as-is.

**Review by lyonsil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/611)* status: all files reviewed, 5 unresolved discussions

___
*[`c-sharp-tests/Projects/ParatextProjectDataProviderFactoryTests.cs` line 54 at r1](https://reviewable.io/reviews/paranext/paranext-core/611#-NiFhnP87Jqy6AcbCFnC:-Ni_WH9lAjLQML4_6rev:bov50jm) ([raw file](https://github.com/paranext/paranext-core/blob/3352805b27dadbdadfa6e6f760a08bcb2da8006e/c-sharp-tests/Projects/ParatextProjectDataProviderFactoryTests.cs#L54)):*
<details><summary><i>Previously, FoolRunning (Tim Steenwyk) wrote…</i></summary><blockquote>

I mostly agree with you, but we've come across situations when working on Paratext where a bug was introduced that caused an unrelated error - so the tests still ended up passing, but if we had checked the error we'd have caught the new bug. If we had access to the exception itself, I would probably just check to make sure it's the correct type, but here all we get back is a message. Thus, I'd prefer to keep it as-is.
</blockquote></details>

Ok - I don't feel strongly about this which is why I didn't make this comment blocking.  If/when the error message change we can always update the test at the same time.

**Review by tjcouch-sil — APPROVED** [review]
:lgtm: thanks for the hard work on this!

> Reviewed 7 of 7 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/611#-:-Niair0L3wV4JjaIvmQS:bcbj1ey)* status: all files reviewed, 5 unresolved discussions (waiting on @lyonsil)

**Review by lyonsil — APPROVED** [review]
:lgtm:

> Reviewed 7 of 7 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/611#-:-NiauIwLC2N2wLNE0dcO:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @FoolRunning)

___
*[`c-sharp/Projects/ParatextProjectStorageInterpreter.cs` line 200 at r1](https://reviewable.io/reviews/paranext/paranext-core/611#-NiFQpiPDwC1RqxFK-EY:-NiatQUs-owe3EGBr9el:b-f00sgl) ([raw file](https://github.com/paranext/paranext-core/blob/d9f006cc8c2a483f4a88b8975be2763897bec406/c-sharp/Projects/ParatextProjectStorageInterpreter.cs#L200)):*
<details><summary><i>Previously, FoolRunning (Tim Steenwyk) wrote…</i></summary><blockquote>

When opening the file for writing, the TextWriter overwrites the full file and doesn't append (so it defaults to an empty file). TextWriter doesn't even have a way to do this without somehow getting the underlying stream.
And even for FileStreams, I think you have to specifically open it in append-mode for it to append.

Either way, I'm going to revert these changes, so it doesn't matter. 😁
</blockquote></details>

When I was testing this out originally, it was always appending with this code unless I put the `SetLength` call in above.  :shrug: 
___
*[`c-sharp-tests/DummyParatextProjectStorageInterpreter.cs` line 9 at r2](https://reviewable.io/reviews/paranext/paranext-core/611#-Niatld07RHrAxBhGQqC:-Niatld07RHrAxBhGQqD:b-uffm09) ([raw file](https://github.com/paranext/paranext-core/blob/00f57904b4d864e4ed03883d62ad1dfb35fc3469/c-sharp-tests/DummyParatextProjectStorageInterpreter.cs#L9)):*
> ```Smalltalk
>     {
>         private readonly Dictionary<string, byte[]> _inMemoryFiles = new();
>         
> ```

Minor nit - for some reason I noticed here and one place lower down in this file there are a bunch of spaces instead of just a newline.  I'm not sure why something isn't erasing those.

**Pull request merged**
