### PR TITLE
Add Shadcn/ui and a new BCV-control

### PR DESCRIPTION
**Pull request by rolfheij-sil**
This change is [Reviewable](https://reviewable.io/reviews/paranext/paranext-core/858)

### CODE REVIEW

**Review by tjcouch-sil — COMMENTED** [review]
Wow! Awesome! Thanks for the great work on all this, guys! A couple blocking things that should be quick, then a number of follow-up items that would probably be best to take note of and fix after we get done with all this UX test stuff.

> Reviewed 51 of 57 files at r1, 6 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/858#-:-NvrHsX7CkFCj4-_bB8G:b-7jiafa)* status: all files reviewed, 12 unresolved discussions (waiting on @rolfheij-sil)

___
*[`package.json` line 198 at r2](https://reviewable.io/reviews/paranext/paranext-core/858#-Nvr4HZL6jsf1ol6OvIz:-Nvr4HZL6jsf1ol6OvJ-:b-275x2b) ([raw file](https://github.com/paranext/paranext-core/blob/09a9f3f007abb0ddb1f6fe05aa4284e851fe17fe/package.json#L198)):*
> ```JSON
>     "prettier": "^3.2.5",
>     "prettier-plugin-jsdoc": "^1.3.0",
>     "prettier-plugin-tailwindcss": "^0.5.13",
> ```

Could this (and its configuration) be placed instead in `lib/platform-bible-react`? For follow-up; not needed now
___
*[`lib/platform-bible-react/.eslintrc.cjs` line 10 at r2](https://reviewable.io/reviews/paranext/paranext-core/858#-Nvq_xFXE04_JmxsBoNi:-Nvq_xFXE04_JmxsBoNj:b-nq3qcs) ([raw file](https://github.com/paranext/paranext-core/blob/09a9f3f007abb0ddb1f6fe05aa4284e851fe17fe/lib/platform-bible-react/.eslintrc.cjs#L10)):*
> ```JavaScript
>   rules: {
>     'no-console': 'off',
>     'react/prop-types': [2, { ignore: ['className'] }],
> ```

What's up here? Do we need this? Would be glad to wait for a follow-up
___
*[`lib/platform-bible-react/src/components/book-chapter-control/book-chapter-control.component.tsx` line 33 at r2](https://reviewable.io/reviews/paranext/paranext-core/858#-NvrBsw4-3pLW8Tfau9y:-NvrBsw54-9avA92xi4Y:b-9cfol7) ([raw file](https://github.com/paranext/paranext-core/blob/09a9f3f007abb0ddb1f6fe05aa4284e851fe17fe/lib/platform-bible-react/src/components/book-chapter-control/book-chapter-control.component.tsx#L33)):*
> ```XML
> 
> function BookChapterControl({ scrRef, handleSubmit }: BookChapterControlProps) {
>   const { allBookIds } = Canon;
> ```

I believe this can come out of the function component. Can be follow-up
___
*[`lib/platform-bible-react/src/components/book-chapter-control/book-chapter-control.component.tsx` line 51 at r2](https://reviewable.io/reviews/paranext/paranext-core/858#-NvrC6NLAu8ZJEBlLL7p:-NvrC6NLAu8ZJEBlLL7q:b-9cfol7) ([raw file](https://github.com/paranext/paranext-core/blob/09a9f3f007abb0ddb1f6fe05aa4284e851fe17fe/lib/platform-bible-react/src/components/book-chapter-control/book-chapter-control.component.tsx#L51)):*
> ```XML
>   const menuItemRef = useRef<HTMLDivElement>(undefined!);
> 
>   const fetchGroupedBooks = useCallback(
> ```

I believe this can come out of the function component. Can be follow-up
___
*[`lib/platform-bible-react/src/components/book-chapter-control/book-chapter-control.component.tsx` line 78 at r2](https://reviewable.io/reviews/paranext/paranext-core/858#-NvrC73Y1EO3967qNfKP:-NvrC73Y1EO3967qNfKQ:b-9cfol7) ([raw file](https://github.com/paranext/paranext-core/blob/09a9f3f007abb0ddb1f6fe05aa4284e851fe17fe/lib/platform-bible-react/src/components/book-chapter-control/book-chapter-control.component.tsx#L78)):*
> ```XML
>   };
> 
>   const fetchEndChapter = useCallback((bookId: string) => {
> ```

I believe this can come out of the function component. Can be follow-up
___
*[`lib/platform-bible-react/src/components/book-chapter-control/book-chapter-control.component.tsx` line 148 at r2](https://reviewable.io/reviews/paranext/paranext-core/858#-NvrDbRJ5vTSZvoJuTTh:-NvrDbRJ5vTSZvoJuTTi:b-ilf15t) ([raw file](https://github.com/paranext/paranext-core/blob/09a9f3f007abb0ddb1f6fe05aa4284e851fe17fe/lib/platform-bible-react/src/components/book-chapter-control/book-chapter-control.component.tsx#L148)):*
> ```XML
>   );
> 
>   const handleKeyDownContent = (event: KeyboardEvent<HTMLInputElement>) => {
> ```

Was a bit difficult to understand what this was doing - might be worth writing a comment to explain. Follow-up is fine
___
*[`lib/platform-bible-react/src/components/book-chapter-control/book-chapter-control.component.tsx` line 149 at r2](https://reviewable.io/reviews/paranext/paranext-core/858#-NvrDj0F1YhboqHiRHkI:-NvrDj0F1YhboqHiRHkJ:bbor7dj) ([raw file](https://github.com/paranext/paranext-core/blob/09a9f3f007abb0ddb1f6fe05aa4284e851fe17fe/lib/platform-bible-react/src/components/book-chapter-control/book-chapter-control.component.tsx#L149)):*
> ```XML
> 
>   const handleKeyDownContent = (event: KeyboardEvent<HTMLInputElement>) => {
>     console.log('content key down processed');
> ```

I expect the log statements will come out when this becomes a full-fledged PR, but just wanted to make a reminder :)
___
*[`lib/platform-bible-react/src/components/book-chapter-control/book-chapter-control.component.tsx` line 233 at r2](https://reviewable.io/reviews/paranext/paranext-core/858#-NvrGFvq2U7bMYQ0o9x1:-NvrGFvq2U7bMYQ0o9x2:bct1phh) ([raw file](https://github.com/paranext/paranext-core/blob/09a9f3f007abb0ddb1f6fe05aa4284e851fe17fe/lib/platform-bible-react/src/components/book-chapter-control/book-chapter-control.component.tsx#L233)):*
> ```XML
>     <div>
>       <ShadDropdownMenu modal={false} open={isContentOpen} onOpenChange={controlMenuState}>
>         {/* Trigger sets input type as button */}
> ```

Is this comment useful anymore? Fine as follow-up
___
*[`lib/platform-bible-react/src/components/book-chapter-control/book-chapter-control.component.tsx` line 282 at r2](https://reviewable.io/reviews/paranext/paranext-core/858#-NvrGA8gDGb42UWrbQDe:-NvrGA8gDGb42UWrbQDf:bct1phh) ([raw file](https://github.com/paranext/paranext-core/blob/09a9f3f007abb0ddb1f6fe05aa4284e851fe17fe/lib/platform-bible-react/src/components/book-chapter-control/book-chapter-control.component.tsx#L282)):*
> ```XML
>                         isSelected={selectedBookId === bookId}
>                         handleHighlightBook={() => setHighlightedBookId(bookId)}
>                         // isHighlighted={highlightedBookId === bookId}
> ```

Is this comment useful anymore? Fine as follow-up
___
*[`lib/platform-bible-react/src/components/book-chapter-control/book-chapter-control.component.tsx` line 304 at r2](https://reviewable.io/reviews/paranext/paranext-core/858#-NvrFWO574wkP0FVCmpH:-NvrFWO574wkP0FVCmpI:b1frquw) ([raw file](https://github.com/paranext/paranext-core/blob/09a9f3f007abb0ddb1f6fe05aa4284e851fe17fe/lib/platform-bible-react/src/components/book-chapter-control/book-chapter-control.component.tsx#L304)):*
> ```XML
>                   ))}
>                   {/* We know this is right because the order of bookTypes will not change */}
>                   {bookType === 'OT' || bookType === 'NT' ? (
> ```

Would probably be best to instead get the second parameter out of the `bookTypeArray.map` (second parameter in `map` is index in the array) and determine this condition using that and the length of `bookTypeArray`. Not a big deal right now, but it wouldn't hurt to do in a follow-up
___
*[`lib/platform-bible-react/src/components/book-chapter-control/book-menu-item.component.tsx` line 9 at r2](https://reviewable.io/reviews/paranext/paranext-core/858#-Nvr9DvBBMlNWVV497c1:-Nvr9DvBBMlNWVV497c2:bbzw5bd) ([raw file](https://github.com/paranext/paranext-core/blob/09a9f3f007abb0ddb1f6fe05aa4284e851fe17fe/lib/platform-bible-react/src/components/book-chapter-control/book-menu-item.component.tsx#L9)):*
> ```XML
> 
> type BookMenuItemProps = PropsWithChildren<{
>   // String id of book
> ```

These should be TSDocs. Follow-up is fine
___
*[`lib/platform-bible-react/src/components/book-chapter-control/book-menu-item.component.tsx` line 42 at r2](https://reviewable.io/reviews/paranext/paranext-core/858#-NvrH2sZ5D8iVD79IOun:-NvrH2sZ5D8iVD79IOuo:b-88lxss) ([raw file](https://github.com/paranext/paranext-core/blob/09a9f3f007abb0ddb1f6fe05aa4284e851fe17fe/lib/platform-bible-react/src/components/book-chapter-control/book-menu-item.component.tsx#L42)):*
> ```XML
>     };
> 
>     const currentBookRef = isSelected ? ref : undefined;
> ```

We should not conditionally expose the ref to the parent. This is very difficult to understand when using `BookMenuItem`. Best practice would be instead in `book-chapter-control.component.tsx` to pass in a function to the `ref` prop on `BookMenuItem` that assigns the `ref` to `menuItemRef.current` if it is the selected menu item.

See [here](https://mattclaffey.medium.com/adding-react-refs-to-an-array-of-items-96e9a12ab40c) for an example of passing a function in as the `ref` prop (though it is doing something else with its function than we need here)

Follow-up is fine
___
*[`lib/platform-bible-react/src/components/book-chapter-control/chapter-select.component.tsx` line 5 at r2](https://reviewable.io/reviews/paranext/paranext-core/858#-Nvr8bEoE4wegJKfXU0q:-Nvr8bEoE4wegJKfXU0r:bbzw5bd) ([raw file](https://github.com/paranext/paranext-core/blob/09a9f3f007abb0ddb1f6fe05aa4284e851fe17fe/lib/platform-bible-react/src/components/book-chapter-control/chapter-select.component.tsx#L5)):*
> ```XML
> 
> export type ChapterSelectProps = {
>   // Callback to run when a chapter div is selected
> ```

These should be TSDocs. Follow-up is fine
___
*[`lib/platform-bible-react/src/components/book-chapter-control/goTo-menu-item.component.tsx` line 0 at r2](https://reviewable.io/reviews/paranext/paranext-core/858#-Nvr5sNq7pKBV0Dz941O:-Nvr5sNq7pKBV0Dz941P:byx1jpm) ([raw file](https://github.com/paranext/paranext-core/blob/09a9f3f007abb0ddb1f6fe05aa4284e851fe17fe/lib/platform-bible-react/src/components/book-chapter-control/goTo-menu-item.component.tsx#L0)):*
the name of this file needs to be changed to `go-to-menu...` to match file naming conventions.

**Review by tjcouch-sil — COMMENTED** [review]
> Reviewed 5 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/858)* status: all files reviewed, 12 unresolved discussions (waiting on @rolfheij-sil)

**Review by tjcouch-sil — APPROVED** [review]
:lgtm: Awesome!! Thanks, guys!

> Reviewed 12 of 12 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/858#-:-Nw520RS-7eTcmnoeSVZ:b-6wjasw)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Review by tjcouch-sil — DISMISSED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/858)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Review by tjcouch-sil — APPROVED** [review]
Just a couple of things I'd prefer to do in follow-up so I can get this into the UX test builds! But since I have now committed to this branch, my approval doesn't matter. If you want to get these notes in before we find someone else to approve this PR, feel free.

Thanks for all the hard work, you guys!!

> Reviewed 10 of 10 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/858#-:-NwBQGl69vUtYc_5DaI7:bfdpcq8)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

___
*[`lib/platform-bible-react/src/components/book-chapter-control/book-chapter-control.component.tsx` line 142 at r6](https://reviewable.io/reviews/paranext/paranext-core/858#-NwBOqH6EHJYpoDIbLrn:-NwBOqH6EHJYpoDIbLro:bn9qx05) ([raw file](https://github.com/paranext/paranext-core/blob/2a0f1946f460d54877a1df8f198e66091cfbe9a9/lib/platform-bible-react/src/components/book-chapter-control/book-chapter-control.component.tsx#L142)):*
> ```XML
>     (bookId: string, shouldClose: boolean, chapter?: number, verse?: number) => {
>       if (bookId && (!chapter || fetchEndChapter(bookId) === -1)) {
>         setSelectedBookId(selectedBookId !== bookId ? bookId : '');
> ```

`shouldClose` is not respected in this case. Please mark this for a follow-up.
___
*[`lib/platform-bible-react/src/components/book-chapter-control/book-chapter-control.component.tsx` line 147 at r6](https://reviewable.io/reviews/paranext/paranext-core/858#-NwBPPQrBuoG_heZOw46:-NwBPPQrBuoG_heZOw47:bbujrbo) ([raw file](https://github.com/paranext/paranext-core/blob/2a0f1946f460d54877a1df8f198e66091cfbe9a9/lib/platform-bible-react/src/components/book-chapter-control/book-chapter-control.component.tsx#L147)):*
> ```XML
> 
>       setHighlightedChapter(
>         Canon.bookNumberToId(scrRef.bookNum) !== bookId ? 1 : scrRef.chapterNum,
> ```

I'm confused about this. Wouldn't you want the highlighted chapter to be `chapter`?
___
*[`lib/platform-bible-react/src/components/book-chapter-control/book-chapter-control.component.tsx` line 286 at r6](https://reviewable.io/reviews/paranext/paranext-core/858#-NwBPm2L8DEgR0YvwZtD:-NwBPm2L8DEgR0YvwZtE:biiame3) ([raw file](https://github.com/paranext/paranext-core/blob/2a0f1946f460d54877a1df8f198e66091cfbe9a9/lib/platform-bible-react/src/components/book-chapter-control/book-chapter-control.component.tsx#L286)):*
> ```XML
> 
>   // The purpose of these useLayoutEffects and timeout is to delay the scroll just
>   // enough so that the refs have time to be defined and it makes it through the check on 293
> ```

Since line numbers are highly volatile, I'd recommend referring to the code below in some other way that describes what it is rather than using a line number. For follow-up

**Review by irahopkinson — APPROVED** [review]
:lgtm:

> Reviewed 44 of 58 files at r1, 4 of 13 files at r4, 5 of 10 files at r6, 8 of 8 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/858#-:-NwC2xq_EGLoAZXyeA6p:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Review by rolfheij-sil — COMMENTED** [review]
Thanks for reviewing! I've added the follow-up items to my list. Excited to finally see this get merged to main!

> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/858#-:-NwE2PV-0qF_tKpyD12A:b45scfe)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Review by rolfheij-sil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/858)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

___
*[`package.json` line 198 at r2](https://reviewable.io/reviews/paranext/paranext-core/858#-Nvr4HZL6jsf1ol6OvIz:-NwFavWYAIH82-gODzFV:bb6un1j) ([raw file](https://github.com/paranext/paranext-core/blob/09a9f3f007abb0ddb1f6fe05aa4284e851fe17fe/package.json#L198)):*
<details><summary><i>Previously, rolfheij-sil wrote…</i></summary><blockquote>

I can't figure out how to extend the `.prettierrc.json` config in lib/platform-bible-react, so I can't fix it for now. Added it to the list of follow-up items
</blockquote></details>

Done
___
*[`lib/platform-bible-react/src/components/book-chapter-control/book-chapter-control.component.tsx` line 142 at r6](https://reviewable.io/reviews/paranext/paranext-core/858#-NwBOqH6EHJYpoDIbLrn:-NwFnkYEBb0_Nw9HnbKv:b-7ti4tr) ([raw file](https://github.com/paranext/paranext-core/blob/2a0f1946f460d54877a1df8f198e66091cfbe9a9/lib/platform-bible-react/src/components/book-chapter-control/book-chapter-control.component.tsx#L142)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

`shouldClose` is not respected in this case. Please mark this for a follow-up.
</blockquote></details>

I've reworked the logic of this function
___
*[`lib/platform-bible-react/src/components/book-chapter-control/book-chapter-control.component.tsx` line 147 at r6](https://reviewable.io/reviews/paranext/paranext-core/858#-NwBPPQrBuoG_heZOw46:-NwFNJ144FotGtVEmN3p:butilwb) ([raw file](https://github.com/paranext/paranext-core/blob/2a0f1946f460d54877a1df8f198e66091cfbe9a9/lib/platform-bible-react/src/components/book-chapter-control/book-chapter-control.component.tsx#L147)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

I'm confused about this. Wouldn't you want the highlighted chapter to be `chapter`?
</blockquote></details>

This code is run whenever you select a book in the dropdown list. When the current ref is Exodus 14 for example, and you select Psalms for example, you want chapter 1 to be highlighted there, not 14. Does that make sense? If not I can show you 
___
*[`lib/platform-bible-react/src/components/book-chapter-control/book-chapter-control.component.tsx` line 286 at r6](https://reviewable.io/reviews/paranext/paranext-core/858#-NwBPm2L8DEgR0YvwZtD:-NwFT86HCuzhw9rkg8tB:bb6un1j) ([raw file](https://github.com/paranext/paranext-core/blob/2a0f1946f460d54877a1df8f198e66091cfbe9a9/lib/platform-bible-react/src/components/book-chapter-control/book-chapter-control.component.tsx#L286)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

Since line numbers are highly volatile, I'd recommend referring to the code below in some other way that describes what it is rather than using a line number. For follow-up
</blockquote></details>

Done
___
*[`lib/platform-bible-react/src/components/book-chapter-control/chapter-select.component.tsx` line 5 at r2](https://reviewable.io/reviews/paranext/paranext-core/858#-Nvr8bEoE4wegJKfXU0q:-NwFS6yW04r6_74IC1yx:bb6un1j) ([raw file](https://github.com/paranext/paranext-core/blob/09a9f3f007abb0ddb1f6fe05aa4284e851fe17fe/lib/platform-bible-react/src/components/book-chapter-control/chapter-select.component.tsx#L5)):*
<details><summary><i>Previously, rolfheij-sil wrote…</i></summary><blockquote>

Added to list of follow-up items
</blockquote></details>

Done

**Pull request merged**
