### PR TITLE
344 current ref resource viewer

### PR DESCRIPTION
**Pull request by katherinejensen00**
This change is [Reviewable](https://reviewable.io/reviews/paranext/paranext-core/399)

### CODE REVIEW

**Review by tjcouch-sil — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/399)* status: all files reviewed, 3 unresolved discussions (waiting on @katherinejensen00)

___
*[`extensions/src/resource-viewer/resource-viewer.web-view.tsx` line 151 at r1](https://reviewable.io/reviews/paranext/paranext-core/399#-Nchcxts0SVCPU-0cceE:-Nchcxts0SVCPU-0cceF:byxy86r) ([raw file](https://github.com/paranext/paranext-core/blob/2cd7d86f740b81e43e1758ec93bd80d5e7dae6f6/extensions/src/resource-viewer/resource-viewer.web-view.tsx#L151)):*
> ```XML
>   logger.info('Preparing to display the Resource Viewer');
> 
>   const defaultScrRef = {
> ```

I believe this variable either needs to go outside the `ResourceViewer` function or needs to be wrapped in a `useMemo` so it isn't given a new object reference every render since it is going into a dependency array in `useSetting`, meaning every time there is a new reference passed in as the default, it will render again. Which is every render right now. See the warning on the Intellisense documentation on `useSetting` :)
___
*[`extensions/src/resource-viewer/resource-viewer.web-view.tsx` line 167 at r1](https://reviewable.io/reviews/paranext/paranext-core/399#-Nchdl8eB8ru4ujsL1Yp:-Nchdl8f8-28sUWbkhKd:b3eobyu) ([raw file](https://github.com/paranext/paranext-core/blob/2cd7d86f740b81e43e1758ec93bd80d5e7dae6f6/extensions/src/resource-viewer/resource-viewer.web-view.tsx#L167)):*
> ```XML
>     <div>
>       <RefSelector
>         scrRef={scrRef as ScriptureReference}
> ```

This type assertion shouldn't need to be here - why isn't `scrRef` of type `ScriptureReference` already? Do you need to add a type to `defaultScrRef`? Like `const defaultScrRef: ScriptureReference = ...`
___
*[`extensions/src/resource-viewer/resource-viewer.web-view.tsx` line 168 at r1](https://reviewable.io/reviews/paranext/paranext-core/399#-Nchdx6f59yop67GQNug:-Nchdx6f59yop67GQNuh:bvo70yt) ([raw file](https://github.com/paranext/paranext-core/blob/2cd7d86f740b81e43e1758ec93bd80d5e7dae6f6/extensions/src/resource-viewer/resource-viewer.web-view.tsx#L168)):*
> ```XML
>       <RefSelector
>         scrRef={scrRef as ScriptureReference}
>         handleSubmit={(newScrRef: {
> ```

This again should just work without specifying this type. I wonder if the same fix from above will fix this as well.

**Review by irahopkinson — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/399)* status: all files reviewed, 4 unresolved discussions (waiting on @katherinejensen00)

___
*[`extensions/src/resource-viewer/package-lock.json` line 11 at r1](https://reviewable.io/reviews/paranext/paranext-core/399#-NcsugE9A71FJQmwnvI2:-NcsugEA3clg3rxpOBtn:b-lrq6d3) ([raw file](https://github.com/paranext/paranext-core/blob/fb5926603be8b02beb05308bcee530ed90721bd6/extensions/src/resource-viewer/package-lock.json#L11)):*
> ```JSON
>       "version": "0.0.1",
>       "license": "MIT",
>       "devDependencies": {
> ```

You'll need to do an `npm i` here to update this correctly after reverting the change to `package.json` (which will likely revert all the changes to this file).

**Review by katherinejensen00 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/399)* status: all files reviewed, 4 unresolved discussions (waiting on @irahopkinson and @tjcouch-sil)

___
*[`extensions/src/resource-viewer/package-lock.json` line 11 at r1](https://reviewable.io/reviews/paranext/paranext-core/399#-NcsugE9A71FJQmwnvI2:-Nd2BqOc1D9nxkfS7pEN:b6tjuag) ([raw file](https://github.com/paranext/paranext-core/blob/fb5926603be8b02beb05308bcee530ed90721bd6/extensions/src/resource-viewer/package-lock.json#L11)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

You'll need to do an `npm i` here to update this correctly after reverting the change to `package.json` (which will likely revert all the changes to this file).
</blockquote></details>

You are right. Thanks for the heads up!
___
*[`extensions/src/resource-viewer/resource-viewer.web-view.tsx` line 151 at r1](https://reviewable.io/reviews/paranext/paranext-core/399#-Nchcxts0SVCPU-0cceE:-Nd2Bvv9-yQo11iS2au4:bqq4ez3) ([raw file](https://github.com/paranext/paranext-core/blob/2cd7d86f740b81e43e1758ec93bd80d5e7dae6f6/extensions/src/resource-viewer/resource-viewer.web-view.tsx#L151)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

I believe this variable either needs to go outside the `ResourceViewer` function or needs to be wrapped in a `useMemo` so it isn't given a new object reference every render since it is going into a dependency array in `useSetting`, meaning every time there is a new reference passed in as the default, it will render again. Which is every render right now. See the warning on the Intellisense documentation on `useSetting` :)
</blockquote></details>

Good point. Thanks for explaining that!
___
*[`extensions/src/resource-viewer/resource-viewer.web-view.tsx` line 167 at r1](https://reviewable.io/reviews/paranext/paranext-core/399#-Nchdl8eB8ru4ujsL1Yp:-Nd2CC0W-J_yFPci6EhO:b-896fix) ([raw file](https://github.com/paranext/paranext-core/blob/2cd7d86f740b81e43e1758ec93bd80d5e7dae6f6/extensions/src/resource-viewer/resource-viewer.web-view.tsx#L167)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

This type assertion shouldn't need to be here - why isn't `scrRef` of type `ScriptureReference` already? Do you need to add a type to `defaultScrRef`? Like `const defaultScrRef: ScriptureReference = ...`
</blockquote></details>

Done.
___
*[`extensions/src/resource-viewer/resource-viewer.web-view.tsx` line 168 at r1](https://reviewable.io/reviews/paranext/paranext-core/399#-Nchdx6f59yop67GQNug:-Nd2CBoW4AJK62qQIlxo:b-896fix) ([raw file](https://github.com/paranext/paranext-core/blob/2cd7d86f740b81e43e1758ec93bd80d5e7dae6f6/extensions/src/resource-viewer/resource-viewer.web-view.tsx#L168)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

This again should just work without specifying this type. I wonder if the same fix from above will fix this as well.
</blockquote></details>

Done.

**Review by tjcouch-sil — CHANGES_REQUESTED** [review]
Great! Thanks for the adjustments! One more thing :)

> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/399#-:-Nd2EzRkCLGFzh_9SpPv:bk15oo3)* status: all files reviewed, 1 unresolved discussion (waiting on @irahopkinson)

___
*[`extensions/src/resource-viewer/package-lock.json` line 11 at r1](https://reviewable.io/reviews/paranext/paranext-core/399#-NcsugE9A71FJQmwnvI2:-Nd2EZFw7PPP4ioWGSuT:b-xlpesi) ([raw file](https://github.com/paranext/paranext-core/blob/fb5926603be8b02beb05308bcee530ed90721bd6/extensions/src/resource-viewer/package-lock.json#L11)):*
<details><summary><i>Previously, katherinejensen00 wrote…</i></summary><blockquote>

You are right. Thanks for the heads up!
</blockquote></details>

I think Ira meant leave `devDependencies` in the other file, then do `npm install` to update this file as well so that both files show `devDependencies`. Previously, it was properly `devDependencies` in the other file, but it was still `dependencies` in this file.

**Review by irahopkinson — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/399)* status: all files reviewed, 1 unresolved discussion (waiting on @tjcouch-sil)

___
*[`extensions/src/resource-viewer/package-lock.json` line 11 at r1](https://reviewable.io/reviews/paranext/paranext-core/399#-NcsugE9A71FJQmwnvI2:-Nd2FM-y7vC6DJrGnVKR:but0tit) ([raw file](https://github.com/paranext/paranext-core/blob/fb5926603be8b02beb05308bcee530ed90721bd6/extensions/src/resource-viewer/package-lock.json#L11)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

I think Ira meant leave `devDependencies` in the other file, then do `npm install` to update this file as well so that both files show `devDependencies`. Previously, it was properly `devDependencies` in the other file, but it was still `dependencies` in this file.
</blockquote></details>

Yep, what @tjcouch-sil said, sorry I wasn't clearer.

**Review by irahopkinson — APPROVED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/399)* status: all files reviewed, 1 unresolved discussion (waiting on @tjcouch-sil)

**Review by tjcouch-sil — APPROVED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/399)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
