### PR TITLE
introduce common scss + style docking framework

### PR DESCRIPTION
**Pull request by Sebastian-ubs**
- fixes https://github.com/paranext/ux/issues/39
- style changes for https://github.com/paranext/ux/issues/22

grafik

- - -
This change is [Reviewable](https://reviewable.io/reviews/paranext/paranext-core/665)

### CODE REVIEW

**Review by irahopkinson — DISMISSED** [review]
:lgtm: thanks for this great start on styling

> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/665#-:-NkrXtVa20NNtWfPtemR:bm7wc4h)* status: all files reviewed, 1 unresolved discussion (waiting on @tjcouch-sil)

___
*[`src/shared/styles.scss` line 1 at r1](https://reviewable.io/reviews/paranext/paranext-core/665#-Nkq7lxt7qdfGUGTSff3:-Nkr3-T30PNZ3sVlfOBL:brdry6c) ([raw file](https://github.com/paranext/paranext-core/blob/54dbf1e6f3a8473cc5904f9f10cfcedccbf519d0/src/shared/styles.scss#L1)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

I believe this belongs in `src/renderer` because it's styles and will only be used in the renderer to my knowledge unless I'm not thinking of something. Could we move this to `src/renderer` (maybe even in its own folder `src/renderer/styles` if you want. I dunno if we'll have multiple of these kinds of global style files, but it seems likely for light/dark mode considerations and such maybe) and call it `base-styles.scss` or `vars.scss` or something so it's a bit clearer what's in here?
</blockquote></details>

+1 for `vars.scss`. It should also start with an underscore since it's a partial, i.e. `_vars.scss`.

**Review by Sebastian-ubs — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/665)* status: all files reviewed, 1 unresolved discussion (waiting on @tjcouch-sil)

___
*[`src/shared/styles.scss` line 1 at r1](https://reviewable.io/reviews/paranext/paranext-core/665#-Nkq7lxt7qdfGUGTSff3:-NkyLdEY9PLarNh-CSDe:b8fbzk0) ([raw file](https://github.com/paranext/paranext-core/blob/54dbf1e6f3a8473cc5904f9f10cfcedccbf519d0/src/shared/styles.scss#L1)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

+1 for `vars.scss`. It should also start with an underscore since it's a partial, i.e. `_vars.scss`.
</blockquote></details>

Thank you. What is the purpose of folder the folder "shared"?
These style variables should finally also be available to extension developer. How would this be done?

**Review by Sebastian-ubs — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/665)* status: all files reviewed, 1 unresolved discussion (waiting on @tjcouch-sil)

___
*[`src/shared/styles.scss` line 1 at r1](https://reviewable.io/reviews/paranext/paranext-core/665#-Nkq7lxt7qdfGUGTSff3:-Nkz9m8O8lMxgDSzB_wu:birjote) ([raw file](https://github.com/paranext/paranext-core/blob/54dbf1e6f3a8473cc5904f9f10cfcedccbf519d0/src/shared/styles.scss#L1)):*
<details><summary><i>Previously, Sebastian-ubs wrote…</i></summary><blockquote>

Thank you. What is the purpose of folder the folder "shared"?
These style variables should finally also be available to extension developer. How would this be done?
</blockquote></details>

Wow. Sorry for the bad typos!

**Review by tjcouch-sil — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/665)* status: all files reviewed, 1 unresolved discussion (waiting on @irahopkinson and @Sebastian-ubs)

___
*[`src/shared/styles.scss` line 1 at r1](https://reviewable.io/reviews/paranext/paranext-core/665#-Nkq7lxt7qdfGUGTSff3:-Nkzy1BQ943moRm4jlH1:b-hxofzr) ([raw file](https://github.com/paranext/paranext-core/blob/54dbf1e6f3a8473cc5904f9f10cfcedccbf519d0/src/shared/styles.scss#L1)):*
<details><summary><i>Previously, Sebastian-ubs wrote…</i></summary><blockquote>

Wow. Sorry for the bad typos!
</blockquote></details>

The `shared` folder indicates that the things in it are not specific to certain processes but can be used by any process. Core's `src` subfolders indicate what what runs on each process because core's `src` is focused on processes. I think we have an issue somewhere to document this structure, but we have not done so yet to my knowledge :grimacing: sorry.

We don't currently have a design around giving extension developers some CSS they can use, and we definitely don't have a design around giving extension developers SCSS. Would need to think about this. Maybe it could go in `papi-components` somewhere somehow. Sharing `SCSS` is tricky, though. If you feel it is worth doing, I recommend filing an issue for figuring out how to share CSS and SCSS with extensions.

**Review by Sebastian-ubs — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/665)* status: 2 of 7 files reviewed, 1 unresolved discussion (waiting on @irahopkinson and @tjcouch-sil)

___
*[`src/shared/styles.scss` line 1 at r1](https://reviewable.io/reviews/paranext/paranext-core/665#-Nkq7lxt7qdfGUGTSff3:-Nl3iG6wDvj_JVG-E3bK:b-1fkzga) ([raw file](https://github.com/paranext/paranext-core/blob/54dbf1e6f3a8473cc5904f9f10cfcedccbf519d0/src/shared/styles.scss#L1)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

The `shared` folder indicates that the things in it are not specific to certain processes but can be used by any process. Core's `src` subfolders indicate what what runs on each process because core's `src` is focused on processes. I think we have an issue somewhere to document this structure, but we have not done so yet to my knowledge :grimacing: sorry.

We don't currently have a design around giving extension developers some CSS they can use, and we definitely don't have a design around giving extension developers SCSS. Would need to think about this. Maybe it could go in `papi-components` somewhere somehow. Sharing `SCSS` is tricky, though. If you feel it is worth doing, I recommend filing an issue for figuring out how to share CSS and SCSS with extensions.
</blockquote></details>

Thank you. I've moved it to shared/vars.scss now.
Prettier complains about files that have a leading underscore, so I was not using this one.
We can later think about how to make it shareable for extensions, but this is definitively something we would like to be able to do and extension developers to use it (besides more to-be-created shared components).

**Comment by Sebastian-ubs** [comment]
new style
grafik

**Review by irahopkinson — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/665)* status: all files reviewed, 4 unresolved discussions (waiting on @Sebastian-ubs and @tjcouch-sil)

___
*[`src/renderer/components/docking/platform-dock-layout.component.scss` line 72 at r2](https://reviewable.io/reviews/paranext/paranext-core/665#-Nl4WiOY8U0rRyQWHmvc:-Nl4WiOY8U0rRyQWHmvd:ba05nh2) ([raw file](https://github.com/paranext/paranext-core/blob/bd84d947592a51420cea5d3448822bbf3d67facc/src/renderer/components/docking/platform-dock-layout.component.scss#L72)):*
> ```SCSS
>   /*
>    * Remove the handle bar at the top of each dock-tab. Note: Now, the tab
>    * group can only be grabbed by grabbing the intersection between two tabs
> ```

BTW: IMHO it feels busier without the border spacing around panels. I think that is because the deliniation is almost gone and there is not enough "whitespace" for the eyes to rest. Any thoughts on how to improve this?



_Code quote:_
```SCSS
   * Remove the handle bar at the top of each dock-tab. Note: Now, the tab
   * group can only be grabbed by grabbing the intersection between two tabs
```
___
*[`src/renderer/components/docking/platform-dock-layout.component.scss` line 99 at r2](https://reviewable.io/reviews/paranext/paranext-core/665#-Nl4Txu97SvcMsmHQzHk:-Nl4Txu97SvcMsmHQzHl:b-mq06ax) ([raw file](https://github.com/paranext/paranext-core/blob/bd84d947592a51420cea5d3448822bbf3d67facc/src/renderer/components/docking/platform-dock-layout.component.scss#L99)):*
> ```SCSS
>   //box-shadow: 0 4px 20px 0 $color--text-dimmed;
>   /* fix to show over the right next ribbon as well. needed for rounded bottom tab and box-shadow */
>   //z-index: 1;
> ```

Since these are commented then add a comment to explain why they are or just remove them.



_Code quote:_
```SCSS
  //box-shadow: 0 4px 20px 0 $color--text-dimmed;
  /* fix to show over the right next ribbon as well. needed for rounded bottom tab and box-shadow */
  //z-index: 1;
```
___
*[`src/renderer/components/docking/platform-dock-layout.component.scss` line 113 at r2](https://reviewable.io/reviews/paranext/paranext-core/665#-Nl4UbGs8WNEGXySn9L0:-Nl4UbGs8WNEGXySn9L1:b-391knj) ([raw file](https://github.com/paranext/paranext-core/blob/bd84d947592a51420cea5d3448822bbf3d67facc/src/renderer/components/docking/platform-dock-layout.component.scss#L113)):*
> ```SCSS
> /************* ROUNDED CORNERS *********************/
> 
> /*
> ```

Same here: since these are commented then add a comment to explain why they are or just remove them.
___
*[`src/shared/styles.scss` line 1 at r1](https://reviewable.io/reviews/paranext/paranext-core/665#-Nkq7lxt7qdfGUGTSff3:-Nl4YlsF7hH4c3iWubcw:bb1v04z) ([raw file](https://github.com/paranext/paranext-core/blob/54dbf1e6f3a8473cc5904f9f10cfcedccbf519d0/src/shared/styles.scss#L1)):*
<details><summary><i>Previously, Sebastian-ubs wrote…</i></summary><blockquote>

Thank you. I've moved it to shared/vars.scss now.
Prettier complains about files that have a leading underscore, so I was not using this one.
We can later think about how to make it shareable for extensions, but this is definitively something we would like to be able to do and extension developers to use it (besides more to-be-created shared components).
</blockquote></details>

When the SCSS is a partial, this is indicated by naming the file with a starting undescore, i.e. `_vars.scss` but the imports don't include the underscore, i.e. in `platform-tab-title.component.scss` the import stays as `@import '../../styles/vars';`. This also means you won't have trouble with any of our linters/prettier.

**Review by tjcouch-sil — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/665)* status: all files reviewed, 5 unresolved discussions (waiting on @Sebastian-ubs)

___
*[`src/renderer/components/docking/platform-dock-layout.component.scss` line 3 at r2](https://reviewable.io/reviews/paranext/paranext-core/665#-Nl4ma0W0CBS1ae_u6zZ:-Nl4ma0W0CBS1ae_u6z_:bfe5knf) ([raw file](https://github.com/paranext/paranext-core/blob/bd84d947592a51420cea5d3448822bbf3d67facc/src/renderer/components/docking/platform-dock-layout.component.scss#L3)):*
> ```SCSS
> @import '../../styles/vars';
> 
> /************* GENERAL *********************/
> ```

I would prefer regions to make these sections collapsible, though I don't know if they work in these scss files. I also don't consider this necessary; just a preference. Here's how to do a region:

```typescript
// #region General

// #endregion
```

Though you may need to make them in-line comments with `/* ... */`. I think I remember that scss allows full-line comments, but I don't remember for sure.

**Comment by Sebastian-ubs** [comment]
New design (still work in progress) as follows. I would prefer to merge this and do other style changes in a new PR.
Please advice if canges to files in the dist folder are valid/necessary/required. Thanks

grafik

**Comment by Sebastian-ubs** [comment]
Hi, I've rebased this branch onto master. Please update any local references.

**Review by tjcouch-sil — APPROVED** [review]
:lgtm: thanks for all the great work and persistence!

> Reviewed 3 of 5 files at r2, 3 of 5 files at r3, 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/665#-:-NlOzHpE32EApR1xtvti:bdmhhru)* status: all files reviewed, 4 unresolved discussions (waiting on @Sebastian-ubs)

___
*[`src/renderer/components/docking/platform-dock-layout.component.scss` line 3 at r2](https://reviewable.io/reviews/paranext/paranext-core/665#-Nl4ma0W0CBS1ae_u6zZ:-NlOyY2j-n1P4UMN33lj:b-d2lxou) ([raw file](https://github.com/paranext/paranext-core/blob/bd84d947592a51420cea5d3448822bbf3d67facc/src/renderer/components/docking/platform-dock-layout.component.scss#L3)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

I would prefer regions to make these sections collapsible, though I don't know if they work in these scss files. I also don't consider this necessary; just a preference. Here's how to do a region:

```typescript
// #region General

// #endregion
```

Though you may need to make them in-line comments with `/* ... */`. I think I remember that scss allows full-line comments, but I don't remember for sure.
</blockquote></details>

I don't want to block this PR with this comment, so I'm resolving it.

**Review by irahopkinson — APPROVED** [review]
:lgtm: thanks for this

> Reviewed 3 of 5 files at r3, 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/665#-:-NlP9pwQ1uJEKSXRX9z2:b-r4tcg3)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Comment by irahopkinson** [comment]
@Sebastian-ubs you need to merge the branch yourself now that its approved.

**Pull request merged**
