### PR TITLE
add component hierarchy to the preview app

### PR DESCRIPTION
**Pull request by Sebastian-ubs**
This change is [Reviewable](https://reviewable.io/reviews/paranext/paranext-core/896)

### CODE REVIEW

**Comment by Sebastian-ubs** [comment]
grafik

grafik

grafik

**Review by irahopkinson — CHANGES_REQUESTED** [review]
:lgtm: just one blocking comment. Feel free to marked the non-blocking comments as **Satisfied** yourself if appropriate.

> Reviewed 10 of 13 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/896#-:-Ny37X10Em45ExQZdrUJ:bwpordx)* status: all files reviewed, 6 unresolved discussions (waiting on @Sebastian-ubs)

___
*[`lib/platform-bible-react/src/preview/theme-provider.tsx` line 7 at r2](https://reviewable.io/reviews/paranext/paranext-core/896#-Ny2xpaz5_rVaAIiixRC:-Ny2xpaz5_rVaAIiixRD:b-23q0xq) ([raw file](https://github.com/paranext/paranext-core/blob/30eb962563226b464a7a9d643499723a249f1890/lib/platform-bible-react/src/preview/theme-provider.tsx#L7)):*
> ```XML
> 
> type ThemeProviderProps = {
>   children: React.ReactNode;
> ```

BTW is there some reason you aren't using the React `PropsWithChildren` type here?
I.e.:
```typescript
type ThemeProviderProps = PropsWithChildren<{
  defaultTheme?: Theme;
  storageKey?: string;
}>;

```
___
*[`lib/platform-bible-react/src/preview/theme-provider.tsx` line 22 at r2](https://reviewable.io/reviews/paranext/paranext-core/896#-Ny2yenr0q1jlcHp8YS0:-Ny2yenr0q1jlcHp8YS1:bt6w29f) ([raw file](https://github.com/paranext/paranext-core/blob/30eb962563226b464a7a9d643499723a249f1890/lib/platform-bible-react/src/preview/theme-provider.tsx#L22)):*
> ```XML
> };
> 
> const ThemeProviderContext = createContext<ThemeProviderState>(initialState);
> ```

Nit: you don't strictly need to provide this generic type override because `initialState` is that type so `ThemeProviderContext` will also be of that type.



_Code quote:_
```XML
<ThemeProviderState>
```
___
*[`lib/platform-bible-react/src/preview/theme-provider.tsx` line 35 at r2](https://reviewable.io/reviews/paranext/paranext-core/896#-Ny31K3p6BIhRS-OSSDn:-Ny31K3q6N7uohaVXCiS:bglbvrg) ([raw file](https://github.com/paranext/paranext-core/blob/30eb962563226b464a7a9d643499723a249f1890/lib/platform-bible-react/src/preview/theme-provider.tsx#L35)):*
> ```XML
> 
>   useEffect(() => {
>     const root = window.document.documentElement;
> ```

Nit: I know this isn't consistent in all our code but we don't tend to preface with `window.` since our frontend code is all used in the browser. You also don't use it consistently since `localStorage` doesn't have it. I'd suggest you remove it.



_Code quote:_
```XML
window.
```
___
*[`lib/platform-bible-react/src/preview/theme-toggle.tsx` line 0 at r2](https://reviewable.io/reviews/paranext/paranext-core/896#-Ny37ufdAvxLg4FYWBPJ:-Ny37ufdAvxLg4FYWBPK:b5s7kuh) ([raw file](https://github.com/paranext/paranext-core/blob/30eb962563226b464a7a9d643499723a249f1890/lib/platform-bible-react/src/preview/theme-toggle.tsx#L0)):*
Strictly this file (and all the ones below) should have the _type_ `.component` added to the filename, e.g. `theme-toggle.component.tsx` . See the first item of our [style guide](https://github.com/paranext/paranext/wiki/Code-Style-Guide#typescript-specific-guidelines).
___
*[`lib/platform-bible-react/src/preview/components/basics.tsx` line 90 at r2](https://reviewable.io/reviews/paranext/paranext-core/896#-Ny361OE1FNDyqYSu2un:-Ny361OE1FNDyqYSu2uo:b-wvaryr) ([raw file](https://github.com/paranext/paranext-core/blob/30eb962563226b464a7a9d643499723a249f1890/lib/platform-bible-react/src/preview/components/basics.tsx#L90)):*
> ```XML
>                 <DropdownMenuItem>
>                   <span>DropdownMenuItem</span>
>                   <DropdownMenuShortcut>⇧⌘P</DropdownMenuShortcut>
> ```

BTW I'm guessing this works on Windows and Linux also despite the macOS label?



_Code quote:_
```XML
⇧⌘P
```
___
*[`lib/platform-bible-react/src/preview/components/examples.tsx` line 18 at r2](https://reviewable.io/reviews/paranext/paranext-core/896#-Ny36_id9xKdqNWGWypO:-Ny36_id9xKdqNWGWypP:bgh9dka) ([raw file](https://github.com/paranext/paranext-core/blob/30eb962563226b464a7a9d643499723a249f1890/lib/platform-bible-react/src/preview/components/examples.tsx#L18)):*
> ```XML
> };
> 
> function Compositions() {
> ```

Minor: should this be renamed `Examples` (maybe missed after copy and paste).



_Code quote:_
```XML
Compositions
```

**Review by irahopkinson — COMMENTED** [review]
BTW thanks for adding the screenshots. That meant I didn't have to checkout the branch and run it to see it.

> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/896#-:-Ny3Oo2Q3LIiaR5A-NpU:bi91dac)* status: all files reviewed, 6 unresolved discussions (waiting on @Sebastian-ubs)

**Review by Sebastian-ubs — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/896)* status: all files reviewed, 6 unresolved discussions (waiting on @irahopkinson)

___
*[`lib/platform-bible-react/src/preview/theme-provider.tsx` line 7 at r2](https://reviewable.io/reviews/paranext/paranext-core/896#-Ny2xpaz5_rVaAIiixRC:-Ny4f8QUCupgEbiEn3IE:buf832g) ([raw file](https://github.com/paranext/paranext-core/blob/30eb962563226b464a7a9d643499723a249f1890/lib/platform-bible-react/src/preview/theme-provider.tsx#L7)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

BTW is there some reason you aren't using the React `PropsWithChildren` type here?
I.e.:
```typescript
type ThemeProviderProps = PropsWithChildren<{
  defaultTheme?: Theme;
  storageKey?: string;
}>;

```
</blockquote></details>

I should have mentioned that this code is basically coming from https://ui.shadcn.com/docs/dark-mode/vite
I can apply your modifications in case you think they should be done for us.
___
*[`lib/platform-bible-react/src/preview/theme-provider.tsx` line 22 at r2](https://reviewable.io/reviews/paranext/paranext-core/896#-Ny2yenr0q1jlcHp8YS0:-Ny4gxuz0PEBTl5L85w7:byr4ffv) ([raw file](https://github.com/paranext/paranext-core/blob/30eb962563226b464a7a9d643499723a249f1890/lib/platform-bible-react/src/preview/theme-provider.tsx#L22)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

Nit: you don't strictly need to provide this generic type override because `initialState` is that type so `ThemeProviderContext` will also be of that type.
</blockquote></details>

see above
___
*[`lib/platform-bible-react/src/preview/theme-provider.tsx` line 35 at r2](https://reviewable.io/reviews/paranext/paranext-core/896#-Ny31K3p6BIhRS-OSSDn:-Ny4h-Cs7FKXx_jtvQwf:byr4ffv) ([raw file](https://github.com/paranext/paranext-core/blob/30eb962563226b464a7a9d643499723a249f1890/lib/platform-bible-react/src/preview/theme-provider.tsx#L35)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

Nit: I know this isn't consistent in all our code but we don't tend to preface with `window.` since our frontend code is all used in the browser. You also don't use it consistently since `localStorage` doesn't have it. I'd suggest you remove it.
</blockquote></details>

see above
___
*[`lib/platform-bible-react/src/preview/theme-toggle.tsx` line  at r2](https://reviewable.io/reviews/paranext/paranext-core/896#-Ny37ufdAvxLg4FYWBPJ:-Ny4gCjFD6G6tdoNVUvo:bhy9oss) ([raw file](https://github.com/paranext/paranext-core/blob/30eb962563226b464a7a9d643499723a249f1890/lib/platform-bible-react/src/preview/theme-toggle.tsx#L)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

Strictly this file (and all the ones below) should have the _type_ `.component` added to the filename, e.g. `theme-toggle.component.tsx` . See the first item of our [style guide](https://github.com/paranext/paranext/wiki/Code-Style-Guide#typescript-specific-guidelines).
</blockquote></details>

Will do 
___
*[`lib/platform-bible-react/src/preview/components/basics.tsx` line 90 at r2](https://reviewable.io/reviews/paranext/paranext-core/896#-Ny361OE1FNDyqYSu2un:-Ny4gHw0-Lx2a3ATKrIC:bg2130q) ([raw file](https://github.com/paranext/paranext-core/blob/30eb962563226b464a7a9d643499723a249f1890/lib/platform-bible-react/src/preview/components/basics.tsx#L90)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

BTW I'm guessing this works on Windows and Linux also despite the macOS label?
</blockquote></details>

I think it's just example text added here and not adding any real functionality / keyboard handler.
___
*[`lib/platform-bible-react/src/preview/components/examples.tsx` line 18 at r2](https://reviewable.io/reviews/paranext/paranext-core/896#-Ny36_id9xKdqNWGWypO:-Ny4gtJWAYB9dvkRg0OJ:b2nign6) ([raw file](https://github.com/paranext/paranext-core/blob/30eb962563226b464a7a9d643499723a249f1890/lib/platform-bible-react/src/preview/components/examples.tsx#L18)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

Minor: should this be renamed `Examples` (maybe missed after copy and paste).
</blockquote></details>

yes

**Review by irahopkinson — APPROVED** [review]
:lgtm:

> Reviewed 9 of 9 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/896#-:-NyN9-vi7LFvAeJAfnNR:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @Sebastian-ubs)

___
*[`lib/platform-bible-react/src/preview/theme-provider.component.tsx` line 1 at r3](https://reviewable.io/reviews/paranext/paranext-core/896#-NyN8drF7rggLZYW8Vq4:-NyN8drF7rggLZYW8Vq5:b-fnouob) ([raw file](https://github.com/paranext/paranext-core/blob/69714574d64b772ab176d8e7c6803f4574cf99db/lib/platform-bible-react/src/preview/theme-provider.component.tsx#L1)):*
> ```XML
> // source: https://ui.shadcn.com/docs/dark-mode/vite
> ```

FYI thanks for adding these source comments to these files.

**Review by Sebastian-ubs — COMMENTED** [review]
> Reviewed 1 of 3 files at r2, 8 of 9 files at r3, 5 of 5 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/896)* status: 9 of 14 files reviewed, all discussions resolved (waiting on @Sebastian-ubs)

**Review by Sebastian-ubs — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/896#-:-Nyuhlpu3WBnRUP97oE4:bnfp4nl)* status: 9 of 14 files reviewed, all discussions resolved (waiting on @Sebastian-ubs)

**Review by Sebastian-ubs — COMMENTED** [review]
> Reviewed 1 of 3 files at r2, 8 of 9 files at r3, 5 of 5 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/896)* status: 9 of 14 files reviewed, all discussions resolved (waiting on @Sebastian-ubs)

**Review by ianhewubs — APPROVED** [review]
> Reviewed 1 of 3 files at r2, 8 of 9 files at r3, 5 of 5 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/896)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Pull request merged**
