### PR TITLE
Adjusted Network Object and Data Provider Types

### PR DESCRIPTION
**Pull request by tjcouch-sil**
Adjusted network object and data provider types to indicate their constraints and relationships more strongly.

Renamed Data Provider types/interfaces:

IDataProviderEngine [stayed the same] (like NetworkableObject)
IDataProvider -> DataProviderInternal (like NetworkableObject)
DisposableDataProvider -> IDisposableDataProvider (like DisposableNetworkObject)
DataProvider -> IDataProvider (like NetworkObject)

Relates to #125

- - -
This change is [Reviewable](https://reviewable.io/reviews/paranext/paranext-core/163)

### CODE REVIEW

**Review by lyonsil — APPROVED** [review]
> Reviewed 16 of 16 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/163)* status: all files reviewed, 1 unresolved discussion (waiting on @tjcouch-sil)

___
*[`src/shared/models/network-object.model.ts` line 4 at r1](https://reviewable.io/reviews/paranext/paranext-core/163#-NU9-LOy0qprW50VzpAJ:-NU9-LOy0qprW50VzpAK:bjy620x) ([raw file](https://github.com/paranext/paranext-core/blob/45888bf5aeaa5303273d5d363744ea41699282f1/src/shared/models/network-object.model.ts#L4)):*
> ```XML
> // This is used in @see comments in the JSDoc
> // eslint-disable-next-line @typescript-eslint/no-unused-vars
> import type networkObjectService from '@shared/services/network-object.service';
> ```

Did you have a problem with the comments if the type wasn't imported?

Technically I think I did this wrong, and I probably should have used a @link instead of @see.  It isn't that important at least until we do something more substantial with JSDoc.

**Review by lyonsil — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/163)* status: all files reviewed, 1 unresolved discussion (waiting on @tjcouch-sil)

**Review by katherinejensen00 — APPROVED** [review]
Note, there are some comments that are too long in papi.d.ts, but I don't think that is worth fixing. This looks good to me. Thanks for all of the work!

> Reviewed 16 of 16 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/163#-:-NU97I3KAHQIWOxniDd_:bsg4s0p)* status: all files reviewed, 2 unresolved discussions (waiting on @tjcouch-sil)

___
*[`lib/papi-dts/papi.d.ts` line 119 at r1](https://reviewable.io/reviews/paranext/paranext-core/163#-NU8yQAg-WtbSKd9MDbr:-NU8yQAhEmE3jtcc2V52:bc58xq6) ([raw file](https://github.com/paranext/paranext-core/blob/45888bf5aeaa5303273d5d363744ea41699282f1/lib/papi-dts/papi.d.ts#L119)):*
> ```XML
>   /**
>    * HTML Encodes the provided string.
>    * Thanks to ChatGPT
> ```

That's cool :)
___
*[`lib/papi-dts/papi.d.ts` line 2101 at r1](https://reviewable.io/reviews/paranext/paranext-core/163#-NU95Gux8ISYI8029dk4:-NU95Gux8ISYI8029dk5:bgyid8e) ([raw file](https://github.com/paranext/paranext-core/blob/45888bf5aeaa5303273d5d363744ea41699282f1/lib/papi-dts/papi.d.ts#L2101)):*
> ```XML
>           eventHandler: import('shared/models/papi-event.model').PapiEventHandler<T_1>,
>         ) => void;
>         useEventAsync: <T_2>(
> ```

Just a question to make sure I understand, do you need T_1, T_2, etc. so that T_1 can be a separate type from T_2?

**Review by tjcouch-sil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/163)* status: all files reviewed, 1 unresolved discussion (waiting on @katherinejensen00)

___
*[`lib/papi-dts/papi.d.ts` line 119 at r1](https://reviewable.io/reviews/paranext/paranext-core/163#-NU8yQAg-WtbSKd9MDbr:-NUMY9eGDihPDniCvNyM:b-h40dum) ([raw file](https://github.com/paranext/paranext-core/blob/45888bf5aeaa5303273d5d363744ea41699282f1/lib/papi-dts/papi.d.ts#L119)):*
<details><summary><i>Previously, katherinejensen00 wrote…</i></summary><blockquote>

That's cool :)
</blockquote></details>

Can't take credit; this was Matt's idea :)
___
*[`lib/papi-dts/papi.d.ts` line 2101 at r1](https://reviewable.io/reviews/paranext/paranext-core/163#-NU95Gux8ISYI8029dk4:-NUMYD2O3R0Uaj9fjz3n:b-5m6gk3) ([raw file](https://github.com/paranext/paranext-core/blob/45888bf5aeaa5303273d5d363744ea41699282f1/lib/papi-dts/papi.d.ts#L2101)):*
<details><summary><i>Previously, katherinejensen00 wrote…</i></summary><blockquote>

Just a question to make sure I understand, do you need T_1, T_2, etc. so that T_1 can be a separate type from T_2?
</blockquote></details>

`papi.d.ts` is a generated file, so the comments are long and this is happening. There are a number of weird things in this file that would be good to improve, but I don't really know how to fine-tune it right now unfortunately. Would be good to investigate. https://github.com/paranext/paranext-core/issues/166
___
*[`src/shared/models/network-object.model.ts` line 4 at r1](https://reviewable.io/reviews/paranext/paranext-core/163#-NU9-LOy0qprW50VzpAJ:-NUMYxzBBTQDVDMtgJLC:b-lzxml9) ([raw file](https://github.com/paranext/paranext-core/blob/45888bf5aeaa5303273d5d363744ea41699282f1/src/shared/models/network-object.model.ts#L4)):*
<details><summary><i>Previously, lyonsil wrote…</i></summary><blockquote>

Did you have a problem with the comments if the type wasn't imported?

Technically I think I did this wrong, and I probably should have used a @link instead of @see.  It isn't that important at least until we do something more substantial with JSDoc.
</blockquote></details>

Not sure why, but I got an error at one point when this wasn't in there. But then after I put it in, I tried taking it out again and didn't see the problem after that. Not sure what's going on 🤷‍♂️

**Review by lyonsil — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/163)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @tjcouch-sil)

**Pull request merged**
