### PR TITLE
Add prototype GraphQL service on top of Paratext project data providers

### PR DESCRIPTION
**Pull request by lyonsil**
This change is [Reviewable](https://reviewable.io/reviews/paranext/paranext-core/520)

### CODE REVIEW

**Review by tjcouch-sil — DISMISSED** [review]
:lgtm: Great first step!! Just a couple notes to put in a new issue.

> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/520#-:-Nfr1oMM4BZwbsYE4rAm:b-kgi5o9)* status: :shipit: complete! all files reviewed, all discussions resolved

___
*[`src/shared/services/graphql.service.ts` line 110 at r1](https://reviewable.io/reviews/paranext/paranext-core/520#-Nfr0isF6feLFzzfvaZ6:-Nfr0isF6feLFzzfvaZ7:b-f11qhj) ([raw file](https://github.com/paranext/paranext-core/blob/320f6629287eb9777851b1a350a1d53ca1113db8/src/shared/services/graphql.service.ts#L110)):*
> ```XML
>   if (results.errors) throw new Error(JSON.stringify(results.errors));
>   // If there is only 1 result, just give it to the caller instead of making the use a map to get it
>   if (results.data && Object.keys(results.data).length === 1)
> ```

I imagine this should not happen long-term to stick with expected GraphQL behavior
___
*[`src/shared/services/graphql.service.ts` line 120 at r1](https://reviewable.io/reviews/paranext/paranext-core/520#-Nfr15kfAUeQvSi43c4G:-Nfr15kfAUeQvSi43c4H:b-d2j0u9) ([raw file](https://github.com/paranext/paranext-core/blob/320f6629287eb9777851b1a350a1d53ca1113db8/src/shared/services/graphql.service.ts#L120)):*
> ```XML
> };
> 
> export default graphqlService;
> ```

I think it could be potentially very beneficial to our performance to put the "backend" of the service on the main process and make it a network object that we call from other processes. That way, we reduce the number of processes to cross to make each call to data providers.

In the far future, we could even maybe make the main process have a supergraph, then the extension host and C# processes could be subgraphs that expose their respective data providers. :)

**Review by irahopkinson — CHANGES_REQUESTED** [review]
Thanks for this and producing something so quickly. Just 2 blockers.

> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/520#-:-Nfr2Fsr0oO7e3bGCml1:b-siyae2)* status: all files reviewed, 4 unresolved discussions (waiting on @lyonsil)

___
*[`src/shared/services/graphql.service.ts` line 8 at r1](https://reviewable.io/reviews/paranext/paranext-core/520#-NfqvoYi2ixB4eQ0wTfY:-NfqvoYi2ixB4eQ0wTfZ:b86oyh3) ([raw file](https://github.com/paranext/paranext-core/blob/320f6629287eb9777851b1a350a1d53ca1113db8/src/shared/services/graphql.service.ts#L8)):*
> ```XML
> import { getProjectDataProvider } from '@shared/services/project-data-provider.service';
> 
> // TODO: figure out what to do with the schema. It's a baked in string just to get things rolling, not because it's optimal.
> ```

BTW I'm not wanting you to make a change in this PR, but just curious why you went with `buildSchema` rather than the classes that allow you to structure the schema as documented in the [graphql npm package README](https://github.com/graphql/graphql-js)?
___
*[`src/shared/services/graphql.service.ts` line 25 at r1](https://reviewable.io/reviews/paranext/paranext-core/520#-NfqwqOp7rLZmB1YiHKD:-NfqwqOp7rLZmB1YiHKE:b-1rxs0l) ([raw file](https://github.com/paranext/paranext-core/blob/320f6629287eb9777851b1a350a1d53ca1113db8/src/shared/services/graphql.service.ts#L25)):*
> ```XML
> 
>   type Query {
>     projects: [Project]
> ```

Strictly this is not projects themselves but project's metadata.
___
*[`src/shared/services/graphql.service.ts` line 34 at r1](https://reviewable.io/reviews/paranext/paranext-core/520#-Nfr-nHA7olSkb3-vhEi:-Nfr-nHA7olSkb3-vhEj:b-drb4v1) ([raw file](https://github.com/paranext/paranext-core/blob/320f6629287eb9777851b1a350a1d53ca1113db8/src/shared/services/graphql.service.ts#L34)):*
> ```XML
> // There are probably frameworks that can  be used to automatically convert between GraphQL and TS/JS types
> // We should figure out how we want to use GraphQL in more detail before deciding which ones (if any) to use
> function extractVerseRef(verseRef: Object): VerseRef {
> ```

Just like you wouldn't declare `let str: String` (using the string constructor) also here use the type `object` (lowercase).
___
*[`src/shared/services/graphql.service.ts` line 36 at r1](https://reviewable.io/reviews/paranext/paranext-core/520#-NfqyIio7YdregfGyw05:-NfqyIio7YdregfGyw06:b-mdoqxw) ([raw file](https://github.com/paranext/paranext-core/blob/320f6629287eb9777851b1a350a1d53ca1113db8/src/shared/services/graphql.service.ts#L36)):*
> ```XML
> function extractVerseRef(verseRef: Object): VerseRef {
>   // eslint-disable-next-line no-undef-init
>   let versification: ScrVers | undefined = undefined;
> ```

It is not necessary to add the initialization. In JS if you declare a variable it is undefined by definition unless it is initialized. Remove the intilaizer and the eslint comment above (this eslint rule exists to make sure we don't add more code than is necessary).
___
*[`src/shared/services/graphql.service.ts` line 47 at r1](https://reviewable.io/reviews/paranext/paranext-core/520#-Nfr0g4r-ZCrRYgOytzk:-Nfr0g4r-ZCrRYgOytzl:b-khugdw) ([raw file](https://github.com/paranext/paranext-core/blob/320f6629287eb9777851b1a350a1d53ca1113db8/src/shared/services/graphql.service.ts#L47)):*
> ```XML
> }
> 
> // Caching some objects do we don't have to keep making network calls for every GraphQL query
> ```

sp: 'so'



_Code quote:_
```XML
do
```

**Review by lyonsil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/520)* status: all files reviewed, 3 unresolved discussions (waiting on @irahopkinson)

___
*[`src/shared/services/graphql.service.ts` line 8 at r1](https://reviewable.io/reviews/paranext/paranext-core/520#-NfqvoYi2ixB4eQ0wTfY:-Nfr3LoHAVWXTaRTGPvm:b-qrwjmf) ([raw file](https://github.com/paranext/paranext-core/blob/320f6629287eb9777851b1a350a1d53ca1113db8/src/shared/services/graphql.service.ts#L8)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

BTW I'm not wanting you to make a change in this PR, but just curious why you went with `buildSchema` rather than the classes that allow you to structure the schema as documented in the [graphql npm package README](https://github.com/graphql/graphql-js)?
</blockquote></details>

I was working from the example on https://graphql.org/graphql-js/ which uses `buildSchema`.
___
*[`src/shared/services/graphql.service.ts` line 25 at r1](https://reviewable.io/reviews/paranext/paranext-core/520#-NfqwqOp7rLZmB1YiHKD:-Nfr3fEf0ht84DlPfUap:b-crui2j) ([raw file](https://github.com/paranext/paranext-core/blob/320f6629287eb9777851b1a350a1d53ca1113db8/src/shared/services/graphql.service.ts#L25)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

Strictly this is not projects themselves but project's metadata.
</blockquote></details>

yes - This whole area (including and starting with the underlying PDP data model for Paratext projects) probably needs some deeper thought.  That probably would benefit from someone who has deeper experience with what ParatextData exposes in terms of its object model for project contents.
___
*[`src/shared/services/graphql.service.ts` line 34 at r1](https://reviewable.io/reviews/paranext/paranext-core/520#-Nfr-nHA7olSkb3-vhEi:-Nfr434D3INQsKU-zp6R:b-896fix) ([raw file](https://github.com/paranext/paranext-core/blob/320f6629287eb9777851b1a350a1d53ca1113db8/src/shared/services/graphql.service.ts#L34)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

Just like you wouldn't declare `let str: String` (using the string constructor) also here use the type `object` (lowercase).
</blockquote></details>

Done.
___
*[`src/shared/services/graphql.service.ts` line 36 at r1](https://reviewable.io/reviews/paranext/paranext-core/520#-NfqyIio7YdregfGyw05:-Nfr44A57W1iP2_eOjZW:b-896fix) ([raw file](https://github.com/paranext/paranext-core/blob/320f6629287eb9777851b1a350a1d53ca1113db8/src/shared/services/graphql.service.ts#L36)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

It is not necessary to add the initialization. In JS if you declare a variable it is undefined by definition unless it is initialized. Remove the intilaizer and the eslint comment above (this eslint rule exists to make sure we don't add more code than is necessary).
</blockquote></details>

Done.
___
*[`src/shared/services/graphql.service.ts` line 110 at r1](https://reviewable.io/reviews/paranext/paranext-core/520#-Nfr0isF6feLFzzfvaZ6:-Nfr4BzQ2GM06RjVl54H:b4vhabo) ([raw file](https://github.com/paranext/paranext-core/blob/320f6629287eb9777851b1a350a1d53ca1113db8/src/shared/services/graphql.service.ts#L110)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

I imagine this should not happen long-term to stick with expected GraphQL behavior
</blockquote></details>

I'm not sure what the "expected" behavior is in this case.  In most cases people are going over HTTP, and this results object gets mapped in some way to the HTTP response.  But yeah, all of this code, including this line, is quite likely to change.
___
*[`src/shared/services/graphql.service.ts` line 120 at r1](https://reviewable.io/reviews/paranext/paranext-core/520#-Nfr15kfAUeQvSi43c4G:-Nfr4VoNDO8OlDCbGzUq:b1s5kq7) ([raw file](https://github.com/paranext/paranext-core/blob/320f6629287eb9777851b1a350a1d53ca1113db8/src/shared/services/graphql.service.ts#L120)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

I think it could be potentially very beneficial to our performance to put the "backend" of the service on the main process and make it a network object that we call from other processes. That way, we reduce the number of processes to cross to make each call to data providers.

In the far future, we could even maybe make the main process have a supergraph, then the extension host and C# processes could be subgraphs that expose their respective data providers. :)
</blockquote></details>

I'm assuming this code will get rewritten/significantly updated before we consider it "good" for production use.  I went for the very simple approach for now until we have a better sense of really how we want it to work.  I did a slight optimization by caching PDP and project metadata.

**Review by irahopkinson — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/520#-:-NfrfdnZ0jad3jG1j9zV:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
