### PR TITLE
Change some dependencies from dev to peer to eliminate runtime issues

### PR DESCRIPTION
**Pull request by lyonsil**
Suggested changes came from https://github.com/emotion-js/emotion/discussions/2795.

- - -
This change is [Reviewable](https://reviewable.io/reviews/paranext/paranext-core/302)

### CODE REVIEW

**Review by irahopkinson — CHANGES_REQUESTED** [review]
This looks like a good move however see my question.

> Reviewed 9 of 9 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/302#-:-N_eZWwj81HeOpLbtDoR:b-qzwncy)* status: all files reviewed, 1 unresolved discussion (waiting on @lyonsil)

___
*[`lib/papi-components/vite.config.ts` line 26 at r1](https://reviewable.io/reviews/paranext/paranext-core/302#-N_eZD-cAgfgMJGINimj:-N_eZD-cAgfgMJGINimk:b-uxjs17) ([raw file](https://github.com/paranext/paranext-core/blob/5a9ac155266532a638004670ee1525b3cc25ab4e/lib/papi-components/vite.config.ts#L26)):*
> ```XML
>         'react-data-grid',
>         'react-dom',
>         'react/jsx-runtime',
> ```

However, what surprises me is that the build gets bigger without peer dependnecies whereas I would expect it to get smaller:

**Review by lyonsil — COMMENTED** [review]
I wish I had more insight into your observation.

I pushed up one more change as part of this PR.  As part of investigating your observation, I saw that `npm ls` showed a number of version problems with dependencies in papi-components.  I ran `npm dedup` to fix these problems.

> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/302#-:-N_iqq2_68wOHTJ_6x7t:b-gr9ncp)* status: 6 of 9 files reviewed, 1 unresolved discussion (waiting on @irahopkinson)

___
*[`lib/papi-components/vite.config.ts` line 26 at r1](https://reviewable.io/reviews/paranext/paranext-core/302#-N_eZD-cAgfgMJGINimj:-N_il6Q67teVRsK_MGSz:bwifch3) ([raw file](https://github.com/paranext/paranext-core/blob/5a9ac155266532a638004670ee1525b3cc25ab4e/lib/papi-components/vite.config.ts#L26)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

However, what surprises me is that the build gets bigger without peer dependnecies whereas I would expect it to get smaller:


</blockquote></details>

I see the same results as you.  I can't say with confidence what the cause is, and I'm not sure anyone currently on the team has enough detailed knowledge of our builds to explain it.  (If I'm wrong, I'd be happy!)  Here are some potentially relevant points:
- Moving dev dependencies to peer dependencies means the final output of projects using `papi-components` has to bundle the dependencies, right?  I don't know if those dependencies (e.g., react) were already included by the extensions for other reasons.  But as dev dependencies they would not have been forced to be included before.
- In digging through our build setup, I see we are using commonjs outputs.  Docs for webpack and other blogs made it clear that tree shaking requires (or at least is far easier and better supported) with ejs modules rather than cjs.  It might be the case that tools like vite and webpack cannot perform tree shaking as well with how we have our builds setup now.
- I could trim down the list of modules in this block of vite config to remove things that aren't directly imported by us (e.g., `react/jsx-runtime`).  That doesn't seem to impact anything with the size, though.  I'm inclined to leave the extra lines here since they don't hurt anything and it's kind of confusing to have to remember to update 2 places (package.json and vite config) when adding a new dependency.  The extra modules listed here were mentioned as being used by another component library, so it is plausible that we might use them in the future.

After spending several hours looking into this, I don't know how to fix the bug that this PR targets without the change in output size.

**Review by irahopkinson — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/302#-:-N_jV1A5AQGlZU7VxuK6:bnfp4nl)* status: all files reviewed, 1 unresolved discussion

**Review by irahopkinson — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/302)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
