### PR TITLE
181 paratext data linux support

### PR DESCRIPTION
**Pull request by FoolRunning**
Just a draft PR to see if the C# tests testing loading ParatextData will run on Linux/Mac

- - -
This change is [Reviewable](https://reviewable.io/reviews/paranext/paranext-core/216)

### CODE REVIEW

**Review by lyonsil — COMMENTED** [review]
This has been opened up to a "real" PR because I believe it's ready for feedback now that it is working.  We might choose to reject it if there is still substantial work to finish first, but this is important enough to try to move forward.

> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/216#-:-NYKq5JK3wVYdwyJNvSu:b-rcfsty)* status: 0 of 96 files reviewed, all discussions resolved

**Review by irahopkinson — CHANGES_REQUESTED** [review]
I know this has been a lot of work to get it this far. Thanks for all the work on this from both of you.

> Reviewed 91 of 93 files at r1, 3 of 5 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/216#-:-NYL3iqC08ROStTsMHmp:betsbat)* status: all files reviewed, 3 unresolved discussions (waiting on @FoolRunning)

___
*[`assets/ATTRIBUTION.md` line 1 at r3](https://reviewable.io/reviews/paranext/paranext-core/216#-NYKyG8YE4AUJhs-6TtW:-NYKyG8YE4AUJhs-6TtX:bl1euc6) ([raw file](https://github.com/paranext/paranext-core/blob/8dd4a713f16789cc06a83c69f40f4a2141bdf27b/assets/ATTRIBUTION.md#L1)):*
> ```Markdown
> # Attribution
> ```

I don't think you want these here as this is a specific folder used by electron to deliver items to the renderer. If you do want them in the renderer then you might need to update `assests.d.ts`. Otherwise move all these added assets.
___
*[`assets/usfm.sty` line 1 at r3](https://reviewable.io/reviews/paranext/paranext-core/216#-NYKzst-7yiHB8UoRF1s:-NYKzst-7yiHB8UoRF1t:bue92bi) ([raw file](https://github.com/paranext/paranext-core/blob/8dd4a713f16789cc06a83c69f40f4a2141bdf27b/assets/usfm.sty#L1)):*
> ```TeX
> # Version=3.0.4
> ```

This is an almost identical file to the one in the `WEB` folder. Are they meant to be the same? Do we need both? Either way only one is referenced in the `assets/ATTRIBUTION.md` file.
___
*[`c-sharp/Program.cs` line 78 at r3](https://reviewable.io/reviews/paranext/paranext-core/216#-NYL11Zl3L3EYwpFW3Rf:-NYL11Zl3L3EYwpFW3Rg:b-zcesu6) ([raw file](https://github.com/paranext/paranext-core/blob/8dd4a713f16789cc06a83c69f40f4a2141bdf27b/c-sharp/Program.cs#L78)):*
> ```Smalltalk
> 
>     #region DummyRegistry class
>     private sealed class DummyRegistry : RegistryU
> ```

BTW is this a temporary solution to get things going and will eventually be removed? If not we probably don't want this defined in this file.
___
*[`c-sharp-tests/ParatextDataConnectionTests.cs` line 24 at r3](https://reviewable.io/reviews/paranext/paranext-core/216#-NYL2jqE1onTzPoYnEfJ:-NYL2jqE1onTzPoYnEfK:b-yf95wu) ([raw file](https://github.com/paranext/paranext-core/blob/8dd4a713f16789cc06a83c69f40f4a2141bdf27b/c-sharp-tests/ParatextDataConnectionTests.cs#L24)):*
> ```Smalltalk
>             if (!File.Exists(icuConfigFile))
>             {
>                 // It's a bit hacky to hard code the config file here, but there isn't a great
> ```

Actually, its kinda nice to see what config is being used. It might even be useful to control it for given tests in the future.

**Comment by irahopkinson** [comment]
BTW when I run this branch I get these errors in the terminal:

Presummably that's because I don't have the right ICU installed? If so we should add instructions to the README about installing it and think about how we would deliver it on a production build on all OSes.

**Review by lyonsil — COMMENTED** [review]
@irahopkinson That particular error is very likely caused by a missing `icu.net.dll.config` file.  When running normally (i.e., `npm start` or from VSCode), the config file should have been put there by `dotnet restore` as it is part of the dependency package.  When running from `npm test`, there is a known NUnit bug that causes the file not to copy there, but a workaround is checked into the code.

It would be good to understand why that config file is missing in your case.  If this comes up regularly, we might need to put the NUnit workaround in our normal code path so we always inject the file if it is missing.

> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/216#-:-NYOFy2u31GfjWhf3bI5:b2s45wv)* status: all files reviewed, 3 unresolved discussions (waiting on @FoolRunning and @irahopkinson)

___
*[`assets/ATTRIBUTION.md` line 1 at r3](https://reviewable.io/reviews/paranext/paranext-core/216#-NYKyG8YE4AUJhs-6TtW:-NYOHJ1iEwhh77gcKwH6:bp8pulc) ([raw file](https://github.com/paranext/paranext-core/blob/8dd4a713f16789cc06a83c69f40f4a2141bdf27b/assets/ATTRIBUTION.md#L1)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

I don't think you want these here as this is a specific folder used by electron to deliver items to the renderer. If you do want them in the renderer then you might need to update `assests.d.ts`. Otherwise move all these added assets.
</blockquote></details>

Sure - Do you have a suggested location name?
___
*[`assets/usfm.sty` line 1 at r3](https://reviewable.io/reviews/paranext/paranext-core/216#-NYKzst-7yiHB8UoRF1s:-NYOHlhs8QMQdhwtXZLQ:b-24q5mf) ([raw file](https://github.com/paranext/paranext-core/blob/8dd4a713f16789cc06a83c69f40f4a2141bdf27b/assets/usfm.sty#L1)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

This is an almost identical file to the one in the `WEB` folder. Are they meant to be the same? Do we need both? Either way only one is referenced in the `assets/ATTRIBUTION.md` file.
</blockquote></details>

This is likely a mistake.  @FoolRunning Do we need `usfm.sty` in the parent directory of `WEB` and in `WEB` itself?
___
*[`c-sharp/Program.cs` line 78 at r3](https://reviewable.io/reviews/paranext/paranext-core/216#-NYL11Zl3L3EYwpFW3Rf:-NYOI0zQ-qvvqjjEEfGS:b-edm8vl) ([raw file](https://github.com/paranext/paranext-core/blob/8dd4a713f16789cc06a83c69f40f4a2141bdf27b/c-sharp/Program.cs#L78)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

BTW is this a temporary solution to get things going and will eventually be removed? If not we probably don't want this defined in this file.
</blockquote></details>

I think this is a permanent solution, but @FoolRunning should confirm.

**Review by lyonsil — COMMENTED** [review]
@irahopkinson Actually can you run "Debug .NET Core" in VSCode and see what the output shows?  That will give more details on ICU loading errors.  It could be a few different things.

> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/216#-:-NYOIOWP8oiBgQXZm7hy:b-9xrsv0)* status: all files reviewed, 3 unresolved discussions (waiting on @FoolRunning and @irahopkinson)

**Review by FoolRunning — COMMENTED** [review]
Since I'm the original creator of the PR, I can't block it, but consider it blocked until the things I mentioned are cleared up. :smile: 

> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/216#-:-NYO_U8o5Vs2LDPHJEfJ:b-4bicmi)* status: all files reviewed, 4 unresolved discussions (waiting on @irahopkinson and @lyonsil)

___
*[`assets/usfm.sty` line 1 at r3](https://reviewable.io/reviews/paranext/paranext-core/216#-NYKzst-7yiHB8UoRF1s:-NYOXuNP2xrGuQxn8ieH:b-xbkv6z) ([raw file](https://github.com/paranext/paranext-core/blob/8dd4a713f16789cc06a83c69f40f4a2141bdf27b/assets/usfm.sty#L1)):*
<details><summary><i>Previously, lyonsil (Matt Lyons) wrote…</i></summary><blockquote>

This is likely a mistake.  @FoolRunning Do we need `usfm.sty` in the parent directory of `WEB` and in `WEB` itself?
</blockquote></details>

The one in the parent directory (this one) is the one that should be kept. The one in the WEB directory should be deleted.
___
*[`assets/WEB/en.xml` line 1 at r3](https://reviewable.io/reviews/paranext/paranext-core/216#-NYOZS1D-HIzF_D4eGo8:-NYOZS1D-HIzF_D4eGo9:b-9wrpbk) ([raw file](https://github.com/paranext/paranext-core/blob/8dd4a713f16789cc06a83c69f40f4a2141bdf27b/assets/WEB/en.xml#L1)):*
> ```XML
> <?xml version="1.0" encoding="utf-8"?>
> ```

I'm fairly certain this file should be deleted. This is actually an LDML file with an XML extension.
___
*[`c-sharp/Program.cs` line 78 at r3](https://reviewable.io/reviews/paranext/paranext-core/216#-NYL11Zl3L3EYwpFW3Rf:-NYOY3NvAIA_gWKVDw3M:b-fai7d) ([raw file](https://github.com/paranext/paranext-core/blob/8dd4a713f16789cc06a83c69f40f4a2141bdf27b/c-sharp/Program.cs#L78)):*
<details><summary><i>Previously, lyonsil (Matt Lyons) wrote…</i></summary><blockquote>

I think this is a permanent solution, but @FoolRunning should confirm.
</blockquote></details>

Yes, it is permanent (at least through the tech demo). Eventually we might want to get the information for the real Paratext install from the Windows Registry, but I don't think we want to do that yet since it could be potentially dangerous (corruption of a project, for example).

**Review by lyonsil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/216)* status: 93 of 96 files reviewed, 2 unresolved discussions (waiting on @irahopkinson)

___
*[`assets/WEB/en.xml` line 1 at r3](https://reviewable.io/reviews/paranext/paranext-core/216#-NYOZS1D-HIzF_D4eGo8:-NYOo4XN42hKFufKtfop:bb6un1j) ([raw file](https://github.com/paranext/paranext-core/blob/8dd4a713f16789cc06a83c69f40f4a2141bdf27b/assets/WEB/en.xml#L1)):*
<details><summary><i>Previously, FoolRunning (Tim Steenwyk) wrote…</i></summary><blockquote>

I'm fairly certain this file should be deleted. This is actually an LDML file with an XML extension.
</blockquote></details>

Done

**Review by FoolRunning — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/216#-:-NYOy7AyDDJ-99DjsHSb:bnfp4nl)* status: 93 of 96 files reviewed, 2 unresolved discussions (waiting on @irahopkinson)

**Review by lyonsil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/216)* status: 4 of 96 files reviewed, 2 unresolved discussions (waiting on @irahopkinson)

___
*[`assets/ATTRIBUTION.md` line 1 at r3](https://reviewable.io/reviews/paranext/paranext-core/216#-NYKyG8YE4AUJhs-6TtW:-NYPiCea-ex75qY3Zxrb:b-e1hx1h) ([raw file](https://github.com/paranext/paranext-core/blob/8dd4a713f16789cc06a83c69f40f4a2141bdf27b/assets/ATTRIBUTION.md#L1)):*
<details><summary><i>Previously, lyonsil (Matt Lyons) wrote…</i></summary><blockquote>

Sure - Do you have a suggested location name?
</blockquote></details>

Moved the relevant files in the `assets` folder under `c-sharp/assets` per our discussion
___
*[`assets/usfm.sty` line 1 at r3](https://reviewable.io/reviews/paranext/paranext-core/216#-NYKzst-7yiHB8UoRF1s:-NYPiOTJ4w4j_2GurB9s:bb6un1j) ([raw file](https://github.com/paranext/paranext-core/blob/8dd4a713f16789cc06a83c69f40f4a2141bdf27b/assets/usfm.sty#L1)):*
<details><summary><i>Previously, FoolRunning (Tim Steenwyk) wrote…</i></summary><blockquote>

The one in the parent directory (this one) is the one that should be kept. The one in the WEB directory should be deleted.
</blockquote></details>

Done

**Review by irahopkinson — CHANGES_REQUESTED** [review]
I'm still getting this error on Windows.

> Reviewed 2 of 3 files at r4, 89 of 89 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/216#-:-NYPtnA74TkIEvXFcai_:bupq064)* status: all files reviewed, 1 unresolved discussion (waiting on @FoolRunning)

___
*[`assets/ATTRIBUTION.md` line 1 at r1](https://reviewable.io/reviews/paranext/paranext-core/216#-NYPgjEt5QF9jCoH2qy7:-NYPgjEt5QF9jCoH2qy8:big5jrk) ([raw file](https://github.com/paranext/paranext-core/blob/13c5a476ec5898396ba5b059031d3f592199e9e3/assets/ATTRIBUTION.md#L1)):*
> ```Markdown
> # Attribution
> ```

BTW we don't need to shout with the filename, i.e. ALLCAPS. Just use lowercase. We do shout for `README.md` to get peoples attention to start there.
___
*[`assets/usfm.sty` line 1 at r3](https://reviewable.io/reviews/paranext/paranext-core/216#-NYKzst-7yiHB8UoRF1s:-NYPhIpyAtWLXQelLgg_:bwzg80f) ([raw file](https://github.com/paranext/paranext-core/blob/8dd4a713f16789cc06a83c69f40f4a2141bdf27b/assets/usfm.sty#L1)):*
<details><summary><i>Previously, FoolRunning (Tim Steenwyk) wrote…</i></summary><blockquote>

The one in the parent directory (this one) is the one that should be kept. The one in the WEB directory should be deleted.
</blockquote></details>

Do note the one in the `WEB` folder is a later version so should probaly overwrite this one.

**Review by lyonsil — COMMENTED** [review]
I discovered that Microsoft built ICUUC DLLs and makes them available as project references.  I just added it to our c-sharp project, and it got past the error on my laptop.

> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/216#-:-NYQ1DCk4noBYLRHMbKU:b-rzs5fj)* status: 94 of 96 files reviewed, 1 unresolved discussion (waiting on @irahopkinson)

___
*[`assets/ATTRIBUTION.md` line 1 at r1](https://reviewable.io/reviews/paranext/paranext-core/216#-NYPgjEt5QF9jCoH2qy7:-NYQ1TB2AFGmdfiknNjy:bitx5g1) ([raw file](https://github.com/paranext/paranext-core/blob/13c5a476ec5898396ba5b059031d3f592199e9e3/assets/ATTRIBUTION.md#L1)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

BTW we don't need to shout with the filename, i.e. ALLCAPS. Just use lowercase. We do shout for `README.md` to get peoples attention to start there.
</blockquote></details>

I can change it, but we do it for all of our .md files, include README, CODE_OF_CONDUCT, and CHANGELOG.  We actually don't have a change that uses lowercase letters.  This can be our first if we want to change that approach.
___
*[`assets/usfm.sty` line 1 at r3](https://reviewable.io/reviews/paranext/paranext-core/216#-NYKzst-7yiHB8UoRF1s:-NYQ2l-p8M_jZzftxW7p:b-e3liuk) ([raw file](https://github.com/paranext/paranext-core/blob/8dd4a713f16789cc06a83c69f40f4a2141bdf27b/assets/usfm.sty#L1)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

Do note the one in the `WEB` folder is a later version so should probaly overwrite this one.
</blockquote></details>

Ah, good point!  Updated to the newer version (which matches the version currently at the URL in the attribution).

**Review by irahopkinson — APPROVED** [review]
Good find.
:lgtm: It's now working without throwing an exception in Windows. I can see the time ticking again.

> Reviewed 1 of 1 files at r7, 1 of 1 files at r8, 1 of 5 files at r10, 93 of 94 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/216#-:-NYQ45hK0Y_Nbe74QEwM:bjmhuue)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @FoolRunning)

___
*[`assets/ATTRIBUTION.md` line 1 at r1](https://reviewable.io/reviews/paranext/paranext-core/216#-NYPgjEt5QF9jCoH2qy7:-NYQ3inD9gMZGqBxXSiB:b25pac9) ([raw file](https://github.com/paranext/paranext-core/blob/13c5a476ec5898396ba5b059031d3f592199e9e3/assets/ATTRIBUTION.md#L1)):*
<details><summary><i>Previously, lyonsil (Matt Lyons) wrote…</i></summary><blockquote>

I can change it, but we do it for all of our .md files, include README, CODE_OF_CONDUCT, and CHANGELOG.  We actually don't have a change that uses lowercase letters.  This can be our first if we want to change that approach.
</blockquote></details>

Yes please since it's new. We inherited those other three from ERB.

**Review by irahopkinson — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/216#-:-NYQDZz57L3OoN9oTfzN:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @FoolRunning)

**Pull request merged**
