### PR TITLE
Refactor Get Resources into Filterable Resource List PBR component

### PR DESCRIPTION
**Pull request by rolfheij-sil**
This PR:
- moves the Get Resources extension from Platform Bible Internal Extensions into Core
- creates a new Home extension that is basically a copy of Get Resources for now
- refactors Get Resources into a reusable component named Filterable Resource List

This PR does not update the Get Resources implementation in any way, so the code in FilterableResourceList.component.tsx has already been reviewed in [this PR](https://github.com/paranext/paratext-bible-internal-extensions/pull/81)

This change is [Reviewable](https://reviewable.io/reviews/paranext/paranext-core/1363)

### CODE REVIEW

**Review by tjcouch-sil — CHANGES_REQUESTED** [review]
Looking good! Thanks :) just a few little things.

> Reviewed 75 of 100 files at r1, 29 of 29 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/1363#-:-ODgbuyo8wojzT8n7cr5:b-nesfy6)* status: all files reviewed, 8 unresolved discussions (waiting on @rolfheij-sil)

___
*[`extensions/src/platform-get-resources/LICENSE` line 3 at r2](https://reviewable.io/reviews/paranext/paranext-core/1363#-ODgL4al5txoOnJGqj0f:-ODgL4al5txoOnJGqj0g:btf53gy) ([raw file](https://github.com/paranext/paranext-core/blob/4ee32f74c48f8c865846aa475b4f36690cc92e09/extensions/src/platform-get-resources/LICENSE#L3)):*
> ```
> MIT License
> 
> Copyright (c) <year> <copyright_holder_name>
> ```

Need to fill license copyrights in :)
___
*[`extensions/src/platform-home/LICENSE` line 3 at r2](https://reviewable.io/reviews/paranext/paranext-core/1363#-ODgQPoG5EaQqHtJRJAN:-ODgQPoH6xg0MrderKZV:b-r7l132) ([raw file](https://github.com/paranext/paranext-core/blob/4ee32f74c48f8c865846aa475b4f36690cc92e09/extensions/src/platform-home/LICENSE#L3)):*
> ```
> MIT License
> 
> Copyright (c) <year> <copyright_holder_name>
> ```

Copyright
___
*[`assets/localization/en.json` line 7 at r2](https://reviewable.io/reviews/paranext/paranext-core/1363#-ODgF5nm0YtVCMu3SvmO:-ODgF5nm0YtVCMu3SvmP:b-3i0fbx) ([raw file](https://github.com/paranext/paranext-core/blob/28fdd2214bf40142faf5632c54c1d7f2d7995b97/assets/localization/en.json#L7)):*
> ```JSON
>   "%about_db_ip_attribution_intro%": "Internet safety features use data from",
>   "%about_db_ip_attribution_terms%": "Terms",
>   "%downloadResources_errorRegistrationInvalid%": "User registration is not valid. Cannot retrieve resources from DBL.",
> ```

Technically we're not supposed to remove localized strings because that's a breaking change :grimacing: it's fine this once since these are suuuuper specific strings that probably haven't been and won't be used elsewhere. But let's avoid removing strings in the future :)
___
*[`extensions/src/platform-get-resources/src/main.ts` line 23 at r2](https://reviewable.io/reviews/paranext/paranext-core/1363#-ODgPmTU-DTPcfV8sBsU:-ODgPmTU-DTPcfV8sBsV:b-b807dr) ([raw file](https://github.com/paranext/paranext-core/blob/4ee32f74c48f8c865846aa475b4f36690cc92e09/extensions/src/platform-get-resources/src/main.ts#L23)):*
> ```XML
> 
>     return {
>       allowPopups: true,
> ```

What is this for? I think it may not be needed
___
*[`extensions/src/platform-home/README.md` line 5 at r2](https://reviewable.io/reviews/paranext/paranext-core/1363#-ODgQ_pp5AvfeMumPjDb:-ODgQ_pq2S58pcnap106:boag886) ([raw file](https://github.com/paranext/paranext-core/blob/4ee32f74c48f8c865846aa475b4f36690cc92e09/extensions/src/platform-home/README.md#L5)):*
> ```Markdown
> Home screen extension for Platform.Bible
> 
> 
> ```

Commented?
___
*[`extensions/src/platform-home/package.json` line 94 at r2](https://reviewable.io/reviews/paranext/paranext-core/1363#-ODgQY36Bda42NLSC-yb:-ODgQY36Bda42NLSC-yc:bx2kfof) ([raw file](https://github.com/paranext/paranext-core/blob/4ee32f74c48f8c865846aa475b4f36690cc92e09/extensions/src/platform-home/package.json#L94)):*
> ```JSON
>   },
>   "volta": {
>     "node": "20.18.0"
> ```

Volta extend
___
*[`extensions/src/platform-get-resources/README.md` line 5 at r2](https://reviewable.io/reviews/paranext/paranext-core/1363#-ODgMGMFEqjRTP0PU7xl:-ODgMGMFEqjRTP0PU7xm:b-5per5r) ([raw file](https://github.com/paranext/paranext-core/blob/4ee32f74c48f8c865846aa475b4f36690cc92e09/extensions/src/platform-get-resources/README.md#L5)):*
> ```Markdown
> Get resources extension for Platform.Bible
> 
> 
> ```

I think this section still need to be hidden
___
*[`extensions/src/platform-home/src/main.ts` line 23 at r2](https://reviewable.io/reviews/paranext/paranext-core/1363#-ODgbc4U8JSya0OeKnU1:-ODgbc4U8JSya0OeKnU2:b2j7gwk) ([raw file](https://github.com/paranext/paranext-core/blob/4ee32f74c48f8c865846aa475b4f36690cc92e09/extensions/src/platform-home/src/main.ts#L23)):*
> ```XML
> 
>     return {
>       allowPopups: true,
> ```

Also theorize this may not be needed
___
*[`extensions/src/platform-get-resources/package.json` line 93 at r2](https://reviewable.io/reviews/paranext/paranext-core/1363#-ODgLTix8NFe67vQ4v9i:-ODgLTix8NFe67vQ4v9j:bg5ex2z) ([raw file](https://github.com/paranext/paranext-core/blob/4ee32f74c48f8c865846aa475b4f36690cc92e09/extensions/src/platform-get-resources/package.json#L93)):*
> ```JSON
>     "zip-build": "^1.8.0"
>   },
>   "volta": {
> ```

To match other extensions, please change this to the following:

```json
"volta": {
    "extends": "../../package.json"
  }
```

**Review by rolfheij-sil — COMMENTED** [review]
Thanks for reviewing! :)

> Reviewed 74 of 100 files at r1, 12 of 29 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/1363#-:-ODk6nuJDwgZ7SiUhYIa:b2nxsi7)* status: all files reviewed, 6 unresolved discussions (waiting on @tjcouch-sil)

___
*[`assets/localization/en.json` line 7 at r2](https://reviewable.io/reviews/paranext/paranext-core/1363#-ODgF5nm0YtVCMu3SvmO:-ODk5rlZACl9J4nB4cDy:b-pcus16) ([raw file](https://github.com/paranext/paranext-core/blob/28fdd2214bf40142faf5632c54c1d7f2d7995b97/assets/localization/en.json#L7)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

Technically we're not supposed to remove localized strings because that's a breaking change :grimacing: it's fine this once since these are suuuuper specific strings that probably haven't been and won't be used elsewhere. But let's avoid removing strings in the future :)
</blockquote></details>

Oops. Noted.
___
*[`extensions/src/platform-get-resources/LICENSE` line 3 at r2](https://reviewable.io/reviews/paranext/paranext-core/1363#-ODgL4al5txoOnJGqj0f:-ODk67YZEI4zzj4gMxkE:b-896fix) ([raw file](https://github.com/paranext/paranext-core/blob/4ee32f74c48f8c865846aa475b4f36690cc92e09/extensions/src/platform-get-resources/LICENSE#L3)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

Need to fill license copyrights in :)
</blockquote></details>

Done.
___
*[`extensions/src/platform-get-resources/package.json` line 93 at r2](https://reviewable.io/reviews/paranext/paranext-core/1363#-ODgLTix8NFe67vQ4v9i:-ODk6F6-4EnGe7HVDFNy:b-896fix) ([raw file](https://github.com/paranext/paranext-core/blob/4ee32f74c48f8c865846aa475b4f36690cc92e09/extensions/src/platform-get-resources/package.json#L93)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

To match other extensions, please change this to the following:

```json
"volta": {
    "extends": "../../package.json"
  }
```
</blockquote></details>

Done.
___
*[`extensions/src/platform-get-resources/README.md` line 5 at r2](https://reviewable.io/reviews/paranext/paranext-core/1363#-ODgMGMFEqjRTP0PU7xl:-ODk6RGs8RKIt5ILSUf4:bb6un1j) ([raw file](https://github.com/paranext/paranext-core/blob/4ee32f74c48f8c865846aa475b4f36690cc92e09/extensions/src/platform-get-resources/README.md#L5)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

I think this section still need to be hidden
</blockquote></details>

Done
___
*[`extensions/src/platform-get-resources/src/main.ts` line 23 at r2](https://reviewable.io/reviews/paranext/paranext-core/1363#-ODgPmTU-DTPcfV8sBsU:-ODk6aBw8qEz28C74P94:bkk1wl7) ([raw file](https://github.com/paranext/paranext-core/blob/4ee32f74c48f8c865846aa475b4f36690cc92e09/extensions/src/platform-get-resources/src/main.ts#L23)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

What is this for? I think it may not be needed
</blockquote></details>

Don't know where that came from. Maybe I copied it from something else in Platform Bible Internal Extensions. Removed it now.
___
*[`extensions/src/platform-home/LICENSE` line 3 at r2](https://reviewable.io/reviews/paranext/paranext-core/1363#-ODgQPoG5EaQqHtJRJAN:-ODk6isQ8zBxy4R9WlGt:b-896fix) ([raw file](https://github.com/paranext/paranext-core/blob/4ee32f74c48f8c865846aa475b4f36690cc92e09/extensions/src/platform-home/LICENSE#L3)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

Copyright
</blockquote></details>

Done.
___
*[`extensions/src/platform-home/package.json` line 94 at r2](https://reviewable.io/reviews/paranext/paranext-core/1363#-ODgQY36Bda42NLSC-yb:-ODk6j_p65okEpfb8B5U:b-896fix) ([raw file](https://github.com/paranext/paranext-core/blob/4ee32f74c48f8c865846aa475b4f36690cc92e09/extensions/src/platform-home/package.json#L94)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

Volta extend
</blockquote></details>

Done.
___
*[`extensions/src/platform-home/README.md` line 5 at r2](https://reviewable.io/reviews/paranext/paranext-core/1363#-ODgQ_pp5AvfeMumPjDb:-ODk6ldR19yYA4A4eZ67:bb6un1j) ([raw file](https://github.com/paranext/paranext-core/blob/4ee32f74c48f8c865846aa475b4f36690cc92e09/extensions/src/platform-home/README.md#L5)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

Commented?
</blockquote></details>

Done
___
*[`extensions/src/platform-home/src/main.ts` line 23 at r2](https://reviewable.io/reviews/paranext/paranext-core/1363#-ODgbc4U8JSya0OeKnU1:-ODk6n314g9TIe0Xx1gM:b-896fix) ([raw file](https://github.com/paranext/paranext-core/blob/4ee32f74c48f8c865846aa475b4f36690cc92e09/extensions/src/platform-home/src/main.ts#L23)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

Also theorize this may not be needed
</blockquote></details>

Done.

**Review by rolfheij-sil — COMMENTED** [review]
> Reviewed 1 of 100 files at r1, 17 of 29 files at r2.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/1363)* status: 96 of 104 files reviewed, 6 unresolved discussions (waiting on @tjcouch-sil)

**Review by rolfheij-sil — COMMENTED** [review]
> Reviewed 8 of 8 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/1363)* status: 96 of 104 files reviewed, 6 unresolved discussions (waiting on @tjcouch-sil)

**Review by tjcouch-sil — APPROVED** [review]
:lgtm: woo! I didn't follow the discussion super carefully; did you ever get an answer on what to do with the button to open the download resources page if you're in Platform.Bible?

> Reviewed 8 of 8 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/1363#-:-ODmAMCW96UZIO_tvN7l:box6wtp)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Review by rolfheij-sil — COMMENTED** [review]
Yay, thanks! Nope, it's gonna be part of a larger discussion. UX indicated that they currently do not have clear distinctions between designs for Platform and designs for Paratext. They will have to think this through and come to some decisions. I don't know when that will happen

> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/1363#-:-ODmuJHR0Yxp0FUNzv-I:b-nl0h6t)* status: 96 of 104 files reviewed, all discussions resolved (waiting on @tjcouch-sil)

**Review by rolfheij-sil — COMMENTED** [review]
> Reviewed 8 of 8 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/1363)* status: 96 of 104 files reviewed, all discussions resolved

**Review by tjcouch-sil — APPROVED** [review]
> Reviewed 8 of 8 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/1363)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Review by tjcouch-sil — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/1363)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Review by tjcouch-sil — APPROVED** [review]
:lgtm:

> Reviewed 4 of 4 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/1363#-:-ODr7-Nw3NPfbS9W03sH:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Pull request merged**
