### PR TITLE
Add CSharpier formatting

### PR DESCRIPTION
**Pull request by irahopkinson**
- add VSCode extension for CSharpier
- add GHA check
- specify editor width

- format existing C# files

- format TS and other existing files

It may be easier to review the 3 commits separately. The first makes the changes, the second has C# re-formatting (shorter width), the third TS has other file re-formatting (longer width).

- - -
This change is [Reviewable](https://reviewable.io/reviews/paranext/paranext-core/100)

### CODE REVIEW

**Review by tjcouch-sil — CHANGES_REQUESTED** [review]
> Reviewed 9 of 9 files at r1, 7 of 7 files at r2, 42 of 42 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/100)* status: all files reviewed, 4 unresolved discussions (waiting on @irahopkinson)

___
*[`README.md` line 116 at r1](https://reviewable.io/reviews/paranext/paranext-core/100#-NRFKhnH3t62_TFvZS71:-NRFKhnH3t62_TFvZS72:bki5s41) ([raw file](https://github.com/paranext/paranext-core/blob/225ead6ef6f78a6822d33d0bd78d4c8c01cd098f/README.md#L116)):*
> ```Markdown
> ## Formatting and Linting
> 
> Formatting happens automatically when you commit. If you use VS Code with this repo's recommended extensions it will format when you save.
> ```

How does formatting automatically happen when you commit? I expected to see changes to the husky file. That's where the pre-commit linting happens.
___
*[`.vscode/settings.json` line 6 at r1](https://reviewable.io/reviews/paranext/paranext-core/100#-NRFJgAv58vQ1bP8z8sa:-NRFJgAw3FDs2EPUojRV:bbrdy2g) ([raw file](https://github.com/paranext/paranext-core/blob/225ead6ef6f78a6822d33d0bd78d4c8c01cd098f/.vscode/settings.json#L6)):*
> ```JSON
>     "editor.defaultFormatter": "csharpier.csharpier-vscode"
>   },
>   "editor.formatOnSave": true,
> ```

I would prefer not to mandate format on save to be honest. I personally like not having to format until I want to. We can certainly discuss sometime if desired. I also don't see anywhere where prettier is configured to use width 100 - where is that? I expected to see changes in the prettier config file. Are we relying on VSCode's config to tell prettier how to run, or can prettier format to 100 independently?
___
*[`c-sharp/Program.cs` line 10 at r2](https://reviewable.io/reviews/paranext/paranext-core/100#-NRFL9z6CdRZPYNs7st4:-NRFL9z6CdRZPYNs7st5:boclpvq) ([raw file](https://github.com/paranext/paranext-core/blob/fb6e6a5c038f3b06b91de5d3ae20eafca406e2be/c-sharp/Program.cs#L10)):*
> ```Smalltalk
> public static class Program
> {
>     public static async Task Main( /* string[] args */
> ```

Eeewww... Do you know why this formatting is being applied? Can we change it?
___
*[`c-sharp/Web/PapiClient.cs` line 135 at r2](https://reviewable.io/reviews/paranext/paranext-core/100#-NRFLazzDnhX-FaFSLS_:-NRFLazzDnhX-FaFSLSa:bkwy19k) ([raw file](https://github.com/paranext/paranext-core/blob/fb6e6a5c038f3b06b91de5d3ae20eafca406e2be/c-sharp/Web/PapiClient.cs#L135)):*
> ```Smalltalk
>                 Console.WriteLine("Exception while handling response message: {0}", ex);
>             }
>         } while (response == null);
> ```

I personally prefer to have the `while` after the `}` in C# because the `do` is on the line above. Just feels more parallel. Same with `try` and `catch`. Is there a rule for this? What do you think?

**Review by irahopkinson — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/100)* status: 57 of 58 files reviewed, 4 unresolved discussions (waiting on @tjcouch-sil)

___
*[`README.md` line 116 at r1](https://reviewable.io/reviews/paranext/paranext-core/100#-NRFKhnH3t62_TFvZS71:-NRF_SPVCoxR_rP_uY5b:bsycwtp) ([raw file](https://github.com/paranext/paranext-core/blob/225ead6ef6f78a6822d33d0bd78d4c8c01cd098f/README.md#L116)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

How does formatting automatically happen when you commit? I expected to see changes to the husky file. That's where the pre-commit linting happens.
</blockquote></details>

It's already working - this is just documenting that it does do it on commit in the README. Husky [precommit](https://github.com/paranext/paranext-core/blob/main/.husky/pre-commit) calls `lint-staged` which has config on L68 of [package.json](https://github.com/paranext/paranext-core/blob/main/package.json). Additionally the new `c-sharp/.lintstagedrc.yml` file now ensures it happens for C# also. `lint-staged` combines the `package.json` config using prettier with this file for C#. I specifically kept them separate so they can be handled in the expected locations for each.
___
*[`.vscode/settings.json` line 6 at r1](https://reviewable.io/reviews/paranext/paranext-core/100#-NRFJgAv58vQ1bP8z8sa:-NRFbU7x5BSS-SuLXxUI:bjcjsqz) ([raw file](https://github.com/paranext/paranext-core/blob/225ead6ef6f78a6822d33d0bd78d4c8c01cd098f/.vscode/settings.json#L6)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

I would prefer not to mandate format on save to be honest. I personally like not having to format until I want to. We can certainly discuss sometime if desired. I also don't see anywhere where prettier is configured to use width 100 - where is that? I expected to see changes in the prettier config file. Are we relying on VSCode's config to tell prettier how to run, or can prettier format to 100 independently?
</blockquote></details>

Yeah, I debated about adding this one. I included it because it gets formatting happening in the editor sooner. Its pretty jarring to leave until commit but thats an importnat backup. I had assumed if it was on in the Workspace Settings you could still turn it off in the User Settings but I just tried it and that doesn't work. Do you know you can **Save without Formatting** in VS Code (which has a long keyboard shortcut but you can change that)? Would that help you?

Prettier reads compatible config from `.editorconfig` (see `max_line_length = 100` there), that way you only have to specifiy it in one place and its used in both (particularly useful if using some other editor that only respects `.editorconfig`).
___
*[`c-sharp/Program.cs` line 10 at r2](https://reviewable.io/reviews/paranext/paranext-core/100#-NRFL9z6CdRZPYNs7st4:-NRFdXuH5wyCZgQyDbl_:b-r9ktoc) ([raw file](https://github.com/paranext/paranext-core/blob/fb6e6a5c038f3b06b91de5d3ae20eafca406e2be/c-sharp/Program.cs#L10)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

Eeewww... Do you know why this formatting is being applied? Can we change it?
</blockquote></details>

Yeah that was my reaction to that change also - I tried several things to change this to no avail. CSharpier is opinionated for a reason. However after looking at the way it formated other files with args (e.g. see `PapiClient.cs` below), it does make more sense and this is just an unfortunate edge case. One option is to remove the comment. I've 'fixed' it for now by putting the comment on its own line.
___
*[`c-sharp/Web/PapiClient.cs` line 135 at r2](https://reviewable.io/reviews/paranext/paranext-core/100#-NRFLazzDnhX-FaFSLS_:-NRFgDzJ3tJfOqgv0Dur:bybltnn) ([raw file](https://github.com/paranext/paranext-core/blob/fb6e6a5c038f3b06b91de5d3ae20eafca406e2be/c-sharp/Web/PapiClient.cs#L135)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

I personally prefer to have the `while` after the `}` in C# because the `do` is on the line above. Just feels more parallel. Same with `try` and `catch`. Is there a rule for this? What do you think?
</blockquote></details>

Sorry, no rules, CSharpier is opinionated for a reason - to stop endless formatting debate. The only thing we can change in CSharpier is already specified in the `c-sharp/.csharpierrc.yml` file.

**Review by lyonsil — APPROVED** [review]
I scanned through all the updates.  The C# ones all make sense to me with the rules.  There are a couple of small things, but as you mentioned in other comments it's opinionated for a reason.  Nothing here seems egregious, and in all it seems better to have enforced consistency than not, especially when talking about working with a larger group of people spread across multiple organizations.

**Review by tjcouch-sil — APPROVED** [review]
:lgtm: Agreed. Although some of the formatting is a bit unfortunate, it is definitely better to have formatting than not to have it :) thanks for all the hard work on this!!

> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/100#-:-NRJhPLx8uLithkolwjC:b-j3zidj)* status: all files reviewed, 1 unresolved discussion (waiting on @irahopkinson)

___
*[`README.md` line 116 at r1](https://reviewable.io/reviews/paranext/paranext-core/100#-NRFKhnH3t62_TFvZS71:-NRJh4QP0WBJQzzA5zyy:b4fy5a9) ([raw file](https://github.com/paranext/paranext-core/blob/225ead6ef6f78a6822d33d0bd78d4c8c01cd098f/README.md#L116)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

It's already working - this is just documenting that it does do it on commit in the README. Husky [precommit](https://github.com/paranext/paranext-core/blob/main/.husky/pre-commit) calls `lint-staged` which has config on L68 of [package.json](https://github.com/paranext/paranext-core/blob/main/package.json). Additionally the new `c-sharp/.lintstagedrc.yml` file now ensures it happens for C# also. `lint-staged` combines the `package.json` config using prettier with this file for C#. I specifically kept them separate so they can be handled in the expected locations for each.
</blockquote></details>

Aaaah that's neat that it runs the `.lintstagedrc.yml` in directories. Thanks for explaining!
___
*[`.vscode/settings.json` line 6 at r1](https://reviewable.io/reviews/paranext/paranext-core/100#-NRFJgAv58vQ1bP8z8sa:-NRJfAsC0Q47Tu1axCq8:bzivv4) ([raw file](https://github.com/paranext/paranext-core/blob/225ead6ef6f78a6822d33d0bd78d4c8c01cd098f/.vscode/settings.json#L6)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

Yeah, I debated about adding this one. I included it because it gets formatting happening in the editor sooner. Its pretty jarring to leave until commit but thats an importnat backup. I had assumed if it was on in the Workspace Settings you could still turn it off in the User Settings but I just tried it and that doesn't work. Do you know you can **Save without Formatting** in VS Code (which has a long keyboard shortcut but you can change that)? Would that help you?

Prettier reads compatible config from `.editorconfig` (see `max_line_length = 100` there), that way you only have to specifiy it in one place and its used in both (particularly useful if using some other editor that only respects `.editorconfig`).
</blockquote></details>

You have a good point - I'll just give it a shot and try to get used to it. I will try the Save without Formatting thing if I can't get used to the spots that I imagine would be annoying :)

Ah cool! Thanks for sharing. Good to know.

**Pull request merged**
