### PR TITLE
Add communication to web views (Web View Controllers and `postMessageToWebView`)

### LINKED ISSUE #1185: Provide interaction with web views on papi via project or scroll group
**User Story**
As an extension developer, I want to be able to interact with specific web views so that I can make complex interactions between pieces of the UI or different extensions.

**Description**
In order to support #454, we need to add some way to interact with web views for a specific project. Maybe we need to interact with a specific web view type, or maybe we need to interact with all web views focused on a project; not sure.  We probably also need to interact with web views by scroll group.

Maybe we should add some kind of message passing between the web view provider and the web view, then the web view provider can broker the communication. Or open it up so anyone can send messages. Or maybe we add some way to update web view state from the web view provider. Or open it up to anyone.

- [x] Rename stuff (deprecate old stuff but keep for now)
  - [x] `papi.webViews.getWebView` -> `papi.webViews.openWebView`
  - [x] `papi.webViews.getSavedWebViewDefinition` -> `papi.webViews.getOpenWebViewDefinition`
  - [x] `papi.webViews.onDidAddWebView` -> `papi.webViews.onDidOpenWebView`
  - [x] `papi.webViewProviders.register` -> `papi.webViewProviders.registerWebViewProvider`
- [x] Add `papi.webViews.onDidCloseWebView`
- [x] New network object category web view controller: allows others to interact with an api that represents a web view of a certain type. Id of the web view controller is derived from the web view id. Web view providers should register these as part of their `getWebView` if they want one 
  - [x] New method on web view provider service `registerWebViewController` (backend only)
  - [x] New method on web view service `getWebViewController`
  - [x] New shared type `WebViewController`
  - [x] Consider moving web view controller methods to web view service or maybe just `getWebViewController`
  - [x] Maybe make an abstract class `WebViewProvider`
    - [x] Handles the mutex for creating web view controllers
    - [x] Automatically run `dispose` on web view controller or make an optional web view provider method that we call when this happens to make the connection easier...?
- [x] Some form of communication between web view provider and web view - lean on [`postMessage` api](https://developer.mozilla.org/en-US/docs/Web/API/Window/postMessage)?
  - [x] Register request for each web view that gets put on `papi.webViewProviders.postMessageToWebView` or something
  - [x] Add some kind of nonce for some amount of security of communication

#1270 and #1305 split off for another time

### PR DESCRIPTION
**Pull request by tjcouch-sil**
Resolves #1185 

- Web View Controllers are network objects create by Web View Providers that represent web views so other extensions can communicate with them,
- `WebViewFactory` is a new abstract class an extension can implement to combine a Web View Provider with Web View Controllers.
- `papi.webViewProviders.postMessageToWebView` is a new method for sending messages directly to web views. These are communicated via [`postMessage`](https://developer.mozilla.org/en-US/docs/Web/API/Window/postMessage) and can be received in the web view with `window.addEventListener('message', ...)`
  - This method is restricted to use only if you have the new `webViewNonce` which is given to the web view provider via a new third parameter in `IWebViewProvider.getWebView`
- Added aliases and deprecated some names for clearer method names in the web view service. See #1185 for more details
- Misc network fixes, logging adjustments, extension restarting fixes, etc.
  - Fixed extension host web socket not properly disconnecting on restart extension host
  - Made disconnecting client log only the method names that are being removed because they were registered to that client instead of listing all method names
- Added sample web view controllers for hello world project web views. The viewer created from a project web view uses the web view controller to communicate with the project web view.
- Added `papi.webViews.onDidCloseWebView`
- Added `useWebViewController` hook
- Added `globalThis.webViewId` on web views

Known Problems:
- useEventAsync has a bug with subscriptions such that it is causing problems with the web view message handler request when moving the web view and causing it to reload (might be the same reason `useData`'s `isLoading` doesn't work properly)
- Didn't enforce something.something on web view types

image

- - -
This change is [Reviewable](https://reviewable.io/reviews/paranext/paranext-core/1300)

### CODE REVIEW

**Review by lyonsil — CHANGES_REQUESTED** [review]
Looking great! I'm excited to see this come in.

Here are some initial thoughts. Just passing along what I've reviewed for now to help us get through this sooner. I'll review the rest later today if I get some time.

> Reviewed 13 of 27 files at r1, 8 of 12 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/1300#-:-OBacZa04xTknplnG8Sv:b-a8f21r)* status: 15 of 27 files reviewed, 10 unresolved discussions (waiting on @tjcouch-sil)

___
*[`src/shared/global-this.model.ts` line 38 at r1](https://reviewable.io/reviews/paranext/paranext-core/1300#-OBaG2e46bhmh_iUQqSa:-OBaG2e46bhmh_iUQqSb:botjlro) ([raw file](https://github.com/paranext/paranext-core/blob/41642e9c699798e30d3b9f490d712339f48e4b09/src/shared/global-this.model.ts#L38)):*
> ```XML
>   var webViewComponent: FunctionComponent<WebViewProps>;
>   /** The id of the current web view. Only used in WebView iframes. */
>   var webViewId: WebViewId;
> ```

My initial reaction to this is "why not just put this in the renderer's global-this?". Actually the same thought applies to all the webview-related items in this file. I guess the Node processes don't really care there is extra stuff, but it seems like we're targeting the wrong scope.
___
*[`src/shared/services/web-view.service-model.ts` line 26 at r1](https://reviewable.io/reviews/paranext/paranext-core/1300#-OBa6wHPCGpbLHlr_dPl:-OBa6wHPCGpbLHlr_dPm:blbshv0) ([raw file](https://github.com/paranext/paranext-core/blob/41642e9c699798e30d3b9f490d712339f48e4b09/src/shared/services/web-view.service-model.ts#L26)):*
> ```XML
> export interface WebViewServiceType {
>   /** Event that emits with webView info when a webView is added */
>   onDidAddWebView: PlatformEvent<AddWebViewEvent>;
> ```

Would this be a good time to change this to `onDidOpenWebView` to align better with the new `onDidCloseWebView`? Alternatively, we could change `onDidCloseWebView` to `onDidRemoveWebView` to align better with this one. It just seems a little odd to have `Add` and `Close` be the matching verbs.
___
*[`src/shared/services/web-view-provider.service.ts` line 142 at r1](https://reviewable.io/reviews/paranext/paranext-core/1300#-OBaBa8S9GMQKtptrSJp:-OBaBa8S9GMQKtptrSJq:b5zr59j) ([raw file](https://github.com/paranext/paranext-core/blob/41642e9c699798e30d3b9f490d712339f48e4b09/src/shared/services/web-view-provider.service.ts#L142)):*
> ```XML
>     webViewProvider,
>     WEB_VIEW_PROVIDER_OBJECT_TYPE,
>     { webViewType },
> ```

I wonder if we're being a little too loose with these attributes. Below we are providing the type and the ID controllers, while here we are only providing the type for providers. Does it make sense to use a single type for attributes of both and make sure we're setting attributes that align with that type?
___
*[`src/shared/services/web-view-provider.service.ts` line 182 at r1](https://reviewable.io/reviews/paranext/paranext-core/1300#-OBaAq82-XYBnNXUdMNk:-OBaAq82-XYBnNXUdMNl:bbo4zsx) ([raw file](https://github.com/paranext/paranext-core/blob/41642e9c699798e30d3b9f490d712339f48e4b09/src/shared/services/web-view-provider.service.ts#L182)):*
> ```XML
>  * it unless something else in the existing process is subscribed to it.
>  *
>  * @param webViewType Type of webView to check for
> ```

These comments don't match the function signature. Are we intended to be querying by `webViewType` or `webViewId` here?
___
*[`src/shared/services/web-view-provider.service.ts` line 239 at r1](https://reviewable.io/reviews/paranext/paranext-core/1300#-OBaCmp25D2i0JYaDdEO:-OBaCmp25D2i0JYaDdEP:bskq7uv) ([raw file](https://github.com/paranext/paranext-core/blob/41642e9c699798e30d3b9f490d712339f48e4b09/src/shared/services/web-view-provider.service.ts#L239)):*
> ```XML
> 
>   if (webViewControllersById.has(webViewId))
>     logger.warn(
> ```

Why warn instead of throw?
___
*[`src/shared/services/web-view-provider.service.ts` line 284 at r1](https://reviewable.io/reviews/paranext/paranext-core/1300#-OBaDwK8EC6-zJQFXMjt:-OBaDwK8EC6-zJQFXMju:b-7rm4dg) ([raw file](https://github.com/paranext/paranext-core/blob/41642e9c699798e30d3b9f490d712339f48e4b09/src/shared/services/web-view-provider.service.ts#L284)):*
> ```XML
> export interface WebViewProviderService {
>   initialize: typeof initialize;
>   hasKnown: typeof hasKnownWebViewProvider;
> ```

Perhaps deprecate `hasKnown` and `register` and replace them with `hasKnownWebViewProvider` and `registerWebViewProvider`? It seems like that would be cleaner/clearer. Same with the services below.
___
*[`src/renderer/components/web-view.component.tsx` line 85 at r2](https://reviewable.io/reviews/paranext/paranext-core/1300#-OBabfry1ShvohuJsxFZ:-OBabfry1ShvohuJsxF_:bv00l24) ([raw file](https://github.com/paranext/paranext-core/blob/26f6d32d4a4453c3db303d270b77b37de40d4738/src/renderer/components/web-view.component.tsx#L85)):*
> ```XML
>       ([webViewNonce, message, targetOrigin]: Parameters<WebViewMessageRequestHandler>) => {
>         if (webViewNonce !== getWebViewNonce(id))
>           throw new Error(
> ```

Why throw this error but just log the others? I'm not sure why these are treated differently.
___
*[`src/shared/models/web-view-factory.model.ts` line 89 at r1](https://reviewable.io/reviews/paranext/paranext-core/1300#-OBaQ9Ai-ehODg30Vw1p:-OBaQ9Ai-ehODg30Vw1q:bw3zj9l) ([raw file](https://github.com/paranext/paranext-core/blob/41642e9c699798e30d3b9f490d712339f48e4b09/src/shared/models/web-view-factory.model.ts#L89)):*
> ```XML
> 
>       if (webViewDefinition.id !== webViewId)
>         logger.warn(
> ```

What not throw instead of warn? It kind of invalidates the point of locking on the original ID, and I'm not sure what else might be impacted.
___
*[`src/renderer/services/web-view.service-host.ts` line 534 at r2](https://reviewable.io/reviews/paranext/paranext-core/1300#-OBaZzCf8eGCRVD4htel:-OBaZzCf8eGCRVD4htem:bfpo5k4) ([raw file](https://github.com/paranext/paranext-core/blob/26f6d32d4a4453c3db303d270b77b37de40d4738/src/renderer/services/web-view.service-host.ts#L534)):*
> ```XML
>  * @param newLayout The changed layout to save.
>  */
> // TODO: We could filter whether we need to save based on the `direction` argument. - IJH 2023-05-1
> ```

It looks like this "TODO" is done. Perhaps more importantly, the params from the docs no longer match the params from the actual function.
___
*[`src/renderer/services/web-view.service-host.ts` line 815 at r2](https://reviewable.io/reviews/paranext/paranext-core/1300#-OBaaCvFAYlEzZkL00zF:-OBaaCvFAYlEzZkL00zG:baw03ub) ([raw file](https://github.com/paranext/paranext-core/blob/26f6d32d4a4453c3db303d270b77b37de40d4738/src/renderer/services/web-view.service-host.ts#L815)):*
> ```XML
>  * for more info.
>  */
> export function getWebViewNonce(id: WebViewId) {
> ```

There is no return type listed for this method.

It might be safer to not export this function but instead export a function that returns whether a provided nonce value matches the nonce for a provided webViewId. Then retrieving nonces can never leave this module, but you still provide a way for other services to check if a nonce they were given is valid.

**Review by tjcouch-sil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/1300)* status: 8 of 27 files reviewed, 10 unresolved discussions (waiting on @lyonsil)

___
*[`src/renderer/components/web-view.component.tsx` line 85 at r2](https://reviewable.io/reviews/paranext/paranext-core/1300#-OBabfry1ShvohuJsxFZ:-OBadnLmCGb6N5W2UTR6:b-3vksa9) ([raw file](https://github.com/paranext/paranext-core/blob/26f6d32d4a4453c3db303d270b77b37de40d4738/src/renderer/components/web-view.component.tsx#L85)):*
<details><summary><i>Previously, lyonsil (Matt Lyons) wrote…</i></summary><blockquote>

Why throw this error but just log the others? I'm not sure why these are treated differently.
</blockquote></details>

:zany_face: good idea. I wrote these at different times and was thinking more about it when I wrote this one haha
___
*[`src/renderer/services/web-view.service-host.ts` line 534 at r2](https://reviewable.io/reviews/paranext/paranext-core/1300#-OBaZzCf8eGCRVD4htel:-OBaeehM2ju2t5YEF3kT:bh2panr) ([raw file](https://github.com/paranext/paranext-core/blob/26f6d32d4a4453c3db303d270b77b37de40d4738/src/renderer/services/web-view.service-host.ts#L534)):*
<details><summary><i>Previously, lyonsil (Matt Lyons) wrote…</i></summary><blockquote>

It looks like this "TODO" is done. Perhaps more importantly, the params from the docs no longer match the params from the actual function.
</blockquote></details>

The TODO is still valid as we are not avoiding saving based on specific `direction`s. I was kinda avoiding writing descriptions for the parameters, but I went ahead and wrote them here anyway.
___
*[`src/renderer/services/web-view.service-host.ts` line 815 at r2](https://reviewable.io/reviews/paranext/paranext-core/1300#-OBaaCvFAYlEzZkL00zF:-OBaf2Fx8OQOMnukdS8c:bgj53af) ([raw file](https://github.com/paranext/paranext-core/blob/26f6d32d4a4453c3db303d270b77b37de40d4738/src/renderer/services/web-view.service-host.ts#L815)):*
<details><summary><i>Previously, lyonsil (Matt Lyons) wrote…</i></summary><blockquote>

There is no return type listed for this method.

It might be safer to not export this function but instead export a function that returns whether a provided nonce value matches the nonce for a provided webViewId. Then retrieving nonces can never leave this module, but you still provide a way for other services to check if a nonce they were given is valid.
</blockquote></details>

Oh good idea. Duh. Thanks :)
___
*[`src/shared/global-this.model.ts` line 38 at r1](https://reviewable.io/reviews/paranext/paranext-core/1300#-OBaG2e46bhmh_iUQqSa:-OBafqaU2oYXMGljwVyF:b57z779) ([raw file](https://github.com/paranext/paranext-core/blob/41642e9c699798e30d3b9f490d712339f48e4b09/src/shared/global-this.model.ts#L38)):*
<details><summary><i>Previously, lyonsil (Matt Lyons) wrote…</i></summary><blockquote>

My initial reaction to this is "why not just put this in the renderer's global-this?". Actually the same thought applies to all the webview-related items in this file. I guess the Node processes don't really care there is extra stuff, but it seems like we're targeting the wrong scope.
</blockquote></details>

The `global-this` files are kinda weird... I believe VS Code does not respect any kind of boundaries in terms of being able to tell where the different `globalThis` properties are available. I think I put `webViewComponent` here long ago for some specific reason that I don't remember now, and I just figured I'd put `webViewId` wherever `webViewComponent` was since they're pretty similar in some sense. Since they're already a mess without guidance or patterns around what should exactly go where, I'd like to consider the organization of these files another time if that's ok.
___
*[`src/shared/models/web-view-factory.model.ts` line 89 at r1](https://reviewable.io/reviews/paranext/paranext-core/1300#-OBaQ9Ai-ehODg30Vw1p:-OBagcz60aveKEF8j9Lr:b-ngl9uw) ([raw file](https://github.com/paranext/paranext-core/blob/41642e9c699798e30d3b9f490d712339f48e4b09/src/shared/models/web-view-factory.model.ts#L89)):*
<details><summary><i>Previously, lyonsil (Matt Lyons) wrote…</i></summary><blockquote>

What not throw instead of warn? It kind of invalidates the point of locking on the original ID, and I'm not sure what else might be impacted.
</blockquote></details>

Eh probably not worth explaining why I did this or leaving it to be honest. Very esoteric and hopefully unused potential functionality of web view providers. I was on the fence anyway. I'll change it. If someone complains, we can always change something about this another time.
___
*[`src/shared/services/web-view-provider.service.ts` line 142 at r1](https://reviewable.io/reviews/paranext/paranext-core/1300#-OBaBa8S9GMQKtptrSJp:-OBahQ6O3ytG1a7jKZiG:b1n1mrh) ([raw file](https://github.com/paranext/paranext-core/blob/41642e9c699798e30d3b9f490d712339f48e4b09/src/shared/services/web-view-provider.service.ts#L142)):*
<details><summary><i>Previously, lyonsil (Matt Lyons) wrote…</i></summary><blockquote>

I wonder if we're being a little too loose with these attributes. Below we are providing the type and the ID controllers, while here we are only providing the type for providers. Does it make sense to use a single type for attributes of both and make sure we're setting attributes that align with that type?
</blockquote></details>

I'd think each network object type should be free to have its own consistent type of attributes. Since these are two different object types, I gave them two different types of attributes based on things I thought would be relevant for them. We can discuss more if desired.
___
*[`src/shared/services/web-view-provider.service.ts` line 182 at r1](https://reviewable.io/reviews/paranext/paranext-core/1300#-OBaAq82-XYBnNXUdMNk:-OBahotSDJhCjuhU1u1f:b-9fkmmz) ([raw file](https://github.com/paranext/paranext-core/blob/41642e9c699798e30d3b9f490d712339f48e4b09/src/shared/services/web-view-provider.service.ts#L182)):*
<details><summary><i>Previously, lyonsil (Matt Lyons) wrote…</i></summary><blockquote>

These comments don't match the function signature. Are we intended to be querying by `webViewType` or `webViewId` here?
</blockquote></details>

Oh I copied and pasted this from `hasKnownWebViewProvider`. Fixed. Thanks for catching.
___
*[`src/shared/services/web-view-provider.service.ts` line 239 at r1](https://reviewable.io/reviews/paranext/paranext-core/1300#-OBaCmp25D2i0JYaDdEO:-OBaiCQ698-jNxZ157Yr:bp7ux5j) ([raw file](https://github.com/paranext/paranext-core/blob/41642e9c699798e30d3b9f490d712339f48e4b09/src/shared/services/web-view-provider.service.ts#L239)):*
<details><summary><i>Previously, lyonsil (Matt Lyons) wrote…</i></summary><blockquote>

Why warn instead of throw?
</blockquote></details>

We already registered the web view controller. We already checked this condition in `hasKnownWebViewController`, so the only possibility for this happening is if somehow two controllers with the same id got registered at the same exact time and somehow didn't throw an error when they were getting registered on the network. Seems like an exceptionally low chance that this could happen if any at all, and I figured might as well just keep going if we somehow actually hit this point. If we actually hit this line, other bad things have already happened that are much harder to sort out and undo, so let's just note that there was a problem and do our best to keep going so at least the web view controller gets returned and can be properly disposed. Let me know if you still want me to change it to throw an error.
___
*[`src/shared/services/web-view-provider.service.ts` line 284 at r1](https://reviewable.io/reviews/paranext/paranext-core/1300#-OBaDwK8EC6-zJQFXMjt:-OBajVA_029goiIHiFy_:bnjeyom) ([raw file](https://github.com/paranext/paranext-core/blob/41642e9c699798e30d3b9f490d712339f48e4b09/src/shared/services/web-view-provider.service.ts#L284)):*
<details><summary><i>Previously, lyonsil (Matt Lyons) wrote…</i></summary><blockquote>

Perhaps deprecate `hasKnown` and `register` and replace them with `hasKnownWebViewProvider` and `registerWebViewProvider`? It seems like that would be cleaner/clearer. Same with the services below.
</blockquote></details>

Oh I didn't even process that `hasKnown` was exposed outside this service. It isn't used anywhere. I'm just going to remove it. Note it isn't on the `papi` version; just core code.

Good idea on renaming; done.
___
*[`src/shared/services/web-view.service-model.ts` line 26 at r1](https://reviewable.io/reviews/paranext/paranext-core/1300#-OBa6wHPCGpbLHlr_dPl:-OBamGr12rJul0bk-cya:bafw9fz) ([raw file](https://github.com/paranext/paranext-core/blob/41642e9c699798e30d3b9f490d712339f48e4b09/src/shared/services/web-view.service-model.ts#L26)):*
<details><summary><i>Previously, lyonsil (Matt Lyons) wrote…</i></summary><blockquote>

Would this be a good time to change this to `onDidOpenWebView` to align better with the new `onDidCloseWebView`? Alternatively, we could change `onDidCloseWebView` to `onDidRemoveWebView` to align better with this one. It just seems a little odd to have `Add` and `Close` be the matching verbs.
</blockquote></details>

I thought about this, too, but I just didn't end up taking any action. Done.

I actually started by making it `onDidRemoveWebView`, but I decided this made no sense and the `Add` didn't make sense either :joy: so I changed the new one but not the existing one.

**Review by lyonsil — COMMENTED** [review]
> Reviewed 4 of 9 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/1300)* status: 12 of 27 files reviewed, all discussions resolved

___
*[`src/shared/global-this.model.ts` line 38 at r1](https://reviewable.io/reviews/paranext/paranext-core/1300#-OBaG2e46bhmh_iUQqSa:-OBbcGOFC7r1VCqVSYXq:bkvfdfv) ([raw file](https://github.com/paranext/paranext-core/blob/41642e9c699798e30d3b9f490d712339f48e4b09/src/shared/global-this.model.ts#L38)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

The `global-this` files are kinda weird... I believe VS Code does not respect any kind of boundaries in terms of being able to tell where the different `globalThis` properties are available. I think I put `webViewComponent` here long ago for some specific reason that I don't remember now, and I just figured I'd put `webViewId` wherever `webViewComponent` was since they're pretty similar in some sense. Since they're already a mess without guidance or patterns around what should exactly go where, I'd like to consider the organization of these files another time if that's ok.
</blockquote></details>

Yeah we can reorganize later. It was just strange to me.
___
*[`src/shared/services/web-view-provider.service.ts` line 142 at r1](https://reviewable.io/reviews/paranext/paranext-core/1300#-OBaBa8S9GMQKtptrSJp:-OBbSCkh8TrsZsOWXLog:b-7ydu0b) ([raw file](https://github.com/paranext/paranext-core/blob/41642e9c699798e30d3b9f490d712339f48e4b09/src/shared/services/web-view-provider.service.ts#L142)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

I'd think each network object type should be free to have its own consistent type of attributes. Since these are two different object types, I gave them two different types of attributes based on things I thought would be relevant for them. We can discuss more if desired.
</blockquote></details>

Ok, makes sense. This is aligned with how we've done this in other places, too, so if we want to formalize types better we can do it in a larger pass.
___
*[`src/shared/services/web-view-provider.service.ts` line 239 at r1](https://reviewable.io/reviews/paranext/paranext-core/1300#-OBaCmp25D2i0JYaDdEO:-OBbUCYqCriTdvTk21dh:b332gn1) ([raw file](https://github.com/paranext/paranext-core/blob/41642e9c699798e30d3b9f490d712339f48e4b09/src/shared/services/web-view-provider.service.ts#L239)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

We already registered the web view controller. We already checked this condition in `hasKnownWebViewController`, so the only possibility for this happening is if somehow two controllers with the same id got registered at the same exact time and somehow didn't throw an error when they were getting registered on the network. Seems like an exceptionally low chance that this could happen if any at all, and I figured might as well just keep going if we somehow actually hit this point. If we actually hit this line, other bad things have already happened that are much harder to sort out and undo, so let's just note that there was a problem and do our best to keep going so at least the web view controller gets returned and can be properly disposed. Let me know if you still want me to change it to throw an error.
</blockquote></details>

I guess in my mind if we got into a really bad spot that's when we'd want to throw instead of limping along. But I don't feel that strongly about it. As you say this shouldn't really happen.

**Review by lyonsil — CHANGES_REQUESTED** [review]
> Reviewed 8 of 27 files at r1, 2 of 12 files at r2, 5 of 9 files at r3.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/1300)* status: all files reviewed, 3 unresolved discussions (waiting on @tjcouch-sil)

___
*[`src/declarations/papi-shared-types.ts` line 577 at r3](https://reviewable.io/reviews/paranext/paranext-core/1300#-OBbhMyf2H5pWQJulZVe:-OBbhMyf2H5pWQJulZVf:bet1sh3) ([raw file](https://github.com/paranext/paranext-core/blob/fc44dfaac1a67ef81c4f51fccfa2d62d6d63d2fe/src/declarations/papi-shared-types.ts#L577)):*
> ```XML
>    */
>   export interface WebViewControllers {
>     'platform.stuffWebView': NetworkableObject<{ doStuff(thing: string): Promise<boolean> }>;
> ```

I'm assuming we can erase these two placeholders once we put something real in place, right?
___
*[`src/main/services/extension-host.service.ts` line 91 at r3](https://reviewable.io/reviews/paranext/paranext-core/1300#-OBbgBgV9uXHmhYCKzJr:-OBbgBgV9uXHmhYCKzJs:b-x632go) ([raw file](https://github.com/paranext/paranext-core/blob/fc44dfaac1a67ef81c4f51fccfa2d62d6d63d2fe/src/main/services/extension-host.service.ts#L91)):*
> ```XML
>   // Tells nodemon to restart the process https://github.com/remy/nodemon/blob/HEAD/doc/events.md#using-nodemon-as-child-process
>   extensionHost?.send('restart');
>   return undefined;
> ```

Not a big deal, but I don't think you need a `return` statement here at all.
___
*[`src/extension-host/services/extension.service.ts` line 1212 at r3](https://reviewable.io/reviews/paranext/paranext-core/1300#-OBbm8iS3v_Ld2IVlI9B:-OBbm8iS3v_Ld2IVlI9C:bheyzpq) ([raw file](https://github.com/paranext/paranext-core/blob/fc44dfaac1a67ef81c4f51fccfa2d62d6d63d2fe/src/extension-host/services/extension.service.ts#L1212)):*
> ```XML
>       shouldReload = false;
>       reloadExtensions(shouldDeactivateExtensions, shouldEmitDidReloadEvent);
>     })();
> ```

Doesn't this turn into an unawaited promise that we know can throw? Seems like we should at least `try`/`catch` around the `reloadExtensions` call and log the error message.

An alternative approach to this whole thing would be to wrap extension reloading with a mutex so it only runs one at a time. Then any errors would always be seen.

**Review by lyonsil — APPROVED** [review]
:lgtm:

> Reviewed 4 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/1300#-:-OBbsEmKEB__EzNL3-lv:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

___
*[`src/extension-host/services/extension.service.ts` line 1212 at r3](https://reviewable.io/reviews/paranext/paranext-core/1300#-OBbm8iS3v_Ld2IVlI9B:-OBbruVS99cv8oLWpVg4:b-ucfknh) ([raw file](https://github.com/paranext/paranext-core/blob/fc44dfaac1a67ef81c4f51fccfa2d62d6d63d2fe/src/extension-host/services/extension.service.ts#L1212)):*
<details><summary><i>Previously, lyonsil (Matt Lyons) wrote…</i></summary><blockquote>

Doesn't this turn into an unawaited promise that we know can throw? Seems like we should at least `try`/`catch` around the `reloadExtensions` call and log the error message.

An alternative approach to this whole thing would be to wrap extension reloading with a mutex so it only runs one at a time. Then any errors would always be seen.
</blockquote></details>

Thanks!
___
*[`src/main/services/extension-host.service.ts` line 91 at r3](https://reviewable.io/reviews/paranext/paranext-core/1300#-OBbgBgV9uXHmhYCKzJr:-OBbrzpj2VvYZlbDFUSI:b-ucfknh) ([raw file](https://github.com/paranext/paranext-core/blob/fc44dfaac1a67ef81c4f51fccfa2d62d6d63d2fe/src/main/services/extension-host.service.ts#L91)):*
<details><summary><i>Previously, lyonsil (Matt Lyons) wrote…</i></summary><blockquote>

Not a big deal, but I don't think you need a `return` statement here at all.
</blockquote></details>

Thanks!

**Review by lyonsil — APPROVED** [review]
https://tenor.com/view/the-schuyler-sisters-hamilton-schuyler-hamilfilm-angelica-schuyler-gif-17826335

> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/1300#-:-OBbsPeo6YmfM8-ktwaA:b-mwgig6)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Review by tjcouch-sil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/1300)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

___
*[`src/declarations/papi-shared-types.ts` line 577 at r3](https://reviewable.io/reviews/paranext/paranext-core/1300#-OBbhMyf2H5pWQJulZVe:-OBbnTX7DtjdAFAUNZw4:b-sxnzmb) ([raw file](https://github.com/paranext/paranext-core/blob/fc44dfaac1a67ef81c4f51fccfa2d62d6d63d2fe/src/declarations/papi-shared-types.ts#L577)):*
<details><summary><i>Previously, lyonsil (Matt Lyons) wrote…</i></summary><blockquote>

I'm assuming we can erase these two placeholders once we put something real in place, right?
</blockquote></details>

I imagine so :)
___
*[`src/extension-host/services/extension.service.ts` line 1212 at r3](https://reviewable.io/reviews/paranext/paranext-core/1300#-OBbm8iS3v_Ld2IVlI9B:-OBbpbf5Bp1hs1IAAr5n:b-9yza6q) ([raw file](https://github.com/paranext/paranext-core/blob/fc44dfaac1a67ef81c4f51fccfa2d62d6d63d2fe/src/extension-host/services/extension.service.ts#L1212)):*
<details><summary><i>Previously, lyonsil (Matt Lyons) wrote…</i></summary><blockquote>

Doesn't this turn into an unawaited promise that we know can throw? Seems like we should at least `try`/`catch` around the `reloadExtensions` call and log the error message.

An alternative approach to this whole thing would be to wrap extension reloading with a mutex so it only runs one at a time. Then any errors would always be seen.
</blockquote></details>

Oops! Good find. Added try/catch.
___
*[`src/main/services/extension-host.service.ts` line 91 at r3](https://reviewable.io/reviews/paranext/paranext-core/1300#-OBbgBgV9uXHmhYCKzJr:-OBbofpx0qhGDFe8-T-l:bqk54uv) ([raw file](https://github.com/paranext/paranext-core/blob/fc44dfaac1a67ef81c4f51fccfa2d62d6d63d2fe/src/main/services/extension-host.service.ts#L91)):*
<details><summary><i>Previously, lyonsil (Matt Lyons) wrote…</i></summary><blockquote>

Not a big deal, but I don't think you need a `return` statement here at all.
</blockquote></details>

Oh good catch. I guess there was an "inconsistent returns" error at some point, but I guess it went away later.
___
*[`src/shared/services/web-view-provider.service.ts` line 239 at r1](https://reviewable.io/reviews/paranext/paranext-core/1300#-OBaCmp25D2i0JYaDdEO:-OBbdpDH8kxpga7k9XMA:b499q7j) ([raw file](https://github.com/paranext/paranext-core/blob/41642e9c699798e30d3b9f490d712339f48e4b09/src/shared/services/web-view-provider.service.ts#L239)):*
<details><summary><i>Previously, lyonsil (Matt Lyons) wrote…</i></summary><blockquote>

I guess in my mind if we got into a really bad spot that's when we'd want to throw instead of limping along. But I don't feel that strongly about it. As you say this shouldn't really happen.
</blockquote></details>

Changed

**Comment by irahopkinson** [comment]
*[`src/main/services/extension-host.service.ts` line 91 at r3](https://reviewable.io/reviews/paranext/paranext-core/1300#-OBbgBgV9uXHmhYCKzJr:-OBbnxVq5jym6cr6p_5m:bk1ev5p) ([raw file](https://github.com/paranext/paranext-core/blob/fc44dfaac1a67ef81c4f51fccfa2d62d6d63d2fe/src/main/services/extension-host.service.ts#L91)):*
<details><summary><i>Previously, lyonsil (Matt Lyons) wrote…</i></summary><blockquote>

Not a big deal, but I don't think you need a `return` statement here at all.
</blockquote></details>

Yep, that changed with the type checking PR. We turned off the `consistent-return` eslint rule and let TSC get it right with `noImplicitReturns`.

**Comment by irahopkinson** [comment]
*[`extensions/src/hello-world/src/main.ts` line 112 at r2](https://reviewable.io/reviews/paranext/paranext-core/1300#-OBbbFP34i_hlFi82tYZ:-OBbbFP34i_hlFi82tY_:b1mmdm8) ([raw file](https://github.com/paranext/paranext-core/blob/26f6d32d4a4453c3db303d270b77b37de40d4738/extensions/src/hello-world/src/main.ts#L112)):*
> ```XML
> 
>   // No need to use `this` and implementing an abstract method so can't be static
>   // eslint-disable-next-line class-methods-use-this
> ```

FYI This seems like it shouldn't be necessary and indeed https://typescript-eslint.io/rules/class-methods-use-this/ accounts for overrides but we are using the eslint rule not this TS one. I'll make a PR to fix-up this rule.

**Pull request merged**
