### PR TITLE
Fix issues with reference selector component

### LINKED ISSUE #322: Fix issues in `ref-selector.component.tsx`
- [x] `ref-selector.component.tsx` is having issues with matching up its `options` and its `value`. Let's reformat the component and the scripture util to use consistent object references instead of creating new objects frequently.

[This commit](https://github.com/paranext/paranext-core/commit/b3d7877113605792eff9f25a32056afb8b61740d#diff-540bcf29c5a0d26447b76e61841e82af071c31c1f436ae2b0da4a662d7cd5149) has a quick fix to the problem. Essentially, I compared the values of the props of the book display names so the reference itself doesn't matter (like an easier version of deep equality).

Before the quick fix, `value` was not actually contained in `options` because the object references were different, so you had this problem:

Image

When it gathers its `options`, the scripture util gives it a unique set of options (lots of new objects with new references and such). Maybe we should cache the book name options or something so they are shared amongst the many scripture util functions that can give them.

- [x] `currentBookOption` is unnecessary state that accidentally causes the component to be both controlled and uncontrolled. Because `currentBookOption` is a state that starts with a value based on a prop, that state stays at the same value as the prop originally was when you first created the component. `setCurrentBookOption` gets called when the selector changes the book, but nothing updates `currentBookOption` when the prop changes (Note just fyi: you could fix this by making a `useEffect` that listens for changes to the prop and updates `currentBookOption`, but let's not do that since we don't actually need to hold or internally edit this state). Since `currentBookOption` is really just a helpful value that is derived from the prop, it can be changed to `useMemo`. `useMemo` allows us to derive some value from the prop every time the prop changes. Now that value is controlled because the prop determines its value instead of being its own uncontrolled state. You don't have to worry about updating the state all the time when you change the book because the value will be updated when the prop is updated! :)

### PR DESCRIPTION
**Pull request by rolfheij-sil**
Resolves #322 

This change is [Reviewable](https://reviewable.io/reviews/paranext/paranext-core/346)

### CODE REVIEW

**Review by rolfheij-sil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/346)* status: 0 of 8 files reviewed, 1 unresolved discussion

___
*[`lib/papi-components/src/ref-selector.component.tsx` line 52 at r1](https://reviewable.io/reviews/paranext/paranext-core/346#-NbFgJBREvgtO_MejFb5:-NbFgJBREvgtO_MejFb6:bf7tsie) ([raw file](https://github.com/paranext/paranext-core/blob/c5d900f6ed1109580292cffbba39ec902f602ab8/lib/papi-components/src/ref-selector.component.tsx#L52)):*
> ```XML
>         title="Book"
>         className="papi-ref-selector book"
>         value={bookNames[scrRef.bookNum - 1]}
> ```

Is this okay? It feels illegal for some reason.
I'm still not fully comfortable with the controlled/uncontrolled paradigms

**Review by tjcouch-sil — CHANGES_REQUESTED** [review]
Good stuff :) looking forward to having these improvements in! Thanks!

> Reviewed 8 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/346#-:-NbFjPDpCjSd2IUiEeFv:bpsgnpf)* status: all files reviewed, 2 unresolved discussions (waiting on @rolfheij-sil)

___
*[`lib/papi-components/src/ref-selector.component.tsx` line 26 at r1](https://reviewable.io/reviews/paranext/paranext-core/346#-NbFi8ee02S3y_nY0VmH:-NbFi8ee02S3y_nY0VmI:bihb9l4) ([raw file](https://github.com/paranext/paranext-core/blob/c5d900f6ed1109580292cffbba39ec902f602ab8/lib/papi-components/src/ref-selector.component.tsx#L26)):*
> ```XML
> 
> function RefSelector({ scrRef, handleSubmit }: ScrRefSelectorProps) {
>   const bookNames = useMemo(() => getBookNameOptions(), []);
> ```

Since this value does not depend on any props (so it does not change between functions) and does not change (so it doesn't cause rerenders), you can actually just take this out of the function component and put it above without a hook at all (like `const bookNames = getBookNameOptions()`. But then I wonder if `getBookNameOptions` should just memoize the value itself so you don't have to worry about it in here. I imagine this function will be called commonly and will frequently have this problem.
___
*[`lib/papi-components/src/ref-selector.component.tsx` line 52 at r1](https://reviewable.io/reviews/paranext/paranext-core/346#-NbFgJBREvgtO_MejFb5:-NbFiY3J2gEXDgfqpTLf:bffq4ni) ([raw file](https://github.com/paranext/paranext-core/blob/c5d900f6ed1109580292cffbba39ec902f602ab8/lib/papi-components/src/ref-selector.component.tsx#L52)):*
<details><summary><i>Previously, rolfheij-sil wrote…</i></summary><blockquote>

Is this okay? It feels illegal for some reason.
I'm still not fully comfortable with the controlled/uncontrolled paradigms
</blockquote></details>

This works fine. Another way to do this so it doesn't compute with every render would be to put this calculation into a `useMemo`, but it's ok like this as well.

**Review by rolfheij-sil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/346)* status: all files reviewed, 1 unresolved discussion (waiting on @tjcouch-sil)

___
*[`lib/papi-components/src/ref-selector.component.tsx` line 26 at r1](https://reviewable.io/reviews/paranext/paranext-core/346#-NbFi8ee02S3y_nY0VmH:-NbKAwevBya6NyRYM75o:bn19geq) ([raw file](https://github.com/paranext/paranext-core/blob/c5d900f6ed1109580292cffbba39ec902f602ab8/lib/papi-components/src/ref-selector.component.tsx#L26)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

Since this value does not depend on any props (so it does not change between functions) and does not change (so it doesn't cause rerenders), you can actually just take this out of the function component and put it above without a hook at all (like `const bookNames = getBookNameOptions()`. But then I wonder if `getBookNameOptions` should just memoize the value itself so you don't have to worry about it in here. I imagine this function will be called commonly and will frequently have this problem.
</blockquote></details>

I tried adding memoization in scriptureUtils. I based it on code that I found in some articles, and got some help from chatGPT. I think it works...

**Review by rolfheij-sil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/346)* status: all files reviewed, 1 unresolved discussion (waiting on @tjcouch-sil)

___
*[`lib/papi-components/src/ref-selector.component.tsx` line 26 at r1](https://reviewable.io/reviews/paranext/paranext-core/346#-NbFi8ee02S3y_nY0VmH:-NbKBCZc6cZQUpxm91_0:b34uoy0) ([raw file](https://github.com/paranext/paranext-core/blob/c5d900f6ed1109580292cffbba39ec902f602ab8/lib/papi-components/src/ref-selector.component.tsx#L26)):*
<details><summary><i>Previously, rolfheij-sil wrote…</i></summary><blockquote>

I tried adding memoization in scriptureUtils. I based it on code that I found in some articles, and got some help from chatGPT. I think it works...
</blockquote></details>

https://www.npmjs.com/package/typescript-memoize 
This might also work?

**Review by tjcouch-sil — CHANGES_REQUESTED** [review]
> Reviewed 7 of 7 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/346)* status: all files reviewed, 2 unresolved discussions (waiting on @rolfheij-sil)

___
*[`lib/papi-components/src/ref-selector.component.tsx` line 26 at r1](https://reviewable.io/reviews/paranext/paranext-core/346#-NbFi8ee02S3y_nY0VmH:-NbKeN2K9b4fONHC-xVZ:b-t4pqit) ([raw file](https://github.com/paranext/paranext-core/blob/c5d900f6ed1109580292cffbba39ec902f602ab8/lib/papi-components/src/ref-selector.component.tsx#L26)):*
<details><summary><i>Previously, rolfheij-sil wrote…</i></summary><blockquote>

https://www.npmjs.com/package/typescript-memoize 
This might also work?
</blockquote></details>

Yeah, you got it! You can make it a bit simpler, though, if you want; you don't need to build a memo function or another fetch function backing it up. I think the term "memoize" is a pretty JS-exclusive term and isn't particularly necessary to use in this context, so maybe I should have said "cache" to convey a simpler concept. What you did essentially caches the output of the `getBookNameOptions` function so it always returns the same thing and doesn't have to recompute the objects and re-create their references. That's essentially what I was suggesting. But to simplify, there are a couple of options:

1. Simple caching: basically you can just make a `bookNameOptions` variable in `scripture-util.ts`. Then you check if it is defined when you run `getBookNameOptions` and just return it if it is defined. Then actually create it, save it out to the new `bookNameOptions` cache variable, and return it.
2. Use a memoizing library and wrap over an arrow function: alternatively you can use something like the `memoizeOne` library ([example use in our code](https://github.com/paranext/paranext-core/blob/e7a12aac41c50bbeb654ac632011b53a79bd672d/src/node/utils/util.ts#L47)) that basically provides memoization for you (its memoization works for a specific use case, but it's fine here since there are no parameters). So you just do `const getBookNameOptions = memoizeOne(() => {...})` (you could also just modify what you have now to use an inline arrow function; that part isn't unique to `memoizeOne`).

Both of these options are just a slight tweak to what you did to make things a bit simpler. What you have also works if you want to stick with that. Just might be a bit more difficult to understand, and might lead people to use the fetch version accidentally, which we probably don't want.

Now, since you have cached/memoized `getBookNameOptions`, you can use it in other functions that use book name options so you are still using the same object references even across functions like in `bookNumToBookOption` (where you would run `getBookNameOptions` and pick the appropriate object out of its return; don't use the actual `bookNameOptions` variable elsewhere). Actually, I think that needs to happen, so I'll make a comment there.
___
*[`lib/papi-components/src/ref-selector.component.tsx` line 52 at r1](https://reviewable.io/reviews/paranext/paranext-core/346#-NbFgJBREvgtO_MejFb5:-NbKbibz3O9eAAFeRmJN:btbbtod) ([raw file](https://github.com/paranext/paranext-core/blob/c5d900f6ed1109580292cffbba39ec902f602ab8/lib/papi-components/src/ref-selector.component.tsx#L52)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

This works fine. Another way to do this so it doesn't compute with every render would be to put this calculation into a `useMemo`, but it's ok like this as well.
</blockquote></details>

I recommend taking the hook out and putting it above the JSX area. Generally, it's cleaner to have logic (like hooks and such that get to the values you want to display) higher in the function component and kinda separated from the visuals (JSX stuff) lower in the function component. However, this does work as-is.
___
*[`lib/papi-components/src/scripture/scripture-util.ts` line 106 at r2](https://reviewable.io/reviews/paranext/paranext-core/346#-NbKfp9o2KoY957p9Hy_:-NbKfp9o2KoY957p9Hya:b-ayrv6v) ([raw file](https://github.com/paranext/paranext-core/blob/0203f28f19ee3badbfc00f2a30802434872b84cb/lib/papi-components/src/scripture/scripture-util.ts#L106)):*
> ```XML
> 
> export function bookNumToBookOption(bookNum: number): BookNameOption {
>   return {
> ```

This function should call `getBookNameOptions` and get the correct value from there so you are using the same object references :) there may be other functions like this; I haven't looked around.

**Review by rolfheij-sil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/346)* status: all files reviewed, 2 unresolved discussions (waiting on @tjcouch-sil)

___
*[`lib/papi-components/src/ref-selector.component.tsx` line 26 at r1](https://reviewable.io/reviews/paranext/paranext-core/346#-NbFi8ee02S3y_nY0VmH:-NbL4O5KD-eYwOsTcSM5:bf280l9) ([raw file](https://github.com/paranext/paranext-core/blob/c5d900f6ed1109580292cffbba39ec902f602ab8/lib/papi-components/src/ref-selector.component.tsx#L26)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

Yeah, you got it! You can make it a bit simpler, though, if you want; you don't need to build a memo function or another fetch function backing it up. I think the term "memoize" is a pretty JS-exclusive term and isn't particularly necessary to use in this context, so maybe I should have said "cache" to convey a simpler concept. What you did essentially caches the output of the `getBookNameOptions` function so it always returns the same thing and doesn't have to recompute the objects and re-create their references. That's essentially what I was suggesting. But to simplify, there are a couple of options:

1. Simple caching: basically you can just make a `bookNameOptions` variable in `scripture-util.ts`. Then you check if it is defined when you run `getBookNameOptions` and just return it if it is defined. Then actually create it, save it out to the new `bookNameOptions` cache variable, and return it.
2. Use a memoizing library and wrap over an arrow function: alternatively you can use something like the `memoizeOne` library ([example use in our code](https://github.com/paranext/paranext-core/blob/e7a12aac41c50bbeb654ac632011b53a79bd672d/src/node/utils/util.ts#L47)) that basically provides memoization for you (its memoization works for a specific use case, but it's fine here since there are no parameters). So you just do `const getBookNameOptions = memoizeOne(() => {...})` (you could also just modify what you have now to use an inline arrow function; that part isn't unique to `memoizeOne`).

Both of these options are just a slight tweak to what you did to make things a bit simpler. What you have also works if you want to stick with that. Just might be a bit more difficult to understand, and might lead people to use the fetch version accidentally, which we probably don't want.

Now, since you have cached/memoized `getBookNameOptions`, you can use it in other functions that use book name options so you are still using the same object references even across functions like in `bookNumToBookOption` (where you would run `getBookNameOptions` and pick the appropriate object out of its return; don't use the actual `bookNameOptions` variable elsewhere). Actually, I think that needs to happen, so I'll make a comment there.
</blockquote></details>

Okay, it's simpler now. Are you okay with it?
And a comprehension question: If we create a variable that is not of a native type, it is stored on the heap, right? And that is why we can use it to cache things. Is it also 'static' in a way? So that when two different components include `scripture-util` and call `getBookNameOptions` they access the same heap address? That would be really awesome.
___
*[`lib/papi-components/src/ref-selector.component.tsx` line 52 at r1](https://reviewable.io/reviews/paranext/paranext-core/346#-NbFgJBREvgtO_MejFb5:-NbL4zA87lwyhN-VenSP:bb6un1j) ([raw file](https://github.com/paranext/paranext-core/blob/c5d900f6ed1109580292cffbba39ec902f602ab8/lib/papi-components/src/ref-selector.component.tsx#L52)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

I recommend taking the hook out and putting it above the JSX area. Generally, it's cleaner to have logic (like hooks and such that get to the values you want to display) higher in the function component and kinda separated from the visuals (JSX stuff) lower in the function component. However, this does work as-is.
</blockquote></details>

Done
___
*[`lib/papi-components/src/scripture/scripture-util.ts` line 106 at r2](https://reviewable.io/reviews/paranext/paranext-core/346#-NbKfp9o2KoY957p9Hy_:-NbL50sA8GRajexQ-_Qd:b-n75p8h) ([raw file](https://github.com/paranext/paranext-core/blob/0203f28f19ee3badbfc00f2a30802434872b84cb/lib/papi-components/src/scripture/scripture-util.ts#L106)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

This function should call `getBookNameOptions` and get the correct value from there so you are using the same object references :) there may be other functions like this; I haven't looked around.
</blockquote></details>

I believe this function isn't being used anywhere, so I just deleted it

**Review by tjcouch-sil — CHANGES_REQUESTED** [review]
> Reviewed 6 of 6 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/346)* status: all files reviewed, 2 unresolved discussions (waiting on @rolfheij-sil)

___
*[`lib/papi-components/src/ref-selector.component.tsx` line 26 at r1](https://reviewable.io/reviews/paranext/paranext-core/346#-NbFi8ee02S3y_nY0VmH:-NbpsjTP1JCtUzAd7mI0:bzbst1e) ([raw file](https://github.com/paranext/paranext-core/blob/c5d900f6ed1109580292cffbba39ec902f602ab8/lib/papi-components/src/ref-selector.component.tsx#L26)):*
<details><summary><i>Previously, rolfheij-sil wrote…</i></summary><blockquote>

Okay, it's simpler now. Are you okay with it?
And a comprehension question: If we create a variable that is not of a native type, it is stored on the heap, right? And that is why we can use it to cache things. Is it also 'static' in a way? So that when two different components include `scripture-util` and call `getBookNameOptions` they access the same heap address? That would be really awesome.
</blockquote></details>

Looks great! Thanks!

Yes, reference types on the stack point to things (objects, functions, etc) on the heap. [This article](https://blog.alexdevero.com/memory-life-cycle-heap-stack-javascript/) explains a bit further if you want to see more :)

When you create a const outside of any functions or classes or things, that const is a module-scoped constant. A module is basically a file. When you import a file, it will run the code in that file and create a module from it. That module is an object that has the exported properties as its properties, and it can be imported elsewhere. So every file has its own scope called module scope. Each module's code should generally run just once no matter how many times you import it in other places.
___
*[`lib/papi-components/src/scripture/scripture-util.ts` line 85 at r3](https://reviewable.io/reviews/paranext/paranext-core/346#-NbLg6Hz7BjeyI6adfZb:-NbLg6Hz7BjeyI6adfZc:bfrh5s8) ([raw file](https://github.com/paranext/paranext-core/blob/8e762d7a7e8a29fb2346d6a0920528ae707e5b8b/lib/papi-components/src/scripture/scripture-util.ts#L85)):*
> ```XML
>  * @returns An array of ComboBox options for book names.
>  */
> let bookNameOptions: BookNameOption[];
> ```

I think the comment on `getBookNameOptions` got separated from the function. Let's put `bookNameOptions above the JSDoc comment if that's ok :)

**Review by rolfheij-sil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/346)* status: 1 of 9 files reviewed, 1 unresolved discussion (waiting on @tjcouch-sil)

___
*[`lib/papi-components/src/scripture/scripture-util.ts` line 85 at r3](https://reviewable.io/reviews/paranext/paranext-core/346#-NbLg6Hz7BjeyI6adfZb:-NbsRLJS6BiY65yYqtWv:b-896fix) ([raw file](https://github.com/paranext/paranext-core/blob/8e762d7a7e8a29fb2346d6a0920528ae707e5b8b/lib/papi-components/src/scripture/scripture-util.ts#L85)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

I think the comment on `getBookNameOptions` got separated from the function. Let's put `bookNameOptions above the JSDoc comment if that's ok :)
</blockquote></details>

Done.

**Review by tjcouch-sil — APPROVED** [review]
:lgtm: thanks for the hard work on this fix!! Great to have it in

> Reviewed 8 of 8 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/346#-:-NbuPtjF22l7_j3EyfS0:brsuzj4)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
