### PR TITLE
Standalone extensions, bundled extensions, and Core share types

### LINKED ISSUE #69: Figure out sharing types between extensions
We currently share types with extension files from our `papi-dts` package (which has a `papi.d.ts` file). We need to figure out how extension files will share types with one another.

To avoid extensions having to publish their own `<extension>-dts` packages, maybe we could find a way to add the Paranext extensions folder as a `typeRoot` so each downloaded extension's `.d.ts` can be used. Then, each extension's `package.json` will need to be updated to point to the correct `.d.ts` file (right now, the extensions' `package.json` files don't point to their `.d.ts` files... I don't know why I didn't set them up to in the first place). We need to figure out some way to prevent people from importing things from other extensions, though - seems that probably won't work as they expect it to... Maybe as long as the `.d.ts` files just export `type` and `interface` items like I currently expect them to, it will be fine.

From [Detailed Notes](https://docs.google.com/document/d/1tCi7GRyP-TWPb9iPc2qWY6I6haSziQtnuPucrrRVUe4/edit#heading=h.o8w5snomexsb):

> Extensions [externally reference other extensions](https://github.com/microsoft/vscode/blob/main/extensions/github/src/extension.ts#L69) by using [extensions.getExtension](https://code.visualstudio.com/api/references/vscode-api#extensions), which returns an object which is the object returned by an extension’s activate function. [VSCode’s source types these objects with .d.ts files](https://github.com/microsoft/vscode/blob/main/extensions/github/src/typings/git-base.d.ts) included in the extension doing the referencing (I imagine you could make a [@types npm package](https://www.npmjs.com/package/vscode-dts) that supplies these types). Interestingly, git-base.d.ts is in [two ](https://github.com/microsoft/vscode/blob/main/extensions/github/src/typings/git-base.d.ts)[places ](https://github.com/microsoft/vscode/blob/main/extensions/git/src/api/git-base.d.ts)in vscode’s source

Carson Full has also mentioned interface string types that can be extended (probably similar to native event handlers). We should investigate making our command functions have extensible interface string types so extensions can pair commands with function signatures.

### PR DESCRIPTION
**Pull request by tjcouch-sil**
- Extensions all can share types via `typeRoots`
- Commands can have their types published with `papi-commands` -> `CommandHandlers`
- Commands now must have at least two strings and a period inbetween
- Recommending lower camel case now instead of kebab case
- Use extensions `lib` folder instead of dist to avoid having to build every time and avoid accidentally changing `dist` `.d.ts` files instead of `lib`
- Changed the way we provide types for the C# side (new `main: null` option in `manifest.json`. Also note there is no `undefined` in json, so I went with `null` as an explicit nothing instead of just leaving `main` out, which is more likely to be an oversight/error on the extension developer's part)
Resolves #69, #267, and #230

- - -
This change is [Reviewable](https://reviewable.io/reviews/paranext/paranext-core/281)

### CODE REVIEW

**Review by tjcouch-sil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/281)* status: 0 of 45 files reviewed, 1 unresolved discussion

___
*[`-- commits` line 23 at r1](https://reviewable.io/reviews/paranext/paranext-core/281#-NZkavRD8bg9Mblwl-78):*
This is a non-blocking comment. Is it counting as unresolved?

**Review by tjcouch-sil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/281)* status: 0 of 45 files reviewed, all discussions resolved

___
*[`-- commits` line 23 at r1](https://reviewable.io/reviews/paranext/paranext-core/281#-NZkavRD8bg9Mblwl-78):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

This is a non-blocking comment. Is it counting as unresolved?
</blockquote></details>

Yes it does

**Review by tjcouch-sil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/281)* status: 0 of 45 files reviewed, 2 unresolved discussions

___
*[`-- commits` line 25 at r1](https://reviewable.io/reviews/paranext/paranext-core/281#-NZkbGThB52ewj87XjR1):*
Test not blocking
___
*[`-- commits` line 31 at r1](https://reviewable.io/reviews/paranext/paranext-core/281#-NZkbHlh2XaiFG7owEJY):*
Test blocking

**Review by lyonsil — CHANGES_REQUESTED** [review]
Nice!  Looks pretty good overall.  I have several comments, but they are all pretty localized.

> Reviewed 36 of 45 files at r1, 9 of 9 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/281#-:-NZlboJ39SvxVI_boCo2:b-leg6m7)* status: all files reviewed, 7 unresolved discussions (waiting on @tjcouch-sil)

___
*[`README.md` line 65 at r2](https://reviewable.io/reviews/paranext/paranext-core/281#-NZlEV9fBfGtBTmbCllM:-NZlEV9g05S3K-GQdt8a:bsdfci) ([raw file](https://github.com/paranext/paranext-core/blob/1f109f14497e286c04df8df21a0b73cad394b052/README.md#L65)):*
> ```Markdown
> 
> ```bash
> npm run build:extensions
> ```

"build:extensions" is still a command in `package.json`.  Why drop this?
___
*[`extensions/lib/c-sharp-provider-test/index.d.ts` line 5 at r2](https://reviewable.io/reviews/paranext/paranext-core/281#-NZlJzZn3qKYM8gvk-5j:-NZlJzZn3qKYM8gvk-5k:b-anphk8) ([raw file](https://github.com/paranext/paranext-core/blob/e66fb32169ab317fc5ebb20e5700b09b3fb8432f/extensions/lib/c-sharp-provider-test/index.d.ts#L5)):*
> ```XML
> declare module 'c-sharp-provider-test' {
>   type TimeDataType = {
>     TimeData: DataProviderDataType<string, string | undefined, string>;
> ```

I forgot to ask before, but this review reminds me.  Is there a way to have a data provider without specifying the first type or the last type?  If not, we might want to add it as a low-priority item in the future.  I just said "string" for the first type because I didn't see a clear way to omit types.  Maybe there won't be real cases like this, but if there is only 1 type of data to get and it is a read-only data provider, the first and last types aren't really doing anything helpful.
___
*[`extensions/lib/hello-someone/hello-someone.ts` line 269 at r2](https://reviewable.io/reviews/paranext/paranext-core/281#-NZlI4N37VgaCBF8KZLy:-NZlI4N37VgaCBF8KZLz:b9dzqb5) ([raw file](https://github.com/paranext/paranext-core/blob/e66fb32169ab317fc5ebb20e5700b09b3fb8432f/extensions/lib/hello-someone/hello-someone.ts#L269)):*
> ```XML
>     }),
>     papi.commands.registerCommand('helloSomeone.echoSomeoneRenderer', async (message: string) => {
>       return `echo-someone-renderer: ${await papi.commands.sendCommand(
> ```

Since the returned string matched the command name previously, you might want to update it to match the new command name.
___
*[`extensions/lib/usfm-data-provider/manifest.json` line 5 at r2](https://reviewable.io/reviews/paranext/paranext-core/281#-NZlKZWu2nRvrTobiM0c:-NZlKZWu2nRvrTobiM0d:bo8c6xn) ([raw file](https://github.com/paranext/paranext-core/blob/e66fb32169ab317fc5ebb20e5700b09b3fb8432f/extensions/lib/usfm-data-provider/manifest.json#L5)):*
> ```JSON
>   "version": "0.0.1",
>   "description": "USFM Data Provider for Paranext - provided by C# data provider",
>   "author": "Matt Lyons",
> ```

This should be consistent with the other manifest files.  You can just use "Paranext" here like the other extensions.
___
*[`lib/papi-dts/package.json` line 30 at r2](https://reviewable.io/reviews/paranext/paranext-core/281#-NZlR3nj8WONeUauljHo:-NZlR3nj8WONeUauljHp:bg90qdn) ([raw file](https://github.com/paranext/paranext-core/blob/e66fb32169ab317fc5ebb20e5700b09b3fb8432f/lib/papi-dts/package.json#L30)):*
> ```JSON
>   "scripts": {
>     "build": "tsc && ts-node edit-papi-d-ts.ts && prettier --write papi.d.ts",
>     "build:fresh": "rimraf papi.tsbuildinfo && npm run build",
> ```

Small suggestion - Many languages that are compiled have a step/option called "clean" that simply removes all compiled outputs.  If we're going to have steps that do that sort of thing, it might be nice to call the `rimraf` step `build:clean` and perhaps have `build:fresh` run `npm run build:clean && npm run build`.
___
*[`src/main/main.ts` line 51 at r2](https://reviewable.io/reviews/paranext/paranext-core/281#-NZlZTAm22D1VmIxRYmP:-NZlZTAm22D1VmIxRYmQ:bx5xho8) ([raw file](https://github.com/paranext/paranext-core/blob/e66fb32169ab317fc5ebb20e5700b09b3fb8432f/src/main/main.ts#L51)):*
> ```XML
>   // This is a temporary hack (per TJ) to allow the Exit menu to have a way to exit the app.
>   'platform.quit': async () => {
>     app.exit();
> ```

I think `app.quit()` would probably be preferred here over `app.exit()` since we have a `will-quit` handler.  From the Electron docs regarding `app.exit()`:
```
All windows will be closed immediately without asking the user, and the `before-quit` and `will-quit` events will not be emitted.
```
___
*[`lib/papi-dts/.eslintrc.cjs` line 18 at r2](https://reviewable.io/reviews/paranext/paranext-core/281#-NZlLPnKEzxqSuuzchSM:-NZlLPnKEzxqSuuzchSN:bpta9j1) ([raw file](https://github.com/paranext/paranext-core/blob/e66fb32169ab317fc5ebb20e5700b09b3fb8432f/lib/papi-dts/.eslintrc.cjs#L18)):*
> ```JavaScript
>         'max-classes-per-file': 'off',
>         'import/newline-after-import': 'off',
>         // Ignore problems with pseudomodules provided in the src/declarations folder
> ```

Why are you saying "pseudomodule" here?  They are modules, are they not?
___
*[`lib/papi-dts/.eslintrc.cjs` line 20 at r2](https://reviewable.io/reviews/paranext/paranext-core/281#-NZlMwzr-zXXOGnZfI_N:-NZlMwzr-zXXOGnZfI_O:bm9hx0z) ([raw file](https://github.com/paranext/paranext-core/blob/e66fb32169ab317fc5ebb20e5700b09b3fb8432f/lib/papi-dts/.eslintrc.cjs#L20)):*
> ```JavaScript
>         // Ignore problems with pseudomodules provided in the src/declarations folder
>         // For example, papi-commands. If this causes problems, we can improve it
>         'import/no-unresolved': ['error', { ignore: ['papi-*'] }],
> ```

`papi-commands` in `src/declarations` doesn't need any import statements.  I checkout out this branch, commented out this line, and everything still built fine.  Why is this ignore needed?

**Review by tjcouch-sil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/281)* status: all files reviewed, 10 unresolved discussions (waiting on @irahopkinson and @lyonsil)

___
*[`README.md` line 65 at r2](https://reviewable.io/reviews/paranext/paranext-core/281#-NZlEV9fBfGtBTmbCllM:-N_-0JHOBtxwT4xR7ds5:b-7nbr62) ([raw file](https://github.com/paranext/paranext-core/blob/1f109f14497e286c04df8df21a0b73cad394b052/README.md#L65)):*
<details><summary><i>Previously, lyonsil (Matt Lyons) wrote…</i></summary><blockquote>

"build:extensions" is still a command in `package.json`.  Why drop this?
</blockquote></details>

Because we're now using `lib` for extension types, you don't have to build extensions anymore. It does it automatically in the right place at the right time when you're running paranext core now. There is still stuff explaining building extensions and such in the extension folder README though :)
___
*[`extensions/lib/c-sharp-provider-test/index.d.ts` line 5 at r2](https://reviewable.io/reviews/paranext/paranext-core/281#-NZlJzZn3qKYM8gvk-5j:-N_-TiEA4Q6fGmFEL0ci:bpcnhcu) ([raw file](https://github.com/paranext/paranext-core/blob/e66fb32169ab317fc5ebb20e5700b09b3fb8432f/extensions/lib/c-sharp-provider-test/index.d.ts#L5)):*
<details><summary><i>Previously, lyonsil (Matt Lyons) wrote…</i></summary><blockquote>

I forgot to ask before, but this review reminds me.  Is there a way to have a data provider without specifying the first type or the last type?  If not, we might want to add it as a low-priority item in the future.  I just said "string" for the first type because I didn't see a clear way to omit types.  Maybe there won't be real cases like this, but if there is only 1 type of data to get and it is a read-only data provider, the first and last types aren't really doing anything helpful.
</blockquote></details>

You can put `undefined` or `null` in the first and `never` in the last, which is what I will do for this. Unfortunately, you can't provide `never` as the first one since you have to provide some kind of selector as a parameter in a bunch of data provider functions.
___
*[`extensions/lib/hello-someone/hello-someone.ts` line 269 at r2](https://reviewable.io/reviews/paranext/paranext-core/281#-NZlI4N37VgaCBF8KZLy:-N_-UYvK3XmOqHr5SnxO:b-mw7rum) ([raw file](https://github.com/paranext/paranext-core/blob/e66fb32169ab317fc5ebb20e5700b09b3fb8432f/extensions/lib/hello-someone/hello-someone.ts#L269)):*
<details><summary><i>Previously, lyonsil (Matt Lyons) wrote…</i></summary><blockquote>

Since the returned string matched the command name previously, you might want to update it to match the new command name.
</blockquote></details>

Good catch! Thanks. I thought I caught all these.
___
*[`extensions/lib/quick-verse/quick-verse.d.ts` line 4 at r2](https://reviewable.io/reviews/paranext/paranext-core/281#-NZxoNEDAz5Yz4w6dEwi:-N_-Uf4A5S31Bo8C9jNL:b32rwwp) ([raw file](https://github.com/paranext/paranext-core/blob/e66fb32169ab317fc5ebb20e5700b09b3fb8432f/extensions/lib/quick-verse/quick-verse.d.ts#L4)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

Is it still possible to generate these now we have moved in this direction? If not we can remove this TODO comment.
</blockquote></details>

Yeah, I think we can theoretically still generate them. It would probably be a bit messier as you would likely have things like the `activate` function in the `.d.ts`, which doesn't make any sense. But I think we still could. Maybe we shouldn't autogenerate, though haha dunno. I kinda lean toward shouldn't honestly. We have this `.d.ts` because it is a different interface than the node loader - we kinda made our own module loader with our own set of exports. Thoughts? (I'll take it out for now unless we decide otherwise)
___
*[`extensions/lib/usfm-data-provider/manifest.json` line 5 at r2](https://reviewable.io/reviews/paranext/paranext-core/281#-NZlKZWu2nRvrTobiM0c:-N_-VCsE3acy3uTJfbAB:b-896fix) ([raw file](https://github.com/paranext/paranext-core/blob/e66fb32169ab317fc5ebb20e5700b09b3fb8432f/extensions/lib/usfm-data-provider/manifest.json#L5)):*
<details><summary><i>Previously, lyonsil (Matt Lyons) wrote…</i></summary><blockquote>

This should be consistent with the other manifest files.  You can just use "Paranext" here like the other extensions.
</blockquote></details>

Done.
___
*[`lib/papi-dts/edit-papi-d-ts.ts` line 20 at r2](https://reviewable.io/reviews/paranext/paranext-core/281#-NZxruAJEXi5hbbx-jYK:-N_-WlLh9FIbb-6Zctde:bxxfrm9) ([raw file](https://github.com/paranext/paranext-core/blob/e66fb32169ab317fc5ebb20e5700b09b3fb8432f/lib/papi-dts/edit-papi-d-ts.ts#L20)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

Why did we go to this `escapeStringRegexp` RegExp?

FYI, I'm pretty sure `replaceAll` did actually work here despite your IDE having a red squiggly line under it - that was just because we didn't have everything setup right for the IDE to know it was ok since this file is called with `ts-node` rather than our usual setup (or it could be our usual setup is not actually correct).
</blockquote></details>

Indeed it did work just fine before. But I kept getting tricked by the file showing it had one error, so I changed it. I guess I could change it back and put an ignore errors line. However, all the changes I made to the `tsconfig.json` seemed not to fix the problem unfortunately :(
___
*[`lib/papi-dts/package.json` line 30 at r2](https://reviewable.io/reviews/paranext/paranext-core/281#-NZlR3nj8WONeUauljHo:-N_-XEti9pUqde-uva6C:bjxvwgp) ([raw file](https://github.com/paranext/paranext-core/blob/e66fb32169ab317fc5ebb20e5700b09b3fb8432f/lib/papi-dts/package.json#L30)):*
<details><summary><i>Previously, lyonsil (Matt Lyons) wrote…</i></summary><blockquote>

Small suggestion - Many languages that are compiled have a step/option called "clean" that simply removes all compiled outputs.  If we're going to have steps that do that sort of thing, it might be nice to call the `rimraf` step `build:clean` and perhaps have `build:fresh` run `npm run build:clean && npm run build`.
</blockquote></details>

Sounds nice! Done.
___
*[`lib/papi-dts/tsconfig.json` line 9 at r2](https://reviewable.io/reviews/paranext/paranext-core/281#-NZxvZ1T-r_yn2UStmtA:-N_-Xfpj87EOQN1XExSr:bnsl6qc) ([raw file](https://github.com/paranext/paranext-core/blob/e66fb32169ab317fc5ebb20e5700b09b3fb8432f/lib/papi-dts/tsconfig.json#L9)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

Strictly speacking `.json` files don't support comments. VS Code might be dealing with it but this may couse problems for some peoples setup and/or another IDE. However, do you think we can leave these in for now until we encounter an issue? It might be annoying and hard to find if this is the reason an extension developer can't get their setup working. What do you think?
</blockquote></details>

Indeed, but I learned when doing some research on this issue that TypeScript wrote a custom parser that does support comments. That's why I use it in `edit-papi-d-ts.ts` :) because of this special support for this one specific json file, I suggest we leave the comments.
___
*[`src/declarations/README.md` line 5 at r2](https://reviewable.io/reviews/paranext/paranext-core/281#-NZy0J40-TmjSs34wbDy:-N_-Y3_I7Aq8evUefGkt:b-fx6mz3) ([raw file](https://github.com/paranext/paranext-core/blob/e66fb32169ab317fc5ebb20e5700b09b3fb8432f/src/declarations/README.md#L5)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

Why are files in this folder `.ts` rather than `.d.ts`?
</blockquote></details>

`.d.ts` files are considered to be their own module, so `papi.d.ts` will make a `reference` line and leave the `.d.ts` declarations out, but `.ts` files are bundled into `papi.d.ts`. I will state this more explicitly.
___
*[`src/main/main.ts` line 51 at r2](https://reviewable.io/reviews/paranext/paranext-core/281#-NZlZTAm22D1VmIxRYmP:-N_-YafHCRJcxTdj02EF:b-5oyo9l) ([raw file](https://github.com/paranext/paranext-core/blob/e66fb32169ab317fc5ebb20e5700b09b3fb8432f/src/main/main.ts#L51)):*
<details><summary><i>Previously, lyonsil (Matt Lyons) wrote…</i></summary><blockquote>

I think `app.quit()` would probably be preferred here over `app.exit()` since we have a `will-quit` handler.  From the Electron docs regarding `app.exit()`:
```
All windows will be closed immediately without asking the user, and the `before-quit` and `will-quit` events will not be emitted.
```
</blockquote></details>

I agree. Done. I didn't add and don't think I reviewed this code. I just wasn't paying attention or thinking about improving it.
___
*[`src/shared/services/network.service.ts` line 147 at r2](https://reviewable.io/reviews/paranext/paranext-core/281#-NZy5_bl0wWpaWNRemrp:-N_-ZBsf4YkoOkkBcsl6:bw1m75w) ([raw file](https://github.com/paranext/paranext-core/blob/e66fb32169ab317fc5ebb20e5700b09b3fb8432f/src/shared/services/network.service.ts#L147)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

Would it be cleaner if you destructed here, i.e. `const { category, directive } = deserializeRequestType(requestType);`?
</blockquote></details>

Definitely! Thanks.
___
*[`src/shared/services/network.service.ts` line 147 at r2](https://reviewable.io/reviews/paranext/paranext-core/281#-NZy6Odt3iTrvncgPg4P:-N_0ArBT9rCSfOF2aN3j:b-896fix) ([raw file](https://github.com/paranext/paranext-core/blob/e66fb32169ab317fc5ebb20e5700b09b3fb8432f/src/shared/services/network.service.ts#L147)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

`deserializeRequestType` is  probably not written very efficiently (it's previous usage didn't require it). However, here it's likely called a lot of times. Do you think we should improve it?
</blockquote></details>

Done.
___
*[`lib/papi-dts/.eslintrc.cjs` line 18 at r2](https://reviewable.io/reviews/paranext/paranext-core/281#-NZlLPnKEzxqSuuzchSM:-N_-VGqH-6BO7IaYavFq:br5n2v0) ([raw file](https://github.com/paranext/paranext-core/blob/e66fb32169ab317fc5ebb20e5700b09b3fb8432f/lib/papi-dts/.eslintrc.cjs#L18)):*
<details><summary><i>Previously, lyonsil (Matt Lyons) wrote…</i></summary><blockquote>

Why are you saying "pseudomodule" here?  They are modules, are they not?
</blockquote></details>

Actually they're not real modules. They're just serving types that people can use. There isn't any real code there.
___
*[`lib/papi-dts/.eslintrc.cjs` line 20 at r2](https://reviewable.io/reviews/paranext/paranext-core/281#-NZlMwzr-zXXOGnZfI_N:-N_-Vbyy48d07xnyBk48:b-umld35) ([raw file](https://github.com/paranext/paranext-core/blob/e66fb32169ab317fc5ebb20e5700b09b3fb8432f/lib/papi-dts/.eslintrc.cjs#L20)):*
<details><summary><i>Previously, lyonsil (Matt Lyons) wrote…</i></summary><blockquote>

`papi-commands` in `src/declarations` doesn't need any import statements.  I checkout out this branch, commented out this line, and everything still built fine.  Why is this ignore needed?
</blockquote></details>

`papi-commands` isn't an actual module, so eslint throws a fit when it sees it in most cases.

If you open VSCode to the `lib/papi-dts` folder, its `eslintrc` will be used. You can see importing it throws an error because eslint thinks it's not a real module (because it isn't). I used a trick to configure it to look like an actual module in `paranext-core`'s eslint, but that was through webpack which isn't available in this folder.

See the image below where I removed the ignore line and opened VSCode to `lib/papi-dts`:



I could change the ignore line to just `papi-commands` if we want, but I figured it would get annoying to make multiple changes every time we wanted to do something like this. Let me know your preference.

**Review by lyonsil — COMMENTED** [review]
> Reviewed 20 of 23 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/281)* status: 48 of 51 files reviewed, 6 unresolved discussions (waiting on @irahopkinson)

___
*[`lib/papi-dts/.eslintrc.cjs` line 20 at r2](https://reviewable.io/reviews/paranext/paranext-core/281#-NZlMwzr-zXXOGnZfI_N:-N_0LCa28Df1SBmI8Udx:byxt2n9) ([raw file](https://github.com/paranext/paranext-core/blob/e66fb32169ab317fc5ebb20e5700b09b3fb8432f/lib/papi-dts/.eslintrc.cjs#L20)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

`papi-commands` isn't an actual module, so eslint throws a fit when it sees it in most cases.

If you open VSCode to the `lib/papi-dts` folder, its `eslintrc` will be used. You can see importing it throws an error because eslint thinks it's not a real module (because it isn't). I used a trick to configure it to look like an actual module in `paranext-core`'s eslint, but that was through webpack which isn't available in this folder.

See the image below where I removed the ignore line and opened VSCode to `lib/papi-dts`:



I could change the ignore line to just `papi-commands` if we want, but I figured it would get annoying to make multiple changes every time we wanted to do something like this. Let me know your preference.
</blockquote></details>

I would be interested in @irahopkinson 's thoughts here.

**Review by irahopkinson — APPROVED** [review]
> Reviewed 23 of 23 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/281)* status: :shipit: complete! all files reviewed, all discussions resolved

___
*[`lib/papi-dts/edit-papi-d-ts.ts` line 20 at r2](https://reviewable.io/reviews/paranext/paranext-core/281#-NZxruAJEXi5hbbx-jYK:-N_14uJ_2wRAROculV3Q:b1mr2rw) ([raw file](https://github.com/paranext/paranext-core/blob/e66fb32169ab317fc5ebb20e5700b09b3fb8432f/lib/papi-dts/edit-papi-d-ts.ts#L20)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

Indeed it did work just fine before. But I kept getting tricked by the file showing it had one error, so I changed it. I guess I could change it back and put an ignore errors line. However, all the changes I made to the `tsconfig.json` seemed not to fix the problem unfortunately :(
</blockquote></details>

I suspect we need another `tsconfig.tsnode.json` for this file (the only one that is called by `ts-node`) with either a different *target* or add something to *lib*. However, given this is boilerplate it probably is not worth the effort.
___
*[`lib/papi-dts/tsconfig.json` line 9 at r2](https://reviewable.io/reviews/paranext/paranext-core/281#-NZxvZ1T-r_yn2UStmtA:-N_15xaj1zJdVKCfR-eN:b-awisza) ([raw file](https://github.com/paranext/paranext-core/blob/e66fb32169ab317fc5ebb20e5700b09b3fb8432f/lib/papi-dts/tsconfig.json#L9)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

Indeed, but I learned when doing some research on this issue that TypeScript wrote a custom parser that does support comments. That's why I use it in `edit-papi-d-ts.ts` :) because of this special support for this one specific json file, I suggest we leave the comments.
</blockquote></details>

Oh, that's really good to know, thanks.
___
*[`lib/papi-dts/.eslintrc.cjs` line 20 at r2](https://reviewable.io/reviews/paranext/paranext-core/281#-NZlMwzr-zXXOGnZfI_N:-N_123Nu1EEmC4ZITdFP:bv9aw5m) ([raw file](https://github.com/paranext/paranext-core/blob/e66fb32169ab317fc5ebb20e5700b09b3fb8432f/lib/papi-dts/.eslintrc.cjs#L20)):*
<details><summary><i>Previously, lyonsil (Matt Lyons) wrote…</i></summary><blockquote>

I would be interested in @irahopkinson 's thoughts here.
</blockquote></details>

My first thought was we should just put an ignore comment at the top of each file that needs it but then developers might forget so this is probably better. The down side is someone might name any file starting with `papi-` and it would be ignored but then I suppose it would have other problems with the way it got included by vite before this became the biggest issue. So leave it as is for now.

**Review by lyonsil — DISMISSED** [review]
> Reviewed 3 of 23 files at r3.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/281)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by irahopkinson — APPROVED** [review]
:lgtm: just need to sort out that test and we are good to go.

> Reviewed 5 of 5 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/281#-:-N_6o8o0-4DwsVEDJ_tb:bsln2k8)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by lyonsil — DISMISSED** [review]
> Reviewed 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/281)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by lyonsil — APPROVED** [review]
> Reviewed 8 of 8 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/281)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
