### PR TITLE
update editor

### PR DESCRIPTION
**Pull request by irahopkinson**
- add `onCommentChange` & `onSelectionChange` props
- remove `onUsjChange` check no longer needed after `platform-editor` v0.6.0

- - -
This change is [Reviewable](https://reviewable.io/reviews/paranext/paranext-core/1182)

### CODE REVIEW

**Review by lyonsil — APPROVED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/1182)* status: all files reviewed, 1 unresolved discussion (waiting on @irahopkinson)

___
*[`extensions/src/platform-scripture-editor/src/platform-scripture-editor.web-view.tsx` line 189 at r1](https://reviewable.io/reviews/paranext/paranext-core/1182#-O88tqrx3pQQrKwjn0kn:-O88tqrx3pQQrKwjn0ko:b-2crpb9) ([raw file](https://github.com/paranext/paranext-core/blob/43b55043a4681bc8e84844e4971e988334673f4f/extensions/src/platform-scripture-editor/src/platform-scripture-editor.web-view.tsx#L189)):*
> ```XML
>         scrRef={scrRef}
>         onScrRefChange={setScrRef}
>         onUsjChange={isReadOnly ? undefined : onUsjChange}
> ```

Do the new props need to be set here even if we don't have logic to insert yet? I'm guessing not but just making sure.

**Comment by irahopkinson** [comment]
*[`extensions/src/platform-scripture-editor/src/platform-scripture-editor.web-view.tsx` line 189 at r1](https://reviewable.io/reviews/paranext/paranext-core/1182#-O88tqrx3pQQrKwjn0kn:-O89AzYd2tzy7YqTHLhL:bdklytd) ([raw file](https://github.com/paranext/paranext-core/blob/43b55043a4681bc8e84844e4971e988334673f4f/extensions/src/platform-scripture-editor/src/platform-scripture-editor.web-view.tsx#L189)):*
<details><summary><i>Previously, lyonsil (Matt Lyons) wrote…</i></summary><blockquote>

Do the new props need to be set here even if we don't have logic to insert yet? I'm guessing not but just making sure.
</blockquote></details>

No, all the properties are optional so you don't have to set them.

**Review by tjcouch-sil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/1182)* status: all files reviewed, 1 unresolved discussion (waiting on @irahopkinson)

___
*[`extensions/src/platform-scripture-editor/src/platform-scripture-editor.web-view.tsx` line 111 at r1](https://reviewable.io/reviews/paranext/paranext-core/1182#-O8CcgXt0on8k9HkAPA1:-O8CcgXt0on8k9HkAPA2:bi9awx3) ([raw file](https://github.com/paranext/paranext-core/blob/9f2756a062f9a5679eb172a7915929e56760b38b/extensions/src/platform-scripture-editor/src/platform-scripture-editor.web-view.tsx#L111)):*
> ```XML
>       // not run onChange if the change came externally (our tracked editorUsj.current editor state
>       // will already be up-to-date)
>       if (deepEqualAcrossIframes(newUsj, editorUsj.current)) return;
> ```

Have we checked to make sure removing this doesn't cause usj-unrelated lexical state changes like changing the mouse cursor or other things like that to send updates?

**Comment by irahopkinson** [comment]
*[`extensions/src/platform-scripture-editor/src/platform-scripture-editor.web-view.tsx` line 111 at r1](https://reviewable.io/reviews/paranext/paranext-core/1182#-O8CcgXt0on8k9HkAPA1:-O8DR-ON1-HDqr3SBFVh:b-p0vdys) ([raw file](https://github.com/paranext/paranext-core/blob/9f2756a062f9a5679eb172a7915929e56760b38b/extensions/src/platform-scripture-editor/src/platform-scripture-editor.web-view.tsx#L111)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

Have we checked to make sure removing this doesn't cause usj-unrelated lexical state changes like changing the mouse cursor or other things like that to send updates?
</blockquote></details>

Yes, the editor is specifically ignoring external USJ mutations, selection changes, cursor changes and annotation changes. I did some basic testing in Platform. However I was going to ask you to do some testing of whatever caused you to add this code in the first place. We still have the normalization bug though.

**Pull request merged**
