### PR TITLE
Enable comment propagation to properties of objects using custom script

### PR DESCRIPTION
**Pull request by lyonsil**
This is a fourth option for how to resolve https://github.com/paranext/paranext-core/issues/292.  I don't know if I really love it, but it works.

In short, use `/** JSDOC SOURCE <name> [rest of the comments/docs on new lines] */` to define the comments you want to be copied somewhere else.  Then use `/** JSDOC DESTINATION <name> */` to denote the target of where you want the comments copied.  `edit-papi-d-ts.ts` takes care of the rest.

Note that this required eliminating the shared `papi` and putting all the appropriate parts into the front end and back end `papi`s.  It seems that when you extend a custom object with additional properties, comments from the original object's properties are not forwarded along.

@tjcouch-sil and @irahopkinson - I want to get a thumbs up from both of you if we're going to call this good.  It's not horrible, but it's weird.  It does make Intellisense work nicely when typing in VSCode, though.  When you type `papi.`, all the properties pop up and show their comments inline.  (Note that many of our current comments are pretty weak and should be improved for this to be maximally useful for extension devs.)

On the positive side, this new functionality allows us to eliminate the duplicate comments for the `getData` hook.

- - -
This change is [Reviewable](https://reviewable.io/reviews/paranext/paranext-core/310)

### CODE REVIEW

**Review by irahopkinson — CHANGES_REQUESTED** [review]
I'm Ok with this fix since we already manipulate `papi.d.ts` using `edit-papi-d-ts.ts` and I think it's better than the other 3 options in #292.

> Reviewed 20 of 20 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/310#-:-Na5EdeY6gknSwVh3pZZ:b-ck2ufy)* status: all files reviewed, 5 unresolved discussions (waiting on @lyonsil)

___
*[`lib/papi-dts/edit-papi-d-ts.ts` line 31 at r1](https://reviewable.io/reviews/paranext/paranext-core/310#-Na59314A6yapYD_28u9:-Na59314A6yapYD_28uA:b-1llgk4) ([raw file](https://github.com/paranext/paranext-core/blob/3e1b08c32519aae15ef38b3dff896efece906548/lib/papi-dts/edit-papi-d-ts.ts#L31)):*
> ```XML
> // #region Copy "JSDOC DESTINATION" blocks to "JSDOC SOURCE" blocks
> 
> type target = {
> ```

Type/interface names should start with a capital, i.e. `Target`.
___
*[`lib/papi-dts/edit-papi-d-ts.ts` line 42 at r1](https://reviewable.io/reviews/paranext/paranext-core/310#-Na5CQ570RyIw3JNOlSV:-Na5CQ570RyIw3JNOlSW:b-c0g5fh) ([raw file](https://github.com/paranext/paranext-core/blob/3e1b08c32519aae15ef38b3dff896efece906548/lib/papi-dts/edit-papi-d-ts.ts#L42)):*
> ```XML
> const jsdocRegex = /\/\*\*[\s]*?JSDOC (SOURCE|DESTINATION) (\w+)[\s\S]*?\*\//g;
> let match: RegExpExecArray | null;
> /* eslint no-cond-assign: ["error", "except-parens"] */
> ```

There is a good reason to leave this rule on since the assignment operator can be ambiguous (it is very easy to mistype a comparison operator (such as `==`) as an assignment operator (such as `=`)). You also have it disabled for the rest of the file below rather than just the next line. Instead set `match = jsdocRegex.exec(papiDTS)` at the end of the `while` and when you declare `match`.
___
*[`lib/papi-dts/edit-papi-d-ts.ts` line 60 at r1](https://reviewable.io/reviews/paranext/paranext-core/310#-Na5Ayt-84xXKjQTqWp1:-Na5Ayt-84xXKjQTqWp2:bgq19jd) ([raw file](https://github.com/paranext/paranext-core/blob/3e1b08c32519aae15ef38b3dff896efece906548/lib/papi-dts/edit-papi-d-ts.ts#L60)):*
> ```XML
> // Now replace destinations with sources
> // eslint-disable-next-line @typescript-eslint/no-unused-vars
> jsdocDestinations.forEach((destinationItem, _) => {
> ```

Since you don't need the 2nd argument then just remove it and the eslint disable comment above.
___
*[`src/shared/services/command.service.ts` line 178 at r1](https://reviewable.io/reviews/paranext/paranext-core/310#-Na54oVl6726B97k6gGe:-Na54oVm9Zo3QZ2lePsE:b-cghpua) ([raw file](https://github.com/paranext/paranext-core/blob/3e1b08c32519aae15ef38b3dff896efece906548/src/shared/services/command.service.ts#L178)):*
> ```XML
>  * You can send commands to other services and extensions that have registered commands.
>  */
> export type moduleSummaryComments = {};
> ```

It looks like this is an unused type declaration just so there is a placeholder for the JSDOC SOURCE, is that right?
___
*[`src/shared/utils/papi-util.ts` line 213 at r1](https://reviewable.io/reviews/paranext/paranext-core/310#-Na551a1BRNYD08kS3Cx:-Na551a1BRNYD08kS3Cy:b-xs2pvm) ([raw file](https://github.com/paranext/paranext-core/blob/3e1b08c32519aae15ef38b3dff896efece906548/src/shared/utils/papi-util.ts#L213)):*
> ```XML
>  * Extensions should not use or rely on anything in papiUtil unless some other service requires it.
>  */
> export type moduleSummaryComments = {};
> ```

It looks like this is an unused type declaration just so there is a placeholder for the JSDOC SOURCE, is that right? I tried moving this comment to the very top of the file above the imports (and removed the type declaration) and it still works to place the comment in `papi.d.ts`. However it didn't work for the command service - not sure why. Perhaps a tweak in `lib/papi-dts/edit-papi-d-ts.ts` would make it work?

**Review by lyonsil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/310)* status: 19 of 20 files reviewed, 4 unresolved discussions (waiting on @irahopkinson)

___
*[`lib/papi-dts/edit-papi-d-ts.ts` line 31 at r1](https://reviewable.io/reviews/paranext/paranext-core/310#-Na59314A6yapYD_28u9:-Na7kbzD4X9X-Be2O-3T:b-896fix) ([raw file](https://github.com/paranext/paranext-core/blob/fcba145159d5d40f60d1e4ff8db14a22288fef6c/lib/papi-dts/edit-papi-d-ts.ts#L31)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

Type/interface names should start with a capital, i.e. `Target`.
</blockquote></details>

Done.
___
*[`lib/papi-dts/edit-papi-d-ts.ts` line 42 at r1](https://reviewable.io/reviews/paranext/paranext-core/310#-Na5CQ570RyIw3JNOlSV:-Na7ksl59HQk0BNaBAp7:blkl2tg) ([raw file](https://github.com/paranext/paranext-core/blob/fcba145159d5d40f60d1e4ff8db14a22288fef6c/lib/papi-dts/edit-papi-d-ts.ts#L42)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

There is a good reason to leave this rule on since the assignment operator can be ambiguous (it is very easy to mistype a comparison operator (such as `==`) as an assignment operator (such as `=`)). You also have it disabled for the rest of the file below rather than just the next line. Instead set `match = jsdocRegex.exec(papiDTS)` at the end of the `while` and when you declare `match`.
</blockquote></details>

I kind of like this syntax so that I don't have to repeat the call to `jsdocRegex.exec()`.  Otherwise I have to do it both before the loop starts and in the `while` as you suggest.  I also have to have an extra line for the null check at the start of the loop.  The `except-parens` option exists for cases just like this.  That's why someone took the time to make the option.

I changed this to a single line disable.  Note that I had to drop the `except-parens` option because you can't pass options to eslint-disable directives for single line disables.  I think that making the `except-parens` exception would make sense for the project overall, honestly, but that's really a bigger discussion.
___
*[`lib/papi-dts/edit-papi-d-ts.ts` line 60 at r1](https://reviewable.io/reviews/paranext/paranext-core/310#-Na5Ayt-84xXKjQTqWp1:-Na7mdCG3-44nBxY6wd6:bc4sjc7) ([raw file](https://github.com/paranext/paranext-core/blob/fcba145159d5d40f60d1e4ff8db14a22288fef6c/lib/papi-dts/edit-papi-d-ts.ts#L60)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

Since you don't need the 2nd argument then just remove it and the eslint disable comment above.
</blockquote></details>

Done.  Good call!
___
*[`src/shared/services/command.service.ts` line 178 at r1](https://reviewable.io/reviews/paranext/paranext-core/310#-Na54oVl6726B97k6gGe:-Na7mxrr36Zz4OSX_5J6:b-oyfytt) ([raw file](https://github.com/paranext/paranext-core/blob/fcba145159d5d40f60d1e4ff8db14a22288fef6c/src/shared/services/command.service.ts#L178)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

It looks like this is an unused type declaration just so there is a placeholder for the JSDOC SOURCE, is that right?
</blockquote></details>

Correct - It needs an anchor to something to show up in the `papi.d.ts` file.  I don't understand why the compiler will sometimes allow comments at the top of the file without an anchor to pass through to `papi.d.ts`, but it isn't consistent as you pointed out in your other comment.  Also, all the services that export an object at the end (which is most of them) have comments for the service at the end, so putting the placeholder at the end for the module-level comments made things consistent.
___
*[`src/shared/utils/papi-util.ts` line 213 at r1](https://reviewable.io/reviews/paranext/paranext-core/310#-Na551a1BRNYD08kS3Cx:-Na7r6yN1ioG7qOs_tPS:b-1bim10) ([raw file](https://github.com/paranext/paranext-core/blob/fcba145159d5d40f60d1e4ff8db14a22288fef6c/src/shared/utils/papi-util.ts#L213)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

It looks like this is an unused type declaration just so there is a placeholder for the JSDOC SOURCE, is that right? I tried moving this comment to the very top of the file above the imports (and removed the type declaration) and it still works to place the comment in `papi.d.ts`. However it didn't work for the command service - not sure why. Perhaps a tweak in `lib/papi-dts/edit-papi-d-ts.ts` would make it work?
</blockquote></details>

`edit.papi.d.ts` can't fix this unless it goes back to the original sources that were made to put together `papi.d.ts`.  That would be a significant increase in scope of what the tools does.

The problem you point out with command service is that the `JSDOC SOURCE` comments for command service never make it into `papi.d.ts` from `tsc`.  Instead, `tsc` simply drops the comments on the floor when putting together `papi.d.ts`.  If you give the comments an anchor, even if that anchor is just an empty type declaration, then `tsc` works consistently with those comments.

**Review by irahopkinson — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/310)* status: all files reviewed, 1 unresolved discussion (waiting on @lyonsil)

___
*[`lib/papi-dts/edit-papi-d-ts.ts` line 42 at r1](https://reviewable.io/reviews/paranext/paranext-core/310#-Na5CQ570RyIw3JNOlSV:-Na8Osop50MH-FP1e31r:b-pim7bb) ([raw file](https://github.com/paranext/paranext-core/blob/fcba145159d5d40f60d1e4ff8db14a22288fef6c/lib/papi-dts/edit-papi-d-ts.ts#L42)):*
<details><summary><i>Previously, lyonsil (Matt Lyons) wrote…</i></summary><blockquote>

I kind of like this syntax so that I don't have to repeat the call to `jsdocRegex.exec()`.  Otherwise I have to do it both before the loop starts and in the `while` as you suggest.  I also have to have an extra line for the null check at the start of the loop.  The `except-parens` option exists for cases just like this.  That's why someone took the time to make the option.

I changed this to a single line disable.  Note that I had to drop the `except-parens` option because you can't pass options to eslint-disable directives for single line disables.  I think that making the `except-parens` exception would make sense for the project overall, honestly, but that's really a bigger discussion.
</blockquote></details>

JS `while` loops check before entering the loop so no extra null check would be needed (a `do...while` checks at the end of the loop). If you want to leave it as is I'd be happier with the `"except-parens"` option so you could put that back and add `/\* eslint-enable \*/` after the `while` line so it's only on for that line.

**Review by lyonsil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/310)* status: 19 of 20 files reviewed, 1 unresolved discussion (waiting on @irahopkinson)

___
*[`lib/papi-dts/edit-papi-d-ts.ts` line 42 at r1](https://reviewable.io/reviews/paranext/paranext-core/310#-Na5CQ570RyIw3JNOlSV:-NaCN0EuCEVh1U8Oqh1o:b-3hqegu) ([raw file](https://github.com/paranext/paranext-core/blob/fcba145159d5d40f60d1e4ff8db14a22288fef6c/lib/papi-dts/edit-papi-d-ts.ts#L42)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

JS `while` loops check before entering the loop so no extra null check would be needed (a `do...while` checks at the end of the loop). If you want to leave it as is I'd be happier with the `"except-parens"` option so you could put that back and add `/\* eslint-enable \*/` after the `while` line so it's only on for that line.
</blockquote></details>

Oh, when you said "at the end" I thought you were talking about changing to a `do ... while` loop.

I think the original way is slightly better (along with a change to the lint config to make `except-parens` the default so no override is needed,  but I'll just change to duplicate the assignment to `match`.  We're not doing this enough in our code to warrant a bigger discussion.

**Review by tjcouch-sil — CHANGES_REQUESTED** [review]
This is a great idea! I love it. I'm really sad to see you can't figure out how to keep the shared papi file to be honest. Maybe you can add a region in each of the split out files to help people to remember to consider whether things should be shared if you'd like. I'm totally down to go with this option. Thanks for the great work!!

> Reviewed 19 of 20 files at r1, 1 of 1 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/310#-:-NaCVYV540TOpD3iC4hm:b-yett6f)* status: all files reviewed, 9 unresolved discussions (waiting on @irahopkinson and @lyonsil)

___
*[`lib/papi-dts/edit-papi-d-ts.ts` line 42 at r1](https://reviewable.io/reviews/paranext/paranext-core/310#-Na5CQ570RyIw3JNOlSV:-NaCC3bf0Eb1hAX-T6ll:bns7h2h) ([raw file](https://github.com/paranext/paranext-core/blob/fcba145159d5d40f60d1e4ff8db14a22288fef6c/lib/papi-dts/edit-papi-d-ts.ts#L42)):*
<details><summary><i>Previously, lyonsil (Matt Lyons) wrote…</i></summary><blockquote>

Oh, when you said "at the end" I thought you were talking about changing to a `do ... while` loop.

I think the original way is slightly better (along with a change to the lint config to make `except-parens` the default so no override is needed,  but I'll just change to duplicate the assignment to `match`.  We're not doing this enough in our code to warrant a bigger discussion.
</blockquote></details>

[Comment from before Matt's most recent update and comment. I was looking at r2. Do whatever you'd like :)]
I have never seen this syntax before; very unusual. Honestly it's hard to read... I would have thought an assignment would return true if it worked and false otherwise, but apparently it returns the result of the assignment. Strange haha but I admit I do like that you don't have to write twice the code that sets the variable for the while condition like this. That has always bothered me about while loops, too, Matt.

One thing we could do is put an item in the style doc about it and leave it here with the single-line disable or the block-level `"except-parens"` disable. However, our style guide does require that you state why you have disabled something if you disabled it. So I suggest if you leave it that you put another comment above the disabling line that says you use it here to avoid having to write the assignment twice because while loops are annoying.
___
*[`lib/papi-dts/edit-papi-d-ts.ts` line 40 at r2](https://reviewable.io/reviews/paranext/paranext-core/310#-NaCINSr6dyFfgeJvwbQ:-NaCINSr6dyFfgeJvwbR:b-xt9yqq) ([raw file](https://github.com/paranext/paranext-core/blob/b46be08c4350f941981c16daf6b1e40440f24ca2/lib/papi-dts/edit-papi-d-ts.ts#L40)):*
> ```XML
> 
> // Find all sources and destinations in one pass through the file
> const jsdocRegex = /\/\*\*[\s]*?JSDOC (SOURCE|DESTINATION) (\w+)[\s\S]*?\*\//g;
> ```

Part of me wants to put curly braces around the magic comment like `/** {JSDOC SOURCE thingy}` or something. That way, it's very well-defined what the string is and more obvious that this is something special we're doing (and you can have spaces if you want, though that's kinda a side effect more than the main reason to do it). Maybe even make the words something more catered to us like PAPIDOC SRC and DEST or something (though I know we said not to abbreviate words. Just thing to make it not so long especially since I added two characters)? Just some thoughts; you don't have to do either of these.
___
*[`lib/papi-dts/edit-papi-d-ts.ts` line 71 at r2](https://reviewable.io/reviews/paranext/paranext-core/310#-NaCFa7lBgYvnp9vKJMw:-NaCFa7lBgYvnp9vKJMx:bqyka7k) ([raw file](https://github.com/paranext/paranext-core/blob/b46be08c4350f941981c16daf6b1e40440f24ca2/lib/papi-dts/edit-papi-d-ts.ts#L71)):*
> ```XML
> 
> // Remove all the "JSDOC SOURCE targetName" portions of the comments as a final clean up
> papiDTS = papiDTS.replace(/\/\*\*[\s]*JSDOC SOURCE \w+\n/g, '/**\n');
> ```

I believe I see here that JSDOC SOURCE must have a newline afterward, but that condition is not required for DESTINATION. What do you think of making a capture group around the `\n` and making it `\n?` and then putting `$1` at the end of the replace instead of `\n`? That way, you can have one liners if you want.

So it would be `\/\*\*\s*JSDOC SOURCE \w+(\n?)/g` (I took out the brackets around `\s` while I was at it since it doesn't do anything) and `'/**$1'` with my suggestion.
___
*[`lib/papi-dts/edit-papi-d-ts.ts` line 29 at r3](https://reviewable.io/reviews/paranext/paranext-core/310#-NaCXaM2A6F7IZj4k2tQ:-NaCXaM2A6F7IZj4k2tR:b-qyt2sq) ([raw file](https://github.com/paranext/paranext-core/blob/e344291d63de3edc1eecd3f478bc4e0988dd6396/lib/papi-dts/edit-papi-d-ts.ts#L29)):*
> ```XML
>   );
> 
> // #region Copy "JSDOC DESTINATION" blocks to "JSDOC SOURCE" blocks
> ```

Think you could add some documentation about this to the main `paranext-core/README.md`? Seems like it would be helpful maybe to add it in a "Special Features" section [like I'm adding](https://github.com/paranext/paranext-core/tree/280-webpack/extensions#special-features-of-this-project) with the webpack changes. Note my comment below about the different constraints on JSDOC SOURCE and DESTINATION
___
*[`lib/papi-dts/edit-papi-d-ts.ts` line 47 at r3](https://reviewable.io/reviews/paranext/paranext-core/310#-NaCWomx5tMlh78M6FOS:-NaCWomx5tMlh78M6FOT:bcqc30y) ([raw file](https://github.com/paranext/paranext-core/blob/e344291d63de3edc1eecd3f478bc4e0988dd6396/lib/papi-dts/edit-papi-d-ts.ts#L47)):*
> ```XML
>     if (jsdocSources.has(name)) {
>       console.error(`JSDOC SOURCE for ${name} was defined more than once`);
>       exit(-1);
> ```

I wonder if it might be worth collecting an array of errors and then only exiting at the end (before or after writing `papi.d.ts`? Not sure) or whenever there's a serious error so people know all the problems that are occurring. What do you think? Maybe not worth spending time on now; feel free to do what you'd like.
___
*[`lib/papi-dts/edit-papi-d-ts.ts` line 63 at r3](https://reviewable.io/reviews/paranext/paranext-core/310#-NaCW2579-7a2Sq8mBeu:-NaCW2579-7a2Sq8mBev:b-re01hk) ([raw file](https://github.com/paranext/paranext-core/blob/e344291d63de3edc1eecd3f478bc4e0988dd6396/lib/papi-dts/edit-papi-d-ts.ts#L63)):*
> ```XML
>   const sourceBlock = jsdocSources.get(name);
>   if (sourceBlock) {
>     papiDTS = papiDTS.replace(block, sourceBlock);
> ```

I see we don't have a check to make sure all the JSDOC SOURCE things got used. Think it's worth putting a boolean in the `jsdocSources` values that indicates if it was used and then go through and make sure they were all used after? Seems like that might be worth an error.
___
*[`src/extension-host/services/papi-backend.service.ts` line 23 at r2](https://reviewable.io/reviews/paranext/paranext-core/310#-NaCT6jF7iXOlO1RKQzJ:-NaCT6jF7iXOlO1RKQzK:bh2r335) ([raw file](https://github.com/paranext/paranext-core/blob/b46be08c4350f941981c16daf6b1e40440f24ca2/src/extension-host/services/papi-backend.service.ts#L23)):*
> ```XML
> } from '@extension-host/services/extension-storage.service';
> 
> // Note: we need to provide type assertions for all members so they carry the JSDoc comments on the
> ```

Is this still the case? Or can we leave these assertions out with this new comment stuff?
___
*[`src/renderer/services/papi-frontend.service.ts` line 19 at r2](https://reviewable.io/reviews/paranext/paranext-core/310#-NaCTR8L5lGFOK2tkoCA:-NaCTR8L5lGFOK2tkoCB:bx4kvxr) ([raw file](https://github.com/paranext/paranext-core/blob/b46be08c4350f941981c16daf6b1e40440f24ca2/src/renderer/services/papi-frontend.service.ts#L19)):*
> ```XML
> 
> // Note: we need to provide type assertions for all members so they carry the JSDoc comments on the
> // papi.d.ts file so extension developers see the comments. Please add to all properties you add.
> ```

I imagined I'd see the new "Also" comment from the other file here as well. And same here as with the other comment - do we need to assert things now that we have this new carry-over syntax?
___
*[`src/renderer/services/papi-frontend.service.ts` line 23 at r2](https://reviewable.io/reviews/paranext/paranext-core/310#-NaCU3Bw8ZqiBQW3E66K:-NaCU3Bw8ZqiBQW3E66L:bg4fl8g) ([raw file](https://github.com/paranext/paranext-core/blob/b46be08c4350f941981c16daf6b1e40440f24ca2/src/renderer/services/papi-frontend.service.ts#L23)):*
> ```XML
>   // Classes
>   /** JSDOC DESTINATION PapiEventEmitter */
>   EventEmitter: PapiEventEmitter,
> ```

Since we can no longer share parts of the papi, could we add a region that has the shared stuff in it? Maybe also a reminder comment explaining that people should consider whether they should add stuff to both when they are adding things to these files?

**Review by lyonsil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/310)* status: 17 of 21 files reviewed, 2 unresolved discussions (waiting on @irahopkinson and @tjcouch-sil)

___
*[`lib/papi-dts/edit-papi-d-ts.ts` line 40 at r2](https://reviewable.io/reviews/paranext/paranext-core/310#-NaCINSr6dyFfgeJvwbQ:-NaD4wX89G-d4gAEaYYu:b-1c0plv) ([raw file](https://github.com/paranext/paranext-core/blob/b46be08c4350f941981c16daf6b1e40440f24ca2/lib/papi-dts/edit-papi-d-ts.ts#L40)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

Part of me wants to put curly braces around the magic comment like `/** {JSDOC SOURCE thingy}` or something. That way, it's very well-defined what the string is and more obvious that this is something special we're doing (and you can have spaces if you want, though that's kinda a side effect more than the main reason to do it). Maybe even make the words something more catered to us like PAPIDOC SRC and DEST or something (though I know we said not to abbreviate words. Just thing to make it not so long especially since I added two characters)? Just some thoughts; you don't have to do either of these.
</blockquote></details>

I'm going to avoid touching the regex I think at this point unless we really need to change the syntax.
___
*[`lib/papi-dts/edit-papi-d-ts.ts` line 71 at r2](https://reviewable.io/reviews/paranext/paranext-core/310#-NaCFa7lBgYvnp9vKJMw:-NaCrX-kAShVQj_MHFWo:b-f56lfq) ([raw file](https://github.com/paranext/paranext-core/blob/b46be08c4350f941981c16daf6b1e40440f24ca2/lib/papi-dts/edit-papi-d-ts.ts#L71)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

I believe I see here that JSDOC SOURCE must have a newline afterward, but that condition is not required for DESTINATION. What do you think of making a capture group around the `\n` and making it `\n?` and then putting `$1` at the end of the replace instead of `\n`? That way, you can have one liners if you want.

So it would be `\/\*\*\s*JSDOC SOURCE \w+(\n?)/g` (I took out the brackets around `\s` while I was at it since it doesn't do anything) and `'/**$1'` with my suggestion.
</blockquote></details>

Yes, I was assuming no one-liners, but I guess there is no great reason to block them.  I applied your suggested change to enable them, though I left the brackets around `\s` because it starts the same as the earlier regex.  Originally I had included more in the brackets, but after taking the other parts out I left the brackets because I think it makes the regex easier to read.  `\\/\\\*\\\*` is really awkward to parse when reading code.
___
*[`lib/papi-dts/edit-papi-d-ts.ts` line 29 at r3](https://reviewable.io/reviews/paranext/paranext-core/310#-NaCXaM2A6F7IZj4k2tQ:-NaDBNKr7BkV-hQSBOSz:b-896fix) ([raw file](https://github.com/paranext/paranext-core/blob/e344291d63de3edc1eecd3f478bc4e0988dd6396/lib/papi-dts/edit-papi-d-ts.ts#L29)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

Think you could add some documentation about this to the main `paranext-core/README.md`? Seems like it would be helpful maybe to add it in a "Special Features" section [like I'm adding](https://github.com/paranext/paranext-core/tree/280-webpack/extensions#special-features-of-this-project) with the webpack changes. Note my comment below about the different constraints on JSDOC SOURCE and DESTINATION
</blockquote></details>

Done.
___
*[`lib/papi-dts/edit-papi-d-ts.ts` line 47 at r3](https://reviewable.io/reviews/paranext/paranext-core/310#-NaCWomx5tMlh78M6FOS:-NaCjUMr1Dh-d4RwmNZI:b-74lx28) ([raw file](https://github.com/paranext/paranext-core/blob/e344291d63de3edc1eecd3f478bc4e0988dd6396/lib/papi-dts/edit-papi-d-ts.ts#L47)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

I wonder if it might be worth collecting an array of errors and then only exiting at the end (before or after writing `papi.d.ts`? Not sure) or whenever there's a serious error so people know all the problems that are occurring. What do you think? Maybe not worth spending time on now; feel free to do what you'd like.
</blockquote></details>

I delayed the `exit()` call to after lookup and replace work is complete if there is an error.
___
*[`lib/papi-dts/edit-papi-d-ts.ts` line 63 at r3](https://reviewable.io/reviews/paranext/paranext-core/310#-NaCW2579-7a2Sq8mBeu:-NaCr3otAEAlMkhJNYaT:b-4l6snq) ([raw file](https://github.com/paranext/paranext-core/blob/e344291d63de3edc1eecd3f478bc4e0988dd6396/lib/papi-dts/edit-papi-d-ts.ts#L63)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

I see we don't have a check to make sure all the JSDOC SOURCE things got used. Think it's worth putting a boolean in the `jsdocSources` values that indicates if it was used and then go through and make sure they were all used after? Seems like that might be worth an error.
</blockquote></details>

Good point - I added a check for this.
___
*[`src/extension-host/services/papi-backend.service.ts` line 23 at r2](https://reviewable.io/reviews/paranext/paranext-core/310#-NaCT6jF7iXOlO1RKQzJ:-NaCwR6802pHOs5RinCn:b-etf5wz) ([raw file](https://github.com/paranext/paranext-core/blob/b46be08c4350f941981c16daf6b1e40440f24ca2/src/extension-host/services/papi-backend.service.ts#L23)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

Is this still the case? Or can we leave these assertions out with this new comment stuff?
</blockquote></details>


This change does not eliminate the need for type assertions.  If you add comments to function properties of objects that implement an interface (e.g., `getNetworkEvent()` in `networkService`), `tsc` doesn't copy your JSDoc comments over to the `d.ts` file.  Also, if you eliminate the interfaces altogether and just try to use new this doc copying functionality, Intellisense will now show you the docs.  There is a split for how it handles functions  (and arrow functions) vs non-functions.  Functions seem to get docs through interfaces while non-functions require direct comments.

It's perhaps worth noting that this is all undocumented behavior of VSCode that could change in the future.
___
*[`src/renderer/services/papi-frontend.service.ts` line 19 at r2](https://reviewable.io/reviews/paranext/paranext-core/310#-NaCTR8L5lGFOK2tkoCA:-NaCx61J6Yks6pkvqqJu:b-trhoxn) ([raw file](https://github.com/paranext/paranext-core/blob/b46be08c4350f941981c16daf6b1e40440f24ca2/src/renderer/services/papi-frontend.service.ts#L19)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

I imagined I'd see the new "Also" comment from the other file here as well. And same here as with the other comment - do we need to assert things now that we have this new carry-over syntax?
</blockquote></details>

Good point - I added the "Also" comment here.

This change does not eliminate the need for type assertions.  If you add comments to function properties of objects that implement an interface (e.g., `getNetworkEvent()` in `networkService`), `tsc` doesn't copy your JSDoc comments over to the `d.ts` file.  Also, if you eliminate the interfaces altogether and just try to use new this doc copying functionality, Intellisense will now show you the docs.  There is a split for how it handles functions  (and arrow functions) vs non-functions.  Functions seem to get docs through interfaces while non-functions require direct comments.

It's perhaps worth noting that this is all undocumented behavior of VSCode that could change in the future.
___
*[`src/renderer/services/papi-frontend.service.ts` line 23 at r2](https://reviewable.io/reviews/paranext/paranext-core/310#-NaCU3Bw8ZqiBQW3E66K:-NaCyzFcCJbptdlPl6dJ:br6ions) ([raw file](https://github.com/paranext/paranext-core/blob/b46be08c4350f941981c16daf6b1e40440f24ca2/src/renderer/services/papi-frontend.service.ts#L23)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

Since we can no longer share parts of the papi, could we add a region that has the shared stuff in it? Maybe also a reminder comment explaining that people should consider whether they should add stuff to both when they are adding things to these files?
</blockquote></details>

I'm not sure there is much value in artificially trying to create code blocks that are copy/paste identical over time between the two places.  It doesn't actually do anything different in the code, and anything that people have to remember will eventually have a mistake.  Also we might decide to make them different on purpose for other reasons.  For example, in this PR I included `papiWebViewProviderService` on the back end but not the front end based on recent discussions.

Having said all this, I added a comment to both files as a reminder to consider whether new additions to one should also go to the other to minimize the risk of accidental oversight.

**Review by lyonsil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/310)* status: 17 of 21 files reviewed, 2 unresolved discussions (waiting on @irahopkinson and @tjcouch-sil)

___
*[`lib/papi-dts/edit-papi-d-ts.ts` line 42 at r1](https://reviewable.io/reviews/paranext/paranext-core/310#-Na5CQ570RyIw3JNOlSV:-NaDCAZ321C7RhhPcjYj:b-diywgu) ([raw file](https://github.com/paranext/paranext-core/blob/fcba145159d5d40f60d1e4ff8db14a22288fef6c/lib/papi-dts/edit-papi-d-ts.ts#L42)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

[Comment from before Matt's most recent update and comment. I was looking at r2. Do whatever you'd like :)]
I have never seen this syntax before; very unusual. Honestly it's hard to read... I would have thought an assignment would return true if it worked and false otherwise, but apparently it returns the result of the assignment. Strange haha but I admit I do like that you don't have to write twice the code that sets the variable for the while condition like this. That has always bothered me about while loops, too, Matt.

One thing we could do is put an item in the style doc about it and leave it here with the single-line disable or the block-level `"except-parens"` disable. However, our style guide does require that you state why you have disabled something if you disabled it. So I suggest if you leave it that you put another comment above the disabling line that says you use it here to avoid having to write the assignment twice because while loops are annoying.
</blockquote></details>

I think this is resolved now.

**Review by tjcouch-sil — APPROVED** [review]
:lgtm: everything looks great! Thanks a ton for the hard work!

> Reviewed 4 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/310#-:-NaDsWWMCTN_bDaTT0xQ:bkrvv1e)* status: all files reviewed, 1 unresolved discussion (waiting on @irahopkinson)

___
*[`README.md` line 208 at r4](https://reviewable.io/reviews/paranext/paranext-core/310#-NaDr_oc6g2sLApKyBU7:-NaDr_od8ut1w1DTH11i:br3z6pp) ([raw file](https://github.com/paranext/paranext-core/blob/55514372e45a87884ed9d444f74a15d7230e8a1b/README.md#L208)):*
> ```Markdown
> ```typescript
> /** JSDOC SOURCE myService
>   * myService is amazing. Here are more details about it.
> ```

🔥🔥amazing service

**Review by irahopkinson — APPROVED** [review]
:lgtm:

> Reviewed 4 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/310#-:-NaDvJX_84BLyDz7vO1p:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
