### PR TITLE
435 basic list 

### PR DESCRIPTION
**Pull request by rolfheij-sil**
This change is [Reviewable](https://reviewable.io/reviews/paranext/paranext-core/550)

### CODE REVIEW

**Review by tjcouch-sil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/550)* status: 0 of 6 files reviewed, all discussions resolved

___
*[`src/renderer/components/basic-list/basic-list.component.tsx` line 10 at r1](https://reviewable.io/reviews/paranext/paranext-core/550#-NgdfiBCCp_SjV1vx3uE:-NgdfiBCCp_SjV1vx3uF:bh4h3yy) ([raw file](https://github.com/paranext/paranext-core/blob/4636e50c50adfb848ad847447a934ffe3abaad0b/src/renderer/components/basic-list/basic-list.component.tsx#L10)):*
> ```XML
>   ColumnDef,
>   flexRender,
> } from '@tanstack/react-table';
> ```

Any particular reason you didn't want to use the data grid component we already have?

**Review by irahopkinson — CHANGES_REQUESTED** [review]
Thanks for your work on this. It would be helpful to have a screenshot in the PR description so I don't have to run up your branch.

> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/550#-:-NgpDW5A28-oPztlBibw:b-aq3g5s)* status: all files reviewed, 4 unresolved discussions (waiting on @rolfheij-sil)

___
*[`src/renderer/components/basic-list/basic-list.component.tsx` line 18 at r1](https://reviewable.io/reviews/paranext/paranext-core/550#-Ngp8FuS4mtDFEnvrfkb:-Ngp8FuS4mtDFEnvrfkc:b-u0hexi) ([raw file](https://github.com/paranext/paranext-core/blob/4636e50c50adfb848ad847447a934ffe3abaad0b/src/renderer/components/basic-list/basic-list.component.tsx#L18)):*
> ```XML
> export const TAB_TYPE_BASIC_LIST = 'basic-list';
> 
> type checkResult = {
> ```

Style: types (and interfaces and classes) should always start with a capital letter, i.e. use PascalCase.
___
*[`src/renderer/components/basic-list/basic-list.component.tsx` line 26 at r1](https://reviewable.io/reviews/paranext/paranext-core/550#-Ngp8sC-EtC_5MbmOx2i:-Ngp8sC-EtC_5MbmOx2j:b-aht7ia) ([raw file](https://github.com/paranext/paranext-core/blob/4636e50c50adfb848ad847447a934ffe3abaad0b/src/renderer/components/basic-list/basic-list.component.tsx#L26)):*
> ```XML
> };
> 
> const newCheckResult = (bookId: string): checkResult => {
> ```

For functions that have simple returns, use the simplified return syntax for arrow functions, i.e.:
```typescript
const newCheckResult = (bookId: string): checkResult => ({
  book: Canon.bookIdToEnglishName(bookId),
  chapter: faker.number.int(40),
  verse: faker.number.int(40),
  issueDescription: 'Basic check issue description',
});
```
___
*[`src/renderer/components/basic-list/basic-list.component.tsx` line 35 at r1](https://reviewable.io/reviews/paranext/paranext-core/550#-NgpATNv0bLGYrIRrELw:-NgpATNv0bLGYrIRrELx:bu81u53) ([raw file](https://github.com/paranext/paranext-core/blob/4636e50c50adfb848ad847447a934ffe3abaad0b/src/renderer/components/basic-list/basic-list.component.tsx#L35)):*
> ```XML
> };
> 
> export function makeMockCheckResults() {
> ```

BTW Does this need to be exported? It's not currently used anywhere outside of this module.
___
*[`src/renderer/components/basic-list/basic-list.component.tsx` line 36 at r1](https://reviewable.io/reviews/paranext/paranext-core/550#-NgpBjal5WNXAWx44AWz:-NgpBjal5WNXAWx44AX-:b-fqa1rk) ([raw file](https://github.com/paranext/paranext-core/blob/4636e50c50adfb848ad847447a934ffe3abaad0b/src/renderer/components/basic-list/basic-list.component.tsx#L36)):*
> ```XML
> 
> export function makeMockCheckResults() {
>   const { allBookIds } = Canon;
> ```

BTW If you used this more than once it might make sense to destructure this but even then I would still just derefence it below since it is then easy to read that you are getting `allBookIds` from `Canon` on the one line, i.e.:
```typescipt
return Canon.allBookIds.map((bookId) => {
```
This may be more of a personal style call so feel free to leave it as is.

**Review by rolfheij-sil — COMMENTED** [review]
Thanks for the feedback! I'll make sure to add a screenshot next time round

> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/550#-:-NgrZR-Y5w94A1nW7pfR:bya0kxe)* status: 5 of 6 files reviewed, 3 unresolved discussions (waiting on @irahopkinson)

___
*[`src/renderer/components/basic-list/basic-list.component.tsx` line 10 at r1](https://reviewable.io/reviews/paranext/paranext-core/550#-NgdfiBCCp_SjV1vx3uE:-NgrYYgA5HtlCY5ZOn-O:b2qaq4h) ([raw file](https://github.com/paranext/paranext-core/blob/4636e50c50adfb848ad847447a934ffe3abaad0b/src/renderer/components/basic-list/basic-list.component.tsx#L10)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

Any particular reason you didn't want to use the data grid component we already have?
</blockquote></details>

Because I thought it did not support expanding rows. But I just realized that it does (https://adazzle.github.io/react-data-grid/#/master-detail)
I'll try to do a small investigation into using that component
___
*[`src/renderer/components/basic-list/basic-list.component.tsx` line 18 at r1](https://reviewable.io/reviews/paranext/paranext-core/550#-Ngp8FuS4mtDFEnvrfkb:-NgrYtrsEYIEiYyUGJC1:b7eoo17) ([raw file](https://github.com/paranext/paranext-core/blob/4636e50c50adfb848ad847447a934ffe3abaad0b/src/renderer/components/basic-list/basic-list.component.tsx#L18)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

Style: types (and interfaces and classes) should always start with a capital letter, i.e. use PascalCase.
</blockquote></details>

Done. Shouldn't eslint check for that?
___
*[`src/renderer/components/basic-list/basic-list.component.tsx` line 26 at r1](https://reviewable.io/reviews/paranext/paranext-core/550#-Ngp8sC-EtC_5MbmOx2i:-NgrZ4WE5w91NEVJRFgc:b-896fix) ([raw file](https://github.com/paranext/paranext-core/blob/4636e50c50adfb848ad847447a934ffe3abaad0b/src/renderer/components/basic-list/basic-list.component.tsx#L26)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

For functions that have simple returns, use the simplified return syntax for arrow functions, i.e.:
```typescript
const newCheckResult = (bookId: string): checkResult => ({
  book: Canon.bookIdToEnglishName(bookId),
  chapter: faker.number.int(40),
  verse: faker.number.int(40),
  issueDescription: 'Basic check issue description',
});
```
</blockquote></details>

Done.
___
*[`src/renderer/components/basic-list/basic-list.component.tsx` line 35 at r1](https://reviewable.io/reviews/paranext/paranext-core/550#-NgpATNv0bLGYrIRrELw:-NgrZ6d90VaUccvCi1re:b-crcq4f) ([raw file](https://github.com/paranext/paranext-core/blob/4636e50c50adfb848ad847447a934ffe3abaad0b/src/renderer/components/basic-list/basic-list.component.tsx#L35)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

BTW Does this need to be exported? It's not currently used anywhere outside of this module.
</blockquote></details>

Yup, you're right. The creation of mock data was in a separate file, but I decided to merge the two. Forgot to remove the export though.
___
*[`src/renderer/components/basic-list/basic-list.component.tsx` line 36 at r1](https://reviewable.io/reviews/paranext/paranext-core/550#-NgpBjal5WNXAWx44AWz:-NgrZNOi9lM_pv1Xk17B:b-896fix) ([raw file](https://github.com/paranext/paranext-core/blob/4636e50c50adfb848ad847447a934ffe3abaad0b/src/renderer/components/basic-list/basic-list.component.tsx#L36)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

BTW If you used this more than once it might make sense to destructure this but even then I would still just derefence it below since it is then easy to read that you are getting `allBookIds` from `Canon` on the one line, i.e.:
```typescipt
return Canon.allBookIds.map((bookId) => {
```
This may be more of a personal style call so feel free to leave it as is.
</blockquote></details>

Done.

**Review by irahopkinson — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/550#-:-Ngu-8_C5tK_9YuX4Q2j:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @rolfheij-sil)

___
*[`src/renderer/components/basic-list/basic-list.component.tsx` line 18 at r1](https://reviewable.io/reviews/paranext/paranext-core/550#-Ngp8FuS4mtDFEnvrfkb:-NgtyhX62UWU4GpdRKa4:bmvra6w) ([raw file](https://github.com/paranext/paranext-core/blob/4636e50c50adfb848ad847447a934ffe3abaad0b/src/renderer/components/basic-list/basic-list.component.tsx#L18)):*
<details><summary><i>Previously, rolfheij-sil wrote…</i></summary><blockquote>

Done. Shouldn't eslint check for that?
</blockquote></details>

Yes, but I don't yet know of a rule to use for this.
___
*[`src/renderer/components/basic-list/basic-list.component.tsx` line 33 at r2](https://reviewable.io/reviews/paranext/paranext-core/550#-Ngtyvdj5pR7U7TPyBQQ:-NgtyvdkCKCfP8iJE48b:bsp3gv5) ([raw file](https://github.com/paranext/paranext-core/blob/655369654ee9e632ea18888825b5de5dffe696ea/src/renderer/components/basic-list/basic-list.component.tsx#L33)):*
> ```XML
> });
> 
> const makeMockCheckResults = () => {
> ```

BTW not a blocker but curious why you changed this to an arrow function? I tend to use arrow functions for smaller and/or simpler returns or if I need a named function that I'm passing around and definitley if I'm using `this` in it, otherwise my default is to use `function`. `functions` are hoisted in the scope so they tend to cause less issues around where they are declared than arrow functions.

**Review by rolfheij-sil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/550)* status: all files reviewed, 1 unresolved discussion (waiting on @irahopkinson)

___
*[`src/renderer/components/basic-list/basic-list.component.tsx` line 33 at r2](https://reviewable.io/reviews/paranext/paranext-core/550#-Ngtyvdj5pR7U7TPyBQQ:-Ngx1UGS12tW4qJz-ILl:b-q6gedm) ([raw file](https://github.com/paranext/paranext-core/blob/655369654ee9e632ea18888825b5de5dffe696ea/src/renderer/components/basic-list/basic-list.component.tsx#L33)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

BTW not a blocker but curious why you changed this to an arrow function? I tend to use arrow functions for smaller and/or simpler returns or if I need a named function that I'm passing around and definitley if I'm using `this` in it, otherwise my default is to use `function`. `functions` are hoisted in the scope so they tend to cause less issues around where they are declared than arrow functions.
</blockquote></details>

I changed it because for consistency reasons. The `newCheckResults` was also an arrow function, and I thought it'd look more uniform if I changed this one too.
Thanks for sharing your reasons for when to (not) use arrow functions, that's helpful!

**Review by irahopkinson — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/550)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by katherinejensen00 — APPROVED** [review]
:lgtm:

> Reviewed 3 of 6 files at r1, 1 of 1 files at r2, 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/550#-:-Nh26uja0oAuGGX6StPH:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
