### PR TITLE
Misc cleanup

### PR DESCRIPTION
**Pull request by irahopkinson**
- remove irrelevant comment in pre-commit hook
- don't need `npx` in npm scripts
- prettier `tsconfig.json` and `launch.json`
- add `new` to all `throw Error` to be correct

- - -
This change is [Reviewable](https://reviewable.io/reviews/paranext/paranext-core/165)

### CODE REVIEW

**Review by rolfheij-sil — APPROVED** [review]
Looks good. One small question about the pre-commit file

> Reviewed 12 of 12 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/165#-:-NULIr8d8BWDP3qOQ2Gt:b-7z8b0u)* status: all files reviewed, 1 unresolved discussion (waiting on @irahopkinson)

___
*[`.husky/pre-commit` line 6 at r1](https://reviewable.io/reviews/paranext/paranext-core/165#-NULITBf9Ie4Xrz3_QU5:-NULITBf9Ie4Xrz3_QU6:b-d49zdy) ([raw file](https://github.com/paranext/paranext-core/blob/3c5dbbe5b32412465783b818463a549698f30301/.husky/pre-commit#L6)):*
> ```
> echo "Running Lint check..."
> 
> # need to generate the .d.ts files for the extensions in the extensions/dist folder
> ```

Have we already created a task in the backlog for this?

**Review by irahopkinson — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/165)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @irahopkinson)

___
*[`.husky/pre-commit` line 6 at r1](https://reviewable.io/reviews/paranext/paranext-core/165#-NULITBf9Ie4Xrz3_QU5:-NULiXbJEvbAaDZV0qZE:b-7nwa0n) ([raw file](https://github.com/paranext/paranext-core/blob/3c5dbbe5b32412465783b818463a549698f30301/.husky/pre-commit#L6)):*
<details><summary><i>Previously, rolfheij-sil wrote…</i></summary><blockquote>

Have we already created a task in the backlog for this?
</blockquote></details>

I don't know and didn't create this comment but it's already on `main` (you would need to ask TJ since he created it). I just removed the comment below it that is no longer relevant. The line used to be `npx lint-staged -q` (which had the `-q` option). It now calls the `lint:staged` script in `package.jso`n so the comment is no longer relevant.

**Review by rolfheij-sil — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/165#-:-NULjrQP-YquVraTUjYr:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by tjcouch-sil — COMMENTED** [review]
> Reviewed 12 of 12 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/165)* status: all files reviewed, 2 unresolved discussions

___
*[`.husky/pre-commit` line 7 at r1](https://reviewable.io/reviews/paranext/paranext-core/165#-NUMPARm1EigT1K3Bby_:-NUMPARm1EigT1K3Bbya:b-byyl3a) ([raw file](https://github.com/paranext/paranext-core/blob/10d536d9cb4c9d1b98f076ed56b757f515ec55cc/.husky/pre-commit#L7)):*
> ```
> 
> # need to generate the .d.ts files for the extensions in the extensions/dist folder
> # -q enables quiet mode to show nothing unless it has an error
> ```

I wish we could put comments in the npm scripts :( would it be worth investigating a good way to do this? Both of these comments are irrelevant really. Both are now embedded in `lint:staged`. But I just didn't know what to do about them, so I left them.
___
*[`src/extension-host/services/extension.service.ts` line 180 at r1](https://reviewable.io/reviews/paranext/paranext-core/165#-NUMPUUm2VWbive0Alib:-NUMPUUm2VWbive0Alic:b-meppmz) ([raw file](https://github.com/paranext/paranext-core/blob/3c5dbbe5b32412465783b818463a549698f30301/src/extension-host/services/extension.service.ts#L180)):*
> ```XML
>   // eslint-disable-next-line no-global-assign
>   globalThis.WebSocket = function WebSocketForbidden() {
>     throw new Error('Cannot use WebSocket!');
> ```

Maybe we should make a code style guideline about this?

**Comment by irahopkinson** [comment]
Good Idea. I've added it to the wiki for now but there is a rule for this so I've also added it to the list of todos in the **Style Guide Evaluation** doc.

**Review by tjcouch-sil — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/165#-:-NUXURhX0ew7-3zNM5tL:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
