### PR TITLE
preview app: add pages: paratext, colors

### PR DESCRIPTION
**Pull request by Sebastian-ubs**
This change is [Reviewable](https://reviewable.io/reviews/paranext/paranext-core/988)

grafik

### CODE REVIEW

**Comment by merchako** [comment]
I'm noticing that the text on primary, secondary-foreground, and accent-foreground (and maybe destructive) are illegible and would fail WCAG AA. Should I expect for contrast issues to be addressed in this PR, @Sebastian-ubs ?

**Review by rolfheij-sil — APPROVED** [review]
> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/988)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Comment by Sebastian-ubs** [comment]
> I'm noticing that the text on primary, secondary-foreground, and accent-foreground (and maybe destructive) are illegible and would fail WCAG AA. Should I expect for contrast issues to be addressed in this PR, @Sebastian-ubs ?

@merchako Thanks for noting this, this PR is about adding pages to the preview app, not changing the PT10 draft style. Please add a separate issue proposing new colors.
BTW I also recognized that the dark theme uses a white color for Card, which is not expected. You may want to add this to your new issue.

**Comment by Sebastian-ubs** [comment]
> @merchako Please add a separate issue proposing new colors.

Created https://github.com/paranext/ux/issues/113

**Pull request merged**
