### PR TITLE
Bundled react-data-grid into papi-components instead of making it a peer dependency

### PR DESCRIPTION
**Pull request by tjcouch-sil**
Seems strange to require packages that depend on `papi-components` to install and worry about versioning for `react-data-grid` since it's an implementation detail. I made it a bundled dependency, so now it's a `devDependency`.

The code for react-data-grid will bundle into all extensions that use it either way since `papi-components` is currently bundled. And it will not be bundled if we make `papi-components` external.

I don't remember why we made it external in the first place. Are we doing it in case someone wanted to use `react-data-grid` in their extension? I guess we could just make that specific package external and let them import it as well. But we also could just test and see if the bundler is smart enough to tell that it is in both places and share that code if we are particularly concerned about this use case, but it seems hopefully rare enough that we might not need to worry about it. If anyone has perspective on it, please feel free to share now :)

This is more of a discussion PR currently than actually proposing we merge this code, so it is a draft.

- - -
This change is [Reviewable](https://reviewable.io/reviews/paranext/paranext-core/297)

### CODE REVIEW

**Review by irahopkinson — APPROVED** [review]
:lgtm:

I don't recall why it was like that. If I had to guess I would say something didn't work early one until I made it an external dependency but it probably didn't solve the issue and I never went back and re-evaluted it after I got things working. I don't see a problem with changing it like this for now.

> Reviewed 9 of 9 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/297#-:-N_aWXgd1T4G9xLlYW8L:bgg1txd)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by lyonsil — COMMENTED** [review]
See my related PR: https://github.com/paranext/paranext-core/pull/302

I'm suggesting we move more things into peer dependencies because it is causing us to load some packages twice which potentially leads to other problems.

> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/297#-:-N_dsrTaBf-bfOkkUs9x:bywea8q)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by lyonsil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/297)* status: all files reviewed, 1 unresolved discussion (waiting on @tjcouch-sil)

___
*[`lib/papi-components/package.json` line 49 at r1](https://reviewable.io/reviews/paranext/paranext-core/297#-N_du_tKBki4P-WSBunM:-N_du_tKBki4P-WSBunN:bkxmytc) ([raw file](https://github.com/paranext/paranext-core/blob/31dd63afe64bac7321b97532abeff0951b337475/lib/papi-components/package.json#L49)):*
> ```JSON
>     "@emotion/react": "^11.10.6",
>     "@emotion/styled": "^11.10.6",
>     "@mui/material": "^5.11.12",
> ```

It seems like we want to move more things into `peerDependencies`, not fewer things.

https://github.com/mui/material-ui/issues/34150#issuecomment-1634751266

**Comment by irahopkinson** [comment]
Closed as it has not moved in some time.

**Pull request closed without merging**
