### PR TITLE
break up preview app into more components

### PR DESCRIPTION
**Pull request by Sebastian-ubs**
This change is [Reviewable](https://reviewable.io/reviews/paranext/paranext-core/997)

### CODE REVIEW

**Comment by Sebastian-ubs** [comment]
for some reason, the bcv dropdown chapter selector is now broken. Probably because it is used in a wrapping `pr-flex`. Need to find the right fix.
grafik

**Review by rolfheij-sil — DISMISSED** [review]
> Reviewed 16 of 16 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/997)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Comment by Sebastian-ubs** [comment]
resolved merge conflic, please re-approve

**Review by rolfheij-sil — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/997#-:-O1wOTvY8YaMULva2oLI:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Pull request merged**
