### PR TITLE
fix: `manageExtensions` provider correctly parses extension name on Windows

### PR DESCRIPTION
**Pull request by captaincrazybro**
This change is [Reviewable](https://reviewable.io/reviews/paranext/paranext-core/1040)

### CODE REVIEW

**Review by tjcouch-sil — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/1040)* status: all files reviewed, 1 unresolved discussion (waiting on @captaincrazybro)

___
*[`src/extension-host/services/extension.service.ts` line 615 at r1](https://reviewable.io/reviews/paranext/paranext-core/1040#-O3YKP2LC853tgS5qTn1:-O3YKP2LC853tgS5qTn2:b-l2ss58) ([raw file](https://github.com/paranext/paranext-core/blob/c7bc03181df370e661e708f73edeb8339027fb30/src/extension-host/services/extension.service.ts#L615)):*
> ```XML
>   return fileUris.map((fileUri: string) => {
>     // Splits by either a forward-slash or back-slash to support Windows as well
>     const fileName = fileUri.split(/\\|\//).pop();
> ```

Have you considered using `path.sep`?

**Review by captaincrazybro — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/1040)* status: all files reviewed, 1 unresolved discussion (waiting on @tjcouch-sil)

___
*[`src/extension-host/services/extension.service.ts` line 615 at r1](https://reviewable.io/reviews/paranext/paranext-core/1040#-O3YKP2LC853tgS5qTn1:-O3YaBYpBBXVvbFtWprX:bok3afq) ([raw file](https://github.com/paranext/paranext-core/blob/c7bc03181df370e661e708f73edeb8339027fb30/src/extension-host/services/extension.service.ts#L615)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

Have you considered using `path.sep`?
</blockquote></details>

Wow, that is so much easier :)

**Review by tjcouch-sil — APPROVED** [review]
:lgtm: thanks for the good catch!

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/1040#-:-O3YaXft8C5YASCAMia_:bpmsicb)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Review by katherinejensen00 — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/1040#-:-O3YbJrc184Nrl6WELY-:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Pull request merged**
