### PR TITLE
Snackbar component

### PR DESCRIPTION
**Pull request by jolierabideau**
This change is [Reviewable](https://reviewable.io/reviews/paranext/paranext-core/249)

### CODE REVIEW

**Review by rolfheij-sil — CHANGES_REQUESTED** [review]
Awesome work! Your first component! :smile: 

> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/249#-:-NYJUcl_BCfbVkhYxdzM:b4scpfp)* status: all files reviewed, 12 unresolved discussions (waiting on @jolierabideau)

___
*[`lib/papi-components/src/snackbar.component.tsx` line 6 at r1](https://reviewable.io/reviews/paranext/paranext-core/249#-NYJQub_BMvocv0V7Uab:-NYJQub_BMvocv0V7Uac:bhgtm66) ([raw file](https://github.com/paranext/paranext-core/blob/fa9be20f24c2e0c8a4b639687e6aa91989cadf52/lib/papi-components/src/snackbar.component.tsx#L6)):*
> ```XML
> import './snackbar.component.css';
> 
> export type CloseReason = 'timeout' | 'clickaway' | 'escapeKeyDown';
> ```

It might be better to just copy the close reasons provided by MUI.
`export type CloseReason = SnackbarCloseReason`
You'd have to import `SnackbarCloseReason` for that to work obviously.
___
*[`lib/papi-components/src/snackbar.component.tsx` line 8 at r1](https://reviewable.io/reviews/paranext/paranext-core/249#-NYJRFnG4cNObW7Xbe2A:-NYJRFnG4cNObW7Xbe2B:b59jok6) ([raw file](https://github.com/paranext/paranext-core/blob/fa9be20f24c2e0c8a4b639687e6aa91989cadf52/lib/papi-components/src/snackbar.component.tsx#L8)):*
> ```XML
> export type CloseReason = 'timeout' | 'clickaway' | 'escapeKeyDown';
> 
> export interface AnchorOrigin {
> ```

Here you could copy `SnackbarOrigin` from MUI
___
*[`lib/papi-components/src/snackbar.component.tsx` line 32 at r1](https://reviewable.io/reviews/paranext/paranext-core/249#-NYJGkYU5QuaXgGOzrjA:-NYJGkYV5nce81kI7_tf:b-veas06) ([raw file](https://github.com/paranext/paranext-core/blob/fa9be20f24c2e0c8a4b639687e6aa91989cadf52/lib/papi-components/src/snackbar.component.tsx#L32)):*
> ```XML
>    * The system prop that allows defining system overrides as well as additional CSS styles.
>    */
>   sx?: SxProps<Theme>;
> ```

We haven't exposed the `sx` prop and theming for other components, so I'm not sure if we want to expose it on the snackbar
___
*[`lib/papi-components/src/snackbar.component.tsx` line 37 at r1](https://reviewable.io/reviews/paranext/paranext-core/249#-NYJOq9q5jzURBby8xV2:-NYJOq9q5jzURBby8xV3:b-trjqs6) ([raw file](https://github.com/paranext/paranext-core/blob/fa9be20f24c2e0c8a4b639687e6aa91989cadf52/lib/papi-components/src/snackbar.component.tsx#L37)):*
> ```XML
>    * Additional css classes to help with unique styling of the snackbar
>    */
>   className?: string;
> ```

Do we need both `classes` and `className`? Don't they kinda do the same thing?
___
*[`lib/papi-components/src/snackbar.component.tsx` line 44 at r1](https://reviewable.io/reviews/paranext/paranext-core/249#-NYJP9wnE0unRW2wydos:-NYJP9wnE0unRW2wydot:b-xcsep4) ([raw file](https://github.com/paranext/paranext-core/blob/fa9be20f24c2e0c8a4b639687e6aa91989cadf52/lib/papi-components/src/snackbar.component.tsx#L44)):*
> ```XML
>    * If true, the component is shown
>    */
>   open?: boolean;
> ```

This prop should be named `isOpen`, as per our Code style guide: https://github.com/paranext/paranext/wiki/Code-Style-Guide
One of the rules reads: `Booleans: use status words like didFinish, isInitialized, or hasPolicy`

Also, a default value for this prop is provided in the component, but there's no `@default` comment here
___
*[`lib/papi-components/src/snackbar.component.tsx` line 48 at r1](https://reviewable.io/reviews/paranext/paranext-core/249#-NYJRqTH1kUcD2RLjWNg:-NYJRqTH1kUcD2RLjWNh:bkl5u58) ([raw file](https://github.com/paranext/paranext-core/blob/fa9be20f24c2e0c8a4b639687e6aa91989cadf52/lib/papi-components/src/snackbar.component.tsx#L48)):*
> ```XML
>   /**
>    * The number of milliseconds to wait before automatically calling onClose()
>    * @default null
> ```

here it says `null`, but in the component it says `6000`
___
*[`lib/papi-components/src/snackbar.component.tsx` line 55 at r1](https://reviewable.io/reviews/paranext/paranext-core/249#-NYJQ84l2AvlHq7oGnqu:-NYJQ84l2AvlHq7oGnqv:b-jtd11) ([raw file](https://github.com/paranext/paranext-core/blob/fa9be20f24c2e0c8a4b639687e6aa91989cadf52/lib/papi-components/src/snackbar.component.tsx#L55)):*
> ```XML
>    * Additional css classes to help with unique styling of the snackbar
>    */
>   className?: string;
> ```

Does this help with styling the bar? So shape/color stuff? And can the theming props in `SnackbarContentProps` only be used to style text etc inside the bar?
___
*[`src/stories/snackbar.stories.tsx` line 4 at r1](https://reviewable.io/reviews/paranext/paranext-core/249#-NYJSWOVBHQCLb1bwkID:-NYJSWOVBHQCLb1bwkIE:b-jvkrxt) ([raw file](https://github.com/paranext/paranext-core/blob/fa9be20f24c2e0c8a4b639687e6aa91989cadf52/src/stories/snackbar.stories.tsx#L4)):*
> ```XML
> import { Snackbar, Button } from 'papi-components';
> 
> //
> ```

Two stray `/` here
___
*[`src/stories/snackbar.stories.tsx` line 17 at r1](https://reviewable.io/reviews/paranext/paranext-core/249#-NYJSu9D8-Nv4EK8MEse:-NYJSu9D8-Nv4EK8MEsf:b-66ez2j) ([raw file](https://github.com/paranext/paranext-core/blob/fa9be20f24c2e0c8a4b639687e6aa91989cadf52/src/stories/snackbar.stories.tsx#L17)):*
> ```XML
>     className: { control: 'text' },
>     /*
>      * adding actions to onClose: timeout, clickaway, or escapekeydown
> ```

I don't see any activity in my console when trying to close the snackbars. Can you explain some more?
___
*[`src/stories/snackbar.stories.tsx` line 20 at r1](https://reviewable.io/reviews/paranext/paranext-core/249#-NYJT0Ml6KaX0MMfwJe7:-NYJT0Ml6KaX0MMfwJe8:b5nmvtf) ([raw file](https://github.com/paranext/paranext-core/blob/fa9be20f24c2e0c8a4b639687e6aa91989cadf52/src/stories/snackbar.stories.tsx#L20)):*
> ```XML
>      * they show up in actions console when they are called
>      */
>     onClose: { action: 'onClose' },
> ```

I'm not very familiar with Storybook yet, but I don't think this works.
Here in the `argTypes` section you can assign controls to your components. Most common are the `boolean`, `text` and ` number` controls.
Since onClose is a callback function it can't be controlled by any of those.
I haven't been able to find a `control` type that can handle functions.
Also I'm not aware that there is an `action` keyword available. 
Can you explain more about what you're doing here?
___
*[`src/stories/snackbar.stories.tsx` line 35 at r1](https://reviewable.io/reviews/paranext/paranext-core/249#-NYJThmW5IKy6n374SpW:-NYJThmXBgykHQCsf-pq:b7orp7g) ([raw file](https://github.com/paranext/paranext-core/blob/fa9be20f24c2e0c8a4b639687e6aa91989cadf52/src/stories/snackbar.stories.tsx#L35)):*
> ```XML
>       classes: { root: 'papi-snackbar primary' }, // styles the root element
>     },
>     // className: 'primary', // styles the div surrounding snackbar
> ```

Why is this commented out?
___
*[`src/stories/snackbar.stories.tsx` line 45 at r1](https://reviewable.io/reviews/paranext/paranext-core/249#-NYJU2294FXdNkBDKqAj:-NYJU2294FXdNkBDKqAk:bjwrf4n) ([raw file](https://github.com/paranext/paranext-core/blob/fa9be20f24c2e0c8a4b639687e6aa91989cadf52/src/stories/snackbar.stories.tsx#L45)):*
> ```XML
>           'This is the primary snackbar story. ' +
>           'You can see the snackbar appear with a basic message and color scheme. ' +
>           'If you open the actions console, you will see the snackbar calls onClose ' +
> ```

I'm not seeing the behavior you describe here. Also `onClose` isn't implemented here, so I don't see how it could produce the behavior you describe. Am I missing something?

**Review by rolfheij-sil — COMMENTED** [review]
Also a more general question: In the main Storybook view for the Snackbar (the view that shows an overview of all stories for the Snackbar), the entire stack of snackbars is rendered in the bottom-left corner of the window. Is it possible to have each snackbar show up in it's own little render box?

> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/249#-:-NYJVAM74xw0VJTd9PBa:bmvxfxc)* status: all files reviewed, 12 unresolved discussions (waiting on @jolierabideau)

**Review by jolierabideau — COMMENTED** [review]
Thank you for your review! As far as your general question, I am not sure I entirely understand. Are you asking if it is possible to have the snackbars appear fully in the windows shown, instead of only the corner? I attached a photo of what I see in the main Storybook view for the Snackbar.




> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/249#-:-NYJgLD94jO2ZYQFJ8Sz:b-6gioqu)* status: 4 of 6 files reviewed, 12 unresolved discussions (waiting on @rolfheij-sil)

___
*[`lib/papi-components/src/snackbar.component.tsx` line 6 at r1](https://reviewable.io/reviews/paranext/paranext-core/249#-NYJQub_BMvocv0V7Uab:-NYK86ZW1jlltwy9zFzU:b-896fix) ([raw file](https://github.com/paranext/paranext-core/blob/fa9be20f24c2e0c8a4b639687e6aa91989cadf52/lib/papi-components/src/snackbar.component.tsx#L6)):*
<details><summary><i>Previously, rolfheij-sil wrote…</i></summary><blockquote>

It might be better to just copy the close reasons provided by MUI.
`export type CloseReason = SnackbarCloseReason`
You'd have to import `SnackbarCloseReason` for that to work obviously.
</blockquote></details>

Done.
___
*[`lib/papi-components/src/snackbar.component.tsx` line 8 at r1](https://reviewable.io/reviews/paranext/paranext-core/249#-NYJRFnG4cNObW7Xbe2A:-NYK86pq1-IJIeJQRefH:b-896fix) ([raw file](https://github.com/paranext/paranext-core/blob/fa9be20f24c2e0c8a4b639687e6aa91989cadf52/lib/papi-components/src/snackbar.component.tsx#L8)):*
<details><summary><i>Previously, rolfheij-sil wrote…</i></summary><blockquote>

Here you could copy `SnackbarOrigin` from MUI
</blockquote></details>

Done.
___
*[`lib/papi-components/src/snackbar.component.tsx` line 32 at r1](https://reviewable.io/reviews/paranext/paranext-core/249#-NYJGkYU5QuaXgGOzrjA:-NYK881ZD_TV4gX8KZ8U:b-d5e6tj) ([raw file](https://github.com/paranext/paranext-core/blob/fa9be20f24c2e0c8a4b639687e6aa91989cadf52/lib/papi-components/src/snackbar.component.tsx#L32)):*
<details><summary><i>Previously, rolfheij-sil wrote…</i></summary><blockquote>

We haven't exposed the `sx` prop and theming for other components, so I'm not sure if we want to expose it on the snackbar
</blockquote></details>

Okay, I wasn't entirely sure about that one. I removed it. 
___
*[`lib/papi-components/src/snackbar.component.tsx` line 37 at r1](https://reviewable.io/reviews/paranext/paranext-core/249#-NYJOq9q5jzURBby8xV2:-NYK8pT9BV2Gyy_641mU:b-3pujws) ([raw file](https://github.com/paranext/paranext-core/blob/fa9be20f24c2e0c8a4b639687e6aa91989cadf52/lib/papi-components/src/snackbar.component.tsx#L37)):*
<details><summary><i>Previously, rolfheij-sil wrote…</i></summary><blockquote>

Do we need both `classes` and `className`? Don't they kinda do the same thing?
</blockquote></details>

I did some more research, and yes I think they do basically the same thing. It looks like the classes attribute might give you more access to style child elements, but I think `className` will give what we are looking for. I removed the `classes` attribute.
___
*[`lib/papi-components/src/snackbar.component.tsx` line 44 at r1](https://reviewable.io/reviews/paranext/paranext-core/249#-NYJP9wnE0unRW2wydos:-NYKHWNm-_O1618HwsU6:b-896fix) ([raw file](https://github.com/paranext/paranext-core/blob/fa9be20f24c2e0c8a4b639687e6aa91989cadf52/lib/papi-components/src/snackbar.component.tsx#L44)):*
<details><summary><i>Previously, rolfheij-sil wrote…</i></summary><blockquote>

This prop should be named `isOpen`, as per our Code style guide: https://github.com/paranext/paranext/wiki/Code-Style-Guide
One of the rules reads: `Booleans: use status words like didFinish, isInitialized, or hasPolicy`

Also, a default value for this prop is provided in the component, but there's no `@default` comment here
</blockquote></details>

Done.
___
*[`lib/papi-components/src/snackbar.component.tsx` line 48 at r1](https://reviewable.io/reviews/paranext/paranext-core/249#-NYJRqTH1kUcD2RLjWNg:-NYKHcsV4plNhw0qahXK:b-9dnwtr) ([raw file](https://github.com/paranext/paranext-core/blob/fa9be20f24c2e0c8a4b639687e6aa91989cadf52/lib/papi-components/src/snackbar.component.tsx#L48)):*
<details><summary><i>Previously, rolfheij-sil wrote…</i></summary><blockquote>

here it says `null`, but in the component it says `6000`
</blockquote></details>

From what I saw, the API says that the default value is `null`, but it is recommended that if `autoHideDuration` is enabled you give users enough time, and so they use `6000` milliseconds as the default for number.


___
*[`lib/papi-components/src/snackbar.component.tsx` line 55 at r1](https://reviewable.io/reviews/paranext/paranext-core/249#-NYJQ84l2AvlHq7oGnqu:-NYK6D9fAMtXDxPgUorX:b-f7z9ov) ([raw file](https://github.com/paranext/paranext-core/blob/fa9be20f24c2e0c8a4b639687e6aa91989cadf52/lib/papi-components/src/snackbar.component.tsx#L55)):*
<details><summary><i>Previously, rolfheij-sil wrote…</i></summary><blockquote>

Does this help with styling the bar? So shape/color stuff? And can the theming props in `SnackbarContentProps` only be used to style text etc inside the bar?
</blockquote></details>

The `SnackbarProps className` applies style to the `<div>` surrounding the snackbar. The `SnackbarContentProps className` applies style to the bar itself. 
___
*[`src/stories/snackbar.stories.tsx` line 4 at r1](https://reviewable.io/reviews/paranext/paranext-core/249#-NYJSWOVBHQCLb1bwkID:-NYK6S1jDb9S3ngw6wDG:b-896fix) ([raw file](https://github.com/paranext/paranext-core/blob/fa9be20f24c2e0c8a4b639687e6aa91989cadf52/src/stories/snackbar.stories.tsx#L4)):*
<details><summary><i>Previously, rolfheij-sil wrote…</i></summary><blockquote>

Two stray `/` here
</blockquote></details>

Done.
___
*[`src/stories/snackbar.stories.tsx` line 17 at r1](https://reviewable.io/reviews/paranext/paranext-core/249#-NYJSu9D8-Nv4EK8MEse:-NYKUQjG2C4E8j4kdBhW:b-8w03pg) ([raw file](https://github.com/paranext/paranext-core/blob/fa9be20f24c2e0c8a4b639687e6aa91989cadf52/src/stories/snackbar.stories.tsx#L17)):*
<details><summary><i>Previously, rolfheij-sil wrote…</i></summary><blockquote>

I don't see any activity in my console when trying to close the snackbars. Can you explain some more?
</blockquote></details>

I'm not sure if you were looking here- but it is not the Javascript console, it is within Storybook itself. If you click the settings icon and have it "Show addons", then you should see a tab for actions. Then, if you hit the escape key, wait for timeout, or click the screen you will see the `onClose` action. The `clickaway` refers to a click outside of the component, that is why it doesn't work if you click the component itself. I attached a photo showing what I see. 



___
*[`src/stories/snackbar.stories.tsx` line 20 at r1](https://reviewable.io/reviews/paranext/paranext-core/249#-NYJT0Ml6KaX0MMfwJe7:-NYKW-xU3EwV7ZWQX9fQ:b-asavdf) ([raw file](https://github.com/paranext/paranext-core/blob/fa9be20f24c2e0c8a4b639687e6aa91989cadf52/src/stories/snackbar.stories.tsx#L20)):*
<details><summary><i>Previously, rolfheij-sil wrote…</i></summary><blockquote>

I'm not very familiar with Storybook yet, but I don't think this works.
Here in the `argTypes` section you can assign controls to your components. Most common are the `boolean`, `text` and ` number` controls.
Since onClose is a callback function it can't be controlled by any of those.
I haven't been able to find a `control` type that can handle functions.
Also I'm not aware that there is an `action` keyword available. 
Can you explain more about what you're doing here?
</blockquote></details>

This is one of the sites I used when I was looking into actions: https://storybook.js.org/docs/react/essentials/actions. 

I have not found a control type that handles functions either. The `action` keyword here is telling Storybook that this argument is not something that can be controlled with the values you listed, but it is an action. Then I believe it creates the argument as a callback so that it can be called, and when it is called it will show up in the Actions console that I included in a photo in the previous comment. 
___
*[`src/stories/snackbar.stories.tsx` line 35 at r1](https://reviewable.io/reviews/paranext/paranext-core/249#-NYJThmW5IKy6n374SpW:-NYK6e3EEqXxentbk0pY:b5m57ht) ([raw file](https://github.com/paranext/paranext-core/blob/fa9be20f24c2e0c8a4b639687e6aa91989cadf52/src/stories/snackbar.stories.tsx#L35)):*
<details><summary><i>Previously, rolfheij-sil wrote…</i></summary><blockquote>

Why is this commented out?
</blockquote></details>

The `className` prop that is a part of the general `SnackbarProps` (and not a part of the `ContentProps`) applies to the `<div>` element surrounding the snackbar, not the bar itself. I did not have any style classes focused on the `<div>`, but left it to demonstrate the difference between styling the `<div>` and the bar itself.
___
*[`src/stories/snackbar.stories.tsx` line 45 at r1](https://reviewable.io/reviews/paranext/paranext-core/249#-NYJU2294FXdNkBDKqAj:-NYKX4217U19kM6FrBHB:bpkj6kk) ([raw file](https://github.com/paranext/paranext-core/blob/fa9be20f24c2e0c8a4b639687e6aa91989cadf52/src/stories/snackbar.stories.tsx#L45)):*
<details><summary><i>Previously, rolfheij-sil wrote…</i></summary><blockquote>

I'm not seeing the behavior you describe here. Also `onClose` isn't implemented here, so I don't see how it could produce the behavior you describe. Am I missing something?
</blockquote></details>

You are right the `onClose` is not implemented here, but by telling Storybook that it is an `action` it can pretend that it is closing by showing us in the Actions console that a callback was fired. The snackbar itself will not actually close in Storybook. I believe it is just a way to showcase what kinds of things would call the `onClose` and when. I hope my comments/screen shots helped a little, if not I would love to share my screen and talk through some of this with you. If it would be better for me to remove the `action` until we all have a better understanding of it, I can do that as well.

**Review by rolfheij-sil — CHANGES_REQUESTED** [review]
Interesting! This is what it looks like on my end
Chrome Version 114.0.5735.134 on Windows 11.
You're on Safari/MacOS, right?



> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/249#-:-NYN-txQ5sIV8n64b3W6:b-8ikehc)* status: all files reviewed, 6 unresolved discussions (waiting on @jolierabideau)

___
*[`lib/papi-components/src/snackbar.component.tsx` line 48 at r1](https://reviewable.io/reviews/paranext/paranext-core/249#-NYJRqTH1kUcD2RLjWNg:-NYN4U4u1OM23ZX26o2A:b-jodxgo) ([raw file](https://github.com/paranext/paranext-core/blob/fa9be20f24c2e0c8a4b639687e6aa91989cadf52/lib/papi-components/src/snackbar.component.tsx#L48)):*
<details><summary><i>Previously, jolierabideau wrote…</i></summary><blockquote>

From what I saw, the API says that the default value is `null`, but it is recommended that if `autoHideDuration` is enabled you give users enough time, and so they use `6000` milliseconds as the default for number.



</blockquote></details>

Ah yes, I get the confusion. The default value specified by MUI is `null`, but on line 85 of this file you've overridden that default to be `6000`
___
*[`lib/papi-components/src/snackbar.component.tsx` line 55 at r1](https://reviewable.io/reviews/paranext/paranext-core/249#-NYJQ84l2AvlHq7oGnqu:-NYN4eyBBFKvyNxtBFwf:b-rqbgt3) ([raw file](https://github.com/paranext/paranext-core/blob/fa9be20f24c2e0c8a4b639687e6aa91989cadf52/lib/papi-components/src/snackbar.component.tsx#L55)):*
<details><summary><i>Previously, jolierabideau wrote…</i></summary><blockquote>

The `SnackbarProps className` applies style to the `<div>` surrounding the snackbar. The `SnackbarContentProps className` applies style to the bar itself. 
</blockquote></details>

Thanks for clarifying
___
*[`src/stories/snackbar.stories.tsx` line 17 at r1](https://reviewable.io/reviews/paranext/paranext-core/249#-NYJSu9D8-Nv4EK8MEse:-NYN5Qk52JYbIpHxKLWv:b-n1onom) ([raw file](https://github.com/paranext/paranext-core/blob/fa9be20f24c2e0c8a4b639687e6aa91989cadf52/src/stories/snackbar.stories.tsx#L17)):*
<details><summary><i>Previously, jolierabideau wrote…</i></summary><blockquote>

I'm not sure if you were looking here- but it is not the Javascript console, it is within Storybook itself. If you click the settings icon and have it "Show addons", then you should see a tab for actions. Then, if you hit the escape key, wait for timeout, or click the screen you will see the `onClose` action. The `clickaway` refers to a click outside of the component, that is why it doesn't work if you click the component itself. I attached a photo showing what I see. 




</blockquote></details>

Interesting. It's not showing anything on my end. Let's have a look at it later today
___
*[`src/stories/snackbar.stories.tsx` line 20 at r1](https://reviewable.io/reviews/paranext/paranext-core/249#-NYJT0Ml6KaX0MMfwJe7:-NYN5sGI126g8q_kU3hR:bmtoqwq) ([raw file](https://github.com/paranext/paranext-core/blob/fa9be20f24c2e0c8a4b639687e6aa91989cadf52/src/stories/snackbar.stories.tsx#L20)):*
<details><summary><i>Previously, jolierabideau wrote…</i></summary><blockquote>

This is one of the sites I used when I was looking into actions: https://storybook.js.org/docs/react/essentials/actions. 

I have not found a control type that handles functions either. The `action` keyword here is telling Storybook that this argument is not something that can be controlled with the values you listed, but it is an action. Then I believe it creates the argument as a callback so that it can be called, and when it is called it will show up in the Actions console that I included in a photo in the previous comment. 
</blockquote></details>

Cool! Seems like a really nice feature.
___
*[`src/stories/snackbar.stories.tsx` line 35 at r1](https://reviewable.io/reviews/paranext/paranext-core/249#-NYJThmW5IKy6n374SpW:-NYN67vC68vQoWPRJicM:b-nco2rx) ([raw file](https://github.com/paranext/paranext-core/blob/fa9be20f24c2e0c8a4b639687e6aa91989cadf52/src/stories/snackbar.stories.tsx#L35)):*
<details><summary><i>Previously, jolierabideau wrote…</i></summary><blockquote>

The `className` prop that is a part of the general `SnackbarProps` (and not a part of the `ContentProps`) applies to the `<div>` element surrounding the snackbar, not the bar itself. I did not have any style classes focused on the `<div>`, but left it to demonstrate the difference between styling the `<div>` and the bar itself.
</blockquote></details>

Ah, that makes sense. Perhaps a good idea to add some styling to the `<div>` too? Seems like a useful thing to show here
___
*[`src/stories/snackbar.stories.tsx` line 45 at r1](https://reviewable.io/reviews/paranext/paranext-core/249#-NYJU2294FXdNkBDKqAj:-NYN6SFJ59e0G-mAs-xi:b-tnh1i6) ([raw file](https://github.com/paranext/paranext-core/blob/fa9be20f24c2e0c8a4b639687e6aa91989cadf52/src/stories/snackbar.stories.tsx#L45)):*
<details><summary><i>Previously, jolierabideau wrote…</i></summary><blockquote>

You are right the `onClose` is not implemented here, but by telling Storybook that it is an `action` it can pretend that it is closing by showing us in the Actions console that a callback was fired. The snackbar itself will not actually close in Storybook. I believe it is just a way to showcase what kinds of things would call the `onClose` and when. I hope my comments/screen shots helped a little, if not I would love to share my screen and talk through some of this with you. If it would be better for me to remove the `action` until we all have a better understanding of it, I can do that as well. 
</blockquote></details>

Yep, let's talk this through! Seems like you did a great job, and that there might be some cross-platform weirdness going on

**Review by rolfheij-sil — CHANGES_REQUESTED** [review]
As we saw during our meeting yesterday, it works correctly in Firefox on Windows 11. Not sure why Chrome is handling things differently, but probably not worth spending time to figure that out right now

> Reviewed 9 of 9 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/249#-:-NYSAFUF4FB4ON-Fj-nb:b-har7f2)* status: all files reviewed, 1 unresolved discussion (waiting on @jolierabideau)

___
*[`src/stories/snackbar.stories.tsx` line 51 at r3](https://reviewable.io/reviews/paranext/paranext-core/249#-NYSBVL62XWN_HgbJUT-:-NYSBVL62XWN_HgbJUT0:b2tjau0) ([raw file](https://github.com/paranext/paranext-core/blob/ebee14c0708cb4ea8e345c89b1a62b8e86ff4f03/src/stories/snackbar.stories.tsx#L51)):*
> ```XML
>     ContentProps: {
>       message: 'This snackbar will timeout',
>       action: '',
> ```

What does it mean to define the action as `''` here?

**Review by jolierabideau — COMMENTED** [review]
@rolfheij-sil I am still working on connecting the papi Button to the Snackbar, like we talked about yesterday. So if we want to wait to do anything with the PR until those changes are added, I can hopefully finish that today.

> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/249#-:-NYSrPPp3YX1v0hwSY1f:bptp84f)* status: all files reviewed, 1 unresolved discussion (waiting on @rolfheij-sil)

___
*[`src/stories/snackbar.stories.tsx` line 51 at r3](https://reviewable.io/reviews/paranext/paranext-core/249#-NYSBVL62XWN_HgbJUT-:-NYSqtFj6LBiZKJkEGDP:b-6uj2ox) ([raw file](https://github.com/paranext/paranext-core/blob/ebee14c0708cb4ea8e345c89b1a62b8e86ff4f03/src/stories/snackbar.stories.tsx#L51)):*
<details><summary><i>Previously, rolfheij-sil wrote…</i></summary><blockquote>

What does it mean to define the action as `''` here?
</blockquote></details>

This is a mistake on my part, I meant to remove this line. This `action` refers to the action attribute in `SnackbarContentProps`, not the action addon for Storybook. Defining it like this just means it is empty, but I am removing the line. Sorry about that, thank you!

**Review by rolfheij-sil — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/249#-:-NYT4FAT64brBGZyff5b:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @jolierabideau)

**Pull request merged**
