### PR TITLE
Streamlined a number of npm scripts

### PR DESCRIPTION
**Pull request by tjcouch-sil**
- Made `npm install` also install dependencies in `extensions`
- `build:types` no longer builds extensions
- Added some helper scripts in `extensions`

- - -
This change is [Reviewable](https://reviewable.io/reviews/paranext/paranext-core/164)

### CODE REVIEW

**Review by lyonsil — CHANGES_REQUESTED** [review]
> Reviewed 7 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/164)* status: all files reviewed, 1 unresolved discussion (waiting on @tjcouch-sil)

___
*[`README.md` line 60 at r1](https://reviewable.io/reviews/paranext/paranext-core/164#-NU93rYC40Nhycy0CSab:-NU93rYC40Nhycy0CSac:bqse1y7) ([raw file](https://github.com/paranext/paranext-core/blob/664428456eb8e124f5e55c9588fdd4b012afa817/README.md#L60)):*
> ```Markdown
> ```
> 
> To build extensions including the declaration type files for the core extensions, run the following:
> ```

Would it be easier/cleaner to just tell people to run `npm run build` which handles extensions, types, and other things?

**Review by katherinejensen00 — DISMISSED** [review]
:lgtm:

> Reviewed 7 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/164#-:-NU97xul2JphgbBamQdO:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @tjcouch-sil)

**Review by tjcouch-sil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/164)* status: 6 of 7 files reviewed, 1 unresolved discussion (waiting on @katherinejensen00 and @lyonsil)

___
*[`README.md` line 60 at r1](https://reviewable.io/reviews/paranext/paranext-core/164#-NU93rYC40Nhycy0CSab:-NUMUjH35TQZ90f9OS8t:b-3t8iiz) ([raw file](https://github.com/paranext/paranext-core/blob/664428456eb8e124f5e55c9588fdd4b012afa817/README.md#L60)):*
<details><summary><i>Previously, lyonsil wrote…</i></summary><blockquote>

Would it be easier/cleaner to just tell people to run `npm run build` which handles extensions, types, and other things?
</blockquote></details>

Unfortunately it seems `npm run build` needs some kind of environmental setup (this script was given to us by the boilerplate we used), so it doesn't run alone. It runs properly under `npm run package`, though. So I believe we need to leave these here.

**Review by lyonsil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/164)* status: 6 of 7 files reviewed, all discussions resolved (waiting on @katherinejensen00)

___
*[`README.md` line 60 at r1](https://reviewable.io/reviews/paranext/paranext-core/164#-NU93rYC40Nhycy0CSab:-NUMZlml6jscZRdAwGNu:b-l2roqm) ([raw file](https://github.com/paranext/paranext-core/blob/664428456eb8e124f5e55c9588fdd4b012afa817/README.md#L60)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

Unfortunately it seems `npm run build` needs some kind of environmental setup (this script was given to us by the boilerplate we used), so it doesn't run alone. It runs properly under `npm run package`, though. So I believe we need to leave these here.
</blockquote></details>

ok, good to know

**Review by lyonsil — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/164#-:-NUM_CWeD2pVLdV7d0Ml:bnfp4nl)* status: 6 of 7 files reviewed, all discussions resolved (waiting on @katherinejensen00)

**Review by katherinejensen00 — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/164#-:-NUMgMw59AB44ZPfZ2UA:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @tjcouch-sil)

**Pull request merged**
