### PR TITLE
Added some more C# tests (mainly for the PSI)

### PR DESCRIPTION
**Pull request by FoolRunning**
This change is [Reviewable](https://reviewable.io/reviews/paranext/paranext-core/654)

### CODE REVIEW

**Comment by FoolRunning** [comment]
Whoops. I guess I got distracted and pushed some failing tests.

**Review by tjcouch-sil — APPROVED** [review]
Just one discussion point, but this looks great! Thanks for the hard work on it.

> Reviewed 20 of 20 files at r1, 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/654#-:-NkLUjOf3aWRtq-SCv1H:b3mptdz)* status: all files reviewed, 1 unresolved discussion (waiting on @FoolRunning)

___
*[`c-sharp/Projects/LocalProjects.cs` line 79 at r1](https://reviewable.io/reviews/paranext/paranext-core/654#-NkLSYbO0beasS-PAqcg:-NkLSYbO0beasS-PAqch:bav0s01) ([raw file](https://github.com/paranext/paranext-core/blob/e14fc2198149df258895b8d920e823be4e2d2a49/c-sharp/Projects/LocalProjects.cs#L79)):*
> ```Smalltalk
>     public ProjectDetails? GetProjectDetails(string projectId)
>     {
>         _projectDetailsMap.TryGetValue(projectId.ToUpperInvariant(), out var details);
> ```

I wonder if @lyonsil particularly desires to throw on this and the following method. I haven't really thought through the consequences much, but I do see that it also throws in `project-lookup.service-host.ts`. Maybe the preference is to return something if it exists or to fail fast and throw otherwise? I can appreciate such a perspective. Fewer nulls seems nice. However, catching exceptions is more computationally expensive than null checking. Any thoughts on why you changed it, Tim?
___
*[`c-sharp/Projects/ParatextProjectStorageInterpreter.cs` line 345 at r2](https://reviewable.io/reviews/paranext/paranext-core/654#-NkLTYgQ51CNMnmid3f2:-NkLTYgQ51CNMnmid3f3:bkgq82r) ([raw file](https://github.com/paranext/paranext-core/blob/d59dc89869f9e8fac4503a43f50c863619340241/c-sharp/Projects/ParatextProjectStorageInterpreter.cs#L345)):*
> ```Smalltalk
>         ScrStylesheet scrStylesheet = scrText.ScrStylesheet(bookNum);
>         // Tokenize usfm
>         List<UsfmToken> tokens = UsfmToken.Tokenize(scrStylesheet, usfm ?? string.Empty, false);
> ```

Thanks for finding this!

**Review by tjcouch-sil — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/654)* status: all files reviewed, 1 unresolved discussion (waiting on @lyonsil)

___
*[`c-sharp/Projects/LocalProjects.cs` line 79 at r1](https://reviewable.io/reviews/paranext/paranext-core/654#-NkLSYbO0beasS-PAqcg:-NkLpVuf1sCp-uMB4LmV:bgw6mil) ([raw file](https://github.com/paranext/paranext-core/blob/e14fc2198149df258895b8d920e823be4e2d2a49/c-sharp/Projects/LocalProjects.cs#L79)):*
<details><summary><i>Previously, FoolRunning (Tim Steenwyk) wrote…</i></summary><blockquote>

Probably a general philosophy different - I tend to avoid exceptions as much as possible because they are inefficient. Also, since we're using the nullable-notation in our C#, it makes it obvious that the result can be null so it seems easier to just do it that way.
</blockquote></details>

That's the way I have historically leaned, but I can appreciate that it's nice to know your value definitely isn't null (as long as everyone plays by the rules of the write-time type checking hints). Hard to say my opinion either direction to be honest. I think it would be good to be consistent between the C# and the TS either way. Could we hear from Matt and then have one place or the other changed to match each other?

**Review by tjcouch-sil — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/654)* status: all files reviewed, 1 unresolved discussion (waiting on @lyonsil)

**Review by lyonsil — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/654)* status: all files reviewed, 3 unresolved discussions (waiting on @FoolRunning and @tjcouch-sil)

___
*[`c-sharp/Projects/LocalProjects.cs` line 79 at r1](https://reviewable.io/reviews/paranext/paranext-core/654#-NkLSYbO0beasS-PAqcg:-NkMCcp5ApJclR_8sLZ2:b-sp5lni) ([raw file](https://github.com/paranext/paranext-core/blob/e14fc2198149df258895b8d920e823be4e2d2a49/c-sharp/Projects/LocalProjects.cs#L79)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

That's the way I have historically leaned, but I can appreciate that it's nice to know your value definitely isn't null (as long as everyone plays by the rules of the write-time type checking hints). Hard to say my opinion either direction to be honest. I think it would be good to be consistent between the C# and the TS either way. Could we hear from Matt and then have one place or the other changed to match each other?
</blockquote></details>

I am expecting this to throw if it fails and put try/catch at appropriate places.  I would prefer if we kept things as they were so we don't have to put so many null checks in various places.  Also, try/catch is nice because if in the future something changes that could cause an exception to throw that doesn't now, we'd still catch the problem.  When exceptions get all the way back up to the message handling layer, the err

From a performance perspective, I've already seen the .NET data provider handle over 1000 requests per second.  The performance isn't really that terrible for what we're doing.
___
*[`c-sharp/Projects/LocalProjects.cs` line 86 at r2](https://reviewable.io/reviews/paranext/paranext-core/654#-NkMDJ2D4cCbwvJxiKs6:-NkMDJ2D4cCbwvJxiKs7:bjakwv9) ([raw file](https://github.com/paranext/paranext-core/blob/d59dc89869f9e8fac4503a43f50c863619340241/c-sharp/Projects/LocalProjects.cs#L86)):*
> ```Smalltalk
>     {
>         HexId? id = HexId.FromStrSafe(projectId);
>         return id != null ? ScrTextCollection.FindById(id) : null;
> ```

Same as above, I would prefer if we kept things as they were.
___
*[`c-sharp/Projects/ParatextProjectDataProviderFactory.cs` line 49 at r2](https://reviewable.io/reviews/paranext/paranext-core/654#-NkMDAMb7kWSND5TMzTj:-NkMDAMb7kWSND5TMzTk:boxv4mx) ([raw file](https://github.com/paranext/paranext-core/blob/d59dc89869f9e8fac4503a43f50c863619340241/c-sharp/Projects/ParatextProjectDataProviderFactory.cs#L49)):*
> ```Smalltalk
> 
>             ProjectDetails? details = _projects.GetProjectDetails(projectID);
>             if (details == null)
> ```

I would prefer if we kept all the try/catch clauses as they were and not add `null` checks.

**Review by lyonsil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/654)* status: all files reviewed, 3 unresolved discussions (waiting on @FoolRunning and @tjcouch-sil)

___
*[`c-sharp/Projects/LocalProjects.cs` line 79 at r1](https://reviewable.io/reviews/paranext/paranext-core/654#-NkLSYbO0beasS-PAqcg:-NkMF69i3tyEUYJV2Ryv:b-akdki3) ([raw file](https://github.com/paranext/paranext-core/blob/e14fc2198149df258895b8d920e823be4e2d2a49/c-sharp/Projects/LocalProjects.cs#L79)):*
<details><summary><i>Previously, lyonsil (Matt Lyons) wrote…</i></summary><blockquote>

I am expecting this to throw if it fails and put try/catch at appropriate places.  I would prefer if we kept things as they were so we don't have to put so many null checks in various places.  Also, try/catch is nice because if in the future something changes that could cause an exception to throw that doesn't now, we'd still catch the problem.  When exceptions get all the way back up to the message handling layer, the err

From a performance perspective, I've already seen the .NET data provider handle over 1000 requests per second.  The performance isn't really that terrible for what we're doing.
</blockquote></details>

Not sure what happened to my previous comment.  What I was saying is: "When exceptions get all the way back up to the message handling layer, the errors are hard to understand.  You often have to debug and get the raw messages to figure it out."

**Review by FoolRunning — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/654)* status: all files reviewed, 3 unresolved discussions (waiting on @lyonsil and @tjcouch-sil)

___
*[`c-sharp/Projects/LocalProjects.cs` line 79 at r1](https://reviewable.io/reviews/paranext/paranext-core/654#-NkLSYbO0beasS-PAqcg:-NkMNxHR2nfcjh_m3Ip0:b-l2x30s) ([raw file](https://github.com/paranext/paranext-core/blob/e14fc2198149df258895b8d920e823be4e2d2a49/c-sharp/Projects/LocalProjects.cs#L79)):*
<details><summary><i>Previously, lyonsil (Matt Lyons) wrote…</i></summary><blockquote>

Not sure what happened to my previous comment.  What I was saying is: "When exceptions get all the way back up to the message handling layer, the errors are hard to understand.  You often have to debug and get the raw messages to figure it out."
</blockquote></details>

I find it a little contradictory to say that when exceptions occur they are hard to debug and so we should throw exceptions in these possibly common cases. I would think it would be better to make it obvious how certain cases are handled via returning a nullable. However, I don't feel so strongly that I feel like fighting it, so I'll just change things back the way they were.

**Review by FoolRunning — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/654)* status: 18 of 21 files reviewed, 3 unresolved discussions (waiting on @lyonsil and @tjcouch-sil)

___
*[`c-sharp/Projects/LocalProjects.cs` line 79 at r1](https://reviewable.io/reviews/paranext/paranext-core/654#-NkLSYbO0beasS-PAqcg:-NkQXLlEAGa3Ourg_grf:b-umsc9o) ([raw file](https://github.com/paranext/paranext-core/blob/e14fc2198149df258895b8d920e823be4e2d2a49/c-sharp/Projects/LocalProjects.cs#L79)):*
<details><summary><i>Previously, lyonsil (Matt Lyons) wrote…</i></summary><blockquote>

My point wasn't "exceptions are hard to debug."  My point was that if all you have for unexpected errors is a very high level error output message, it doesn't help a lot.  You need something that goes deeper to be useful.  Generally you need fewer try/catch blocks than `if` statements, and you have to be very insightful for your `if` statements to cover all potential cases users might hit, so I prefer the try/catch blocks over `if` statements unless really high performance (e.g., reliable sub millisecond responses) is needed which it isn't here.
</blockquote></details>

I've reverted this back to being exceptions
___
*[`c-sharp/Projects/LocalProjects.cs` line 86 at r2](https://reviewable.io/reviews/paranext/paranext-core/654#-NkMDJ2D4cCbwvJxiKs6:-NkQXXjz17nUvpMuoNN2:b-umsc9o) ([raw file](https://github.com/paranext/paranext-core/blob/d59dc89869f9e8fac4503a43f50c863619340241/c-sharp/Projects/LocalProjects.cs#L86)):*
<details><summary><i>Previously, lyonsil (Matt Lyons) wrote…</i></summary><blockquote>

Same as above, I would prefer if we kept things as they were.
</blockquote></details>

I've reverted this back to being exceptions
___
*[`c-sharp/Projects/ParatextProjectDataProviderFactory.cs` line 49 at r2](https://reviewable.io/reviews/paranext/paranext-core/654#-NkMDAMb7kWSND5TMzTj:-NkQXYihBX3e3cYEa2L4:b-umsc9o) ([raw file](https://github.com/paranext/paranext-core/blob/d59dc89869f9e8fac4503a43f50c863619340241/c-sharp/Projects/ParatextProjectDataProviderFactory.cs#L49)):*
<details><summary><i>Previously, lyonsil (Matt Lyons) wrote…</i></summary><blockquote>

I would prefer if we kept all the try/catch clauses as they were and not add `null` checks.
</blockquote></details>

I've reverted this back to being exceptions

**Review by lyonsil — COMMENTED** [review]
> Reviewed 15 of 20 files at r1, 2 of 4 files at r2, 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/654)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by lyonsil — APPROVED** [review]
> Reviewed 1 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/654)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
