### PR TITLE
Load extensions from ZIP files

### PR DESCRIPTION
**Pull request by lyonsil**
This change is [Reviewable](https://reviewable.io/reviews/paranext/paranext-core/349)

### CODE REVIEW

**Review by lyonsil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/349)* status: all files reviewed, 6 unresolved discussions (waiting on @tjcouch-sil)

___
*[`src/extension-host/services/extension.service.ts` line 120 at r1](https://reviewable.io/reviews/paranext/paranext-core/349#-NbMFbvCAje9ztEmquB7:-NbRIsZJ3VrZJYUz8f8D:bxv6mqd) ([raw file](https://github.com/paranext/paranext-core/blob/70dd73b1d204a6db47af46167b74d619e84b9400/src/extension-host/services/extension.service.ts#L120)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

Do we need this log?
</blockquote></details>

Indeed we do not.  That was my mistake.  It was a debugging line left in my original check-in.  I removed it when I made the update to support the `--extensions` command line argument.
___
*[`src/extension-host/services/extension.service.ts` line 100 at r2](https://reviewable.io/reviews/paranext/paranext-core/349#-NbPsBMo8KpMKm7sR0S1:-NbRIFXyCt2uD7J-myOv:blzypdn) ([raw file](https://github.com/paranext/paranext-core/blob/52366a04d35b172ea15af7b518361a0136846b9c/src/extension-host/services/extension.service.ts#L100)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

As we discussed in Discord, would it make sense to put these files in the 'app://' directory? Maybe something like `app://unzipped-extensions` or something? Or maybe `app://cache/ext` so it's clear these are just transient files. Then I can update the location of `app` and add the new `cache` schema or do whatever we want to do in my follow-up PR? Or I suppose you could change the `app` scheme to `~/.platform.bible` now if you'd like! I dunno... But using a scheme here would be best, I think, if that's ok!
</blockquote></details>

Per our discussion in the team meeting, I'm assuming we will leave this as-is for this PR and address the path question in a future PR.  It should be easy enough to update this behavior since everything is getting the cache root directory from this variable.
___
*[`src/extension-host/services/extension.service.ts` line 176 at r2](https://reviewable.io/reviews/paranext/paranext-core/349#-NbQaxsj99TwuU0tEV_c:-NbRJKx2CdjBXS01KFYD:bdeajur) ([raw file](https://github.com/paranext/paranext-core/blob/52366a04d35b172ea15af7b518361a0136846b9c/src/extension-host/services/extension.service.ts#L176)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

Should we make this a debug log or something?
</blockquote></details>

I thought about this when writing the code, and my line of thinking was "If a user reported a problem and sent us their app logs, what would I want to see in the log?"  This line only is output when a file is being put into the cache from a ZIP file, and that should be pretty rare for regular users.  Normally they would just load data from the cache.  If we see it in the log, that seems like a potentially interesting bit of information to have.

I can lower this to debug if preferred, but given the uniqueness of the situation compared to normal, it seemed better to me as `info`.
___
*[`src/extension-host/services/extension.service.ts` line 187 at r2](https://reviewable.io/reviews/paranext/paranext-core/349#-NbQbxOcE8AdxTaVz18C:-NbRK4QTD-6PnDh5JQJL:bv0q7iu) ([raw file](https://github.com/paranext/paranext-core/blob/52366a04d35b172ea15af7b518361a0136846b9c/src/extension-host/services/extension.service.ts#L187)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

If I'm reading this correctly (definitely could be reading it wrong), I believe this code will run the unzipped version of every extension that has ever been unzipped even if it was deleted from the original extension folder. Do you think we could instead look at what zips are present to determine which cached extensions to load? Otherwise, if you remove an extension, the cached version will still load. Let me know your thoughts. Thanks!
</blockquote></details>

Indeed that is what happens.  What do you mean exactly by "even if it was deleted from the original extension folder"?  Do you mean if the ZIP file isn't present anymore?

I think there is a good argument for not loading even extension present in all cases.  Having said that, I'm not sure that the criteria for making that decision ought to be what ZIP files were present in the command line.  People might not have the original ZIP files anymore, and maybe they wouldn't even want to load some of the bundled extensions if we have a bunch of optional ones there.  I was thinking that eventually the app would have something equivalent to a `package.json` file for extensions.  I don't mean literally that format, but I do mean some kind of config that indicates which extensions they should be loading.  I don't remember if it was you or someone else telling me this (maybe Tim?), but someone mentioned to me that we might have different configs/versions for people depending on what role they have in the translation process.

If you think the command line is the right determination for whether or not to load an extension I can make it so.  I was just thinking that we would load everything now like we have been, and the config-based decision on what we should really load would come later.
___
*[`src/extension-host/services/extension.service.ts` line 206 at r3](https://reviewable.io/reviews/paranext/paranext-core/349#-NbQuvs8ELJJvfrbj-xn:-NbRLJem7fiqn-KzoFUD:b2zi20o) ([raw file](https://github.com/paranext/paranext-core/blob/f9e38f56d6e3a391994ca4cef42db94bdaf21834/src/extension-host/services/extension.service.ts#L206)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

This was a bit hard to understand. Could we mention that this is here to indicate we are ignoring files when looking for extensions since we already unzipped extensions into directories? Or maybe return `Promise.reject(reason)` with an explanation of what went wrong for self documentation? Then we wouldn't need the added `!settled.value` below, I believe.
</blockquote></details>

I didn't want to `Promise.reject` here because someone might have pointed to a ZIP file, and that isn't really an error condition the same way that a missing manifest is since we will be unzipping the files for them.  That is, we shouldn't log an error message if someone pointed to a ZIP file.  I will work on a better comment here.
___
*[`src/node/services/node-file-system.service.ts` line 49 at r2](https://reviewable.io/reviews/paranext/paranext-core/349#-NbQcdvq53SJRmLdQU8X:-NbRM-Gh19s8XH9n32tH:b-iditml) ([raw file](https://github.com/paranext/paranext-core/blob/52366a04d35b172ea15af7b518361a0136846b9c/src/node/services/node-file-system.service.ts#L49)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

Synchronous calls freeze the process. Do you think we could instead add the `force` option in `rm` by default so it doesn't throw if the file doesn't exist? And same below in `rmdir`? Then maybe depending on expected functionality in the other contexts, maybe we could catch file not found exceptions?

Or maybe, unless you see a particular problem with it, we could just use the promise version for now and create an issue to make improvements later since I don't believe this code currently prevents problems with the file not existing (I think you would probably just have to call the operations as I mention above to really prevent these kinds of problems) and it doesn't seem super worth refactoring.
</blockquote></details>

I will find an async replacement for `existsSync`.  There isn't one directly in `fs.promises` which is why I used this, but there are some similar enough APIs I can make work.
___
*[`src/node/services/node-file-system.service.ts` line 127 at r2](https://reviewable.io/reviews/paranext/paranext-core/349#-NbQdK8jDkkz4R3eQj1A:-NbRNwsq47Uqanw3dVbn:b-ej06zb) ([raw file](https://github.com/paranext/paranext-core/blob/52366a04d35b172ea15af7b518361a0136846b9c/src/node/services/node-file-system.service.ts#L127)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

I don't usually remember what `force` does for the system call - could you explain what it does in this comment?
</blockquote></details>

Huh - I assumed this used `force` in the same way that the flag is used for the `rm` command line tool in Linux since the API name (`rm`) and flag have the same names.  [Here's a description of what they do in Linux](https://blog.purestorage.com/purely-technical/when-to-use-the-force-flag-in-linux/), but I guess [in the Node API](https://nodejs.org/api/fs.html#fsrmpath-options-callback) it's different.  It's kind of jenky to name something exactly the same as a very common tool and mean something different, but it is what it is.  I will have to think about this a little more.

**Review by tjcouch-sil — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/349)* status: all files reviewed, 3 unresolved discussions (waiting on @lyonsil)

___
*[`src/extension-host/services/extension.service.ts` line 100 at r2](https://reviewable.io/reviews/paranext/paranext-core/349#-NbPsBMo8KpMKm7sR0S1:-NbUf_I_6zIUYsoyhKeh:b-30yfwl) ([raw file](https://github.com/paranext/paranext-core/blob/52366a04d35b172ea15af7b518361a0136846b9c/src/extension-host/services/extension.service.ts#L100)):*
<details><summary><i>Previously, lyonsil (Matt Lyons) wrote…</i></summary><blockquote>

Per our discussion in the team meeting, I'm assuming we will leave this as-is for this PR and address the path question in a future PR.  It should be easy enough to update this behavior since everything is getting the cache root directory from this variable.
</blockquote></details>

Sounds good :)
___
*[`src/extension-host/services/extension.service.ts` line 176 at r2](https://reviewable.io/reviews/paranext/paranext-core/349#-NbQaxsj99TwuU0tEV_c:-NbUfkiG3s3K6EK_LFiE:b-xrrbxs) ([raw file](https://github.com/paranext/paranext-core/blob/52366a04d35b172ea15af7b518361a0136846b9c/src/extension-host/services/extension.service.ts#L176)):*
<details><summary><i>Previously, lyonsil (Matt Lyons) wrote…</i></summary><blockquote>

I thought about this when writing the code, and my line of thinking was "If a user reported a problem and sent us their app logs, what would I want to see in the log?"  This line only is output when a file is being put into the cache from a ZIP file, and that should be pretty rare for regular users.  Normally they would just load data from the cache.  If we see it in the log, that seems like a potentially interesting bit of information to have.

I can lower this to debug if preferred, but given the uniqueness of the situation compared to normal, it seemed better to me as `info`.
</blockquote></details>

Good point; it would work just fine either way. But `info` is not logged in production by default, I think. We could definitely change that, but I think it is `warn` by default (I think it just started that way with `electron-log`).
___
*[`src/extension-host/services/extension.service.ts` line 187 at r2](https://reviewable.io/reviews/paranext/paranext-core/349#-NbQbxOcE8AdxTaVz18C:-NbUgH_W9Issw-LPqzE5:bqv0q0y) ([raw file](https://github.com/paranext/paranext-core/blob/52366a04d35b172ea15af7b518361a0136846b9c/src/extension-host/services/extension.service.ts#L187)):*
<details><summary><i>Previously, lyonsil (Matt Lyons) wrote…</i></summary><blockquote>

Indeed that is what happens.  What do you mean exactly by "even if it was deleted from the original extension folder"?  Do you mean if the ZIP file isn't present anymore?

I think there is a good argument for not loading even extension present in all cases.  Having said that, I'm not sure that the criteria for making that decision ought to be what ZIP files were present in the command line.  People might not have the original ZIP files anymore, and maybe they wouldn't even want to load some of the bundled extensions if we have a bunch of optional ones there.  I was thinking that eventually the app would have something equivalent to a `package.json` file for extensions.  I don't mean literally that format, but I do mean some kind of config that indicates which extensions they should be loading.  I don't remember if it was you or someone else telling me this (maybe Tim?), but someone mentioned to me that we might have different configs/versions for people depending on what role they have in the translation process.

If you think the command line is the right determination for whether or not to load an extension I can make it so.  I was just thinking that we would load everything now like we have been, and the config-based decision on what we should really load would come later.
</blockquote></details>

I'm thinking basically something like this:

Any extension in the default extensions folder (where extensions will be downloaded from the marketplace, I suppose) is considered to be "included" (making this term up right now since we don't have a term for it), meaning Platform.Bible sees it and considers it for activation. Anything added via command line is also considered to be "included", but I would think that would only be considered to be included if it is provided via command line as this seems like a more ephemeral option for including extensions (mostly for development, I imagine, as you could just put an extension in the extensions folder to keep it in Platform.Bible). Maybe we could add a way to configure new permanent extensions folders if that seems like a need at some point.

For now, all included extensions are activated. One day, we will have some kind of extension management to turn included extensions on and off.

In my mind, extensions present in the cache are not considered to be "included" - the cache is only there to unzip and run "included" extensions, not to determine what is "included". This way, if someone puts an extension in the extensions folder (which I'm suggesting means they want that extension to persist until they delete it), all they have to do to remove it is to delete it from there. If someone adds an extension via command line, all they have to do to remove it is to stop providing that command-line argument. They don't need to know about the internal mechanisms we use to run extensions or know that we have an internal cache that holds extension files; they're just seeing that we're including only the extensions that they provide when they provide them.

This feels like expected behavior for "including" extensions in my mind. Conditional activation is outside current scope. Please let me know your thoughts on expected behavior.
___
*[`src/extension-host/services/extension.service.ts` line 206 at r3](https://reviewable.io/reviews/paranext/paranext-core/349#-NbQuvs8ELJJvfrbj-xn:-NbVB_SkBvxDRqoBL6nn:bk31a9r) ([raw file](https://github.com/paranext/paranext-core/blob/f9e38f56d6e3a391994ca4cef42db94bdaf21834/src/extension-host/services/extension.service.ts#L206)):*
<details><summary><i>Previously, lyonsil (Matt Lyons) wrote…</i></summary><blockquote>

I didn't want to `Promise.reject` here because someone might have pointed to a ZIP file, and that isn't really an error condition the same way that a missing manifest is since we will be unzipping the files for them.  That is, we shouldn't log an error message if someone pointed to a ZIP file.  I will work on a better comment here.
</blockquote></details>

Oh I see. Gotcha gotcha. Bummer :/ If only we could make it not log just this one error in a nice way. I guess we could do an `if` in the catch, but that's not super clean :p oh well.

Think you could also add to the comment on 227 to mention that the `!settled.value` is supposed to be specifically to ignore zip files? Just so it's clear what all is supposed to be getting filtered out.
___
*[`src/node/services/node-file-system.service.ts` line 49 at r2](https://reviewable.io/reviews/paranext/paranext-core/349#-NbQcdvq53SJRmLdQU8X:-NbVDLTRCzFXBZBmLQ3S:b-4te3p3) ([raw file](https://github.com/paranext/paranext-core/blob/52366a04d35b172ea15af7b518361a0136846b9c/src/node/services/node-file-system.service.ts#L49)):*
<details><summary><i>Previously, lyonsil (Matt Lyons) wrote…</i></summary><blockquote>

All uses of `existsSync()` have been removed/replaced with async calls.
</blockquote></details>

Looks great! Thank you for doing this. Interesting that `exists` isn't in promises. I guess that's due to the race condition possibility. Not hugely important for us right now, though imo.
___
*[`src/node/services/node-file-system.service.ts` line 127 at r2](https://reviewable.io/reviews/paranext/paranext-core/349#-NbQdK8jDkkz4R3eQj1A:-NbVDD588uo95RbVjrgn:b-iwmy25) ([raw file](https://github.com/paranext/paranext-core/blob/52366a04d35b172ea15af7b518361a0136846b9c/src/node/services/node-file-system.service.ts#L127)):*
<details><summary><i>Previously, lyonsil (Matt Lyons) wrote…</i></summary><blockquote>

I removed the `force` flag.
</blockquote></details>

Weird :p thank you for looking into it!
___
*[`src/node/services/node-file-system.service.ts` line 53 at r4](https://reviewable.io/reviews/paranext/paranext-core/349#-NbVCyC61a4tIVtQNp21:-NbVCyC61a4tIVtQNp22:b-9jyyop) ([raw file](https://github.com/paranext/paranext-core/blob/993d0d61b3cfbfdc5110540d22dfe31e2c166e3e/src/node/services/node-file-system.service.ts#L53)):*
> ```XML
> 
> /**
>  * Get stats about the file or directory. Note that BigInts are used instead of ints to avoid.
> ```

Seems like an accidental period, but no big deal.

**Review by lyonsil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/349)* status: all files reviewed, 1 unresolved discussion

___
*[`src/extension-host/services/extension.service.ts` line 176 at r2](https://reviewable.io/reviews/paranext/paranext-core/349#-NbQaxsj99TwuU0tEV_c:-NbVFgRmDnEWkxcG5Srt:b-r43wt3) ([raw file](https://github.com/paranext/paranext-core/blob/52366a04d35b172ea15af7b518361a0136846b9c/src/extension-host/services/extension.service.ts#L176)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

Good point; it would work just fine either way. But `info` is not logged in production by default, I think. We could definitely change that, but I think it is `warn` by default (I think it just started that way with `electron-log`).
</blockquote></details>

Ah - I was assuming too much.  In my experience production apps that have logs default to `info`.  In my mind `info` is appropriate for production builds and `debug` is appropriate for debug builds as a default logging level.  We don't have to go that way.  It's just what makes sense to me.
___
*[`src/extension-host/services/extension.service.ts` line 206 at r3](https://reviewable.io/reviews/paranext/paranext-core/349#-NbQuvs8ELJJvfrbj-xn:-NbVIvmY4L4_kroiowgY:bqwp01p) ([raw file](https://github.com/paranext/paranext-core/blob/f9e38f56d6e3a391994ca4cef42db94bdaf21834/src/extension-host/services/extension.service.ts#L206)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

Oh I see. Gotcha gotcha. Bummer :/ If only we could make it not log just this one error in a nice way. I guess we could do an `if` in the catch, but that's not super clean :p oh well.

Think you could also add to the comment on 227 to mention that the `!settled.value` is supposed to be specifically to ignore zip files? Just so it's clear what all is supposed to be getting filtered out.
</blockquote></details>

I reworked the code to make it more verbose and clearer.  I put line 227 back how it was.

**Review by lyonsil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/349)* status: 7 of 9 files reviewed, 1 unresolved discussion (waiting on @tjcouch-sil)

___
*[`src/extension-host/services/extension.service.ts` line 187 at r2](https://reviewable.io/reviews/paranext/paranext-core/349#-NbQbxOcE8AdxTaVz18C:-NbVjhZ8CgpclkJ368kc:b-mnlxs2) ([raw file](https://github.com/paranext/paranext-core/blob/52366a04d35b172ea15af7b518361a0136846b9c/src/extension-host/services/extension.service.ts#L187)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

I'm thinking basically something like this:

Any extension in the default extensions folder (where extensions will be downloaded from the marketplace, I suppose) is considered to be "included" (making this term up right now since we don't have a term for it), meaning Platform.Bible sees it and considers it for activation. Anything added via command line is also considered to be "included", but I would think that would only be considered to be included if it is provided via command line as this seems like a more ephemeral option for including extensions (mostly for development, I imagine, as you could just put an extension in the extensions folder to keep it in Platform.Bible). Maybe we could add a way to configure new permanent extensions folders if that seems like a need at some point.

For now, all included extensions are activated. One day, we will have some kind of extension management to turn included extensions on and off.

In my mind, extensions present in the cache are not considered to be "included" - the cache is only there to unzip and run "included" extensions, not to determine what is "included". This way, if someone puts an extension in the extensions folder (which I'm suggesting means they want that extension to persist until they delete it), all they have to do to remove it is to delete it from there. If someone adds an extension via command line, all they have to do to remove it is to stop providing that command-line argument. They don't need to know about the internal mechanisms we use to run extensions or know that we have an internal cache that holds extension files; they're just seeing that we're including only the extensions that they provide when they provide them.

This feels like expected behavior for "including" extensions in my mind. Conditional activation is outside current scope. Please let me know your thoughts on expected behavior.
</blockquote></details>

I think there are multiple ways to manage this, and what you lay out is reasonable.  I have updated the code to reflect this logic.

**Review by tjcouch-sil — DISMISSED** [review]
Thanks for the hard work and perseverance on this one! Sorry for the communication troubles.

> Reviewed 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/349#-:-NbWKECg3gljylNCYoG3:buxl23h)* status: all files reviewed, 1 unresolved discussion (waiting on @lyonsil)

___
*[`src/extension-host/services/extension.service.ts` line 176 at r2](https://reviewable.io/reviews/paranext/paranext-core/349#-NbQaxsj99TwuU0tEV_c:-NbWJ_bE4oGX7bRCD_iH:b7wydqz) ([raw file](https://github.com/paranext/paranext-core/blob/52366a04d35b172ea15af7b518361a0136846b9c/src/extension-host/services/extension.service.ts#L176)):*
<details><summary><i>Previously, lyonsil (Matt Lyons) wrote…</i></summary><blockquote>

Ah - I was assuming too much.  In my experience production apps that have logs default to `info`.  In my mind `info` is appropriate for production builds and `debug` is appropriate for debug builds as a default logging level.  We don't have to go that way.  It's just what makes sense to me.
</blockquote></details>

I went ahead and made an issue for deciding on log levels https://github.com/paranext/paranext-core/issues/353 I dunno what milestone we want to set it to.
___
*[`src/extension-host/services/extension.service.ts` line 187 at r2](https://reviewable.io/reviews/paranext/paranext-core/349#-NbQbxOcE8AdxTaVz18C:-NbWJpG0CtYuQE1vX6YL:b952b83) ([raw file](https://github.com/paranext/paranext-core/blob/52366a04d35b172ea15af7b518361a0136846b9c/src/extension-host/services/extension.service.ts#L187)):*
<details><summary><i>Previously, lyonsil (Matt Lyons) wrote…</i></summary><blockquote>

I think there are multiple ways to manage this, and what you lay out is reasonable.  I have updated the code to reflect this logic.
</blockquote></details>

We discussed also allowing zips in the default extension folder. I'm going to go ahead and mark this as resolved since Matt will do this in a bit.
___
*[`src/extension-host/services/extension.service.ts` line 206 at r3](https://reviewable.io/reviews/paranext/paranext-core/349#-NbQuvs8ELJJvfrbj-xn:-NbWK74m38jJ9TC3hgQh:b6pv2pk) ([raw file](https://github.com/paranext/paranext-core/blob/f9e38f56d6e3a391994ca4cef42db94bdaf21834/src/extension-host/services/extension.service.ts#L206)):*
<details><summary><i>Previously, lyonsil (Matt Lyons) wrote…</i></summary><blockquote>

I reworked the code to make it more verbose and clearer.  I put line 227 back how it was.
</blockquote></details>

Neat :) thanks!
___
*[`src/extension-host/services/extension.service.ts` line 153 at r5](https://reviewable.io/reviews/paranext/paranext-core/349#-NbWIP1y3VW7hqYCuWz2:-NbWIP1zCizjLvP8SKDq:bwiob5b) ([raw file](https://github.com/paranext/paranext-core/blob/6693e1b57329f0d77a791403c3d1097c080a19e7/src/extension-host/services/extension.service.ts#L153)):*
> ```XML
>     });
> 
>   // Remove any explicitly provided ARG_EXTENSIONS values that were files instead of directories
> ```

This is filtering out all `zip`s, not just the ones from `ARG_EXTENSIONS`, right? I could be misunderstanding.

**Review by lyonsil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/349)* status: :shipit: complete! all files reviewed, all discussions resolved

___
*[`src/extension-host/services/extension.service.ts` line 187 at r2](https://reviewable.io/reviews/paranext/paranext-core/349#-NbQbxOcE8AdxTaVz18C:-NbWN1aI0wFKmPTQQCX6:bb6un1j) ([raw file](https://github.com/paranext/paranext-core/blob/52366a04d35b172ea15af7b518361a0136846b9c/src/extension-host/services/extension.service.ts#L187)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

We discussed also allowing zips in the default extension folder. I'm going to go ahead and mark this as resolved since Matt will do this in a bit.
</blockquote></details>

Done
___
*[`src/extension-host/services/extension.service.ts` line 153 at r5](https://reviewable.io/reviews/paranext/paranext-core/349#-NbWIP1y3VW7hqYCuWz2:-NbWMKtY6iiC6UhZkv9S:b6iwdyr) ([raw file](https://github.com/paranext/paranext-core/blob/6693e1b57329f0d77a791403c3d1097c080a19e7/src/extension-host/services/extension.service.ts#L153)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

This is filtering out all `zip`s, not just the ones from `ARG_EXTENSIONS`, right? I could be misunderstanding.
</blockquote></details>

Technically yes, it filters out all files of all kinds for the directories scanned at this point.  Practically speaking, though, the line earlier that does `.flatMap((dirEntries) => dirEntries[nodeFS.EntryType.Directory])` already removed files from `dist` and `ARG_ENTENSION_DIRS`.

Up to this point, I was just trying to gather all the extension directories and ignore files.  The cache directories for any ZIP files are added a few lines later under the comment "Now add in the cache directories for all ZIP files".

I don't know of a way to meaningfully simplify the logic.  We need to gather directories from 3 sources (dist, ARG_EXTENSION_DIRS, and ARG_EXTENSIONS).  The first two need directory scans, and the third needs to see if it's pointing at a manifest.json or just the directory.  All three then may also have ZIP files (and maybe other files we don't care about), but we can't use the direct path to the ZIP files for loading extensions. We have to go back and transform all ZIP file paths to their corresponding cache paths.  It's kind of complicated because the underlying requires are kind of complicated.  Without the command line arguments (or with just one of them) it would be cleaner.

**Review by tjcouch-sil — APPROVED** [review]
:lgtm: thank you again!!

> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/349#-:-Nb_iiMw3Ail2CG7zH8d:blcelkq)* status: :shipit: complete! all files reviewed, all discussions resolved

___
*[`src/extension-host/services/extension.service.ts` line 153 at r5](https://reviewable.io/reviews/paranext/paranext-core/349#-NbWIP1y3VW7hqYCuWz2:-Nb_iBEG2LbkLxQMIUsH:b-cxdznt) ([raw file](https://github.com/paranext/paranext-core/blob/6693e1b57329f0d77a791403c3d1097c080a19e7/src/extension-host/services/extension.service.ts#L153)):*
<details><summary><i>Previously, lyonsil (Matt Lyons) wrote…</i></summary><blockquote>

Technically yes, it filters out all files of all kinds for the directories scanned at this point.  Practically speaking, though, the line earlier that does `.flatMap((dirEntries) => dirEntries[nodeFS.EntryType.Directory])` already removed files from `dist` and `ARG_ENTENSION_DIRS`.

Up to this point, I was just trying to gather all the extension directories and ignore files.  The cache directories for any ZIP files are added a few lines later under the comment "Now add in the cache directories for all ZIP files".

I don't know of a way to meaningfully simplify the logic.  We need to gather directories from 3 sources (dist, ARG_EXTENSION_DIRS, and ARG_EXTENSIONS).  The first two need directory scans, and the third needs to see if it's pointing at a manifest.json or just the directory.  All three then may also have ZIP files (and maybe other files we don't care about), but we can't use the direct path to the ZIP files for loading extensions. We have to go back and transform all ZIP file paths to their corresponding cache paths.  It's kind of complicated because the underlying requires are kind of complicated.  Without the command line arguments (or with just one of them) it would be cleaner.
</blockquote></details>

Oh gotcha. Thanks for clarifying!

**Pull request merged**
