### PR TITLE
Replace most uses of null with undefined

### PR DESCRIPTION
**Pull request by lyonsil**
This change is [Reviewable](https://reviewable.io/reviews/paranext/paranext-core/667)

### CODE REVIEW

**Review by tjcouch-sil — CHANGES_REQUESTED** [review]
Awesome! Thanks for the hard work on all this :)

> Reviewed 46 of 46 files at r1, 3 of 3 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/667#-:-NkvIg1W8c5pVw47hmZ3:brrww8b)* status: all files reviewed, 5 unresolved discussions (waiting on @lyonsil)

___
*[`src/extension-host/services/extension.service.ts` line 762 at r1](https://reviewable.io/reviews/paranext/paranext-core/667#-NkvAsLQ2KAOkvq2bBvo:-NkvAsLQ2KAOkvq2bBvp:bfjfdeq) ([raw file](https://github.com/paranext/paranext-core/blob/2a6b61426f074cdcf68e09d8de2b6dcadf948e4c/src/extension-host/services/extension.service.ts#L762)):*
> ```XML
> 
>   // Save extensions that have JavaScript to run
>   // If main is am empty string, having no JavaScript is intentional. Do not load this extension
> ```

typo: `an`
___
*[`src/renderer/hooks/papi-hooks/use-promise.hook.ts` line 44 at r1](https://reviewable.io/reviews/paranext/paranext-core/667#-NkvC4VZ8YA-YBy8YhPj:-NkvC4VZ8YA-YBy8YhPk:b-g62hlu) ([raw file](https://github.com/paranext/paranext-core/blob/2a6b61426f074cdcf68e09d8de2b6dcadf948e4c/src/renderer/hooks/papi-hooks/use-promise.hook.ts#L44)):*
> ```XML
>         if (promiseIsCurrent) {
>           // If the promise returned undefined, it purposely did this to do nothing. Maybe its dependencies are not set up
>           if (result !== undefined) setValue(() => result);
> ```

Sorry, I didn't clearly convey my proposed direction for this hook. My proposition was to remove this and always set it instead of having some condition in which it doesn't set it. It seemed like this condition would probably feel more like a bug than a feature if it's on the only "not defined"-like value you can use in the codebase. We can definitely just add a bullet point to consider as part of #552 instead if that's preferable; no rush.
___
*[`src/shared/services/settings.service.ts` line 71 at r1](https://reviewable.io/reviews/paranext/paranext-core/667#-NkvE2IN2R1TzbarJFiU:-NkvE2IN2R1TzbarJFiV:b-35yr76) ([raw file](https://github.com/paranext/paranext-core/blob/2a6b61426f074cdcf68e09d8de2b6dcadf948e4c/src/shared/services/settings.service.ts#L71)):*
I don't actually know how this worked before without `as unknown as`... Can you change this line and another line above with the following to avoid the `as unknown as`? Those are best to avoid in general if we can:

```typescript
emitter as PapiEventEmitter<SettingTypes[SettingNames] | undefined>
```

and change the type of `onDidUpdateSettingEmitters` to the following:

```typescript
const onDidUpdateSettingEmitters = new Map<
  SettingNames,
  PapiEventEmitter<SettingTypes[SettingNames] | undefined>
>();
```

I think `onDidUpdateSettingEmitters` has the wrong type as is. I understand this isn't your problem, but we generally explain why we have `as unknown as`. I think these quick tweaks would hopefully prevent needing to put it at all.

I would vote that we put it in our style guide to require an explanation for `as unknown as` since it effectively completely destroys type checking, but I dunno if we have ever really conclusively stated we should do that.
___
*[`src/shared/utils/papi-util.ts` line 162 at r1](https://reviewable.io/reviews/paranext/paranext-core/667#-NkvFbBa9hXVzy8_VwHi:-NkvFbBa9hXVzy8_VwHj:b1gdxg5) ([raw file](https://github.com/paranext/paranext-core/blob/2a6b61426f074cdcf68e09d8de2b6dcadf948e4c/src/shared/utils/papi-util.ts#L162)):*
> ```XML
> 
> // Something to stand for both "undefined" and "null"
> const NIL_MONIKER: string = '__NIL__';
> ```

Sorry it wasn't super clear in my description, but I believe we should use `null` instead of a special moniker. That would express better in the JSON (no weird magic values; it's just normal ol' JSON) and not require additional logic in other languages that don't have a difference between `null` and `undefined`. Seems a bit nicer in my mind than requiring everyone who uses the WebSocket to write a custom serializer and deserializer over this little thing. Would be glad to hear your opinion and discuss if you have a different perspective - not sure if you came to a different conclusion after considering benefits and drawbacks or just thought I was suggesting this.

Honestly I'm surprised everything works with the C# right now because of this :thinking:
___
*[`src/shared/utils/papi-util.test.ts` line 328 at r1](https://reviewable.io/reviews/paranext/paranext-core/667#-NkvHILq9DmQFF1k0Fq8:-NkvHILq9DmQFF1k0Fq9:bq8kp60) ([raw file](https://github.com/paranext/paranext-core/blob/2a6b61426f074cdcf68e09d8de2b6dcadf948e4c/src/shared/utils/papi-util.test.ts#L328)):*
> ```XML
>   });
> 
>   it('successfully determines object with `undefined` prop is not serializable', () => {
> ```

Why did these two tests flip? I think it makes sense to consider these to be serializable, especially since even `undefined` is now serializable. I consider this to be a bug currently.

If this is some crazy 4d chess stuff because of the change, maybe we can file an issue and keep moving with our lives for now - would need to consider the potential impacts of this bug. But it would be good to mark these tests as not performing correctly and link the issue (as in the test below - my most ceremonious `UNsuccessfully` haha) for now if we skip on fixing this.

**Review by irahopkinson — APPROVED** [review]
:lgtm: thanks for this work - loving it. My comments are all non-blocking

> Reviewed 44 of 46 files at r1, 3 of 3 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/667#-:-NkvSdpbCH2Ft3LJkA5y:bjqkmav)* status: all files reviewed, 9 unresolved discussions (waiting on @lyonsil)

___
*[`src/renderer/components/web-view.component.tsx` line 36 at r3](https://reviewable.io/reviews/paranext/paranext-core/667#-NkvNSIO3yZUL9QZHCrG:-NkvNSIO3yZUL9QZHCrH:btdv97x) ([raw file](https://github.com/paranext/paranext-core/blob/244783a55931e579b44c19d7ca5904f633266363/src/renderer/components/web-view.component.tsx#L36)):*
> ```XML
>   // This ref will always be defined
>   // eslint-disable-next-line no-type-assertion/no-type-assertion
>   const iframeRef = useRef<HTMLIFrameElement>(undefined!);
> ```

BTW can you use `undefined` with `useRef`? In another file you add a comment that indicates that you can't.
___
*[`src/renderer/context/papi-context/test.context.ts` line 3 at r3](https://reviewable.io/reviews/paranext/paranext-core/667#-NkvO6La7Y6oeki-cCCY:-NkvO6La7Y6oeki-cCCZ:bg9cjp7) ([raw file](https://github.com/paranext/paranext-core/blob/244783a55931e579b44c19d7ca5904f633266363/src/renderer/context/papi-context/test.context.ts#L3)):*
> ```XML
> import { createContext } from 'react';
> 
> const TestContext = createContext<string>('');
> ```

BTW strictly now it doesn't need the type specifier, i.e `const TestContext = createContext('');`, cleaner is better here, IMO.



_Code quote:_
```XML
<string>
```
___
*[`src/shared/utils/papi-util.test.ts` line 37 at r3](https://reviewable.io/reviews/paranext/paranext-core/667#-NkvRawL10Flh5HWj7tn:-NkvRawL10Flh5HWj7to:brqjydl) ([raw file](https://github.com/paranext/paranext-core/blob/244783a55931e579b44c19d7ca5904f633266363/src/shared/utils/papi-util.test.ts#L37)):*
> ```XML
>   });
> 
>   it('can deserialize with more than one separator in request types', () => {
> ```

BTW Adding each of these to the `it` descriptions indicates to me these series of `it` blocks should be moved to a nested `describe` block.



_Code quote:_
```XML
 in request types
```
___
*[`src/shared/utils/papi-util.test.ts` line 210 at r3](https://reviewable.io/reviews/paranext/paranext-core/667#-NkvR62TExLdxsn19aiU:-NkvR62TExLdxsn19aiV:b-5l8r7g) ([raw file](https://github.com/paranext/paranext-core/blob/244783a55931e579b44c19d7ca5904f633266363/src/shared/utils/papi-util.test.ts#L210)):*
> ```XML
> });
> 
> describe('serialize and deserialize', () => {
> ```

BTW descriptions are typically in Title Case to allow them to be distinguished in the output.

**Review by tjcouch-sil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/667)* status: all files reviewed, 9 unresolved discussions (waiting on @irahopkinson and @lyonsil)

___
*[`src/renderer/components/web-view.component.tsx` line 36 at r3](https://reviewable.io/reviews/paranext/paranext-core/667#-NkvNSIO3yZUL9QZHCrG:-NkvmnT_3KP-F2HKWjN5:b-7ei8e) ([raw file](https://github.com/paranext/paranext-core/blob/244783a55931e579b44c19d7ca5904f633266363/src/renderer/components/web-view.component.tsx#L36)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

BTW can you use `undefined` with `useRef`? In another file you add a comment that indicates that you can't.
</blockquote></details>

I think maybe the issue with the other one is that it was being compared to `null` in some spot (I think in our code, but it may also have been related to `rc-dock`. I didn't look super closely). I think `undefined` is probably fine in both places if it doesn't go into any `rc-dock` apis.

**Review by lyonsil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/667)* status: all files reviewed, 2 unresolved discussions (waiting on @tjcouch-sil)

___
*[`src/extension-host/services/extension.service.ts` line 762 at r1](https://reviewable.io/reviews/paranext/paranext-core/667#-NkvAsLQ2KAOkvq2bBvo:-NkvaQj9973m9xX5dNcz:b-886gsx) ([raw file](https://github.com/paranext/paranext-core/blob/2a6b61426f074cdcf68e09d8de2b6dcadf948e4c/src/extension-host/services/extension.service.ts#L762)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

typo: `an`
</blockquote></details>

Fixed
___
*[`src/renderer/components/web-view.component.tsx` line 36 at r3](https://reviewable.io/reviews/paranext/paranext-core/667#-NkvNSIO3yZUL9QZHCrG:-NkvlgBoEXXSdN0rZr0H:b-2ugwq2) ([raw file](https://github.com/paranext/paranext-core/blob/244783a55931e579b44c19d7ca5904f633266363/src/renderer/components/web-view.component.tsx#L36)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

BTW can you use `undefined` with `useRef`? In another file you add a comment that indicates that you can't.
</blockquote></details>

Good catch - I made the other comment based on something I read from someone else's post online, but when I tested it later it worked fine.  I forgot to change to other one to `undefined` afterwards.
___
*[`src/renderer/context/papi-context/test.context.ts` line 3 at r3](https://reviewable.io/reviews/paranext/paranext-core/667#-NkvO6La7Y6oeki-cCCY:-Nkva_jeDFNE43vnhz73:boob4jf) ([raw file](https://github.com/paranext/paranext-core/blob/244783a55931e579b44c19d7ca5904f633266363/src/renderer/context/papi-context/test.context.ts#L3)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

BTW strictly now it doesn't need the type specifier, i.e `const TestContext = createContext('');`, cleaner is better here, IMO.
</blockquote></details>

Good point - Fixed.
___
*[`src/renderer/hooks/papi-hooks/use-promise.hook.ts` line 44 at r1](https://reviewable.io/reviews/paranext/paranext-core/667#-NkvC4VZ8YA-YBy8YhPj:-NkvbUhQ4fRZZwMztpPs:b3tqtt8) ([raw file](https://github.com/paranext/paranext-core/blob/2a6b61426f074cdcf68e09d8de2b6dcadf948e4c/src/renderer/hooks/papi-hooks/use-promise.hook.ts#L44)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

Sorry, I didn't clearly convey my proposed direction for this hook. My proposition was to remove this and always set it instead of having some condition in which it doesn't set it. It seemed like this condition would probably feel more like a bug than a feature if it's on the only "not defined"-like value you can use in the codebase. We can definitely just add a bullet point to consider as part of #552 instead if that's preferable; no rush.
</blockquote></details>

Got it - sorry for the confusion.  Done.
___
*[`src/shared/services/settings.service.ts` line 71 at r1](https://reviewable.io/reviews/paranext/paranext-core/667#-NkvE2IN2R1TzbarJFiU:-NkvcCNZ6WvtLyfWvcVK:bp1edr8) ([raw file](https://github.com/paranext/paranext-core/blob/2a6b61426f074cdcf68e09d8de2b6dcadf948e4c/src/shared/services/settings.service.ts#L71)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

I don't actually know how this worked before without `as unknown as`... Can you change this line and another line above with the following to avoid the `as unknown as`? Those are best to avoid in general if we can:

```typescript
emitter as PapiEventEmitter<SettingTypes[SettingNames] | undefined>
```

and change the type of `onDidUpdateSettingEmitters` to the following:

```typescript
const onDidUpdateSettingEmitters = new Map<
  SettingNames,
  PapiEventEmitter<SettingTypes[SettingNames] | undefined>
>();
```

I think `onDidUpdateSettingEmitters` has the wrong type as is. I understand this isn't your problem, but we generally explain why we have `as unknown as`. I think these quick tweaks would hopefully prevent needing to put it at all.

I would vote that we put it in our style guide to require an explanation for `as unknown as` since it effectively completely destroys type checking, but I dunno if we have ever really conclusively stated we should do that.
</blockquote></details>

The code change is done.  I'll leave the style guide discussion as a separate thing outside of this PR.
___
*[`src/shared/utils/papi-util.ts` line 162 at r1](https://reviewable.io/reviews/paranext/paranext-core/667#-NkvFbBa9hXVzy8_VwHi:-NkvdQwaCb-XVWQuySlD:bobdirj) ([raw file](https://github.com/paranext/paranext-core/blob/2a6b61426f074cdcf68e09d8de2b6dcadf948e4c/src/shared/utils/papi-util.ts#L162)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

Sorry it wasn't super clear in my description, but I believe we should use `null` instead of a special moniker. That would express better in the JSON (no weird magic values; it's just normal ol' JSON) and not require additional logic in other languages that don't have a difference between `null` and `undefined`. Seems a bit nicer in my mind than requiring everyone who uses the WebSocket to write a custom serializer and deserializer over this little thing. Would be glad to hear your opinion and discuss if you have a different perspective - not sure if you came to a different conclusion after considering benefits and drawbacks or just thought I was suggesting this.

Honestly I'm surprised everything works with the C# right now because of this :thinking:
</blockquote></details>

Done - I bounced between a few options.  Everything is lossy because of the JS language design, so it all feels a little weird.  Sorry for the misunderstanding.  This probably is better for cross-language compatibility on the websocket.
___
*[`src/shared/utils/papi-util.test.ts` line 328 at r1](https://reviewable.io/reviews/paranext/paranext-core/667#-NkvHILq9DmQFF1k0Fq8:-NkvhWkLCy04y06LDiCr:b-i7l4uh) ([raw file](https://github.com/paranext/paranext-core/blob/2a6b61426f074cdcf68e09d8de2b6dcadf948e4c/src/shared/utils/papi-util.test.ts#L328)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

Why did these two tests flip? I think it makes sense to consider these to be serializable, especially since even `undefined` is now serializable. I consider this to be a bug currently.

If this is some crazy 4d chess stuff because of the change, maybe we can file an issue and keep moving with our lives for now - would need to consider the potential impacts of this bug. But it would be good to mark these tests as not performing correctly and link the issue (as in the test below - my most ceremonious `UNsuccessfully` haha) for now if we skip on fixing this.
</blockquote></details>

They flipped because the behavior changed based on the new definition.  I gave an example of this in the JSDocs for `serialize` and `deserialize`:
```
For example, `{ a: 1, b: undefined, c: null }` will become `{ a: 1 }` after passing through serialize then deserialize.
```

The definition of `isSerializable` is essentially "is the JSON string representing this object the same if I serialize it once compared to if I serialize it after round-tripping."  The answer to that is "no" for `undefined` and `null` properties.  For the example above, the first time it serializes the string is `{ a: 1, b: null, c: null }`, and the subsequent times will be `{ a: 1 }`.  We can change the meaning of `isSerializable` if you think that definition is the wrong one to use, but I thought this was clear going into this issue.
___
*[`src/shared/utils/papi-util.test.ts` line 37 at r3](https://reviewable.io/reviews/paranext/paranext-core/667#-NkvRawL10Flh5HWj7tn:-Nkvgf3P35BfIkGw5kcB:b-65ttba) ([raw file](https://github.com/paranext/paranext-core/blob/244783a55931e579b44c19d7ca5904f633266363/src/shared/utils/papi-util.test.ts#L37)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

BTW Adding each of these to the `it` descriptions indicates to me these series of `it` blocks should be moved to a nested `describe` block.
</blockquote></details>

The `describe` block these were in wasn't named in a parallel way with the other `describe` blocks, so I did some renaming.  Note these tests existed prior to this PR.
___
*[`src/shared/utils/papi-util.test.ts` line 210 at r3](https://reviewable.io/reviews/paranext/paranext-core/667#-NkvR62TExLdxsn19aiU:-NkvgtKTCBMDQuefODzH:b7ogcly) ([raw file](https://github.com/paranext/paranext-core/blob/244783a55931e579b44c19d7ca5904f633266363/src/shared/utils/papi-util.test.ts#L210)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

BTW descriptions are typically in Title Case to allow them to be distinguished in the output.
</blockquote></details>

I adjusted all the descriptions to use Title Case except for the function names.  I left those to match the actual casing of the functions themselves.

**Review by tjcouch-sil — CHANGES_REQUESTED** [review]
Thanks for the quick turnaround on these things! Almost there - just one hopefully small bit of discussion left and one optional tiny thing.

> Reviewed 8 of 8 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/667#-:-NkwEEhe7EQhSB4oL9A0:b76gbwr)* status: all files reviewed, 2 unresolved discussions (waiting on @lyonsil)

___
*[`src/renderer/hooks/papi-hooks/use-promise.hook.ts` line 44 at r1](https://reviewable.io/reviews/paranext/paranext-core/667#-NkvC4VZ8YA-YBy8YhPj:-Nkw8QaMEffCZJq9d6p1:b-jmdttr) ([raw file](https://github.com/paranext/paranext-core/blob/2a6b61426f074cdcf68e09d8de2b6dcadf948e4c/src/renderer/hooks/papi-hooks/use-promise.hook.ts#L44)):*
<details><summary><i>Previously, lyonsil (Matt Lyons) wrote…</i></summary><blockquote>

Got it - sorry for the confusion.  Done.
</blockquote></details>

No worries. Thanks!
___
*[`src/shared/utils/papi-util.ts` line 162 at r1](https://reviewable.io/reviews/paranext/paranext-core/667#-NkvFbBa9hXVzy8_VwHi:-NkwAjYLETvGQ31r0G4z:bfg8d4z) ([raw file](https://github.com/paranext/paranext-core/blob/2a6b61426f074cdcf68e09d8de2b6dcadf948e4c/src/shared/utils/papi-util.ts#L162)):*
<details><summary><i>Previously, lyonsil (Matt Lyons) wrote…</i></summary><blockquote>

Done - I bounced between a few options.  Everything is lossy because of the JS language design, so it all feels a little weird.  Sorry for the misunderstanding.  This probably is better for cross-language compatibility on the websocket.
</blockquote></details>

Thanks! Yeah, I agree it's weird... Hopefully this will all straighten things out a bit though. Thanks for the great work on it :)
___
*[`src/shared/utils/papi-util.ts` line 162 at r4](https://reviewable.io/reviews/paranext/paranext-core/667#-NkwAymz1st5cmgdepwu:-NkwAymz1st5cmgdepwv:b-p17kki) ([raw file](https://github.com/paranext/paranext-core/blob/949ae19115cb2f5f76fa5469f14523825b358cb5/src/shared/utils/papi-util.ts#L162)):*
> ```XML
> 
> /**
>  * Converts a JavaScript value to a JSON string, changing `null` and `undefined` values to a moniker
> ```

Should it be specified now that this is converting to `null` instead of a moniker?
___
*[`src/shared/utils/papi-util.test.ts` line 328 at r1](https://reviewable.io/reviews/paranext/paranext-core/667#-NkvHILq9DmQFF1k0Fq8:-NkwBQFVA42xLVCVsR-k:bayk4zv) ([raw file](https://github.com/paranext/paranext-core/blob/2a6b61426f074cdcf68e09d8de2b6dcadf948e4c/src/shared/utils/papi-util.test.ts#L328)):*
<details><summary><i>Previously, lyonsil (Matt Lyons) wrote…</i></summary><blockquote>

They flipped because the behavior changed based on the new definition.  I gave an example of this in the JSDocs for `serialize` and `deserialize`:
```
For example, `{ a: 1, b: undefined, c: null }` will become `{ a: 1 }` after passing through serialize then deserialize.
```

The definition of `isSerializable` is essentially "is the JSON string representing this object the same if I serialize it once compared to if I serialize it after round-tripping."  The answer to that is "no" for `undefined` and `null` properties.  For the example above, the first time it serializes the string is `{ a: 1, b: null, c: null }`, and the subsequent times will be `{ a: 1 }`.  We can change the meaning of `isSerializable` if you think that definition is the wrong one to use, but I thought this was clear going into this issue.
</blockquote></details>

Ah man, I was worried that's what happened here... I'm bummed that it doesn't deserialize back out to `{ a: 1, b: undefined, c: undefined }`, but that's the 4d chess stuff I was thinking of; I guess we would have to stop using a `reviver` and instead recursively crawl the entries of the object and change all `null`s to `undefined` after `JSON.parse` runs as it seems the step of removing `undefined` values happens after the reviver function runs. Bummer :(

In my mind, `undefined` and not being present should be considered equivalent when determining if it's serializable, so I think that would mean `isSerializable` is a bit broken. I was hoping the `reviver` would keep the objects' `undefined` values around unlike default `JSON.parse`. But I think it's probably fine to just make an issue and worry about it another time whenever we run into an issue if you want.

I think the only particular consequence right now that I can think of is that people will not be able to make webview state an object that has an `undefined` member. I guess we can cross that bridge when we get there if you prefer. However, I would like for this test to indicate that this is not expected functionality but has been delayed to another issue (unless you want to discuss that it isn't a bug).

**Review by irahopkinson — APPROVED** [review]
> Reviewed 8 of 8 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/667)* status: all files reviewed, 2 unresolved discussions (waiting on @lyonsil)

___
*[`src/shared/utils/papi-util.test.ts` line 37 at r3](https://reviewable.io/reviews/paranext/paranext-core/667#-NkvRawL10Flh5HWj7tn:-NkwTgLC3-mdQMbF5J9u:b9th0dx) ([raw file](https://github.com/paranext/paranext-core/blob/244783a55931e579b44c19d7ca5904f633266363/src/shared/utils/papi-util.test.ts#L37)):*
<details><summary><i>Previously, lyonsil (Matt Lyons) wrote…</i></summary><blockquote>

The `describe` block these were in wasn't named in a parallel way with the other `describe` blocks, so I did some renaming.  Note these tests existed prior to this PR.
</blockquote></details>

I did know they were there before (I wrote them) but you had changed their description so that makes it part of this PR. I think your solution is better than my suggestion.

**Review by irahopkinson — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/667)* status: all files reviewed, 2 unresolved discussions (waiting on @lyonsil)

**Review by lyonsil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/667)* status: 45 of 48 files reviewed, 1 unresolved discussion (waiting on @irahopkinson and @tjcouch-sil)

___
*[`src/shared/utils/papi-util.ts` line 162 at r4](https://reviewable.io/reviews/paranext/paranext-core/667#-NkwAymz1st5cmgdepwu:-NkwYzLwCPj6x6dMtzl8:b3kqjub) ([raw file](https://github.com/paranext/paranext-core/blob/949ae19115cb2f5f76fa5469f14523825b358cb5/src/shared/utils/papi-util.ts#L162)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

Should it be specified now that this is converting to `null` instead of a moniker?
</blockquote></details>

Good point - fixed
___
*[`src/shared/utils/papi-util.test.ts` line 328 at r1](https://reviewable.io/reviews/paranext/paranext-core/667#-NkvHILq9DmQFF1k0Fq8:-NkwbAJQ9AZq3NZ9Bpdo:b50zdc2) ([raw file](https://github.com/paranext/paranext-core/blob/2a6b61426f074cdcf68e09d8de2b6dcadf948e4c/src/shared/utils/papi-util.test.ts#L328)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

Ah man, I was worried that's what happened here... I'm bummed that it doesn't deserialize back out to `{ a: 1, b: undefined, c: undefined }`, but that's the 4d chess stuff I was thinking of; I guess we would have to stop using a `reviver` and instead recursively crawl the entries of the object and change all `null`s to `undefined` after `JSON.parse` runs as it seems the step of removing `undefined` values happens after the reviver function runs. Bummer :(

In my mind, `undefined` and not being present should be considered equivalent when determining if it's serializable, so I think that would mean `isSerializable` is a bit broken. I was hoping the `reviver` would keep the objects' `undefined` values around unlike default `JSON.parse`. But I think it's probably fine to just make an issue and worry about it another time whenever we run into an issue if you want.

I think the only particular consequence right now that I can think of is that people will not be able to make webview state an object that has an `undefined` member. I guess we can cross that bridge when we get there if you prefer. However, I would like for this test to indicate that this is not expected functionality but has been delayed to another issue (unless you want to discuss that it isn't a bug).
</blockquote></details>

Done - comments have been updated, and #672 has been filed to look at in the future.

**Review by tjcouch-sil — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/667#-:-Nkzx0Mu3zY_HwUc9-IZ:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

___
*[`src/shared/utils/papi-util.test.ts` line 328 at r1](https://reviewable.io/reviews/paranext/paranext-core/667#-NkvHILq9DmQFF1k0Fq8:-Nkzwl_RE6BuwUz4eUaW:b-2ltqf4) ([raw file](https://github.com/paranext/paranext-core/blob/2a6b61426f074cdcf68e09d8de2b6dcadf948e4c/src/shared/utils/papi-util.test.ts#L328)):*
<details><summary><i>Previously, lyonsil (Matt Lyons) wrote…</i></summary><blockquote>

Done - comments have been updated, and #672 has been filed to look at in the future.
</blockquote></details>

Sounds great. Thank you!

**Pull request merged**
