### PR TITLE
Support surrogate pairs

### LINKED ISSUE #686: Internationalization: Support handling UTF-16 Surrogate pair code points
**User Story**

As a user of a language that uses characters not on UTF-16 plane 0, I want Platform.Bible to support using my language so that I can do stuff.

**Description**

We need to support various operations on code points instead of just on UTF-16 code units (built-in JS string operations):
- [ ] Create utility functions or a grouping of functions in `platform-bible-utils` that wrap the [`stringz`](https://www.npmjs.com/package/stringz) library
  - [x] `indexOf` - built into `stringz`
  - [x] `substring` - built into `stringz`
  - [x] `length` - built into `stringz`
  - [x] `toArray` - built into `stringz`
  - [x] `padStart` - can use `limit` probably. However, if there isn't a way to specify `length` parameter as unlimited, you'll have to implement this yourself. See [`padStart`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/padStart) for the interface
  - [x] `padEnd` - can use `limit` probably. However, if there isn't a way to specify `length` parameter as unlimited, you'll have to implement this yourself. See [`padEnd`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/padEnd) for the interface
  - [x] `normalize` - you can just wrap the built-in [`normalize`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/normalize) if this even seems worth doing
  - [ ] Other [String methods](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String)
    - [ ] If there is a very significant impact from doing the operation with code points vs without code points, we should implement these functions. `lastIndexOf` probably should be, for example, since doing it without considering code points would probably yield a very different result
    - [ ] Other methods that have small impact or no impact from doing with code points can probably wait to be reimplemented in this string library. Make sure to document in the readme or the JSDoc for the string function grouping which other String methods have very small differences when considering code points and were just not implemented yet and which String methods have no difference and were not wrapped as a result (`split` for example has pretty insignificant difference, so maybe we don't need to implement it yet)
- [ ] If there are any significant places to use this at this point, change them from the built-in string functions to these. You can use "Find All References" on built-in string functions in VSCode. Things like `indexOf`, `substring`, `slice`, `length`, and others that could be replaced with these. Not the end of the world if you miss one or two.

[Internationalization Spec](https://docs.google.com/document/d/1dFSTR6bgt7n0HaXOvnV3Cc-z1R2S9Gb5KlNlIS4liQI/edit)

<details><summary>Old description</summary>
<p>

We discussed [on Discord](https://discord.com/channels/1064938364597436416/1082712295739760652/1184131003619475456) that we need to convert string operations to operations that support surrogate pairs and such features that are not on unicode plane 0.

Let's use [`stringz`](https://www.npmjs.com/package/stringz). Let's convert all our string operations to use it instead of built-in string operations where possible.

</p>
</details>

### PR DESCRIPTION
**Pull request by rolfheij-sil**
Resolves #686

- - -
This change is [Reviewable](https://reviewable.io/reviews/paranext/paranext-core/773)

### CODE REVIEW

**Review by tjcouch-sil — CHANGES_REQUESTED** [review]
Awesome! Thanks for the good stuff :) some things to look at, but hopefully they're small things

> Reviewed 39 of 39 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/773#-:-Nr6brDd4s3fMtmTTghl:bkxrjn5)* status: all files reviewed, 11 unresolved discussions (waiting on @rolfheij-sil)

___
*[`extensions/src/hello-world/src/web-views/hello-world-2.web-view.tsx` line 26 at r1](https://reviewable.io/reviews/paranext/paranext-core/773#-Nr6OYgDAVCTdu1Uw3f_:-Nr6OYgDAVCTdu1Uw3fa:bhia5ua) ([raw file](https://github.com/paranext/paranext-core/blob/4bdb0c59cf7f12cf561a3adf320768017f2348ee/extensions/src/hello-world/src/web-views/hello-world-2.web-view.tsx#L26)):*
> ```XML
>   );
> 
>   const someIndex = indexOf('SomeStringWithABunchOfWords', 'i', 15);
> ```

Is this test code that should be removed?
___
*[`lib/papi-dts/edit-papi-d-ts.ts` line 142 at r1](https://reviewable.io/reviews/paranext/paranext-core/773#-Nr2KU15-T__Uja2tVAp:-Nr6On9aBYJCbzJi9Q0Q:blvh3fq) ([raw file](https://github.com/paranext/paranext-core/blob/4bdb0c59cf7f12cf561a3adf320768017f2348ee/lib/papi-dts/edit-papi-d-ts.ts#L142)):*
<details><summary><i>Previously, rolfheij-sil wrote…</i></summary><blockquote>

For some reason we can't use our new functions in this file. Does that make sense?

Using it here will trigger the `export {}` issue when trying to build types
</blockquote></details>

I don't know why that issue arises, but it's fine to leave the changes out of this file :)
___
*[`lib/platform-bible-utils/dist/index.d.ts` line 1018 at r1](https://reviewable.io/reviews/paranext/paranext-core/773#-Nr6PJBr38vD0lH13HJa:-Nr6PJBs0YUxcmDeszPA:b-rntig1) ([raw file](https://github.com/paranext/paranext-core/blob/4bdb0c59cf7f12cf561a3adf320768017f2348ee/lib/platform-bible-utils/dist/index.d.ts#L1018)):*
> ```XML
> 
> export {
> 	length$1 as length,
> ```

Any idea what this is?
___
*[`lib/platform-bible-utils/src/string-util.ts` line 1 at r1](https://reviewable.io/reviews/paranext/paranext-core/773#-Nr6Qb7gCJxaN75xK69M:-Nr6Qb7gCJxaN75xK69N:bre2ovx) ([raw file](https://github.com/paranext/paranext-core/blob/4bdb0c59cf7f12cf561a3adf320768017f2348ee/lib/platform-bible-utils/src/string-util.ts#L1)):*
> ```XML
> import {
> ```

How does the generated documentation page look for these string utils? Would it benefit from having a jsdoc at the top that explains that this consists of util functions that mirror the built-in ones but work on code points? I can't remember if those get picked up in the generated docs or not, but it seems like it would be helpful if it does :)
___
*[`lib/platform-bible-utils/src/string-util.ts` line 11 at r1](https://reviewable.io/reviews/paranext/paranext-core/773#-Nr6QAsO62iccPNRr5CF:-Nr6QAsO62iccPNRr5CG:b-n0ggxi) ([raw file](https://github.com/paranext/paranext-core/blob/4bdb0c59cf7f12cf561a3adf320768017f2348ee/lib/platform-bible-utils/src/string-util.ts#L11)):*
> ```XML
> 
> /**
>  * Finds the Unicode code point at the given index
> ```

I think this needs "This function handles Unicode code points instead of UTF-16 character codes."
___
*[`lib/platform-bible-utils/src/string-util.ts` line 14 at r1](https://reviewable.io/reviews/paranext/paranext-core/773#-Nr6PgcWCPFC1tcPY4Jo:-Nr6PgcXBuNhkyavTAnJ:bd3lcvu) ([raw file](https://github.com/paranext/paranext-core/blob/4bdb0c59cf7f12cf561a3adf320768017f2348ee/lib/platform-bible-utils/src/string-util.ts#L14)):*
> ```XML
>  *
>  * @param {string} string String to index
>  * @param {number} index Position of the character to be returned in range of 0 to -length(string)
> ```

Is this the right range? I am confused about it
___
*[`lib/platform-bible-utils/src/string-util.ts` line 17 at r1](https://reviewable.io/reviews/paranext/paranext-core/773#-Nr6S93-0VnwNHxyv3u1:-Nr6S93-0VnwNHxyv3u2:b-xhhxs4) ([raw file](https://github.com/paranext/paranext-core/blob/4bdb0c59cf7f12cf561a3adf320768017f2348ee/lib/platform-bible-utils/src/string-util.ts#L17)):*
> ```XML
>  * @returns {string} New string consisting of the Unicode code point located at the specified
>  *   offset, undefined if index is out of bounds
>  */
> ```

This file's functions use almost exclusively JSDoc syntax, but we usually use TSDoc syntax. For example, compare these JSDocs to those in `lib\platform-bible-utils\src\util.ts` which use TSDoc syntax. Sorry for the confusion. VSCode generates TSDocs when you type `/**` and hit enter above a function, so I wonder how these got to be JSDocs.

I thought VSCode offered a way to automatically transform JSDocs into TSDocs in the quick fix menu, but I'm not seeing it right now. Maybe you'll see it. I think I remember the function has the little white dots under it if the transformation is available. This screenshot shows something very similar but not the same thing:


Anyway, I don't think this breaks anything, so this isn't a demand or anything, but I do recommend changing to TSDocs since they are more concise and the types won't get out of sync.
___
*[`lib/platform-bible-utils/src/string-util.ts` line 24 at r1](https://reviewable.io/reviews/paranext/paranext-core/773#-Nr6QDI-C1pg2Mzz8aP-:-Nr6QDI-C1pg2Mzz8aP0:b-xetssz) ([raw file](https://github.com/paranext/paranext-core/blob/4bdb0c59cf7f12cf561a3adf320768017f2348ee/lib/platform-bible-utils/src/string-util.ts#L24)):*
> ```XML
> 
> /**
>  * Always indexes string as a sequence of Unicode code points
> ```

I am confused about this description. Does it need some adjustment? Also I think it needs "This function handles Unicode code points instead of UTF-16 character codes."
___
*[`lib/platform-bible-utils/src/string-util.ts` line 114 at r1](https://reviewable.io/reviews/paranext/paranext-core/773#-Nr6WMod2Unr-93qrlfG:-Nr6WMod2Unr-93qrlfH:b-6ezp2d) ([raw file](https://github.com/paranext/paranext-core/blob/4bdb0c59cf7f12cf561a3adf320768017f2348ee/lib/platform-bible-utils/src/string-util.ts#L114)):*
> ```XML
>  * @param {string} searchString Substring to search for
>  * @param {number} [position=+Infinity] The method returns the index of the last occurrence of the
>  *   specified substring at a position less than or equal to position. . Default is `+Infinity`
> ```

Calling the default `+Infinity` was confusing to read. I didn't understand what it meant without reading the code. Maybe consider saying something along the lines of what the built-in `lastIndexOf` says: "The index at which to begin searching. If omitted, the search begins at the end of the string." and using `undefined`
___
*[`lib/platform-bible-utils/src/string-util.ts` line 156 at r1](https://reviewable.io/reviews/paranext/paranext-core/773#-Nr6XFteDjTN7roxZJjI:-Nr6XFteDjTN7roxZJjJ:b-nrdisa) ([raw file](https://github.com/paranext/paranext-core/blob/4bdb0c59cf7f12cf561a3adf320768017f2348ee/lib/platform-bible-utils/src/string-util.ts#L156)):*
> ```XML
>  * @param {'NFC' | 'NFD' | 'NFKC' | 'NFKD' | 'none'} [form='NFC'] Form specifying the Unicode
>  *   Normalization Form. Default is `'NFC'`
>  * @returns {string} A string containing the Unicode Normalization Form of the given string.
> ```

This JSDoc overall and especially this return statement are a bit confusing. I recommend rewording to match the built-in normalize a bit better.
___
*[`lib/platform-bible-utils/src/string-util.ts` line 338 at r1](https://reviewable.io/reviews/paranext/paranext-core/773#-Nr6Z3Xa8rx6xZepiH3q:-Nr6Z3Xa8rx6xZepiH3r:bmqbxuh) ([raw file](https://github.com/paranext/paranext-core/blob/4bdb0c59cf7f12cf561a3adf320768017f2348ee/lib/platform-bible-utils/src/string-util.ts#L338)):*
> ```XML
> export function substring(
>   string: string,
>   begin?: number | undefined,
> ```

I believe this argument is not supposed to be optional
___
*[`lib/platform-bible-utils/src/string-util.test.ts` line 27 at r1](https://reviewable.io/reviews/paranext/paranext-core/773#-Nr6ZKuEA08XcVUf5I24:-Nr6ZKuEA08XcVUf5I25:b-g5icli) ([raw file](https://github.com/paranext/paranext-core/blob/4bdb0c59cf7f12cf561a3adf320768017f2348ee/lib/platform-bible-utils/src/string-util.test.ts#L27)):*
> ```XML
> 
> const LONG_SURROGATE_PAIRS_STRING =
>   'Look𐐷At🦄All😎These😁Awesome🍕Symbols💩That🚀Are📷Represented😉By🍕Surrogate🔥Pairs💋!🌟';
> ```

Eeeeeewww 💩

**Review by rolfheij-sil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/773)* status: 30 of 39 files reviewed, 10 unresolved discussions (waiting on @tjcouch-sil)

___
*[`lib/platform-bible-utils/dist/index.d.ts` line 1018 at r1](https://reviewable.io/reviews/paranext/paranext-core/773#-Nr6PJBr38vD0lH13HJa:-Nr6ijGj00N2Fr6WCRjt:b-16v9ei) ([raw file](https://github.com/paranext/paranext-core/blob/4bdb0c59cf7f12cf561a3adf320768017f2348ee/lib/platform-bible-utils/dist/index.d.ts#L1018)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

Any idea what this is?
</blockquote></details>

Nope, no idea? Maybe resolving a potential name conflict?
Because we import this:
`length as stringzLength,`
and export this:
`export function length(string: string)`
___
*[`lib/platform-bible-utils/src/string-util.ts` line 1 at r1](https://reviewable.io/reviews/paranext/paranext-core/773#-Nr6Qb7gCJxaN75xK69M:-Nr6kKU-9AujXLr3tULe:bgzxz3v) ([raw file](https://github.com/paranext/paranext-core/blob/4bdb0c59cf7f12cf561a3adf320768017f2348ee/lib/platform-bible-utils/src/string-util.ts#L1)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

How does the generated documentation page look for these string utils? Would it benefit from having a jsdoc at the top that explains that this consists of util functions that mirror the built-in ones but work on code points? I can't remember if those get picked up in the generated docs or not, but it seems like it would be helpful if it does :)
</blockquote></details>

Where could I find this documentation page?
___
*[`lib/platform-bible-utils/src/string-util.ts` line 11 at r1](https://reviewable.io/reviews/paranext/paranext-core/773#-Nr6QAsO62iccPNRr5CF:-Nr6jWW-D8pqhtJhhkzd:b-896fix) ([raw file](https://github.com/paranext/paranext-core/blob/4bdb0c59cf7f12cf561a3adf320768017f2348ee/lib/platform-bible-utils/src/string-util.ts#L11)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

I think this needs "This function handles Unicode code points instead of UTF-16 character codes."
</blockquote></details>

Done.
___
*[`lib/platform-bible-utils/src/string-util.ts` line 14 at r1](https://reviewable.io/reviews/paranext/paranext-core/773#-Nr6PgcWCPFC1tcPY4Jo:-Nr6kSeA3B066u0sTVk-:b-g33pcj) ([raw file](https://github.com/paranext/paranext-core/blob/4bdb0c59cf7f12cf561a3adf320768017f2348ee/lib/platform-bible-utils/src/string-util.ts#L14)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

Is this the right range? I am confused about it
</blockquote></details>

Nope, it wasn't. Fixed it.
___
*[`lib/platform-bible-utils/src/string-util.ts` line 17 at r1](https://reviewable.io/reviews/paranext/paranext-core/773#-Nr6S93-0VnwNHxyv3u1:-Nr6m_q7-WM7WNfN-Ws-:bdkt1m4) ([raw file](https://github.com/paranext/paranext-core/blob/4bdb0c59cf7f12cf561a3adf320768017f2348ee/lib/platform-bible-utils/src/string-util.ts#L17)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

This file's functions use almost exclusively JSDoc syntax, but we usually use TSDoc syntax. For example, compare these JSDocs to those in `lib\platform-bible-utils\src\util.ts` which use TSDoc syntax. Sorry for the confusion. VSCode generates TSDocs when you type `/**` and hit enter above a function, so I wonder how these got to be JSDocs.

I thought VSCode offered a way to automatically transform JSDocs into TSDocs in the quick fix menu, but I'm not seeing it right now. Maybe you'll see it. I think I remember the function has the little white dots under it if the transformation is available. This screenshot shows something very similar but not the same thing:


Anyway, I don't think this breaks anything, so this isn't a demand or anything, but I do recommend changing to TSDocs since they are more concise and the types won't get out of sync.
</blockquote></details>

Fixed it, I think? 
___
*[`lib/platform-bible-utils/src/string-util.ts` line 24 at r1](https://reviewable.io/reviews/paranext/paranext-core/773#-Nr6QDI-C1pg2Mzz8aP-:-Nr6nRja5QP2xBM3SZ9I:bf0ohob) ([raw file](https://github.com/paranext/paranext-core/blob/4bdb0c59cf7f12cf561a3adf320768017f2348ee/lib/platform-bible-utils/src/string-util.ts#L24)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

I am confused about this description. Does it need some adjustment? Also I think it needs "This function handles Unicode code points instead of UTF-16 character codes."
</blockquote></details>

I think it was partially copied over from the JavaScript String library docs. I changed it now.
___
*[`lib/platform-bible-utils/src/string-util.ts` line 114 at r1](https://reviewable.io/reviews/paranext/paranext-core/773#-Nr6WMod2Unr-93qrlfG:-Nr6oNyQ5WWuO7X9Mhqp:b-886gsx) ([raw file](https://github.com/paranext/paranext-core/blob/4bdb0c59cf7f12cf561a3adf320768017f2348ee/lib/platform-bible-utils/src/string-util.ts#L114)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

Calling the default `+Infinity` was confusing to read. I didn't understand what it meant without reading the code. Maybe consider saying something along the lines of what the built-in `lastIndexOf` says: "The index at which to begin searching. If omitted, the search begins at the end of the string." and using `undefined`
</blockquote></details>

Fixed
___
*[`lib/platform-bible-utils/src/string-util.ts` line 156 at r1](https://reviewable.io/reviews/paranext/paranext-core/773#-Nr6XFteDjTN7roxZJjI:-Nr6p54x8s-hboNkExsY:b-bljk8v) ([raw file](https://github.com/paranext/paranext-core/blob/4bdb0c59cf7f12cf561a3adf320768017f2348ee/lib/platform-bible-utils/src/string-util.ts#L156)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

This JSDoc overall and especially this return statement are a bit confusing. I recommend rewording to match the built-in normalize a bit better.
</blockquote></details>

These comments are almost exact copies of the comments of the built in normalize function. What do you think is unclear, and how would you like to change it?
___
*[`lib/platform-bible-utils/src/string-util.ts` line 338 at r1](https://reviewable.io/reviews/paranext/paranext-core/773#-Nr6Z3Xa8rx6xZepiH3q:-Nr6q_Ng7q_sW0cuiHeG:b-qxz1gl) ([raw file](https://github.com/paranext/paranext-core/blob/4bdb0c59cf7f12cf561a3adf320768017f2348ee/lib/platform-bible-utils/src/string-util.ts#L338)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

I believe this argument is not supposed to be optional
</blockquote></details>

Done. Fixed
___
*[`lib/platform-bible-utils/src/string-util.test.ts` line 27 at r1](https://reviewable.io/reviews/paranext/paranext-core/773#-Nr6ZKuEA08XcVUf5I24:-Nr6qann-ux8sB7yOg-q:b-6h42rm) ([raw file](https://github.com/paranext/paranext-core/blob/4bdb0c59cf7f12cf561a3adf320768017f2348ee/lib/platform-bible-utils/src/string-util.test.ts#L27)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

Eeeeeewww 💩
</blockquote></details>

Happy Poop by Mauro Gatti on Dribbble

___
*[`extensions/src/hello-world/src/web-views/hello-world-2.web-view.tsx` line 26 at r1](https://reviewable.io/reviews/paranext/paranext-core/773#-Nr6OYgDAVCTdu1Uw3f_:-Nr6hwMz3B9GoRuJHFYE:b9cxdmw) ([raw file](https://github.com/paranext/paranext-core/blob/4bdb0c59cf7f12cf561a3adf320768017f2348ee/extensions/src/hello-world/src/web-views/hello-world-2.web-view.tsx#L26)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

Is this test code that should be removed?
</blockquote></details>

Oops GIF - Oops - Discover & Share GIFs

**Review by rolfheij-sil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/773)* status: all files reviewed, 2 unresolved discussions (waiting on @tjcouch-sil)

___
*[`lib/platform-bible-utils/dist/index.d.ts` line 1018 at r1](https://reviewable.io/reviews/paranext/paranext-core/773#-Nr6PJBr38vD0lH13HJa:-Nr7YS7K7PuYEyd_jOIq:b-oxjnbx) ([raw file](https://github.com/paranext/paranext-core/blob/4bdb0c59cf7f12cf561a3adf320768017f2348ee/lib/platform-bible-utils/dist/index.d.ts#L1018)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

Hmm is the length function not exported except here? I don't see any JSDocs here... I wonder what's the difference between this and `indexOf` for example which does get exported properly with JSDocs.
</blockquote></details>

That is very strange indeed. I will investigate.
___
*[`lib/platform-bible-utils/src/string-util.ts` line 1 at r1](https://reviewable.io/reviews/paranext/paranext-core/773#-Nr6Qb7gCJxaN75xK69M:-Nr7Y0iU6rsmlFeg8MlY:bwr0rp0) ([raw file](https://github.com/paranext/paranext-core/blob/4bdb0c59cf7f12cf561a3adf320768017f2348ee/lib/platform-bible-utils/src/string-util.ts#L1)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

You have to build it. I think there's a script in `platform-bible-utils`'s `package.json` to generate it :) Jolie probably can help more if needed.

Oh I think there may have been some miscommunication. I meant putting a jsdoc at the top of this file that describes the module, not a statement on each function. However, the statement on each function seems nice as well :) probably not a huge deal to worry about the jsdoc at the top of the module now.
</blockquote></details>

Yeah I talked to Jolie about it and she tried adding a JSDoc at the top of the file and it didn't get included. So we did it this way.
___
*[`lib/platform-bible-utils/src/string-util.ts` line 17 at r1](https://reviewable.io/reviews/paranext/paranext-core/773#-Nr6S93-0VnwNHxyv3u1:-Nr7Y8iU4KwWN2h2yAve:b-ucfknh) ([raw file](https://github.com/paranext/paranext-core/blob/4bdb0c59cf7f12cf561a3adf320768017f2348ee/lib/platform-bible-utils/src/string-util.ts#L17)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

Looks great :) thanks!
</blockquote></details>

Thanks!
___
*[`lib/platform-bible-utils/src/string-util.ts` line 156 at r1](https://reviewable.io/reviews/paranext/paranext-core/773#-Nr6XFteDjTN7roxZJjI:-Nr7YQh683C9-Tf0AGrM:blyphgc) ([raw file](https://github.com/paranext/paranext-core/blob/4bdb0c59cf7f12cf561a3adf320768017f2348ee/lib/platform-bible-utils/src/string-util.ts#L156)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

Ah I see - I was looking at the TypeScript definitions:


But I see what you have is pretty much same as the mozilla documentation. I think it's fine. Sorry for red herring.
</blockquote></details>

No problem!
___
*[`lib/platform-bible-utils/src/string-util.ts` line 31 at r3](https://reviewable.io/reviews/paranext/paranext-core/773#-Nr7Ql7282BXXKtQKDvr:-Nr7YDcN7VWAkzajdsOi:bm3ng18) ([raw file](https://github.com/paranext/paranext-core/blob/a6d19784b144ff10b4b76f6f3bf70fe13a2bcd6c/lib/platform-bible-utils/src/string-util.ts#L31)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

Because this is using the stringz library's `substr`, I believe it is returning a string of a unicode code point instead of a UTF-16 code unit, right?
</blockquote></details>

Whoops. You're right.

**Review by tjcouch-sil — DISMISSED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/773)* status: all files reviewed, 1 unresolved discussion

**Review by rolfheij-sil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/773)* status: all files reviewed, 1 unresolved discussion (waiting on @tjcouch-sil)

___
*[`lib/platform-bible-utils/dist/index.d.ts` line 1018 at r1](https://reviewable.io/reviews/paranext/paranext-core/773#-Nr6PJBr38vD0lH13HJa:-NrB_MSS99fxJViMAO8Q:b-4en8wv) ([raw file](https://github.com/paranext/paranext-core/blob/4bdb0c59cf7f12cf561a3adf320768017f2348ee/lib/platform-bible-utils/dist/index.d.ts#L1018)):*
<details><summary><i>Previously, rolfheij-sil wrote…</i></summary><blockquote>

That is very strange indeed. I will investigate.
</blockquote></details>

`length` seems to be a reserved keyword or something. Changing the function name resolves the issue

**Review by tjcouch-sil — APPROVED** [review]
:lgtm:

> Reviewed 17 of 17 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/773#-:-NrBu00d5pqlBzjAFeag:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

___
*[`lib/platform-bible-utils/dist/index.d.ts` line 1018 at r1](https://reviewable.io/reviews/paranext/paranext-core/773#-Nr6PJBr38vD0lH13HJa:-NrBtijC1siYKOF-wnth:b-5hteh6) ([raw file](https://github.com/paranext/paranext-core/blob/4bdb0c59cf7f12cf561a3adf320768017f2348ee/lib/platform-bible-utils/dist/index.d.ts#L1018)):*
<details><summary><i>Previously, rolfheij-sil wrote…</i></summary><blockquote>

`length` seems to be a reserved keyword or something. Changing the function name resolves the issue
</blockquote></details>

Weird. Good idea! Thanks! :)

**Pull request merged**
