### PR TITLE
feat: implemented papi event to indicate when file watcher finished reloading extensions

### PR DESCRIPTION
**Pull request by captaincrazybro**
This change is [Reviewable](https://reviewable.io/reviews/paranext/paranext-core/1041)

### CODE REVIEW

**Review by tjcouch-sil — CHANGES_REQUESTED** [review]
The code looks good! Thanks for matching what's already there well.

What is the point of this event? We are usually pretty selective about what we expose from core, so I'd like to consider with you to see what options are available. Thanks!

> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/1041#-:-O3YsD1s1alV7hQ9j8yt:b-mwp1mb)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @captaincrazybro)

___
*[`src/extension-host/services/extension.service.ts` line 1128 at r1](https://reviewable.io/reviews/paranext/paranext-core/1041#-O3Yru1V2RtAFY-0X4Ac:-O3Yru1V2RtAFY-0X4Ad:benk4hx) ([raw file](https://github.com/paranext/paranext-core/blob/1efac974d24458cfe0829c8e4aa57d686450606b/src/extension-host/services/extension.service.ts#L1128)):*
> ```XML
> 
>     reloadFinishedEventEmitter = network.createNetworkEventEmitter<boolean>(
>       'extension-services.reloadFinished',
> ```

This should conform to the naming conventions we use like `platform.onDidReloadExtensions`. `on` indicates it's an event, and `did` indicates it is finished :)

**Review by captaincrazybro — COMMENTED** [review]
So, this was Matt's idea that I just went ahead and gave a stab at implementing. We need an event that the frontend of the marketplace extension can listen to that will tell it when all the extensions (especially the new extension that was just installed) finished loading. This is also to prevent trying to install a new extension while the extension marketplace is also in the midst of reloading. By event, I assumed it was something like the events we had already been using. There may be a better way to do this, however...

> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/1041#-:-O3Z8AmP-3BOLEL7JOIP:b-lgjfhk)* status: 0 of 1 files reviewed, 1 unresolved discussion

**Review by tjcouch-sil — DISMISSED** [review]
:lgtm: this should be fine. Thank you!

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/1041#-:-O3btpvHEwe-x-whyrcG:b74dijr)* status: all files reviewed, 1 unresolved discussion (waiting on @captaincrazybro)

**Review by captaincrazybro — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/1041)* status: all files reviewed, 1 unresolved discussion (waiting on @tjcouch-sil)

___
*[`src/extension-host/services/extension.service.ts` line 1128 at r1](https://reviewable.io/reviews/paranext/paranext-core/1041#-O3Yru1V2RtAFY-0X4Ac:-O3c3QiZBBrJG6lJl2-r:b-896fix) ([raw file](https://github.com/paranext/paranext-core/blob/1efac974d24458cfe0829c8e4aa57d686450606b/src/extension-host/services/extension.service.ts#L1128)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

This should conform to the naming conventions we use like `platform.onDidReloadExtensions`. `on` indicates it's an event, and `did` indicates it is finished :)
</blockquote></details>

Done.

**Review by tjcouch-sil — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/1041)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

___
*[`src/extension-host/services/extension.service.ts` line 1128 at r1](https://reviewable.io/reviews/paranext/paranext-core/1041#-O3Yru1V2RtAFY-0X4Ac:-O3c3i0JBE1w2B2m8VKp:b93h3vv) ([raw file](https://github.com/paranext/paranext-core/blob/1efac974d24458cfe0829c8e4aa57d686450606b/src/extension-host/services/extension.service.ts#L1128)):*
<details><summary><i>Previously, captaincrazybro (Cqptain) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

BRUH sorry I forgot to resolve this comment

**Review by tjcouch-sil — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/1041#-:-O3c3ugf3WaN7ATwYWOe:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Review by tjcouch-sil — APPROVED** [review]

**Review by jolierabideau — DISMISSED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/1041#-:-O3c473SAoVZ3N1kjGYU:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Review by tjcouch-sil — APPROVED** [review]

**Review by tjcouch-sil — DISMISSED** [review]
test

**Review by captaincrazybro — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/1041#-:-O3c4cdACbMBnAPGS2kt:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Review by tjcouch-sil — DISMISSED** [review]

**Review by tjcouch-sil — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/1041)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Review by jolierabideau — APPROVED** [review]

**Pull request merged**
