### PR TITLE
Finish shimming require & others in extension host

### PR DESCRIPTION
**Pull request by irahopkinson**
- try imports in 'evil' extension
- don't need to put require and others back since the extension host is in its own process
- replace `fetch` with `papi.fetch`
- also remove `.promise` after #202

- - -
This change is [Reviewable](https://reviewable.io/reviews/paranext/paranext-core/213)

### CODE REVIEW

**Review by tjcouch-sil — CHANGES_REQUESTED** [review]
Looks awesome! So excited to have this out of the way. It has been nagging my brain for months now. Glad it was this easy. Just one request.

> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/213#-:-NWrGxKP6IUNSgcmCV5E:be7sgu8)* status: all files reviewed, 1 unresolved discussion (waiting on @irahopkinson)

___
*[`src/extension-host/services/extension.service.ts` line 224 at r1](https://reviewable.io/reviews/paranext/paranext-core/213#-NWrEc47EXFTtKY28u_L:-NWrEc48B638vqF1XlIK:bojesdz) ([raw file](https://github.com/paranext/paranext-core/blob/2594d96ba9b0ce0b56f6366e72e3309e927636f4/src/extension-host/services/extension.service.ts#L224)):*
> ```XML
>   // Replace fetch with papi.fetch.
>   // eslint-disable-next-line no-global-assign
>   globalThis.fetch = papi.fetch;
> ```

Thanks for making this change! Cool :)

Could you please also make this change for web views so the frontend can also now use `fetch` appropriately?

Probably would just be replacing [this line](
https://github.com/paranext/paranext-core/blob/e3b33773d2232da0f21d3952154041eba58f9707/src/shared/services/web-view.service.ts#L155) with `window.fetch = papi.fetch;`

I guess filing an issue would also be ok.

**Review by irahopkinson — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/213)* status: 3 of 4 files reviewed, 1 unresolved discussion (waiting on @tjcouch-sil)

___
*[`src/extension-host/services/extension.service.ts` line 224 at r1](https://reviewable.io/reviews/paranext/paranext-core/213#-NWrEc47EXFTtKY28u_L:-NWsv5BU8jGvJFnwv88S:b-f7xsxx) ([raw file](https://github.com/paranext/paranext-core/blob/2594d96ba9b0ce0b56f6366e72e3309e927636f4/src/extension-host/services/extension.service.ts#L224)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

Thanks for making this change! Cool :)

Could you please also make this change for web views so the frontend can also now use `fetch` appropriately?

Probably would just be replacing [this line](
https://github.com/paranext/paranext-core/blob/e3b33773d2232da0f21d3952154041eba58f9707/src/shared/services/web-view.service.ts#L155) with `window.fetch = papi.fetch;`

I guess filing an issue would also be ok.
</blockquote></details>

Done. Thanks for remembering that needed changing too.

**Review by tjcouch-sil — APPROVED** [review]
:lgtm: Thanks for the hard work on this!

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/213#-:-NWsw5t-5iEcyITH3Ktq:bvh2ymi)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @irahopkinson)

___
*[`src/extension-host/services/extension.service.ts` line 224 at r1](https://reviewable.io/reviews/paranext/paranext-core/213#-NWrEc47EXFTtKY28u_L:-NWsw7wqD1LDR29DKR_G:br0erwu) ([raw file](https://github.com/paranext/paranext-core/blob/2594d96ba9b0ce0b56f6366e72e3309e927636f4/src/extension-host/services/extension.service.ts#L224)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

Done. Thanks for remembering that needed changing too.
</blockquote></details>

No prob! If you wouldn't mind, could you please temporarily change `hello-world.web-view.tsx` to use `fetch` instead of `papi.fetch`, put a breakpoint in `internet.service.ts` on line 10 inside the `papiFetch` in DevTools in the renderer, and see if it hits just to be absolutely sure the shim worked? I think it did; just want a sanity check to be certain.

**Review by irahopkinson — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/213)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @irahopkinson)

___
*[`src/extension-host/services/extension.service.ts` line 224 at r1](https://reviewable.io/reviews/paranext/paranext-core/213#-NWrEc47EXFTtKY28u_L:-NWszkSyAecLr6YBWqsw:b-relqi2) ([raw file](https://github.com/paranext/paranext-core/blob/2594d96ba9b0ce0b56f6366e72e3309e927636f4/src/extension-host/services/extension.service.ts#L224)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

No prob! If you wouldn't mind, could you please temporarily change `hello-world.web-view.tsx` to use `fetch` instead of `papi.fetch`, put a breakpoint in `internet.service.ts` on line 10 inside the `papiFetch` in DevTools in the renderer, and see if it hits just to be absolutely sure the shim worked? I think it did; just want a sanity check to be certain.
</blockquote></details>

Yep, I tried that and it stopped on the breakpoint. I checked the compiled JS and despite the source calling `fetch` the compile code still has `papi.fetch`, because of the assignment of `window.fetch = papi.fetch;`, which in hindsight should be expected.

**Review by tjcouch-sil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/213)* status: :shipit: complete! all files reviewed, all discussions resolved

___
*[`src/extension-host/services/extension.service.ts` line 224 at r1](https://reviewable.io/reviews/paranext/paranext-core/213#-NWrEc47EXFTtKY28u_L:-NWt-yrt3LFjNFJLRcLv:bqi8rbu) ([raw file](https://github.com/paranext/paranext-core/blob/2594d96ba9b0ce0b56f6366e72e3309e927636f4/src/extension-host/services/extension.service.ts#L224)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

Yep, I tried that and it stopped on the breakpoint. I checked the compiled JS and despite the source calling `fetch` the compile code still has `papi.fetch`, because of the assignment of `window.fetch = papi.fetch;`, which in hindsight should be expected.
</blockquote></details>

Hmm actually I would expect the built `hello-world.web-view.tsx` not to have `papi.fetch` in it if you removed it because the web view doesn't know that code got shimmed in. In the web view's perspective, it's just calling fetch. Do you know if it didn't build for some reason or something...?

**Pull request merged**
