### PR TITLE
Drop the I in some interface names after reviewing with Ira

### PR DESCRIPTION
**Pull request by lyonsil**
This change is [Reviewable](https://reviewable.io/reviews/paranext/paranext-core/162)

### CODE REVIEW

**Review by katherinejensen00 — APPROVED** [review]
> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/162)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @lyonsil)

**Review by irahopkinson — DISMISSED** [review]
I have one non-blocking question since it's out of scope for this PR, so ready to merge.

> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/162#-:-NTzf1ti9MOXsckH-NfN:bi53b7a)* status: all files reviewed, 1 unresolved discussion (waiting on @lyonsil)

___
*[`src/shared/utils/util.ts` line 152 at r1](https://reviewable.io/reviews/paranext/paranext-core/162#-NTzeXe31mZazk1NMWJb:-NTzeXe4229oVNhqFyjw:b-x9ehhb) ([raw file](https://github.com/paranext/paranext-core/blob/cd6cd218157b68bd68ea26cb61ce70524cf55bac/src/shared/utils/util.ts#L152)):*
> ```XML
>  * This type is basically a pointer to an object.
>  */
> export interface Container<T> {
> ```

I'm not sure this type belongs in this `util.ts` file. Having said that I'm not sure where else it might go so this is non-blocking.

**Review by katherinejensen00 — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/162)* status: all files reviewed, 1 unresolved discussion (waiting on @lyonsil)

**Review by lyonsil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/162)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @lyonsil)

___
*[`src/shared/utils/util.ts` line 152 at r1](https://reviewable.io/reviews/paranext/paranext-core/162#-NTzeXe31mZazk1NMWJb:-NTziTn62AjEE6yyrATB:bd0870g) ([raw file](https://github.com/paranext/paranext-core/blob/06a6fc1a8ac916483bee2c8224eed1f07f0824f3/src/shared/utils/util.ts#L152)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

I'm not sure this type belongs in this `util.ts` file. Having said that I'm not sure where else it might go so this is non-blocking.
</blockquote></details>

I couldn't find a better place to put it, and TJ didn't have another suggestion, so that's why it went where it did.  I can move it into it's own file if you think that's better.

**Review by irahopkinson — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/162)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @lyonsil)

**Pull request merged**
