### PR TITLE
Split Resource Viewer into a Read-only Resource Viewer and an editable Scripture Editor

### LINKED ISSUE #542: Split Resource Viewer into a Read-only Resource Viewer and an editable Scripture Editor
**User Story**
As a user, I want to view resources in read only mode so that I know they are accurate because I couldn't have accidentally changed them.

**Description**
We want to present to users the concept of "Resource" and "Project" in order to carry over the user experience from Paratext. However, the underlying data is exactly the same between the two at least right now. As such, let's make some adjustments present these concepts to users.
- [x] Rename `resource-viewer` extension to `platform-scripture-editor` or something and rename the registered things in `main.ts` like `resourceViewer.react` so they are called things like `platformScriptureEdtior.react` (though it would also be nice to have a more descriptive name)
- [x] Make two commands (currently, there is just one) and add them to the menu: Open Resource Viewer, Open Scripture Editor
  - [x] These commands should do almost the same thing for now: they should show the user a dialog asking for which project to choose then open the scripture editor web view (previously the resource viewer) with the selected project. However, depending on which command was used, there are a couple differences. There is no need to make multiple web views or extensions; just pass a boolean along or something:
    - [x] The web view title should have "Resource Viewer" or "Scripture Editor" in it
    - [x] The scripture editor should be read-only in the resource viewer version.

Note that this issue is simply setting up two different avenues to get to the shared editor for now. Once we have the ability to get project settings, we will use the setting for whether the project is editable to filter the project dialog for each command, but that is for later:

### PR DESCRIPTION
**Pull request by rolfheij-sil**
Fixes #542

- - -
This change is [Reviewable](https://reviewable.io/reviews/paranext/paranext-core/877)

### CODE REVIEW

**Review by tjcouch-sil — APPROVED** [review]
Cool! Very exciting :) thanks for doing this!

> Reviewed 76 of 76 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/877#-:-NwPee_x9194b38Xy-eh:bal4c1t)* status: all files reviewed, 2 unresolved discussions (waiting on @rolfheij-sil)

___
*[`-- commits` line 3 at r1](https://reviewable.io/reviews/paranext/paranext-core/877#-NwPclsA5kUtyUPHEmso):*
Sadly, because of how the multi-template works with subtrees and such, I think you might have to use `npm run create-extension -- platform-scripture-editor` in order to create that extension. Without doing so, I don't think you'll get updates from the template properly. It's possible it will work ok, but I don't think it will.

We can wait on this if you prefer. Maybe I can tinker around a bit when I get back to see if we can keep the folder without having to run create extension and copy the files over.
___
*[`extensions/src/platform-scripture-editor/src/types/platform-scripture-editor.d.ts` line 15 at r1](https://reviewable.io/reviews/paranext/paranext-core/877#-NwPdwNz46nSrIFVCwgE:-NwPdwO-Cy6USGsQMtRX:bvxh9ey) ([raw file](https://github.com/paranext/paranext-core/blob/23f4c274fcc83a1ec9cba4d880a48ac7760a85af/extensions/src/platform-scripture-editor/src/types/platform-scripture-editor.d.ts#L15)):*
> ```XML
>     'platformScriptureEditor.openScriptureEditor': (
>       projectId: string | undefined,
>       isReadOnly: boolean,
> ```

`isReadOnly` is not present, right? Just in the internal function if I saw that correctly
___
*[`extensions/src/platform-scripture-editor/src/types/platform-scripture-editor.d.ts` line 28 at r1](https://reviewable.io/reviews/paranext/paranext-core/877#-NwPe-suCerML1C5U2ia:-NwPe-suCerML1C5U2ib:bvxh9ey) ([raw file](https://github.com/paranext/paranext-core/blob/23f4c274fcc83a1ec9cba4d880a48ac7760a85af/extensions/src/platform-scripture-editor/src/types/platform-scripture-editor.d.ts#L28)):*
> ```XML
>     'platformScriptureEditor.openResourceViewer': (
>       projectId: string | undefined,
>       isReadOnly: boolean,
> ```

`isReadOnly` is not present, right? Just in the internal function if I saw that correctly

**Review by rolfheij-sil — COMMENTED** [review]
Thanks for reviewing!

> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/877#-:-NwPhxA8DYUeAU6xIAa5:b-yz40g0)* status: all files reviewed, 2 unresolved discussions (waiting on @tjcouch-sil)

___
*[`-- commits` line 3 at r1](https://reviewable.io/reviews/paranext/paranext-core/877#-NwPclsA5kUtyUPHEmso):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

Sadly, because of how the multi-template works with subtrees and such, I think you might have to use `npm run create-extension -- platform-scripture-editor` in order to create that extension. Without doing so, I don't think you'll get updates from the template properly. It's possible it will work ok, but I don't think it will.

We can wait on this if you prefer. Maybe I can tinker around a bit when I get back to see if we can keep the folder without having to run create extension and copy the files over.
</blockquote></details>

Okay, I'll let it be for now
___
*[`extensions/src/platform-scripture-editor/src/types/platform-scripture-editor.d.ts` line 15 at r1](https://reviewable.io/reviews/paranext/paranext-core/877#-NwPdwNz46nSrIFVCwgE:-NwPi2z174Re_A2YhN7F:b-ko7de3) ([raw file](https://github.com/paranext/paranext-core/blob/23f4c274fcc83a1ec9cba4d880a48ac7760a85af/extensions/src/platform-scripture-editor/src/types/platform-scripture-editor.d.ts#L15)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

`isReadOnly` is not present, right? Just in the internal function if I saw that correctly
</blockquote></details>

Yes, that's right. I wanted to add it in the implementation too, but since we're not using it there, ESLint complained about it, so I removed it there. But since it will be required in the future, I thought it would be okay to leave it here
___
*[`extensions/src/platform-scripture-editor/src/types/platform-scripture-editor.d.ts` line 28 at r1](https://reviewable.io/reviews/paranext/paranext-core/877#-NwPe-suCerML1C5U2ia:-NwPiODiDqyhVa3WHTdO:b-33b6k6) ([raw file](https://github.com/paranext/paranext-core/blob/23f4c274fcc83a1ec9cba4d880a48ac7760a85af/extensions/src/platform-scripture-editor/src/types/platform-scripture-editor.d.ts#L28)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

`isReadOnly` is not present, right? Just in the internal function if I saw that correctly
</blockquote></details>

See comment above

**Review by tjcouch-sil — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/877)* status: all files reviewed, 2 unresolved discussions (waiting on @rolfheij-sil)

___
*[`extensions/src/platform-scripture-editor/src/types/platform-scripture-editor.d.ts` line 15 at r1](https://reviewable.io/reviews/paranext/paranext-core/877#-NwPdwNz46nSrIFVCwgE:-NwPpd171pgYY5h0Yn92:b64ljb1) ([raw file](https://github.com/paranext/paranext-core/blob/23f4c274fcc83a1ec9cba4d880a48ac7760a85af/extensions/src/platform-scripture-editor/src/types/platform-scripture-editor.d.ts#L15)):*
<details><summary><i>Previously, rolfheij-sil wrote…</i></summary><blockquote>

Yes, that's right. I wanted to add it in the implementation too, but since we're not using it there, ESLint complained about it, so I removed it there. But since it will be required in the future, I thought it would be okay to leave it here
</blockquote></details>

If you run `openScriptureEditor`, the project you open should always be editable, and if you run `openResourceViewer`, the project you open should always be read-only, right? I don't understand why we would provide this parameter.

Also I see now that `projectId` is not listed as optional with `?`, but this command is expected to be run from the top-level menu which will not provide any parameters. I recommend making that parameter optional and removing `isReadOnly`.

**Review by rolfheij-sil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/877)* status: all files reviewed, 2 unresolved discussions (waiting on @tjcouch-sil)

___
*[`extensions/src/platform-scripture-editor/src/types/platform-scripture-editor.d.ts` line 15 at r1](https://reviewable.io/reviews/paranext/paranext-core/877#-NwPdwNz46nSrIFVCwgE:-NwQ0Rid3QLQNWXk2DF-:b-jbl7c0) ([raw file](https://github.com/paranext/paranext-core/blob/23f4c274fcc83a1ec9cba4d880a48ac7760a85af/extensions/src/platform-scripture-editor/src/types/platform-scripture-editor.d.ts#L15)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

If you run `openScriptureEditor`, the project you open should always be editable, and if you run `openResourceViewer`, the project you open should always be read-only, right? I don't understand why we would provide this parameter.

Also I see now that `projectId` is not listed as optional with `?`, but this command is expected to be run from the top-level menu which will not provide any parameters. I recommend making that parameter optional and removing `isReadOnly`.
</blockquote></details>

Ah okay. I was under the impression that the top-level menu would provide parameters in the future. I've removed it.

**Review by tjcouch-sil — APPROVED** [review]
:lgtm: thanks for all the hard work!

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/877#-:-NwQCMHbCzwISjPp2i_3:brnydxk)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

___
*[`extensions/src/platform-scripture-editor/src/types/platform-scripture-editor.d.ts` line 15 at r1](https://reviewable.io/reviews/paranext/paranext-core/877#-NwPdwNz46nSrIFVCwgE:-NwQCISI0wqKR0s4ML7u:b5na08v) ([raw file](https://github.com/paranext/paranext-core/blob/23f4c274fcc83a1ec9cba4d880a48ac7760a85af/extensions/src/platform-scripture-editor/src/types/platform-scripture-editor.d.ts#L15)):*
<details><summary><i>Previously, rolfheij-sil wrote…</i></summary><blockquote>

Ah okay. I was under the impression that the top-level menu would provide parameters in the future. I've removed it.
</blockquote></details>

Gotcha. I understand how that would be confusing :) thanks for the update!

**Pull request merged**
