### PR TITLE
paranext-core 61: Pair requests to their respective responses

### PR DESCRIPTION
**Pull request by lyonsil**
This change is [Reviewable](https://reviewable.io/reviews/paranext/paranext-core/101)

### CODE REVIEW

**Review by FoolRunning — CHANGES_REQUESTED** [review]
> Reviewed 22 of 22 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/101)* status: all files reviewed, 8 unresolved discussions (waiting on @lyonsil and @tjcouch-sil)

___
*[`c-sharp/Data/NetworkConnectorTypes.cs` line 7 at r1](https://reviewable.io/reviews/paranext/paranext-core/101#-NRIpWfA4sqzV74le9oX:-NRIpWfA4sqzV74le9oY:bbxxz2v) ([raw file](https://github.com/paranext/paranext-core/blob/9ec9e3fd6f42856e2b081c9c5b38c771efe0ead9/c-sharp/Data/NetworkConnectorTypes.cs#L7)):*
> ```Smalltalk
> 
> // **********************************************************************************************
> // NOTE: The types defined in this file should match what is defined in NetworkConnectorTypes.ts
> ```

Since you have split this file up, it no longer mimics what is in NetworkConnectorTypes.ts. I feel like this might be a downside to your refactoring. There is no longer a single location on both ends that can be searched for parity (i.e. NetworkConnectorTypes.cs and NetworkConnectorTypes.ts). The problem is that the types in both must match as much as possible so they can be serialized/deserialized properly.
___
*[`c-sharp/MessageHandlers/MessageHandlerRequestByRequestType.cs` line 38 at r1](https://reviewable.io/reviews/paranext/paranext-core/101#-NRJ80Bv8Ii8K6zU3H51:-NRJ80Bv8Ii8K6zU3H52:b-yqh6wv) ([raw file](https://github.com/paranext/paranext-core/blob/0ddff984bd75a316020313fd4d872134b327e350/c-sharp/MessageHandlers/MessageHandlerRequestByRequestType.cs#L38)):*
> ```Smalltalk
>                 else
>                     _messageSink.SendMessage(new MessageResponse(0, request.RequestType, request.RequestId, request.SenderId, response.ErrorMessage));
>             }
> ```

At the very least, I think we should log that there was a request that we didn't handle (if ``_handlersByRequestType`` doesn't contain the item). The server shouldn't be sending us requests that we didn't register to handle.
___
*[`c-sharp/Messages/MessageInitClient.cs` line 10 at r1](https://reviewable.io/reviews/paranext/paranext-core/101#-NRIs8JVEjL049qLgCMD:-NRIs8JVEjL049qLgCME:basp22q) ([raw file](https://github.com/paranext/paranext-core/blob/0ddff984bd75a316020313fd4d872134b327e350/c-sharp/Messages/MessageInitClient.cs#L10)):*
> ```Smalltalk
> public sealed class MessageInitClient : Message
> {
>     public sealed class NetworkConnectorInfo
> ```

Is there a particular reason you embedded this class inside of ``MessageInitClient``? That means that anywhere it's accessed we need to prepend ``MessageInitClient`` to it. In general, we should avoid public classes inside of another class. I think it should be moved out of this class (ideally in the same file in a region).
Also, it seems to go against our [coding standard](https://github.com/paranext/paranext/wiki/Code-Style-Guide#c-specific-guidelines) (specifically [this part](https://learn.microsoft.com/en-us/dotnet/standard/design-guidelines/nested-types) ). 
___
*[`src/shared/data/NetworkConnectorTypes.ts` line 2 at r1](https://reviewable.io/reviews/paranext/paranext-core/101#-NRIpL7-2eUG3lpEdvDx:-NRIpL7-2eUG3lpEdvDy:b-thabor) ([raw file](https://github.com/paranext/paranext-core/blob/0ddff984bd75a316020313fd4d872134b327e350/src/shared/data/NetworkConnectorTypes.ts#L2)):*
> ```XML
> // **********************************************************************************************
> // NOTE: The types defined in this file should match what is defined in NetworkConnectorTypes.cs
> ```

See my previous comment. This code comment is no longer relevant. Something should be done.
___
*[`c-sharp/MessageTransports/PapiClient.cs` line 111 at r1](https://reviewable.io/reviews/paranext/paranext-core/101#-NRIxFF_4iZdIfyVPgai:-NRIxFF_4iZdIfyVPgaj:b-u8q2i3) ([raw file](https://github.com/paranext/paranext-core/blob/0ddff984bd75a316020313fd4d872134b327e350/c-sharp/MessageTransports/PapiClient.cs#L111)):*
> ```Smalltalk
>             _clientId,
>             RequestType.RegisterRequest,
>             Interlocked.Increment(ref _nextRequestId),
> ```

This interlock shouldn't ever be needed since request registrations should only be done once at the start and awaited, but I guess it's better to be prepared.
___
*[`c-sharp/MessageTransports/PapiClient.cs` line 124 at r1](https://reviewable.io/reviews/paranext/paranext-core/101#-NRJ0a8L2Ue1PZUnwAKR:-NRJ0a8L2Ue1PZUnwAKS:bgisleu) ([raw file](https://github.com/paranext/paranext-core/blob/0ddff984bd75a316020313fd4d872134b327e350/c-sharp/MessageTransports/PapiClient.cs#L124)):*
> ```Smalltalk
>                 {
>                     var responder = _messageHandlersByMessageType[MessageType.Request];
>                     if (responder == null)
> ```

Using the indexer on a Dictionary will throw an exception if not found, it will not return null. If you want to check if it exists, you need to use ``TryGetValue()``. In this case, however, since the item is added to the dictionary in the constructor, I would remove the check for ``null`` completely since it should not ever happen.
___
*[`c-sharp/MessageTransports/PapiClient.cs` line 136 at r1](https://reviewable.io/reviews/paranext/paranext-core/101#-NRJ3St_1hORp29dPa-3:-NRJ3St_1hORp29dPa-4:b836fgb) ([raw file](https://github.com/paranext/paranext-core/blob/0ddff984bd75a316020313fd4d872134b327e350/c-sharp/MessageTransports/PapiClient.cs#L136)):*
> ```Smalltalk
>                     else
>                     {
>                         Console.Error.WriteLine("Unexpected message handler registered for MessageType.Request");
> ```

Similarly, since the handler is registered in the constructor, it had better be of the type ``MessageHandlerRequestByRequestType`` so you should just do a direct cast instead of checking it (i.e. allow it to throw an exception sooner instead of failing in another way later).
___
*[`c-sharp/MessageTransports/PapiClient.cs` line 215 at r1](https://reviewable.io/reviews/paranext/paranext-core/101#-NRJ5_GC3nAOaugTxOW7:-NRJ5_GC3nAOaugTxOW8:bdet110) ([raw file](https://github.com/paranext/paranext-core/blob/0ddff984bd75a316020313fd4d872134b327e350/c-sharp/MessageTransports/PapiClient.cs#L215)):*
> ```Smalltalk
>     /// Sends the specified message to the server
>     /// </summary>
>     public async Task SendMessage(Message message)
> ```

Why was this made public? Ideally, ``PapiClient`` should be the only thing creating ``Message``s and sending them to the server.
___
*[`c-sharp/MessageTransports/PapiClient.cs` line 220 at r1](https://reviewable.io/reviews/paranext/paranext-core/101#-NRJ4vpdDHXD9zeGHkK-:-NRJ4vpdDHXD9zeGHkK0:b93cpwr) ([raw file](https://github.com/paranext/paranext-core/blob/0ddff984bd75a316020313fd4d872134b327e350/c-sharp/MessageTransports/PapiClient.cs#L220)):*
> ```Smalltalk
>             throw new InvalidOperationException("Can not send data when the socket is closed");
> 
>         message.SenderId = _clientId;
> ```

The sender is required in the ``Message`` constructor. This should be redundant.
If wanted, this could be turned into ``Debug.Assert(message.SenderId == _clientId)`` to make sure that the messages are created correctly.

**Review by lyonsil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/101)* status: all files reviewed, 8 unresolved discussions (waiting on @FoolRunning and @tjcouch-sil)

___
*[`c-sharp/Data/NetworkConnectorTypes.cs` line 7 at r1](https://reviewable.io/reviews/paranext/paranext-core/101#-NRIpWfA4sqzV74le9oX:-NRJFR2K3kVDM7HMwryv:bcrm1rd) ([raw file](https://github.com/paranext/paranext-core/blob/9ec9e3fd6f42856e2b081c9c5b38c771efe0ead9/c-sharp/Data/NetworkConnectorTypes.cs#L7)):*
<details><summary><i>Previously, FoolRunning (Tim Steenwyk) wrote…</i></summary><blockquote>

Since you have split this file up, it no longer mimics what is in NetworkConnectorTypes.ts. I feel like this might be a downside to your refactoring. There is no longer a single location on both ends that can be searched for parity (i.e. NetworkConnectorTypes.cs and NetworkConnectorTypes.ts). The problem is that the types in both must match as much as possible so they can be serialized/deserialized properly.
</blockquote></details>

Yes, that is a downside to my refactoring.  Even if I back it out doing it was helpful for me to get a better sense of how everything fits together.  Keeping 9+ classes in a single file isn't something I've normally seen done, and it makes glancing at the file structure no longer a good parallel to understanding the class hierarchy.  It was hard for me to understand what was going on at first with multiple classes being held together like that.  Even the current arrangement isn't foolproof as there was a new message type in typescript that wasn't in C#.  It actually made it more visible to me when I broke down the file because I could more easily recognize what was in C# and what wasn't.
___
*[`c-sharp/MessageHandlers/MessageHandlerRequestByRequestType.cs` line 38 at r1](https://reviewable.io/reviews/paranext/paranext-core/101#-NRJ80Bv8Ii8K6zU3H51:-NRJHOso5zKnDapUUxEc:b-lz8h9o) ([raw file](https://github.com/paranext/paranext-core/blob/0ddff984bd75a316020313fd4d872134b327e350/c-sharp/MessageHandlers/MessageHandlerRequestByRequestType.cs#L38)):*
<details><summary><i>Previously, FoolRunning (Tim Steenwyk) wrote…</i></summary><blockquote>

At the very least, I think we should log that there was a request that we didn't handle (if ``_handlersByRequestType`` doesn't contain the item). The server shouldn't be sending us requests that we didn't register to handle.
</blockquote></details>

That is a good point.  I will make the change.
___
*[`c-sharp/Messages/MessageInitClient.cs` line 10 at r1](https://reviewable.io/reviews/paranext/paranext-core/101#-NRIs8JVEjL049qLgCMD:-NRJHqtE6oee9B8V6D5X:bspuw2f) ([raw file](https://github.com/paranext/paranext-core/blob/0ddff984bd75a316020313fd4d872134b327e350/c-sharp/Messages/MessageInitClient.cs#L10)):*
<details><summary><i>Previously, FoolRunning (Tim Steenwyk) wrote…</i></summary><blockquote>

Is there a particular reason you embedded this class inside of ``MessageInitClient``? That means that anywhere it's accessed we need to prepend ``MessageInitClient`` to it. In general, we should avoid public classes inside of another class. I think it should be moved out of this class (ideally in the same file in a region).
Also, it seems to go against our [coding standard](https://github.com/paranext/paranext/wiki/Code-Style-Guide#c-specific-guidelines) (specifically [this part](https://learn.microsoft.com/en-us/dotnet/standard/design-guidelines/nested-types) ). 
</blockquote></details>

The reason I did it was that `NetworkConnectorInfo` only ever has any meaning within this message.  It is never used in any other context.  Having said that, I will back it out.  I don't feel strongly about this, and I was focused on the one "green check" part of the guidelines (DO use nested types when the relationship between the nested type and its outer type is such that member-accessibility semantics are desirable).  There are good reasons to not do it, too.
___
*[`src/shared/data/NetworkConnectorTypes.ts` line 2 at r1](https://reviewable.io/reviews/paranext/paranext-core/101#-NRIpL7-2eUG3lpEdvDx:-NRJMk4eBsJYEm13FLSG:b-jrb4vk) ([raw file](https://github.com/paranext/paranext-core/blob/0ddff984bd75a316020313fd4d872134b327e350/src/shared/data/NetworkConnectorTypes.ts#L2)):*
<details><summary><i>Previously, FoolRunning (Tim Steenwyk) wrote…</i></summary><blockquote>

See my previous comment. This code comment is no longer relevant. Something should be done.
</blockquote></details>

Understood
___
*[`c-sharp/MessageTransports/PapiClient.cs` line 111 at r1](https://reviewable.io/reviews/paranext/paranext-core/101#-NRIxFF_4iZdIfyVPgai:-NRJIdNB0ljqiQ4GWPzT:bc0j54f) ([raw file](https://github.com/paranext/paranext-core/blob/0ddff984bd75a316020313fd4d872134b327e350/c-sharp/MessageTransports/PapiClient.cs#L111)):*
<details><summary><i>Previously, FoolRunning (Tim Steenwyk) wrote…</i></summary><blockquote>

This interlock shouldn't ever be needed since request registrations should only be done once at the start and awaited, but I guess it's better to be prepared.
</blockquote></details>

Yeah this was done in part based on questions I asked the team at Wednesday's scrum (I think).  I was trying to get a sense of what the intended use cases were/could be.  I think this is more future proofing or implying that we expect this could be used in a more dynamic way in the future when, for example, the code is used in a live website.
___
*[`c-sharp/MessageTransports/PapiClient.cs` line 124 at r1](https://reviewable.io/reviews/paranext/paranext-core/101#-NRJ0a8L2Ue1PZUnwAKR:-NRJJCgy9Deg4QtZYWt2:bke7z1x) ([raw file](https://github.com/paranext/paranext-core/blob/0ddff984bd75a316020313fd4d872134b327e350/c-sharp/MessageTransports/PapiClient.cs#L124)):*
<details><summary><i>Previously, FoolRunning (Tim Steenwyk) wrote…</i></summary><blockquote>

Using the indexer on a Dictionary will throw an exception if not found, it will not return null. If you want to check if it exists, you need to use ``TryGetValue()``. In this case, however, since the item is added to the dictionary in the constructor, I would remove the check for ``null`` completely since it should not ever happen.
</blockquote></details>

Sure, I can remove the `null` check here.
___
*[`c-sharp/MessageTransports/PapiClient.cs` line 136 at r1](https://reviewable.io/reviews/paranext/paranext-core/101#-NRJ3St_1hORp29dPa-3:-NRJK6MC22jCYJOfs8MV:b-epemxl) ([raw file](https://github.com/paranext/paranext-core/blob/0ddff984bd75a316020313fd4d872134b327e350/c-sharp/MessageTransports/PapiClient.cs#L136)):*
<details><summary><i>Previously, FoolRunning (Tim Steenwyk) wrote…</i></summary><blockquote>

Similarly, since the handler is registered in the constructor, it had better be of the type ``MessageHandlerRequestByRequestType`` so you should just do a direct cast instead of checking it (i.e. allow it to throw an exception sooner instead of failing in another way later).
</blockquote></details>

This was done with defensive coding in mind.  That is, what if someone in the future updates one part of the code and doesn't update this later?  It seems like it would be nice to allow the process to keep going.  In this case the registration will fail gracefully which seems like the desired outcome.

Having said this, this is a pretty minor thing that would be pretty obvious if it broke, so I will remove it.  
___
*[`c-sharp/MessageTransports/PapiClient.cs` line 215 at r1](https://reviewable.io/reviews/paranext/paranext-core/101#-NRJ5_GC3nAOaugTxOW7:-NRJKvsOCQ4MUhGqPV0m:b-wih7jd) ([raw file](https://github.com/paranext/paranext-core/blob/0ddff984bd75a316020313fd4d872134b327e350/c-sharp/MessageTransports/PapiClient.cs#L215)):*
<details><summary><i>Previously, FoolRunning (Tim Steenwyk) wrote…</i></summary><blockquote>

Why was this made public? Ideally, ``PapiClient`` should be the only thing creating ``Message``s and sending them to the server.
</blockquote></details>

Well this was actually pretty important in terms of trying to keep logic localized to different parts of the code.  I was trying to allow all `IMessageHandler` classes to own the logic they needed and keep them out of `PapiClient`.  Request handlers in particular need to send responses based on the messages they received.  Having said that, I'm realizing now that I could change `IMessageHandler` to return an optional Message itself, and `PapiClient` could send that message on behalf of message handlers in that case.  So I can change this back to private and get rid of `IMessageSink` at the same time.
___
*[`c-sharp/MessageTransports/PapiClient.cs` line 220 at r1](https://reviewable.io/reviews/paranext/paranext-core/101#-NRJ4vpdDHXD9zeGHkK-:-NRJM3ds9g_vadvLUKIG:bm9fmq6) ([raw file](https://github.com/paranext/paranext-core/blob/0ddff984bd75a316020313fd4d872134b327e350/c-sharp/MessageTransports/PapiClient.cs#L220)):*
<details><summary><i>Previously, FoolRunning (Tim Steenwyk) wrote…</i></summary><blockquote>

The sender is required in the ``Message`` constructor. This should be redundant.
If wanted, this could be turned into ``Debug.Assert(message.SenderId == _clientId)`` to make sure that the messages are created correctly.
</blockquote></details>

I would argue that things that create messages should not need to know the value of the client ID.  The entity that owns the client ID is `PapiClient`, and `PapiClient` really should not need to expose that to anyone else.  I actually wondered if it would be better to not include the client ID in constructors in general, but I wasn't sure if that would break JSON deserialization, so I left it as-is.  I do think it's actually the right thing for `PapiClient` to overwrite any client ID in messages before being sent, though.

**Review by FoolRunning — CHANGES_REQUESTED** [review]
> Reviewed 14 of 14 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/101)* status: all files reviewed, 1 unresolved discussion (waiting on @irahopkinson, @lyonsil, and @tjcouch-sil)

___
*[`c-sharp/Messages/MessageEvent.cs` line 28 at r2](https://reviewable.io/reviews/paranext/paranext-core/101#-NRJqHSv2SlBfcWjNpIf:-NRJqHSv2SlBfcWjNpIg:bnr26cy) ([raw file](https://github.com/paranext/paranext-core/blob/6f9323676aaf5b1eb35ab8f32ee6dcc1350b0a49/c-sharp/Messages/MessageEvent.cs#L28)):*
> ```Smalltalk
>     public override string ToString()
>     {
>         return $"Event: {EventType} from {SenderId}";
> ```

I'm guessing these changes were to try make it more in line with what is going on in the TS. However, I think this was inadequate because of the ``/** Contents of the event */  event: T;`` in the TS (see ``InternalEvent``). I think there is a task to update the C# for the changes to the TS already (or there will be), so it might be best to just revert these changes and leave updating the API to a later task.
___
*[`c-sharp/Messages/MessageInitClient.cs` line 10 at r1](https://reviewable.io/reviews/paranext/paranext-core/101#-NRIs8JVEjL049qLgCMD:-NRJo1f409JxXylns2Z5:bki8z9a) ([raw file](https://github.com/paranext/paranext-core/blob/0ddff984bd75a316020313fd4d872134b327e350/c-sharp/Messages/MessageInitClient.cs#L10)):*
<details><summary><i>Previously, lyonsil wrote…</i></summary><blockquote>

Done
</blockquote></details>

I don't prefer having the class in its own file when it feels like it belongs with ``MessageInitClient``, but that's probably just personal preference so, for now, I'll drop the suggestion to put it into the same file.
___
*[`c-sharp/Messages/MessageType.cs` line 7 at r1](https://reviewable.io/reviews/paranext/paranext-core/101#-NRJr-wy12vCRBLZG5Bv:-NRJr-wy12vCRBLZG5Bw:b-3satpl) ([raw file](https://github.com/paranext/paranext-core/blob/0ddff984bd75a316020313fd4d872134b327e350/c-sharp/Messages/MessageType.cs#L7)):*
> ```Smalltalk
> // **********************************************************************************************
> // NOTE: The types defined in this file should match what is defined in NetworkConnectorTypes.ts
> // **********************************************************************************************
> ```

I'm not sure that completely removing this comment without doing something else was best, but I'm not sure what is best at this point, so let's leave it for now.
___
*[`c-sharp/MessageTransports/PapiClient.cs` line 136 at r1](https://reviewable.io/reviews/paranext/paranext-core/101#-NRJ3St_1hORp29dPa-3:-NRJowYq8vEGUCOCFGZM:bmsb40p) ([raw file](https://github.com/paranext/paranext-core/blob/0ddff984bd75a316020313fd4d872134b327e350/c-sharp/MessageTransports/PapiClient.cs#L136)):*
<details><summary><i>Previously, lyonsil wrote…</i></summary><blockquote>

Done
</blockquote></details>

My philosophy is to fail sooner rather than have something fail later and you need to track it down. Thus, to me, it's better to have a direct cast and throw an exception when it goes wrong than just silently fail (even with a console message).
___
*[`c-sharp/MessageTransports/PapiClient.cs` line 220 at r1](https://reviewable.io/reviews/paranext/paranext-core/101#-NRJ4vpdDHXD9zeGHkK-:-NRJpOgn1r-AMl-WMpUM:b-ltxjvq) ([raw file](https://github.com/paranext/paranext-core/blob/0ddff984bd75a316020313fd4d872134b327e350/c-sharp/MessageTransports/PapiClient.cs#L220)):*
<details><summary><i>Previously, lyonsil wrote…</i></summary><blockquote>

I actually went back and removed the client ID from all the message constructors except `MessageClientConnect` and `MessageInitClient` since it is integral for the purpose of those two messages.  The other message creators shouldn't necessarily have to know client IDs ahead of creating a message.  `PapiClient` owns the connection and tracking of that ID.
</blockquote></details>

I think that's fine for now. I think it might be best at some point to make everything consistent (i.e. don't have any message creators ever have to worry about the client ID).

**Review by lyonsil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/101)* status: 22 of 24 files reviewed, 1 unresolved discussion (waiting on @FoolRunning, @irahopkinson, and @tjcouch-sil)

___
*[`c-sharp/Messages/MessageEvent.cs` line 28 at r2](https://reviewable.io/reviews/paranext/paranext-core/101#-NRJqHSv2SlBfcWjNpIf:-NRKHel49yZegIR-pf8M:btf53g0) ([raw file](https://github.com/paranext/paranext-core/blob/6f9323676aaf5b1eb35ab8f32ee6dcc1350b0a49/c-sharp/Messages/MessageEvent.cs#L28)):*
<details><summary><i>Previously, FoolRunning (Tim Steenwyk) wrote…</i></summary><blockquote>

I'm guessing these changes were to try make it more in line with what is going on in the TS. However, I think this was inadequate because of the ``/** Contents of the event */  event: T;`` in the TS (see ``InternalEvent``). I think there is a task to update the C# for the changes to the TS already (or there will be), so it might be best to just revert these changes and leave updating the API to a later task.
</blockquote></details>

I was trying to get something to at least show proper console output when events are received.  What I had before wasn't actually showing anything meaningful from inside the event.  I was basically misunderstanding what the JSON deserializer was doing.  I didn't try to align to anything in TS other than the fact that I see `eventType` exists as a field both in the code and in the payloads I've been getting.  A more thorough updating of the message is still in order. 
___
*[`c-sharp/Messages/MessageType.cs` line 7 at r1](https://reviewable.io/reviews/paranext/paranext-core/101#-NRJr-wy12vCRBLZG5Bv:-NRKOlcvC_OntAKHGLYB:b-20un9y) ([raw file](https://github.com/paranext/paranext-core/blob/0ddff984bd75a316020313fd4d872134b327e350/c-sharp/Messages/MessageType.cs#L7)):*
<details><summary><i>Previously, FoolRunning (Tim Steenwyk) wrote…</i></summary><blockquote>

I'm not sure that completely removing this comment without doing something else was best, but I'm not sure what is best at this point, so let's leave it for now.
</blockquote></details>

I just added a README.md and adjusted text in TS to try to help with this.

**Review by irahopkinson — COMMENTED** [review]
> Reviewed 8 of 22 files at r1, 14 of 14 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/101)* status: all files reviewed, 3 unresolved discussions (waiting on @FoolRunning, @lyonsil, and @tjcouch-sil)

___
*[`c-sharp/MessageHandlers/MessageHandlerRequestByRequestType.cs` line 25 at r3](https://reviewable.io/reviews/paranext/paranext-core/101#-NRVY0rPBZaui7mznttN:-NRVY0rQ-Lev3kVUCVYp:b79pyho) ([raw file](https://github.com/paranext/paranext-core/blob/b973bc1fe62de2addfaac76129cfca01f96e3725/c-sharp/MessageHandlers/MessageHandlerRequestByRequestType.cs#L25)):*
> ```Smalltalk
> 
>             var request = (MessageRequest)message;
>             if (_handlersByRequestType.TryGetValue(request.RequestType, out Func<dynamic, ResponseToRequest>? handler))
> ```

Use nominal flow (not indented by if or else) only dealing with exceptions in the `if` with no `else`, i.e:
```
            if (!_handlersByRequestType.TryGetValue(request.RequestType, out Func<dynamic, ResponseToRequest>? handler))
            {
                Console.Error.WriteLine("Unable to process unexpected request type: {0}", request.RequestType);
                return null;
            }

            var response = handler(request.Contents);
            if (response.Success)
                return new MessageResponse(request.RequestType, request.RequestId, request.SenderId, response.Contents);
            else
                return new MessageResponse(request.RequestType, request.RequestId, request.SenderId, response.ErrorMessage);
```
___
*[`c-sharp/MessageTransports/PapiClient.cs` line 213 at r3](https://reviewable.io/reviews/paranext/paranext-core/101#-NRVe2OACEiWlq2EeDfl:-NRVe2OACEiWlq2EeDfm:bhj5w9s) ([raw file](https://github.com/paranext/paranext-core/blob/b973bc1fe62de2addfaac76129cfca01f96e3725/c-sharp/MessageTransports/PapiClient.cs#L213)):*
> ```Smalltalk
>         message.SenderId = _clientId;
>         string jsonData = JsonSerializer.Serialize(message, s_serializationOptions);
>         Console.WriteLine("Sending message over websocket: {0}", jsonData);
> ```

I'm wondering if we really want to be spitting all this to the logs (also L249 below). For one it will make the logs fuller. Also we may be spitting user sensative data to the logs. We probably need to talk about how we handle this in general.

**Review by lyonsil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/101)* status: all files reviewed, 2 unresolved discussions (waiting on @irahopkinson and @tjcouch-sil)

___
*[`c-sharp/MessageHandlers/MessageHandlerRequestByRequestType.cs` line 25 at r3](https://reviewable.io/reviews/paranext/paranext-core/101#-NRVY0rPBZaui7mznttN:-NRYJPPiDQKX63MkTQwA:b-kefy5h) ([raw file](https://github.com/paranext/paranext-core/blob/b973bc1fe62de2addfaac76129cfca01f96e3725/c-sharp/MessageHandlers/MessageHandlerRequestByRequestType.cs#L25)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

Use nominal flow (not indented by if or else) only dealing with exceptions in the `if` with no `else`, i.e:
```
            if (!_handlersByRequestType.TryGetValue(request.RequestType, out Func<dynamic, ResponseToRequest>? handler))
            {
                Console.Error.WriteLine("Unable to process unexpected request type: {0}", request.RequestType);
                return null;
            }

            var response = handler(request.Contents);
            if (response.Success)
                return new MessageResponse(request.RequestType, request.RequestId, request.SenderId, response.Contents);
            else
                return new MessageResponse(request.RequestType, request.RequestId, request.SenderId, response.ErrorMessage);
```
</blockquote></details>

Sure, I will make this change.  I plan to recreate this PR on top of your C# formatting using a new branch to avoid what would be (at least for me) a painful rebase, and I will do it there.
___
*[`c-sharp/MessageTransports/PapiClient.cs` line 213 at r3](https://reviewable.io/reviews/paranext/paranext-core/101#-NRVe2OACEiWlq2EeDfl:-NRYHmv82INAVmLm-d0H:bl9s4mr) ([raw file](https://github.com/paranext/paranext-core/blob/b973bc1fe62de2addfaac76129cfca01f96e3725/c-sharp/MessageTransports/PapiClient.cs#L213)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

I'm wondering if we really want to be spitting all this to the logs (also L249 below). For one it will make the logs fuller. Also we may be spitting user sensative data to the logs. We probably need to talk about how we handle this in general.
</blockquote></details>

I found this logging super helpful from a debugging standpoint, but I agree that in the normal course of things we would not want to log this much out.  This is a prime candidate for using log levels IMO.  I would expect this to be at a level of verbosity that is not logging by default.  For example, if there are 5 levels (i.e., ERROR, WARN, INFO, DEBUG, TRACE), I could see this being DEBUG or TRACE with the default logging set to WARN (or arguably ERROR or INFO).

Until there are log levels in place or we find this spews far too much data for our own debugging, I would like to leave this here.

**Pull request closed without merging**
