### PR TITLE
feat:added customizable filter button

### PR DESCRIPTION
**Pull request by ssikande**
added customizable filter button. can change what groups to add, what labels, if the items are checkbox or radio, etc.
image

- - -
This change is [Reviewable](https://reviewable.io/reviews/paranext/paranext-core/1030)

### CODE REVIEW

**Review by jolierabideau — CHANGES_REQUESTED** [review]
I see this dropdown appears above the button in the preview, but below the button in the marketplace? Does it ever appear below the button in the preview?

> Reviewed 13 of 13 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/1030#-:-O2ypCA9AXQpihBkmyFZ:b-s477qz)* status: all files reviewed, 7 unresolved discussions (waiting on @ssikande)

___
*[`lib/platform-bible-react/src/components/advanced-components/extension-marketplace/filter-dropdown.component.tsx` line 13 at r1](https://reviewable.io/reviews/paranext/paranext-core/1030#-O2yohVd1uvP96Mn3Uf3:-O2yohVe734IWHyJyJzt:ba5g6qy) ([raw file](https://github.com/paranext/paranext-core/blob/de83affabab797f43d0e98b001d40466402eed4d/lib/platform-bible-react/src/components/advanced-components/extension-marketplace/filter-dropdown.component.tsx#L13)):*
> ```XML
> import FilterButton from './buttons/filter-button.component';
> 
> interface DropdownItem {
> ```

Can we make this a type and export it in index.ts
___
*[`lib/platform-bible-react/src/components/advanced-components/extension-marketplace/filter-dropdown.component.tsx` line 17 at r1](https://reviewable.io/reviews/paranext/paranext-core/1030#-O2ygXlk1AhkxkzxMT9m:-O2ygXlk1AhkxkzxMT9n:b6ikizm) ([raw file](https://github.com/paranext/paranext-core/blob/de83affabab797f43d0e98b001d40466402eed4d/lib/platform-bible-react/src/components/advanced-components/extension-marketplace/filter-dropdown.component.tsx#L17)):*
> ```XML
>   label: string;
>   /** The checkbox boolean value determines if the item is a checkbox or radio item. */
>   checkbox: boolean;
> ```

This prop is a little bit confusing- can we do something like this `itemType: 'check' | 'radio';` ? Then it's clear we are setting the item type instead of just saying whether or not to make it a checkbox, and we can add more types here if we need to in the future.
___
*[`lib/platform-bible-react/src/components/advanced-components/extension-marketplace/filter-dropdown.component.tsx` line 22 at r1](https://reviewable.io/reviews/paranext/paranext-core/1030#-O2yorNl9TAcNwWrYi0m:-O2yorNl9TAcNwWrYi0n:ba5g6qy) ([raw file](https://github.com/paranext/paranext-core/blob/de83affabab797f43d0e98b001d40466402eed4d/lib/platform-bible-react/src/components/advanced-components/extension-marketplace/filter-dropdown.component.tsx#L22)):*
> ```XML
> }
> 
> interface DropdownGroup {
> ```

Can we make this a type and export it in index.ts
___
*[`lib/platform-bible-react/src/components/advanced-components/extension-marketplace/filter-dropdown.component.tsx` line 29 at r1](https://reviewable.io/reviews/paranext/paranext-core/1030#-O2yjQ_d3YRtPFUOiFHd:-O2yjQ_d3YRtPFUOiFHe:bc0vojg) ([raw file](https://github.com/paranext/paranext-core/blob/de83affabab797f43d0e98b001d40466402eed4d/lib/platform-bible-react/src/components/advanced-components/extension-marketplace/filter-dropdown.component.tsx#L29)):*
> ```XML
>   label: string;
>   /** The items array contains the items that will be displayed in the dropdown group */
>   items: DropdownItem[];
> ```

Just curious- these `items` appear in the same order in the menu as they do in the dropdown, right? Same for `groups`?
___
*[`lib/platform-bible-react/src/components/advanced-components/extension-marketplace/filter-dropdown.component.tsx` line 58 at r1](https://reviewable.io/reviews/paranext/paranext-core/1030#-O2yk54_BCnI4j_IQmR6:-O2yk54a9T--03J1QKeF:b-q9jcrr) ([raw file](https://github.com/paranext/paranext-core/blob/de83affabab797f43d0e98b001d40466402eed4d/lib/platform-bible-react/src/components/advanced-components/extension-marketplace/filter-dropdown.component.tsx#L58)):*
> ```XML
>                 <div>
>                   {item.checkbox ? (
>                     <DropdownMenuCheckboxItem onClick={item.onClick}>
> ```

Does this need a `value`?
___
*[`lib/platform-bible-react/src/components/advanced-components/extension-marketplace/buttons/filter-button.component.tsx` line 8 at r1](https://reviewable.io/reviews/paranext/paranext-core/1030#-O2ykQwx6anaCOqROH5r:-O2ykQwx6anaCOqROH5s:b-k295w1) ([raw file](https://github.com/paranext/paranext-core/blob/de83affabab797f43d0e98b001d40466402eed4d/lib/platform-bible-react/src/components/advanced-components/extension-marketplace/buttons/filter-button.component.tsx#L8)):*
> ```XML
>  * The FilterButton component is a button designed for initiating filtering of data. It includes
>  * dropdown visuals for active filtering and idle states. it uses forwardRef to pass the button to
>  * the dropdown trigger asChild.
> ```

I'm confused about this part of the comment "It includes dropdown visuals for active filtering and idle states." There is also a typo it -> It
___
*[`lib/platform-bible-react/src/preview/components/advanced/marketplace-buttons.example.component.tsx` line 8 at r1](https://reviewable.io/reviews/paranext/paranext-core/1030#-O2yozxC2S8n9J8dGeSA:-O2yozxC2S8n9J8dGeSB:b5hl25i) ([raw file](https://github.com/paranext/paranext-core/blob/de83affabab797f43d0e98b001d40466402eed4d/lib/platform-bible-react/src/preview/components/advanced/marketplace-buttons.example.component.tsx#L8)):*
> ```XML
> 
> export default function MarketplaceButtonExamples() {
>   const filterItems = ['All', 'Verified', 'Experimental'];
> ```

Can this be called `publisherFilterItems` since they are just for the publisher group

**Review by ssikande — COMMENTED** [review]
its still going to show up underneath in marketplace

> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/1030#-:-O2z-DziD6MmzmK4A-8d:bluvxtq)* status: all files reviewed, 7 unresolved discussions (waiting on @jolierabideau)

___
*[`lib/platform-bible-react/src/components/advanced-components/extension-marketplace/filter-dropdown.component.tsx` line 29 at r1](https://reviewable.io/reviews/paranext/paranext-core/1030#-O2yjQ_d3YRtPFUOiFHd:-O2z-X0o1tIuh-3sJcoe:b2nign6) ([raw file](https://github.com/paranext/paranext-core/blob/de83affabab797f43d0e98b001d40466402eed4d/lib/platform-bible-react/src/components/advanced-components/extension-marketplace/filter-dropdown.component.tsx#L29)):*
<details><summary><i>Previously, jolierabideau wrote…</i></summary><blockquote>

Just curious- these `items` appear in the same order in the menu as they do in the dropdown, right? Same for `groups`?
</blockquote></details>

yes
___
*[`lib/platform-bible-react/src/components/advanced-components/extension-marketplace/filter-dropdown.component.tsx` line 58 at r1](https://reviewable.io/reviews/paranext/paranext-core/1030#-O2yk54_BCnI4j_IQmR6:-O2z-ajr6YAjEiqETE9W:bjs3vl9) ([raw file](https://github.com/paranext/paranext-core/blob/de83affabab797f43d0e98b001d40466402eed4d/lib/platform-bible-react/src/components/advanced-components/extension-marketplace/filter-dropdown.component.tsx#L58)):*
<details><summary><i>Previously, jolierabideau wrote…</i></summary><blockquote>

Does this need a `value`?
</blockquote></details>

do you mean the item.label?

**Review by jolierabideau — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/1030)* status: all files reviewed, 6 unresolved discussions (waiting on @ssikande)

___
*[`lib/platform-bible-react/src/components/advanced-components/extension-marketplace/filter-dropdown.component.tsx` line 58 at r1](https://reviewable.io/reviews/paranext/paranext-core/1030#-O2yk54_BCnI4j_IQmR6:-O2z7QUQBA5zMBKe8jnx:bfemhvh) ([raw file](https://github.com/paranext/paranext-core/blob/de83affabab797f43d0e98b001d40466402eed4d/lib/platform-bible-react/src/components/advanced-components/extension-marketplace/filter-dropdown.component.tsx#L58)):*
<details><summary><i>Previously, ssikande wrote…</i></summary><blockquote>

do you mean the item.label?
</blockquote></details>

The `DropdownRadioItem` has a value field, I didn't know if this one needed something like that too

**Review by jolierabideau — CHANGES_REQUESTED** [review]
> Reviewed 9 of 9 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/1030)* status: all files reviewed, 9 unresolved discussions (waiting on @ssikande)

___
*[`lib/platform-bible-react/src/index.ts` line 88 at r2](https://reviewable.io/reviews/paranext/paranext-core/1030#-O2z9iMlBN4h7gCVCUkh:-O2z9iMm3UT5YWCXFwsl:bkq1ds1) ([raw file](https://github.com/paranext/paranext-core/blob/87514e6c4aaadf3f1393c58b45c7091e797e2a23/lib/platform-bible-react/src/index.ts#L88)):*
> ```XML
>   DropdownItem,
>   DropdownGroup,
> } from './components/advanced-components/extension-marketplace/filter-dropdown.component';
> ```

This needs to be combined with the line to export `FilterDropdown`, we talked about that before you have to add the `type` keyword
___
*[`lib/platform-bible-react/src/index.ts` line 89 at r2](https://reviewable.io/reviews/paranext/paranext-core/1030#-O2z9TECBwy_fhzcr_ep:-O2z9TECBwy_fhzcr_eq:bgop3ye) ([raw file](https://github.com/paranext/paranext-core/blob/87514e6c4aaadf3f1393c58b45c7091e797e2a23/lib/platform-bible-react/src/index.ts#L89)):*
> ```XML
>   DropdownGroup,
> } from './components/advanced-components/extension-marketplace/filter-dropdown.component';
> export { default as DropdownMenuItemType } from './components/advanced-components/extension-marketplace/filter-dropdown.component';
> ```

This needs to be combined with the line to export `FilterDropdown` too and if you have to have a default it should be `FilterDropdown`
___
*[`lib/platform-bible-react/src/components/advanced-components/extension-marketplace/filter-dropdown.component.tsx` line 21 at r2](https://reviewable.io/reviews/paranext/paranext-core/1030#-O2z9xLlDsgfAEAVWPr2:-O2z9xLlDsgfAEAVWPr3:b-5pjw7g) ([raw file](https://github.com/paranext/paranext-core/blob/87514e6c4aaadf3f1393c58b45c7091e797e2a23/lib/platform-bible-react/src/components/advanced-components/extension-marketplace/filter-dropdown.component.tsx#L21)):*
> ```XML
>   /** The label is the text that will be displayed on the dropdown item. */
>   label: string;
>   /** The itemType determines if the item is a checkbox or radio item. */
> ```

Should be something like "... determines the DropdownMenuItem type"

**Review by jolierabideau — APPROVED** [review]
> Reviewed 7 of 7 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/1030)* status: all files reviewed, 9 unresolved discussions (waiting on @ssikande)

**Review by ssikande — COMMENTED** [review]
> Reviewed 4 of 13 files at r1, 2 of 9 files at r2, 7 of 7 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/1030)* status: all files reviewed, 9 unresolved discussions

**Review by ssikande — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/1030)* status: all files reviewed, 9 unresolved discussions (waiting on @jolierabideau)

___
*[`lib/platform-bible-react/src/index.ts` line 88 at r2](https://reviewable.io/reviews/paranext/paranext-core/1030#-O2z9iMlBN4h7gCVCUkh:-O2zJI24CdFNdK_RlKRF:b-896fix) ([raw file](https://github.com/paranext/paranext-core/blob/87514e6c4aaadf3f1393c58b45c7091e797e2a23/lib/platform-bible-react/src/index.ts#L88)):*
<details><summary><i>Previously, jolierabideau wrote…</i></summary><blockquote>

This needs to be combined with the line to export `FilterDropdown`, we talked about that before you have to add the `type` keyword
</blockquote></details>

Done.
___
*[`lib/platform-bible-react/src/index.ts` line 89 at r2](https://reviewable.io/reviews/paranext/paranext-core/1030#-O2z9TECBwy_fhzcr_ep:-O2zJHef0VnQppa_7krk:b-896fix) ([raw file](https://github.com/paranext/paranext-core/blob/87514e6c4aaadf3f1393c58b45c7091e797e2a23/lib/platform-bible-react/src/index.ts#L89)):*
<details><summary><i>Previously, jolierabideau wrote…</i></summary><blockquote>

This needs to be combined with the line to export `FilterDropdown` too and if you have to have a default it should be `FilterDropdown`
</blockquote></details>

Done.
___
*[`lib/platform-bible-react/src/components/advanced-components/extension-marketplace/filter-dropdown.component.tsx` line 13 at r1](https://reviewable.io/reviews/paranext/paranext-core/1030#-O2yohVd1uvP96Mn3Uf3:-O2zJGjl1wn37lkozm94:b-896fix) ([raw file](https://github.com/paranext/paranext-core/blob/de83affabab797f43d0e98b001d40466402eed4d/lib/platform-bible-react/src/components/advanced-components/extension-marketplace/filter-dropdown.component.tsx#L13)):*
<details><summary><i>Previously, jolierabideau wrote…</i></summary><blockquote>

Can we make this a type and export it in index.ts
</blockquote></details>

Done.
___
*[`lib/platform-bible-react/src/components/advanced-components/extension-marketplace/filter-dropdown.component.tsx` line 17 at r1](https://reviewable.io/reviews/paranext/paranext-core/1030#-O2ygXlk1AhkxkzxMT9m:-O2zJJsUAxGXRncNJP69:b-896fix) ([raw file](https://github.com/paranext/paranext-core/blob/de83affabab797f43d0e98b001d40466402eed4d/lib/platform-bible-react/src/components/advanced-components/extension-marketplace/filter-dropdown.component.tsx#L17)):*
<details><summary><i>Previously, jolierabideau wrote…</i></summary><blockquote>

This prop is a little bit confusing- can we do something like this `itemType: 'check' | 'radio';` ? Then it's clear we are setting the item type instead of just saying whether or not to make it a checkbox, and we can add more types here if we need to in the future.
</blockquote></details>

Done.
___
*[`lib/platform-bible-react/src/components/advanced-components/extension-marketplace/filter-dropdown.component.tsx` line 22 at r1](https://reviewable.io/reviews/paranext/paranext-core/1030#-O2yorNl9TAcNwWrYi0m:-O2zJKLA91_-lyY_1hT4:b-896fix) ([raw file](https://github.com/paranext/paranext-core/blob/de83affabab797f43d0e98b001d40466402eed4d/lib/platform-bible-react/src/components/advanced-components/extension-marketplace/filter-dropdown.component.tsx#L22)):*
<details><summary><i>Previously, jolierabideau wrote…</i></summary><blockquote>

Can we make this a type and export it in index.ts
</blockquote></details>

Done.
___
*[`lib/platform-bible-react/src/components/advanced-components/extension-marketplace/filter-dropdown.component.tsx` line 58 at r1](https://reviewable.io/reviews/paranext/paranext-core/1030#-O2yk54_BCnI4j_IQmR6:-O2zJKrh2jPgJaWnwls0:b-896fix) ([raw file](https://github.com/paranext/paranext-core/blob/de83affabab797f43d0e98b001d40466402eed4d/lib/platform-bible-react/src/components/advanced-components/extension-marketplace/filter-dropdown.component.tsx#L58)):*
<details><summary><i>Previously, jolierabideau wrote…</i></summary><blockquote>

The `DropdownRadioItem` has a value field, I didn't know if this one needed something like that too
</blockquote></details>

Done.
___
*[`lib/platform-bible-react/src/components/advanced-components/extension-marketplace/filter-dropdown.component.tsx` line 21 at r2](https://reviewable.io/reviews/paranext/paranext-core/1030#-O2z9xLlDsgfAEAVWPr2:-O2zJJa-Eb7WOGtKcSRO:b-896fix) ([raw file](https://github.com/paranext/paranext-core/blob/87514e6c4aaadf3f1393c58b45c7091e797e2a23/lib/platform-bible-react/src/components/advanced-components/extension-marketplace/filter-dropdown.component.tsx#L21)):*
<details><summary><i>Previously, jolierabideau wrote…</i></summary><blockquote>

Should be something like "... determines the DropdownMenuItem type"
</blockquote></details>

Done.
___
*[`lib/platform-bible-react/src/components/advanced-components/extension-marketplace/buttons/filter-button.component.tsx` line 8 at r1](https://reviewable.io/reviews/paranext/paranext-core/1030#-O2ykQwx6anaCOqROH5r:-O2zJLK96sXgezDad3qZ:b-896fix) ([raw file](https://github.com/paranext/paranext-core/blob/de83affabab797f43d0e98b001d40466402eed4d/lib/platform-bible-react/src/components/advanced-components/extension-marketplace/buttons/filter-button.component.tsx#L8)):*
<details><summary><i>Previously, jolierabideau wrote…</i></summary><blockquote>

I'm confused about this part of the comment "It includes dropdown visuals for active filtering and idle states." There is also a typo it -> It
</blockquote></details>

Done.
___
*[`lib/platform-bible-react/src/preview/components/advanced/marketplace-buttons.example.component.tsx` line 8 at r1](https://reviewable.io/reviews/paranext/paranext-core/1030#-O2yozxC2S8n9J8dGeSA:-O2zJLwS7sSG_2JTGQCS:b-896fix) ([raw file](https://github.com/paranext/paranext-core/blob/de83affabab797f43d0e98b001d40466402eed4d/lib/platform-bible-react/src/preview/components/advanced/marketplace-buttons.example.component.tsx#L8)):*
<details><summary><i>Previously, jolierabideau wrote…</i></summary><blockquote>

Can this be called `publisherFilterItems` since they are just for the publisher group
</blockquote></details>

Done.

**Review by jolierabideau — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/1030)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Pull request merged**
