### PR TITLE
Show Live Check Results

### PR DESCRIPTION
**Pull request by rolfheij-sil**
The Check Results web view can be opened from the context menu of the Scripture Editor (the button was already there)
image

The title bar now shows the number of check results
image

Note: When dealing with larger amounts of checks, some ghost data seems to get stuck in the results viewer.
In the screenshot below you can see that only the RepeatedWord check is enabled, but a number of `Punctuation missing` results are still shown at the top of the table

image

This change is [Reviewable](https://reviewable.io/reviews/paranext/paranext-core/1114)

### CODE REVIEW

**Review by tjcouch-sil — CHANGES_REQUESTED** [review]
Wow! Exciting :) just a few things here and there.

> Reviewed 9 of 10 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/1114#-:-O68GG4z-CXm7aAGCSvj:b7h6n76)* status: all files reviewed, 8 unresolved discussions (waiting on @rolfheij-sil)

___
*[`extensions/src/platform-scripture/src/checking-results-list.web-view.tsx` line 38 at r2](https://reviewable.io/reviews/paranext/paranext-core/1114#-O6841djBS5RwtYglgUI:-O6841djBS5RwtYglgUJ:b46ocg1) ([raw file](https://github.com/paranext/paranext-core/blob/5d4d98e06269433c983f8ac9cd035609d503ca1f/extensions/src/platform-scripture/src/checking-results-list.web-view.tsx#L38)):*
> ```XML
>     let resultsSet = resultsSets.find((newSource) => newSource.source.id === checkResult.checkId);
>     if (!resultsSet) {
>       const checkId = checkResult.checkId ?? 'Unspecified Source ID';
> ```

Does this "Unspecified Source ID" need to be localized (or maybe more accurately "internationalized", but I dunno haha)? Genuinely asking - I haven't read enough to figure out if this displays anywhere
___
*[`extensions/src/platform-scripture/src/checking-results-list.web-view.tsx` line 41 at r2](https://reviewable.io/reviews/paranext/paranext-core/1114#-O6845CA8I2vJN9gBG2m:-O6845CA8I2vJN9gBG2n:buooesf) ([raw file](https://github.com/paranext/paranext-core/blob/5d4d98e06269433c983f8ac9cd035609d503ca1f/extensions/src/platform-scripture/src/checking-results-list.web-view.tsx#L41)):*
> ```XML
>       const checkDescription =
>         availableChecks.find((check) => check.checkId === checkResult.checkId)?.checkDescription ??
>         'Unspecified Source Name';
> ```

Same as above; does this "Unspecified Source Name" need to be localized?
___
*[`extensions/src/platform-scripture/src/checking-results-list.web-view.tsx` line 97 at r2](https://reviewable.io/reviews/paranext/paranext-core/1114#-O687ujOEX0joMxeSbHo:-O687ujOEX0joMxeSbHp:bdg3z1f) ([raw file](https://github.com/paranext/paranext-core/blob/5d4d98e06269433c983f8ac9cd035609d503ca1f/extensions/src/platform-scripture/src/checking-results-list.web-view.tsx#L97)):*
> ```XML
> 
>   useEffect(() => {
>     const updateTitle = async () => {
> ```

Since you're running async stuff here and interacting with react-related stuff after awaiting the promise, you'll probably want to make sure you don't run the stuff after the await if the component gets unmounted. You can do this by adding a boolean (start at true) tracking if the promise should be active, then in the callback you return to `useEffect` (the unsubscriber for the `useEffect`), you set the boolean to false. Then after your await you check the boolean and return if it's false. You can see an example in `promiseIsCurrent` in the `usePromise` hook source code.

Disclaimer: In this case, you're running `updateWebViewDefinition` (which interacts with some other React components but doesn't directly set something on this component) after awaiting a promise, not doing something React very strictly does not like to do after unmounting like setting a state on this component (React throws an error if you try to set a state after a component is unmounted). I dunno if this absolutely necessarily cannot be run after unmount without an error like setting a state would produce an error, but it seems it would probably not be a good thing to try to update a web view that has been removed... :) I'd say it is indeterminate and risky
___
*[`extensions/src/platform-scripture/src/checking-results-list.web-view.tsx` line 103 at r2](https://reviewable.io/reviews/paranext/paranext-core/1114#-O687U688UhYQayu-ION:-O687U688UhYQayu-IOO:bwi7wb6) ([raw file](https://github.com/paranext/paranext-core/blob/5d4d98e06269433c983f8ac9cd035609d503ca1f/extensions/src/platform-scripture/src/checking-results-list.web-view.tsx#L103)):*
> ```XML
>         }),
>         {
>           resultsCount: checkResults.length,
> ```

I think these results need to be filtered by project id since this web view is check results for one particular project, right (and in other places in this component where appropriate)? If so, I might recommend changing to use the web view definition property `projectId` instead of web view state `projectName`, then you can use it here and also get the appropriate `projectName` for the `projectId` using `usePromise`.
___
*[`extensions/src/platform-scripture/src/checking-results-list.web-view.tsx` line 113 at r2](https://reviewable.io/reviews/paranext/paranext-core/1114#-O68C3w7EvkKaqbUmE9_:-O68C3w7EvkKaqbUmE9a:b5le01k) ([raw file](https://github.com/paranext/paranext-core/blob/5d4d98e06269433c983f8ac9cd035609d503ca1f/extensions/src/platform-scripture/src/checking-results-list.web-view.tsx#L113)):*
> ```XML
>     };
> 
>     updateTitle().catch((error) =>
> ```

I'm sad to say it because I kinda like this syntax sometimes (this is one of those times), but we have decided not to use promise chaining syntax but rather to use `async/await` syntax. So the way you would catch an error here would be to add a `try/catch` block inside `updateTitle` that encompasses the entire contents of the function.
___
*[`extensions/src/platform-scripture/src/checking-results-list.web-view-provider.ts` line 75 at r2](https://reviewable.io/reviews/paranext/paranext-core/1114#-O68DKmy1ilJnMXPbcVB:-O68DKmy1ilJnMXPbcVC:bv8u3z5) ([raw file](https://github.com/paranext/paranext-core/blob/5d4d98e06269433c983f8ac9cd035609d503ca1f/extensions/src/platform-scripture/src/checking-results-list.web-view-provider.ts#L75)):*
> ```XML
>         ...savedWebView.state,
>         projectName,
>         projectId,
> ```

I know you didn't make this, but it is probably best to pull `projectId` out to being part of the web view definition itself, not in the state. If you end up making the change I was recommending earlier (or just using `projectId` in general), I'd suggest doing this instead of using web view state for `projectId`. I appreciate this isn't your code, though, so I understand if you don't want to do it right now if you don't make the change in the other file.
___
*[`extensions/src/platform-scripture/src/configure-checks.web-view.tsx` line 29 at r2](https://reviewable.io/reviews/paranext/paranext-core/1114#-O68EdseE5LDzy8MC4kH:-O68EdseE5LDzy8MC4kI:bl4zk5y) ([raw file](https://github.com/paranext/paranext-core/blob/5d4d98e06269433c983f8ac9cd035609d503ca1f/extensions/src/platform-scripture/src/configure-checks.web-view.tsx#L29)):*
> ```XML
> };
> 
> global.webViewComponent = function InventoryWebView({ useWebViewState }: WebViewProps) {
> ```

Oh just noticed the name of this component `InventoryWebView`. Maybe a copy/paste error from a previous PR? Would you mind changing please? :grimacing: sorry
___
*[`extensions/src/platform-scripture/src/configure-checks.web-view.tsx` line 30 at r2](https://reviewable.io/reviews/paranext/paranext-core/1114#-O68ELOM6RMmHBHxGUs0:-O68ELOM6RMmHBHxGUs1:b-blz66m) ([raw file](https://github.com/paranext/paranext-core/blob/5d4d98e06269433c983f8ac9cd035609d503ca1f/extensions/src/platform-scripture/src/configure-checks.web-view.tsx#L30)):*
> ```XML
> 
> global.webViewComponent = function InventoryWebView({ useWebViewState }: WebViewProps) {
>   const [projectId] = useWebViewState('projectId', '');
> ```

I'd also recommend switching this `projectId` to be from the `WebViewProps` as part of the web view definition instead of being a web view state. Then you can add a menu item that opens the run checks web view (or whatever we're calling it) from this web view too! :)

**Review by tjcouch-sil — CHANGES_REQUESTED** [review]
Looking good! Thanks for the adjustments :) just a few more details

> Reviewed 7 of 7 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/1114#-:-O6Mit8m41Fc5azL-pje:bfbk1ay)* status: all files reviewed, 6 unresolved discussions (waiting on @rolfheij-sil)

___
*[`extensions/src/platform-scripture/src/checking-results-list.web-view-provider.ts` line 75 at r2](https://reviewable.io/reviews/paranext/paranext-core/1114#-O68DKmy1ilJnMXPbcVB:-O6MhruA075aKlmBhwy1:b-7kl0el) ([raw file](https://github.com/paranext/paranext-core/blob/5d4d98e06269433c983f8ac9cd035609d503ca1f/extensions/src/platform-scripture/src/checking-results-list.web-view-provider.ts#L75)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

I know you didn't make this, but it is probably best to pull `projectId` out to being part of the web view definition itself, not in the state. If you end up making the change I was recommending earlier (or just using `projectId` in general), I'd suggest doing this instead of using web view state for `projectId`. I appreciate this isn't your code, though, so I understand if you don't want to do it right now if you don't make the change in the other file.
</blockquote></details>

Thanks for the adjustments!
___
*[`extensions/src/platform-scripture/src/checking-results-list.web-view-provider.ts` line 34 at r3](https://reviewable.io/reviews/paranext/paranext-core/1114#-O6Mhbal7sB14FVyTklc:-O6Mhbal7sB14FVyTkld:b-cyoa0q) ([raw file](https://github.com/paranext/paranext-core/blob/ae654bc1d5c76a7619ab3ed08562a92fff81ecd1/extensions/src/platform-scripture/src/checking-results-list.web-view-provider.ts#L34)):*
> ```XML
>       getWebViewOptions.projectId ||
>       // eslint-disable-next-line no-type-assertion/no-type-assertion
>       (savedWebView.state?.projectId as string) ||
> ```

Now you want to pull `projectId` out of `savedWebView` instead of out of its `state`
___
*[`extensions/src/platform-scripture/src/checking-results-list.web-view-provider.ts` line 69 at r3](https://reviewable.io/reviews/paranext/paranext-core/1114#-O6MhiMkC7xHe26YXHeV:-O6MhiMkC7xHe26YXHeW:b6s56os) ([raw file](https://github.com/paranext/paranext-core/blob/ae654bc1d5c76a7619ab3ed08562a92fff81ecd1/extensions/src/platform-scripture/src/checking-results-list.web-view-provider.ts#L69)):*
> ```XML
>     return {
>       title,
>       ...savedWebView,
> ```

Now you want to add `projectId` in here, right? After `savedWebView` somewhere but not inside `state`
___
*[`extensions/src/platform-scripture/src/configure-checks.web-view-provider.ts` line 29 at r3](https://reviewable.io/reviews/paranext/paranext-core/1114#-O6MiTHo9iMnJwXOYxfO:-O6MiTHo9iMnJwXOYxfP:b-cyoa0q) ([raw file](https://github.com/paranext/paranext-core/blob/ae654bc1d5c76a7619ab3ed08562a92fff81ecd1/extensions/src/platform-scripture/src/configure-checks.web-view-provider.ts#L29)):*
> ```XML
>       getWebViewOptions.projectId ||
>       // eslint-disable-next-line no-type-assertion/no-type-assertion
>       (savedWebView.state?.projectId as string) ||
> ```

Now you want to pull `projectId` out of `savedWebView` instead of out of its `state`
___
*[`extensions/src/platform-scripture/src/configure-checks.web-view-provider.ts` line 50 at r3](https://reviewable.io/reviews/paranext/paranext-core/1114#-O6MiZI93jcZs7PFvAqt:-O6MiZI93jcZs7PFvAqu:btf3vqi) ([raw file](https://github.com/paranext/paranext-core/blob/ae654bc1d5c76a7619ab3ed08562a92fff81ecd1/extensions/src/platform-scripture/src/configure-checks.web-view-provider.ts#L50)):*
> ```XML
>     return {
>       title,
>       projectId,
> ```

I believe you want `projectId` here to be after `...savedWebView` so the new `projectId` (if it changed) will be used, right?

**Review by rolfheij-sil — COMMENTED** [review]
Thanks!

> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/1114#-:-O6MRtLi5btFTmMddIeE:b-ucfknh)* status: 11 of 13 files reviewed, 6 unresolved discussions (waiting on @tjcouch-sil)

___
*[`extensions/src/platform-scripture/src/checking-results-list.web-view.tsx` line 38 at r2](https://reviewable.io/reviews/paranext/paranext-core/1114#-O6841djBS5RwtYglgUI:-O6MBfK600YwoO6HRnpe:bqt47k1) ([raw file](https://github.com/paranext/paranext-core/blob/5d4d98e06269433c983f8ac9cd035609d503ca1f/extensions/src/platform-scripture/src/checking-results-list.web-view.tsx#L38)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

Does this "Unspecified Source ID" need to be localized (or maybe more accurately "internationalized", but I dunno haha)? Genuinely asking - I haven't read enough to figure out if this displays anywhere
</blockquote></details>

Yep, good call. The `checkDescription` will display in the results list if the result are provided by a check that doesn't have a proper description
___
*[`extensions/src/platform-scripture/src/checking-results-list.web-view.tsx` line 41 at r2](https://reviewable.io/reviews/paranext/paranext-core/1114#-O6845CA8I2vJN9gBG2m:-O6MFYbY4w7azesVmKai:bt2vr1b) ([raw file](https://github.com/paranext/paranext-core/blob/5d4d98e06269433c983f8ac9cd035609d503ca1f/extensions/src/platform-scripture/src/checking-results-list.web-view.tsx#L41)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

Same as above; does this "Unspecified Source Name" need to be localized?
</blockquote></details>

Fixed.
___
*[`extensions/src/platform-scripture/src/checking-results-list.web-view.tsx` line 97 at r2](https://reviewable.io/reviews/paranext/paranext-core/1114#-O687ujOEX0joMxeSbHo:-O6MGhKj32oOEGJno8qF:b4rce9d) ([raw file](https://github.com/paranext/paranext-core/blob/5d4d98e06269433c983f8ac9cd035609d503ca1f/extensions/src/platform-scripture/src/checking-results-list.web-view.tsx#L97)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

Since you're running async stuff here and interacting with react-related stuff after awaiting the promise, you'll probably want to make sure you don't run the stuff after the await if the component gets unmounted. You can do this by adding a boolean (start at true) tracking if the promise should be active, then in the callback you return to `useEffect` (the unsubscriber for the `useEffect`), you set the boolean to false. Then after your await you check the boolean and return if it's false. You can see an example in `promiseIsCurrent` in the `usePromise` hook source code.

Disclaimer: In this case, you're running `updateWebViewDefinition` (which interacts with some other React components but doesn't directly set something on this component) after awaiting a promise, not doing something React very strictly does not like to do after unmounting like setting a state on this component (React throws an error if you try to set a state after a component is unmounted). I dunno if this absolutely necessarily cannot be run after unmount without an error like setting a state would produce an error, but it seems it would probably not be a good thing to try to update a web view that has been removed... :) I'd say it is indeterminate and risky
</blockquote></details>

Thanks for explaining. Fixed it.
___
*[`extensions/src/platform-scripture/src/checking-results-list.web-view.tsx` line 103 at r2](https://reviewable.io/reviews/paranext/paranext-core/1114#-O687U688UhYQayu-ION:-O6MKtVW4AYYSACuOn8E:b-h990k8) ([raw file](https://github.com/paranext/paranext-core/blob/5d4d98e06269433c983f8ac9cd035609d503ca1f/extensions/src/platform-scripture/src/checking-results-list.web-view.tsx#L103)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

I think these results need to be filtered by project id since this web view is check results for one particular project, right (and in other places in this component where appropriate)? If so, I might recommend changing to use the web view definition property `projectId` instead of web view state `projectName`, then you can use it here and also get the appropriate `projectName` for the `projectId` using `usePromise`.
</blockquote></details>

Good call. Fixed.
___
*[`extensions/src/platform-scripture/src/checking-results-list.web-view.tsx` line 113 at r2](https://reviewable.io/reviews/paranext/paranext-core/1114#-O68C3w7EvkKaqbUmE9_:-O6MLfcLBFZrs93mOkcx:b-bld6gf) ([raw file](https://github.com/paranext/paranext-core/blob/5d4d98e06269433c983f8ac9cd035609d503ca1f/extensions/src/platform-scripture/src/checking-results-list.web-view.tsx#L113)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

I'm sad to say it because I kinda like this syntax sometimes (this is one of those times), but we have decided not to use promise chaining syntax but rather to use `async/await` syntax. So the way you would catch an error here would be to add a `try/catch` block inside `updateTitle` that encompasses the entire contents of the function.
</blockquote></details>

Bummer. Fixed.
___
*[`extensions/src/platform-scripture/src/checking-results-list.web-view-provider.ts` line 75 at r2](https://reviewable.io/reviews/paranext/paranext-core/1114#-O68DKmy1ilJnMXPbcVB:-O6MRd23B-ip5cru7coi:b15bpsj) ([raw file](https://github.com/paranext/paranext-core/blob/5d4d98e06269433c983f8ac9cd035609d503ca1f/extensions/src/platform-scripture/src/checking-results-list.web-view-provider.ts#L75)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

I know you didn't make this, but it is probably best to pull `projectId` out to being part of the web view definition itself, not in the state. If you end up making the change I was recommending earlier (or just using `projectId` in general), I'd suggest doing this instead of using web view state for `projectId`. I appreciate this isn't your code, though, so I understand if you don't want to do it right now if you don't make the change in the other file.
</blockquote></details>

Fixed it :)
___
*[`extensions/src/platform-scripture/src/configure-checks.web-view.tsx` line 29 at r2](https://reviewable.io/reviews/paranext/paranext-core/1114#-O68EdseE5LDzy8MC4kH:-O6MO1G286NiW4XmR6-N:b-t8fyss) ([raw file](https://github.com/paranext/paranext-core/blob/5d4d98e06269433c983f8ac9cd035609d503ca1f/extensions/src/platform-scripture/src/configure-checks.web-view.tsx#L29)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

Oh just noticed the name of this component `InventoryWebView`. Maybe a copy/paste error from a previous PR? Would you mind changing please? :grimacing: sorry
</blockquote></details>

Oops. Fixed.
___
*[`extensions/src/platform-scripture/src/configure-checks.web-view.tsx` line 30 at r2](https://reviewable.io/reviews/paranext/paranext-core/1114#-O68ELOM6RMmHBHxGUs0:-O6MReTq63VDotgAHfFK:bge73gm) ([raw file](https://github.com/paranext/paranext-core/blob/5d4d98e06269433c983f8ac9cd035609d503ca1f/extensions/src/platform-scripture/src/configure-checks.web-view.tsx#L30)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

I'd also recommend switching this `projectId` to be from the `WebViewProps` as part of the web view definition instead of being a web view state. Then you can add a menu item that opens the run checks web view (or whatever we're calling it) from this web view too! :)
</blockquote></details>

Fixed. I don't really get the idea in the second half of your comment though.

**Review by rolfheij-sil — COMMENTED** [review]
Thanks for reviewing! Sorry, I pushed half of my changes first, then you reviewed, then I pushed my responses to this review, and then I pushed the other half of my changes, and now I'm pushing more responses and more changes. It's a but of a mess :joy: 

> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/1114#-:-O6MmXkVDbx9_HM7iKXd:b7ngbs8)* status: 11 of 13 files reviewed, 6 unresolved discussions (waiting on @tjcouch-sil)

___
*[`extensions/src/platform-scripture/src/checking-results-list.web-view-provider.ts` line 34 at r3](https://reviewable.io/reviews/paranext/paranext-core/1114#-O6Mhbal7sB14FVyTklc:-O6MmNQT6fyn1nb7IHJ7:b-896fix) ([raw file](https://github.com/paranext/paranext-core/blob/ae654bc1d5c76a7619ab3ed08562a92fff81ecd1/extensions/src/platform-scripture/src/checking-results-list.web-view-provider.ts#L34)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

Now you want to pull `projectId` out of `savedWebView` instead of out of its `state`
</blockquote></details>

Done.
___
*[`extensions/src/platform-scripture/src/checking-results-list.web-view-provider.ts` line 69 at r3](https://reviewable.io/reviews/paranext/paranext-core/1114#-O6MhiMkC7xHe26YXHeV:-O6MmPjd4kYfKGfX7ilX:bim01g) ([raw file](https://github.com/paranext/paranext-core/blob/ae654bc1d5c76a7619ab3ed08562a92fff81ecd1/extensions/src/platform-scripture/src/checking-results-list.web-view-provider.ts#L69)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

Now you want to add `projectId` in here, right? After `savedWebView` somewhere but not inside `state`
</blockquote></details>

Sorry I committed that change but didn't push it yet. Fixed
___
*[`extensions/src/platform-scripture/src/configure-checks.web-view-provider.ts` line 29 at r3](https://reviewable.io/reviews/paranext/paranext-core/1114#-O6MiTHo9iMnJwXOYxfO:-O6MmTlKAIWkUtO5QSIk:b-896fix) ([raw file](https://github.com/paranext/paranext-core/blob/ae654bc1d5c76a7619ab3ed08562a92fff81ecd1/extensions/src/platform-scripture/src/configure-checks.web-view-provider.ts#L29)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

Now you want to pull `projectId` out of `savedWebView` instead of out of its `state`
</blockquote></details>

Done.
___
*[`extensions/src/platform-scripture/src/configure-checks.web-view-provider.ts` line 50 at r3](https://reviewable.io/reviews/paranext/paranext-core/1114#-O6MiZI93jcZs7PFvAqt:-O6MmVN_A3Z1gJGq6Ni0:b-haj1sa) ([raw file](https://github.com/paranext/paranext-core/blob/ae654bc1d5c76a7619ab3ed08562a92fff81ecd1/extensions/src/platform-scripture/src/configure-checks.web-view-provider.ts#L50)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

I believe you want `projectId` here to be after `...savedWebView` so the new `projectId` (if it changed) will be used, right?
</blockquote></details>

Same as above. Done.

**Review by tjcouch-sil — COMMENTED** [review]
Didn't see a few fixes, but I did see most adjustments you mentioned :) thanks!

> Reviewed 8 of 8 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/1114#-:-O6MwWdF2P_UAP7mtVvO:bw2bh3i)* status: all files reviewed, 4 unresolved discussions (waiting on @rolfheij-sil)

___
*[`extensions/src/platform-scripture/src/configure-checks.web-view.tsx` line 30 at r2](https://reviewable.io/reviews/paranext/paranext-core/1114#-O68ELOM6RMmHBHxGUs0:-O6Mv_jUAN60DOu0Hjuo:bsfmmw6) ([raw file](https://github.com/paranext/paranext-core/blob/5d4d98e06269433c983f8ac9cd035609d503ca1f/extensions/src/platform-scripture/src/configure-checks.web-view.tsx#L30)):*
<details><summary><i>Previously, rolfheij-sil (Rolf Heij) wrote…</i></summary><blockquote>

Fixed. I don't really get the idea in the second half of your comment though.
</blockquote></details>

I assumed there was a web view menu item on the Scripture editor that lets you run a command to open the "run checks" web view with the project opened in the Scripture editor. Now that you're using `projectId` the same way here, you can also add a menu item to this web view menu that runs the same command to open the "run checks" web view with the project id opened in this web view :)

**Review by rolfheij-sil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/1114)* status: all files reviewed, 3 unresolved discussions (waiting on @tjcouch-sil)

___
*[`extensions/src/platform-scripture/src/configure-checks.web-view.tsx` line 30 at r2](https://reviewable.io/reviews/paranext/paranext-core/1114#-O68ELOM6RMmHBHxGUs0:-O6N5bpM6xxtpKSzl_FS:bqo6yd9) ([raw file](https://github.com/paranext/paranext-core/blob/5d4d98e06269433c983f8ac9cd035609d503ca1f/extensions/src/platform-scripture/src/configure-checks.web-view.tsx#L30)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

I assumed there was a web view menu item on the Scripture editor that lets you run a command to open the "run checks" web view with the project opened in the Scripture editor. Now that you're using `projectId` the same way here, you can also add a menu item to this web view menu that runs the same command to open the "run checks" web view with the project id opened in this web view :)
</blockquote></details>

Ah okay, I could do that. But this webview doesn't have a menu right now. Do you want me to add one?

**Review by tjcouch-sil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/1114)* status: all files reviewed, 3 unresolved discussions (waiting on @rolfheij-sil)

___
*[`extensions/src/platform-scripture/src/configure-checks.web-view.tsx` line 30 at r2](https://reviewable.io/reviews/paranext/paranext-core/1114#-O68ELOM6RMmHBHxGUs0:-O6NDahY8G14okAeLETr:b9hhxlz) ([raw file](https://github.com/paranext/paranext-core/blob/5d4d98e06269433c983f8ac9cd035609d503ca1f/extensions/src/platform-scripture/src/configure-checks.web-view.tsx#L30)):*
<details><summary><i>Previously, rolfheij-sil (Rolf Heij) wrote…</i></summary><blockquote>

Ah okay, I could do that. But this webview doesn't have a menu right now. Do you want me to add one?
</blockquote></details>

If you don't mind, that would probably help with workflow :)

**Review by tjcouch-sil — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/1114)* status: all files reviewed, 3 unresolved discussions (waiting on @rolfheij-sil)

___
*[`extensions/src/platform-scripture/src/checking-results-list.web-view-provider.ts` line 69 at r3](https://reviewable.io/reviews/paranext/paranext-core/1114#-O6MhiMkC7xHe26YXHeV:-O6NDwU8AkgY9erPtmjX:b-9m1xut) ([raw file](https://github.com/paranext/paranext-core/blob/ae654bc1d5c76a7619ab3ed08562a92fff81ecd1/extensions/src/platform-scripture/src/checking-results-list.web-view-provider.ts#L69)):*
<details><summary><i>Previously, rolfheij-sil (Rolf Heij) wrote…</i></summary><blockquote>

Sorry I committed that change but didn't push it yet. Fixed
</blockquote></details>

By the way, I see here that `projectId` is still above `...savedWebView` instead of below it. Just FYI in case somehow it got missed in all the post-change-post-change stuff :)
___
*[`extensions/src/platform-scripture/src/configure-checks.web-view.tsx` line 29 at r2](https://reviewable.io/reviews/paranext/paranext-core/1114#-O68EdseE5LDzy8MC4kH:-O6NDiYe5hCcolTHmNg7:b-6ptkyc) ([raw file](https://github.com/paranext/paranext-core/blob/5d4d98e06269433c983f8ac9cd035609d503ca1f/extensions/src/platform-scripture/src/configure-checks.web-view.tsx#L29)):*
<details><summary><i>Previously, rolfheij-sil (Rolf Heij) wrote…</i></summary><blockquote>

Oops. Fixed.
</blockquote></details>

By the way, I don't see this change yet. Just FYI in case somehow it got missed in all the post-change-post-change stuff :)
___
*[`extensions/src/platform-scripture/src/configure-checks.web-view-provider.ts` line 50 at r3](https://reviewable.io/reviews/paranext/paranext-core/1114#-O6MiZI93jcZs7PFvAqt:-O6NDu3AEUor4Vk0lS9m:b-6ptkyc) ([raw file](https://github.com/paranext/paranext-core/blob/ae654bc1d5c76a7619ab3ed08562a92fff81ecd1/extensions/src/platform-scripture/src/configure-checks.web-view-provider.ts#L50)):*
<details><summary><i>Previously, rolfheij-sil (Rolf Heij) wrote…</i></summary><blockquote>

Same as above. Done.
</blockquote></details>

By the way, I don't see this change yet. Just FYI in case somehow it got missed in all the post-change-post-change stuff :)

**Review by rolfheij-sil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/1114)* status: 9 of 15 files reviewed, 2 unresolved discussions (waiting on @tjcouch-sil)

___
*[`extensions/src/platform-scripture/src/checking-results-list.web-view-provider.ts` line 69 at r3](https://reviewable.io/reviews/paranext/paranext-core/1114#-O6MhiMkC7xHe26YXHeV:-O6NFTox7x7o4lwN9w3E:b-896fix) ([raw file](https://github.com/paranext/paranext-core/blob/ae654bc1d5c76a7619ab3ed08562a92fff81ecd1/extensions/src/platform-scripture/src/checking-results-list.web-view-provider.ts#L69)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

By the way, I see here that `projectId` is still above `...savedWebView` instead of below it. Just FYI in case somehow it got missed in all the post-change-post-change stuff :)
</blockquote></details>

Done.
___
*[`extensions/src/platform-scripture/src/configure-checks.web-view.tsx` line 29 at r2](https://reviewable.io/reviews/paranext/paranext-core/1114#-O68EdseE5LDzy8MC4kH:-O6NFlSh2mcJR-EKUOsb:b-896fix) ([raw file](https://github.com/paranext/paranext-core/blob/5d4d98e06269433c983f8ac9cd035609d503ca1f/extensions/src/platform-scripture/src/configure-checks.web-view.tsx#L29)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

By the way, I don't see this change yet. Just FYI in case somehow it got missed in all the post-change-post-change stuff :)
</blockquote></details>

Done.
___
*[`extensions/src/platform-scripture/src/configure-checks.web-view.tsx` line 30 at r2](https://reviewable.io/reviews/paranext/paranext-core/1114#-O68ELOM6RMmHBHxGUs0:-O6NFnvW6mbQd6iBUZ-1:b-896fix) ([raw file](https://github.com/paranext/paranext-core/blob/5d4d98e06269433c983f8ac9cd035609d503ca1f/extensions/src/platform-scripture/src/configure-checks.web-view.tsx#L30)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

If you don't mind, that would probably help with workflow :)
</blockquote></details>

Done.
___
*[`extensions/src/platform-scripture/src/configure-checks.web-view-provider.ts` line 50 at r3](https://reviewable.io/reviews/paranext/paranext-core/1114#-O6MiZI93jcZs7PFvAqt:-O6NOV7E0mZRWWFjtykU:b-r6hkl7) ([raw file](https://github.com/paranext/paranext-core/blob/ae654bc1d5c76a7619ab3ed08562a92fff81ecd1/extensions/src/platform-scripture/src/configure-checks.web-view-provider.ts#L50)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

By the way, I don't see this change yet. Just FYI in case somehow it got missed in all the post-change-post-change stuff :)
</blockquote></details>

Should be there now

**Review by tjcouch-sil — APPROVED** [review]
:lgtm: woo! Thanks!

> Reviewed 6 of 6 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/1114#-:-O6NgnuCDFxqE74yIL0R:bwvka6p)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Pull request merged**
