### PR TITLE
Add support for creating data providers in C# and apply a few Resharper suggestions

### PR DESCRIPTION
**Pull request by lyonsil**
This change is [Reviewable](https://reviewable.io/reviews/paranext/paranext-core/241)

### CODE REVIEW

**Comment by lyonsil** [comment]
This doesn't add USFM support yet.  It just adds a simple C# data provider to start.  Once ParatextData integration is working, this code can be used to create a USFM data provider.

**Review by irahopkinson — DISMISSED** [review]
:lgtm: I have enough C# to say this looks ok to me but not enough to **know** it's ok. However given it works that's probably enough to merge it.

> Reviewed 12 of 12 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/241#-:-NXwo5DgC0Zf5Z4_t6-r:bb49oek)* status: all files reviewed, 4 unresolved discussions (waiting on @lyonsil)

___
*[`c-sharp/MessageTransports/PapiClient.cs` line 82 at r1](https://reviewable.io/reviews/paranext/paranext-core/241#-NXwr8KsC7PAlPIxv7SH:-NXwr8KsC7PAlPIxv7SI:bjyfwet) ([raw file](https://github.com/paranext/paranext-core/blob/769933cd0a808d68c5d5fa6edb7521549ff7d264/c-sharp/MessageTransports/PapiClient.cs#L82)):*
> ```Smalltalk
>         // Do not change this code. Put cleanup code in 'Dispose(bool isDisposing)' method
>         Dispose(isDisposing: true);
>         // ReSharper disable once GCSuppressFinalizeForTypeWithoutDestructor
> ```

BTW is ReSharper doing some kind of linting for you? If so how would someone else run/check it?
___
*[`c-sharp/NetworkObjects/DataProvider.cs` line 33 at r1](https://reviewable.io/reviews/paranext/paranext-core/241#-NXwotdJ5DSp4w2kO2mC:-NXwotdJ5DSp4w2kO2mD:bljddit) ([raw file](https://github.com/paranext/paranext-core/blob/769933cd0a808d68c5d5fa6edb7521549ff7d264/c-sharp/NetworkObjects/DataProvider.cs#L33)):*
> ```Smalltalk
>             : base(papiClient)
>         {
>             // "-data" is the prefix used by PAPI for data provider names
> ```

BTW you wrote 'prefix' but you add it as a 'suffix', did I miss something or is this a typo?



_Code quote:_
```Smalltalk
prefix
```
___
*[`c-sharp/NetworkObjects/TimeDataProvider.cs` line 30 at r1](https://reviewable.io/reviews/paranext/paranext-core/241#-NXwjR7R7psva3YEJyDR:-NXwjR7S3gVp9rLeUn2b:b-sbbh8p) ([raw file](https://github.com/paranext/paranext-core/blob/769933cd0a808d68c5d5fa6edb7521549ff7d264/c-sharp/NetworkObjects/TimeDataProvider.cs#L30)):*
> ```Smalltalk
>         protected override ResponseToRequest HandleRequest(string functionName, string[] arguments)
>         {
>             return functionName switch
> ```

Oh, switch expressions are cool! I had to look them up though.
___
*[`c-sharp/Properties/launchSettings.json` line 11 at r1](https://reviewable.io/reviews/paranext/paranext-core/241#-NXwfh-7-XHg5YLPpwiy:-NXwfh-7-XHg5YLPpwiz:b-u95zhr) ([raw file](https://github.com/paranext/paranext-core/blob/769933cd0a808d68c5d5fa6edb7521549ff7d264/c-sharp/Properties/launchSettings.json#L11)):*
> ```JSON
>     }
>   }
> }
> ```

BTW the two red symbols at the end here indicate there should be a blank line at the end of the file but there isn't.
___
*[`extensions/lib/hello-world/hello-world.web-view.tsx` line 58 at r1](https://reviewable.io/reviews/paranext/paranext-core/241#-NXwexNJ8s9uXHOfV9-0:-NXwexNJ8s9uXHOfV9-1:b-4pf7yv) ([raw file](https://github.com/paranext/paranext-core/blob/769933cd0a808d68c5d5fa6edb7521549ff7d264/extensions/lib/hello-world/hello-world.web-view.tsx#L58)):*
> ```XML
>   };
> 
>   const [currentTime] = useData.Time<TimeDataType, 'TimeData'>(
> ```

BTW I could be wrong but I think that the name after `useData.` and the string literal in the type should match, however I think it's not currently checking for this. I.e. in your case `Time` and `'TimeData'` don't match when they should.

**Review by lyonsil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/241)* status: 11 of 12 files reviewed, 2 unresolved discussions (waiting on @irahopkinson and @tjcouch-sil)

___
*[`c-sharp/MessageTransports/PapiClient.cs` line 82 at r1](https://reviewable.io/reviews/paranext/paranext-core/241#-NXwr8KsC7PAlPIxv7SH:-NXzAj28-fp3iHW0dr9f:b50rmvi) ([raw file](https://github.com/paranext/paranext-core/blob/769933cd0a808d68c5d5fa6edb7521549ff7d264/c-sharp/MessageTransports/PapiClient.cs#L82)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

BTW is ReSharper doing some kind of linting for you? If so how would someone else run/check it?
</blockquote></details>

I finally got a Resharper license, and it started popping things up in Visual Studio when I opened the project.  So I guess the answer is "open the C# project in Visual Studio with Resharper installed."  That doesn't align with how some of our other tools have been working, but it's the only answer I know.
___
*[`c-sharp/NetworkObjects/DataProvider.cs` line 33 at r1](https://reviewable.io/reviews/paranext/paranext-core/241#-NXwotdJ5DSp4w2kO2mC:-NXzBCGi43oDobdeYYnO:b-azt8hp) ([raw file](https://github.com/paranext/paranext-core/blob/769933cd0a808d68c5d5fa6edb7521549ff7d264/c-sharp/NetworkObjects/DataProvider.cs#L33)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

BTW you wrote 'prefix' but you add it as a 'suffix', did I miss something or is this a typo?
</blockquote></details>

Indeed that was a mistake.  Fixed.
___
*[`c-sharp/NetworkObjects/TimeDataProvider.cs` line 30 at r1](https://reviewable.io/reviews/paranext/paranext-core/241#-NXwjR7R7psva3YEJyDR:-NXzBQZI-RA1YHeohwJD:b-x66ybl) ([raw file](https://github.com/paranext/paranext-core/blob/769933cd0a808d68c5d5fa6edb7521549ff7d264/c-sharp/NetworkObjects/TimeDataProvider.cs#L30)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

Oh, switch expressions are cool! I had to look them up though.
</blockquote></details>

Actually they were new to me, too.  I learned about them because Resharper suggested I use one here instead of a traditional switch statement.  This form is a little more compact, so I kept it.
___
*[`c-sharp/Properties/launchSettings.json` line 11 at r1](https://reviewable.io/reviews/paranext/paranext-core/241#-NXwfh-7-XHg5YLPpwiy:-NXzBgXpCBrv2Hum-6pT:b-96qp06) ([raw file](https://github.com/paranext/paranext-core/blob/769933cd0a808d68c5d5fa6edb7521549ff7d264/c-sharp/Properties/launchSettings.json#L11)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

BTW the two red symbols at the end here indicate there should be a blank line at the end of the file but there isn't.
</blockquote></details>

Hmm.  It's a little funny that the file was automatically created by one tool (Visual Studio) to use for itself while another tool (Reviewable) says the file is wrong.  I think this is just tools disagreeing with each other.  What is "right" is relative here, I think.
___
*[`extensions/lib/hello-world/hello-world.web-view.tsx` line 58 at r1](https://reviewable.io/reviews/paranext/paranext-core/241#-NXwexNJ8s9uXHOfV9-0:-NXzC9lL3-sucStfYRGx:b-uit58j) ([raw file](https://github.com/paranext/paranext-core/blob/769933cd0a808d68c5d5fa6edb7521549ff7d264/extensions/lib/hello-world/hello-world.web-view.tsx#L58)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

BTW I could be wrong but I think that the name after `useData.` and the string literal in the type should match, however I think it's not currently checking for this. I.e. in your case `Time` and `'TimeData'` don't match when they should.
</blockquote></details>

I thought it was looking for the name of the property in the type.  The TS code backing this is a little dense, and it wasn't obvious to me.

I can say for certain that `Time` after `useData` causes the framework to call `getTime` on the network object.  That one is super important.  Everything inside the angle brackets seems to be all about type checking in TS.  That's why I thought it was focused on that.  I could just call both "Time" and make it ambiguous, but this might be something good to clarify with @tjcouch-sil when he's back.

**Review by FoolRunning — CHANGES_REQUESTED** [review]
> Reviewed 11 of 12 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/241)* status: all files reviewed, 2 unresolved discussions (waiting on @irahopkinson, @lyonsil, and @tjcouch-sil)

___
*[`c-sharp/Properties/launchSettings.json` line 11 at r1](https://reviewable.io/reviews/paranext/paranext-core/241#-NXwfh-7-XHg5YLPpwiy:-NXzU5LN0akfCM9PdOQK:bffted4) ([raw file](https://github.com/paranext/paranext-core/blob/769933cd0a808d68c5d5fa6edb7521549ff7d264/c-sharp/Properties/launchSettings.json#L11)):*
<details><summary><i>Previously, lyonsil (Matt Lyons) wrote…</i></summary><blockquote>

Hmm.  It's a little funny that the file was automatically created by one tool (Visual Studio) to use for itself while another tool (Reviewable) says the file is wrong.  I think this is just tools disagreeing with each other.  What is "right" is relative here, I think.
</blockquote></details>

I actually think this file should be deleted. I vaguely recall having this same file be created on the initial C# code implementation and TJ requesting it get removed since it's not needed.

**Review by lyonsil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/241)* status: 11 of 13 files reviewed, 2 unresolved discussions (waiting on @FoolRunning, @irahopkinson, and @tjcouch-sil)

___
*[`c-sharp/Properties/launchSettings.json` line 11 at r1](https://reviewable.io/reviews/paranext/paranext-core/241#-NXwfh-7-XHg5YLPpwiy:-NY-cV6t4T1_JNY6EvtZ:bx6t47p) ([raw file](https://github.com/paranext/paranext-core/blob/769933cd0a808d68c5d5fa6edb7521549ff7d264/c-sharp/Properties/launchSettings.json#L11)):*
<details><summary><i>Previously, FoolRunning (Tim Steenwyk) wrote…</i></summary><blockquote>

I actually think this file should be deleted. I vaguely recall having this same file be created on the initial C# code implementation and TJ requesting it get removed since it's not needed.
</blockquote></details>

Ok.  I removed it and added it to the `.gitignore` file.

**Review by FoolRunning — APPROVED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/241)* status: all files reviewed, 1 unresolved discussion (waiting on @tjcouch-sil)

**Pull request merged**
