### PR TITLE
Add documentation for inventory components, and add unit tests for inventory utils in platform-bible-react

### LINKED ISSUE #1037: Add unit tests to Inventory util functions
A number of utility functions were created in the scope of the Inventories.
They can be found in 
`paranext-core\lib\platform-bible-react\src\components\advanced\inventory\inventory-utils.ts`
and in
`paranext-core\extensions\src\platform-scripture\src\inventory-utils.ts`

Unit tests still need to be added for these utility functions.
Also, a test environment still needs to be set up in the `platform-scripture` extension

### PR DESCRIPTION
**Pull request by rolfheij-sil**
Resolves #1037 and #1038

The documentation is not anywhere near complete, but it covers the essentials for now.

This change is [Reviewable](https://reviewable.io/reviews/paranext/paranext-core/1091)

### CODE REVIEW

**Review by tjcouch-sil — DISMISSED** [review]
Cool, thanks!! You need to rebuild `platform-bible-react`, right?

> Reviewed 10 of 10 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/1091#-:-O5Fhpud-y7pp7o492Y9:banc1pd)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Review by irahopkinson — CHANGES_REQUESTED** [review]
Nice to see the TSDocs and thanks for adding some unit tests.

> Reviewed 10 of 10 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/1091#-:-O5G83u09e0wUvjngIHg:b-vh0ayu)* status: all files reviewed, 9 unresolved discussions (waiting on @rolfheij-sil)

___
*[`extensions/src/platform-scripture/src/character-inventory.component.tsx` line 31 at r1](https://reviewable.io/reviews/paranext/paranext-core/1091#-O5FuG0h7JnObQRPwsv9:-O5FuG0h7JnObQRPwsvA:bwr9zak) ([raw file](https://github.com/paranext/paranext-core/blob/df1fabc167eb1beb5ab78bfdc15053d9daa43d42/extensions/src/platform-scripture/src/character-inventory.component.tsx#L31)):*
> ```XML
>  * @param statusLabel Localized label for the status column
>  * @param statusChangeHandler Callback function that handles status updates to selected item(s)
>  * @returns
> ```

Add a description of what this function returns, e.g. "An array of ..."
___
*[`extensions/src/platform-scripture/src/inventory-utils.ts` line 33 at r1](https://reviewable.io/reviews/paranext/paranext-core/1091#-O5Fveuy4wdiHVk2XPmd:-O5Fveuy4wdiHVk2XPme:byjdjtk) ([raw file](https://github.com/paranext/paranext-core/blob/df1fabc167eb1beb5ab78bfdc15053d9daa43d42/extensions/src/platform-scripture/src/inventory-utils.ts#L33)):*
> ```XML
> ): string[] => {
>   const repeatedWords: string[] = [];
>   const words = split(text, /[\s]+/);
> ```

FYI some languages use different space characters (and even more than one). We will eventually need to allow for that in this function.
___
*[`extensions/src/platform-scripture/src/inventory.web-view.tsx` line 24 at r1](https://reviewable.io/reviews/paranext/paranext-core/1091#-O5Fwzyu-5_qymT5r-ek:-O5Fwzyu-5_qymT5r-el:b-n0k9df) ([raw file](https://github.com/paranext/paranext-core/blob/df1fabc167eb1beb5ab78bfdc15053d9daa43d42/extensions/src/platform-scripture/src/inventory.web-view.tsx#L24)):*
> ```XML
>  */
> const getText = async (
>   scope: string,
> ```

FYI it might be better to make the type `'book' | 'chapter' | 'verse'` rather than `string` to help with type checking.
___
*[`extensions/src/platform-scripture/src/repeated-words-inventory.component.tsx` line 28 at r1](https://reviewable.io/reviews/paranext/paranext-core/1091#-O5FzWRoDtAAc_iWvh5T:-O5FzWRoDtAAc_iWvh5U:bwr9zak) ([raw file](https://github.com/paranext/paranext-core/blob/df1fabc167eb1beb5ab78bfdc15053d9daa43d42/extensions/src/platform-scripture/src/repeated-words-inventory.component.tsx#L28)):*
> ```XML
>  * @param statusLabel Localized label for the status column
>  * @param statusChangeHandler Callback function that handles status updates to selected item(s)
>  * @returns
> ```

Add a description of what this function returns, e.g. "An array of ..."
___
*[`lib/platform-bible-react/src/components/advanced/inventory/inventory-columns.tsx` line 10 at r1](https://reviewable.io/reviews/paranext/paranext-core/1091#-O5G-kJd6clWygHw4jET:-O5G-kJd6clWygHw4jEU:bozmwtg) ([raw file](https://github.com/paranext/paranext-core/blob/df1fabc167eb1beb5ab78bfdc15053d9daa43d42/lib/platform-bible-react/src/components/advanced/inventory/inventory-columns.tsx#L10)):*
> ```XML
>  * @param itemLabel Localized label for the item column (e.g. 'Character', 'Repeated Word', etc.)
>  * @returns Column that shows the inventory items.
>  * Should be used with the DataTable component
> ```

Either add a `@remark` to the start of this line and a newline above, or move this to be part of the first line in the TSDoc. Here and below.



_Code quote:_
```XML
Should be used with the DataTable component
```
___
*[`lib/platform-bible-react/src/components/advanced/inventory/inventory-utils.ts` line 8 at r1](https://reviewable.io/reviews/paranext/paranext-core/1091#-O5G0YKu2ngKW3U0FJcn:-O5G0YKu2ngKW3U0FJco:bqw4l87) ([raw file](https://github.com/paranext/paranext-core/blob/df1fabc167eb1beb5ab78bfdc15053d9daa43d42/lib/platform-bible-react/src/components/advanced/inventory/inventory-utils.ts#L8)):*
> ```XML
>  */
> export const getLinesFromUSFM = (text: string) => {
>   return text.split(/(?:\r?\n|\r)|(?=(?:\\(?:v|c|id)))/g);
> ```

A RegEx almost always needs a comment. Add a normal comment above this line explaining what the RegEx does, e.g. "splits on CRLF or CR, book, and standard chapter and verse" (I don't actually know what it does exactly). Here and below.
___
*[`lib/platform-bible-react/src/components/advanced/inventory/inventory-utils.ts` line 23 at r1](https://reviewable.io/reviews/paranext/paranext-core/1091#-O5G2TXUAi1gX2icr03-:-O5G2TXUAi1gX2icr030:b-icd5rc) ([raw file](https://github.com/paranext/paranext-core/blob/df1fabc167eb1beb5ab78bfdc15053d9daa43d42/lib/platform-bible-react/src/components/advanced/inventory/inventory-utils.ts#L23)):*
> ```XML
>     return +match[1];
>   }
>   return 0;
> ```

BTW it might be better to return `undefined` if this can't find anything since that makes more sense. Also I think there are legitimate references to chapter 0 or verse 0 that you might need to support.



_Code quote:_
```XML
return 0;
```
___
*[`lib/platform-bible-react/src/components/advanced/inventory/inventory.component.tsx` line 71 at r1](https://reviewable.io/reviews/paranext/paranext-core/1091#-O5G5Fl6-cXk56Qccse3:-O5G5Fl6-cXk56Qccse4:bgsl3be) ([raw file](https://github.com/paranext/paranext-core/blob/df1fabc167eb1beb5ab78bfdc15053d9daa43d42/lib/platform-bible-react/src/components/advanced/inventory/inventory.component.tsx#L71)):*
> ```XML
>  * @param items All items and their related information
>  * @param statusFilter Allows filtering by status (i.e. show all items, or only items that are
>  * 'approved', 'unapproved' or 'unknown')
> ```

or 'all'?
___
*[`lib/platform-bible-react/src/components/advanced/inventory/inventory.component.tsx` line 73 at r1](https://reviewable.io/reviews/paranext/paranext-core/1091#-O5G6h3x2wXIk_wOpk9M:-O5G6h3x2wXIk_wOpk9N:b-fsoqml) ([raw file](https://github.com/paranext/paranext-core/blob/df1fabc167eb1beb5ab78bfdc15053d9daa43d42/lib/platform-bible-react/src/components/advanced/inventory/inventory.component.tsx#L73)):*
> ```XML
>  * 'approved', 'unapproved' or 'unknown')
>  * @param textFilter Allows filtering by text. All items that include the filter text will be
>  * selected.
> ```

You should run `cd lib/platform-bible-react && npm run lint-fix:scripts` to make sure these TSDocs are formatted correctly. You have also changed code so you should also do a build (which would fix the formatting anyway).
___
*[`lib/platform-bible-react/src/components/advanced/inventory/inventory.component.tsx` line 78 at r1](https://reviewable.io/reviews/paranext/paranext-core/1091#-O5G4x-L0UOYhqRx4KQC:-O5G4x-L0UOYhqRx4KQD:bt42cf6) ([raw file](https://github.com/paranext/paranext-core/blob/df1fabc167eb1beb5ab78bfdc15053d9daa43d42/lib/platform-bible-react/src/components/advanced/inventory/inventory.component.tsx#L78)):*
> ```XML
> const filterItemData = (
>   items: ItemData[],
>   statusFilter: string,
> ```

BTW Perhaps this type should be `'approved' | 'unapproved'  | 'unknown' | 'all'` instead of `string`? That would improve type checking.



_Code quote:_
```XML
statusFilter: string,
```
___
*[`lib/platform-bible-react/src/components/advanced/inventory/inventory.component.tsx` line 330 at r1](https://reviewable.io/reviews/paranext/paranext-core/1091#-O5G7nyq45PqTTCLCntt:-O5G7nyq45PqTTCLCntu:b-mtbdxm) ([raw file](https://github.com/paranext/paranext-core/blob/df1fabc167eb1beb5ab78bfdc15053d9daa43d42/lib/platform-bible-react/src/components/advanced/inventory/inventory.component.tsx#L330)):*
> ```XML
> }
> 
> export default Inventory;
> ```

Nit This can be moved to the function declaration rather than being on its own at the end of the file.



_Code quote:_
```XML
export default
```

**Review by rolfheij-sil — COMMENTED** [review]
Thanks for reviewing!

> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/1091#-:-O5JPUXz9vc0KgVkyOOw:b-yz40g0)* status: 2 of 16 files reviewed, 7 unresolved discussions (waiting on @irahopkinson, @remark, and @tjcouch-sil)

___
*[`extensions/src/platform-scripture/src/character-inventory.component.tsx` line 31 at r1](https://reviewable.io/reviews/paranext/paranext-core/1091#-O5FuG0h7JnObQRPwsv9:-O5JFoGC1ZVDQQ0iP9WB:b-896fix) ([raw file](https://github.com/paranext/paranext-core/blob/df1fabc167eb1beb5ab78bfdc15053d9daa43d42/extensions/src/platform-scripture/src/character-inventory.component.tsx#L31)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

Add a description of what this function returns, e.g. "An array of ..."
</blockquote></details>

Done.
___
*[`extensions/src/platform-scripture/src/inventory-utils.ts` line 33 at r1](https://reviewable.io/reviews/paranext/paranext-core/1091#-O5Fveuy4wdiHVk2XPmd:-O5JFrml6tis1q9gDnKF:b-5gi9mm) ([raw file](https://github.com/paranext/paranext-core/blob/df1fabc167eb1beb5ab78bfdc15053d9daa43d42/extensions/src/platform-scripture/src/inventory-utils.ts#L33)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

FYI some languages use different space characters (and even more than one). We will eventually need to allow for that in this function.
</blockquote></details>

Yes, most of these util function will probably have to change later, of they might even be replaced by importing Paratext 9 / C# code
___
*[`extensions/src/platform-scripture/src/inventory.web-view.tsx` line 24 at r1](https://reviewable.io/reviews/paranext/paranext-core/1091#-O5Fwzyu-5_qymT5r-ek:-O5JInpE2wRLhzqJ7shD:b-utmyaq) ([raw file](https://github.com/paranext/paranext-core/blob/df1fabc167eb1beb5ab78bfdc15053d9daa43d42/extensions/src/platform-scripture/src/inventory.web-view.tsx#L24)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

FYI it might be better to make the type `'book' | 'chapter' | 'verse'` rather than `string` to help with type checking.
</blockquote></details>

Good idea. Implemented it.
___
*[`extensions/src/platform-scripture/src/repeated-words-inventory.component.tsx` line 28 at r1](https://reviewable.io/reviews/paranext/paranext-core/1091#-O5FzWRoDtAAc_iWvh5T:-O5JIwPA2lwsWjta2_8B:b-896fix) ([raw file](https://github.com/paranext/paranext-core/blob/df1fabc167eb1beb5ab78bfdc15053d9daa43d42/extensions/src/platform-scripture/src/repeated-words-inventory.component.tsx#L28)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

Add a description of what this function returns, e.g. "An array of ..."
</blockquote></details>

Done.
___
*[`lib/platform-bible-react/src/components/advanced/inventory/inventory-columns.tsx` line 10 at r1](https://reviewable.io/reviews/paranext/paranext-core/1091#-O5G-kJd6clWygHw4jET:-O5JJVbD2I4s6cSlkchJ:b-tp7654) ([raw file](https://github.com/paranext/paranext-core/blob/df1fabc167eb1beb5ab78bfdc15053d9daa43d42/lib/platform-bible-react/src/components/advanced/inventory/inventory-columns.tsx#L10)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

Either add a `@remark` to the start of this line and a newline above, or move this to be part of the first line in the TSDoc. Here and below.
</blockquote></details>

IntelliSense doesn't list `@remark` as an option for me, so I added it to the first line of the TSDoc
___
*[`lib/platform-bible-react/src/components/advanced/inventory/inventory-utils.ts` line 8 at r1](https://reviewable.io/reviews/paranext/paranext-core/1091#-O5G0YKu2ngKW3U0FJcn:-O5JLiiM1_IIHqOWkGJM:b-b5ob1t) ([raw file](https://github.com/paranext/paranext-core/blob/df1fabc167eb1beb5ab78bfdc15053d9daa43d42/lib/platform-bible-react/src/components/advanced/inventory/inventory-utils.ts#L8)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

A RegEx almost always needs a comment. Add a normal comment above this line explaining what the RegEx does, e.g. "splits on CRLF or CR, book, and standard chapter and verse" (I don't actually know what it does exactly). Here and below.
</blockquote></details>

Done. You're right, regex is hard to read. I like to use this website to unravel them for me: https://regex101.com/
___
*[`lib/platform-bible-react/src/components/advanced/inventory/inventory-utils.ts` line 23 at r1](https://reviewable.io/reviews/paranext/paranext-core/1091#-O5G2TXUAi1gX2icr03-:-O5JM0FX6EBC5N7Vp2Pd:bf6zykc) ([raw file](https://github.com/paranext/paranext-core/blob/df1fabc167eb1beb5ab78bfdc15053d9daa43d42/lib/platform-bible-react/src/components/advanced/inventory/inventory-utils.ts#L23)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

BTW it might be better to return `undefined` if this can't find anything since that makes more sense. Also I think there are legitimate references to chapter 0 or verse 0 that you might need to support.
</blockquote></details>

That makes sense. I've updated it. Although I don't really know what to do with the output value in case it's `undefined`. For now I'll just represent it with `-1` in the table where it's used. Alternatively I could hide any results where the verse/chapter number is undefined, but I feel like that's  a bit too drastic for now.
___
*[`lib/platform-bible-react/src/components/advanced/inventory/inventory.component.tsx` line 71 at r1](https://reviewable.io/reviews/paranext/paranext-core/1091#-O5G5Fl6-cXk56Qccse3:-O5JOE4fA7bFP4aMNrbh:b3offoy) ([raw file](https://github.com/paranext/paranext-core/blob/df1fabc167eb1beb5ab78bfdc15053d9daa43d42/lib/platform-bible-react/src/components/advanced/inventory/inventory.component.tsx#L71)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

or 'all'?
</blockquote></details>

The sentence starts with `show all items`. Would you like me to rephrase it?
___
*[`lib/platform-bible-react/src/components/advanced/inventory/inventory.component.tsx` line 73 at r1](https://reviewable.io/reviews/paranext/paranext-core/1091#-O5G6h3x2wXIk_wOpk9M:-O5JOcth1d4B0wv2l8re:b-ov3ugz) ([raw file](https://github.com/paranext/paranext-core/blob/df1fabc167eb1beb5ab78bfdc15053d9daa43d42/lib/platform-bible-react/src/components/advanced/inventory/inventory.component.tsx#L73)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

You should run `cd lib/platform-bible-react && npm run lint-fix:scripts` to make sure these TSDocs are formatted correctly. You have also changed code so you should also do a build (which would fix the formatting anyway).
</blockquote></details>

Yes, sorry, I forgot to do that before
___
*[`lib/platform-bible-react/src/components/advanced/inventory/inventory.component.tsx` line 78 at r1](https://reviewable.io/reviews/paranext/paranext-core/1091#-O5G4x-L0UOYhqRx4KQC:-O5JPH1-18Q8ni6DTkrO:bb6un1j) ([raw file](https://github.com/paranext/paranext-core/blob/df1fabc167eb1beb5ab78bfdc15053d9daa43d42/lib/platform-bible-react/src/components/advanced/inventory/inventory.component.tsx#L78)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

BTW Perhaps this type should be `'approved' | 'unapproved'  | 'unknown' | 'all'` instead of `string`? That would improve type checking.
</blockquote></details>

Done
___
*[`lib/platform-bible-react/src/components/advanced/inventory/inventory.component.tsx` line 330 at r1](https://reviewable.io/reviews/paranext/paranext-core/1091#-O5G7nyq45PqTTCLCntt:-O5JPTPW5y_gAPxOXxtc:b-896fix) ([raw file](https://github.com/paranext/paranext-core/blob/df1fabc167eb1beb5ab78bfdc15053d9daa43d42/lib/platform-bible-react/src/components/advanced/inventory/inventory.component.tsx#L330)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

Nit This can be moved to the function declaration rather than being on its own at the end of the file.
</blockquote></details>

Done.

**Review by irahopkinson — CHANGES_REQUESTED** [review]
Thanks for all the changes. Just the one code issue left.

The only other thing is that you could create types and use those to make your code DRYer (but I didn't want that to be a blocking comment), i.e.:
```ts
type Scope = 'book' | 'chapter' | 'verse';
type StatusFilter = 'all' | 'approved' | 'unapproved' | 'unknown';
```

> Reviewed 14 of 14 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/1091#-:-O5Kcbs_0J4Y17jlmAB3:bbg7jse)* status: all files reviewed, 1 unresolved discussion (waiting on @rolfheij-sil)

___
*[`lib/platform-bible-react/src/components/advanced/inventory/inventory.component.tsx` line 71 at r1](https://reviewable.io/reviews/paranext/paranext-core/1091#-O5G5Fl6-cXk56Qccse3:-O5KbBoKCMb30oo6MuD-:b-fp1x8q) ([raw file](https://github.com/paranext/paranext-core/blob/df1fabc167eb1beb5ab78bfdc15053d9daa43d42/lib/platform-bible-react/src/components/advanced/inventory/inventory.component.tsx#L71)):*
<details><summary><i>Previously, rolfheij-sil (Rolf Heij) wrote…</i></summary><blockquote>

The sentence starts with `show all items`. Would you like me to rephrase it?
</blockquote></details>

Sorry, my bad, I didn't re-read this when I saw below the 4 values of the `statusFilter`.
___
*[`lib/platform-bible-react/src/components/advanced/inventory/occurrences-table.component.tsx` line 57 at r2](https://reviewable.io/reviews/paranext/paranext-core/1091#-O5Kc68t2JF6piSuYpr8:-O5Kc68t2JF6piSuYpr9:b-h7rxmv) ([raw file](https://github.com/paranext/paranext-core/blob/06cb5e26df6a48d8f68a082e9123dc8daff44621/lib/platform-bible-react/src/components/advanced/inventory/occurrences-table.component.tsx#L57)):*
> ```XML
>         reference: {
>           ...scriptureRef,
>           chapterNum: currentChapter ? +currentChapter : -1,
> ```

`0` is falsy so you need to explicitly check, i.e. `currentChapter !== undefined`. For `verseNum` also.

**Review by irahopkinson — CHANGES_REQUESTED** [review]
> Reviewed 14 of 14 files at r2.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/1091)* status: 5 of 17 files reviewed, 1 unresolved discussion (waiting on @rolfheij-sil)

**Review by irahopkinson — CHANGES_REQUESTED** [review]
> Reviewed 14 of 14 files at r2.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/1091)* status: 5 of 17 files reviewed, 1 unresolved discussion (waiting on @rolfheij-sil)

**Review by irahopkinson — APPROVED** [review]
:lgtm:

> Reviewed 14 of 14 files at r2, 12 of 12 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/1091#-:-O5Kcbs_0J4Y17jlmAB3:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Pull request merged**
