### PR TITLE
Create open multiple projects dialog

### PR DESCRIPTION
**Pull request by jolierabideau**
Created the dialog and added it to the test layout. I did not create a menu item and command for this because the issue said it does not need to be in the application menu. Also added `ListItemIcons` in the other components to help with styling for now, and another project to test with.

This change is [Reviewable](https://reviewable.io/reviews/paranext/paranext-core/393)

### CODE REVIEW

**Review by tjcouch-sil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/393)* status: 0 of 6 files reviewed, 1 unresolved discussion (waiting on @jolierabideau)

___
*[`src/renderer/components/docking/open-multiple-projects-tab.component.tsx` line 39 at r1](https://reviewable.io/reviews/paranext/paranext-core/393#-NcXak2n1qmpstiSBGEU:-NcXak2n1qmpstiSBGEV:bxapm1x) ([raw file](https://github.com/paranext/paranext-core/blob/c9534169ea144234752b1fef46218d6589fe2889/src/renderer/components/docking/open-multiple-projects-tab.component.tsx#L39)):*
> ```XML
>   return (
>     <div className="open-multiple-projects-dialog">
>       <List>
> ```

I see that this list of projects and the list of projects in the open project dialog seem very similar. Is there a way to combine them in another component that you use in both places?

**Review by jolierabideau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/393)* status: 0 of 7 files reviewed, 1 unresolved discussion (waiting on @tjcouch-sil)

___
*[`src/renderer/components/docking/open-multiple-projects-tab.component.tsx` line 39 at r1](https://reviewable.io/reviews/paranext/paranext-core/393#-NcXak2n1qmpstiSBGEU:-NcYfpeO4dAGXi31HkJ8:b-xedz65) ([raw file](https://github.com/paranext/paranext-core/blob/c9534169ea144234752b1fef46218d6589fe2889/src/renderer/components/docking/open-multiple-projects-tab.component.tsx#L39)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

I see that this list of projects and the list of projects in the open project dialog seem very similar. Is there a way to combine them in another component that you use in both places?
</blockquote></details>

I have added a `ProjectList` component that the dialogs can use. But I cannot figure out a good way to do it when there are multiple buttons per project in the list, as in the update/delete section of the download/update dialog. For now that is the only one not using the new `ProjectList`

**Review by jolierabideau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/393)* status: 0 of 7 files reviewed, 1 unresolved discussion (waiting on @tjcouch-sil)

___
*[`src/renderer/components/docking/open-multiple-projects-tab.component.tsx` line 39 at r1](https://reviewable.io/reviews/paranext/paranext-core/393#-NcXak2n1qmpstiSBGEU:-NcYgYdq6EFiiTtVxnzp:b-ol1jur) ([raw file](https://github.com/paranext/paranext-core/blob/c9534169ea144234752b1fef46218d6589fe2889/src/renderer/components/docking/open-multiple-projects-tab.component.tsx#L39)):*
<details><summary><i>Previously, jolierabideau wrote…</i></summary><blockquote>

I have added a `ProjectList` component that the dialogs can use. But I cannot figure out a good way to do it when there are multiple buttons per project in the list, as in the update/delete section of the download/update dialog. For now that is the only one not using the new `ProjectList`
</blockquote></details>

I am also not sure where this component should live? It is currently in the same place as the dialogs

**Review by tjcouch-sil — APPROVED** [review]
:lgtm: thanks again for the hard work!

> Reviewed 3 of 6 files at r1, 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/393#-:-NcYwuf4CHL67pNxPoi2:b-q4edjr)* status: :shipit: complete! all files reviewed, all discussions resolved

___
*[`src/renderer/components/docking/open-multiple-projects-tab.component.scss` line 6 at r2](https://reviewable.io/reviews/paranext/paranext-core/393#-NcYwE9RBfQggEecNcAx:-NcYwE9SA_kR-EmssITZ:bmwwt6q) ([raw file](https://github.com/paranext/paranext-core/blob/673c62ad5d3e2f52c44d82e35112e0f1f64b82f7/src/renderer/components/docking/open-multiple-projects-tab.component.scss#L6)):*
> ```SCSS
> 
> .open-multiple-projects-submit-button {
>   display: flex !important;
> ```

Just a quick note: in general, you almost never want to use `!important` and rather should try to find a way around using it. `!important` kinda breaks the expected rules in CSS, so it's an escape hatch. However, since we're using MUI, I imagine it's probably not easy or maybe even possible to find a way around it. Just wanted to make sure I mentioned at some point that this isn't usually the preferred option :)
___
*[`src/renderer/components/docking/open-multiple-projects-tab.component.tsx` line 39 at r1](https://reviewable.io/reviews/paranext/paranext-core/393#-NcXak2n1qmpstiSBGEU:-NcYtH5N7sjfzs67oJCb:b-o4fwvb) ([raw file](https://github.com/paranext/paranext-core/blob/c9534169ea144234752b1fef46218d6589fe2889/src/renderer/components/docking/open-multiple-projects-tab.component.tsx#L39)):*
<details><summary><i>Previously, jolierabideau wrote…</i></summary><blockquote>

I am also not sure where this component should live? It is currently in the same place as the dialogs
</blockquote></details>

There are a few ways to render a dynamic number of buttons, but those are pretty complex and not really necessary to worry about at the moment. What you have done is good :) let's go with it!

**Pull request merged**
