### PR TITLE
Use <feature>.<type>.<ext> filename convention

### PR DESCRIPTION
**Pull request by irahopkinson**
- most files have just been renamed in place to ensure git tracability
- some files have been moved but are only minor renames of an existing path

- - -
This change is [Reviewable](https://reviewable.io/reviews/paranext/paranext-core/142)

### CODE REVIEW

**Review by FoolRunning — DISMISSED** [review]
> Reviewed 88 of 88 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/142)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @irahopkinson)

___
*[`src/client/services/web-socket.factory.ts` line 6 at r1](https://reviewable.io/reviews/paranext/paranext-core/142#-NSkHFgIEeLlKQAFxgnK:-NSkHFgIEeLlKQAFxgnL:bjkvhhe) ([raw file](https://github.com/paranext/paranext-core/blob/59284bd4682be084c73b6d93699f605741914e8d/src/client/services/web-socket.factory.ts#L6)):*
> ```XML
> 
> import { isRenderer } from '@shared/utils/internal-util';
> import { IWebSocket } from './i-web-socket.model';
> ```

I wasn't ever a fan of the dash notation, but this takes it to a whole new level. ``i-`` does not look good. 😖
___
*[`src/renderer/hooks/papi-hooks/use-event.hook.ts` line 2 at r1](https://reviewable.io/reviews/paranext/paranext-core/142#-NSkIfpeA7RTzVMYahRw:-NSkIfpeA7RTzVMYahRx:bidqriu) ([raw file](https://github.com/paranext/paranext-core/blob/59284bd4682be084c73b6d93699f605741914e8d/src/renderer/hooks/papi-hooks/use-event.hook.ts#L2)):*
> ```XML
> import { getNetworkEvent } from '@shared/services/network.service';
> import { PEvent, PEventHandler } from '@shared/models/p-event.model';
> ```

Another one that doesn't look good 😖

**Review by lyonsil — CHANGES_REQUESTED** [review]
> Reviewed 88 of 88 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/142)* status: all files reviewed, 1 unresolved discussion (waiting on @irahopkinson)

___
*[`src/client/services/web-socket.factory.ts` line 6 at r1](https://reviewable.io/reviews/paranext/paranext-core/142#-NSkHFgIEeLlKQAFxgnK:-NSk_Rwj04hLhpSjxBBR:b-9hza92) ([raw file](https://github.com/paranext/paranext-core/blob/59284bd4682be084c73b6d93699f605741914e8d/src/client/services/web-socket.factory.ts#L6)):*
<details><summary><i>Previously, FoolRunning (Tim Steenwyk) wrote…</i></summary><blockquote>

I wasn't ever a fan of the dash notation, but this takes it to a whole new level. ``i-`` does not look good. 😖
</blockquote></details>

There was an `INetworkConnector` in an earlier file where the `I` was dropped.  I don't know which is better, but we should probably be consistent.  Either drop the `I` or put it back there.  It looks like in most cases the conversion was consistent to `i-something.whatever`.
___
*[`src/node/services/node-file-system.service.ts` line 8 at r1](https://reviewable.io/reviews/paranext/paranext-core/142#-NSkaiII9BOEQ7K-L_NJ:-NSkaiIJ-8aVpNi3Zjij:btqjfz8) ([raw file](https://github.com/paranext/paranext-core/blob/59284bd4682be084c73b6d93699f605741914e8d/src/node/services/node-file-system.service.ts#L8)):*
> ```XML
> import { Uri } from '@shared/data/file-system.model';
> import { getPathFromUri, joinUriPaths } from '@node/util/util';
> import { groupBy } from '@shared/utils/util';
> ```

Why was `utils` made plural here but not on the line above?

**Review by katherinejensen00 — COMMENTED** [review]
Besides the utils question that Matt asked, I think this looks good.

> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/142#-:-NSkuhLPAwquAK44E00B:bfoy8fl)* status: all files reviewed, 1 unresolved discussion (waiting on @irahopkinson)

**Review by irahopkinson — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/142)* status: 64 of 88 files reviewed, 1 unresolved discussion (waiting on @FoolRunning and @lyonsil)

___
*[`src/client/services/web-socket.factory.ts` line 6 at r1](https://reviewable.io/reviews/paranext/paranext-core/142#-NSkHFgIEeLlKQAFxgnK:-NSmK_6X02_GFJ8CmQMJ:b-517v2z) ([raw file](https://github.com/paranext/paranext-core/blob/59284bd4682be084c73b6d93699f605741914e8d/src/client/services/web-socket.factory.ts#L6)):*
<details><summary><i>Previously, lyonsil wrote…</i></summary><blockquote>

There was an `INetworkConnector` in an earlier file where the `I` was dropped.  I don't know which is better, but we should probably be consistent.  Either drop the `I` or put it back there.  It looks like in most cases the conversion was consistent to `i-something.whatever`.
</blockquote></details>

Done. `INetworkConnector` has also been made consistent with this - thanks for spotting that.
___
*[`src/node/services/node-file-system.service.ts` line 8 at r1](https://reviewable.io/reviews/paranext/paranext-core/142#-NSkaiII9BOEQ7K-L_NJ:-NSmKpaWBTeUtwe40a4n:b-896fix) ([raw file](https://github.com/paranext/paranext-core/blob/59284bd4682be084c73b6d93699f605741914e8d/src/node/services/node-file-system.service.ts#L8)):*
<details><summary><i>Previously, lyonsil wrote…</i></summary><blockquote>

Why was `utils` made plural here but not on the line above?
</blockquote></details>

Done.
___
*[`src/renderer/hooks/papi-hooks/use-event.hook.ts` line 2 at r1](https://reviewable.io/reviews/paranext/paranext-core/142#-NSkIfpeA7RTzVMYahRw:-NSmKv3jDIUmvA428zt0:b-896fix) ([raw file](https://github.com/paranext/paranext-core/blob/59284bd4682be084c73b6d93699f605741914e8d/src/renderer/hooks/papi-hooks/use-event.hook.ts#L2)):*
<details><summary><i>Previously, FoolRunning (Tim Steenwyk) wrote…</i></summary><blockquote>

Another one that doesn't look good 😖
</blockquote></details>

Done.

**Review by lyonsil — APPROVED** [review]
:lgtm:

> Reviewed 24 of 24 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/142#-:-NSmMTOY8EwiLg61QJEa:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @irahopkinson)

**Pull request merged**
