### PR TITLE
254 update render edit cell api

### PR DESCRIPTION
**Pull request by rolfheij-sil**
This change is [Reviewable](https://reviewable.io/reviews/paranext/paranext-core/256)

### CODE REVIEW

**Review by tjcouch-sil — APPROVED** [review]
I like it! I don't know what people would think about this, but it seems like an intuitive api to me. Sad that we have to shallow clone each column, but it seems it may be worth it to fix the weird api that the data grid library exposes.

> Reviewed 10 of 10 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/256#-:-NYUGpEa6xlZBe2xIg1z:be0wnew)* status: all files reviewed, 3 unresolved discussions (waiting on @rolfheij-sil)

___
*[`lib/papi-components/src/table.component.tsx` line 294 at r1](https://reviewable.io/reviews/paranext/paranext-core/256#-NYU6so48EEswx1clnP9:-NYU6so48EEswx1clnPA:b-5g5bul) ([raw file](https://github.com/paranext/paranext-core/blob/86b94a9beb930ad5aace6ca477999814702512d8/lib/papi-components/src/table.component.tsx#L294)):*
> ```XML
>   const cachedColumns = useMemo(() => {
>     const editableColumns = columns.map((column) => {
>       if (column.editable && !column.renderEditCell) {
> ```

This code currently does not allow for `editable` to be a function that takes the row and returns whether that specific cell should be editable. You can check if `editable` is a function with `typeof column.editable === 'function'`. Since, as I mentioned in the comment below (I split this one out so it is a bit less overwhelmingly large), we can make a cell not editable if the `editable` function returns false, maybe we can make a new function that layers over the return from the `editable` function and returns `false` if it's falsy. Something like:

```typescript
function editableFalsy(row: R) {
  return !!editable(row);
}
```

The double bang `!!` converts a truthy/falsey into actual `true` or `false`, so that will make it so people can return whatever truthy/falsey value they want, and it will properly set editable to `false`.
___
*[`lib/papi-components/src/table.component.tsx` line 298 at r1](https://reviewable.io/reviews/paranext/paranext-core/256#-NYTd8oB2Gnnv586x3PY:-NYU21BkCwRnJE5GfvIp:b-u29b0d) ([raw file](https://github.com/paranext/paranext-core/blob/86b94a9beb930ad5aace6ca477999814702512d8/lib/papi-components/src/table.component.tsx#L298)):*
<details><summary><i>Previously, rolfheij-sil wrote…</i></summary><blockquote>

Not sure how I feel about setting the renderEditCell to `null` in case `editable` is disabled. It does result in the desired behavior, but setting this to `null` might not be something we want to do. Opinions?
</blockquote></details>

Yeah, it's a bit weird. I will recommend an alternative in a few moments, but some thoughts on `null` itself for learning's sake: I would recommend removing `renderEditCell` from the object via destructuring or `delete` or setting `renderEditCell` to `undefined` instead of `null`. [The check uses `!= null`](https://github.com/adazzle/react-data-grid/blob/c29bf0cd6116584eee71c26c51acc4874c485b45/src/utils/selectedCellUtils.ts#L24) (note `!=` instead of `!==`. Double equals `==` and `!=` perform type coercion, so they are more lenient than triple equals) which works with either `null` or `undefined`, and our style guide says to avoid `null`.

A few options:
1. Destructure out - probably works well
```typescript
const { renderEditCell, ...columnNotEditable } = column;
return columnNotEditable;
```
2. Delete - may be a good option if TypeScript doesn't show errors, but hopefully it won't
```typescript
const columnNotEditable = column;
delete columnNotEditable.renderEditCell;
return columnNotEditable;
```
3. Set to undefined (basically what you have now. This will leave `renderEditCell` on the object, but that's not a big deal)
`return { ...column, renderEditCell: undefined }`

However, instead of doing any of the above, I suggest setting `editable` to `false` in this case and leaving `renderEditCell` as it is. It seems [the check](https://github.com/adazzle/react-data-grid/blob/c29bf0cd6116584eee71c26c51acc4874c485b45/src/utils/selectedCellUtils.ts#L26) allows for `renderEditCell` to be defined as long as `editable` is specifically `false` or a function that returns `false` for a given row.

Also note this method changes the reference to each column from what is passed in. Kinda weird, but I don't know what else we would do with this method. Would be best to note in the `columns` prop jsdoc that we have some internal logic that shallow clones the columns so people know they can't use object reference equivalence to figure out which column they're using (if someone ever tries to do that).
___
*[`lib/papi-dts/papi.d.ts` line 1372 at r1](https://reviewable.io/reviews/paranext/paranext-core/256#-NYTdMiv6MQJ_9hnDy3M:-NYUG_WY4dZw1kKBbJnf:bxiuhen) ([raw file](https://github.com/paranext/paranext-core/blob/86b94a9beb930ad5aace6ca477999814702512d8/lib/papi-dts/papi.d.ts#L1372)):*
<details><summary><i>Previously, rolfheij-sil wrote…</i></summary><blockquote>

Not sure how this change happened. Should I discard it?
</blockquote></details>

Maybe there was some change that didn't get a `papi.d.ts` generated for it in a previous PR or something. Probably not a big deal.

**Review by rolfheij-sil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/256)* status: all files reviewed, 2 unresolved discussions (waiting on @tjcouch-sil)

___
*[`lib/papi-components/src/table.component.tsx` line 294 at r1](https://reviewable.io/reviews/paranext/paranext-core/256#-NYU6so48EEswx1clnP9:-NYXQlTcAebNMVK4y8J8:bo5bvot) ([raw file](https://github.com/paranext/paranext-core/blob/86b94a9beb930ad5aace6ca477999814702512d8/lib/papi-components/src/table.component.tsx#L294)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

This code currently does not allow for `editable` to be a function that takes the row and returns whether that specific cell should be editable. You can check if `editable` is a function with `typeof column.editable === 'function'`. Since, as I mentioned in the comment below (I split this one out so it is a bit less overwhelmingly large), we can make a cell not editable if the `editable` function returns false, maybe we can make a new function that layers over the return from the `editable` function and returns `false` if it's falsy. Something like:

```typescript
function editableFalsy(row: R) {
  return !!editable(row);
}
```

The double bang `!!` converts a truthy/falsey into actual `true` or `false`, so that will make it so people can return whatever truthy/falsey value they want, and it will properly set editable to `false`.
</blockquote></details>

I understand what you mean, but I have trouble converting it to actual code. Where would we want to put this extra function? And isn't it the responsibility of the extensions developer to return a usable value (i.e. a boolean)? The signature of the `editable` function is `((row: R) => boolean)`, so it can only return a boolean, right?

By the way, I just tried using it with a function, and it works. I guess `column.editable` also evaluates to `true` if a function is assigned to it.
___
*[`lib/papi-components/src/table.component.tsx` line 298 at r1](https://reviewable.io/reviews/paranext/paranext-core/256#-NYTd8oB2Gnnv586x3PY:-NYXM5Ul-2g1rBthvE1j:bwoh7wr) ([raw file](https://github.com/paranext/paranext-core/blob/86b94a9beb930ad5aace6ca477999814702512d8/lib/papi-components/src/table.component.tsx#L298)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

Yeah, it's a bit weird. I will recommend an alternative in a few moments, but some thoughts on `null` itself for learning's sake: I would recommend removing `renderEditCell` from the object via destructuring or `delete` or setting `renderEditCell` to `undefined` instead of `null`. [The check uses `!= null`](https://github.com/adazzle/react-data-grid/blob/c29bf0cd6116584eee71c26c51acc4874c485b45/src/utils/selectedCellUtils.ts#L24) (note `!=` instead of `!==`. Double equals `==` and `!=` perform type coercion, so they are more lenient than triple equals) which works with either `null` or `undefined`, and our style guide says to avoid `null`.

A few options:
1. Destructure out - probably works well
```typescript
const { renderEditCell, ...columnNotEditable } = column;
return columnNotEditable;
```
2. Delete - may be a good option if TypeScript doesn't show errors, but hopefully it won't
```typescript
const columnNotEditable = column;
delete columnNotEditable.renderEditCell;
return columnNotEditable;
```
3. Set to undefined (basically what you have now. This will leave `renderEditCell` on the object, but that's not a big deal)
`return { ...column, renderEditCell: undefined }`

However, instead of doing any of the above, I suggest setting `editable` to `false` in this case and leaving `renderEditCell` as it is. It seems [the check](https://github.com/adazzle/react-data-grid/blob/c29bf0cd6116584eee71c26c51acc4874c485b45/src/utils/selectedCellUtils.ts#L26) allows for `renderEditCell` to be defined as long as `editable` is specifically `false` or a function that returns `false` for a given row.

Also note this method changes the reference to each column from what is passed in. Kinda weird, but I don't know what else we would do with this method. Would be best to note in the `columns` prop jsdoc that we have some internal logic that shallow clones the columns so people know they can't use object reference equivalence to figure out which column they're using (if someone ever tries to do that).
</blockquote></details>

Nice, thanks for helping me understand. Option 1 works well, option 2 doesn't work (deleting a readonly prop is not allowed), haven't tried option 3 but it's basically the same as what I had before.
I've added a note on the `editable` prop

**Review by tjcouch-sil — COMMENTED** [review]
> Reviewed 6 of 9 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/256)* status: 7 of 10 files reviewed, 1 unresolved discussion (waiting on @rolfheij-sil)

___
*[`lib/papi-components/src/table.component.tsx` line 294 at r1](https://reviewable.io/reviews/paranext/paranext-core/256#-NYU6so48EEswx1clnP9:-NYeWKvY-pluLEXyE1DU:b-v54fre) ([raw file](https://github.com/paranext/paranext-core/blob/86b94a9beb930ad5aace6ca477999814702512d8/lib/papi-components/src/table.component.tsx#L294)):*
<details><summary><i>Previously, rolfheij-sil wrote…</i></summary><blockquote>

I understand what you mean, but I have trouble converting it to actual code. Where would we want to put this extra function? And isn't it the responsibility of the extensions developer to return a usable value (i.e. a boolean)? The signature of the `editable` function is `((row: R) => boolean)`, so it can only return a boolean, right?

By the way, I just tried using it with a function, and it works. I guess `column.editable` also evaluates to `true` if a function is assigned to it.
</blockquote></details>

The function would probably go right above the place where you're shallow cloning the column so you can make a new function for each column (since each column can have a unique `editable` function).

It *could* be the responsibility of the extension developer to return specifically a boolean, but I'm suggesting we don't put that responsibility on them. The issue you saw where you had to set `renderEditCell` to `null` was due to `undefined !== false` and `null !== false`. Falsy is not the same as `false` in JavaScript, which is causing all this confusion. I would say it is best to avoid making `false` different than falsy in all circumstances, which `adazzle` unfortunately did not do. Basically putting a function in there that converts a falsy that an extension developer provides to actual false just simplifies the api and makes it a lot harder to make unexpected functionality that looks like bugs.

Ah yes, you're right - an `editable` function would work here. Functions are truthy, so an `editable` function will enter this `if` statement if you don't provide a `renderEditCell` function. I didn't think about that this wouldn't actually cause any problems. Sorry I didn't think about that.

**Review by tjcouch-sil — APPROVED** [review]
:lgtm: Awesome!! Thanks for all the hard work on this. Looks great!

> Reviewed 3 of 9 files at r2, 4 of 4 files at r3, 12 of 12 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/256#-:-NZ7U6Ke8LJyeb_jWDMv:b-h71zuh)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @rolfheij-sil)

**Pull request merged**
