### PR TITLE
326 add aliases

### PR DESCRIPTION
**Pull request by katherinejensen00**
Add command line aliases for extensions, extension dirs, log levels, resources path, and packaged.

- - -
This change is [Reviewable](https://reviewable.io/reviews/paranext/paranext-core/734)

### CODE REVIEW

**Review by tjcouch-sil — CHANGES_REQUESTED** [review]
Awesome! Thanks for the good stuff. Just a couple little things.

> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/734#-:-Np1m01U3GeKMQ6CiHBK:b-gmyo5t)* status: all files reviewed, 2 unresolved discussions (waiting on @katherinejensen00)

___
*[`src/node/utils/command-line.util.ts` line 7 at r1](https://reviewable.io/reviews/paranext/paranext-core/734#-Np1WPvh13_HJ16IwJJW:-Np1WPvh13_HJ16IwJJX:bdgiyt) ([raw file](https://github.com/paranext/paranext-core/blob/3c9739dd6e23be62a1c6c2207eda0a891a7f7ab7/src/node/utils/command-line.util.ts#L7)):*
> ```XML
> 
> /**
>  * Command Line Arguments Extensions - Command-line argument that specifies extra individual
> ```

Looks like this got scrunched up by the auto-formatting. JSDocs are Markdown, so maybe each argument description was separated by a single space which can be condensed down to being on the same line since one single newline between lines doesn't do anything in Markdown. Maybe you could make this a list instead like this:

```typescript
/**
 * Command Line Arguments
 * - Extensions - ...
 * - ExtensionsDir - ...
 * ...
 */
```

or whatever you want to do. If you just want them separated by a line, you can put two newlines between each line.
___
*[`src/node/utils/command-line.util.ts` line 28 at r1](https://reviewable.io/reviews/paranext/paranext-core/734#-Np1WNE69oti9siLbNq7:-Np1WNE69oti9siLbNq8:bii3u9d) ([raw file](https://github.com/paranext/paranext-core/blob/3c9739dd6e23be62a1c6c2207eda0a891a7f7ab7/src/node/utils/command-line.util.ts#L28)):*
> ```XML
> }
> 
> export const extensions: CommandLineArgumentAliases = {
> ```

This needs to be renamed to be descriptive of what it is. Maybe `commandLineArgumentAliases`? Also needs a JSDoc describing it - maybe can just take the JSDoc from the `CommandLineArgumentAliases` type if you want.

**Review by katherinejensen00 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/734)* status: 2 of 4 files reviewed, 2 unresolved discussions (waiting on @tjcouch-sil)

___
*[`src/node/utils/command-line.util.ts` line 7 at r1](https://reviewable.io/reviews/paranext/paranext-core/734#-Np1WPvh13_HJ16IwJJW:-Np6GOhZDR9qGoWYIjBC:b-s018vz) ([raw file](https://github.com/paranext/paranext-core/blob/3c9739dd6e23be62a1c6c2207eda0a891a7f7ab7/src/node/utils/command-line.util.ts#L7)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

Looks like this got scrunched up by the auto-formatting. JSDocs are Markdown, so maybe each argument description was separated by a single space which can be condensed down to being on the same line since one single newline between lines doesn't do anything in Markdown. Maybe you could make this a list instead like this:

```typescript
/**
 * Command Line Arguments
 * - Extensions - ...
 * - ExtensionsDir - ...
 * ...
 */
```

or whatever you want to do. If you just want them separated by a line, you can put two newlines between each line.
</blockquote></details>

Good idea using the dashes to prevent weird restyling. Thanks!
___
*[`src/node/utils/command-line.util.ts` line 28 at r1](https://reviewable.io/reviews/paranext/paranext-core/734#-Np1WNE69oti9siLbNq7:-Np6G_MW3MI0_6y2OAw_:b-896fix) ([raw file](https://github.com/paranext/paranext-core/blob/3c9739dd6e23be62a1c6c2207eda0a891a7f7ab7/src/node/utils/command-line.util.ts#L28)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

This needs to be renamed to be descriptive of what it is. Maybe `commandLineArgumentAliases`? Also needs a JSDoc describing it - maybe can just take the JSDoc from the `CommandLineArgumentAliases` type if you want.
</blockquote></details>

Done.

**Review by tjcouch-sil — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/734)* status: all files reviewed, 3 unresolved discussions (waiting on @katherinejensen00)

___
*[`src/extension-host/global-this.model.ts` line 15 at r2](https://reviewable.io/reviews/paranext/paranext-core/734#-Np6HlO-3S7uKiGT5fPp:-Np6HlO00bv86mGy9UXm:bl53xpg) ([raw file](https://github.com/paranext/paranext-core/blob/3a4f1e15c85741ba0d5f2103a25d64caf5e225d9/src/extension-host/global-this.model.ts#L15)):*
> ```XML
> // #region command-line arguments
> 
> const isPackaged = getCommandLineSwitch(extensions[COMMAND_LINE_ARGS.Packaged][0]);
> ```

Looks like `getCommandLineSwitch` also needs to be updated to accept `COMMAND_LINE_ARGS` instead of just one string. That way, any of the options for the command line argument will work instead of just the first.
___
*[`src/node/utils/command-line.util.ts` line 28 at r1](https://reviewable.io/reviews/paranext/paranext-core/734#-Np1WNE69oti9siLbNq7:-Np6IzWj5xA4-bt9RABB:b-4cjdwy) ([raw file](https://github.com/paranext/paranext-core/blob/3c9739dd6e23be62a1c6c2207eda0a891a7f7ab7/src/node/utils/command-line.util.ts#L28)):*
<details><summary><i>Previously, katherinejensen00 wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Thanks for moving the JSDoc over! Looks like `extensions` still needs to be renamed.
___
*[`src/node/utils/command-line.util.ts` line 121 at r2](https://reviewable.io/reviews/paranext/paranext-core/734#-Np6IeNlD_D5jXS1mHQI:-Np6IeNlD_D5jXS1mHQJ:b-wqje0w) ([raw file](https://github.com/paranext/paranext-core/blob/3a4f1e15c85741ba0d5f2103a25d64caf5e225d9/src/node/utils/command-line.util.ts#L121)):*
> ```XML
>         index < process.argv.length - 1) ||
>       // If the next word is also an arg name, there was no actual argument provided
>       findNextCommandLineArgumentIndex(index) === index + 1,
> ```

Looks like this also needs to be swapped from `||` to `&&` and flipped to negative like `findNextCommandLineArgumentIndex(index) !== index + 1` or `findNextCommandLineArgumentIndex(index) > index + 1` like the other two conditions were flipped

**Review by tjcouch-sil — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/734)* status: all files reviewed, 1 unresolved discussion (waiting on @katherinejensen00)

___
*[`src/node/utils/command-line.util.ts` line 121 at r2](https://reviewable.io/reviews/paranext/paranext-core/734#-Np6IeNlD_D5jXS1mHQI:-NpLovQI5TyBc23il-yM:b-2mlfki) ([raw file](https://github.com/paranext/paranext-core/blob/3a4f1e15c85741ba0d5f2103a25d64caf5e225d9/src/node/utils/command-line.util.ts#L121)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

Looks like this also needs to be swapped from `||` to `&&` and flipped to negative like `findNextCommandLineArgumentIndex(index) !== index + 1` or `findNextCommandLineArgumentIndex(index) > index + 1` like the other two conditions were flipped
</blockquote></details>

I believe all three conditions need to be together with `&&` since all three need to be satisfied in order for this to work properly. So I think it needs to be something like this:

```typescript
(index >= 0 && index < process.argv.length - 1 && findNextCommandLineArgumentIndex(index) !== index + 1)
```

Sorry for the miscommunication!
___
*[`src/node/utils/command-line.util.ts` line 144 at r3](https://reviewable.io/reviews/paranext/paranext-core/734#-NpLnZCK4-b2bLr90pC_:-NpLnZCK4-b2bLr90pCa:b1gtd5o) ([raw file](https://github.com/paranext/paranext-core/blob/153220e3df29a393b1d65ddf7139b95622348727/src/node/utils/command-line.util.ts#L144)):*
> ```XML
>   const argNames: string[] = commandLineArgumentsAliases[argName];
>   let found = false;
>   argNames.forEach((alias) => {
> ```

Just a note(no action needed unless you particularly desire to change it): this could be refactored to use `argNames.some` instead of `found` and `argNames.forEach` :)

**Review by katherinejensen00 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/734)* status: all files reviewed, 1 unresolved discussion (waiting on @tjcouch-sil)

___
*[`src/node/utils/command-line.util.ts` line 121 at r2](https://reviewable.io/reviews/paranext/paranext-core/734#-Np6IeNlD_D5jXS1mHQI:-NpLshtRECbOlE4bJAKG:b-a5f94a) ([raw file](https://github.com/paranext/paranext-core/blob/3a4f1e15c85741ba0d5f2103a25d64caf5e225d9/src/node/utils/command-line.util.ts#L121)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

I believe all three conditions need to be together with `&&` since all three need to be satisfied in order for this to work properly. So I think it needs to be something like this:

```typescript
(index >= 0 && index < process.argv.length - 1 && findNextCommandLineArgumentIndex(index) !== index + 1)
```

Sorry for the miscommunication!
</blockquote></details>

I was going to fast and forgot to switch the or. Thank you for catching that!
___
*[`src/node/utils/command-line.util.ts` line 144 at r3](https://reviewable.io/reviews/paranext/paranext-core/734#-NpLnZCK4-b2bLr90pC_:-NpLsoAHCOadBVj3fCXf:b33omt9) ([raw file](https://github.com/paranext/paranext-core/blob/153220e3df29a393b1d65ddf7139b95622348727/src/node/utils/command-line.util.ts#L144)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

Just a note(no action needed unless you particularly desire to change it): this could be refactored to use `argNames.some` instead of `found` and `argNames.forEach` :)
</blockquote></details>

That is really helpful to know and learn. Thanks! :)

**Review by tjcouch-sil — APPROVED** [review]
:lgtm: thanks for the great work on this!

> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/734#-:-NpMVmQu3xU7aU8-9kzP:b-c9dus0)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Pull request merged**
