### PR TITLE
#454: Changed checking-results-list to be a webview

### PR DESCRIPTION
**Pull request by tombogle**
Also added a menu item in the Scripture editor menu to be able to show it.
Although this does not really address #454 specifically, having a real project is a necessary prerequisite to being able to get the Scripture editor associated with that project to scroll to the correct location and select the appropriate text.

- - -
This change is [Reviewable](https://reviewable.io/reviews/paranext/paranext-core/1076)

### CODE REVIEW

**Review by rolfheij-sil — CHANGES_REQUESTED** [review]
Looks good!

> Reviewed 14 of 17 files at r1, 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/1076#-:-O4vLBbZCS927ONMKARh:b-vs1prh)* status: all files reviewed, 9 unresolved discussions (waiting on @tombogle)

___
*[`tsconfig.json` line 44 at r1](https://reviewable.io/reviews/paranext/paranext-core/1076#-O4pZF2V6fq2qhSQlkJJ:-O4pZF2V6fq2qhSQlkJK:bqm53ib) ([raw file](https://github.com/paranext/paranext-core/blob/2c4c54e2a166752dddc5331dcd29a14e4326b643/tsconfig.json#L44)):*
> ```jsonc
>     "src",
>     "assets",
>     "extensions/src/platform-scripture/src/checking-results-list.web-view.tsx",
> ```

Why are these included here? Doesn't seem right
___
*[`extensions/src/platform-scripture/src/checking-results-list.web-view.tsx` line 12 at r2](https://reviewable.io/reviews/paranext/paranext-core/1076#-O4vECag2J0Ayg_AyeVe:-O4vECah4QYO77Ffjb8W:b-4pe9io) ([raw file](https://github.com/paranext/paranext-core/blob/5fc4b5349b74f4d2a86bccdf4ae48e16ad1676b6/extensions/src/platform-scripture/src/checking-results-list.web-view.tsx#L12)):*
> ```XML
> import { badLeftoversCheck, engineProblemsCheck } from './testing/test-scripture-checks';
> 
> export type CheckingResultsListProps = ScriptureResultsViewerProps & {
> ```

Is this type being used anywhere? I can't find any references to it
___
*[`extensions/src/platform-scripture/src/checking-results-list.web-view.tsx` line 19 at r2](https://reviewable.io/reviews/paranext/paranext-core/1076#-O4vFtSR40oYHE3C5S8g:-O4vFtSR40oYHE3C5S8h:bumz4l7) ([raw file](https://github.com/paranext/paranext-core/blob/5fc4b5349b74f4d2a86bccdf4ae48e16ad1676b6/extensions/src/platform-scripture/src/checking-results-list.web-view.tsx#L19)):*
> ```XML
> 
> const getLabel = (
>   project: string | undefined,
> ```

Maybe rename to `projectName` to make it clear we're dealing with a string here
___
*[`extensions/src/platform-scripture/src/checking-results-list.web-view.tsx` line 37 at r2](https://reviewable.io/reviews/paranext/paranext-core/1076#-O4vFhzY7DOkcYjj0x_E:-O4vFhzY7DOkcYjj0x_F:bumz4l7) ([raw file](https://github.com/paranext/paranext-core/blob/5fc4b5349b74f4d2a86bccdf4ae48e16ad1676b6/extensions/src/platform-scripture/src/checking-results-list.web-view.tsx#L37)):*
> ```XML
> 
> global.webViewComponent = function CheckingResultsListWebView({ useWebViewState }: WebViewProps) {
>   const [project] = useWebViewState('projectName', '') ?? 'Dummy project';
> ```

Maybe rename to `projectName` to make it clear we're dealing with a string here
___
*[`extensions/src/platform-scripture/src/checking-results-list.web-view.tsx` line 49 at r2](https://reviewable.io/reviews/paranext/paranext-core/1076#-O4vGvKp9fJFDEMO8P9T:-O4vGvKp9fJFDEMO8P9U:b-cy05jn) ([raw file](https://github.com/paranext/paranext-core/blob/5fc4b5349b74f4d2a86bccdf4ae48e16ad1676b6/extensions/src/platform-scripture/src/checking-results-list.web-view.tsx#L49)):*
> ```XML
> 
>   const [lastUpdateTimestamp, setLastUpdateTimestamp] = useState<string | undefined>(undefined);
>   const [currentSources, setCurrentSources] = useState(sources);
> ```

Do we need this? `sources` and `currentSources` are basically the same thing now, right?
___
*[`extensions/src/platform-scripture/src/checking-results-list.web-view.tsx` line 67 at r2](https://reviewable.io/reviews/paranext/paranext-core/1076#-O4vHcPV19ZXPys_FZrJ:-O4vHcPV19ZXPys_FZrK:b9sgug6) ([raw file](https://github.com/paranext/paranext-core/blob/5fc4b5349b74f4d2a86bccdf4ae48e16ad1676b6/extensions/src/platform-scripture/src/checking-results-list.web-view.tsx#L67)):*
> ```XML
>       handleResultsUpdated();
>     }
>   }, [onRerun, sources, handleResultsUpdated]);
> ```

All of these items are stable now, right? Do you expect them to change in the future?
___
*[`extensions/src/platform-scripture/src/testing/test-scripture-checks.ts` line 56 at r2](https://reviewable.io/reviews/paranext/paranext-core/1076#-O4vJ9Fz6DSxA0sEyJHP:-O4vJ9Fz6DSxA0sEyJHQ:bka8hi) ([raw file](https://github.com/paranext/paranext-core/blob/5fc4b5349b74f4d2a86bccdf4ae48e16ad1676b6/extensions/src/platform-scripture/src/testing/test-scripture-checks.ts#L56)):*
> ```XML
>   'Iffy meatloaf',
>   'Dried out chicken',
>   'Stinky cheese',
> ```

It's always a bad day when the stinky cheese finds it way into your Bible translation project again...
___
*[`extensions/src/platform-scripture-editor/contributions/localizedStrings.json` line 15 at r2](https://reviewable.io/reviews/paranext/paranext-core/1076#-O4vI3X2EzkRMNvB53bn:-O4vI3X2EzkRMNvB53bo:b-c4mpmv) ([raw file](https://github.com/paranext/paranext-core/blob/5fc4b5349b74f4d2a86bccdf4ae48e16ad1676b6/extensions/src/platform-scripture-editor/contributions/localizedStrings.json#L15)):*
> ```JSON
>       "%webView_platformScriptureEditor_charactersInventory%": "Inventory: Characters",
>       "%webView_platformScriptureEditor_repeatedWordsInventory%": "Inventory: Repeated Words",
>       "%webView_platformScriptureEditor_runBasicChecks%": "Run Basic Checks...",
> ```

Why the `...`?
___
*[`extensions/src/platform-scripture-editor/contributions/menus.json` line 91 at r1](https://reviewable.io/reviews/paranext/paranext-core/1076#-O4q2X0T-yCn-tuL6fB1:-O4q2X0T-yCn-tuL6fB2:b2fmvbl) ([raw file](https://github.com/paranext/paranext-core/blob/2c4c54e2a166752dddc5331dcd29a14e4326b643/extensions/src/platform-scripture-editor/contributions/menus.json#L91)):*
> ```JSON
>             "group": "platformScriptureEditor.checks",
>             "order": 1,
>             "command": "platformScripture.runBasicChecks"
> ```

This command will bring up the results view now. I guess in the future we want it to bring up the dialog that lets you select the checks that you want to run and lets you start the actual checks?

**Review by tombogle — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/1076)* status: all files reviewed, 6 unresolved discussions (waiting on @rolfheij-sil)

___
*[`tsconfig.json` line 44 at r1](https://reviewable.io/reviews/paranext/paranext-core/1076#-O4pZF2V6fq2qhSQlkJJ:-O4vOS1W8yrFjlx7WkO9:b-wmvgd2) ([raw file](https://github.com/paranext/paranext-core/blob/2c4c54e2a166752dddc5331dcd29a14e4326b643/tsconfig.json#L44)):*
<details><summary><i>Previously, rolfheij-sil (Rolf Heij) wrote…</i></summary><blockquote>

Why are these included here? Doesn't seem right
</blockquote></details>

No idea. One of them doesn't even exist. I'm pretty sure I didn't add them manually, at least not on purpose.
___
*[`extensions/src/platform-scripture-editor/contributions/localizedStrings.json` line 15 at r2](https://reviewable.io/reviews/paranext/paranext-core/1076#-O4vI3X2EzkRMNvB53bn:-O4vSckx555xlCsQzsH3:bg4sevw) ([raw file](https://github.com/paranext/paranext-core/blob/5fc4b5349b74f4d2a86bccdf4ae48e16ad1676b6/extensions/src/platform-scripture-editor/contributions/localizedStrings.json#L15)):*
<details><summary><i>Previously, rolfheij-sil (Rolf Heij) wrote…</i></summary><blockquote>

Why the `...`?
</blockquote></details>

At least in the olden days, ellipses on a menu command told the user that the command was going to display a modal dialog box. I don't know if that's still even a thing in modern web menus. of course, currently this command does NOT do that, but in my mind this command will eventually display the Run Basic Checks dialog box, and then when the checks are run and have results ready to display, that will trigger the results list to be displayed (or updated if it is already being displayed).
___
*[`extensions/src/platform-scripture-editor/contributions/menus.json` line 91 at r1](https://reviewable.io/reviews/paranext/paranext-core/1076#-O4q2X0T-yCn-tuL6fB1:-O4vTOOA4c3X80kp6EMV:b-ecwtg3) ([raw file](https://github.com/paranext/paranext-core/blob/2c4c54e2a166752dddc5331dcd29a14e4326b643/extensions/src/platform-scripture-editor/contributions/menus.json#L91)):*
<details><summary><i>Previously, rolfheij-sil (Rolf Heij) wrote…</i></summary><blockquote>

This command will bring up the results view now. I guess in the future we want it to bring up the dialog that lets you select the checks that you want to run and lets you start the actual checks?
</blockquote></details>

That's my belief

**Review by rolfheij-sil — COMMENTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/1076)* status: all files reviewed, 3 unresolved discussions (waiting on @tombogle)

**Review by irahopkinson — DISMISSED** [review]
:lgtm:

Sorry for the delay, I started reviewing this yesterday but ran out of time. I probably should have just published my partial review. Fortunately, @rolfheij-sil got you unblocked.

> Reviewed 17 of 17 files at r1, 4 of 4 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/1076#-:-O4w1i1d3xT7ZlzMEG0X:btcxwd4)* status: all files reviewed, 4 unresolved discussions (waiting on @tombogle)

___
*[`extensions/src/platform-scripture/src/main.ts` line 90 at r1](https://reviewable.io/reviews/paranext/paranext-core/1076#-O4w0qdu30Qdjx76GDf3:-O4w0qdu30Qdjx76GDf4:b-go33x9) ([raw file](https://github.com/paranext/paranext-core/blob/2c4c54e2a166752dddc5331dcd29a14e4326b643/extensions/src/platform-scripture/src/main.ts#L90)):*
> ```XML
>   if (!projectId) {
>     logger.debug('No project!');
>     return undefined;
> ```

Nit I'm pretty sure you can just do `return;` here.
___
*[`tsconfig.json` line 44 at r1](https://reviewable.io/reviews/paranext/paranext-core/1076#-O4pZF2V6fq2qhSQlkJJ:-O4w1TiDD0jjDu-VMJCb:bth6bbf) ([raw file](https://github.com/paranext/paranext-core/blob/2c4c54e2a166752dddc5331dcd29a14e4326b643/tsconfig.json#L44)):*
<details><summary><i>Previously, tombogle (Tom Bogle) wrote…</i></summary><blockquote>

No idea. One of them doesn't even exist. I'm pretty sure I didn't add them manually, at least not on purpose.
</blockquote></details>

Likely VS Code was trying to be helpful by automatically changing this file but it doesn't know we have a monorepo. Thanks for reverting.

**Review by tombogle — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/1076)* status: 15 of 17 files reviewed, 4 unresolved discussions (waiting on @irahopkinson and @rolfheij-sil)

___
*[`extensions/src/platform-scripture/src/checking-results-list.web-view.tsx` line 12 at r2](https://reviewable.io/reviews/paranext/paranext-core/1076#-O4vECag2J0Ayg_AyeVe:-O4vVm1MAKiZqqf-DMCz:b-896fix) ([raw file](https://github.com/paranext/paranext-core/blob/5fc4b5349b74f4d2a86bccdf4ae48e16ad1676b6/extensions/src/platform-scripture/src/checking-results-list.web-view.tsx#L12)):*
<details><summary><i>Previously, rolfheij-sil (Rolf Heij) wrote…</i></summary><blockquote>

Is this type being used anywhere? I can't find any references to it
</blockquote></details>

Done.
___
*[`extensions/src/platform-scripture/src/main.ts` line 90 at r1](https://reviewable.io/reviews/paranext/paranext-core/1076#-O4w0qdu30Qdjx76GDf3:-O4w9LV5EOOzDgeEEaWP:bmu169s) ([raw file](https://github.com/paranext/paranext-core/blob/2c4c54e2a166752dddc5331dcd29a14e4326b643/extensions/src/platform-scripture/src/main.ts#L90)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

Nit I'm pretty sure you can just do `return;` here.
</blockquote></details>

Results in error  Async function 'runPlatformBasicChecks' expected no return value  consistent-return

**Review by irahopkinson — APPROVED** [review]
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/1076)* status: all files reviewed, 3 unresolved discussions (waiting on @rolfheij-sil and @tombogle)

___
*[`extensions/src/platform-scripture/src/main.ts` line 90 at r1](https://reviewable.io/reviews/paranext/paranext-core/1076#-O4w0qdu30Qdjx76GDf3:-O4wIJIsE-KkVmKJKxjE:b-40hj94) ([raw file](https://github.com/paranext/paranext-core/blob/2c4c54e2a166752dddc5331dcd29a14e4326b643/extensions/src/platform-scripture/src/main.ts#L90)):*
<details><summary><i>Previously, tombogle (Tom Bogle) wrote…</i></summary><blockquote>

Results in error  Async function 'runPlatformBasicChecks' expected no return value  consistent-return
</blockquote></details>

Yep, you are right. I did a little investigation and added a comment to #1085.

**Review by rolfheij-sil — APPROVED** [review]
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/1076)* status: all files reviewed, 2 unresolved discussions (waiting on @tombogle)

**Review by rolfheij-sil — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/1076)* status: 15 of 17 files reviewed, 2 unresolved discussions (waiting on @irahopkinson and @tombogle)

**Review by tombogle — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/1076)* status: 15 of 17 files reviewed, all discussions resolved (waiting on @irahopkinson and @rolfheij-sil)

___
*[`extensions/src/platform-scripture/src/checking-results-list.web-view.tsx` line 49 at r2](https://reviewable.io/reviews/paranext/paranext-core/1076#-O4vGvKp9fJFDEMO8P9T:-O5YjrlO6vvjCXqjVA7f:beq2ia3) ([raw file](https://github.com/paranext/paranext-core/blob/5fc4b5349b74f4d2a86bccdf4ae48e16ad1676b6/extensions/src/platform-scripture/src/checking-results-list.web-view.tsx#L49)):*
<details><summary><i>Previously, rolfheij-sil (Rolf Heij) wrote…</i></summary><blockquote>

Do we need this? `sources` and `currentSources` are basically the same thing now, right?
</blockquote></details>

Code has changed since this comment.
___
*[`extensions/src/platform-scripture/src/checking-results-list.web-view.tsx` line 67 at r2](https://reviewable.io/reviews/paranext/paranext-core/1076#-O4vHcPV19ZXPys_FZrJ:-O5YjzRG7F4KGqU91zxc:beq2ia3) ([raw file](https://github.com/paranext/paranext-core/blob/5fc4b5349b74f4d2a86bccdf4ae48e16ad1676b6/extensions/src/platform-scripture/src/checking-results-list.web-view.tsx#L67)):*
<details><summary><i>Previously, rolfheij-sil (Rolf Heij) wrote…</i></summary><blockquote>

All of these items are stable now, right? Do you expect them to change in the future?
</blockquote></details>

Code has changed since this comment.

**Review by tjcouch-sil — APPROVED** [review]
:lgtm:

> Reviewed 10 of 17 files at r1, 2 of 4 files at r2, 1 of 1 files at r3, 2 of 2 files at r4, 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/1076#-:-O5Yv4W23Dg5gVGgwpJd:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Pull request merged**
