### PR TITLE
Update electron

### PR DESCRIPTION
**Pull request by irahopkinson**
- delete `node_modules/electron/` folder before running `npm i`
- fix deprecated `protocol.registerBufferProtocol()`
- bump minimum node version to what is required by electron v24 (electron v25 minimum is TBD)
- also update a few minor versions

- - -
This change is [Reviewable](https://reviewable.io/reviews/paranext/paranext-core/312)

### CODE REVIEW

**Review by tjcouch-sil — COMMENTED** [review]
This looks good to me! But I don't know all the inner workings, so I'll defer to @lyonsil on this one. Thanks!

> Reviewed 12 of 12 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/312#-:-Na7Ggrk21ZBrMpmliqi:b-yk46uf)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by lyonsil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/312)* status: :shipit: complete! all files reviewed, all discussions resolved

___
*[`src/main/services/extension-asset-protocol.service.ts` line 62 at r1](https://reviewable.io/reviews/paranext/paranext-core/312#-Na7Org_68KBk0Ib08Lf:-Na7QbKU3j4aucoo2pIj:bnyqffg) ([raw file](https://github.com/paranext/paranext-core/blob/4c2670e1a378cee40d4d6fd7cfa61b2ee03bdc1f/src/main/services/extension-asset-protocol.service.ts#L62)):*
<details><summary><i>Previously, lyonsil (Matt Lyons) wrote…</i></summary><blockquote>

While at first glance this seems reasonable while reading the code, it doesn't work in practice.  I pulled the branch, and the Q icon fails to load with an error about an unknown URL scheme.



</blockquote></details>

Actually after deleting the electron node modules and rerunning "npm install" it works now.  I missed that the first line was an instruction to the developer.

**Review by lyonsil — COMMENTED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/312#-:-Na7T32xBx02tw1bYOy8:bg7igkv)* status: :shipit: complete! all files reviewed, all discussions resolved

___
*[`src/main/services/extension-asset-protocol.service.ts` line 103 at r1](https://reviewable.io/reviews/paranext/paranext-core/312#-Na7SPtZ7IJERF0mzS9C:-Na7SPtZ7IJERF0mzS9D:b5tpocv) ([raw file](https://github.com/paranext/paranext-core/blob/4c2670e1a378cee40d4d6fd7cfa61b2ee03bdc1f/src/main/services/extension-asset-protocol.service.ts#L103)):*
> ```XML
>         status: StatusCodes.OK,
>         headers: {
>           'Content-Type': getMimeTypeForFileName(asset),
> ```

I don't remember with 100% certainty, but I think I had to specifically use the MIME type before instead of Content type to get the image previews to work in the Chromium development tools.  It looks like the Content types work now, though.

**Review by lyonsil — APPROVED** [review]
> Reviewed 12 of 12 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/312)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
