### PR TITLE
fix twMerge to use our prefix

### PR DESCRIPTION
**Pull request by Sebastian-ubs**
This will fix class duplication when trying to overwrite a class from a component.

Thank you @tjcouch-sil 

- - -
This change is [Reviewable](https://reviewable.io/reviews/paranext/paranext-core/999)

### CODE REVIEW

**Review by Sebastian-ubs — COMMENTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/999)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @Sebastian-ubs)

**Review by Sebastian-ubs — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/999#-:-O1bQr7d0rJZG1SkRk7t:bnfp4nl)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @Sebastian-ubs)

**Review by Sebastian-ubs — COMMENTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/999)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @Sebastian-ubs)

**Review by tjcouch-sil — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/999#-:-O1bSWQOEu7pNoFBsWEh:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Pull request merged**
