### PR TITLE
Resolved infinite loop between two layering PDPs, added new class to make resolving this easier

### PR DESCRIPTION
**Pull request by tjcouch-sil**
[Breaking] Had to add a new requirement for layering PDPFs. Just extend from the class `LayeringProjectDataProviderEngineFactory` available on `@papi/backend` in order to fulfill this requirement automatically.
- Long explanation of the requirement: `getAvailableProjects` now receives a parameter which is some subset of the filtering options being used while calling `getAvailableProjects` on this PDPF. The subset of filtering options will primarily contain some set of PDPF ids to exclude from the search in order to avoid infinitely recurring calls to other layering PDPFs' `getAvailableProjects`. Base PDPFs can ignore that parameter, but layering PDPFs that call `papi.projectLookup.getMetadataForAllProjects` to get some set of existing project ids to layer over **absolutely must** now merge the filter options passed into `getAvailableProjects` into the filter options they use when calling `papi.projectLookup.getMetadataForAllProjects`.

- - -
This change is [Reviewable](https://reviewable.io/reviews/paranext/paranext-core/944)

### CODE REVIEW

**Review by lyonsil — APPROVED** [review]
> Reviewed 12 of 12 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/944)* status: all files reviewed, 1 unresolved discussion (waiting on @tjcouch-sil)

___
*[`src/shared/models/project-data-provider-engine-factory.model.ts` line 27 at r1](https://reviewable.io/reviews/paranext/paranext-core/944#-O-goh125WgUSsz_diHC:-O-goh125WgUSsz_diHD:b-y7fcfj) ([raw file](https://github.com/paranext/paranext-core/blob/35c7df5d2eeb597f89ab489eafae955e70aff178/src/shared/models/project-data-provider-engine-factory.model.ts#L27)):*
> ```XML
>  * {@link IBaseProjectDataProvider} and {@link ProjectDataProviderInterfaces} for more information.
>  *
>  * WARNING: For Layering PDPFs, `getAvailableProjects` has very specific requirements that
> ```

It seems a little odd to put a big warning here without explaining the warning in some way. This and the following paragraph make it seem like there is a special handshake that gets kicked out of the club if you don't know it.

**Review by tjcouch-sil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/944)* status: 10 of 12 files reviewed, 1 unresolved discussion (waiting on @lyonsil)

___
*[`src/shared/models/project-data-provider-engine-factory.model.ts` line 27 at r1](https://reviewable.io/reviews/paranext/paranext-core/944#-O-goh125WgUSsz_diHC:-O-gydFdDnCyBYs5R_uC:bca566w) ([raw file](https://github.com/paranext/paranext-core/blob/35c7df5d2eeb597f89ab489eafae955e70aff178/src/shared/models/project-data-provider-engine-factory.model.ts#L27)):*
<details><summary><i>Previously, lyonsil (Matt Lyons) wrote…</i></summary><blockquote>

It seems a little odd to put a big warning here without explaining the warning in some way. This and the following paragraph make it seem like there is a special handshake that gets kicked out of the club if you don't know it.
</blockquote></details>



Does the link make it better?

**Review by lyonsil — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/944#-:-O-h4M4R11CDAWcdDdT7:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

___
*[`src/shared/models/project-data-provider-engine-factory.model.ts` line 27 at r1](https://reviewable.io/reviews/paranext/paranext-core/944#-O-goh125WgUSsz_diHC:-O-h40vN3BbkcpfFxMaR:b-we5x7p) ([raw file](https://github.com/paranext/paranext-core/blob/35c7df5d2eeb597f89ab489eafae955e70aff178/src/shared/models/project-data-provider-engine-factory.model.ts#L27)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>



Does the link make it better?
</blockquote></details>

LOL - At first nope, but now that I see it in Reviewable I'm all good. :smile:

**Review by tjcouch-sil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/944)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

___
*[`src/shared/models/project-data-provider-engine-factory.model.ts` line 27 at r1](https://reviewable.io/reviews/paranext/paranext-core/944#-O-goh125WgUSsz_diHC:-O-h6kc9Cd6NFL2A0Hbt:b1lyc0l) ([raw file](https://github.com/paranext/paranext-core/blob/35c7df5d2eeb597f89ab489eafae955e70aff178/src/shared/models/project-data-provider-engine-factory.model.ts#L27)):*
<details><summary><i>Previously, lyonsil (Matt Lyons) wrote…</i></summary><blockquote>

LOL - At first nope, but now that I see it in Reviewable I'm all good. :smile: 


</blockquote></details>

Oh sorry I meant the `{@link...` I added in the TSDoc. Thanks!

**Pull request merged**
