### PR TITLE
Allow read/write of project settings in C#

### PR DESCRIPTION
**Pull request by lyonsil**
This change is [Reviewable](https://reviewable.io/reviews/paranext/paranext-core/857)

### CODE REVIEW

**Review by tjcouch-sil — CHANGES_REQUESTED** [review]
Awesome! Thanks for the great work on this. Excited to have project settings almost functional!!

> Reviewed 7 of 7 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/857#-:-NvcmNYa-s_uM5o_d2Tv:bwiwfpp)* status: all files reviewed, 5 unresolved discussions (waiting on @lyonsil)

___
*[`c-sharp/Projects/ParatextProjectDataProvider.cs` line 72 at r1](https://reviewable.io/reviews/paranext/paranext-core/857#-NvcLODc3s0RIHKRMyR8:-NvcLODc3s0RIHKRMyR9:bw6xo5g) ([raw file](https://github.com/paranext/paranext-core/blob/946b4edea406db3175ea32b652bca261fc01b00a/c-sharp/Projects/ParatextProjectDataProvider.cs#L72)):*
> ```Smalltalk
>     }
> 
>     private ResponseToRequest ResetProjectSetting(string key)
> ```

Reset should actually just remove the value so that Get will return the default again. Is this reasonably feasible in this iteration? I know you mentioned that this doesn't yet support non-Paratext settings, so maybe it makes more sense to rework it when we do that.
___
*[`c-sharp/Projects/ParatextProjectDataProvider.cs` line 42 at r2](https://reviewable.io/reviews/paranext/paranext-core/857#-Nvck142Dvb8ihhQiKVx:-Nvck142Dvb8ihhQiKVy:b-6phd80) ([raw file](https://github.com/paranext/paranext-core/blob/b66775acab077d9ea3ac17f1db0ecebf031d1697/c-sharp/Projects/ParatextProjectDataProvider.cs#L42)):*
> ```Smalltalk
>         return functionName switch
>         {
>             "resetSetting" => ResetProjectSetting(args[0]!.ToJsonString()),
> ```

This needs to run `SendDataUpdateEvent` with the return from this function, right? Just like [the setters](https://github.com/paranext/paranext-core/blob/main/c-sharp/Projects/ProjectDataProvider.cs#L90) (or of course you can implement this whatever other way you want)
___
*[`c-sharp/Projects/ParatextProjectStorageInterpreter.cs` line 217 at r1](https://reviewable.io/reviews/paranext/paranext-core/857#-NvcTT5g8mCR1cDTNiCu:-NvcTT5g8mCR1cDTNiCv:bjpkn4g) ([raw file](https://github.com/paranext/paranext-core/blob/946b4edea406db3175ea32b652bca261fc01b00a/c-sharp/Projects/ParatextProjectStorageInterpreter.cs#L217)):*
> ```Smalltalk
>                     ? JsonConvert.SerializeObject(currentValueResponse.Contents)
>                     : "";
>                 if (!ProjectSettingsService.IsValid(
> ```

I considered what would happen if `ProjectSettingsService.IsValid` were to throw an exception instead of just returning false, and I think I traced up to `PapiClient.HandleIncomingMessage` which just writes the exception to the console. Should this have a try/catch to make sure it sends a proper fail message? Or maybe `PapiClient.HandleIncomingMessage` should! Or maybe I missed something along the way up the call stack.
___
*[`c-sharp/Projects/ParatextProjectStorageInterpreter.cs` line 230 at r1](https://reviewable.io/reviews/paranext/paranext-core/857#-NvcTvUn-E-HrkY2N1qn:-NvcTvUn-E-HrkY2N1qo:b1d0xxi) ([raw file](https://github.com/paranext/paranext-core/blob/946b4edea406db3175ea32b652bca261fc01b00a/c-sharp/Projects/ParatextProjectStorageInterpreter.cs#L230)):*
> ```Smalltalk
>                 if (paratextSettingName == null)
>                     return ResponseToRequest.Failed(
>                         $"No known Paratext setting for {scope.DataQualifier}");
> ```

I think we will want to save non-Paratext project settings into Paratext projects to maintain back/forward compatibility, right? Maybe we can save the non-Paratext settings separately in a json file somewhere?

You mentioned you haven't done this yet - does that mean you have in mind filing a separate issue on it? Might be reasonable.

Also I wonder if we should consider reworking the `ParatextStandard` file structure so everything is in the Paratext-formatted file structure. I realized while considering this non-Paratext settings thing that `ParatextStandard` isn't really quite exactly a PT9 project since we also have that separate extensions folder. Wonder if it might be worth jamming all our Platform.Bible-specific stuff in some folder in the PT9-structure plugin data folder so it gets picked up by S/R. Basically just keeping everything contained within the Paratext 9 project folder so we really are reading from the PT9 structure instead of almost the PT9 structure but *still* need an import/export transformation. Would be glad to discuss sometime as this is not really quite the topic of this issue.

Note I am not suggesting we should put extension data in the PT9-structure plugin data folder as if it were a PT9 plugin like I was arguing at way too much length that one time... :joy:
___
*[`extensions/src/usfm-data-provider/index.d.ts` line 21 at r1](https://reviewable.io/reviews/paranext/paranext-core/857#-NvcioIa5WvUXkdlFEFJ:-NvcioIa5WvUXkdlFEFK:bybr0q5) ([raw file](https://github.com/paranext/paranext-core/blob/946b4edea406db3175ea32b652bca261fc01b00a/extensions/src/usfm-data-provider/index.d.ts#L21)):*
> ```XML
>   };
> 
>   export type UsfmDataProvider = IProjectDataProvider<UsfmProviderDataTypes>;
> ```

I believe this is representing the [usfm data provider](https://github.com/paranext/paranext-core/blob/main/c-sharp/NetworkObjects/UsfmDataProvider.cs) itself (which we should probably just remove), so it actually is a data provider.
___
*[`extensions/src/usfm-data-provider/index.d.ts` line 363 at r1](https://reviewable.io/reviews/paranext/paranext-core/857#-Nvcj3xf0EjtqO9N8Fkf:-Nvcj3xf0EjtqO9N8Fkg:b-t4jypw) ([raw file](https://github.com/paranext/paranext-core/blob/946b4edea406db3175ea32b652bca261fc01b00a/extensions/src/usfm-data-provider/index.d.ts#L363)):*
> ```XML
> 
>   export type ParatextStandardProjectDataProvider =
>     IProjectDataProvider<ParatextStandardProjectDataTypes>;
> ```

Good catch! Thanks!

**Review by lyonsil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/857)* status: all files reviewed, 3 unresolved discussions (waiting on @tjcouch-sil)

___
*[`c-sharp/Projects/ParatextProjectDataProvider.cs` line 72 at r1](https://reviewable.io/reviews/paranext/paranext-core/857#-NvcLODc3s0RIHKRMyR8:-NvglXl5912QDhC6LLJ4:b17ppt8) ([raw file](https://github.com/paranext/paranext-core/blob/946b4edea406db3175ea32b652bca261fc01b00a/c-sharp/Projects/ParatextProjectDataProvider.cs#L72)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

Reset should actually just remove the value so that Get will return the default again. Is this reasonably feasible in this iteration? I know you mentioned that this doesn't yet support non-Paratext settings, so maybe it makes more sense to rework it when we do that.
</blockquote></details>

Yeah this is pretty specific to Paratext. Since we're trying to maintain compatibility with Paratext, I think it might be clearer to just do what we're doing here (i.e., overwrite the value with the default) so the `Settings.xml` file still has a value stored for the setting. Do you have concerns with that?
___
*[`c-sharp/Projects/ParatextProjectDataProvider.cs` line 42 at r2](https://reviewable.io/reviews/paranext/paranext-core/857#-Nvck142Dvb8ihhQiKVx:-NvgghSfArm3JYHSFtrU:b-jhc74v) ([raw file](https://github.com/paranext/paranext-core/blob/b66775acab077d9ea3ac17f1db0ecebf031d1697/c-sharp/Projects/ParatextProjectDataProvider.cs#L42)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

This needs to run `SendDataUpdateEvent` with the return from this function, right? Just like [the setters](https://github.com/paranext/paranext-core/blob/main/c-sharp/Projects/ProjectDataProvider.cs#L90) (or of course you can implement this whatever other way you want)
</blockquote></details>

Yeah I was thinking this was being taken care of with the `Set` call, but you're right that it doesn't in this case.  Fixed now.
___
*[`c-sharp/Projects/ParatextProjectStorageInterpreter.cs` line 217 at r1](https://reviewable.io/reviews/paranext/paranext-core/857#-NvcTT5g8mCR1cDTNiCu:-NvhGnuS9xqlKCT6kQi9:btj5ubw) ([raw file](https://github.com/paranext/paranext-core/blob/946b4edea406db3175ea32b652bca261fc01b00a/c-sharp/Projects/ParatextProjectStorageInterpreter.cs#L217)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

I considered what would happen if `ProjectSettingsService.IsValid` were to throw an exception instead of just returning false, and I think I traced up to `PapiClient.HandleIncomingMessage` which just writes the exception to the console. Should this have a try/catch to make sure it sends a proper fail message? Or maybe `PapiClient.HandleIncomingMessage` should! Or maybe I missed something along the way up the call stack.
</blockquote></details>

`ProjectDataProvider.HandleRequest` has a general `try`/`catch` around all `get` and `set` calls. I suppose I do need to make sure the `reset` call has something similar, though, since it doesn't go through the normal `get`/`set` path. Fixed.
___
*[`c-sharp/Projects/ParatextProjectStorageInterpreter.cs` line 230 at r1](https://reviewable.io/reviews/paranext/paranext-core/857#-NvcTvUn-E-HrkY2N1qn:-NvhHeJL4UI5f8-M8o2b:b-v8ti8e) ([raw file](https://github.com/paranext/paranext-core/blob/946b4edea406db3175ea32b652bca261fc01b00a/c-sharp/Projects/ParatextProjectStorageInterpreter.cs#L230)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

I think we will want to save non-Paratext project settings into Paratext projects to maintain back/forward compatibility, right? Maybe we can save the non-Paratext settings separately in a json file somewhere?

You mentioned you haven't done this yet - does that mean you have in mind filing a separate issue on it? Might be reasonable.

Also I wonder if we should consider reworking the `ParatextStandard` file structure so everything is in the Paratext-formatted file structure. I realized while considering this non-Paratext settings thing that `ParatextStandard` isn't really quite exactly a PT9 project since we also have that separate extensions folder. Wonder if it might be worth jamming all our Platform.Bible-specific stuff in some folder in the PT9-structure plugin data folder so it gets picked up by S/R. Basically just keeping everything contained within the Paratext 9 project folder so we really are reading from the PT9 structure instead of almost the PT9 structure but *still* need an import/export transformation. Would be glad to discuss sometime as this is not really quite the topic of this issue.

Note I am not suggesting we should put extension data in the PT9-structure plugin data folder as if it were a PT9 plugin like I was arguing at way too much length that one time... :joy:
</blockquote></details>

I figured out a way to save "non-standard" Paratext settings into `Settings.xml`, so there is no reason to worry about other files. 
___
*[`extensions/src/usfm-data-provider/index.d.ts` line 21 at r1](https://reviewable.io/reviews/paranext/paranext-core/857#-NvcioIa5WvUXkdlFEFJ:-NvhTZOlBpt4J_ZxmpSO:b-896fix) ([raw file](https://github.com/paranext/paranext-core/blob/946b4edea406db3175ea32b652bca261fc01b00a/extensions/src/usfm-data-provider/index.d.ts#L21)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

I believe this is representing the [usfm data provider](https://github.com/paranext/paranext-core/blob/main/c-sharp/NetworkObjects/UsfmDataProvider.cs) itself (which we should probably just remove), so it actually is a data provider.
</blockquote></details>

Done.

**Review by tjcouch-sil — APPROVED** [review]
:lgtm: Awesome. Thanks! Just one thing to double check and resolve yourself if it is correct, and you're good to go

> Reviewed 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/857#-:-Nvlm9zl02_mFvBazP9y:bp6v7qm)* status: all files reviewed, 1 unresolved discussion (waiting on @lyonsil)

___
*[`c-sharp/Projects/ParatextProjectDataProvider.cs` line 72 at r1](https://reviewable.io/reviews/paranext/paranext-core/857#-NvcLODc3s0RIHKRMyR8:-NvlizGk4KV9XlvGY_ud:bowlsyg) ([raw file](https://github.com/paranext/paranext-core/blob/946b4edea406db3175ea32b652bca261fc01b00a/c-sharp/Projects/ParatextProjectDataProvider.cs#L72)):*
<details><summary><i>Previously, lyonsil (Matt Lyons) wrote…</i></summary><blockquote>

Yeah this is pretty specific to Paratext. Since we're trying to maintain compatibility with Paratext, I think it might be clearer to just do what we're doing here (i.e., overwrite the value with the default) so the `Settings.xml` file still has a value stored for the setting. Do you have concerns with that?
</blockquote></details>

Fair enough! I guess I should probably change the wording about our requirements for project storage interpreters then - maybe it's all more recommended than really required...
___
*[`c-sharp/Projects/ParatextProjectDataProvider.cs` line 92 at r3](https://reviewable.io/reviews/paranext/paranext-core/857#-Nvlkz374NcdoqXo_GSJ:-Nvlkz38DMl5mMmasTFx:brtbxkm) ([raw file](https://github.com/paranext/paranext-core/blob/9bb5dc7a1deff769b795e922c3bcf2753ada855a/c-sharp/Projects/ParatextProjectDataProvider.cs#L92)):*
> ```Smalltalk
>         );
>         if (defaultValue == null)
>             return ResponseToRequest.Failed($"Default value for {settingName} was null");
> ```

Just to be sure, this is really checking to make sure you received a default value at all, right? Even if it tells you the default is null, that wouldn't trigger this failure, right? `null` (really `undefined` on the js side) is a valid default value if people choose to make it the default for their setting, so just making sure. I think I'm reading `ProjectSettingsService.GetDefault` right!

**Review by lyonsil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/857)* status: 7 of 8 files reviewed, 1 unresolved discussion (waiting on @tjcouch-sil)

___
*[`c-sharp/Projects/ParatextProjectDataProvider.cs` line 92 at r3](https://reviewable.io/reviews/paranext/paranext-core/857#-Nvlkz374NcdoqXo_GSJ:-Nvn5Z9iBZkJsvvvyA9m:b-9zjrkq) ([raw file](https://github.com/paranext/paranext-core/blob/9bb5dc7a1deff769b795e922c3bcf2753ada855a/c-sharp/Projects/ParatextProjectDataProvider.cs#L92)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

Just to be sure, this is really checking to make sure you received a default value at all, right? Even if it tells you the default is null, that wouldn't trigger this failure, right? `null` (really `undefined` on the js side) is a valid default value if people choose to make it the default for their setting, so just making sure. I think I'm reading `ProjectSettingsService.GetDefault` right!
</blockquote></details>

Unfortunately as we discussed there are lower level issues with `null`/`undefined` being passed through to the .NET process right now. Per our discussion we'll set this aside for now.

**Review by tjcouch-sil — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/857#-:-NvnGyB9EcC2yoOunIuD:bnfp4nl)* status: all files reviewed, 1 unresolved discussion

**Review by tjcouch-sil — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/857)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Pull request merged**
