### PR TITLE
Fixed scroll group selector sometimes having undefined key

### PR DESCRIPTION
**Pull request by tjcouch-sil**
Apparently `undefined` is not a valid key in React even if there is only one sibling in the list that has `undefined` as its key. Apparently `undefined` is not considered to be "unique" >.>

image

- - -
This change is [Reviewable](https://reviewable.io/reviews/paranext/paranext-core/1106)

### CODE REVIEW

**Review by jolierabideau — APPROVED** [review]
Good to know! Thanks TJ

> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/1106#-:-O5sACO15kf712bkXIWG:b-bu1ex0)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Comment by irahopkinson** [comment]
@tjcouch-sil I'd appreciate this being rebased and merged.

**Comment by tjcouch-sil** [comment]
> @tjcouch-sil I'd appreciate this being rebased and merged.

Sorry, thought I'd wait on some other work messing with PBR to get in before I rebased and got into another PBR race. But I'll go ahead. Hopefully will get in soon and not hit another PBR merge conflict.

**Review by jolierabideau — APPROVED** [review]
Thanks TJ!

> Reviewed 6 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/1106#-:-O6MWJzW6gyOluYA7A8x:b-7z3n2f)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Pull request merged**
