### PR TITLE
343 storage mock for verseref

### LINKED ISSUE #343: Create quick settings storage mock on renderer
As an extension developer, I want to be able to get the current verse ref so I can write my stuff well.

We need to create some kind of `papi.settings.setUserSetting`, `papi.settings.getUserSetting`, and `papi.settings.subscribeUserSetting` or something that just backs up to localstorage. We just need a quick way for now for people to sync up to the verse ref.

The settings could have a mapped type like with `papi-commands`! See this issue for more info on mapped types https://github.com/paranext/paranext-core/issues/317

### PR DESCRIPTION
**Pull request by rolfheij-sil**
Resolves #343 

This change is [Reviewable](https://reviewable.io/reviews/paranext/paranext-core/386)

### CODE REVIEW

**Review by rolfheij-sil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/386)* status: 0 of 19 files reviewed, 1 unresolved discussion

___
*[`lib/papi-dts/papi.d.ts` line 2404 at r1](https://reviewable.io/reviews/paranext/paranext-core/386#-Nc2YFux9IklNoBMfnxF:-Nc2YFux9IklNoBMfnxG:bodypz3) ([raw file](https://github.com/paranext/paranext-core/blob/cf94ce812e01d85beafb3b68e4295a8fa27b5701/lib/papi-dts/papi.d.ts#L2404)):*
> ```XML
>    * @returns The value of the specified setting, parsed to an object. Returns `null` if setting is not present or no value is available
>    */
>   const getSetting: (key: string) => unknown | null;
> ```

To-do: `unknown` should be replaced with a template type

**Review by tjcouch-sil — CHANGES_REQUESTED** [review]
Awesome!! Almost there. Looking forward to having this in! I would be glad to review again once you do the mapped types; no worries.

> Reviewed 19 of 19 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/386#-:-Nc2vKmBBgdmgOKY-ljJ:bugdg93)* status: all files reviewed, 4 unresolved discussions (waiting on @rolfheij-sil)

___
*[`src/renderer/app.component.tsx` line 30 at r1](https://reviewable.io/reviews/paranext/paranext-core/386#-Nc2qxIw980kg2Q9pT0Z:-Nc2qxIw980kg2Q9pT0_:b-p5vgcm) ([raw file](https://github.com/paranext/paranext-core/blob/cf94ce812e01d85beafb3b68e4295a8fa27b5701/src/renderer/app.component.tsx#L30)):*
> ```XML
>     <TestContext.Provider value="test">
>       <PlatformBibleToolbar
>         referenceChanged={handleReferenceChanged}
> ```

Is there anything preventing us from using the `useSetting` hook inside `PlatformBibleToolbar` instead of passing it down here?
___
*[`src/renderer/hooks/papi-hooks/use-setting.hook.ts` line 5 at r1](https://reviewable.io/reviews/paranext/paranext-core/386#-Nc2szZV4NCs1KVbYQA9:-Nc2szZV4NCs1KVbYQAA:bh0naz5) ([raw file](https://github.com/paranext/paranext-core/blob/cf94ce812e01d85beafb3b68e4295a8fa27b5701/src/renderer/hooks/papi-hooks/use-setting.hook.ts#L5)):*
> ```XML
> 
> /**
>  * This hooks layers over useState, and stores the stateful value in local storage too.
> ```

Let's avoid mentioning localstorage in here since that is a short-term solution to the settings implementation.

For clarity and ease of understanding for people who want to use it, I'd also suggest stating declaratively what this hook does instead of describing its contents (like `use-promise.hook.ts`'s description) like:

"Gets and sets a setting on the `papi`. Also keeps up-to-date when the setting changes." or something.

Also see `use-promise.hook.ts`'s `@returns` for an example of how you could fill in the return :)
___
*[`src/shared/services/settings.service.ts` line 5 at r1](https://reviewable.io/reviews/paranext/paranext-core/386#-Nc2rpAp8JVTPr6Z4Ioe:-Nc2rpAp8JVTPr6Z4Iof:b-q26bz3) ([raw file](https://github.com/paranext/paranext-core/blob/cf94ce812e01d85beafb3b68e4295a8fa27b5701/src/shared/services/settings.service.ts#L5)):*
> ```XML
> 
> /** All message subscriptions - emitters that emit an event each time a setting is updated */
> const messageEmitters = new Map<string, PapiEventEmitter<unknown>>();
> ```

This variable name and description are outdated from the network connector file - maybe change to `onDidUpdateSettingEmitters` or something?

**Review by rolfheij-sil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/386)* status: 13 of 20 files reviewed, 3 unresolved discussions (waiting on @tjcouch-sil)

___
*[`src/renderer/app.component.tsx` line 30 at r1](https://reviewable.io/reviews/paranext/paranext-core/386#-Nc2qxIw980kg2Q9pT0Z:-NcO6_EfEMI6XuhfLsx0:bqy3k3r) ([raw file](https://github.com/paranext/paranext-core/blob/cf94ce812e01d85beafb3b68e4295a8fa27b5701/src/renderer/app.component.tsx#L30)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

Is there anything preventing us from using the `useSetting` hook inside `PlatformBibleToolbar` instead of passing it down here?
</blockquote></details>

Nope. I guess there isn't. The scrref state was defined at the App component level, so I figured it would be there for a reason. Moved it now. Looks cleaner.
___
*[`src/renderer/hooks/papi-hooks/use-setting.hook.ts` line 5 at r1](https://reviewable.io/reviews/paranext/paranext-core/386#-Nc2szZV4NCs1KVbYQA9:-NcOBiUV92YfKhxLZCTt:bjame6w) ([raw file](https://github.com/paranext/paranext-core/blob/cf94ce812e01d85beafb3b68e4295a8fa27b5701/src/renderer/hooks/papi-hooks/use-setting.hook.ts#L5)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

Let's avoid mentioning localstorage in here since that is a short-term solution to the settings implementation.

For clarity and ease of understanding for people who want to use it, I'd also suggest stating declaratively what this hook does instead of describing its contents (like `use-promise.hook.ts`'s description) like:

"Gets and sets a setting on the `papi`. Also keeps up-to-date when the setting changes." or something.

Also see `use-promise.hook.ts`'s `@returns` for an example of how you could fill in the return :)
</blockquote></details>

Thanks for the help. Is this better?
___
*[`src/shared/services/settings.service.ts` line 5 at r1](https://reviewable.io/reviews/paranext/paranext-core/386#-Nc2rpAp8JVTPr6Z4Ioe:-NcO76ZUD5u9vIvLnl30:b-896fix) ([raw file](https://github.com/paranext/paranext-core/blob/cf94ce812e01d85beafb3b68e4295a8fa27b5701/src/shared/services/settings.service.ts#L5)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

This variable name and description are outdated from the network connector file - maybe change to `onDidUpdateSettingEmitters` or something?
</blockquote></details>

Done.

**Review by tjcouch-sil — APPROVED** [review]
:lgtm: thanks for the hard work!

> Reviewed 8 of 8 files at r2, 6 of 6 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/386#-:-NcO_5k19PpJ7PggXntl:bh33jmx)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
