### PR TITLE
Use <feature>.<type>.<ext> filename convention

### PR DESCRIPTION
**Pull request by irahopkinson**
- most files have just been renamed in place to ensure git tracability
- some files have been moved but are only minor renames of an existing path

- - -
This change is [Reviewable](https://reviewable.io/reviews/paranext/paranext-core/112)

### CODE REVIEW

**Review by FoolRunning — COMMENTED** [review]
I'm not sure this PR is ready for review, but I'm personally not a fan of the dashed naming. Why that versus camelCase?

> Reviewed 1 of 33 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/112#-:-NRhh0tlB_2Ep952NsJN:b-tonszf)* status: 1 of 33 files reviewed, all discussions resolved

**Review by irahopkinson — COMMENTED** [review]
It's definitely only a draft. I only created it in the first place to check that GitHub and Reviewable are seeing my on-going changes as renames (and not add and deletes).

Using _PascalCase_ for React components, e.g. `PComboBox.component.tsx`, _camelCase_ for hooks and other React items, e.g. `usePromise.hook.ts`. React does at least already make those casing guidelines. And so using `kebab-case` to distinguish all other items, e.g. `network-object.service.ts`. All other items could also be _camelCase_ but I think it will be helpful to distinguish them since we will have a lot of files.

> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/112#-:-NRjmzOk8jKtzacJAn7K:b-dgfeaz)* status: 1 of 33 files reviewed, all discussions resolved (waiting on @FoolRunning)

**Review by irahopkinson — COMMENTED** [review]
@FoolRunning at our style meeting today we decided to use _kebab-case_ for folders and file names. This is to avoid git issues with case-insensitive file systems as per the last heading in this [article](https://profy.dev/article/react-folder-structure). Are you ok with that?

> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/112#-:-NRoQs2A2QR0g3zdXyXl:b-swu3we)* status: 1 of 33 files reviewed, all discussions resolved (waiting on @FoolRunning)

**Review by FoolRunning — COMMENTED** [review]
Yes, I'm fine with the decision.

> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/112#-:-NSGo8tF795G3b8qZWTg:b-8d9k48)* status: 0 of 73 files reviewed, all discussions resolved

**Comment by FoolRunning** [comment]
Sorry, I didn't realize I was somehow holding this up.

**Comment by irahopkinson** [comment]
Closing in favour of new PR for final review.

**Pull request closed without merging**
