### PR TITLE
Add reset function to useWebViewState

### PR DESCRIPTION
**Pull request by rolfheij-sil**
This change is [Reviewable](https://reviewable.io/reviews/paranext/paranext-core/717)

### CODE REVIEW

**Review by irahopkinson — CHANGES_REQUESTED** [review]
This looks fine to me but I'm not familiar enough with this part of the code. @tjcouch-sil can you review this also?

> Reviewed 2 of 8 files at r1, 6 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/717#-:-NoNn1YM8-NZUtn8C6qV:btwtixe)* status: all files reviewed, 2 unresolved discussions (waiting on @rolfheij-sil)

___
*[`src/renderer/hooks/use-web-view-state.hook.ts` line 22 at r2](https://reviewable.io/reviews/paranext/paranext-core/717#-NoNl6tI9tPf2kW7Kmo2:-NoNl6tJ-0xL-zrERXxO:b-jaftl0) ([raw file](https://github.com/paranext/paranext-core/blob/677d330d8adf1fd6a3e2f4288d375921015fd88b/src/renderer/hooks/use-web-view-state.hook.ts#L22)):*
> ```XML
>   }, [defaultStateValue, state, stateKey]);
> 
>   const resetState = () => {
> ```

Does this need to be enclosed in a `useCallback`?
___
*[`src/renderer/services/web-view-state.service.ts` line 107 at r2](https://reviewable.io/reviews/paranext/paranext-core/717#-NoNm55M5VMGPmD9gsHb:-NoNm55M5VMGPmD9gsHc:bs1dtuo) ([raw file](https://github.com/paranext/paranext-core/blob/677d330d8adf1fd6a3e2f4288d375921015fd88b/src/renderer/services/web-view-state.service.ts#L107)):*
> ```XML
>  */
> export function resetWebViewStateById(id: string, stateKey: string): void {
>   if (!id || !stateKey) throw new Error('id and stateKey must be provided to remove webview state');
> ```

Probably should use `.trim()` on each of these inputs to catch strings with no useful content.

**Review by tjcouch-sil — CHANGES_REQUESTED** [review]
> Reviewed 6 of 8 files at r1, 6 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/717)* status: all files reviewed, 4 unresolved discussions (waiting on @irahopkinson and @rolfheij-sil)

___
*[`src/renderer/hooks/use-web-view-state.hook.ts` line 14 at r2](https://reviewable.io/reviews/paranext/paranext-core/717#-NoOXmunBih8Pw1J_cu9:-NoOXmunBih8Pw1J_cuA:bfam367) ([raw file](https://github.com/paranext/paranext-core/blob/677d330d8adf1fd6a3e2f4288d375921015fd88b/src/renderer/hooks/use-web-view-state.hook.ts#L14)):*
> ```XML
>   defaultStateValue: T,
> ): [webViewState: T, setWebViewState: Dispatch<SetStateAction<T>>, resetWebViewState: () => void] {
>   const [state, setState] = useState(() => this.getWebViewState(stateKey) ?? defaultStateValue);
> ```

This will need to be updated to pass the default value into `getWebViewState`
___
*[`src/renderer/hooks/use-web-view-state.hook.ts` line 22 at r2](https://reviewable.io/reviews/paranext/paranext-core/717#-NoNl6tI9tPf2kW7Kmo2:-NoOWN09BnwsJOipLLrL:blajsdo) ([raw file](https://github.com/paranext/paranext-core/blob/677d330d8adf1fd6a3e2f4288d375921015fd88b/src/renderer/hooks/use-web-view-state.hook.ts#L22)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

Does this need to be enclosed in a `useCallback`?
</blockquote></details>

This does indeed need to be enclosed in a `useCallback` to keep the returned function stable :)
___
*[`src/renderer/services/web-view-state.service.ts` line 74 at r2](https://reviewable.io/reviews/paranext/paranext-core/717#-NoOYDa541TabxoTpBAq:-NoOYDa541TabxoTpBAr:b-8xmzfs) ([raw file](https://github.com/paranext/paranext-core/blob/677d330d8adf1fd6a3e2f4288d375921015fd88b/src/renderer/services/web-view-state.service.ts#L74)):*
> ```XML
>  * @returns String (if it exists) containing the state for the given key of the given web view
>  */
> export function getWebViewStateById<T>(id: string, stateKey: string): T | undefined {
> ```

You need to add a `defaultValue: T` parameter on here in accord with the new get/set/reset pattern since default values are not stored elsewhere. Then you can remove `| undefined` on the return type.

Note: since `defaultValue` is a required parameter, you can always trust it as the correct `defaultValue` if there isn't a value at the key specified; you do not need to throw. I didn't realize it before, but it is also the case with `getSetting` in the setting service. Sorry I didn't think about it before. I can update it unless you particularly desire to do so since I will already be in that area of the code with my hook work. Also the `@return` JSDoc on `getSetting` is out of date. `undefined` is no longer returned arbitrarily (but it should be returned if `defaultSetting` is `undefined` and there isn't another value).

**Review by tjcouch-sil — COMMENTED** [review]
Thanks for the good work on this! Looking forward to having this in soon :)

> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/717#-:-NoOhWo-4JnXvPbqkgSl:b-nzuea5)* status: all files reviewed, 4 unresolved discussions (waiting on @irahopkinson and @rolfheij-sil)

**Review by irahopkinson — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/717)* status: all files reviewed, 4 unresolved discussions (waiting on @rolfheij-sil)

___
*[`src/renderer/services/web-view-state.service.ts` line 107 at r2](https://reviewable.io/reviews/paranext/paranext-core/717#-NoNm55M5VMGPmD9gsHb:-NoOhFmw4bFQDdmyLUFi:b-miws70) ([raw file](https://github.com/paranext/paranext-core/blob/677d330d8adf1fd6a3e2f4288d375921015fd88b/src/renderer/services/web-view-state.service.ts#L107)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

Probably should use `.trim()` on each of these inputs to catch strings with no useful content.
</blockquote></details>

I talked about this with @tjcouch-sil and since this is just copying an existing code example, and fixing this here doesn't fix it everywhere else, I'm making this non-blocking.

**Review by rolfheij-sil — COMMENTED** [review]
Thanks!

> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/717#-:-NoRNNADACS7COTn0ykU:b-ucfknh)* status: 0 of 9 files reviewed, 4 unresolved discussions (waiting on @irahopkinson and @tjcouch-sil)

___
*[`src/renderer/hooks/use-web-view-state.hook.ts` line 14 at r2](https://reviewable.io/reviews/paranext/paranext-core/717#-NoOXmunBih8Pw1J_cu9:-NoR0O2Q-vgU73U6Tgl5:b-896fix) ([raw file](https://github.com/paranext/paranext-core/blob/677d330d8adf1fd6a3e2f4288d375921015fd88b/src/renderer/hooks/use-web-view-state.hook.ts#L14)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

This will need to be updated to pass the default value into `getWebViewState`
</blockquote></details>

Done.
___
*[`src/renderer/hooks/use-web-view-state.hook.ts` line 22 at r2](https://reviewable.io/reviews/paranext/paranext-core/717#-NoNl6tI9tPf2kW7Kmo2:-NoQvNG64WPHqHn3q8I0:b-896fix) ([raw file](https://github.com/paranext/paranext-core/blob/677d330d8adf1fd6a3e2f4288d375921015fd88b/src/renderer/hooks/use-web-view-state.hook.ts#L22)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

This does indeed need to be enclosed in a `useCallback` to keep the returned function stable :)
</blockquote></details>

Done.
___
*[`src/renderer/services/web-view-state.service.ts` line 74 at r2](https://reviewable.io/reviews/paranext/paranext-core/717#-NoOYDa541TabxoTpBAq:-NoR16PK6gCUT21ZhmzH:b-yx5eta) ([raw file](https://github.com/paranext/paranext-core/blob/677d330d8adf1fd6a3e2f4288d375921015fd88b/src/renderer/services/web-view-state.service.ts#L74)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

You need to add a `defaultValue: T` parameter on here in accord with the new get/set/reset pattern since default values are not stored elsewhere. Then you can remove `| undefined` on the return type.

Note: since `defaultValue` is a required parameter, you can always trust it as the correct `defaultValue` if there isn't a value at the key specified; you do not need to throw. I didn't realize it before, but it is also the case with `getSetting` in the setting service. Sorry I didn't think about it before. I can update it unless you particularly desire to do so since I will already be in that area of the code with my hook work. Also the `@return` JSDoc on `getSetting` is out of date. `undefined` is no longer returned arbitrarily (but it should be returned if `defaultSetting` is `undefined` and there isn't another value).
</blockquote></details>

Done. Thanks for thinking all that through. I updated the code. 
___
*[`src/renderer/services/web-view-state.service.ts` line 107 at r2](https://reviewable.io/reviews/paranext/paranext-core/717#-NoNm55M5VMGPmD9gsHb:-NoRN9zXCBqZmaCqkyH8:b28b8qh) ([raw file](https://github.com/paranext/paranext-core/blob/677d330d8adf1fd6a3e2f4288d375921015fd88b/src/renderer/services/web-view-state.service.ts#L107)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

I talked about this with @tjcouch-sil and since this is just copying an existing code example, and fixing this here doesn't fix it everywhere else, I'm making this non-blocking.
</blockquote></details>

I think I'll leave this for now. Like you say, just fixing it in this one place doesn't really improve things

**Review by tjcouch-sil — APPROVED** [review]
:lgtm: thanks for the hard work!

> Reviewed 9 of 9 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/717#-:-NoSFKH51OZLRlHR4B8k:bh33jmx)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

___
*[`src/renderer/hooks/use-web-view-state.hook.ts` line 20 at r3](https://reviewable.io/reviews/paranext/paranext-core/717#-NoS66ws5gIA5tPYrOS4:-NoS66ws5gIA5tPYrOS5:bmpwo4w) ([raw file](https://github.com/paranext/paranext-core/blob/b3addaa0b574719a6d106f02c1f7a427b1446dc5/src/renderer/hooks/use-web-view-state.hook.ts#L20)):*
> ```XML
>   useEffect(() => {
>     if (
>       this.getWebViewState(stateKey, defaultStateValue) === defaultStateValue &&
> ```

Because I know you love to learn, I will put some deeper-level comments here. To be clear, I don't expect you to make these changes. Just notes so you can learn :) *if* you *really* want to implement these changes, of course, feel free. But I just want to be clear that I do not expect you to make these changes at all. They are informational only.

I'm not exactly sure of the purpose for this `if` statement, but I *suspect* this `useEffect` could be rewritten to simplify it. I think the idea here is "if the default state changes, get the new state and update our state internally". If I'm not missing something, I believe you could rewrite this `useEffect` like this:

```typescript
useEffect(() => {
  setStateInternal(this.getWebViewState(stateKey, defaultStateValue));
}, [defaultStateValue, stateKey]);
```

`useState`'s `set` function internally compares the current value to the new value and doesn't update or trigger re-renders if they are referentially equal (`===`), so we don't need to avoid setting if they are equal. I believe that removes the need for `state` in the dependency array, which I believe removes the need for the first part of the `if` statement (not sure, though; again, I'm not sure of the purpose for that part) to avoid circular re-renders. We can trust `this.getWebViewState` will give us the appropriate value in any situation. As such, I think this rework would solve the problems here. I believe it also achieves keeping the state up-to-date when the key changes, which I do not believe will happen currently.

I will probably make some adjustments that include this in my PR FYI.

Again, this is just informational. No action needed unless you particularly desire to make the change yourself!
___
*[`src/renderer/hooks/use-web-view-state.hook.ts` line 28 at r3](https://reviewable.io/reviews/paranext/paranext-core/717#-NoSE5hlErK_34ieJs79:-NoSE5hlErK_34ieJs7A:b-gy86c0) ([raw file](https://github.com/paranext/paranext-core/blob/b3addaa0b574719a6d106f02c1f7a427b1446dc5/src/renderer/hooks/use-web-view-state.hook.ts#L28)):*
> ```XML
>   const setState = useCallback(
>     (newStateValue: T) => {
>       setStateInternal(newStateValue);
> ```

*Learning disclaimer* I think I would probably put `setStateInternal` after `this.setWebViewState` so that, if `setWebViewState` throws, `setStateInternal` doesn't incorrectly have the new value. Same with reset below.
___
*[`src/renderer/services/web-view-state.service.ts` line 107 at r2](https://reviewable.io/reviews/paranext/paranext-core/717#-NoNm55M5VMGPmD9gsHb:-NoSEzqTBKC2UMgLiIlA:bl45id9) ([raw file](https://github.com/paranext/paranext-core/blob/677d330d8adf1fd6a3e2f4288d375921015fd88b/src/renderer/services/web-view-state.service.ts#L107)):*
<details><summary><i>Previously, rolfheij-sil wrote…</i></summary><blockquote>

I think I'll leave this for now. Like you say, just fixing it in this one place doesn't really improve things
</blockquote></details>

I am resolving this discussion to avoid blocking the PR.

**Review by rolfheij-sil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/717)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

___
*[`src/renderer/hooks/use-web-view-state.hook.ts` line 20 at r3](https://reviewable.io/reviews/paranext/paranext-core/717#-NoS66ws5gIA5tPYrOS4:-NoWvWer8ExZE71qBncx:b-hzy5fo) ([raw file](https://github.com/paranext/paranext-core/blob/b3addaa0b574719a6d106f02c1f7a427b1446dc5/src/renderer/hooks/use-web-view-state.hook.ts#L20)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

Because I know you love to learn, I will put some deeper-level comments here. To be clear, I don't expect you to make these changes. Just notes so you can learn :) *if* you *really* want to implement these changes, of course, feel free. But I just want to be clear that I do not expect you to make these changes at all. They are informational only.

I'm not exactly sure of the purpose for this `if` statement, but I *suspect* this `useEffect` could be rewritten to simplify it. I think the idea here is "if the default state changes, get the new state and update our state internally". If I'm not missing something, I believe you could rewrite this `useEffect` like this:

```typescript
useEffect(() => {
  setStateInternal(this.getWebViewState(stateKey, defaultStateValue));
}, [defaultStateValue, stateKey]);
```

`useState`'s `set` function internally compares the current value to the new value and doesn't update or trigger re-renders if they are referentially equal (`===`), so we don't need to avoid setting if they are equal. I believe that removes the need for `state` in the dependency array, which I believe removes the need for the first part of the `if` statement (not sure, though; again, I'm not sure of the purpose for that part) to avoid circular re-renders. We can trust `this.getWebViewState` will give us the appropriate value in any situation. As such, I think this rework would solve the problems here. I believe it also achieves keeping the state up-to-date when the key changes, which I do not believe will happen currently.

I will probably make some adjustments that include this in my PR FYI.

Again, this is just informational. No action needed unless you particularly desire to make the change yourself!
</blockquote></details>

Thanks for these comments, super cool! I'd like to make the changes, but since this branch is already merged and deleted it might be easier if you just do it at part of your work, as you propose

**Pull request merged**
