### PR TITLE
Shim internet access out of extensions on extension host and in web view

### LINKED ISSUE #49: Create internet access service and shim internet access out
Create an internet access service on the papi, and shim out internet access so extension developers can't access the internet outside our avenues. Probably pretty much just perfectly mirror the fetch api (maybe even just pass the args straight to it).

Depends on #30

Closely related to #75, but not quite dependent on it.

### PR DESCRIPTION
**Pull request by tjcouch-sil**
- Added InternetService to have a place where extensions can go for internet access
- Changed React webview to a createRoot in an iframe to cut off access to renderer window context
  - Unfortunately, this means React webviews no longer have natural access to our React context
- Renamed `WebviewTypes.ts` to `WebViewTypes.ts` - we should probably decide if we want it to be called `WebView` or `Webview`
- Added content security policies and iframe sandboxing
- Bumped nvmrc to 18.0.0 to match the introduction of the Node `fetch` API

Created some issues as follow-ups from this one:
#85 
#86 
#87 
#88 
#89 
#90 
#91

Resolves #49

- - -
This change is [Reviewable](https://reviewable.io/reviews/paranext/paranext-core/93)

### CODE REVIEW

**Review by FoolRunning — CHANGES_REQUESTED** [review]
> Reviewed 20 of 20 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/93)* status: all files reviewed, 4 unresolved discussions (waiting on @tjcouch-sil)

___
*[`src/extension-host/services/ExtensionService.ts` line 146 at r1](https://reviewable.io/reviews/paranext/paranext-core/93#-NQzctBk7xv4rMY7iwSa:-NQzctBk7xv4rMY7iwSb:b-vyc5g3) ([raw file](https://github.com/paranext/paranext-core/blob/2c636f98c604ab8af3bd1664405aa78d64f0cf63/src/extension-host/services/ExtensionService.ts#L146)):*
> ```XML
>     // Disallow any imports within the extension
>     // TODO: make this throw so the extension knows what's going on
>     // Tell the extension dev if there is an api similar to what they want to import
> ```

Is there a reason this wasn't coded as a ``throw``? It would make much more sense. I would expect the current behavior of getting something back from a ``require`` call the doesn't contain any of the expected objects/properties would be much more confusing.
___
*[`src/extension-host/services/ExtensionService.ts` line 162 at r1](https://reviewable.io/reviews/paranext/paranext-core/93#-NQzdW0cAi33XvGaJT-1:-NQzdW0cAi33XvGaJT-2:b-yf8itn) ([raw file](https://github.com/paranext/paranext-core/blob/2c636f98c604ab8af3bd1664405aa78d64f0cf63/src/extension-host/services/ExtensionService.ts#L162)):*
> ```XML
>   globalThis.fetch = () => {
>     throw Error('Cannot use fetch! Try using papi.fetch');
>   };
> ```

I think the shimming should be done consistently (i.e. either using an anonymous function or using a named function as the other two below). Unless there is some subtle difference between the two and is thus a reason to do it the way it was done.
___
*[`src/shared/services/InternetService.ts` line 7 at r1](https://reviewable.io/reviews/paranext/paranext-core/93#-NQziFoF5_kIKmSvtXwj:-NQziFoF5_kIKmSvtXwk:b-grajmw) ([raw file](https://github.com/paranext/paranext-core/blob/2c636f98c604ab8af3bd1664405aa78d64f0cf63/src/shared/services/InternetService.ts#L7)):*
> ```XML
> 
> // TODO: use some more universal cached version of fetch in paranext-core#75
> const fetchOriginal = globalThis.fetch;
> ```

Is there some kind of guarantee that the code in ExtensionService.ts that replaces ``fetch`` won't be run first? Otherwise, this seems very fragile.
___
*[`src/shared/data/WebViewTypes.ts` line 54 at r2](https://reviewable.io/reviews/paranext/paranext-core/93#-NQzhls1DJ1_r-spxPq4:-NQzhls1DJ1_r-spxPq5:bdmx6qv) ([raw file](https://github.com/paranext/paranext-core/blob/1bf121a2909e2f103d673202b4ce5c6c220700c9/src/shared/data/WebViewTypes.ts#L54)):*
> ```XML
> 
> /** Base WebView properties that all WebViews share */
> type WebViewContentsBase = { contents: string; title?: string };
> ```

Is ``contents`` always a string now because passing a ReactNode isn't feasible anymore?

**Review by tjcouch-sil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/93)* status: 19 of 21 files reviewed, 4 unresolved discussions (waiting on @FoolRunning)

___
*[`src/extension-host/services/ExtensionService.ts` line 146 at r1](https://reviewable.io/reviews/paranext/paranext-core/93#-NQzctBk7xv4rMY7iwSa:-NR-EVdNBfG88JNl0YV5:b-798n5m) ([raw file](https://github.com/paranext/paranext-core/blob/2c636f98c604ab8af3bd1664405aa78d64f0cf63/src/extension-host/services/ExtensionService.ts#L146)):*
<details><summary><i>Previously, FoolRunning (Tim Steenwyk) wrote…</i></summary><blockquote>

Is there a reason this wasn't coded as a ``throw``? It would make much more sense. I would expect the current behavior of getting something back from a ``require`` call the doesn't contain any of the expected objects/properties would be much more confusing.
</blockquote></details>

I think I just didn't want to have to handle the exceptions in the extensions. Thanks for calling out lazy TJ. Made a new `evil` extension that does bad things and removed the bad things from the other extensions.
___
*[`src/extension-host/services/ExtensionService.ts` line 162 at r1](https://reviewable.io/reviews/paranext/paranext-core/93#-NQzdW0cAi33XvGaJT-1:-NR-EzYc11ZxzSr3x_eE:bjc7ppq) ([raw file](https://github.com/paranext/paranext-core/blob/2c636f98c604ab8af3bd1664405aa78d64f0cf63/src/extension-host/services/ExtensionService.ts#L162)):*
<details><summary><i>Previously, FoolRunning (Tim Steenwyk) wrote…</i></summary><blockquote>

I think the shimming should be done consistently (i.e. either using an anonymous function or using a named function as the other two below). Unless there is some subtle difference between the two and is thus a reason to do it the way it was done.
</blockquote></details>

Done. I did the others as named functions because you can't use an arrow function as a constructor, but I didn't think to change this one. Thanks!
___
*[`src/shared/services/InternetService.ts` line 7 at r1](https://reviewable.io/reviews/paranext/paranext-core/93#-NQziFoF5_kIKmSvtXwj:-NR-FYJz5VAWGx059SCU:bkdeysl) ([raw file](https://github.com/paranext/paranext-core/blob/2c636f98c604ab8af3bd1664405aa78d64f0cf63/src/shared/services/InternetService.ts#L7)):*
<details><summary><i>Previously, FoolRunning (Tim Steenwyk) wrote…</i></summary><blockquote>

Is there some kind of guarantee that the code in ExtensionService.ts that replaces ``fetch`` won't be run first? Otherwise, this seems very fragile.
</blockquote></details>

Actually, `ExtensionService.ts` doesn't fully shim out the globals permanently right now. #75 addresses that issue. But regardless, this code runs before the extension service starts doing its thing because this code happens on import (imports happen before all other code and are even hoisted such that they have to run before other code), whereas the `ExtensionService` doesn't start doing stuff until its `initialize` function is executed. But the long-term answer is that we need something better in #75 :)
___
*[`src/shared/data/WebViewTypes.ts` line 54 at r2](https://reviewable.io/reviews/paranext/paranext-core/93#-NQzhls1DJ1_r-spxPq4:-NR-F5eWAS6_JOHx3OBR:b7gzkwf) ([raw file](https://github.com/paranext/paranext-core/blob/1bf121a2909e2f103d673202b4ce5c6c220700c9/src/shared/data/WebViewTypes.ts#L54)):*
<details><summary><i>Previously, FoolRunning (Tim Steenwyk) wrote…</i></summary><blockquote>

Is ``contents`` always a string now because passing a ReactNode isn't feasible anymore?
</blockquote></details>

Yep! No extension code is being run on the renderer window anymore; it's all passed down into the iframe. Before, I was reading the code and running it in the renderer to get a React node, but now we have to pass the component code down as a string.

**Review by FoolRunning — APPROVED** [review]
:lgtm: 

> Reviewed 2 of 2 files at r3, 6 of 6 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/93#-:-NR-Hh3w3jaYN_eaeSZu:bg7igkv)* status: all files reviewed, 1 unresolved discussion (waiting on @tjcouch-sil)

**Review by FoolRunning — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/93)* status: all files reviewed, 1 unresolved discussion (waiting on @tjcouch-sil)

___
*[`src/shared/data/WebViewTypes.ts` line 54 at r2](https://reviewable.io/reviews/paranext/paranext-core/93#-NQzhls1DJ1_r-spxPq4:-NR-jH987KlsFQm9fcpL:bmdcrh) ([raw file](https://github.com/paranext/paranext-core/blob/1bf121a2909e2f103d673202b4ce5c6c220700c9/src/shared/data/WebViewTypes.ts#L54)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

Yep! No extension code is being run on the renderer window anymore; it's all passed down into the iframe. Before, I was reading the code and running it in the renderer to get a React node, but now we have to pass the component code down as a string.
</blockquote></details>

Sounds like a pain, but I guess it's what we have to do. :(

**Review by FoolRunning — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/93)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @tjcouch-sil)

**Pull request merged**
