### PR TITLE
Checks stability update

### PR DESCRIPTION
**Pull request by rolfheij-sil**
Note: This branch is built off of `add-shadcn-toast` rather than `main`

Feedback is shown by the sonner when active range changes:
image

When hovering over the sonner, up to three messages are displayed: (this number is configurable I think)
image

Feedback is also shown when checks are toggled:
image

Warning/error feedback that is encountered when enabling a check is displayed like so:
image

This change is [Reviewable](https://reviewable.io/reviews/paranext/paranext-core/1139)

### CODE REVIEW

**Comment by Sebastian-ubs** [comment]
Looks nice. Are always the last 3 shown or do they appear after a certain time?

**Comment by Sebastian-ubs** [comment]
From a theming perspective I would expect them to be in the same theme a platform.

**Review by lyonsil — APPROVED** [review]
:lgtm:, but please check with TJ before merging as he is finalizing the build for the summit.

> Reviewed 13 of 13 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/1139#-:-O6k_qnfEAygo9nRByMh:b-o4mzwc)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

___
*[`extensions/src/platform-scripture/src/checking-results-list.web-view.tsx` line 80 at r1](https://reviewable.io/reviews/paranext/paranext-core/1139#-O6kZGPZAA-XaS1M7BOU:-O6kZGP_AwP7kSQSShak:b-egoy52) ([raw file](https://github.com/paranext/paranext-core/blob/899e0aec7951f715c4f206a3a736394bf77ec021/extensions/src/platform-scripture/src/checking-results-list.web-view.tsx#L80)):*
> ```XML
>             },
>     };
>     // The checking service seems to produce duplicated check results so this is a temporary fix to
> ```

Thanks for flagging this and opening a ticket for me to follow up.
___
*[`lib/platform-bible-react/src/components/basics/combo-box.component.tsx` line 45 at r1](https://reviewable.io/reviews/paranext/paranext-core/1139#-O6k_8_s-PqMkjRslEP_:-O6k_8_s-PqMkjRslEPa:b-p3akmk) ([raw file](https://github.com/paranext/paranext-core/blob/899e0aec7951f715c4f206a3a736394bf77ec021/lib/platform-bible-react/src/components/basics/combo-box.component.tsx#L45)):*
> ```XML
>   /** Text direction ltr or rtl */
>   dir?: Direction;
>   /** Component is not enabled when true */
> ```

In general I find that naming boolean variables to be a positive term is easier to think about in the code than variables that have negative meanings. For example, it might be easier to think about a boolean named `enabled`. Otherwise when you see something like `if (!disabled)` you don't have to stop and think about it. But it's not a big deal either way. I understand that you were just matching the button component here.

**Review by rolfheij-sil — COMMENTED** [review]
@Sebastian-ubs I guess we can remove the theming code. Typically we change the imported shadcn code as little as we can, but this seems to interfere with our theming stuff. I'll do it in a separate PR though

@lyonsil Thanks for reviewing! 

> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/1139#-:-O6v8dyGDSis9ZmvNm8K:bikrx8w)* status: all files reviewed, 1 unresolved discussion

___
*[`extensions/src/platform-scripture/src/checking-results-list.web-view.tsx` line 82 at r1](https://reviewable.io/reviews/paranext/paranext-core/1139#-O6vArcz79LaoyhQ2XHQ:-O6vArd-0IJgdTBcnd-s:b-iakmbd) ([raw file](https://github.com/paranext/paranext-core/blob/cc9883008a9eb36327c063925b7fa0cdbd162a2e/extensions/src/platform-scripture/src/checking-results-list.web-view.tsx#L82)):*
> ```XML
>     // The checking service seems to produce duplicated check results so this is a temporary fix to
>     // get rid of them
>     const isDuplicate = resultsSet.data.some(
> ```

The ticket can be found [here](https://github.com/paranext/paranext-core/issues/1144)

**Pull request merged**
