### PR TITLE
Add tooltips to app bar

### LINKED ISSUE #515: Webview tooltips
As a user, I would like to see extra information about my tabs by hovering over the title so I can get the information I need at a glance.

As an extension developer, I want to specify webview tab tooltips so users can get the information they need.

----

Like in Paratext 9, web view providers should be able to specify a tooltip for their webview tab:

Image

This could hopefully simply be on the `WebViewDefinitionBase` in `web-view.model.ts` and carried along from the webview provider.

It should also be updatable, so it needs to be added to `WebViewDefinitionUpdatableProperties` (and the code using it) as well.

### PR DESCRIPTION
**Pull request by rolfheij-sil**
Fixed #515 

This change is [Reviewable](https://reviewable.io/reviews/paranext/paranext-core/657)

### CODE REVIEW

**Review by tjcouch-sil — CHANGES_REQUESTED** [review]
Awesome! Just one little thing and a couple suggestions. Thanks for the quick snipe on this! It will be nice to have this PR as a concise guide for adding things here in the future :)

> Reviewed 7 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/657#-:-NkVeohF2ELCkR6H2t00:b3aftzv)* status: all files reviewed, 3 unresolved discussions (waiting on @rolfheij-sil)

___
*[`src/renderer/components/docking/platform-tab-title.component.tsx` line 26 at r1](https://reviewable.io/reviews/paranext/paranext-core/657#-NkVci7m-f2cIHWpUoF7:-NkVci7m-f2cIHWpUoF8:b-fcrloi) ([raw file](https://github.com/paranext/paranext-core/blob/f9643dd2e759a11dde82d29c2f941e5df3a188ce/src/renderer/components/docking/platform-tab-title.component.tsx#L26)):*
> ```XML
>   };
> 
>   const tooltipDiv = tooltip ? <div style={{ whiteSpace: 'pre-line' }}>{tooltip}</div> : '';
> ```

Please make a class for this if possible :)
___
*[`src/renderer/components/docking/platform-tab-title.component.tsx` line 26 at r1](https://reviewable.io/reviews/paranext/paranext-core/657#-NkVdVc8-kIbLF4m8tzq:-NkVdVc8-kIbLF4m8tzr:bxwwqux) ([raw file](https://github.com/paranext/paranext-core/blob/f9643dd2e759a11dde82d29c2f941e5df3a188ce/src/renderer/components/docking/platform-tab-title.component.tsx#L26)):*
> ```XML
>   };
> 
>   const tooltipDiv = tooltip ? <div style={{ whiteSpace: 'pre-line' }}>{tooltip}</div> : '';
> ```

I think it would be nice to let extension devs use spaces and tabs at the start of their lines if they want - what do you think about using [`pre-wrap`](https://developer.mozilla.org/en-US/docs/Web/CSS/white-space#pre-wrap) instead? Then they could make indented lines and such if desired.
___
*[`src/shared/models/web-view.model.ts` line 42 at r1](https://reviewable.io/reviews/paranext/paranext-core/657#-NkVdIIP24-daJ8lF2XE:-NkVdIIP24-daJ8lF2XF:b-6hl6of) ([raw file](https://github.com/paranext/paranext-core/blob/f9643dd2e759a11dde82d29c2f941e5df3a188ce/src/shared/models/web-view.model.ts#L42)):*
> ```XML
>   /** Name of the tab for the WebView */
>   title?: string;
>   /** Tooltip than is shown when hovering over the webview title */
> ```

typo? "than" -> "that"

**Review by rolfheij-sil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/657)* status: all files reviewed, 2 unresolved discussions (waiting on @tjcouch-sil)

___
*[`src/renderer/components/docking/platform-tab-title.component.tsx` line 26 at r1](https://reviewable.io/reviews/paranext/paranext-core/657#-NkVci7m-f2cIHWpUoF7:-NkVu6762KAWhTyp0xQu:b-896fix) ([raw file](https://github.com/paranext/paranext-core/blob/f9643dd2e759a11dde82d29c2f941e5df3a188ce/src/renderer/components/docking/platform-tab-title.component.tsx#L26)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

Please make a class for this if possible :)
</blockquote></details>

Done.
___
*[`src/renderer/components/docking/platform-tab-title.component.tsx` line 26 at r1](https://reviewable.io/reviews/paranext/paranext-core/657#-NkVdVc8-kIbLF4m8tzq:-NkVu7Np1aVTRt7Qpl2A:bb6un1j) ([raw file](https://github.com/paranext/paranext-core/blob/f9643dd2e759a11dde82d29c2f941e5df3a188ce/src/renderer/components/docking/platform-tab-title.component.tsx#L26)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

I think it would be nice to let extension devs use spaces and tabs at the start of their lines if they want - what do you think about using [`pre-wrap`](https://developer.mozilla.org/en-US/docs/Web/CSS/white-space#pre-wrap) instead? Then they could make indented lines and such if desired.
</blockquote></details>

Done
___
*[`src/shared/models/web-view.model.ts` line 42 at r1](https://reviewable.io/reviews/paranext/paranext-core/657#-NkVdIIP24-daJ8lF2XE:-NkVsutkEdMytiXjdbh0:bu5y5yo) ([raw file](https://github.com/paranext/paranext-core/blob/f9643dd2e759a11dde82d29c2f941e5df3a188ce/src/shared/models/web-view.model.ts#L42)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

typo? "than" -> "that"
</blockquote></details>

Well spotted. Fixed.

**Review by tjcouch-sil — DISMISSED** [review]
:lgtm: thanks!!

> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/657#-:-NkVurPH8zxL39icfVMu:b-1tfu20)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by tjcouch-sil — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/657#-:-NkVv5-D-WJqMQMXx97o:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
