### PR TITLE
Update configure checks components

### PR DESCRIPTION
**Pull request by rolfheij-sil**
- Replaced MUI components for shadcn ones
- Added RadioGroup and ToggleGroup as new shadcn components
- Added preview app examples for these shadcn components
- Added localization

image

This change is [Reviewable](https://reviewable.io/reviews/paranext/paranext-core/1151)

### CODE REVIEW

**Review by jolierabideau — CHANGES_REQUESTED** [review]
Looks great! Thanks Rolf

> Reviewed 32 of 32 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/1151#-:-O7en6fw1Jk2G_LS4RIL:b-fcb4h9)* status: all files reviewed, 2 unresolved discussions (waiting on @rolfheij-sil)

___
*[`lib/platform-bible-react/src/components/basics/checklist.component.tsx` line 1 at r1](https://reviewable.io/reviews/paranext/paranext-core/1151#-O7ekrtu-HsOyvBu9PtO:-O7ekrtu-HsOyvBu9PtP:b-tuafg8) ([raw file](https://github.com/paranext/paranext-core/blob/1c684eba0ed27da447dc1cecfb80d78d5ac7acd8/lib/platform-bible-react/src/components/basics/checklist.component.tsx#L1)):*
> ```XML
> import Checkbox from '../shadcn-ui/checkbox';
> ```

Should these be aliased?
___
*[`lib/platform-bible-react/src/components/basics/checklist.component.tsx` line 45 at r1](https://reviewable.io/reviews/paranext/paranext-core/1151#-O7el2U_ExFdw0arBas-:-O7el2Ua4eOlVxBwsgmO:bm6mdwx) ([raw file](https://github.com/paranext/paranext-core/blob/1c684eba0ed27da447dc1cecfb80d78d5ac7acd8/lib/platform-bible-react/src/components/basics/checklist.component.tsx#L45)):*
> ```XML
>       )}
>       {listItems.map((item) => (
>         <div className="pr-twp pr-m-2 pr-flex pr-items-center">
> ```

Should `pr-twp` be on the outermost component?

**Review by rolfheij-sil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/1151)* status: all files reviewed, 2 unresolved discussions (waiting on @jolierabideau)

___
*[`lib/platform-bible-react/src/components/basics/checklist.component.tsx` line 1 at r1](https://reviewable.io/reviews/paranext/paranext-core/1151#-O7ekrtu-HsOyvBu9PtO:-O7esUWP0F_5UxlGgCvU:b5bvmz7) ([raw file](https://github.com/paranext/paranext-core/blob/1c684eba0ed27da447dc1cecfb80d78d5ac7acd8/lib/platform-bible-react/src/components/basics/checklist.component.tsx#L1)):*
<details><summary><i>Previously, jolierabideau wrote…</i></summary><blockquote>

Should these be aliased?
</blockquote></details>

Yep. Fixed. Also in other places
___
*[`lib/platform-bible-react/src/components/basics/checklist.component.tsx` line 45 at r1](https://reviewable.io/reviews/paranext/paranext-core/1151#-O7el2U_ExFdw0arBas-:-O7esYUZ8KihnZ_a34ml:b-896fix) ([raw file](https://github.com/paranext/paranext-core/blob/1c684eba0ed27da447dc1cecfb80d78d5ac7acd8/lib/platform-bible-react/src/components/basics/checklist.component.tsx#L45)):*
<details><summary><i>Previously, jolierabideau wrote…</i></summary><blockquote>

Should `pr-twp` be on the outermost component?
</blockquote></details>

Done.

**Review by jolierabideau — APPROVED** [review]
> Reviewed 8 of 8 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/1151)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Review by tjcouch-sil — COMMENTED** [review]
> Reviewed 5 of 32 files at r1.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/1151)* status: all files reviewed, 3 unresolved discussions (waiting on @rolfheij-sil)

___
*[`extensions/src/platform-scripture/contributions/localizedStrings.json` line 35 at r1](https://reviewable.io/reviews/paranext/paranext-core/1151#-O7ifC488a8qw2YGZEUr:-O7ifC494iLU2zUbriWa:bb76y2s) ([raw file](https://github.com/paranext/paranext-core/blob/e905398960b1a92748b4b98386a4dd2e2f04a0d3/extensions/src/platform-scripture/contributions/localizedStrings.json#L35)):*
> ```JSON
>       "%webView_inventory_unapproved%": "Unapproved items",
>       "%webView_inventory_unknown%": "Unknown items",
>       "%webView_inventory_scope_book%": "Current book",
> ```

Generally it is best not to change localized string keys as the style guide mentions. We don't have control over what places use localized strings, so we never know if we're breaking something by changing a key. However, we are early on, so it's not that big a deal. It is important, though, to make sure that any shared uses of a string have the same function to avoid problems with things possibly needing to be localized differently in different languages. Do the two uses of this new string key have the same function? Based on that it seems to me (I haven't looked very closely; just a hunch) that one needs a colon and the other doesn't, they probably aren't serving quite the same purpose.

https://github.com/paranext/paranext/wiki/Code-Style-Guide#localized-strings-guidelines
___
*[`lib/platform-bible-react/src/components/advanced/book-selector.component.tsx` line 91 at r1](https://reviewable.io/reviews/paranext/paranext-core/1151#-O7ig_tYDTTk0uKu6bGD:-O7ig_tYDTTk0uKu6bGE:b-n5aw6m) ([raw file](https://github.com/paranext/paranext-core/blob/1c684eba0ed27da447dc1cecfb80d78d5ac7acd8/lib/platform-bible-react/src/components/advanced/book-selector.component.tsx#L91)):*
> ```XML
>           <div className="pr-flex pr-items-center">
>             <RadioGroupItem value={BookSelectionMode.CURRENT_BOOK} />
>             <Label className="pr-ml-1">{`${currentBookText}:`}</Label>
> ```

Please see "Concatenate strings with format strings" in https://github.com/paranext/paranext/wiki/Code-Style-Guide#localized-strings-guidelines

Also I think I saw Sebastian asked you to put the selected book labels aligned with each other; does this depend on how these strings are localized (aka if these were localized in a different language and were a different length, would the columns still be aligned)? Just a question for your consideration; I didn't look at these tailwind classes to check. Tailwind is still not easy for me to read. If it is dependent on localization, I would suggest (maybe next time; not sure if it's worth fixing this right now. Maybe just file a bug) trying to make it not localization-dependent in a natural way. If you can't do that, I'd suggest bringing it up to Sebastian and asking his recommendations.
___
*[`lib/platform-bible-react/src/components/advanced/book-selector.component.tsx` line 108 at r1](https://reviewable.io/reviews/paranext/paranext-core/1151#-O7ih4-z772qobTVA8YN:-O7ih4-z772qobTVA8YO:bk4tc8n) ([raw file](https://github.com/paranext/paranext-core/blob/1c684eba0ed27da447dc1cecfb80d78d5ac7acd8/lib/platform-bible-react/src/components/advanced/book-selector.component.tsx#L108)):*
> ```XML
>           <div className="pr-flex pr-items-center">
>             <RadioGroupItem value={BookSelectionMode.CHOOSE_BOOKS} />
>             <Label className="pr-ml-1">{`${chooseBooksText}:`}</Label>
> ```

Please see "Concatenate strings with format strings" in https://github.com/paranext/paranext/wiki/Code-Style-Guide#localized-strings-guidelines

**Review by rolfheij-sil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/1151)* status: all files reviewed, 3 unresolved discussions (waiting on @tjcouch-sil)

___
*[`extensions/src/platform-scripture/contributions/localizedStrings.json` line 35 at r1](https://reviewable.io/reviews/paranext/paranext-core/1151#-O7ifC488a8qw2YGZEUr:-O7nyNch0i1yKIGDhY-U:b31z3y) ([raw file](https://github.com/paranext/paranext-core/blob/e905398960b1a92748b4b98386a4dd2e2f04a0d3/extensions/src/platform-scripture/contributions/localizedStrings.json#L35)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

Generally it is best not to change localized string keys as the style guide mentions. We don't have control over what places use localized strings, so we never know if we're breaking something by changing a key. However, we are early on, so it's not that big a deal. It is important, though, to make sure that any shared uses of a string have the same function to avoid problems with things possibly needing to be localized differently in different languages. Do the two uses of this new string key have the same function? Based on that it seems to me (I haven't looked very closely; just a hunch) that one needs a colon and the other doesn't, they probably aren't serving quite the same purpose.

https://github.com/paranext/paranext/wiki/Code-Style-Guide#localized-strings-guidelines
</blockquote></details>

They do serve a different purpose, so I've restored the old one. I don't want to make the colon part of the localized string, because I can see UX coming up with a design where the colon is not needed
___
*[`lib/platform-bible-react/src/components/advanced/book-selector.component.tsx` line 91 at r1](https://reviewable.io/reviews/paranext/paranext-core/1151#-O7ig_tYDTTk0uKu6bGD:-O7nytUsDANYW6WqIJ7a:bndb92l) ([raw file](https://github.com/paranext/paranext-core/blob/1c684eba0ed27da447dc1cecfb80d78d5ac7acd8/lib/platform-bible-react/src/components/advanced/book-selector.component.tsx#L91)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

Please see "Concatenate strings with format strings" in https://github.com/paranext/paranext/wiki/Code-Style-Guide#localized-strings-guidelines

Also I think I saw Sebastian asked you to put the selected book labels aligned with each other; does this depend on how these strings are localized (aka if these were localized in a different language and were a different length, would the columns still be aligned)? Just a question for your consideration; I didn't look at these tailwind classes to check. Tailwind is still not easy for me to read. If it is dependent on localization, I would suggest (maybe next time; not sure if it's worth fixing this right now. Maybe just file a bug) trying to make it not localization-dependent in a natural way. If you can't do that, I'd suggest bringing it up to Sebastian and asking his recommendations.
</blockquote></details>

I'll just get rid of the colons for now because I don't think they're essential to the design.

Also the alignment is handled using `pr-grid`, so it's not dependant the localization of this string
___
*[`lib/platform-bible-react/src/components/advanced/book-selector.component.tsx` line 108 at r1](https://reviewable.io/reviews/paranext/paranext-core/1151#-O7ih4-z772qobTVA8YN:-O7nz75b-Gt1OZBV0X2h:b-1zvthm) ([raw file](https://github.com/paranext/paranext-core/blob/1c684eba0ed27da447dc1cecfb80d78d5ac7acd8/lib/platform-bible-react/src/components/advanced/book-selector.component.tsx#L108)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

Please see "Concatenate strings with format strings" in https://github.com/paranext/paranext/wiki/Code-Style-Guide#localized-strings-guidelines
</blockquote></details>

I'll just get rid of the colons for now because I don't think they're essential to the design.

**Pull request merged**
