### PR TITLE
Make log level obvious

### PR DESCRIPTION
**Pull request by irahopkinson**
- change `logger.log` to `logger.info` to make the level obvious
- move logger to service

- - -
This change is [Reviewable](https://reviewable.io/reviews/paranext/paranext-core/111)

### CODE REVIEW

**Review by rolfheij-sil — CHANGES_REQUESTED** [review]
What `log` levels/categories are available currently? Is there any documentation on this?

> Reviewed 21 of 21 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/111#-:-NRgWjO_3y_i-0VxJjdc:b-fwdo55)* status: all files reviewed, 6 unresolved discussions (waiting on @irahopkinson)

___
*[`src/client/services/ClientNetworkConnector.ts` line 26 at r1](https://reviewable.io/reviews/paranext/paranext-core/111#-NRgVaPU5fqNsOD7dmzT:-NRgVaPV5bSpHUJrdidQ:b-9kk7g9) ([raw file](https://github.com/paranext/paranext-core/blob/1875054ee5ccdeed442e2e29551e07795e1e3396/src/client/services/ClientNetworkConnector.ts#L26)):*
> ```XML
> } from '@shared/data/NetworkConnectorTypes';
> import { getErrorMessage } from '@shared/util/Util';
> import logger from '@shared/services/logger.service';
> ```

Why `logger.service`? `LoggerService` would be more consistent with other services that are located in this folder
___
*[`src/extension-host/services/ExtensionService.ts` line 12 at r1](https://reviewable.io/reviews/paranext/paranext-core/111#-NRgWH2k3_ELWyY32Shi:-NRgWH2k3_ELWyY32Shj:b-oquei7) ([raw file](https://github.com/paranext/paranext-core/blob/1875054ee5ccdeed442e2e29551e07795e1e3396/src/extension-host/services/ExtensionService.ts#L12)):*
> ```XML
> import Module from 'module';
> import papi, { MODULE_SIMILAR_APIS } from '@shared/services/papi';
> import logger from '@shared/services/logger.service';
> ```

Why imported if not used?
___
*[`src/main/services/ServerNetworkConnector.ts` line 15 at r1](https://reviewable.io/reviews/paranext/paranext-core/111#-NRgWARL3oUGxyGhq7dR:-NRgWARL3oUGxyGhq7dS:b-oquei7) ([raw file](https://github.com/paranext/paranext-core/blob/1875054ee5ccdeed442e2e29551e07795e1e3396/src/main/services/ServerNetworkConnector.ts#L15)):*
> ```XML
> } from '@shared/data/InternalConnectionTypes';
> import INetworkConnector from '@shared/services/INetworkConnector';
> import logger from '@shared/services/logger.service';
> ```

Why imported if not used?
___
*[`src/renderer/components/WebView.tsx` line 2 at r1](https://reviewable.io/reviews/paranext/paranext-core/111#-NRgWNet5qfBcN1FVj-5:-NRgWNet5qfBcN1FVj-6:b-oquei7) ([raw file](https://github.com/paranext/paranext-core/blob/1875054ee5ccdeed442e2e29551e07795e1e3396/src/renderer/components/WebView.tsx#L2)):*
> ```XML
> import { WebViewContents } from '@shared/data/WebViewTypes';
> import logger from '@shared/services/logger.service';
> ```

Why imported if not used?
___
*[`src/shared/services/papi.ts` line 12 at r1](https://reviewable.io/reviews/paranext/paranext-core/111#-NRgWTxwEbKJ3tAeuowr:-NRgWTxwEbKJ3tAeuows:b-oquei7) ([raw file](https://github.com/paranext/paranext-core/blob/1875054ee5ccdeed442e2e29551e07795e1e3396/src/shared/services/papi.ts#L12)):*
> ```XML
> import * as WebViewService from '@shared/services/WebViewService';
> import PEventEmitter from '@shared/models/PEventEmitter';
> import logger from '@shared/services/logger.service';
> ```

Why imported if not used?
___
*[`src/shared/util/Util.ts` line 104 at r1](https://reviewable.io/reviews/paranext/paranext-core/111#-NRgW_4Z54zS0Pix2Bv4:-NRgW_4Z54zS0Pix2Bv5:b-ehx4zn) ([raw file](https://github.com/paranext/paranext-core/blob/1875054ee5ccdeed442e2e29551e07795e1e3396/src/shared/util/Util.ts#L104)):*
> ```XML
>  * @example
>  *  try {...}
>  *  catch (e) { logger.info(getErrorMessage(e)) }
> ```

I don't see and import for `logger.service` here, is that okay?

**Review by tjcouch-sil — COMMENTED** [review]
> Reviewed 21 of 21 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/111)* status: all files reviewed, 6 unresolved discussions (waiting on @irahopkinson and @rolfheij-sil)

___
*[`src/client/services/ClientNetworkConnector.ts` line 26 at r1](https://reviewable.io/reviews/paranext/paranext-core/111#-NRgVaPU5fqNsOD7dmzT:-NRhxRvd6o7QSt8To9lz:b-qyzj7j) ([raw file](https://github.com/paranext/paranext-core/blob/1875054ee5ccdeed442e2e29551e07795e1e3396/src/client/services/ClientNetworkConnector.ts#L26)):*
<details><summary><i>Previously, rolfheij-sil wrote…</i></summary><blockquote>

Why `logger.service`? `LoggerService` would be more consistent with other services that are located in this folder
</blockquote></details>

I also think it makes sense to keep the names consistent until we conclude on moving to the other naming convention. That being said, I could kinda see it either way considering that some files will need to be changed either way we decide to come down on naming convention.

**Review by irahopkinson — COMMENTED** [review]
Any file you import the logger, you can type `logger.` and VSCode will give you a list of properties and methods including methods to log. The documentation for `electron-log` is [here](https://www.npmjs.com/package/electron-log) which has a section for **Log levels**.

> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/111#-:-NRjVUas3VjLOR_e_gpw:b-nxrvdd)* status: all files reviewed, 6 unresolved discussions (waiting on @rolfheij-sil)

___
*[`src/client/services/ClientNetworkConnector.ts` line 26 at r1](https://reviewable.io/reviews/paranext/paranext-core/111#-NRgVaPU5fqNsOD7dmzT:-NRjWNfq5yNChRSf__qC:b-o17bcv) ([raw file](https://github.com/paranext/paranext-core/blob/1875054ee5ccdeed442e2e29551e07795e1e3396/src/client/services/ClientNetworkConnector.ts#L26)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

I also think it makes sense to keep the names consistent until we conclude on moving to the other naming convention. That being said, I could kinda see it either way considering that some files will need to be changed either way we decide to come down on naming convention.
</blockquote></details>

We actually have 2 naming conventions at present. This is consistent with one of them, see `src/main/services` for examples.
___
*[`src/extension-host/services/ExtensionService.ts` line 12 at r1](https://reviewable.io/reviews/paranext/paranext-core/111#-NRgWH2k3_ELWyY32Shi:-NRjSMZaC3tJ-NiQMba6:b-z03aov) ([raw file](https://github.com/paranext/paranext-core/blob/1875054ee5ccdeed442e2e29551e07795e1e3396/src/extension-host/services/ExtensionService.ts#L12)):*
<details><summary><i>Previously, rolfheij-sil wrote…</i></summary><blockquote>

Why imported if not used?
</blockquote></details>

It is used further down in the file on L168. This is just moving the service from `util` folder to `services` folder since it's a service.
___
*[`src/main/services/ServerNetworkConnector.ts` line 15 at r1](https://reviewable.io/reviews/paranext/paranext-core/111#-NRgWARL3oUGxyGhq7dR:-NRjXDJG7wtiU8mwAfua:b28xwnd) ([raw file](https://github.com/paranext/paranext-core/blob/1875054ee5ccdeed442e2e29551e07795e1e3396/src/main/services/ServerNetworkConnector.ts#L15)):*
<details><summary><i>Previously, rolfheij-sil wrote…</i></summary><blockquote>

Why imported if not used?
</blockquote></details>

It is used further down in the file. This is just moving the service from `util` folder to `services` folder since it's a service.
___
*[`src/renderer/components/WebView.tsx` line 2 at r1](https://reviewable.io/reviews/paranext/paranext-core/111#-NRgWNet5qfBcN1FVj-5:-NRjXTyG-MzxS73LW7p3:b28xwnd) ([raw file](https://github.com/paranext/paranext-core/blob/1875054ee5ccdeed442e2e29551e07795e1e3396/src/renderer/components/WebView.tsx#L2)):*
<details><summary><i>Previously, rolfheij-sil wrote…</i></summary><blockquote>

Why imported if not used?
</blockquote></details>

It is used further down in the file. This is just moving the service from `util` folder to `services` folder since it's a service.
___
*[`src/shared/services/papi.ts` line 12 at r1](https://reviewable.io/reviews/paranext/paranext-core/111#-NRgWTxwEbKJ3tAeuowr:-NRjXVpa06LKiaYk_-iP:b28xwnd) ([raw file](https://github.com/paranext/paranext-core/blob/1875054ee5ccdeed442e2e29551e07795e1e3396/src/shared/services/papi.ts#L12)):*
<details><summary><i>Previously, rolfheij-sil wrote…</i></summary><blockquote>

Why imported if not used?
</blockquote></details>

It is used further down in the file. This is just moving the service from `util` folder to `services` folder since it's a service.
___
*[`src/shared/util/Util.ts` line 104 at r1](https://reviewable.io/reviews/paranext/paranext-core/111#-NRgW_4Z54zS0Pix2Bv4:-NRjXZaA11ulaphrhfZC:b4e75wc) ([raw file](https://github.com/paranext/paranext-core/blob/1875054ee5ccdeed442e2e29551e07795e1e3396/src/shared/util/Util.ts#L104)):*
<details><summary><i>Previously, rolfheij-sil wrote…</i></summary><blockquote>

I don't see and import for `logger.service` here, is that okay?
</blockquote></details>

Yes, this is part of a JSDoc `@example` that gives an example of how to use the `getErrorMessage` function, therefore we don't need or want an unused import.

**Review by rolfheij-sil — DISMISSED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/111#-:-NRlzQ5HEpzv0nJxDqcN:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @irahopkinson)

**Review by tjcouch-sil — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/111)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @irahopkinson)

**Review by tjcouch-sil — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/111#-:-NRoDL9S6lxE_DEIlpDX:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @irahopkinson)

**Pull request merged**
