### PR TITLE
Publish storybook to a public github page on every change in components or stories

### PR DESCRIPTION
**Pull request by Sebastian-ubs**
Fixes paranext/ux#3

- - -
This change is [Reviewable](https://reviewable.io/reviews/paranext/paranext-core/413)

### CODE REVIEW

**Comment by Sebastian-ubs** [comment]
Please set the following setting in repo settings:
Pages > branch: _github-pages_ (and keep _root_)
Like here https://budiirawan.com/images/2022/storybook-github-pages-setting.jpg

Currently gh action config is pointing to this branch, to try it out.

**Review by tjcouch-sil — CHANGES_REQUESTED** [review]
Thanks for the hard work on this! Looks good :) just a couple things

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/413#-:-NdGCBBA5DTfA-tvFEp6:balj3x4)* status: all files reviewed, 2 unresolved discussions (waiting on @Sebastian-ubs)

___
*[`.github/workflows/storybook.yml` line 1 at r1](https://reviewable.io/reviews/paranext/paranext-core/413#-NdG9mPo2VbLHuyeDdkN:-NdG9mPo2VbLHuyeDdkO:b-wiihr4) ([raw file](https://github.com/paranext/paranext-core/blob/3997a678684a1496e3454aa483d6167af75ead00/.github/workflows/storybook.yml#L1)):*
> ```YAML
> name: Storybook
> ```

I think it would be hard to understand looking at the workflow name what this workflow is doing. Could we change this name and the file name to be a bit more descriptive? Like "Publish Storybook to GitHub Pages" and "publish-storybook.yml" or something?
___
*[`.github/workflows/storybook.yml` line 5 at r1](https://reviewable.io/reviews/paranext/paranext-core/413#-NdGAODL8NQfZAqJlOv8:-NdGAODL8NQfZAqJlOv9:byjxvpo) ([raw file](https://github.com/paranext/paranext-core/blob/3997a678684a1496e3454aa483d6167af75ead00/.github/workflows/storybook.yml#L5)):*
> ```YAML
>   push:
>     branches:
>       - Sebastian-ubs/issue411
> ```

Should this branch name be `main`?

**Comment by Sebastian-ubs** [comment]
@tjcouch-sil seems it is using the user of the one that triggers the action by pushing. So the branch protection rule needs to be not too strict.
I can see the content being pushed [here](https://github.com/paranext/paranext-core/tree/github-pages).
However it was not updating the github page [there](https://paranext.github.io/paranext-core/).

**Review by tjcouch-sil — COMMENTED** [review]
It seems mine doesn't work by running `npx http-server storybook-static` as indicated in [this guide to testing the built storybook files locally](https://storybook.js.org/docs/react/sharing/publish-storybook), but it doesn't look like the same problem. After running `npm run storybook:build` locally, my 
`storybook-static/index.html` is different than the one in the github-pages branch. My `index.html` looks nothing like what's pictured, which is `github-pages/index.html`:



I also have fewer files in my `storybook-static` than what `github-pages` has:



I don't know what's going on here, but there must be some environmental difference or something.

Regarding authentication, do you know if `JamesIves/github-pages-deploy-action@3.6.2` provides a way to pass in a git auth token or something? I imagine there's probably a way to define secrets in the repo that we can pass into the workflow yml file to get special privileges to push to github-pages even if it's locked.

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/413#-:-NdGwQZm8l-KZoABYuLL:bm1mrbl)* status: all files reviewed, 2 unresolved discussions (waiting on @Sebastian-ubs)

**Comment by Sebastian-ubs** [comment]
Thank you. I recognized it also shows a blank page for me when built locally. Will need to have closer look into it.

Yes, `JamesIves/github-pages-deploy-action@3.6.2` allowes to specify auth token secrets

**Review by tjcouch-sil — COMMENTED** [review]
I added branch protection on the github-pages branch. Would you mind making some kind of change that triggers it and seeing if it works please? We can figure out authentication if it doesn't work.

> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/413#-:-NdbQDMa8Uljk6Jcy9_9:b-rbzoq4)* status: all files reviewed, 2 unresolved discussions (waiting on @Sebastian-ubs)

**Comment by Sebastian-ubs** [comment]
@tjcouch-sil pushing with my credentials does not work, but we could add an auth token of an allowed automation-user
>  remote: error: GH006: Protected branch update failed for refs/heads/github-pages.        
remote: error: You're not authorized to push to this branch. Visit https://docs.github.com/articles/about-protected-branches/ for more information.

**Comment by Sebastian-ubs** [comment]
> Thank you. I recognized it also shows a blank page for me when built locally. Will need to have closer look into it.

Probably it is because of `// TODO: Make this work in production mode`
https://github.com/paranext/paranext-core/blob/Sebastian-ubs/issue411/.storybook/main.ts#L35

**Review by tjcouch-sil — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/413)* status: 0 of 2 files reviewed, 3 unresolved discussions (waiting on @Sebastian-ubs)

___
*[`.github/workflows/storybook.yml` line 25 at r4](https://reviewable.io/reviews/paranext/paranext-core/413#-Ndk4deS7IDZUn3giyMP:-NdkO8J53trZmChImpTq:b-63i6cf) ([raw file](https://github.com/paranext/paranext-core/blob/ff931244a9b8a50062842473e285c3ec1b17ecd7/.github/workflows/storybook.yml#L25)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

I believe this is supposed to be [`token: ${{ secrets.PAGES_PAT }}`](https://github.com/JamesIves/github-pages-deploy-action#required-setup). I wonder if this has to do with this job not running. Otherwise I may have messed something up on my end.
</blockquote></details>

Hmm looks like it still didn't run. I changed something on my end. Would you mind pushing another fake change to see if the Storybook workflow runs? Thanks!

**Comment by Sebastian-ubs** [comment]
there is goes. well yes you are right we actually told it to only run on a change in components or stories ;-)
Other thing: We switch looking into how to publish with Chromatic instead so was not paying much attention here.

**Review by tjcouch-sil — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/413)* status: 0 of 2 files reviewed, 3 unresolved discussions (waiting on @Sebastian-ubs)

___
*[`.github/workflows/storybook.yml` line 25 at r4](https://reviewable.io/reviews/paranext/paranext-core/413#-Ndk4deS7IDZUn3giyMP:-NdkP3SI04LvGFIGH8X-:b-fv1i09) ([raw file](https://github.com/paranext/paranext-core/blob/ff931244a9b8a50062842473e285c3ec1b17ecd7/.github/workflows/storybook.yml#L25)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

Hmm looks like it still didn't run. I changed something on my end. Would you mind pushing another fake change to see if the Storybook workflow runs? Thanks!
</blockquote></details>

Looks like it's working again, but we changed multiple things at once. I'm going to change something on my end again. Would you mind making another fake commit please? Thanks!

**Comment by Sebastian-ubs** [comment]
Not quite decided. Maybe let's pause looking into fixing it for now. I can make it a draft PR or anything if the helps anybody

**Review by tjcouch-sil — COMMENTED** [review]
Ok gotcha. Looks like the authentication method I provided didn't work :( we'll have to investigate further if we look into this again. Thanks for the hard work!

> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/413#-:-NdkRfnk2Tb88UZlaOHW:b-5kocuy)* status: 0 of 2 files reviewed, 3 unresolved discussions (waiting on @Sebastian-ubs)

**Comment by irahopkinson** [comment]
@Sebastian-ubs can we close this PR since it hasn't moved for some time?

**Comment by Sebastian-ubs** [comment]
Yes, we will follow up in paranext/ux#3 it based on priority

**Pull request closed without merging**
