### PR TITLE
Implement get set reset pattern for useSetting and useWebViewState

### PR DESCRIPTION
**Pull request by rolfheij-sil**
This change is [Reviewable](https://reviewable.io/reviews/paranext/paranext-core/697)

### CODE REVIEW

**Review by rolfheij-sil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/697)* status: 0 of 5 files reviewed, 5 unresolved discussions

___
*[`src/renderer/hooks/papi-hooks/use-setting.hook.ts` line 44 at r1](https://reviewable.io/reviews/paranext/paranext-core/697#-NnPN1r5CsKnZSYeaXEj:-NnPN1r5CsKnZSYeaXEk:b-qa9i2b) ([raw file](https://github.com/paranext/paranext-core/blob/fd987e497ed5b0d9fa358f8741cc5929c058a09f/src/renderer/hooks/papi-hooks/use-setting.hook.ts#L44)):*
> ```XML
>     const unsubscriber = settingsService.subscribe(key, (newSetting) => {
>       if (newSetting.type === 'set-setting') {
>         // For some reason the function expects a `ScriptureReference | undefined` here, instead of the general `SettingTypes[SettingName]`
> ```

I'd like some help here
___
*[`src/shared/services/papi-core.service.ts` line 39 at r1](https://reviewable.io/reviews/paranext/paranext-core/697#-NnPN5Xb-N7DjkZdyu13:-NnPN5Xb-N7DjkZdyu14:b-qa9i2b) ([raw file](https://github.com/paranext/paranext-core/blob/fd987e497ed5b0d9fa358f8741cc5929c058a09f/src/shared/services/papi-core.service.ts#L39)):*
> ```XML
> export type { IWebViewProvider } from '@shared/models/web-view-provider.model';
> 
> // TODO: Do we really need to export? These types are only used internally in the useSettingHook
> ```

I'd like some help here
___
*[`src/shared/services/settings.service.ts` line 5 at r1](https://reviewable.io/reviews/paranext/paranext-core/697#-NnPNDFA3urrrlttiyiH:-NnPNDFA3urrrlttiyiI:b-wzp01h) ([raw file](https://github.com/paranext/paranext-core/blob/fd987e497ed5b0d9fa358f8741cc5929c058a09f/src/shared/services/settings.service.ts#L5)):*
> ```XML
> import { SettingNames, SettingTypes } from 'papi-shared-types';
> 
> /** Message sent to the client to give it NetworkConnectorInfo */
> ```

I tried to do something similiar to what `network-connector.model.ts` does, but don't know if I succeeded
___
*[`src/shared/services/settings.service.ts` line 62 at r1](https://reviewable.io/reviews/paranext/paranext-core/697#-NnPNOYJETZz0Trk0x45:-NnPNOYJETZz0Trk0x46:b-qa9i2b) ([raw file](https://github.com/paranext/paranext-core/blob/fd987e497ed5b0d9fa358f8741cc5929c058a09f/src/shared/services/settings.service.ts#L62)):*
> ```XML
>   // eslint-disable-next-line no-type-assertion/no-type-assertion
>   const emitter = onDidUpdateSettingEmitters.get(key);
>   // TODO: Why do I still need to specify `type` here? It's hardcoded in the SetSettingMessage type, right?
> ```

I'd like some help here
___
*[`src/shared/services/settings.service.ts` line 77 at r1](https://reviewable.io/reviews/paranext/paranext-core/697#-NnPNPWNEHZtQf7pAvFx:-NnPNPWNEHZtQf7pAvFy:b-qa9i2b) ([raw file](https://github.com/paranext/paranext-core/blob/fd987e497ed5b0d9fa358f8741cc5929c058a09f/src/shared/services/settings.service.ts#L77)):*
> ```XML
>   // eslint-disable-next-line no-type-assertion/no-type-assertion
>   const emitter = onDidUpdateSettingEmitters.get(key);
>   // TODO: Why do I still need to specify `type` here? It's hardcoded in the ResetSettingMessage type, right?
> ```

I'd like some help here

**Review by tjcouch-sil — COMMENTED** [review]
> Reviewed 4 of 5 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/697)* status: all files reviewed, 6 unresolved discussions (waiting on @rolfheij-sil)

___
*[`src/renderer/hooks/papi-hooks/use-setting.hook.ts` line 44 at r1](https://reviewable.io/reviews/paranext/paranext-core/697#-NnPN1r5CsKnZSYeaXEj:-Nnif1k_01vJISB0l_Ee:bvpvwn8) ([raw file](https://github.com/paranext/paranext-core/blob/fd987e497ed5b0d9fa358f8741cc5929c058a09f/src/renderer/hooks/papi-hooks/use-setting.hook.ts#L44)):*
<details><summary><i>Previously, rolfheij-sil wrote…</i></summary><blockquote>

I'd like some help here
</blockquote></details>

I believe this is happening because `newSetting.setting` is seen as any setting that exists. It is no longer narrowed down to the specific setting we are using in this hook, which is whatever `key` is, because of the changes to the `subscribe` function's types. This should be resolved if we fix the types in `settings.service.ts` as I mention there.
___
*[`src/shared/services/papi-core.service.ts` line 39 at r1](https://reviewable.io/reviews/paranext/paranext-core/697#-NnPN5Xb-N7DjkZdyu13:-Nnigc8M0IlBEZ1KD3vA:b-5hse7p) ([raw file](https://github.com/paranext/paranext-core/blob/fd987e497ed5b0d9fa358f8741cc5929c058a09f/src/shared/services/papi-core.service.ts#L39)):*
<details><summary><i>Previously, rolfheij-sil wrote…</i></summary><blockquote>

I'd like some help here
</blockquote></details>

The reason I suggested we export this is because it's an event that people can access on the setting service. Though the type is currently only specified inside the service, we are already using the type in the hook, for example. Anyone who uses the setting service's `subscribe` will be using this type, and they may want to have this type. We don't always need to export every single type we expose, but we should evaluate if someone might plausibly want to use each type we export. This one could definitely go either way; feel free to include it or leave it out for now. We don't know the future :)
___
*[`src/shared/services/settings.service.ts` line 5 at r1](https://reviewable.io/reviews/paranext/paranext-core/697#-NnPNDFA3urrrlttiyiH:-NnihuSM1mi2ZVY66eEW:bmh86ks) ([raw file](https://github.com/paranext/paranext-core/blob/fd987e497ed5b0d9fa358f8741cc5929c058a09f/src/shared/services/settings.service.ts#L5)):*
<details><summary><i>Previously, rolfheij-sil wrote…</i></summary><blockquote>

I tried to do something similiar to what `network-connector.model.ts` does, but don't know if I succeeded
</blockquote></details>

This is a bit tricky; you'll need to combine what you have here with the type specification that is happening elsewhere in this service with `SettingName`. You'll need to make `SetSettingMessage` have a generic parameter `SettingName` like in the functions in this service. Then `setting` in there will be `SettingTypes[SettingName]` instead of just `SettingTypes[SettingNames]`. Then you'll need to add this generic to `SettingMessage` as well so you can pass it into `SetSettingMessage`.

With what you have currently, TypeScript will never know which setting you're trying to use in any given situation, so it will combine the types of all the settings into one. That's why you're seeing `ScriptureReference | undefined`: currently, there are two settings, and those are their types. So we need to add a generic `SettingName` that extends `SettingNames`, which basically means that generic is guaranteed to be one of the `SettingNames`. That way, you can specify which setting is in question with `SettingMessage<'platform.verseRef'>` for example (or more likely in our situation here, it will look like `SettingMessage<SettingName>` probably every time you write it).

I would also recommend changing the names of these to better fit their use; something like `SettingMessage` -> `UpdateSettingEvent` or something might work well. But that's not necessary; just a suggestion for clearer readability.

Also please update JSDocs for these at some point :) thanks!
___
*[`src/shared/services/settings.service.ts` line 62 at r1](https://reviewable.io/reviews/paranext/paranext-core/697#-NnPNOYJETZz0Trk0x45:-NnikrVr6S5b4rGGokaZ:b-tcxcn2) ([raw file](https://github.com/paranext/paranext-core/blob/fd987e497ed5b0d9fa358f8741cc5929c058a09f/src/shared/services/settings.service.ts#L62)):*
<details><summary><i>Previously, rolfheij-sil wrote…</i></summary><blockquote>

I'd like some help here
</blockquote></details>

You have to specify `type` here because `SetSettingMessage` is only a *type*. TypeScript types only describe the shape of an object; they don't dictate what the object actually has. They are only hints that are applied over the JavaScript. So TypeScript tells you that you have to specify properly all the properties of an object of a specific type, but it can't actually put properties on the object even if it knows with certainty that a certain property has a certain type. To make it so you don't have to specify `type`, you can create something that will actually have `type` set inside it. To do this, you could turn `SetSettingMessage` into a class that has `type` set appropriately in its constructor. I played around a bit with some different options to see what might be a clean option while preventing `type` from being changed by devious extension devs and didn't come up with anything super nice. Feel free to [take a look](https://www.typescriptlang.org/play?#code/PTAEHEHsEMBsC5QGMBOBTaAXNprNtAM6GgDuAlpgBa6iYCeADjoypMyg3VVqIVZFIkAro1DkAdqABSAZQDyAOQB0hTCkkBzcgDN6oAEbDM4whIDkJ6Adg5MkQziQ8JmtABM+DtAA9sEwnJIKXc0ADcSJGgLE3cHULCg4RJqLUIAKHSQUABaPPz80AAhInIkXNAJB0I0JGENLgAKBmZkaMdkFzd3AEoAGkNjcUxzEkCAW0ZbXAlPACtkk1JIFABrQmVQABUqchIBCTQ1WH1x8k0qEwMcBbVQHUk0TKQCYm3d1wAeLYA+UABvdKgYGgRjCGxlUDoaBxCQnOhMHAAXlAlg+mnMAG5MiDkME1ChhEh7ChGmCIeU1MIdDpEFsegCAL7pZnpJD4kypVygFGHUjvLSNcw2aBUcw9bFZMDQ2HwvagW5WbaI2SociMEwfEw5YagOJHGK4YnCODw1jhNASJYNLSbIpDSh6yBHPgCfntNAoNgoAaEByO3i2IgmSTuMpYF2QeriK2WzDpLmaZQtZGong8UAASU60W63Hl0XopGg9AAhFjnvjILZlLBIJpmuiJZlsgU26BZLV6pR9AZ9OhxpBEtzqDhrORYD26A5nLm7FQ7Ijnq8SDstAAmb5-QG48mT8oy4LwlM81GJ9cVoEg9kBdREklk8H7viYam07YMne4kHyAxzWqYMooQPIcAAKbAcAwjZ7AMliIuYAxft+35hHAwhoIgqQbCmfRXshuKkA01i2IgOhwDUuH4d+lrCOMnrERhdCEmglFUdewQPJo9QMaR5EsXh36Ms2uLMqyN53Oep58gKrjrkKIpUBezZSvmsnJoip4AET0FGbSGrOrhjpUwQ5IRlAMaAqGwOhmmSuJ1ZoLW9bQbJymtm2hQAKo1LQahYJCbiYNgKCbOBaBBfoEhlCxfBdugAxGCYOnCKAPBhHYDjJDgAAG9hyEo2UzJ4hDMEguj6KOoCBcFdAUEgTxsiuMmaAAzFuAICXukJ+ZgAXhQizCNJ+Am4ugr4oFIaJaC1FYiTiILZAAEtA6XTqCQxYaAwQZaC6DpVaoJoOw0w6Gw4y4MQWhaGtiYtepzCdU+fWcoiQ0dVRY31FIa6uHdKbYnNAniXexIrI+FKqZohB0p+rK4nlCiKG9SHfktK07SVtTlQNOALugjhRFlVXhcFJDQPjVQmASV0PB4I0gp9E0AqAyis1hAwpnS6J-RpzJzWJHKQy1UloPyP2tfJBBUDNblgOLPOtCi2m6VE+ldEZPXPcFoyWWhaC2Spt33amysparlg5oZtDVZ6OtWTZdlVjWdYNrdsu5B5eSgN5Rk2ygRUzEar6mvorDkKh2D4EQJC07A7ihWNXBRfVvpxTFiWgMlqXo2tRO5ZA+WKIV0TuCpbG7eHEZR28sfuPsOd4AYjqQDoW3pSgC4wjGMiyAT0BE5TuCwLAhhsEInpjKIjArJyC7nX63BoPo5MsNW9APMPdONdHzUACztSjADEJ4olNri77NIJdeUgU48j9PAozUhYcox+IgDIJw+xt6EqDpLX5DaGH4mTzWBAjJQ98qJo1WvYPgpVsYnjxjga4hMfJhwjiwCCnpeouhXsZKm6gabkDph9cKX1mas2TLsQgHNESYWoa-E8fNP4skrLeSGu8RZi3RLvSWooL7u0TLvY2Wks7mxMAZNw1sSa2xIPbfW2JshCMYRpJWYjogW0kUZdBVdWDsGwfQO2esDZsido5F2LlNC73djsT0Y58aQFHP7dgvV8Qc0gJAAYk5Vg4GApIa6eAqgSFMkRGwOBa5bWfguauJA9H2EQUFRg0MQB+SQKsIcnodB1lIModk4xgAAEd0JqCCAEYAAA2AAHAARnXAABkqQATnKcAPYOQnFoByNAHILxo45DQEUyutgrTtMgDkOJjjERdKChoRKRwgA) and consider :) feel free to ask me questions if you're interested in the JS/TS intricacies here. Feel free to just pick one of those options; doesn't really matter that much, I don't think.
___
*[`src/shared/services/settings.service.ts` line 77 at r1](https://reviewable.io/reviews/paranext/paranext-core/697#-NnPNPWNEHZtQf7pAvFx:-NnitgkaBExcvXYRmrqL:bkm1mmt) ([raw file](https://github.com/paranext/paranext-core/blob/fd987e497ed5b0d9fa358f8741cc5929c058a09f/src/shared/services/settings.service.ts#L77)):*
<details><summary><i>Previously, rolfheij-sil wrote…</i></summary><blockquote>

I'd like some help here
</blockquote></details>

See reply above
___
*[`src/shared/services/settings.service.ts` line 92 at r2](https://reviewable.io/reviews/paranext/paranext-core/697#-NnikY033BRkjY7mUjAB:-NnikY033BRkjY7mUjAC:babi21v) ([raw file](https://github.com/paranext/paranext-core/blob/72a273f37d6770d0c740de4ccde414e766fd86c8/src/shared/services/settings.service.ts#L92)):*
> ```XML
> const subscribeToSetting = <SettingName extends SettingNames>(
>   key: SettingName,
>   callback: (newSetting: SettingMessage) => void,
> ```

All throughout this function, you'll want to update `SettingMessage` to have the generic specified: `SettingMessage<SettingName>`. Especially on this callback as that will affect users of the function. When you make this change, you will probably not have any more trouble with types in `useSetting` and will be able to remove the type assertion.

**Review by tjcouch-sil — COMMENTED** [review]
Looks great! Just one little thing that got auto-changed and needs to be adjusted. Thanks!

> Reviewed 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/697#-:-NoI8mTW3w9QCmMvdnij:bh9vxse)* status: all files reviewed, 1 unresolved discussion (waiting on @rolfheij-sil)

___
*[`src/shared/services/papi-core.service.ts` line 39 at r3](https://reviewable.io/reviews/paranext/paranext-core/697#-NoI8I2K5Lb52XyKu_bf:-NoI8I2K5Lb52XyKu_bg:bz7wv67) ([raw file](https://github.com/paranext/paranext-core/blob/f4ad1146812ecc5347b565746def0c82f5c4da5d/src/shared/services/papi-core.service.ts#L39)):*
> ```XML
> export type { IWebViewProvider } from '@shared/models/web-view-provider.model';
> 
> export type { SettingEvent as SettingMessage } from '@shared/services/settings.service';
> ```

Unfortunately it looks like they tried to preserve the old name here when you renamed `SettingMessage` to `SettngEvent` :( sorry bout that

**Review by rolfheij-sil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/697)* status: 4 of 6 files reviewed, 1 unresolved discussion (waiting on @tjcouch-sil)

___
*[`src/renderer/hooks/papi-hooks/use-setting.hook.ts` line 44 at r1](https://reviewable.io/reviews/paranext/paranext-core/697#-NnPN1r5CsKnZSYeaXEj:-NoI78MK0ViY0qWBEmup:b-896fix) ([raw file](https://github.com/paranext/paranext-core/blob/fd987e497ed5b0d9fa358f8741cc5929c058a09f/src/renderer/hooks/papi-hooks/use-setting.hook.ts#L44)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

I believe this is happening because `newSetting.setting` is seen as any setting that exists. It is no longer narrowed down to the specific setting we are using in this hook, which is whatever `key` is, because of the changes to the `subscribe` function's types. This should be resolved if we fix the types in `settings.service.ts` as I mention there.
</blockquote></details>

Done.
___
*[`src/shared/services/papi-core.service.ts` line 39 at r3](https://reviewable.io/reviews/paranext/paranext-core/697#-NoI8I2K5Lb52XyKu_bf:-NoI9PwY9Eet9U_CVUFc:b-896fix) ([raw file](https://github.com/paranext/paranext-core/blob/f4ad1146812ecc5347b565746def0c82f5c4da5d/src/shared/services/papi-core.service.ts#L39)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

Unfortunately it looks like they tried to preserve the old name here when you renamed `SettingMessage` to `SettngEvent` :( sorry bout that
</blockquote></details>

Done.
___
*[`src/shared/services/settings.service.ts` line 5 at r1](https://reviewable.io/reviews/paranext/paranext-core/697#-NnPNDFA3urrrlttiyiH:-NoI7MR52q5pMst-rgkP:b-896fix) ([raw file](https://github.com/paranext/paranext-core/blob/fd987e497ed5b0d9fa358f8741cc5929c058a09f/src/shared/services/settings.service.ts#L5)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

This is a bit tricky; you'll need to combine what you have here with the type specification that is happening elsewhere in this service with `SettingName`. You'll need to make `SetSettingMessage` have a generic parameter `SettingName` like in the functions in this service. Then `setting` in there will be `SettingTypes[SettingName]` instead of just `SettingTypes[SettingNames]`. Then you'll need to add this generic to `SettingMessage` as well so you can pass it into `SetSettingMessage`.

With what you have currently, TypeScript will never know which setting you're trying to use in any given situation, so it will combine the types of all the settings into one. That's why you're seeing `ScriptureReference | undefined`: currently, there are two settings, and those are their types. So we need to add a generic `SettingName` that extends `SettingNames`, which basically means that generic is guaranteed to be one of the `SettingNames`. That way, you can specify which setting is in question with `SettingMessage<'platform.verseRef'>` for example (or more likely in our situation here, it will look like `SettingMessage<SettingName>` probably every time you write it).

I would also recommend changing the names of these to better fit their use; something like `SettingMessage` -> `UpdateSettingEvent` or something might work well. But that's not necessary; just a suggestion for clearer readability.

Also please update JSDocs for these at some point :) thanks!
</blockquote></details>

Done.
___
*[`src/shared/services/settings.service.ts` line 92 at r2](https://reviewable.io/reviews/paranext/paranext-core/697#-NnikY033BRkjY7mUjAB:-NoI7PCj7V4_NK49EC8y:b-896fix) ([raw file](https://github.com/paranext/paranext-core/blob/72a273f37d6770d0c740de4ccde414e766fd86c8/src/shared/services/settings.service.ts#L92)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

All throughout this function, you'll want to update `SettingMessage` to have the generic specified: `SettingMessage<SettingName>`. Especially on this callback as that will affect users of the function. When you make this change, you will probably not have any more trouble with types in `useSetting` and will be able to remove the type assertion.
</blockquote></details>

Done.

**Review by tjcouch-sil — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/697#-:-NoIAGB1Dt5Dgy9sSqDK:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Pull request merged**
