### PR TITLE
Add Table component

### PR DESCRIPTION
**Pull request by rolfheij-sil**
This change is [Reviewable](https://reviewable.io/reviews/paranext/paranext-core/157)

### CODE REVIEW

**Review by tjcouch-sil — CHANGES_REQUESTED** [review]
Looks great! Just one thing to check on to make sure we're not exposing react grid stuff, but I'm really excited about this! Thanks for all the hard work!!

> Reviewed 3 of 6 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/157#-:-NTnWeS44zyVJ-SbQlFZ:b-d418oj)* status: all files reviewed, 1 unresolved discussion (waiting on @rolfheij-sil)

___
*[`src/renderer/components/papi-components/table.component.tsx` line 100 at r2](https://reviewable.io/reviews/paranext/paranext-core/157#-NTnUMeEEkuV1wpCvqmO:-NTnUMeEEkuV1wpCvqmP:bchykxa) ([raw file](https://github.com/paranext/paranext-core/blob/414851bdb7c300bf1a9c4f8297ab0cb20050d571/src/renderer/components/papi-components/table.component.tsx#L100)):*
> ```XML
> export const TableSelectColumn = SelectColumn;
> export type TableSortColumn = SortColumn;
> export const TableTextEditor = textEditor;
> ```

I think this may be exposing the react data grid internal stuff. Do you know what this `textEditor` does? Can we reasonably make our own with our own React component? Seems the `TableEditorProps` are at least reasonably straight-forward :)

**Review by tjcouch-sil — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/157)* status: all files reviewed, 1 unresolved discussion (waiting on @rolfheij-sil)

___
*[`src/renderer/components/papi-components/table.component.tsx` line 100 at r2](https://reviewable.io/reviews/paranext/paranext-core/157#-NTnUMeEEkuV1wpCvqmO:-NTnWqDN0LhOrEj_EYzP:bmzhab5) ([raw file](https://github.com/paranext/paranext-core/blob/414851bdb7c300bf1a9c4f8297ab0cb20050d571/src/renderer/components/papi-components/table.component.tsx#L100)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

I think this may be exposing the react data grid internal stuff. Do you know what this `textEditor` does? Can we reasonably make our own with our own React component? Seems the `TableEditorProps` are at least reasonably straight-forward :)
</blockquote></details>

Actually, now that I think about it, since you made it exported from this file, we could just rework it in the future. I think it's ok if you want to leave it!

**Review by katherinejensen00 — APPROVED** [review]
I had some questions, but those are mainly academic. I think this looks pretty good.

> Reviewed 3 of 6 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/157#-:-NToePXSEQ4GbYrbmCFN:bf4tjj5)* status: all files reviewed, 3 unresolved discussions (waiting on @rolfheij-sil)

___
*[`package.json` line 100 at r2](https://reviewable.io/reviews/paranext/paranext-core/157#-NToU38q1UUDruOEB9ur:-NToU38q1UUDruOEB9us:byjbksg) ([raw file](https://github.com/paranext/paranext-core/blob/414851bdb7c300bf1a9c4f8297ab0cb20050d571/package.json#L100)):*
> ```JSON
>     "rc-dock": "^3.2.17",
>     "react": "^18.2.0",
>     "react-data-grid": "^7.0.0-beta.28",
> ```

BTW  Is there a particular reason we are using a beta version? I am just curious. I am sure it is great and probably there for some cool feature or other.
___
*[`src/stories/table.stories.tsx` line 60 at r2](https://reviewable.io/reviews/paranext/paranext-core/157#-NTodnKr9teUlXAOI3d7:-NTodnKr9teUlXAOI3d8:b-lx5oij) ([raw file](https://github.com/paranext/paranext-core/blob/414851bdb7c300bf1a9c4f8297ab0cb20050d571/src/stories/table.stories.tsx#L60)):*
> ```XML
>             }
>           }
>           return 0; // What do we need this for?
> ```

Do we have an answer for this?

**Review by rolfheij-sil — COMMENTED** [review]
Thanks for taking a look :)

> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/157#-:-NTrYAJr-Y4BeZ8-ivUC:bpug4ke)* status: all files reviewed, 3 unresolved discussions (waiting on @katherinejensen00 and @tjcouch-sil)

___
*[`package.json` line 100 at r2](https://reviewable.io/reviews/paranext/paranext-core/157#-NToU38q1UUDruOEB9ur:-NTrRjVN7GSU3HaoWazf:blqjsr9) ([raw file](https://github.com/paranext/paranext-core/blob/414851bdb7c300bf1a9c4f8297ab0cb20050d571/package.json#L100)):*
<details><summary><i>Previously, katherinejensen00 wrote…</i></summary><blockquote>

BTW  Is there a particular reason we are using a beta version? I am just curious. I am sure it is great and probably there for some cool feature or other.
</blockquote></details>

I didn't choose this version on purpose, I just ran `npm install react-data-grid` :grin: 
But it seems their latest stable version is v6.1.0 which was published over 4 years ago. Ever since then they've been creating alpha and beta versions for v7.0.0, so it seems like a beta version is the most stable thing we can get.
___
*[`src/renderer/components/papi-components/table.component.tsx` line 100 at r2](https://reviewable.io/reviews/paranext/paranext-core/157#-NTnUMeEEkuV1wpCvqmO:-NTrWiGl-oxz8IgihasT:b-bf9l2t) ([raw file](https://github.com/paranext/paranext-core/blob/414851bdb7c300bf1a9c4f8297ab0cb20050d571/src/renderer/components/papi-components/table.component.tsx#L100)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

Actually, now that I think about it, since you made it exported from this file, we could just rework it in the future. I think it's ok if you want to leave it!
</blockquote></details>

I've updated it, should be fine now. But don't we have a similar issue with `export const TableSelectColumn = SelectColumn;` ? I wasn't able to fix that one easily unfortunately
___
*[`src/stories/table.stories.tsx` line 60 at r2](https://reviewable.io/reviews/paranext/paranext-core/157#-NTodnKr9teUlXAOI3d7:-NTrX6Og6E2yZ3LaLUXa:bxi07df) ([raw file](https://github.com/paranext/paranext-core/blob/414851bdb7c300bf1a9c4f8297ab0cb20050d571/src/stories/table.stories.tsx#L60)):*
<details><summary><i>Previously, katherinejensen00 wrote…</i></summary><blockquote>

Do we have an answer for this?
</blockquote></details>

The best answer I could give right now is this: the `sort` function requires a return value in all cases. Since the return on line 57 is conditional, eslint is not satisfied with that return being the only one.
So we have to add this (unconditional) return that returns a dummy value, even though it will most likely never be executed.
We can also choose to just silent this warning, like we did on line 52 (eslint doesn't like range-based for loops)

**Review by rolfheij-sil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/157)* status: 5 of 6 files reviewed, 3 unresolved discussions (waiting on @katherinejensen00 and @tjcouch-sil)

___
*[`src/renderer/components/papi-components/table.component.tsx` line 100 at r2](https://reviewable.io/reviews/paranext/paranext-core/157#-NTnUMeEEkuV1wpCvqmO:-NTrYekREsFnc7c3AmJ_:bly0ztg) ([raw file](https://github.com/paranext/paranext-core/blob/414851bdb7c300bf1a9c4f8297ab0cb20050d571/src/renderer/components/papi-components/table.component.tsx#L100)):*
<details><summary><i>Previously, rolfheij-sil wrote…</i></summary><blockquote>

I've updated it, should be fine now. But don't we have a similar issue with `export const TableSelectColumn = SelectColumn;` ? I wasn't able to fix that one easily unfortunately
</blockquote></details>

Hmm, I basically copied the content of textEditor from the original, but now I'm no longer able to edit any text.. So I'll revert my changes for now. If you feel like we need to look into it some more, let me know

**Review by tjcouch-sil — DISMISSED** [review]
Thanks again for the hard work!

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/157#-:-NTsiatnA1hSJeFxcZ5K:bp9b3hv)* status: all files reviewed, 3 unresolved discussions (waiting on @katherinejensen00 and @rolfheij-sil)

___
*[`src/renderer/components/papi-components/table.component.tsx` line 100 at r2](https://reviewable.io/reviews/paranext/paranext-core/157#-NTnUMeEEkuV1wpCvqmO:-NTsaVsK4MGQBhadU_cO:bk4uwwa) ([raw file](https://github.com/paranext/paranext-core/blob/414851bdb7c300bf1a9c4f8297ab0cb20050d571/src/renderer/components/papi-components/table.component.tsx#L100)):*
<details><summary><i>Previously, rolfheij-sil wrote…</i></summary><blockquote>

Hmm, I basically copied the content of textEditor from the original, but now I'm no longer able to edit any text.. So I'll revert my changes for now. If you feel like we need to look into it some more, let me know
</blockquote></details>

Ok, that's fine.

We discussed some thoughts regarding `SelectColumn` in a call this morning. Hoping to have a boolean on our table component that shows the select checkboxes. Thanks!
___
*[`src/stories/table.stories.tsx` line 60 at r2](https://reviewable.io/reviews/paranext/paranext-core/157#-NTodnKr9teUlXAOI3d7:-NTsaMvX1eh7YWAa-B-K:b-ab9ruv) ([raw file](https://github.com/paranext/paranext-core/blob/414851bdb7c300bf1a9c4f8297ab0cb20050d571/src/stories/table.stories.tsx#L60)):*
<details><summary><i>Previously, rolfheij-sil wrote…</i></summary><blockquote>

The best answer I could give right now is this: the `sort` function requires a return value in all cases. Since the return on line 57 is conditional, eslint is not satisfied with that return being the only one.
So we have to add this (unconditional) return that returns a dummy value, even though it will most likely never be executed.
We can also choose to just silent this warning, like we did on line 52 (eslint doesn't like range-based for loops)
</blockquote></details>

Maybe we could throw to indicate there is a problem if this code is reached?

**Review by rolfheij-sil — COMMENTED** [review]
My pleasure!

> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/157#-:-NTxFzZd49EtxcljChij:b-9j84vv)* status: 4 of 6 files reviewed, 1 unresolved discussion (waiting on @katherinejensen00 and @tjcouch-sil)

___
*[`src/stories/table.stories.tsx` line 60 at r2](https://reviewable.io/reviews/paranext/paranext-core/157#-NTodnKr9teUlXAOI3d7:-NTxJ9sF0Q10n3vLCEB4:b-k7fn93) ([raw file](https://github.com/paranext/paranext-core/blob/414851bdb7c300bf1a9c4f8297ab0cb20050d571/src/stories/table.stories.tsx#L60)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

Maybe we could throw to indicate there is a problem if this code is reached?
</blockquote></details>

Good idea. Done

**Review by tjcouch-sil — DISMISSED** [review]
:lgtm: thanks for all the hard work!! So excited we have a table :) great work!

> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/157#-:-NTxmyY53im8fBN6PFKG:b-cswzve)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @rolfheij-sil)

___
*[`src/renderer/components/papi-components/table.component.tsx` line 267 at r4](https://reviewable.io/reviews/paranext/paranext-core/157#-NTxmNRk338AE0UHFVlN:-NTxmNRk338AE0UHFVlO:b-orood3) ([raw file](https://github.com/paranext/paranext-core/blob/d4cca499286924e630e19f1babc7e5c669901d9d/src/renderer/components/papi-components/table.component.tsx#L267)):*
> ```XML
>   return (
>     <DataGrid<T>
>       columns={useMemo(() => {
> ```

This is not a usual pattern. Usually people put hooks above the return and assign them to `const`s. However, it is not a big enough deal to change in this PR. I say we go for it!

**Review by rolfheij-sil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/157)* status: 2 of 6 files reviewed, all discussions resolved (waiting on @katherinejensen00 and @tjcouch-sil)

___
*[`src/renderer/components/papi-components/table.component.tsx` line 267 at r4](https://reviewable.io/reviews/paranext/paranext-core/157#-NTxmNRk338AE0UHFVlN:-NTxxc6l0qXlcg3YLbWI:b-kaqglo) ([raw file](https://github.com/paranext/paranext-core/blob/d4cca499286924e630e19f1babc7e5c669901d9d/src/renderer/components/papi-components/table.component.tsx#L267)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

This is not a usual pattern. Usually people put hooks above the return and assign them to `const`s. However, it is not a big enough deal to change in this PR. I say we go for it!
</blockquote></details>

I fixed it anyways :)

**Review by katherinejensen00 — APPROVED** [review]
> Reviewed 4 of 4 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/157)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @rolfheij-sil)

**Review by katherinejensen00 — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/157#-:-NTy67TICq7zzaWep_w3:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @rolfheij-sil)

**Pull request merged**
