### PR TITLE
Add a new thread for message sending due to web socket requirements

### PR DESCRIPTION
**Pull request by lyonsil**
This change is [Reviewable](https://reviewable.io/reviews/paranext/paranext-core/140)

### CODE REVIEW

**Review by katherinejensen00 — CHANGES_REQUESTED** [review]
I think this looks pretty good and makes sense.

> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/140#-:-NSg2cND7lF1dIVpBAGb:b-wxrzjz)* status: all files reviewed, 1 unresolved discussion (waiting on @lyonsil)

___
*[`c-sharp/MessageTransports/PapiClient.cs` line 130 at r1](https://reviewable.io/reviews/paranext/paranext-core/140#-NSg0vQNEe4kmK4XyXgP:-NSg0vQNEe4kmK4XyXgQ:b-vobx9f) ([raw file](https://github.com/paranext/paranext-core/blob/26ff8c40a67bdcc6a73a1bf56bab1ec8755ab563/c-sharp/MessageTransports/PapiClient.cs#L130)):*
> ```Smalltalk
>     /// If false is returned, then there is no need to call <see cref="DisconnectAsync"/> before calling <see cref="Dispose"/>.
>     /// </summary>
>     /// <returns><see cref="Task"/> will resolve to true if the connection initialied properly, false otherwise</returns>
> ```

Suspected Typo: intialied should probably be initialized

**Review by lyonsil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/140)* status: 2 of 4 files reviewed, 1 unresolved discussion (waiting on @katherinejensen00)

___
*[`c-sharp/MessageTransports/PapiClient.cs` line 130 at r1](https://reviewable.io/reviews/paranext/paranext-core/140#-NSg0vQNEe4kmK4XyXgP:-NSg7LTk2lmHj33hCSny:b-z1qknh) ([raw file](https://github.com/paranext/paranext-core/blob/26ff8c40a67bdcc6a73a1bf56bab1ec8755ab563/c-sharp/MessageTransports/PapiClient.cs#L130)):*
<details><summary><i>Previously, katherinejensen00 wrote…</i></summary><blockquote>

Suspected Typo: intialied should probably be initialized
</blockquote></details>

Fixed - Indeed, your are correct!

**Review by lyonsil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/140)* status: 2 of 4 files reviewed, 1 unresolved discussion (waiting on @katherinejensen00)

___
*[`c-sharp/MessageTransports/PapiClient.cs` line 130 at r1](https://reviewable.io/reviews/paranext/paranext-core/140#-NSg0vQNEe4kmK4XyXgP:-NSg7i7R2wudKH2VyB_5:b-ghrey9) ([raw file](https://github.com/paranext/paranext-core/blob/26ff8c40a67bdcc6a73a1bf56bab1ec8755ab563/c-sharp/MessageTransports/PapiClient.cs#L130)):*
<details><summary><i>Previously, lyonsil wrote…</i></summary><blockquote>

Fixed - Indeed, your are correct!
</blockquote></details>

"you" are correct - man, spelling error when talking about my other spelling error! :smile:

**Review by katherinejensen00 — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/140#-:-NSg2sks7IE0Pm6p0mNe:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @lyonsil)

___
*[`c-sharp/MessageTransports/PapiClient.cs` line 130 at r1](https://reviewable.io/reviews/paranext/paranext-core/140#-NSg0vQNEe4kmK4XyXgP:-NSgCLHg6F39S81ZFpFN:b-k99ov1) ([raw file](https://github.com/paranext/paranext-core/blob/26ff8c40a67bdcc6a73a1bf56bab1ec8755ab563/c-sharp/MessageTransports/PapiClient.cs#L130)):*
<details><summary><i>Previously, lyonsil wrote…</i></summary><blockquote>

"you" are correct - man, spelling error when talking about my other spelling error! :smile: 
</blockquote></details>

Ha ha. Thanks for making that nitpicky change :)

**Review by FoolRunning — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/140)* status: all files reviewed, 3 unresolved discussions (waiting on @lyonsil)

___
*[`c-sharp/MessageTransports/PapiClient.cs` line 189 at r1](https://reviewable.io/reviews/paranext/paranext-core/140#-NSgCeCBCTNopoM5o5G-:-NSgCeCBCTNopoM5o5G0:bo1ylji) ([raw file](https://github.com/paranext/paranext-core/blob/26ff8c40a67bdcc6a73a1bf56bab1ec8755ab563/c-sharp/MessageTransports/PapiClient.cs#L189)):*
> ```Smalltalk
>             _incomingMessageThread.Join();
>         if (_outgoingMessageThread.IsAlive)
>             _outgoingMessageThread.Join();
> ```

This looks/feels like the code in ``DisconnectAsync``. Should this also have a timeout or maybe the code of both places be merged together?
___
*[`c-sharp/MessageTransports/PapiClient.cs` line 325 at r1](https://reviewable.io/reviews/paranext/paranext-core/140#-NSgL1dl95RpZY4EOMyB:-NSgL1dl95RpZY4EOMyC:bqqn314) ([raw file](https://github.com/paranext/paranext-core/blob/b1b2cdeeff70e3adba4f8e3471b672f7f469ecce/c-sharp/MessageTransports/PapiClient.cs#L325)):*
> ```Smalltalk
>                     }
>                     else
>                     {
> ```

Is there a reason you moved this ``null`` check into where the new thread is handling it instead of not starting a new thread in the first place?

**Review by lyonsil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/140)* status: all files reviewed, 3 unresolved discussions (waiting on @FoolRunning)

___
*[`c-sharp/MessageTransports/PapiClient.cs` line 189 at r1](https://reviewable.io/reviews/paranext/paranext-core/140#-NSgCeCBCTNopoM5o5G-:-NSgM9_SBJUGu1weiZUU:bsczi0r) ([raw file](https://github.com/paranext/paranext-core/blob/26ff8c40a67bdcc6a73a1bf56bab1ec8755ab563/c-sharp/MessageTransports/PapiClient.cs#L189)):*
<details><summary><i>Previously, FoolRunning (Tim Steenwyk) wrote…</i></summary><blockquote>

This looks/feels like the code in ``DisconnectAsync``. Should this also have a timeout or maybe the code of both places be merged together?
</blockquote></details>

The only use of this function at least right now is for the main program thread to block (in a multi-threading friendly way) once it has done everything else it thinks it needs to do.  I could add the timeout back, but it's also a little weird because a timeout passed in will either be cut in half for each thread or be doubled as it applies to each thread.

In `DisconnectAsync` I definitely wanted a timeout for the reasons we discussed in that PR.  For this function, the need for a timeout wasn't as clear to me.  It's not hard to add one back here, but combining that with the `DisconnectAsync` case is a little more complex because when disconnecting it definitely is an error if the threads don't join quickly.  In the main program thread case, maybe someone later wants to block here but wake up every X seconds to do something else in the background.  If that's the use case, then we don't want to log an error message if the threads didn't join before the timeout happens.

Of course we could have some argument like an optional error message if the timeout happens without joining, but that starts to looks like a clunky function IMO.

I don't have a super string opinion here.  If you think they should be combined, please suggest what you think an appropriate function signature for this should be that takes into account:
- Doubling/halving the timeout period,
- Whether to log an error or not if the timeout is reached (including whether the caller should provide the error message)
- If we're looking for a general "block" function, whether we should support a cancellation token like we use in other parts of the code
___
*[`c-sharp/MessageTransports/PapiClient.cs` line 325 at r1](https://reviewable.io/reviews/paranext/paranext-core/140#-NSgL1dl95RpZY4EOMyB:-NSgLN_YAVKl8W2POgrQ:b6vmiac) ([raw file](https://github.com/paranext/paranext-core/blob/b1b2cdeeff70e3adba4f8e3471b672f7f469ecce/c-sharp/MessageTransports/PapiClient.cs#L325)):*
<details><summary><i>Previously, FoolRunning (Tim Steenwyk) wrote…</i></summary><blockquote>

Is there a reason you moved this ``null`` check into where the new thread is handling it instead of not starting a new thread in the first place?
</blockquote></details>

It could go in either place.  I moved it because semantically as I was trying to clarify what each thread was responsible for, I was settling on:
- Outgoing thread is responsible for pulling messages off the blocking queue and passing them to the web socket
- Incoming thread is responsible for pulling data off the web socket, transforming it to a message, and passing it to a worker thread
- Worker threads are responsible for doing whatever is appropriate with a message

I think the resulting code looks a little more balanced between the incoming and outgoing thread functions.  Having said that, it really would work in either place.

**Review by lyonsil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/140)* status: all files reviewed, 3 unresolved discussions (waiting on @FoolRunning and @katherinejensen00)

___
*[`c-sharp/MessageTransports/PapiClient.cs` line 130 at r1](https://reviewable.io/reviews/paranext/paranext-core/140#-NSg0vQNEe4kmK4XyXgP:-NSgOjJGBcK7m4NUsjZ1:b-896fix) ([raw file](https://github.com/paranext/paranext-core/blob/26ff8c40a67bdcc6a73a1bf56bab1ec8755ab563/c-sharp/MessageTransports/PapiClient.cs#L130)):*
<details><summary><i>Previously, katherinejensen00 wrote…</i></summary><blockquote>

Ha ha. Thanks for making that nitpicky change :)
</blockquote></details>

Done.

**Review by FoolRunning — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/140)* status: all files reviewed, 1 unresolved discussion (waiting on @katherinejensen00)

___
*[`c-sharp/MessageTransports/PapiClient.cs` line 189 at r1](https://reviewable.io/reviews/paranext/paranext-core/140#-NSgCeCBCTNopoM5o5G-:-NSgW5fz9araoM1oWblB:b-plbw47) ([raw file](https://github.com/paranext/paranext-core/blob/26ff8c40a67bdcc6a73a1bf56bab1ec8755ab563/c-sharp/MessageTransports/PapiClient.cs#L189)):*
<details><summary><i>Previously, lyonsil wrote…</i></summary><blockquote>

The only use of this function at least right now is for the main program thread to block (in a multi-threading friendly way) once it has done everything else it thinks it needs to do.  I could add the timeout back, but it's also a little weird because a timeout passed in will either be cut in half for each thread or be doubled as it applies to each thread.

In `DisconnectAsync` I definitely wanted a timeout for the reasons we discussed in that PR.  For this function, the need for a timeout wasn't as clear to me.  It's not hard to add one back here, but combining that with the `DisconnectAsync` case is a little more complex because when disconnecting it definitely is an error if the threads don't join quickly.  In the main program thread case, maybe someone later wants to block here but wake up every X seconds to do something else in the background.  If that's the use case, then we don't want to log an error message if the threads didn't join before the timeout happens.

Of course we could have some argument like an optional error message if the timeout happens without joining, but that starts to looks like a clunky function IMO.

I don't have a super string opinion here.  If you think they should be combined, please suggest what you think an appropriate function signature for this should be that takes into account:
- Doubling/halving the timeout period,
- Whether to log an error or not if the timeout is reached (including whether the caller should provide the error message)
- If we're looking for a general "block" function, whether we should support a cancellation token like we use in other parts of the code
</blockquote></details>

Let's just leave it for now
___
*[`c-sharp/MessageTransports/PapiClient.cs` line 325 at r1](https://reviewable.io/reviews/paranext/paranext-core/140#-NSgL1dl95RpZY4EOMyB:-NSgWRpQEn-wYcEG7ILB:by6bp8w) ([raw file](https://github.com/paranext/paranext-core/blob/b1b2cdeeff70e3adba4f8e3471b672f7f469ecce/c-sharp/MessageTransports/PapiClient.cs#L325)):*
<details><summary><i>Previously, lyonsil wrote…</i></summary><blockquote>

It could go in either place.  I moved it because semantically as I was trying to clarify what each thread was responsible for, I was settling on:
- Outgoing thread is responsible for pulling messages off the blocking queue and passing them to the web socket
- Incoming thread is responsible for pulling data off the web socket, transforming it to a message, and passing it to a worker thread
- Worker threads are responsible for doing whatever is appropriate with a message

I think the resulting code looks a little more balanced between the incoming and outgoing thread functions.  Having said that, it really would work in either place.

</blockquote></details>

I guess it's fine.

**Review by katherinejensen00 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/140)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @lyonsil)

**Pull request merged**
