### PR TITLE
Added `helloWorld` TypeScript test PDP

### LINKED ISSUE #509: Project Settings: Create basic async project settings service
As an extension developer, I want to be able to access project settings like Biblical Terms list on the PAPI so I can develop effectively.

----

We need a project settings service that allows any PSI to validate project settings before saving (PSI actually handles project settings, and PDP passes through to PSI):

- [x] Main process should have project settings service host that has a network object. Other processes imitate and access with project settings service. `papi.projectSettings`
  - [x] Maintain list of all project settings' default values (hard-coded; we will load from extensions in #721)
  - [x] Create a new `ProjectSettingTypes` shared type in `papi-shared-types` along the same lines as `SettingTypes`
    - [x] Include some real settings - books present, language, versification
  - [x] `papi.projectSettings.isValid(newValue, currentValue, key, allChanges, projectType)` - simply returns true. This is just a placeholder for now that will be implemented later - see #511 for information on what `allChanges` is
  - [x] `papi.projectSettings.getDefault(key, projectType)` - provides the default value for the project setting
    - If project setting default is provided in extensions or built into core (though for now the list is just built into core as mentioned above), returns project setting default
    - If project setting default is not provided anywhere, throws
- [x] PDP needs a new data type in its MandatoryDataTypes `Setting: DataProviderDataTypes<ProjectSettingNames, ProjectSettingTypes, ProjectSettingTypes>`. Explain that this should just pass through to the PSI. It also needs `resetSetting(key)` which should also pass through to the PSI
- [x] PSI needs a new MandatoryDataTypes type `Setting: DataProviderDataTypes<{ projectId: string, key: ProjectSettingNames }, ProjectSettingTypes, ProjectSettingTypes>`. Explain that the `setSetting` function needs to run `papi.projectSettings.isValid` before accepting the new setting. Explain that the `getSetting` function should return the value for a setting if set and should otherwise run `papi.projectSettings.getDefault` to get the default value if it does not have a value for the setting. Explain that PSI also needs a `resetSetting(projectId, key)` function that deletes the value at the key and sends a setting update event
- [x] Create `useProjectSetting(projectDataProviderSource, key, defaultValue)`-ish hook that looks suspiciously similar to `useSetting` from #502. Maybe can just use `useProjectData` internally
- PSI does the actual persisting of project settings

Notes:
- keeping track of provided project settings and defaults is in #721 
- the actual validators for project settings will be dealt with in #511
- the components for editing these project settings will be dealt with in #510

[Settings & State Design Doc](https://docs.google.com/document/d/1dUt4cj1VK1f-xchdynERL-OO9SjDEKU4dVF3KfSRwXc/edit)

### PR DESCRIPTION
**Pull request by tjcouch-sil**
- Hello World TypeScript test PDP - doesn't persist data because PSIE is unimplemented
- Added `projectType` filters to project dialogs
- Handful of bug fixes on PDP apis
- Fixed command-line arguments bug
- Updated from templates to fix swc bug
- Moved mutex map to util library
- Auto-pull dependencies for externals in vite projects

Resolves #509

- - -
This change is [Reviewable](https://reviewable.io/reviews/paranext/paranext-core/769)

### CODE REVIEW

**Review by lyonsil — APPROVED** [review]
> Reviewed 55 of 55 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/769)* status: all files reviewed, 3 unresolved discussions (waiting on @tjcouch-sil)

___
*[`extensions/src/hello-world/src/models/hello-world-project-data-provider-engine.model.ts` line 26 at r1](https://reviewable.io/reviews/paranext/paranext-core/769#-Nr18K-25Uv0-TTDlmDb:-Nr18K-34OzAi5DpEGrC:b-5xmb7v) ([raw file](https://github.com/paranext/paranext-core/blob/f9bc468bd617a841042c570a3c7883caecb9d388/extensions/src/hello-world/src/models/hello-world-project-data-provider-engine.model.ts#L26)):*
> ```XML
> 
>   async setRandomNumber(max: number, newNum: number) {
>     if (newNum === this.numbers[max]) return false;
> ```

I don't understand `max` here, but it's just a test so it doesn't really matter.  I think `max` is really just meant to be any index, but then I don't know why it's called `max` in so many places.
___
*[`src/shared/services/project-lookup.service.test.ts` line 7 at r1](https://reviewable.io/reviews/paranext/paranext-core/769#-Nr1BwiF-o47PHQ4CqkJ:-Nr1BwiGEBHu3V1YELs1:b4j5u9) ([raw file](https://github.com/paranext/paranext-core/blob/f9bc468bd617a841042c570a3c7883caecb9d388/src/shared/services/project-lookup.service.test.ts#L7)):*
> ```XML
> describe('filterProjectsMetadata', () => {
>   test('should return a shallow clone if there are no filters', () => {
>     const projectsMetadata: ProjectMetadata[] = [
> ```

It looks like you use the same `ProjectMetadata[]` repeatedly in each test.  You could just declare it above the tests and save space/reading, but not a big deal.
___
*[`src/shared/services/project-lookup.service.test.ts` line 48 at r1](https://reviewable.io/reviews/paranext/paranext-core/769#-Nr1EG0o5z0W0spUmCv4:-Nr1EG0o5z0W0spUmCv5:b-m1p6zs) ([raw file](https://github.com/paranext/paranext-core/blob/f9bc468bd617a841042c570a3c7883caecb9d388/src/shared/services/project-lookup.service.test.ts#L48)):*
> ```XML
>     expect(filteredMetadata.length).toEqual(1);
> 
>     // Precedence over includeProjectTypes
> ```

I wouldn't technically call this precedence in that one filter option isn't really being favored over another.  Instead it's the case that all filter options have to be met for each item returned.

**Review by tjcouch-sil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/769)* status: 51 of 55 files reviewed, 3 unresolved discussions (waiting on @lyonsil)

___
*[`extensions/src/hello-world/src/models/hello-world-project-data-provider-engine.model.ts` line 26 at r1](https://reviewable.io/reviews/paranext/paranext-core/769#-Nr18K-25Uv0-TTDlmDb:-Nr1K-Re8yX_cEZxYM6T:bf5992c) ([raw file](https://github.com/paranext/paranext-core/blob/f9bc468bd617a841042c570a3c7883caecb9d388/extensions/src/hello-world/src/models/hello-world-project-data-provider-engine.model.ts#L26)):*
<details><summary><i>Previously, lyonsil (Matt Lyons) wrote…</i></summary><blockquote>

I don't understand `max` here, but it's just a test so it doesn't really matter.  I think `max` is really just meant to be any index, but then I don't know why it's called `max` in so many places.
</blockquote></details>

`max` is the max number the random number can be. It's very weird and not immensely sensible indeed. I was struggling to think of anything :joy: I adjusted to make it work more precisely as a max value and added some comments to the `.d.ts` that will hopefully make it a bit more understandable
___
*[`src/shared/services/project-lookup.service.test.ts` line 7 at r1](https://reviewable.io/reviews/paranext/paranext-core/769#-Nr1BwiF-o47PHQ4CqkJ:-Nr1Mkt41_5RNyF9WdpO:b-2jd9zv) ([raw file](https://github.com/paranext/paranext-core/blob/f9bc468bd617a841042c570a3c7883caecb9d388/src/shared/services/project-lookup.service.test.ts#L7)):*
<details><summary><i>Previously, lyonsil (Matt Lyons) wrote…</i></summary><blockquote>

It looks like you use the same `ProjectMetadata[]` repeatedly in each test.  You could just declare it above the tests and save space/reading, but not a big deal.
</blockquote></details>

Oh yeah, I think I just assumed I would change some things as I wrote them, so I put it in each one. But now they're all done, and they're all the same. Changed :)
___
*[`src/shared/services/project-lookup.service.test.ts` line 48 at r1](https://reviewable.io/reviews/paranext/paranext-core/769#-Nr1EG0o5z0W0spUmCv4:-Nr1NZq-73H8vl_DtxP-:bf4jm1g) ([raw file](https://github.com/paranext/paranext-core/blob/f9bc468bd617a841042c570a3c7883caecb9d388/src/shared/services/project-lookup.service.test.ts#L48)):*
<details><summary><i>Previously, lyonsil (Matt Lyons) wrote…</i></summary><blockquote>

I wouldn't technically call this precedence in that one filter option isn't really being favored over another.  Instead it's the case that all filter options have to be met for each item returned.
</blockquote></details>

Gotcha. Adjusted wording!

**Review by tjcouch-sil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/769)* status: 54 of 55 files reviewed, all discussions resolved (waiting on @lyonsil)

___
*[`extensions/src/hello-world/src/models/hello-world-project-data-provider-engine.model.ts` line 26 at r1](https://reviewable.io/reviews/paranext/paranext-core/769#-Nr18K-25Uv0-TTDlmDb:-Nr1fx-a9wFO1kAVqi2k:b-1xlkfo) ([raw file](https://github.com/paranext/paranext-core/blob/f9bc468bd617a841042c570a3c7883caecb9d388/extensions/src/hello-world/src/models/hello-world-project-data-provider-engine.model.ts#L26)):*
<details><summary><i>Previously, lyonsil (Matt Lyons) wrote…</i></summary><blockquote>

Honestly this still is kind of confusing since it's being used both as an index and a maximum value for the data, but it's just code to include as a test temporarily, so it doesn't matter that much.
</blockquote></details>

I'm just going to leave it for now. Agreed that it's not great. Maybe we can change it some day - maybe when we implement the PSI.

**Review by lyonsil — APPROVED** [review]
> Reviewed 1 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/769)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Pull request merged**
