### PR TITLE
Add Shadcn combobox

### PR DESCRIPTION
**Pull request by dewert99**
Works towards #889.

* Changes the type of `ComboBoxProps<T>.onChange` to `(value: T) => void` since `shadcn`'s `Command` doesn't give any extra event information and the users of `ComboBox` never used this information.
* Adds `ComposableTextField` which is similar to `TextField` but can be used inside other `shadcn` components via `asChild`. 
  - `TextField` and `ComboBox` both use `ComposableTextField`.
  
### TODO
`ComboBoxProps.width` doesn't seem to affect the `ComboBox` and `ComboBox.isClearable` hasn't been implemented

### Note
The first commit contains the original `shadcn` components installed with `npx shadcn-ui@latest add  ..`

- - -
This change is [Reviewable](https://reviewable.io/reviews/paranext/paranext-core/934)

### CODE REVIEW

**Review by jolierabideau — COMMENTED** [review]
I wasn't sure if you wanted a review yet or were just getting the PR set up, but I made a few comments. Thanks for working on this!!

> Reviewed 10 of 10 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/934#-:-O-CDrK55X0f4fjP_CpR:bu480xn)* status: all files reviewed, 4 unresolved discussions (waiting on @dewert99)

___
*[`lib/platform-bible-react/src/components/combo-box.component.tsx` line 1 at r1](https://reviewable.io/reviews/paranext/paranext-core/934#-O-Bavcg3CxmYsRXqKA_:-O-Bavcg3CxmYsRXqKAa:b-35z2il) ([raw file](https://github.com/paranext/paranext-core/blob/8a6991228f36139369aa2b4ffb739d4621a11aca/lib/platform-bible-react/src/components/combo-box.component.tsx#L1)):*
> ```XML
> import React, { FocusEventHandler } from 'react';
> ```

Code style comment- usually we import things like hooks from 'react' instead of importing React directly.
___
*[`lib/platform-bible-react/src/components/combo-box.component.tsx` line 50 at r1](https://reviewable.io/reviews/paranext/paranext-core/934#-O-CBD1M-2RVjdbLwcsA:-O-CBD1M-2RVjdbLwcsB:bg84f59) ([raw file](https://github.com/paranext/paranext-core/blob/8a6991228f36139369aa2b4ffb739d4621a11aca/lib/platform-bible-react/src/components/combo-box.component.tsx#L50)):*
> ```XML
>    * options entries.
>    */
>   value: T;
> ```

This should be optional
___
*[`lib/platform-bible-react/src/components/combo-box.component.tsx` line 100 at r1](https://reviewable.io/reviews/paranext/paranext-core/934#-O-CCF1Y4kWEN2_rVj09:-O-CCF1Y4kWEN2_rVj0A:bfs0z7s) ([raw file](https://github.com/paranext/paranext-core/blob/8a6991228f36139369aa2b4ffb739d4621a11aca/lib/platform-bible-react/src/components/combo-box.component.tsx#L100)):*
> ```XML
>         <PopoverTrigger asChild>
>           <CommandInput asChild onValueChange={setTextValue}>
>             <ComposableTextField
> ```

Do we need this? The example I saw on the shadcn site doesn't use this textfield, it uses `CommandInput`
___
*[`lib/platform-bible-react/src/components/text-field.component.tsx` line 60 at r1](https://reviewable.io/reviews/paranext/paranext-core/934#-O-CD-9Z5lO6acYvPGIF:-O-CD-9Z5lO6acYvPGIG:b-sihwcg) ([raw file](https://github.com/paranext/paranext-core/blob/8a6991228f36139369aa2b4ffb739d4621a11aca/lib/platform-bible-react/src/components/text-field.component.tsx#L60)):*
> ```XML
> }
> 
> export const ComposableTextField = React.forwardRef<HTMLInputElement, ComposableTextFieldProps>(
> ```

I'm a little confused by the need for this component.

**Review by dewert99 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/934)* status: all files reviewed, 4 unresolved discussions (waiting on @jolierabideau)

___
*[`lib/platform-bible-react/src/components/combo-box.component.tsx` line 50 at r1](https://reviewable.io/reviews/paranext/paranext-core/934#-O-CBD1M-2RVjdbLwcsA:-O-Dm2QR-AtiSqNFMHdX:b-hcxmkb) ([raw file](https://github.com/paranext/paranext-core/blob/8a6991228f36139369aa2b4ffb739d4621a11aca/lib/platform-bible-react/src/components/combo-box.component.tsx#L50)):*
<details><summary><i>Previously, jolierabideau wrote…</i></summary><blockquote>

This should be optional
</blockquote></details>

What should be the behaviour when it is not passed in?
___
*[`lib/platform-bible-react/src/components/combo-box.component.tsx` line 100 at r1](https://reviewable.io/reviews/paranext/paranext-core/934#-O-CCF1Y4kWEN2_rVj09:-O-DjyG76FdsBmC2axPK:becd6ta) ([raw file](https://github.com/paranext/paranext-core/blob/8a6991228f36139369aa2b4ffb739d4621a11aca/lib/platform-bible-react/src/components/combo-box.component.tsx#L100)):*
<details><summary><i>Previously, jolierabideau wrote…</i></summary><blockquote>

Do we need this? The example I saw on the shadcn site doesn't use this textfield, it uses `CommandInput`
</blockquote></details>

This allows `ComboBox` to share an implementation of things like `label` and `hasError` with `TextField`.

**Review by jolierabideau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/934)* status: all files reviewed, 4 unresolved discussions (waiting on @dewert99)

___
*[`lib/platform-bible-react/src/components/combo-box.component.tsx` line 43 at r1](https://reviewable.io/reviews/paranext/paranext-core/934#-O-Ls5QfCEfxgTAhxbSX:-O-Ls5QfCEfxgTAhxbSY:bb13ox8) ([raw file](https://github.com/paranext/paranext-core/blob/8a6991228f36139369aa2b4ffb739d4621a11aca/lib/platform-bible-react/src/components/combo-box.component.tsx#L43)):*
> ```XML
>   width?: number;
>   /** List of available options for the dropdown menu */
>   options?: readonly T[];
> ```

This should be required
___
*[`lib/platform-bible-react/src/components/combo-box.component.tsx` line 50 at r1](https://reviewable.io/reviews/paranext/paranext-core/934#-O-CBD1M-2RVjdbLwcsA:-O-Lrc2YDliVgZkCx_ST:b-5lwcs) ([raw file](https://github.com/paranext/paranext-core/blob/8a6991228f36139369aa2b4ffb739d4621a11aca/lib/platform-bible-react/src/components/combo-box.component.tsx#L50)):*
<details><summary><i>Previously, dewert99 (David Ewert) wrote…</i></summary><blockquote>

What should be the behaviour when it is not passed in?
</blockquote></details>

If they do not pass a value, then there is no selected value when the combobox is rendered. So the box should display either a placeholder if it's provided or be empty until they select something. 
___
*[`lib/platform-bible-react/src/components/combo-box.component.tsx` line 100 at r1](https://reviewable.io/reviews/paranext/paranext-core/934#-O-CCF1Y4kWEN2_rVj09:-O-LstE37Ud_SAHN1SCY:bv0dre) ([raw file](https://github.com/paranext/paranext-core/blob/8a6991228f36139369aa2b4ffb739d4621a11aca/lib/platform-bible-react/src/components/combo-box.component.tsx#L100)):*
<details><summary><i>Previously, dewert99 (David Ewert) wrote…</i></summary><blockquote>

This allows `ComboBox` to share an implementation of things like `label` and `hasError` with `TextField`.
</blockquote></details>

I see! That is a good idea. But I think we want to match the Shadcn implementation of `Combobox`. Using `CommandList` will get us closer to that with the search bar part of the drop down instead of as the main element. This element is a little different because we are not just switching a wrapper from MUI to Shadcn like the others. You can build this `Combobox` just like the one in the docs.

**Comment by dewert99** [comment]
*[`lib/platform-bible-react/src/components/combo-box.component.tsx` line 100 at r1](https://reviewable.io/reviews/paranext/paranext-core/934#-O-CCF1Y4kWEN2_rVj09:-O-qsZdg790RGJz72Q1v:bhcyi7q) ([raw file](https://github.com/paranext/paranext-core/blob/8a6991228f36139369aa2b4ffb739d4621a11aca/lib/platform-bible-react/src/components/combo-box.component.tsx#L100)):*
<details><summary><i>Previously, jolierabideau wrote…</i></summary><blockquote>

I see! That is a good idea. But I think we want to match the Shadcn implementation of `Combobox`. Using `CommandList` will get us closer to that with the search bar part of the drop down instead of as the main element. This element is a little different because we are not just switching a wrapper from MUI to Shadcn like the others. You can build this `Combobox` just like the one in the docs.
</blockquote></details>

If we're not just trying to copy MUI, I'm less sure about how to use the `title` and `hasError` properties

**Comment by jolierabideau** [comment]
@dewert99 
> If we're not just trying to copy MUI, I'm less sure about how to use the `title` and `hasError` properties

Sorry for the late reply on this. When we created these wrappers we based the props on the MUI components so some of them are pretty specific and we don't need to re-implement them. Shadcn doesn't have a `Combobox` component that we can install and use, they show you an example of how to build a `Combobox` with two of their other components, so we really just need to copy their implementation and test it. Once you start to build it following the Shadcn example, you will probably notice things that people will want to customize that could become props. Off the top of my head I see: `options` (frameworks in example), `variant`, `className`, `placeholder`, `isOpen`, `handleOpen`, etc. 

There has been some on-going discussion on the team about how we should implement Shadcn, and if we need wrappers, you may have seen some of those conversations in Discord. The ultimate decision is that we are not moving forward with wrappers. So the `Combobox` is an excellent component for you to work on because Shadcn doesn't provide one, and we will need it. After that would be `IconButton`, because Shadcn doesn't provide an easy to copy one of those. The rest of the components listed at the top of issue #889, we do not need you to convert (I will edit the issue to reflect this).

**Pull request closed without merging**
