### PR TITLE
preview app: add non-text tab trigger

### PR DESCRIPTION
**Pull request by Sebastian-ubs**
This change is [Reviewable](https://reviewable.io/reviews/paranext/paranext-core/926)

### CODE REVIEW

**Review by jolierabideau — COMMENTED** [review]
Just curious, I see the phrase `youShouldNotSeeThis` but I do see Tab 2 and "Tab 2 Content" when I run the preview?

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/926#-:-Nzc_bz45n-lht3ZVPOL:b-op7fxz)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Review by Sebastian-ubs — COMMENTED** [review]
Thanks for asking. What I mean is "you should not see the text >youShouldNotSeeThis< in the Ui", otherwise the value is displayed instead of the inner html of the tab trigger component. How can I make this more clear?

> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/926#-:-Nzcf2b9-UqAA5f92wSC:b-y00uti)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Review by jolierabideau — APPROVED** [review]
Oh I see, I'm not sure how it could be more clear, `youShouldOnlySeeTwo`?  I would only expect to see the child text for those fields, not the value so that is why I was confused.

> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/926#-:-NzdEXjX8hZXiTEZSStP:bpki5m7)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Comment by Sebastian-ubs** [comment]
Thanks Jolie. Yes. with previous implementation some had only seen the values, that's why I added this as kind of a test, but maybe not that important if people anyhow do not expect the value to show up.
With the automerge on it was now already merged. So I would not change it for now.

**Pull request merged**
