### PR TITLE
Added scroll group service, hook to use scroll groups, added to web views, added tab nav bar with simple UI

### LINKED ISSUE #940: Hook up Scroll Group UI to make it work in the editor
**User Story**
As a user, I want to have different tabs scroll together at different references so that I can view different texts at different places in Scripture for things like Parallel Passages or cross references.

**Description**
Implement the functionality side following the UX Scroll Group Design at https://paratext.myjetbrains.com/youtrack/issue/BUX-17.

Make this work with the editor as a starting point. It is assumed that the mechanism determined would work with other extensions.

Making scroll groups work with other applications running in the OS at the same time is out of scope for this ticket.

One possible implementation:
- [x] Add scr ref service - data provider (maybe need local synchronous events too; not sure) that keeps track of scroll groups and scr refs
  - Note: I ended up not taking the time to make this a data provider. Instead, I made `getScrRef` and `setScrRef` as if they could be data provider methods and made `onDidUpdateScrRef` to go with them. This fit my needs better this time. I think, once we open the data provider event up to listeners, we could rework this without much of a problem as a data provider
- [x] Add `scrollGroupScrRef` to web view definition updatable properties
  - [x] Use this property in the tab nav BCV control and scroll group control. Subscribe to the changes
- [x] Add a new hook modeled after `useWebViewState` `useScrRefScrollGroup(): [scrRef, setScrRef, scrollGroup, setScrollGroup]`?
- [x] Set up local event announcing updates to updatable properties, listen in the web view added code to rerender

### PR DESCRIPTION
**Pull request by tjcouch-sil**
Resolves #940, #1055, #1000 combined with the following PRs:

[Updated to use scroll groups by tjcouch-sil · Pull Request #30 · paranext/paratext-bible-extensions](https://github.com/paranext/paratext-bible-extensions/pull/30)
[Updated to use scroll groups by tjcouch-sil · Pull Request #8 · paranext/platform-bible-sample-extensions](https://github.com/paranext/platform-bible-sample-extensions/pull/8)

image

- - -
This change is [Reviewable](https://reviewable.io/reviews/paranext/paranext-core/1096)

### CODE REVIEW

**Review by lyonsil — APPROVED** [review]
Looks good overall. I have a few questions/comments but nothing blocking.

> Reviewed 37 of 37 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/1096#-:-O5ULprNAMkid6ugEQXg:bg88ipk)* status: all files reviewed, 7 unresolved discussions (waiting on @tjcouch-sil)

___
*[`src/extension-host/services/papi-backend.service.ts` line 108 at r1](https://reviewable.io/reviews/paranext/paranext-core/1096#-O5U4f3z-1sv1sYqmhP5:-O5U4f3z-1sv1sYqmhP6:bi7kjsh) ([raw file](https://github.com/paranext/paranext-core/blob/e636c40c66b9669b2134145b58decc045c2e3a00/src/extension-host/services/papi-backend.service.ts#L108)):*
> ```XML
>   menuData: menuDataService as IMenuDataService,
>   /** JSDOC DESTINATION scrollGroupService */
>   scrollGroups: scrollGroupService as IScrollGroupService,
> ```

Just curious - what do you envision the back end doing with scroll groups?
___
*[`src/renderer/global-this.model.ts` line 3 at r1](https://reviewable.io/reviews/paranext/paranext-core/1096#-O5TuJU95dWRQ3ut6LBG:-O5TuJU95dWRQ3ut6LBH:b-xt1fp2) ([raw file](https://github.com/paranext/paranext-core/blob/e636c40c66b9669b2134145b58decc045c2e3a00/src/renderer/global-this.model.ts#L3)):*
> ```XML
> /** Module to set up globalThis and polyfills in the renderer */
> 
> import ReactModule from 'react';
> ```

What does this do for us vs. just `React`? All the examples and code I've seen use `React`, not `ReactModule`.
___
*[`src/renderer/components/settings-tabs/settings-components/setting.component.tsx` line 112 at r1](https://reviewable.io/reviews/paranext/paranext-core/1096#-O5U1uCZ941wZitiAARb:-O5U1uCZ941wZitiAARc:b-wmjhvm) ([raw file](https://github.com/paranext/paranext-core/blob/e636c40c66b9669b2134145b58decc045c2e3a00/src/renderer/components/settings-tabs/settings-components/setting.component.tsx#L112)):*
> ```XML
> 
>   const handleChangeSetting = async (event: ChangeEvent<HTMLInputElement>) => {
>     let newValue: unknown;
> ```

Was this intentional? It looks unrelated to the rest of this PR.
___
*[`src/renderer/hooks/papi-hooks/use-scroll-group-scr-ref.hook.ts` line 61 at r1](https://reviewable.io/reviews/paranext/paranext-core/1096#-O5U2b6I8CT3tfEOlea_:-O5U2b6I8CT3tfEOleaa:b18f149) ([raw file](https://github.com/paranext/paranext-core/blob/e636c40c66b9669b2134145b58decc045c2e3a00/src/renderer/hooks/papi-hooks/use-scroll-group-scr-ref.hook.ts#L61)):*
> ```XML
> 
>   // Use setScrollGroupScrRef as a ref so it doesn't update dependency arrays
>   const setScrollGroupScrRefRef = useRef(setScrollGroupScrRef);
> ```

:zebra: :zebra: 
___
*[`src/renderer/hooks/papi-hooks/use-scroll-group-scr-ref.hook.ts` line 65 at r1](https://reviewable.io/reviews/paranext/paranext-core/1096#-O5UHyvH2RmhyIyP_4Vu:-O5UHyvH2RmhyIyP_4Vv:b1zs0c6) ([raw file](https://github.com/paranext/paranext-core/blob/e636c40c66b9669b2134145b58decc045c2e3a00/src/renderer/hooks/papi-hooks/use-scroll-group-scr-ref.hook.ts#L65)):*
> ```XML
> 
>   const scrollGroupRef = useRef(extractScrollGroup(scrollGroupScrRefDefaulted));
>   const [scrollGroup, setScrollGroupLocal] = useState(scrollGroupRef.current);
> ```

Just curious, why not `[scrollGroupLocal, setScrollGroupLocal]` for consistency?
___
*[`src/renderer/hooks/papi-hooks/use-scroll-group-scr-ref.hook.ts` line 113 at r1](https://reviewable.io/reviews/paranext/paranext-core/1096#-O5UL8paEfaRRyCIwhnZ:-O5UL8pbEJuqvcO-IbJe:b89ijia) ([raw file](https://github.com/paranext/paranext-core/blob/e636c40c66b9669b2134145b58decc045c2e3a00/src/renderer/hooks/papi-hooks/use-scroll-group-scr-ref.hook.ts#L113)):*
> ```XML
> 
>   // Change the scroll group and update ours if successful
>   const setScrollGroup = useCallback(
> ```

It's hard for me to work this all through in my head, but I'm assuming that if the scroll group changes, that will then cause `scrRefLocal` to change when the next render cycle happens, right?
___
*[`src/renderer/services/scroll-group.service-host.ts` line 64 at r1](https://reviewable.io/reviews/paranext/paranext-core/1096#-O5UDLH26S8k1sXydjwH:-O5UDLH26S8k1sXydjwI:b-h8j471) ([raw file](https://github.com/paranext/paranext-core/blob/e636c40c66b9669b2134145b58decc045c2e3a00/src/renderer/services/scroll-group.service-host.ts#L64)):*
> ```XML
>  */
> export function setScrRefSync(
>   newScrollGroup: ScrollGroup | undefined,
> ```

Nit picky, but since this param wasn't in the docs I had to read the code to figure out why it was called `new`. Arguably I would think both parameters should drop `new`, but the first one more significantly. It's not that big of a deal, though.
___
*[`src/shared/services/scroll-group.service-model.ts` line 24 at r1](https://reviewable.io/reviews/paranext/paranext-core/1096#-O5U5l425NeLMWp5sGU7:-O5U5l425NeLMWp5sGU8:b-b6kntb) ([raw file](https://github.com/paranext/paranext-core/blob/e636c40c66b9669b2134145b58decc045c2e3a00/src/shared/services/scroll-group.service-model.ts#L24)):*
> ```XML
>  * These are generally expected to be non-negative numbers (starting at 0).
>  */
> export type ScrollGroup = number;
> ```

Kind of nit picky, but this is more of a ScrollGroupId than a ScrollGroup, right?

**Review by lyonsil — DISMISSED** [review]
Thanks for the updates

> Reviewed 7 of 7 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/1096#-:-O5UwZq-3LAzJDUZACUD:b-vsu5ri)* status: all files reviewed, 4 unresolved discussions (waiting on @tjcouch-sil)

**Review by tjcouch-sil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/1096)* status: all files reviewed, 4 unresolved discussions (waiting on @lyonsil)

___
*[`src/extension-host/services/papi-backend.service.ts` line 108 at r1](https://reviewable.io/reviews/paranext/paranext-core/1096#-O5U4f3z-1sv1sYqmhP5:-O5UM87A9eUXJP3pMJnJ:bnj2lmb) ([raw file](https://github.com/paranext/paranext-core/blob/e636c40c66b9669b2134145b58decc045c2e3a00/src/extension-host/services/papi-backend.service.ts#L108)):*
<details><summary><i>Previously, lyonsil (Matt Lyons) wrote…</i></summary><blockquote>

Just curious - what do you envision the back end doing with scroll groups?
</blockquote></details>

The scroll group service manages scripture references, and I expect the backend to want to edit the scripture references at times. For example, the Psalms LBL extension updates the scripture reference iirc :)

Or maybe someone wants to build an extension that connects the scroll group/scr refs between P.B and P9 or Logos or something. That would also probably go in the backend :)
___
*[`src/renderer/global-this.model.ts` line 3 at r1](https://reviewable.io/reviews/paranext/paranext-core/1096#-O5TuJU95dWRQ3ut6LBG:-O5UMXGDBsPraInj5E39:b-jv3s87) ([raw file](https://github.com/paranext/paranext-core/blob/e636c40c66b9669b2134145b58decc045c2e3a00/src/renderer/global-this.model.ts#L3)):*
<details><summary><i>Previously, lyonsil (Matt Lyons) wrote…</i></summary><blockquote>

What does this do for us vs. just `React`? All the examples and code I've seen use `React`, not `ReactModule`.
</blockquote></details>

I think TS sees `React` as kinda globally available kinda like `jest` in the jest tests. But I don't really know much about how that works and suspect that it doesn't really work in most cases, so we're importing here. But TS complained that we were making a new variable with the same name as an existing one (`React`), so I renamed it.

I wouldn't have touched this if it weren't that it was showing an error that I wanted to get rid of. :)
___
*[`src/renderer/components/settings-tabs/settings-components/setting.component.tsx` line 112 at r1](https://reviewable.io/reviews/paranext/paranext-core/1096#-O5U1uCZ941wZitiAARb:-O5UMr7VEpiwI7sx-S6i:b-o6tuoa) ([raw file](https://github.com/paranext/paranext-core/blob/e636c40c66b9669b2134145b58decc045c2e3a00/src/renderer/components/settings-tabs/settings-components/setting.component.tsx#L112)):*
<details><summary><i>Previously, lyonsil (Matt Lyons) wrote…</i></summary><blockquote>

Was this intentional? It looks unrelated to the rest of this PR.
</blockquote></details>

Yeah, this was erring on me. Jolie and I had some discussions around this stuff a week ago or something. I don't know why it wasn't erring for her, but this change is pretty much in line with the other changes we made to fix the other type errors she was seeing.
___
*[`src/renderer/hooks/papi-hooks/use-scroll-group-scr-ref.hook.ts` line 61 at r1](https://reviewable.io/reviews/paranext/paranext-core/1096#-O5U2b6I8CT3tfEOlea_:-O5UN0ZpD8LSSOz7hBE9:bqhn2wa) ([raw file](https://github.com/paranext/paranext-core/blob/e636c40c66b9669b2134145b58decc045c2e3a00/src/renderer/hooks/papi-hooks/use-scroll-group-scr-ref.hook.ts#L61)):*
<details><summary><i>Previously, lyonsil (Matt Lyons) wrote…</i></summary><blockquote>

:zebra: :zebra:
</blockquote></details>

Indeed :joy:
___
*[`src/renderer/hooks/papi-hooks/use-scroll-group-scr-ref.hook.ts` line 65 at r1](https://reviewable.io/reviews/paranext/paranext-core/1096#-O5UHyvH2RmhyIyP_4Vu:-O5UNNSrBvgxms24BZq6:b-blamm) ([raw file](https://github.com/paranext/paranext-core/blob/e636c40c66b9669b2134145b58decc045c2e3a00/src/renderer/hooks/papi-hooks/use-scroll-group-scr-ref.hook.ts#L65)):*
<details><summary><i>Previously, lyonsil (Matt Lyons) wrote…</i></summary><blockquote>

Just curious, why not `[scrollGroupLocal, setScrollGroupLocal]` for consistency?
</blockquote></details>

I'mma be honest with you: I have no idea. Changed.
___
*[`src/renderer/hooks/papi-hooks/use-scroll-group-scr-ref.hook.ts` line 113 at r1](https://reviewable.io/reviews/paranext/paranext-core/1096#-O5UL8paEfaRRyCIwhnZ:-O5UNYMI1n_E-sy2N9qn:b-cddysm) ([raw file](https://github.com/paranext/paranext-core/blob/e636c40c66b9669b2134145b58decc045c2e3a00/src/renderer/hooks/papi-hooks/use-scroll-group-scr-ref.hook.ts#L113)):*
<details><summary><i>Previously, lyonsil (Matt Lyons) wrote…</i></summary><blockquote>

It's hard for me to work this all through in my head, but I'm assuming that if the scroll group changes, that will then cause `scrRefLocal` to change when the next render cycle happens, right?
</blockquote></details>

Yep. The `useEffect` handles updating `scrollGroupLocal` and `scrRefLocal` when changes come in from the `scrollGroupScrRef` parameter.
___
*[`src/renderer/services/scroll-group.service-host.ts` line 64 at r1](https://reviewable.io/reviews/paranext/paranext-core/1096#-O5UDLH26S8k1sXydjwH:-O5UO-Tp0gk0BYmA0o6U:b-g0n8gk) ([raw file](https://github.com/paranext/paranext-core/blob/e636c40c66b9669b2134145b58decc045c2e3a00/src/renderer/services/scroll-group.service-host.ts#L64)):*
<details><summary><i>Previously, lyonsil (Matt Lyons) wrote…</i></summary><blockquote>

Nit picky, but since this param wasn't in the docs I had to read the code to figure out why it was called `new`. Arguably I would think both parameters should drop `new`, but the first one more significantly. It's not that big of a deal, though.
</blockquote></details>

Good point. I just called them `new` because I had already written the code as if they were `scrollGroup` and `scrRef` then refactored some stuff later and got lazy about names. Refactored.
___
*[`src/shared/services/scroll-group.service-model.ts` line 24 at r1](https://reviewable.io/reviews/paranext/paranext-core/1096#-O5U5l425NeLMWp5sGU7:-O5UO9ZJ4bWqSRWiPrHw:brhd6eo) ([raw file](https://github.com/paranext/paranext-core/blob/e636c40c66b9669b2134145b58decc045c2e3a00/src/shared/services/scroll-group.service-model.ts#L24)):*
<details><summary><i>Previously, lyonsil (Matt Lyons) wrote…</i></summary><blockquote>

Kind of nit picky, but this is more of a ScrollGroupId than a ScrollGroup, right?
</blockquote></details>

I'll change it.

**Review by lyonsil — DISMISSED** [review]
> Reviewed 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/1096)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

___
*[`src/extension-host/services/papi-backend.service.ts` line 108 at r1](https://reviewable.io/reviews/paranext/paranext-core/1096#-O5U4f3z-1sv1sYqmhP5:-O5Uxr2q8vG4pgSeybqi:b4c9lyr) ([raw file](https://github.com/paranext/paranext-core/blob/e636c40c66b9669b2134145b58decc045c2e3a00/src/extension-host/services/papi-backend.service.ts#L108)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

The scroll group service manages scripture references, and I expect the backend to want to edit the scripture references at times. For example, the Psalms LBL extension updates the scripture reference iirc :)

Or maybe someone wants to build an extension that connects the scroll group/scr refs between P.B and P9 or Logos or something. That would also probably go in the backend :)
</blockquote></details>

:thumbsup:

**Review by lyonsil — APPROVED** [review]
> Reviewed 30 of 30 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/1096)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Pull request merged**
