### PR TITLE
Added project settings service and `useProjectSetting` hook

### PR DESCRIPTION
**Pull request by tjcouch-sil**
- Renamed `MandatoryProjectDataType` to `MandatoryProjectDataTypes` (Breaking change)
- Project settings service has `isValid` and `getDefault` for PSIs to call when interacting with project settings
- Added types for a lot of things related to PDPs and PSIs
- Created default implementation `IProjectDataProviderEngine` abstract class that PDPEs can extend
- Added documentation about new project setting requirements for PDPs and improved documentation about `ExtensionData` requirements
- Note: we currently don't have the infrastructure for any of this to be used in TypeScript *\*gulp\** I guess we will use it in C# in #723.
- Added `@link`s to a lot of JSDocs for easier navigation
- Fixed a lot of small inconsistencies and problems in various JSDocs

- - -
This change is [Reviewable](https://reviewable.io/reviews/paranext/paranext-core/758)

### CODE REVIEW

**Review by lyonsil — CHANGES_REQUESTED** [review]
I think this makes sense overall.  I have a few questions/comments.

> Reviewed 31 of 31 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/758#-:-NqU2mPSAdxBnSj6k7PS:bhdw8om)* status: all files reviewed, 7 unresolved discussions (waiting on @tjcouch-sil)

___
*[`src/main/data/core-project-settings-info.data.ts` line 22 at r1](https://reviewable.io/reviews/paranext/paranext-core/758#-NqTe9i49MxqGQmcfg98:-NqTe9i49MxqGQmcfg99:b-2c97ib) ([raw file](https://github.com/paranext/paranext-core/blob/1b7d2e897e74c9d374ec238a2fa06120153bdc08/src/main/data/core-project-settings-info.data.ts#L22)):*
> ```XML
>   'platformScripture.booksPresent': {
>     default:
>       '000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000',
> ```

This seems like it should be something like:
```typescript
'0'.repeat(123);
```

If you want it to be a fixed string, then I would suggest we do something like the following to make it obvious how many characters are in the string:
```
//                                                                                                 1
//       1         2         3         4         5         6         7         8         9         0         1         2         3
// 4567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890
000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
```
___
*[`src/main/services/project-settings.service-host.ts` line 64 at r1](https://reviewable.io/reviews/paranext/paranext-core/758#-NqTrlj-5qbKda_vPGIl:-NqTrlj-5qbKda_vPGIm:b-yr96bk) ([raw file](https://github.com/paranext/paranext-core/blob/1b7d2e897e74c9d374ec238a2fa06120153bdc08/src/main/services/project-settings.service-host.ts#L64)):*
> ```XML
> 
> /** This is an internal-only export for testing purposes, and should not be used in development */
> export const testingProjectSettingsService = {
> ```

Why can't this just live in the `test.ts` file?
___
*[`src/main/services/project-settings.service-host.test.ts` line 16 at r1](https://reviewable.io/reviews/paranext/paranext-core/758#-NqTsWzkBqOdqsiYy6GS:-NqTsWzkBqOdqsiYy6GT:b-nw5lho) ([raw file](https://github.com/paranext/paranext-core/blob/1b7d2e897e74c9d374ec238a2fa06120153bdc08/src/main/services/project-settings.service-host.test.ts#L16)):*
> ```XML
> 
> describe('isValid', () => {
>   it('should return true always', async () => {
> ```

I'm not sure if it makes sense to add a test for something that is currently just stubbed out.  If we're going to put this here, I would expect something to call out that the test needs to change when real validity checking is added.
___
*[`src/shared/models/data-provider-engine.model.ts` line 152 at r1](https://reviewable.io/reviews/paranext/paranext-core/758#-NqTujl71z_y9mRbLjM7:-NqTujl71z_y9mRbLjM8:btjch8v) ([raw file](https://github.com/paranext/paranext-core/blob/1b7d2e897e74c9d374ec238a2fa06120153bdc08/src/shared/models/data-provider-engine.model.ts#L152)):*
> ```XML
>   // This is just a placeholder and will be layered over by papi. We don't need it to do anything
>   // eslint-disable-next-line class-methods-use-this, @typescript-eslint/no-unused-vars
>   notifyUpdate: DataProviderEngineNotifyUpdate<TDataTypes> = (_updateInstructions) => {};
> ```

This might just be me, but using `class` syntax mixed with "lower level" JS/TS property-based syntax for functions doesn't feel normal.  I would normally expect classes to use syntax like:
```typescript
notifyUpdate(_updateInstructions): DataProviderEngineNotifyUpdate<TDataTypes> {}
```

This might only be me.
___
*[`src/shared/models/project-data-provider-engine.model.ts` line 144 at r1](https://reviewable.io/reviews/paranext/paranext-core/758#-NqU1ojv2th5VqTm5dKw:-NqU1ojv2th5VqTm5dKx:b-lp7gdx) ([raw file](https://github.com/paranext/paranext-core/blob/1b7d2e897e74c9d374ec238a2fa06120153bdc08/src/shared/models/project-data-provider-engine.model.ts#L144)):*
> ```XML
>     // our own subscribers
>     this.psiSettingUnsubscriberPromise = this.projectStorageInterpreter.subscribeSetting(
>       // Just picked a key for no reason in particular because we don't need anything in particular
> ```

It doesn't seem right that you have to provide real data that you actually don't care about.  What's the point of giving a setting to subscribe to if you are always going to be called back on all settings?
___
*[`src/shared/models/project-data-provider.model.ts` line 66 at r1](https://reviewable.io/reviews/paranext/paranext-core/758#-NqTyVgq80vKNG7XMB-c:-NqTyVgq80vKNG7XMB-d:b-2f0xep) ([raw file](https://github.com/paranext/paranext-core/blob/1b7d2e897e74c9d374ec238a2fa06120153bdc08/src/shared/models/project-data-provider.model.ts#L66)):*
> ```XML
>  */
> export type MandatoryProjectDataTypes = {
>   /* Setting: DataProviderDataType<
> ```

This shouldn't be commented out, should it?
___
*[`src/shared/models/project-storage-interpreter.model.ts` line 116 at r1](https://reviewable.io/reviews/paranext/paranext-core/758#-NqTzrnp9eWtn0qBuUik:-NqTzrnp9eWtn0qBuUil:b7orp7g) ([raw file](https://github.com/paranext/paranext-core/blob/1b7d2e897e74c9d374ec238a2fa06120153bdc08/src/shared/models/project-storage-interpreter.model.ts#L116)):*
> ```XML
>  */
> export type MandatoryProjectStorageDataTypes = {
>   /* Setting: DataProviderDataType<
> ```

Why is this commented out?

**Review by tjcouch-sil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/758)* status: 26 of 31 files reviewed, 6 unresolved discussions (waiting on @lyonsil)

___
*[`src/main/data/core-project-settings-info.data.ts` line 22 at r1](https://reviewable.io/reviews/paranext/paranext-core/758#-NqTe9i49MxqGQmcfg98:-NqZid6t18bDbW5x7jiA:b-ntbqzl) ([raw file](https://github.com/paranext/paranext-core/blob/1b7d2e897e74c9d374ec238a2fa06120153bdc08/src/main/data/core-project-settings-info.data.ts#L22)):*
<details><summary><i>Previously, lyonsil (Matt Lyons) wrote…</i></summary><blockquote>

This seems like it should be something like:
```typescript
'0'.repeat(123);
```

If you want it to be a fixed string, then I would suggest we do something like the following to make it obvious how many characters are in the string:
```
//                                                                                                 1
//       1         2         3         4         5         6         7         8         9         0         1         2         3
// 4567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890
000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
```
</blockquote></details>

Done. I was going to do the repeat, but then I realized this will possibly go into an actual JSON file at some point. Which ironically also doesn't support comments... Ugh I didn't think of that. Oh well. It's done haha
___
*[`src/main/services/project-settings.service-host.ts` line 64 at r1](https://reviewable.io/reviews/paranext/paranext-core/758#-NqTrlj-5qbKda_vPGIl:-NqZjOcU0Q8kli4AKz-F:bchqibw) ([raw file](https://github.com/paranext/paranext-core/blob/1b7d2e897e74c9d374ec238a2fa06120153bdc08/src/main/services/project-settings.service-host.ts#L64)):*
<details><summary><i>Previously, lyonsil (Matt Lyons) wrote…</i></summary><blockquote>

Why can't this just live in the `test.ts` file?
</blockquote></details>

`projectSettingsService` and its methods are not exported, and I don't want to export them just to test them; they are intended to be accessed via network object service. However, we don't currently have the infrastructure running to mock all that out. Soooooo this is the temporary solution I gave to Rolf and Jolie and am using myself :) make a testing export that is clearly labeled to (hopefully) avoid getting imported elsewhere. 
___
*[`src/main/services/project-settings.service-host.test.ts` line 16 at r1](https://reviewable.io/reviews/paranext/paranext-core/758#-NqTsWzkBqOdqsiYy6GS:-NqZk52x5M0093bwYhVB:benzh5u) ([raw file](https://github.com/paranext/paranext-core/blob/1b7d2e897e74c9d374ec238a2fa06120153bdc08/src/main/services/project-settings.service-host.test.ts#L16)):*
<details><summary><i>Previously, lyonsil (Matt Lyons) wrote…</i></summary><blockquote>

I'm not sure if it makes sense to add a test for something that is currently just stubbed out.  If we're going to put this here, I would expect something to call out that the test needs to change when real validity checking is added.
</blockquote></details>

Mentioned this in the test name. I put this test here somewhat to make sure whoever does #511 implements more useful tests for this :)
___
*[`src/shared/models/data-provider-engine.model.ts` line 152 at r1](https://reviewable.io/reviews/paranext/paranext-core/758#-NqTujl71z_y9mRbLjM7:-Nqc63b59fCmKQYS6UZa:b-rlw275) ([raw file](https://github.com/paranext/paranext-core/blob/1b7d2e897e74c9d374ec238a2fa06120153bdc08/src/shared/models/data-provider-engine.model.ts#L152)):*
<details><summary><i>Previously, lyonsil (Matt Lyons) wrote…</i></summary><blockquote>

This might just be me, but using `class` syntax mixed with "lower level" JS/TS property-based syntax for functions doesn't feel normal.  I would normally expect classes to use syntax like:
```typescript
notifyUpdate(_updateInstructions): DataProviderEngineNotifyUpdate<TDataTypes> {}
```

This might only be me.
</blockquote></details>

Unfortunately they are actually two slightly different things. Main reason I did it this way is so I could specify the function type as `DataProviderEngineNotifyUpdate`, which is unfortunately not possible with function syntax and specifying methods. For ease of visualization, I went ahead and changed it, though. Either way will work for me.

Also note I just moved this code; it's not new :)
___
*[`src/shared/models/project-data-provider-engine.model.ts` line 144 at r1](https://reviewable.io/reviews/paranext/paranext-core/758#-NqU1ojv2th5VqTm5dKw:-Nqc6VDB8yBe4NXRE_vD:b-mv65ny) ([raw file](https://github.com/paranext/paranext-core/blob/1b7d2e897e74c9d374ec238a2fa06120153bdc08/src/shared/models/project-data-provider-engine.model.ts#L144)):*
<details><summary><i>Previously, lyonsil (Matt Lyons) wrote…</i></summary><blockquote>

It doesn't seem right that you have to provide real data that you actually don't care about.  What's the point of giving a setting to subscribe to if you are always going to be called back on all settings?
</blockquote></details>

I thought about modifying the PSI data type a bit to support this case a bit better (like getting no setting or all settings at once or something like that), but I realized I dunno if I really want to add extra complexity to what is probably already a difficult enough interface to follow.

I do have some thoughts on routes we could take here. Would be good to discuss as part of our conversation about making PSI factories a thing. There's already a note on our discussion doc, so I'll add a link to this as a reminder of this related topic.
___
*[`src/shared/models/project-data-provider.model.ts` line 66 at r1](https://reviewable.io/reviews/paranext/paranext-core/758#-NqTyVgq80vKNG7XMB-c:-NqcICqe0oRTCFSAKYYw:barw2tr) ([raw file](https://github.com/paranext/paranext-core/blob/1b7d2e897e74c9d374ec238a2fa06120153bdc08/src/shared/models/project-data-provider.model.ts#L66)):*
<details><summary><i>Previously, lyonsil (Matt Lyons) wrote…</i></summary><blockquote>

This shouldn't be commented out, should it?
</blockquote></details>

From the JSDoc:

```typescript
/**
 * ...
 * Note: the `Setting` data type is not actually part of {@link MandatoryProjectDataTypes} because
 * the methods would not be able to create a generic type extending from `ProjectSettingNames` in
 * order to return the specific setting type being requested. As such, `getSetting`, `setSetting`,
 * and `subscribeSetting` are all specified on {@link IProjectDataProvider} instead. Unfortunately,
 * as a result, using Intellisense with `useProjectData` will not show `Setting` as a data type
 * option, but you can use `useProjectSetting` instead. However, do note that the `Setting` data
 * type is fully functional.
 * ...
 */
```

Would be glad to discuss on our call.
___
*[`src/shared/models/project-storage-interpreter.model.ts` line 116 at r1](https://reviewable.io/reviews/paranext/paranext-core/758#-NqTzrnp9eWtn0qBuUik:-NqcIQ9H8FYqfjRh5Jbz:bl6p9wy) ([raw file](https://github.com/paranext/paranext-core/blob/1b7d2e897e74c9d374ec238a2fa06120153bdc08/src/shared/models/project-storage-interpreter.model.ts#L116)):*
<details><summary><i>Previously, lyonsil (Matt Lyons) wrote…</i></summary><blockquote>

Why is this commented out?
</blockquote></details>

See other comment :)

**Review by lyonsil — COMMENTED** [review]
> Reviewed 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/758)* status: all files reviewed, 2 unresolved discussions

___
*[`src/main/services/project-settings.service-host.ts` line 64 at r1](https://reviewable.io/reviews/paranext/paranext-core/758#-NqTrlj-5qbKda_vPGIl:-NqcZSGT2R7c47VxSHIc:bx923eg) ([raw file](https://github.com/paranext/paranext-core/blob/1b7d2e897e74c9d374ec238a2fa06120153bdc08/src/main/services/project-settings.service-host.ts#L64)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

`projectSettingsService` and its methods are not exported, and I don't want to export them just to test them; they are intended to be accessed via network object service. However, we don't currently have the infrastructure running to mock all that out. Soooooo this is the temporary solution I gave to Rolf and Jolie and am using myself :) make a testing export that is clearly labeled to (hopefully) avoid getting imported elsewhere.
</blockquote></details>

Ok - I'm resolving this but tagging @ira_hopkinson@sil.org in case he has other ideas.
___
*[`src/shared/models/data-provider-engine.model.ts` line 152 at r1](https://reviewable.io/reviews/paranext/paranext-core/758#-NqTujl71z_y9mRbLjM7:-Nqc_wsN3NYiczvrzp79:b3jfkkj) ([raw file](https://github.com/paranext/paranext-core/blob/1b7d2e897e74c9d374ec238a2fa06120153bdc08/src/shared/models/data-provider-engine.model.ts#L152)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

Unfortunately they are actually two slightly different things. Main reason I did it this way is so I could specify the function type as `DataProviderEngineNotifyUpdate`, which is unfortunately not possible with function syntax and specifying methods. For ease of visualization, I went ahead and changed it, though. Either way will work for me.

Also note I just moved this code; it's not new :)
</blockquote></details>

Got it - thanks for the change!

**Review by lyonsil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/758)* status: all files reviewed, 3 unresolved discussions (waiting on @tjcouch-sil)

___
*[`src/main/data/core-project-settings-info.data.ts` line 27 at r2](https://reviewable.io/reviews/paranext/paranext-core/758#-NqcasiF1wE6RDhPlDCQ:-NqcasiF1wE6RDhPlDCR:bebeh0d) ([raw file](https://github.com/paranext/paranext-core/blob/3d0dc41865cb2c0bfe341854fbc700bc04c2cf58/src/main/data/core-project-settings-info.data.ts#L27)):*
> ```XML
>       '000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000',
>   },
>   'platformScripture.versification': { default: 4 },
> ```

It would be nice to have a pointer to the meaning `versification` and `booksPresent` values if it is written down anywhere.

**Comment by irahopkinson** [comment]
*[`src/main/services/project-settings.service-host.ts` line 64 at r1](https://reviewable.io/reviews/paranext/paranext-core/758#-NqTrlj-5qbKda_vPGIl:-NqdGF4o91qaC0TXkYz_:bb3um1y) ([raw file](https://github.com/paranext/paranext-core/blob/1b7d2e897e74c9d374ec238a2fa06120153bdc08/src/main/services/project-settings.service-host.ts#L64)):*
<details><summary><i>Previously, lyonsil (Matt Lyons) wrote…</i></summary><blockquote>

Ok - I'm resolving this but tagging @ira_hopkinson@sil.org in case he has other ideas.
</blockquote></details>

This is expediant rather than ideal as TJ points out. It's also better to test than not. I think this is a resonably safe interim step making the export obvious it's for testing-only as we can safely delete them at any time.

**Review by tjcouch-sil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/758)* status: 23 of 32 files reviewed, 3 unresolved discussions (waiting on @lyonsil)

___
*[`src/main/data/core-project-settings-info.data.ts` line 27 at r2](https://reviewable.io/reviews/paranext/paranext-core/758#-NqcasiF1wE6RDhPlDCQ:-NqhMQSa1UqxfmRAON_w:bg86zez) ([raw file](https://github.com/paranext/paranext-core/blob/3d0dc41865cb2c0bfe341854fbc700bc04c2cf58/src/main/data/core-project-settings-info.data.ts#L27)):*
<details><summary><i>Previously, lyonsil (Matt Lyons) wrote…</i></summary><blockquote>

It would be nice to have a pointer to the meaning `versification` and `booksPresent` values if it is written down anywhere.
</blockquote></details>

I asked where such documentation might exist in the Paratext channel and haven't heard yet. I didn't find anything from a quick search in the Paratext source. Hopefully we can add something later when we get more info :)
___
*[`src/shared/models/project-data-provider.model.ts` line 66 at r1](https://reviewable.io/reviews/paranext/paranext-core/758#-NqTyVgq80vKNG7XMB-c:-NqhJZNRAKbpLn9BcdiN:bjmrhbe) ([raw file](https://github.com/paranext/paranext-core/blob/1b7d2e897e74c9d374ec238a2fa06120153bdc08/src/shared/models/project-data-provider.model.ts#L66)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

From the JSDoc:

```typescript
/**
 * ...
 * Note: the `Setting` data type is not actually part of {@link MandatoryProjectDataTypes} because
 * the methods would not be able to create a generic type extending from `ProjectSettingNames` in
 * order to return the specific setting type being requested. As such, `getSetting`, `setSetting`,
 * and `subscribeSetting` are all specified on {@link IProjectDataProvider} instead. Unfortunately,
 * as a result, using Intellisense with `useProjectData` will not show `Setting` as a data type
 * option, but you can use `useProjectSetting` instead. However, do note that the `Setting` data
 * type is fully functional.
 * ...
 */
```

Would be glad to discuss on our call.
</blockquote></details>

Put in JSDoc as we discussed :)
___
*[`src/shared/models/project-storage-interpreter.model.ts` line 116 at r1](https://reviewable.io/reviews/paranext/paranext-core/758#-NqTzrnp9eWtn0qBuUik:-NqhJa981YYwPawivgAs:bjmrhbe) ([raw file](https://github.com/paranext/paranext-core/blob/1b7d2e897e74c9d374ec238a2fa06120153bdc08/src/shared/models/project-storage-interpreter.model.ts#L116)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

See other comment :)
</blockquote></details>

Put in JSDoc as we discussed :)

**Review by lyonsil — APPROVED** [review]
> Reviewed 10 of 10 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/758)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

___
*[`src/main/data/core-project-settings-info.data.ts` line 27 at r2](https://reviewable.io/reviews/paranext/paranext-core/758#-NqcasiF1wE6RDhPlDCQ:-NqhjoNV1p9EuQN3-593:brxp9sd) ([raw file](https://github.com/paranext/paranext-core/blob/3d0dc41865cb2c0bfe341854fbc700bc04c2cf58/src/main/data/core-project-settings-info.data.ts#L27)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

I asked where such documentation might exist in the Paratext channel and haven't heard yet. I didn't find anything from a quick search in the Paratext source. Hopefully we can add something later when we get more info :)
</blockquote></details>

Sounds good!
___
*[`src/shared/models/project-data-provider.model.ts` line 66 at r1](https://reviewable.io/reviews/paranext/paranext-core/758#-NqTyVgq80vKNG7XMB-c:-Nqhj_tQ53wF2Teaqd9Y:b-ucfknh) ([raw file](https://github.com/paranext/paranext-core/blob/1b7d2e897e74c9d374ec238a2fa06120153bdc08/src/shared/models/project-data-provider.model.ts#L66)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

Put in JSDoc as we discussed :)
</blockquote></details>

Thanks!
___
*[`src/shared/models/project-storage-interpreter.model.ts` line 116 at r1](https://reviewable.io/reviews/paranext/paranext-core/758#-NqTzrnp9eWtn0qBuUik:-NqhjdGZ1e7skCpEWnJU:b-ucfknh) ([raw file](https://github.com/paranext/paranext-core/blob/1b7d2e897e74c9d374ec238a2fa06120153bdc08/src/shared/models/project-storage-interpreter.model.ts#L116)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

Put in JSDoc as we discussed :)
</blockquote></details>

Thanks!

**Review by lyonsil — APPROVED** [review]
:lgtm:

Thanks for adding the pointers!

> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/758#-:-Nqhq0At560eMjJ3Yhuf:b-1q0o1y)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Pull request merged**
