### PR TITLE
Added internet settings to Paratext registration info form, fixed disabling internet in sensitive locations

### PR DESCRIPTION
**Pull request by tjcouch-sil**
- Added internet settings to Paratext registration info form
- Fixed `InternetUse.VpnRequired` setting not working properly (now it disables internet only in sensitive locations instead of disabling internet everywhere before)
- Added `formatReplacementStringToArray` for doing replacement strings with React components (and whatever other objects you want, but it's mostly for React components)

- - -
This change is [Reviewable](https://reviewable.io/reviews/paranext/paranext-core/1320)

### CODE REVIEW

**Review by lyonsil — APPROVED** [review]
Looks good overall. I have a few non-blocking questions/suggestions to consider.

> Reviewed 17 of 17 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/1320#-:-OC9cjaw1fVymj4KaPsI:b-ov8avh)* status: all files reviewed, 3 unresolved discussions (waiting on @tjcouch-sil)

___
*[`src/renderer/testing/about-panel.component.tsx` line 66 at r1](https://reviewable.io/reviews/paranext/paranext-core/1320#-OC9dFtv9LB90m93O6W7:-OC9dFtv9LB90m93O6W8:bpols37) ([raw file](https://github.com/paranext/paranext-core/blob/18f30c3568fb2f87e14350fe758abde175d04d83/src/renderer/testing/about-panel.component.tsx#L66)):*
> ```XML
>           })
>             .split('{')
>             .flatMap((attributionPart) => {
> ```

Does this belong as a utility function similar to `formatReplacementString`?
___
*[`c-sharp/assets/CountryStatuses.xml` line 3 at r1](https://reviewable.io/reviews/paranext/paranext-core/1320#-OC9Rhd36bI-BgqE_oUh:-OC9Rhd36bI-BgqE_oUi:b-6ezpu5) ([raw file](https://github.com/paranext/paranext-core/blob/18f30c3568fb2f87e14350fe758abde175d04d83/c-sharp/assets/CountryStatuses.xml#L3)):*
> ```XML
> <?xml version="1.0" encoding="UTF-8" standalone="yes"?>
> <list>
> 
> ```

It seems like this content might need to be updated over time. Any idea how we might be able to update this programmatically without a new version download?
___
*[`c-sharp/IP-Country.zip` line 0 at r1](https://reviewable.io/reviews/paranext/paranext-core/1320#-OC9RCTC7LpAk1AoM9su:-OC9RCTC7LpAk1AoM9sv:brdm757) ([raw file](https://github.com/paranext/paranext-core/blob/18f30c3568fb2f87e14350fe758abde175d04d83/c-sharp/IP-Country.zip#L0)):*
Would this be better to put into `assets` along with the other non-code files we need to distribute?

**Review by tjcouch-sil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/1320)* status: all files reviewed, 3 unresolved discussions (waiting on @lyonsil)

___
*[`c-sharp/IP-Country.zip` line  at r1](https://reviewable.io/reviews/paranext/paranext-core/1320#-OC9RCTC7LpAk1AoM9su:-OC9nQAcDEG4Jx_AEEYu:b1d5r0w) ([raw file](https://github.com/paranext/paranext-core/blob/18f30c3568fb2f87e14350fe758abde175d04d83/c-sharp/IP-Country.zip#L)):*
<details><summary><i>Previously, lyonsil (Matt Lyons) wrote…</i></summary><blockquote>

Would this be better to put into `assets` along with the other non-code files we need to distribute?
</blockquote></details>

I would be glad to put it wherever it makes sense. I believe I saw the whole `assets` folder is copied into `assets/*`, though, whereas `ParatextData.dll` requires this file to be copied to the dll folder itself (hard-coded path :/ ). I am open to suggestions for how to change this if you want.
___
*[`c-sharp/assets/CountryStatuses.xml` line 3 at r1](https://reviewable.io/reviews/paranext/paranext-core/1320#-OC9Rhd36bI-BgqE_oUh:-OC9ndF8B4vQataR4bxE:b-grnt3y) ([raw file](https://github.com/paranext/paranext-core/blob/18f30c3568fb2f87e14350fe758abde175d04d83/c-sharp/assets/CountryStatuses.xml#L3)):*
<details><summary><i>Previously, lyonsil (Matt Lyons) wrote…</i></summary><blockquote>

It seems like this content might need to be updated over time. Any idea how we might be able to update this programmatically without a new version download?
</blockquote></details>

I copied this directly from PT9. I'd say it would be worth considering how to keep this and the IP-Country.zip file up-to-date. #1322 also mentioned in Paratext Discord.
___
*[`src/renderer/testing/about-panel.component.tsx` line 66 at r1](https://reviewable.io/reviews/paranext/paranext-core/1320#-OC9dFtv9LB90m93O6W7:-OC9pIDZ6uKO1q42z-Gm:b-4zacrb) ([raw file](https://github.com/paranext/paranext-core/blob/18f30c3568fb2f87e14350fe758abde175d04d83/src/renderer/testing/about-panel.component.tsx#L66)):*
<details><summary><i>Previously, lyonsil (Matt Lyons) wrote…</i></summary><blockquote>

Does this belong as a utility function similar to `formatReplacementString`?
</blockquote></details>

I threw this together as a quick hacky little thing because I feel like I'm already really behind on this issue to be honest. I think this has been done one other time, so I will investigate finding that usage as well and considering what kind of utility would be useful to replace both.

**Review by lyonsil — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/1320)* status: all files reviewed, 2 unresolved discussions (waiting on @tjcouch-sil)

___
*[`c-sharp/IP-Country.zip` line  at r1](https://reviewable.io/reviews/paranext/paranext-core/1320#-OC9RCTC7LpAk1AoM9su:-OC9rya29RNJC5mJVaJd:b-7ooy76) ([raw file](https://github.com/paranext/paranext-core/blob/18f30c3568fb2f87e14350fe758abde175d04d83/c-sharp/IP-Country.zip#L)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

I would be glad to put it wherever it makes sense. I believe I saw the whole `assets` folder is copied into `assets/*`, though, whereas `ParatextData.dll` requires this file to be copied to the dll folder itself (hard-coded path :/ ). I am open to suggestions for how to change this if you want.
</blockquote></details>

In case anything else pops up like this, can we create a folder for DLL dependencies and change the `csproj` copy rule so that everything in that directory copies into the DLL folder?
___
*[`c-sharp/assets/CountryStatuses.xml` line 3 at r1](https://reviewable.io/reviews/paranext/paranext-core/1320#-OC9Rhd36bI-BgqE_oUh:-OC9t2z41RLpFiKIrzdo:bg2j5h2) ([raw file](https://github.com/paranext/paranext-core/blob/18f30c3568fb2f87e14350fe758abde175d04d83/c-sharp/assets/CountryStatuses.xml#L3)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

I copied this directly from PT9. I'd say it would be worth considering how to keep this and the IP-Country.zip file up-to-date. #1322 also mentioned in Paratext Discord.
</blockquote></details>

Makes sense, thanks!

**Review by tjcouch-sil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/1320)* status: all files reviewed, 2 unresolved discussions (waiting on @lyonsil)

___
*[`c-sharp/IP-Country.zip` line  at r1](https://reviewable.io/reviews/paranext/paranext-core/1320#-OC9RCTC7LpAk1AoM9su:-OCEjAgz-Xo6EpE5lBoI:bjclw25) ([raw file](https://github.com/paranext/paranext-core/blob/18f30c3568fb2f87e14350fe758abde175d04d83/c-sharp/IP-Country.zip#L)):*
<details><summary><i>Previously, lyonsil (Matt Lyons) wrote…</i></summary><blockquote>

In case anything else pops up like this, can we create a folder for DLL dependencies and change the `csproj` copy rule so that everything in that directory copies into the DLL folder?
</blockquote></details>

Done - look good?
___
*[`src/renderer/testing/about-panel.component.tsx` line 66 at r1](https://reviewable.io/reviews/paranext/paranext-core/1320#-OC9dFtv9LB90m93O6W7:-OCFm5NSAmIc4l9P9BnE:b-l882i5) ([raw file](https://github.com/paranext/paranext-core/blob/18f30c3568fb2f87e14350fe758abde175d04d83/src/renderer/testing/about-panel.component.tsx#L66)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

I threw this together as a quick hacky little thing because I feel like I'm already really behind on this issue to be honest. I think this has been done one other time, so I will investigate finding that usage as well and considering what kind of utility would be useful to replace both.
</blockquote></details>

Added `formatReplacementStringToArray`

**Pull request merged**
