### PR TITLE
Create open project dialog

### PR DESCRIPTION
**Pull request by jolierabideau**
This change is [Reviewable](https://reviewable.io/reviews/paranext/paranext-core/387)

### CODE REVIEW

**Review by tjcouch-sil — APPROVED** [review]
:lgtm: great! Thanks :)

> Reviewed 9 of 9 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/387#-:-Nc94FSa3s7N0OTgNddW:b-3o0m9j)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by tjcouch-sil — COMMENTED** [review]
> Reviewed 8 of 8 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/387)* status: all files reviewed, 1 unresolved discussion (waiting on @jolierabideau)

___
*[`src/renderer/components/docking/open-project-tab.component.tsx` line 5 at r1](https://reviewable.io/reviews/paranext/paranext-core/387#-Nc9T_i_8wFDEqCYSVlI:-Nc9T_i_8wFDEqCYSVlJ:b-lp6k0n) ([raw file](https://github.com/paranext/paranext-core/blob/515a4bd8aefc338dc3ed99e59f7a46d47bd83701/src/renderer/components/docking/open-project-tab.component.tsx#L5)):*
> ```XML
> import FolderOpenIcon from '@mui/icons-material/FolderOpen';
> import logger from '@shared/services/logger.service';
> import './open-project-tab.component.css';
> ```

Do you still need to import the scss?

**Review by jolierabideau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/387)* status: :shipit: complete! all files reviewed, all discussions resolved

___
*[`src/renderer/components/docking/open-project-tab.component.tsx` line 5 at r1](https://reviewable.io/reviews/paranext/paranext-core/387#-Nc9T_i_8wFDEqCYSVlI:-NcNHLMbDO5i4gN46InO:b-w47aho) ([raw file](https://github.com/paranext/paranext-core/blob/515a4bd8aefc338dc3ed99e59f7a46d47bd83701/src/renderer/components/docking/open-project-tab.component.tsx#L5)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

Do you still need to import the scss?
</blockquote></details>

Done yes, I added it

**Review by tjcouch-sil — APPROVED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/387)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
