### PR TITLE
650 refactor imports

### PR DESCRIPTION
**Pull request by rolfheij-sil**
This change is [Reviewable](https://reviewable.io/reviews/paranext/paranext-core/668)

### CODE REVIEW

**Review by tjcouch-sil — APPROVED** [review]
:lgtm: just a couple of non-blocking notes. Thanks!

> Reviewed 28 of 28 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/668#-:-Nkw0Y89D9inA_9wN7DP:bbq2iub)* status: all files reviewed, 2 unresolved discussions (waiting on @rolfheij-sil)

___
*[`extensions/webpack/webpack.config.base.ts` line 42 at r1](https://reviewable.io/reviews/paranext/paranext-core/668#-Nkvxhb14wyziz07Tbsd:-Nkvxhb14wyziz07Tbse:b2160cu) ([raw file](https://github.com/paranext/paranext-core/blob/45878f9f6c01450760e864bafacacc785c148525/extensions/webpack/webpack.config.base.ts#L42)):*
> ```XML
>   // All other dependencies must be bundled into the extension
>   externals: [
>     // 'papi-shared-types',
> ```

Can this comment be removed?
___
*[`src/declarations/README.md` line 9 at r1](https://reviewable.io/reviews/paranext/paranext-core/668#-Nkvzi0jBk9cUiZ9r_y_:-Nkvzi0jBk9cUiZ9r_ya:b-uaei2d) ([raw file](https://github.com/paranext/paranext-core/blob/45878f9f6c01450760e864bafacacc785c148525/src/declarations/README.md#L9)):*
> ```Markdown
> For example, `papi-shared-types.ts` contains an interface that defines command handlers. Core and extensions both define and use each others' command handlers, so they both `declare module 'papi-shared-types'` and extend the `CommandHandlers` interface. That way, both core and extensions can use each others' command handler types.
> 
> All new type declaration names should start with `@papi` to inherit some ESLint rules that ignore unnecessary errors.
> ```

I guess this should now say `papi-` or `@papi`

**Review by tjcouch-sil — APPROVED** [review]
:lgtm: thanks again for the great work :)

> Reviewed 7 of 7 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/668#-:-Nl-aVVo0Mi8tb0uWoC0:bhu5mvx)* status: all files reviewed, 2 unresolved discussions (waiting on @rolfheij-sil)

**Review by tjcouch-sil — APPROVED** [review]
:lgtm:

> Reviewed 12 of 12 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/668#-:-Nl3beqB75DbfhM41_pN:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @rolfheij-sil)

___
*[`src/declarations/README.md` line 9 at r3](https://reviewable.io/reviews/paranext/paranext-core/668#-Nl3bY7l1qPkeny_Igl9:-Nl3bY7l1qPkeny_IglA:b9mb95w) ([raw file](https://github.com/paranext/paranext-core/blob/e8922f46d430d468b5b9fc9cf6ce8bc7cfd22b32/src/declarations/README.md#L9)):*
> ```Markdown
> For example, `papi-shared-types.ts` contains an interface that defines command handlers. Core and extensions both define and use each others' command handlers, so they both `declare module 'papi-shared-types'` and extend the `CommandHandlers` interface. That way, both core and extensions can use each others' command handler types.
> 
> All new type declaration names should start with `@papi` of `papi-` to inherit some ESLint rules that ignore unnecessary errors.
> ```

typo: "of" -> "or"

**Review by rolfheij-sil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/668)* status: all files reviewed, 1 unresolved discussion (waiting on @tjcouch-sil)

___
*[`extensions/webpack/webpack.config.base.ts` line 42 at r1](https://reviewable.io/reviews/paranext/paranext-core/668#-Nkvxhb14wyziz07Tbsd:-Nl3DMuCAZIJzyRKjjIu:bb6un1j) ([raw file](https://github.com/paranext/paranext-core/blob/45878f9f6c01450760e864bafacacc785c148525/extensions/webpack/webpack.config.base.ts#L42)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

Can this comment be removed?
</blockquote></details>

Done
___
*[`src/declarations/README.md` line 9 at r1](https://reviewable.io/reviews/paranext/paranext-core/668#-Nkvzi0jBk9cUiZ9r_y_:-Nl3DeTy0_Rp6loEiuwC:bb6un1j) ([raw file](https://github.com/paranext/paranext-core/blob/45878f9f6c01450760e864bafacacc785c148525/src/declarations/README.md#L9)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

I guess this should now say `papi-` or `@papi`
</blockquote></details>

Done
___
*[`src/declarations/README.md` line 9 at r3](https://reviewable.io/reviews/paranext/paranext-core/668#-Nl3bY7l1qPkeny_Igl9:-Nl3uOQL5A0yYLCynIAo:btk7nxb) ([raw file](https://github.com/paranext/paranext-core/blob/e8922f46d430d468b5b9fc9cf6ce8bc7cfd22b32/src/declarations/README.md#L9)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

typo: "of" -> "or"
</blockquote></details>

Confused Dutch Confused GIF - Confused Dutch Confused Dutch - Discover &  Share GIFs

**Review by tjcouch-sil — DISMISSED** [review]
:lgtm:

> Reviewed 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/668#-:-Nl48aQO9-HsNB46-RdT:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
