### PR TITLE
Update to .NET v8 and update our assembly dependencies

### PR DESCRIPTION
**Pull request by lyonsil**
This change is [Reviewable](https://reviewable.io/reviews/paranext/paranext-core/765)

### CODE REVIEW

**Review by tjcouch-sil — APPROVED** [review]
:lgtm:

> Reviewed 7 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/765#-:-Nqdtgst67M6TINXy7hx:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Review by lyonsil — COMMENTED** [review]
Good catch - I updated the README.

I think we should just merge this and post something to the `platform-changes` channel in Discord as a heads up for everyone.

> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/765#-:-NqhQCku6Q_o7bmxOsXL:b-77yig4)* status: 7 of 8 files reviewed, all discussions resolved

**Review by tjcouch-sil — APPROVED** [review]
:lgtm: agreed; I'd say a post in `platform-changes` would work well

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/765#-:-NqhT12CDHZDCkcwlFeo:b-94iv5u)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Review by tjcouch-sil — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/765)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Review by irahopkinson — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/765#-:-Nqhxokq6YbAsLERhwaO:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Pull request merged**
