### PR TITLE
Added Paratext Registration Info form

### LINKED ISSUE #971: Add Paratext user login (input registry credentials)
**User Story**
As a Bible translator, I want to be able to log in as my Paratext Registry user without opening Paratext 9 so that I can see available resources, use S/R, etc. without having to log in on Paratext 9.

**Description**
Create a way to log into the Paratext Registry in Platform.Bible. When you open PT9 the first time, it asks for a registry code or something along those lines. Basically, we want to be able to do that in Platform.Bible. This user credential needs to go into ParatextData.dll; we probably don't need it elsewhere.

Do this in relation to the identity stuff. Make a nice secure dialog that isn't shared origin and all that. #616

This should go in Platform.Bible

### PR DESCRIPTION
**Pull request by tjcouch-sil**
Also reformatted JSON RPC message errors so localized strings can come through and be displayed without any issues

I considered making the new service a data provider instead of just two commands... Would be interested in feedback. Kinda think it would be helpful to listen for updates to that data... But this is kinda a stopgap till we design and implement identity better. :thinking:

Resolves #971

- - -
This change is [Reviewable](https://reviewable.io/reviews/paranext/paranext-core/1260)

### CODE REVIEW

**Review by lyonsil — CHANGES_REQUESTED** [review]
> Reviewed 62 of 62 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/1260)* status: all files reviewed, 8 unresolved discussions (waiting on @tjcouch-sil)

___
*[`c-sharp/JsonUtils/RegistrationDataConverter.cs` line 26 at r1](https://reviewable.io/reviews/paranext/paranext-core/1260#-OArdp3-03QuezEfe2fh:-OArdp3-03QuezEfe2fi:b-7hzrx2) ([raw file](https://github.com/paranext/paranext-core/blob/d2bec2c487eb256ca557a2cfcb829c3c128ebfc9/c-sharp/JsonUtils/RegistrationDataConverter.cs#L26)):*
> ```Smalltalk
> 
>         string? lastPropertyName = null;
>         while (reader.Read())
> ```

Take a look at the other two `JsonConverter` classes we have. Both are now using the `onObjectLevel` counter to track if we've gotten to the end of the JSON object being deserialized. I found cases where JSON serialization fails if we don't include that logic because the reader goes past the end of this object and into the next object. It's only a few lines of code but is important.
___
*[`c-sharp/Users/ParatextRegistrationService.cs` line 48 at r1](https://reviewable.io/reviews/paranext/paranext-core/1260#-OAremDT0KDHs3j9x_Qk:-OAremDU2R9JZsr2u0kc:b5ltty0) ([raw file](https://github.com/paranext/paranext-core/blob/d2bec2c487eb256ca557a2cfcb829c3c128ebfc9/c-sharp/Users/ParatextRegistrationService.cs#L48)):*
> ```Smalltalk
>     #endregion
> 
>     #region Protected properties and methods
> ```

`protected` seems like an odd choice here. Why not `private`? You aren't subclassing this anywhere, but making this `protected` implies you're intending to do so. It isn't a big deal, just wondering. I think we've done it in some other C# code when we subclass inside of tests.
___
*[`c-sharp/Users/ParatextRegistrationService.cs` line 157 at r1](https://reviewable.io/reviews/paranext/paranext-core/1260#-OAri_wB0ImPVOaYgaSm:-OAri_wB0ImPVOaYgaSn:b-w1jdu0) ([raw file](https://github.com/paranext/paranext-core/blob/d2bec2c487eb256ca557a2cfcb829c3c128ebfc9/c-sharp/Users/ParatextRegistrationService.cs#L157)):*
> ```Smalltalk
>                 && RegistrationInfo.DefaultUser.Name != newRegistrationData.Name
>             )
>                 try
> ```

While what you have works, the convention I'm used to with `if` statements is that if you have more than 1 line in the block that is inside the `if` clause, then you wrap the whole thing in curly braces. I think the point is that if you add something to the end of the block, it might not be obvious that the new line isn't part of the `if` statement anymore if it's too long.

I can't promise that I've always followed this, but usually if I have try/catch I think I do.
___
*[`c-sharp/Users/ParatextRegistrationService.cs` line 176 at r1](https://reviewable.io/reviews/paranext/paranext-core/1260#-OArhVVt0DTW_snu2OYa:-OArhVVt0DTW_snu2OYb:b-jzlqjx) ([raw file](https://github.com/paranext/paranext-core/blob/d2bec2c487eb256ca557a2cfcb829c3c128ebfc9/c-sharp/Users/ParatextRegistrationService.cs#L176)):*
> ```Smalltalk
>             // No need to observe this task in any way. We are scheduling a call to restart the application then
>             // returning from this method to continue execution and properly return from this method.
> #pragma warning disable VSTHRD110 // Observe result of async calls
> ```

If you want to get rid of this warning disable/enable, just prepend `Task.Delay` with `_ = `. That is:
```c-sharp
_ = Task.Delay(...)
```

It looks a little cleaner and is a clear indication to the compiler that you purposefully aren't doing anything with the returned `Task`.
___
*[`c-sharp/Users/ParatextRegistrationService.cs` line 216 at r1](https://reviewable.io/reviews/paranext/paranext-core/1260#-OAriFpJ2lLNb7D1bga7:-OAriFpJ2lLNb7D1bga8:bbslfhv) ([raw file](https://github.com/paranext/paranext-core/blob/d2bec2c487eb256ca557a2cfcb829c3c128ebfc9/c-sharp/Users/ParatextRegistrationService.cs#L216)):*
> ```Smalltalk
>     /// preparation for switching to a different Paratext user.
>     ///
>     /// Adapted from `UserSwitchingHelper.PrepareForUserChange
> ```

Minor nit - I think you intended to put another back tick mark at the end of this line
___
*[`extensions/src/paratext-registration/src/paratext-registration.web-view.tsx` line 134 at r1](https://reviewable.io/reviews/paranext/paranext-core/1260#-OArnINc8Jq4u4GH_l19:-OArnINc8Jq4u4GH_l1A:b-i3qgk4) ([raw file](https://github.com/paranext/paranext-core/blob/d2bec2c487eb256ca557a2cfcb829c3c128ebfc9/extensions/src/paratext-registration/src/paratext-registration.web-view.tsx#L134)):*
> ```XML
>     isLoadingCurrentRegistrationData ||
>     saveState === SaveState.IsSaving ||
>     saveState === SaveState.HasSaved;
> ```

What if someone realizes they saved the wrong thing? Should it really be disabled still once the save is complete?
___
*[`extensions/src/paratext-registration/src/paratext-registration.web-view.tsx` line 141 at r1](https://reviewable.io/reviews/paranext/paranext-core/1260#-OAroiWI8pRj98oqRj2u:-OAroiWI8pRj98oqRj2v:b-kpc93p) ([raw file](https://github.com/paranext/paranext-core/blob/d2bec2c487eb256ca557a2cfcb829c3c128ebfc9/extensions/src/paratext-registration/src/paratext-registration.web-view.tsx#L141)):*
> ```XML
>     currentRegistrationData.email !== email ||
>     currentRegistrationData.supporterName !== supporter;
>   // whether the code seems valid according to a quick check
> ```

Is it worth having a simple regex check for email addresses, too?
___
*[`extensions/src/paratext-registration/src/paratext-registration.web-view.tsx` line 172 at r1](https://reviewable.io/reviews/paranext/paranext-core/1260#-OArnemc0RaPfwxXRcpS:-OArnemc0RaPfwxXRcpT:badnq51) ([raw file](https://github.com/paranext/paranext-core/blob/d2bec2c487eb256ca557a2cfcb829c3c128ebfc9/extensions/src/paratext-registration/src/paratext-registration.web-view.tsx#L172)):*
> ```XML
>           </Grid>
>         </Section>
>         {/* UX said to remove supporter info until we are using it in P10S. Leaving here for uncommenting when the time is right */}
> ```

Isn't the supporter info required to authenticate? If it is, then doesn't disabling it mean you can't enter your full credentials to authenticate to the registry?
___
*[`extensions/src/paratext-registration/src/types/paratext-registration.d.ts` line 31 at r1](https://reviewable.io/reviews/paranext/paranext-core/1260#-OArot7A9eA8e49_ngm8:-OArot7A9eA8e49_ngm9:b-hx4c2r) ([raw file](https://github.com/paranext/paranext-core/blob/d2bec2c487eb256ca557a2cfcb829c3c128ebfc9/extensions/src/paratext-registration/src/types/paratext-registration.d.ts#L31)):*
> ```XML
>     'paratextRegistration.showParatextRegistration': () => Promise<string | undefined>;
>     /**
>      * Gets information about user's current Paratext Registry user information in
> ```

Is it important to call out that the registration code isn't actually returned?
___
*[`src/main/main.ts` line 261 at r1](https://reviewable.io/reviews/paranext/paranext-core/1260#-OArpdZI1y2xn7cqkMy8:-OArpdZI1y2xn7cqkMy9:b-dv2qc6) ([raw file](https://github.com/paranext/paranext-core/blob/d2bec2c487eb256ca557a2cfcb829c3c128ebfc9/src/main/main.ts#L261)):*
> ```XML
>       app.quit();
>     },
>     'platform.restart': async () => {
> ```

I'm a little surprised this works reliably.

**Review by tjcouch-sil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/1260)* status: 58 of 62 files reviewed, 4 unresolved discussions (waiting on @lyonsil)

___
*[`c-sharp/JsonUtils/RegistrationDataConverter.cs` line 26 at r1](https://reviewable.io/reviews/paranext/paranext-core/1260#-OArdp3-03QuezEfe2fh:-OAt4ywB2RniQdO1G3Hr:b-nubwqa) ([raw file](https://github.com/paranext/paranext-core/blob/d2bec2c487eb256ca557a2cfcb829c3c128ebfc9/c-sharp/JsonUtils/RegistrationDataConverter.cs#L26)):*
<details><summary><i>Previously, lyonsil (Matt Lyons) wrote…</i></summary><blockquote>

Take a look at the other two `JsonConverter` classes we have. Both are now using the `onObjectLevel` counter to track if we've gotten to the end of the JSON object being deserialized. I found cases where JSON serialization fails if we don't include that logic because the reader goes past the end of this object and into the next object. It's only a few lines of code but is important.
</blockquote></details>

Done - weird :)
___
*[`c-sharp/Users/ParatextRegistrationService.cs` line 48 at r1](https://reviewable.io/reviews/paranext/paranext-core/1260#-OAremDT0KDHs3j9x_Qk:-OAt5Jcv6jJqurX3-bhl:b-nr4h14) ([raw file](https://github.com/paranext/paranext-core/blob/d2bec2c487eb256ca557a2cfcb829c3c128ebfc9/c-sharp/Users/ParatextRegistrationService.cs#L48)):*
<details><summary><i>Previously, lyonsil (Matt Lyons) wrote…</i></summary><blockquote>

`protected` seems like an odd choice here. Why not `private`? You aren't subclassing this anywhere, but making this `protected` implies you're intending to do so. It isn't a big deal, just wondering. I think we've done it in some other C# code when we subclass inside of tests.
</blockquote></details>

Was just copying things over from the S/R service... :grimacing: *\*whistles\** changed
___
*[`c-sharp/Users/ParatextRegistrationService.cs` line 157 at r1](https://reviewable.io/reviews/paranext/paranext-core/1260#-OAri_wB0ImPVOaYgaSm:-OAt5m0PBSpBXIMAFdrc:bb6un1j) ([raw file](https://github.com/paranext/paranext-core/blob/d2bec2c487eb256ca557a2cfcb829c3c128ebfc9/c-sharp/Users/ParatextRegistrationService.cs#L157)):*
<details><summary><i>Previously, lyonsil (Matt Lyons) wrote…</i></summary><blockquote>

While what you have works, the convention I'm used to with `if` statements is that if you have more than 1 line in the block that is inside the `if` clause, then you wrap the whole thing in curly braces. I think the point is that if you add something to the end of the block, it might not be obvious that the new line isn't part of the `if` statement anymore if it's too long.

I can't promise that I've always followed this, but usually if I have try/catch I think I do.
</blockquote></details>

Done
___
*[`c-sharp/Users/ParatextRegistrationService.cs` line 176 at r1](https://reviewable.io/reviews/paranext/paranext-core/1260#-OArhVVt0DTW_snu2OYa:-OAt6IVf9S8EvzEWqzrP:bxgoxpk) ([raw file](https://github.com/paranext/paranext-core/blob/d2bec2c487eb256ca557a2cfcb829c3c128ebfc9/c-sharp/Users/ParatextRegistrationService.cs#L176)):*
<details><summary><i>Previously, lyonsil (Matt Lyons) wrote…</i></summary><blockquote>

If you want to get rid of this warning disable/enable, just prepend `Task.Delay` with `_ = `. That is:
```c-sharp
_ = Task.Delay(...)
```

It looks a little cleaner and is a clear indication to the compiler that you purposefully aren't doing anything with the returned `Task`.
</blockquote></details>

Oops, forgot to come back to this and change to use `ThreadingUtils.RunTask`. Fixed
___
*[`c-sharp/Users/ParatextRegistrationService.cs` line 216 at r1](https://reviewable.io/reviews/paranext/paranext-core/1260#-OAriFpJ2lLNb7D1bga7:-OAt7gTv3asC7VUBH8gH:byed8lo) ([raw file](https://github.com/paranext/paranext-core/blob/d2bec2c487eb256ca557a2cfcb829c3c128ebfc9/c-sharp/Users/ParatextRegistrationService.cs#L216)):*
<details><summary><i>Previously, lyonsil (Matt Lyons) wrote…</i></summary><blockquote>

Minor nit - I think you intended to put another back tick mark at the end of this line
</blockquote></details>

Done - thanks!
___
*[`extensions/src/paratext-registration/src/paratext-registration.web-view.tsx` line 134 at r1](https://reviewable.io/reviews/paranext/paranext-core/1260#-OArnINc8Jq4u4GH_l19:-OAst5MZ5u-naUyBc3yK:b-owdydn) ([raw file](https://github.com/paranext/paranext-core/blob/d2bec2c487eb256ca557a2cfcb829c3c128ebfc9/extensions/src/paratext-registration/src/paratext-registration.web-view.tsx#L134)):*
<details><summary><i>Previously, lyonsil (Matt Lyons) wrote…</i></summary><blockquote>

What if someone realizes they saved the wrong thing? Should it really be disabled still once the save is complete?
</blockquote></details>

Once the C# side completes, it sets up a restart for shortly after submission. So this web view will be back up and unlocked for additional changes once the application restarts. Think that's all right?
___
*[`extensions/src/paratext-registration/src/paratext-registration.web-view.tsx` line 141 at r1](https://reviewable.io/reviews/paranext/paranext-core/1260#-OAroiWI8pRj98oqRj2u:-OAt1Dvb9ZhZ9R85WxXm:b-elbico) ([raw file](https://github.com/paranext/paranext-core/blob/d2bec2c487eb256ca557a2cfcb829c3c128ebfc9/extensions/src/paratext-registration/src/paratext-registration.web-view.tsx#L141)):*
<details><summary><i>Previously, lyonsil (Matt Lyons) wrote…</i></summary><blockquote>

Is it worth having a simple regex check for email addresses, too?
</blockquote></details>

Done :) 
___
*[`extensions/src/paratext-registration/src/paratext-registration.web-view.tsx` line 172 at r1](https://reviewable.io/reviews/paranext/paranext-core/1260#-OArnemc0RaPfwxXRcpS:-OAt1KRN0ZK56Psa0Iht:b-jfoohk) ([raw file](https://github.com/paranext/paranext-core/blob/d2bec2c487eb256ca557a2cfcb829c3c128ebfc9/extensions/src/paratext-registration/src/paratext-registration.web-view.tsx#L172)):*
<details><summary><i>Previously, lyonsil (Matt Lyons) wrote…</i></summary><blockquote>

Isn't the supporter info required to authenticate? If it is, then doesn't disabling it mean you can't enter your full credentials to authenticate to the registry?
</blockquote></details>

Supporter info is optional and isn't needed for authenticating. I have never had it filled out even from starting here years ago. [According to Sebastian](https://discord.com/channels/1064938364597436416/1298652234430545992/1298661575531429939), it's just a helper field to coordinate between a user and some primary supporter in Paratext 9. UX suggested removing the field. I figured we might want to add it back in, so I left the code commented. Feel free to discuss with UX, and maybe we can add it back in the follow-up if that's the decision. Seems reasonable to me to have it.
___
*[`extensions/src/paratext-registration/src/types/paratext-registration.d.ts` line 31 at r1](https://reviewable.io/reviews/paranext/paranext-core/1260#-OArot7A9eA8e49_ngm8:-OAs5klZ6sfnWX8D8H_d:bcvjgzp) ([raw file](https://github.com/paranext/paranext-core/blob/d2bec2c487eb256ca557a2cfcb829c3c128ebfc9/extensions/src/paratext-registration/src/types/paratext-registration.d.ts#L31)):*
<details><summary><i>Previously, lyonsil (Matt Lyons) wrote…</i></summary><blockquote>

Is it important to call out that the registration code isn't actually returned?
</blockquote></details>

Good idea. Done.
___
*[`src/main/main.ts` line 261 at r1](https://reviewable.io/reviews/paranext/paranext-core/1260#-OArpdZI1y2xn7cqkMy8:-OAs510A3QkMU6S1fj5j:b-e9ybtz) ([raw file](https://github.com/paranext/paranext-core/blob/d2bec2c487eb256ca557a2cfcb829c3c128ebfc9/src/main/main.ts#L261)):*
<details><summary><i>Previously, lyonsil (Matt Lyons) wrote…</i></summary><blockquote>

I'm a little surprised this works reliably.
</blockquote></details>

Why? What would you expect would be better? I just put what Electron said to do to restart. I am definitely open to adjustment.

**Review by lyonsil — DISMISSED** [review]
:lgtm:

I wouldn't suggest we hold releasing due to the restart discussion. I would just suggest we keep this in mind and maybe have Roopa stress test it a bit if possible.

I don't think we need to make the new service a data provider. I mean I guess we **could**, but it feels overly complicated for something that 1) is still pretty early in our implementation (i.e., identity concepts) and 2) is data that really ought to change VERY infrequently as-is (i.e., how often are people going to change their PT registration details?).

> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/1260#-:-OAtMVaxA9s4Ga_nroct:b2rr4oh)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

___
*[`c-sharp/Users/ParatextRegistrationService.cs` line 48 at r1](https://reviewable.io/reviews/paranext/paranext-core/1260#-OAremDT0KDHs3j9x_Qk:-OAtELFm6hmTOYRUrwLH:b-jcr9a3) ([raw file](https://github.com/paranext/paranext-core/blob/d2bec2c487eb256ca557a2cfcb829c3c128ebfc9/c-sharp/Users/ParatextRegistrationService.cs#L48)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

Was just copying things over from the S/R service... :grimacing: *\*whistles\** changed
</blockquote></details>

No worries
___
*[`c-sharp/Users/ParatextRegistrationService.cs` line 157 at r1](https://reviewable.io/reviews/paranext/paranext-core/1260#-OAri_wB0ImPVOaYgaSm:-OAtEOzzCPWba7UjoTnX:b-zcjvte) ([raw file](https://github.com/paranext/paranext-core/blob/d2bec2c487eb256ca557a2cfcb829c3c128ebfc9/c-sharp/Users/ParatextRegistrationService.cs#L157)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

Done
</blockquote></details>

Thanks
___
*[`extensions/src/paratext-registration/src/paratext-registration.web-view.tsx` line 134 at r1](https://reviewable.io/reviews/paranext/paranext-core/1260#-OArnINc8Jq4u4GH_l19:-OAtF2RM5R8a4eruP1BM:b-pwodss) ([raw file](https://github.com/paranext/paranext-core/blob/d2bec2c487eb256ca557a2cfcb829c3c128ebfc9/extensions/src/paratext-registration/src/paratext-registration.web-view.tsx#L134)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

Once the C# side completes, it sets up a restart for shortly after submission. So this web view will be back up and unlocked for additional changes once the application restarts. Think that's all right?
</blockquote></details>

Got it - makes sense
___
*[`extensions/src/paratext-registration/src/paratext-registration.web-view.tsx` line 141 at r1](https://reviewable.io/reviews/paranext/paranext-core/1260#-OAroiWI8pRj98oqRj2u:-OAtF76Z7jg5KXIE-RIP:b-k73z76) ([raw file](https://github.com/paranext/paranext-core/blob/d2bec2c487eb256ca557a2cfcb829c3c128ebfc9/extensions/src/paratext-registration/src/paratext-registration.web-view.tsx#L141)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

Done :)
</blockquote></details>

thanks
___
*[`extensions/src/paratext-registration/src/paratext-registration.web-view.tsx` line 172 at r1](https://reviewable.io/reviews/paranext/paranext-core/1260#-OArnemc0RaPfwxXRcpS:-OAtFCur65_4L8U1HYLb:b-mz2qbp) ([raw file](https://github.com/paranext/paranext-core/blob/d2bec2c487eb256ca557a2cfcb829c3c128ebfc9/extensions/src/paratext-registration/src/paratext-registration.web-view.tsx#L172)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

Supporter info is optional and isn't needed for authenticating. I have never had it filled out even from starting here years ago. [According to Sebastian](https://discord.com/channels/1064938364597436416/1298652234430545992/1298661575531429939), it's just a helper field to coordinate between a user and some primary supporter in Paratext 9. UX suggested removing the field. I figured we might want to add it back in, so I left the code commented. Feel free to discuss with UX, and maybe we can add it back in the follow-up if that's the decision. Seems reasonable to me to have it.
</blockquote></details>

Ok, thanks for confirming
___
*[`src/main/main.ts` line 261 at r1](https://reviewable.io/reviews/paranext/paranext-core/1260#-OArpdZI1y2xn7cqkMy8:-OAtFKRG0K6jzIdjgf6A:b-2dienq) ([raw file](https://github.com/paranext/paranext-core/blob/d2bec2c487eb256ca557a2cfcb829c3c128ebfc9/src/main/main.ts#L261)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

Why? What would you expect would be better? I just put what Electron said to do to restart. I am definitely open to adjustment.
</blockquote></details>

This kind of thing (i.e., an application triggering its own restart) has almost always been flaky in my experience. Maybe `relaunch` has a solid approach. There are various race conditions that I've seen hit with programmatic restarting in general, such as:
- If your process has a start-up mutex of some kind to enforce you can't run more than one instance at a time, how can you ensure the old process gives up the mutex before the new one tries to take it?
- If your old process is slow to die for some reason, does the OS kill it before it actually launches the new one?
- If your process doesn't have something like a mutex but does hold system-level resources (e.g., holds a port open, holds a file open for read/write, etc.), what happens if the new process tries to grab the resource before the old process gives it up?
- The OS will hold onto ports after a process dies based on the `TIME_WAIT` settings in the TCP stack. If you don't use the `SO_REUSEADDR` option then a new process can't bind to the port immediately. Usually `SO_REUSEADDR` is fine to use, but if it isn't for some reason then restarting could be a problem.
-  The OS might be slow to flush data from in memory caches (e.g., files, DBs, etc.) tied to the old process compared to when the new process tries to read from shared data locations. How can you tell for certain that the old process wrote everything in time for the new process to see it?

I'm sure there are other cases, but these are ones I've run into in the past. I think the only semi-foolproof approach has been to run some "sentinel" process whose entire purpose is to start/stop/restart the "real" process. The sentinel manages ensure the old process is closed and all critical resources are ready before starting the new process. Then you still have to worry about the sentinel dying or not killing itself when you want, but usually it's small and a lot less complex.

I'm not suggesting we need a sentinel here. I just would expect a "naive" restart API that just reruns your application's command line to start up a new instance to run into some of the race conditions (sometimes) that I mentioned above.

**Review by tjcouch-sil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/1260)* status: 60 of 65 files reviewed, all discussions resolved (waiting on @lyonsil)

___
*[`src/main/main.ts` line 261 at r1](https://reviewable.io/reviews/paranext/paranext-core/1260#-OArpdZI1y2xn7cqkMy8:-OAyeLSY50V4VrvjtM92:b6jiycl) ([raw file](https://github.com/paranext/paranext-core/blob/d2bec2c487eb256ca557a2cfcb829c3c128ebfc9/src/main/main.ts#L261)):*
<details><summary><i>Previously, lyonsil (Matt Lyons) wrote…</i></summary><blockquote>

This kind of thing (i.e., an application triggering its own restart) has almost always been flaky in my experience. Maybe `relaunch` has a solid approach. There are various race conditions that I've seen hit with programmatic restarting in general, such as:
- If your process has a start-up mutex of some kind to enforce you can't run more than one instance at a time, how can you ensure the old process gives up the mutex before the new one tries to take it?
- If your old process is slow to die for some reason, does the OS kill it before it actually launches the new one?
- If your process doesn't have something like a mutex but does hold system-level resources (e.g., holds a port open, holds a file open for read/write, etc.), what happens if the new process tries to grab the resource before the old process gives it up?
- The OS will hold onto ports after a process dies based on the `TIME_WAIT` settings in the TCP stack. If you don't use the `SO_REUSEADDR` option then a new process can't bind to the port immediately. Usually `SO_REUSEADDR` is fine to use, but if it isn't for some reason then restarting could be a problem.
-  The OS might be slow to flush data from in memory caches (e.g., files, DBs, etc.) tied to the old process compared to when the new process tries to read from shared data locations. How can you tell for certain that the old process wrote everything in time for the new process to see it?

I'm sure there are other cases, but these are ones I've run into in the past. I think the only semi-foolproof approach has been to run some "sentinel" process whose entire purpose is to start/stop/restart the "real" process. The sentinel manages ensure the old process is closed and all critical resources are ready before starting the new process. Then you still have to worry about the sentinel dying or not killing itself when you want, but usually it's small and a lot less complex.

I'm not suggesting we need a sentinel here. I just would expect a "naive" restart API that just reruns your application's command line to start up a new instance to run into some of the race conditions (sometimes) that I mentioned above.
</blockquote></details>

As discussed, let's see if we need to make anything more sophisticated in the future :)

**Review by lyonsil — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/1260)* status: all files reviewed, 1 unresolved discussion (waiting on @tjcouch-sil)

___
*[`src/main/services/rpc-server.ts` line 103 at r3](https://reviewable.io/reviews/paranext/paranext-core/1260#-OB0tPdHBSnk_Y3znbdT:-OB0tPdI2Qd-gzytLjQf:b-ud7fva) ([raw file](https://github.com/paranext/paranext-core/blob/77651db1a2192b17ba752533d1d2b27079734f42/src/main/services/rpc-server.ts#L103)):*
> ```XML
>     requestParams: RequestParams,
>   ): Promise<JSONRPCResponse> {
>     const requestId = this.createNextRequestId();
> ```

These top two lines need to be part of the retry. Otherwise, we could send multiple requests with the same ID which isn't allowed by the JSON-RPC protocol. I think I saw one of the JSON-RPC stacks (.NET or TS, don't remember which) just repeated the same response that had previously been sent when I accidentally reused a request ID during early development.

**Review by lyonsil — APPROVED** [review]
Looks great! Thanks for making the adjustments.

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/1260#-:-OB0yz3mAoOmRr8KvCnA:b-8rzysn)* status: 64 of 65 files reviewed, all discussions resolved

**Review by lyonsil — APPROVED** [review]
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/1260)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Pull request merged**
