### PR TITLE
Added tool bar (#223)

### PR DESCRIPTION
**Pull request by tombogle**
As part of this, I also replaced the "boilerplate" menu with temporary (hard-coded) hamburger menu on tool bar.

- - -
This change is [Reviewable](https://reviewable.io/reviews/paranext/paranext-core/239)

### CODE REVIEW

**Review by katherinejensen00 — CHANGES_REQUESTED** [review]
This looks really good! I liked the menu items you added. 

> Reviewed 10 of 10 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/239#-:-NXkLFIr3176yem3xDVw:bhxl0gh)* status: all files reviewed, 2 unresolved discussions (waiting on @tombogle)

___
*[`src/renderer/components/platform-bible-menu.tsx` line 1 at r1](https://reviewable.io/reviews/paranext/paranext-core/239#-NXkJMyg4QJaKSRInX3h:-NXkJMyg4QJaKSRInX3i:b90k1xa) ([raw file](https://github.com/paranext/paranext-core/blob/7c00819acc1d21adcd3ed60ff93557aec233745a/src/renderer/components/platform-bible-menu.tsx#L1)):*
> ```XML
> import Grid from '@mui/material/Grid';
> ```

Should we wrap Grid and Menu Item like we have been wrapping other MUI components?
___
*[`src/renderer/components/platform-bible-toolbar.tsx` line 4 at r1](https://reviewable.io/reviews/paranext/paranext-core/239#-NXkL0AnCGsC4MkEPpCe:-NXkL0AnCGsC4MkEPpCf:brmk8yf) ([raw file](https://github.com/paranext/paranext-core/blob/7c00819acc1d21adcd3ed60ff93557aec233745a/src/renderer/components/platform-bible-toolbar.tsx#L4)):*
> ```XML
> import AppBar from '@mui/material/AppBar';
> import Toolbar from '@mui/material/Toolbar';
> import IconButton from '@mui/material/IconButton';
> ```

This is definitely a MUI component we will want to wrap. That wasn't part of this case though. Would you mind creating cases for the  MUI components you used as part of this task?

**Review by rolfheij-sil — CHANGES_REQUESTED** [review]
Nice work Tom!

> Reviewed 10 of 10 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/239#-:-NY3b9Is1tuzXjxzBw91:b-7ioa80)* status: all files reviewed, 5 unresolved discussions (waiting on @tombogle)

___
*[`src/renderer/components/platform-bible-toolbar.tsx` line 16 at r1](https://reviewable.io/reviews/paranext/paranext-core/239#-NY3a3gT35LWeCD27ZRj:-NY3a3gT35LWeCD27ZRk:b-86xc4r) ([raw file](https://github.com/paranext/paranext-core/blob/7c00819acc1d21adcd3ed60ff93557aec233745a/src/renderer/components/platform-bible-toolbar.tsx#L16)):*
> ```XML
>   function toggleDrawer(): undefined {
>     setMenuOpen((prev) => !prev);
>     return undefined;
> ```

What's the use of returning undefined? Also, can't these small function just be inlined in the JSX?
___
*[`src/renderer/components/platform-bible-toolbar.tsx` line 20 at r1](https://reviewable.io/reviews/paranext/paranext-core/239#-NY3aVga-ZV5aSIojlmi:-NY3aVga-ZV5aSIojlmj:bvvmkgm) ([raw file](https://github.com/paranext/paranext-core/blob/7c00819acc1d21adcd3ed60ff93557aec233745a/src/renderer/components/platform-bible-toolbar.tsx#L20)):*
> ```XML
> 
>   function closeDrawer(): undefined {
>     if (menuOpen !== false) setMenuOpen(false);
> ```

The condition of the if-statement can probably just be `if(menuOpen)`, right?
___
*[`src/renderer/components/platform-bible-toolbar.tsx` line 50 at r1](https://reviewable.io/reviews/paranext/paranext-core/239#-NY3b2M3C_WxiCkQDmsq:-NY3b2M3C_WxiCkQDmsr:bqcw575) ([raw file](https://github.com/paranext/paranext-core/blob/7c00819acc1d21adcd3ed60ff93557aec233745a/src/renderer/components/platform-bible-toolbar.tsx#L50)):*
> ```XML
>           open={menuOpen}
>           onClose={() => closeDrawer()}
>           PaperProps={{ style: { top: '40px', width: '95%', height: '170px'} }}
> ```

Do we want to inline CSS stuff like this?

**Comment by tombogle** [comment]
*[`src/renderer/components/platform-bible-menu.tsx` line 1 at r1](https://reviewable.io/reviews/paranext/paranext-core/239#-NXkJMyg4QJaKSRInX3h:-NYOwJ0_3CW5aORuVPGP:blaqrl4) ([raw file](https://github.com/paranext/paranext-core/blob/7c00819acc1d21adcd3ed60ff93557aec233745a/src/renderer/components/platform-bible-menu.tsx#L1)):*
<details><summary><i>Previously, katherinejensen00 wrote…</i></summary><blockquote>

Should we wrap Grid and Menu Item like we have been wrapping other MUI components?
</blockquote></details>

Probably. I wasn't at all sure about whether this was likely to be the final approach we would take (especially the grid), so I wasn't sure if I should take the time to try to do this. I guess for the menu items, it might be beneficial to wrap them, so that even if we end up doing something totally different, the wrapper might still serve us. I see that Jolie is now working on this (#250). Since the task was really to add a toolbar, my main intent in adding the menu stuff was as a learning exercise for me and to kind of replace the boilerplate menu with something a little bit closer to what we might ultimately want.

**Comment by tombogle** [comment]
*[`src/renderer/components/platform-bible-toolbar.tsx` line 4 at r1](https://reviewable.io/reviews/paranext/paranext-core/239#-NXkL0AnCGsC4MkEPpCe:-NYOxz6c9f1GKn6HgJpE:btsqlqy) ([raw file](https://github.com/paranext/paranext-core/blob/7c00819acc1d21adcd3ed60ff93557aec233745a/src/renderer/components/platform-bible-toolbar.tsx#L4)):*
<details><summary><i>Previously, katherinejensen00 wrote…</i></summary><blockquote>

This is definitely a MUI component we will want to wrap. That wasn't part of this case though. Would you mind creating cases for the  MUI components you used as part of this task?
</blockquote></details>

I can do that. Do you think we'll want/need both AppBar and Toolbar wrapped as separate components, or would we perhaps be better served by a single wrapper component that encapsulates the two? Similarly, should our toolbar maybe just have a boolean that says whether or not to include the menu button (or an optional object that defines the menu structure)? For now, I'm using Typography only to display some place-holder text. Will we want to use Typography in Paratext? If so, will we want to wrap it? (I'm guessing we would, but not sure.)

**Comment by tombogle** [comment]
*[`src/renderer/components/platform-bible-toolbar.tsx` line 16 at r1](https://reviewable.io/reviews/paranext/paranext-core/239#-NY3a3gT35LWeCD27ZRj:-NYP-m8v1KI9jT02A-RN:b41ejeq) ([raw file](https://github.com/paranext/paranext-core/blob/7c00819acc1d21adcd3ed60ff93557aec233745a/src/renderer/components/platform-bible-toolbar.tsx#L16)):*
<details><summary><i>Previously, rolfheij-sil wrote…</i></summary><blockquote>

What's the use of returning undefined? Also, can't these small function just be inlined in the JSX?
</blockquote></details>

Nothing, I think, unless maybe it made Typescript happy. I grabbed this code from somewhere online. Inlining it is fine. The only potential benefits of making a function is readability (though toggleMenu and closeMenu would be better names) and keeping the JSX lean. I don't know if we have standards that dictate/suggest what we prefer as a team.

**Comment by tombogle** [comment]
*[`src/renderer/components/platform-bible-toolbar.tsx` line 50 at r1](https://reviewable.io/reviews/paranext/paranext-core/239#-NY3b2M3C_WxiCkQDmsq:-NYP1I36BkusIvIfHyy1:bxnh6zy) ([raw file](https://github.com/paranext/paranext-core/blob/7c00819acc1d21adcd3ed60ff93557aec233745a/src/renderer/components/platform-bible-toolbar.tsx#L50)):*
<details><summary><i>Previously, rolfheij-sil wrote…</i></summary><blockquote>

Do we want to inline CSS stuff like this?
</blockquote></details>

This is almost certainly temporary code. I don't know the correct way to dynamically resize the Drawer based on the number and lengths of the menus. I spent some time fiddling with it, but I didn't want to kill myself trying to figure it out since I'm not even sure if this is how we intend to lay out the menus in Platform.Bible.

**Review by rolfheij-sil — APPROVED** [review]
> Reviewed 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/239)* status: all files reviewed, 2 unresolved discussions (waiting on @katherinejensen00)

___
*[`src/renderer/components/platform-bible-toolbar.tsx` line 16 at r1](https://reviewable.io/reviews/paranext/paranext-core/239#-NY3a3gT35LWeCD27ZRj:-NYS9_ljBaZssWZwUZNl:b2tcem1) ([raw file](https://github.com/paranext/paranext-core/blob/7c00819acc1d21adcd3ed60ff93557aec233745a/src/renderer/components/platform-bible-toolbar.tsx#L16)):*
<details><summary><i>Previously, tombogle (Tom Bogle) wrote…</i></summary><blockquote>

Nothing, I think, unless maybe it made Typescript happy. I grabbed this code from somewhere online. Inlining it is fine. The only potential benefits of making a function is readability (though toggleMenu and closeMenu would be better names) and keeping the JSX lean. I don't know if we have standards that dictate/suggest what we prefer as a team.
</blockquote></details>

I don't think there's currently anything about that in the standards. Might be worth having a discussion on

**Review by katherinejensen00 — APPROVED** [review]
:lgtm:

> Reviewed 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/239#-:-NYTHxM57H8Qq2NNCSnR:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @tombogle)

___
*[`src/renderer/components/platform-bible-toolbar.tsx` line 4 at r1](https://reviewable.io/reviews/paranext/paranext-core/239#-NXkL0AnCGsC4MkEPpCe:-NYTHf3q4JMXuXea2X1w:blfsfub) ([raw file](https://github.com/paranext/paranext-core/blob/7c00819acc1d21adcd3ed60ff93557aec233745a/src/renderer/components/platform-bible-toolbar.tsx#L4)):*
<details><summary><i>Previously, tombogle (Tom Bogle) wrote…</i></summary><blockquote>

I can do that. Do you think we'll want/need both AppBar and Toolbar wrapped as separate components, or would we perhaps be better served by a single wrapper component that encapsulates the two? Similarly, should our toolbar maybe just have a boolean that says whether or not to include the menu button (or an optional object that defines the menu structure)? For now, I'm using Typography only to display some place-holder text. Will we want to use Typography in Paratext? If so, will we want to wrap it? (I'm guessing we would, but not sure.)
</blockquote></details>

I don't know for sure, but wrapping Typography makes sense to me. I like the idea of a single wrapper component for AppBar and ToolBar with a boolean for menu button.

**Review by tombogle — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/239)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @tombogle)

___
*[`src/renderer/components/platform-bible-toolbar.tsx` line 20 at r1](https://reviewable.io/reviews/paranext/paranext-core/239#-NY3aVga-ZV5aSIojlmi:-NYP1Dgj-JlFoRKIHBlD:b-896fix) ([raw file](https://github.com/paranext/paranext-core/blob/7c00819acc1d21adcd3ed60ff93557aec233745a/src/renderer/components/platform-bible-toolbar.tsx#L20)):*
<details><summary><i>Previously, rolfheij-sil wrote…</i></summary><blockquote>

The condition of the if-statement can probably just be `if(menuOpen)`, right?
</blockquote></details>

Done.

**Pull request merged**
