### PR TITLE
Use ScriptureReference type more consistently

### LINKED ISSUE #391: Use ScriptureReference type more consistently
There's multiple ways to represent scripture references being used in our code.

- The `VerseRef` class from `@sillsdev/scripture`
- The `ScriptureReference` type from `scripture-util`
- Creating an object in place that kinda looks like `ScriptureReference`

Ideally we would use `VerseRef` everywhere, but since that poses some challenges we've decided to not do that for now. Instead we will use `ScriptureReference` everywhere, consistently. Being consistent allows for an easier change to `VerseRef` when it is time to do that.

### PR DESCRIPTION
**Pull request by rolfheij-sil**
Resolves #391

- - -
This change is [Reviewable](https://reviewable.io/reviews/paranext/paranext-core/392)

### CODE REVIEW

**Review by tjcouch-sil — CHANGES_REQUESTED** [review]
Very good :) thanks for the update!

> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/392#-:-NcSwI6OCwtH9ZlUD4zk:b-e8ammq)* status: all files reviewed, 2 unresolved discussions (waiting on @rolfheij-sil)

___
*[`src/declarations/papi-shared-types.ts` line 51 at r1](https://reviewable.io/reviews/paranext/paranext-core/392#-NcStx2o3FL2tosbu0NE:-NcStx2o3FL2tosbu0NF:b-a01jgg) ([raw file](https://github.com/paranext/paranext-core/blob/87c5eacdddaf57165a01dda4d42ff0a6c9230a9c/src/declarations/papi-shared-types.ts#L51)):*
> ```XML
>   export interface SettingTypes {
>     'platform.verseRef': { bookNum: number; chapterNum: number; verseNum: number };
>     // Is there a way to use ScriptureReference in here too? I got some build issues when I tried..
> ```

Looks like you can just add the following line _inside_ the module declaration:

```typescript
declare module 'papi-shared-types' {
  import { ScriptureReference } from 'papi-components';
...
```
___
*[`src/declarations/papi-shared-types.ts` line 51 at r1](https://reviewable.io/reviews/paranext/paranext-core/392#-NcSwDjB63NBO-K2rKSa:-NcSwDjB63NBO-K2rKSb:b-6e09vo) ([raw file](https://github.com/paranext/paranext-core/blob/87c5eacdddaf57165a01dda4d42ff0a6c9230a9c/src/declarations/papi-shared-types.ts#L51)):*
> ```XML
>   export interface SettingTypes {
>     'platform.verseRef': { bookNum: number; chapterNum: number; verseNum: number };
>     // Is there a way to use ScriptureReference in here too? I got some build issues when I tried..
> ```

While testing the comment above, I discovered that the way `papi.d.ts` is being generated right now is not correct. Essentially is is baking `'platform.verseRef'` into all the setting service generic type options instead of using the interface type because there's only one string in `SettingNames`. Would you mind adding the following please? Sorry I didn't catch this before.

```typescript
  export interface SettingTypes {
    'platform.verseRef': ScriptureReference;
    // With only one key in this interface, `papi.d.ts` was baking in the literal string when
    // `SettingNames` was being used. Adding a placeholder key makes TypeScript generate `papi.d.ts`
    // correctly. When we add another setting, we can remove this placeholder.
    placeholder: null;
  }
```

This is what it looks like without the placeholder:



This is what it looks like with the placeholder:

**Review by tjcouch-sil — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/392#-:-NcTLkQW-bqFdb1YzNKV:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @rolfheij-sil)

___
*[`src/declarations/papi-shared-types.ts` line 51 at r1](https://reviewable.io/reviews/paranext/paranext-core/392#-NcSwDjB63NBO-K2rKSa:-NcTLhm1-c7G3YmOMo4N:b-9755fn) ([raw file](https://github.com/paranext/paranext-core/blob/87c5eacdddaf57165a01dda4d42ff0a6c9230a9c/src/declarations/papi-shared-types.ts#L51)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

While testing the comment above, I discovered that the way `papi.d.ts` is being generated right now is not correct. Essentially is is baking `'platform.verseRef'` into all the setting service generic type options instead of using the interface type because there's only one string in `SettingNames`. Would you mind adding the following please? Sorry I didn't catch this before.

```typescript
  export interface SettingTypes {
    'platform.verseRef': ScriptureReference;
    // With only one key in this interface, `papi.d.ts` was baking in the literal string when
    // `SettingNames` was being used. Adding a placeholder key makes TypeScript generate `papi.d.ts`
    // correctly. When we add another setting, we can remove this placeholder.
    placeholder: null;
  }
```

This is what it looks like without the placeholder:



This is what it looks like with the placeholder:


</blockquote></details>

Thank you!

**Review by rolfheij-sil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/392)* status: all files reviewed, 1 unresolved discussion (waiting on @tjcouch-sil)

___
*[`src/declarations/papi-shared-types.ts` line 51 at r1](https://reviewable.io/reviews/paranext/paranext-core/392#-NcStx2o3FL2tosbu0NE:-NcTEQTkDbZ0xS5G7mJE:b-ol0y5v) ([raw file](https://github.com/paranext/paranext-core/blob/87c5eacdddaf57165a01dda4d42ff0a6c9230a9c/src/declarations/papi-shared-types.ts#L51)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

Looks like you can just add the following line _inside_ the module declaration:

```typescript
declare module 'papi-shared-types' {
  import { ScriptureReference } from 'papi-components';
...
```
</blockquote></details>

Aha, that works. Thanks. Done.
___
*[`src/declarations/papi-shared-types.ts` line 51 at r1](https://reviewable.io/reviews/paranext/paranext-core/392#-NcSwDjB63NBO-K2rKSa:-NcTEKx74itKXLwm7IV_:b-896fix) ([raw file](https://github.com/paranext/paranext-core/blob/87c5eacdddaf57165a01dda4d42ff0a6c9230a9c/src/declarations/papi-shared-types.ts#L51)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

While testing the comment above, I discovered that the way `papi.d.ts` is being generated right now is not correct. Essentially is is baking `'platform.verseRef'` into all the setting service generic type options instead of using the interface type because there's only one string in `SettingNames`. Would you mind adding the following please? Sorry I didn't catch this before.

```typescript
  export interface SettingTypes {
    'platform.verseRef': ScriptureReference;
    // With only one key in this interface, `papi.d.ts` was baking in the literal string when
    // `SettingNames` was being used. Adding a placeholder key makes TypeScript generate `papi.d.ts`
    // correctly. When we add another setting, we can remove this placeholder.
    placeholder: null;
  }
```

This is what it looks like without the placeholder:



This is what it looks like with the placeholder:


</blockquote></details>

Done.

**Review by tjcouch-sil — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/392)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
