### PR TITLE
Provide a way for extensions to start other processes

### PR DESCRIPTION
**Pull request by lyonsil**
This change is [Reviewable](https://reviewable.io/reviews/paranext/paranext-core/1093)

### CODE REVIEW

**Review by tjcouch-sil — APPROVED** [review]
Awesome!! A couple questions, but it looks great :)

> Reviewed 9 of 9 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/1093#-:-O5KJ0ljB5H7Y9b4awiA:b7w6w02)* status: all files reviewed, 1 unresolved discussion (waiting on @lyonsil)

___
*[`lib/papi-dts/papi.d.ts` line 4 at r1](https://reviewable.io/reviews/paranext/paranext-core/1093#-O5KGdawBv4cZxhjAe-G:-O5KGdawBv4cZxhjAe-H:bvwwjxk) ([raw file](https://github.com/paranext/paranext-core/blob/55960dce64dde0170428c5ce8f8d2fa12cc3c991/lib/papi-dts/papi.d.ts#L4)):*
> ```XML
> /// <reference types="node" />
> /// <reference types="node" />
> /// <reference types="node" />
> ```

OH I was always wondering what was wrong. Glad the generator finally figured out we needed to add this same exact line for a third and fourth time. Phew. Kept me up at night. :joy:
___
*[`src/extension-host/services/create-process.service.ts` line 27 at r1](https://reviewable.io/reviews/paranext/paranext-core/1093#-O5KHwTK6KUqtnqZWxKB:-O5KHwTK6KUqtnqZWxKC:b2ae5i1) ([raw file](https://github.com/paranext/paranext-core/blob/55960dce64dde0170428c5ce8f8d2fa12cc3c991/src/extension-host/services/create-process.service.ts#L27)):*
> ```XML
>   options: SpawnOptionsWithStdioTuple<StdioPipe, StdioPipe, StdioPipe>,
> ): ChildProcessByStdio<Writable, Readable, Readable> => {
>   // Can't specify the argument as ExecutionToken because it would create cyclical type dependencies
> ```

You can add `type` to imports to cyclically import types without creating actual circular dependencies - would this help?

```ts
import type { ExecutionToken } from '.....';
```
___
*[`src/shared/models/create-process-privilege.model.ts` line 19 at r1](https://reviewable.io/reviews/paranext/paranext-core/1093#-O5KIapIDKdyNkLDSY37:-O5KIapJ9mL2GFAPFH8m:b-mbgh8g) ([raw file](https://github.com/paranext/paranext-core/blob/55960dce64dde0170428c5ce8f8d2fa12cc3c991/src/shared/models/create-process-privilege.model.ts#L19)):*
> ```XML
> /**
>  * Run {@link spawn} to create a child process. The platform will automatically kill all child
>  * processes created this way in packaged builds. Child processes are not killed when running in
> ```

Do you know why children are not killed in development? Is it because of how we're doing the file watching and such? Seems concerning to me :grimacing: especially considering hot reloading. Do they properly get killed if the extension kills them in `deactivate`?

**Review by lyonsil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/1093)* status: all files reviewed, 1 unresolved discussion (waiting on @tjcouch-sil)

___
*[`lib/papi-dts/papi.d.ts` line 4 at r1](https://reviewable.io/reviews/paranext/paranext-core/1093#-O5KGdawBv4cZxhjAe-G:-O5KJl6w0ghl5D4Oufgf:bjuivz) ([raw file](https://github.com/paranext/paranext-core/blob/55960dce64dde0170428c5ce8f8d2fa12cc3c991/lib/papi-dts/papi.d.ts#L4)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

OH I was always wondering what was wrong. Glad the generator finally figured out we needed to add this same exact line for a third and fourth time. Phew. Kept me up at night. :joy:
</blockquote></details>

Yeah I noticed that. I almost manually removed the new ones, but then I just figured they would be readded when the tool runs again.
___
*[`src/extension-host/services/create-process.service.ts` line 27 at r1](https://reviewable.io/reviews/paranext/paranext-core/1093#-O5KHwTK6KUqtnqZWxKB:-O5KJut9AFT4BEX-42Lu:bfu4zq) ([raw file](https://github.com/paranext/paranext-core/blob/55960dce64dde0170428c5ce8f8d2fa12cc3c991/src/extension-host/services/create-process.service.ts#L27)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

You can add `type` to imports to cyclically import types without creating actual circular dependencies - would this help?

```ts
import type { ExecutionToken } from '.....';
```
</blockquote></details>

I was trying to put all the `elevatedPrivileges` types in `common` so they end up in `papi.d.ts` and are available to extensions. That gets tricky when the types come from our node-dependent libs. In this case, `ExecutionToken` is a class which has some crypto stuff mixed in which is not available in the browser. So I can't put `ExecutionToken` itself anywhere in `shared`. I guess we could create a type/interface that `ExecutionToken` implements and put that in `shared`. That's sort of what I did, but I left off fields in `ExecutionToken` that are pretty much only used by the service.

Maybe I shouldn't have made `ExecutionToken` a class, but at this point I don't really want to refactor unless it's really important. Also I kind of don't want people to know/mess with some of the other fields (like `nonce`).
___
*[`src/shared/models/create-process-privilege.model.ts` line 19 at r1](https://reviewable.io/reviews/paranext/paranext-core/1093#-O5KIapIDKdyNkLDSY37:-O5KLqNW8N8vqd6C_fi4:b-tris7c) ([raw file](https://github.com/paranext/paranext-core/blob/55960dce64dde0170428c5ce8f8d2fa12cc3c991/src/shared/models/create-process-privilege.model.ts#L19)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

Do you know why children are not killed in development? Is it because of how we're doing the file watching and such? Seems concerning to me :grimacing: especially considering hot reloading. Do they properly get killed if the extension kills them in `deactivate`?
</blockquote></details>

This all came up with an earlier change I made fix a bug that Roopa found where the extension host wouldn't restart more than once or twice. There are a couple of things in play here:
1. We need to work on Windows, Linux, and macOS. Linux and macOS adhere to POSIX, and Windows does not. One of the implications of that is that if you send a SIG_TERM signal to a process on Linux/macOS, it is a signal to gracefully shut down and processes can run whatever cleanup logic they like. Windows completely ignores that signal, so apps never know what you were trying to do. The "right" way to close a Windows app gracefully is to get a handle to its main window and send a WM_CLOSE message. I don't know of an obvious way to do that from Node without spawning a separate process like `taskkill` using PIDs, and I find that to be a little dangerous as PIDs can be recycled quickly on Windows if your target process closes and another process opens. So when we send signals right now I'm only ever sending a SIG_KILL since that's the only signal type that all 3 OSes understand. SIG_KILL is an abrupt kill that doesn't give processes a chance to run shutdown code (e.g., the extension host stopping child processes).
2. For the extension host I added an OS agnostic signaling mechanism using Node's interprocess message passing mechanism. Unfortunately in development we aren't actually starting the extension host, we're starting nodemon. So when I try to send a signal it goes to nodemon which gets in the way of message passing. That means whatever solution we might try to find for these secondary processes can't be used in the same way across all our processes which gets a little hard to remember/understand.

When things are working properly in package builds, the flow of operations is:
A) Main receives a signal to shut down.
B) Main sends a graceful shutdown signal to the extension host (node process).
C) The extension host runs `process.exit()`
D) The extension host's `exit` event runs which sends SIG_KILL messages to all the child processes that are still running.

If somewhere in there we try to run `deactivate()` on extensions during shutdown (which I don't think we do), then if the extension has a graceful way to communicate with its child processes it could do so then/there. That wouldn't work in development, though, because of the problem with `nodemon` getting in the way and therefore the extension host never getting the graceful shutdown message.

If we want hot reloading to work with child processes in a graceful way we need to:
- Have a way to reliably sent graceful shutdown messages to the extension host regardless of whether nodemon is there.
- Change the extension host unload all extensions during shutdown (which is also timed right now so that we hard kill after 1 second if the process is still alive when we tried to do it nicely)

On an extension-by-extension basis, someone could also have a way to detect any lingering processes they created (e.g., through lock/PID files) and kill them before starting up new ones. It's all kind of messy, though, with nodemon controlling the extension host.

**Review by tjcouch-sil — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/1093)* status: all files reviewed, 1 unresolved discussion

**Review by tjcouch-sil — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/1093)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Review by tjcouch-sil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/1093)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

___
*[`src/shared/models/create-process-privilege.model.ts` line 19 at r1](https://reviewable.io/reviews/paranext/paranext-core/1093#-O5KIapIDKdyNkLDSY37:-O5KsKvj5F0E-FE5qCvq:bdjklip) ([raw file](https://github.com/paranext/paranext-core/blob/55960dce64dde0170428c5ce8f8d2fa12cc3c991/src/shared/models/create-process-privilege.model.ts#L19)):*
<details><summary><i>Previously, lyonsil (Matt Lyons) wrote…</i></summary><blockquote>

This all came up with an earlier change I made fix a bug that Roopa found where the extension host wouldn't restart more than once or twice. There are a couple of things in play here:
1. We need to work on Windows, Linux, and macOS. Linux and macOS adhere to POSIX, and Windows does not. One of the implications of that is that if you send a SIG_TERM signal to a process on Linux/macOS, it is a signal to gracefully shut down and processes can run whatever cleanup logic they like. Windows completely ignores that signal, so apps never know what you were trying to do. The "right" way to close a Windows app gracefully is to get a handle to its main window and send a WM_CLOSE message. I don't know of an obvious way to do that from Node without spawning a separate process like `taskkill` using PIDs, and I find that to be a little dangerous as PIDs can be recycled quickly on Windows if your target process closes and another process opens. So when we send signals right now I'm only ever sending a SIG_KILL since that's the only signal type that all 3 OSes understand. SIG_KILL is an abrupt kill that doesn't give processes a chance to run shutdown code (e.g., the extension host stopping child processes).
2. For the extension host I added an OS agnostic signaling mechanism using Node's interprocess message passing mechanism. Unfortunately in development we aren't actually starting the extension host, we're starting nodemon. So when I try to send a signal it goes to nodemon which gets in the way of message passing. That means whatever solution we might try to find for these secondary processes can't be used in the same way across all our processes which gets a little hard to remember/understand.

When things are working properly in package builds, the flow of operations is:
A) Main receives a signal to shut down.
B) Main sends a graceful shutdown signal to the extension host (node process).
C) The extension host runs `process.exit()`
D) The extension host's `exit` event runs which sends SIG_KILL messages to all the child processes that are still running.

If somewhere in there we try to run `deactivate()` on extensions during shutdown (which I don't think we do), then if the extension has a graceful way to communicate with its child processes it could do so then/there. That wouldn't work in development, though, because of the problem with `nodemon` getting in the way and therefore the extension host never getting the graceful shutdown message.

If we want hot reloading to work with child processes in a graceful way we need to:
- Have a way to reliably sent graceful shutdown messages to the extension host regardless of whether nodemon is there.
- Change the extension host unload all extensions during shutdown (which is also timed right now so that we hard kill after 1 second if the process is still alive when we tried to do it nicely)

On an extension-by-extension basis, someone could also have a way to detect any lingering processes they created (e.g., through lock/PID files) and kill them before starting up new ones. It's all kind of messy, though, with nodemon controlling the extension host.
</blockquote></details>

Making a note on https://github.com/paranext/paranext-core/issues/115 that we need to figure this out :)

**Review by irahopkinson — COMMENTED** [review]
> Reviewed 9 of 9 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/1093)* status: all files reviewed, 1 unresolved discussion (waiting on @lyonsil)

___
*[`src/shared/models/create-process-privilege.model.ts` line 25 at r1](https://reviewable.io/reviews/paranext/paranext-core/1093#-O5LTyw26rTlsKMZABVv:-O5LTyw26rTlsKMZABVw:b-y120u6) ([raw file](https://github.com/paranext/paranext-core/blob/55960dce64dde0170428c5ce8f8d2fa12cc3c991/src/shared/models/create-process-privilege.model.ts#L25)):*
> ```XML
>  * win32, linux, and macOS that include appropriate executables.
>  *
>  * ```@typescript
> ```

nit the `@` should be removed so that the example is formatted correctly. Here and below.



_Code quote:_
```XML
@
```

**Pull request merged**
