### PR TITLE
Add retry logic to adding webViews and increase a startup delay in main

### PR DESCRIPTION
**Pull request by lyonsil**
This change is [Reviewable](https://reviewable.io/reviews/paranext/paranext-core/153)

### CODE REVIEW

**Review by tjcouch-sil — COMMENTED** [review]
Looks great! Thanks for the hard work on this! Just one thing to adjust if that sounds good.

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/153#-:-NT01cf-400NbKzo1T85:b-30h6tn)* status: all files reviewed, 1 unresolved discussion (waiting on @lyonsil)

___
*[`src/shared/services/web-view.service.ts` line 102 at r1](https://reviewable.io/reviews/paranext/paranext-core/153#-NT01FHSAfHLGRpzUwh0:-NT01FHT82uzi_tCpayX:b-uo9d88) ([raw file](https://github.com/paranext/paranext-core/blob/dab7f1c1dab6d9c6592669a93f162a346b642815/src/shared/services/web-view.service.ts#L102)):*
> ```XML
>         .catch(async (error) => {
>           succeeded = false;
>           if (attemptsRemaining === 1) throw error;
> ```

Let's please return a meaningful error here for debugging purposes :)
```typescript
throw new Error('Message');
```

**Review by tjcouch-sil — APPROVED** [review]
:lgtm: Please feel free to fix and resolve the comment on your own (if reviewable allows. Let me know otherwise)

> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/153#-:-NT01mpH-FmYCJibEErd:bz18cs4)* status: all files reviewed, 1 unresolved discussion (waiting on @lyonsil)

**Review by tjcouch-sil — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/153)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @lyonsil)

___
*[`src/shared/services/web-view.service.ts` line 102 at r1](https://reviewable.io/reviews/paranext/paranext-core/153#-NT01FHSAfHLGRpzUwh0:-NT02j3S-oSSZNhEXqnt:bg192ad) ([raw file](https://github.com/paranext/paranext-core/blob/dab7f1c1dab6d9c6592669a93f162a346b642815/src/shared/services/web-view.service.ts#L102)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

Let's please return a meaningful error here for debugging purposes :)
```typescript
throw new Error('Message');
```
</blockquote></details>

Oh I definitely was not reading this right. Sorry about that. I should have read more carefully.

**Review by lyonsil — COMMENTED** [review]
> Reviewed 1 of 2 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/153)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @lyonsil)

**Review by tjcouch-sil — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/153#-:-NT09Goi3adshog2oeiW:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @lyonsil)

**Pull request merged**
