### PR TITLE
Pair incoming responses to the original requests (#61)

### PR DESCRIPTION
**Pull request by lyonsil**
This is a PR on top of Ira's recent Resharpier update.  It includes all feedback from the original, draft PR.

- - -
This change is [Reviewable](https://reviewable.io/reviews/paranext/paranext-core/102)

### CODE REVIEW

**Review by FoolRunning — CHANGES_REQUESTED** [review]
> Reviewed 23 of 23 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/102)* status: all files reviewed, 1 unresolved discussion (waiting on @irahopkinson, @lyonsil, and @tjcouch-sil)

___
*[`c-sharp/MessageTransports/PapiClient.cs` line 1 at r1](https://reviewable.io/reviews/paranext/paranext-core/102#-NRYoCCM7NHahIZm75u7:-NRYoCCM7NHahIZm75u8:b-hq82zm) ([raw file](https://github.com/paranext/paranext-core/blob/5a96237c4c31ee14b826ea3b5098a8f3aec332d0/c-sharp/MessageTransports/PapiClient.cs#L1)):*
> ```Smalltalk
> using System.Collections.Concurrent;
> ```

Something bad happened here. This was not treated as a renamed file - making it *really* hard to see what was changed.
Is there anything you can do to make it detect as a rename?

**Review by FoolRunning — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/102)* status: all files reviewed, 1 unresolved discussion (waiting on @irahopkinson, @lyonsil, and @tjcouch-sil)

___
*[`c-sharp/MessageTransports/PapiClient.cs` line 1 at r1](https://reviewable.io/reviews/paranext/paranext-core/102#-NRYoCCM7NHahIZm75u7:-NRYof-t2Wm9kx47nTS8:b-7xkpax) ([raw file](https://github.com/paranext/paranext-core/blob/5a96237c4c31ee14b826ea3b5098a8f3aec332d0/c-sharp/MessageTransports/PapiClient.cs#L1)):*
<details><summary><i>Previously, FoolRunning (Tim Steenwyk) wrote…</i></summary><blockquote>

Something bad happened here. This was not treated as a renamed file - making it *really* hard to see what was changed.
Is there anything you can do to make it detect as a rename?
</blockquote></details>

It may require you to change to two commits (one to rename the file and one to make changes to the file).

**Review by lyonsil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/102)* status: all files reviewed, 1 unresolved discussion (waiting on @FoolRunning, @irahopkinson, and @tjcouch-sil)

___
*[`c-sharp/MessageTransports/PapiClient.cs` line 1 at r1](https://reviewable.io/reviews/paranext/paranext-core/102#-NRYoCCM7NHahIZm75u7:-NRYs1j0DDgpXoxoZxw9:b7d4q1s) ([raw file](https://github.com/paranext/paranext-core/blob/5a96237c4c31ee14b826ea3b5098a8f3aec332d0/c-sharp/MessageTransports/PapiClient.cs#L1)):*
<details><summary><i>Previously, lyonsil wrote…</i></summary><blockquote>

This shows up in git as a rename.  Maybe it's just something with Reviewable?

```
 22 files changed, 541 insertions(+), 374 deletions(-)
 delete mode 100644 c-sharp/Data/NetworkConnectorTypes.cs
 rename c-sharp/{Data => JsonUtils}/EnumConverter.cs (96%)
 rename c-sharp/{Data => JsonUtils}/MessageConverter.cs (90%)
 rename c-sharp/{Data => JsonUtils}/PrivateConstructorResolver.cs (95%)
 rename c-sharp/{Utils/JsonUtils.cs => JsonUtils/SerializationOptions.cs} (84%)
 create mode 100644 c-sharp/MessageHandlers/IMessageHandler.cs
 create mode 100644 c-sharp/MessageHandlers/MessageHandlerEvent.cs
 create mode 100644 c-sharp/MessageHandlers/MessageHandlerRequestByRequestType.cs
 create mode 100644 c-sharp/MessageHandlers/MessageHandlerResponse.cs
 rename c-sharp/{Data/RequestReturn.cs => MessageHandlers/ResponseToRequest.cs} (58%)
 rename c-sharp/{Web => MessageTransports}/PapiClient.cs (50%)
 create mode 100644 c-sharp/Messages/Message.cs
 create mode 100644 c-sharp/Messages/MessageClientConnect.cs
 create mode 100644 c-sharp/Messages/MessageEvent.cs
 create mode 100644 c-sharp/Messages/MessageInitClient.cs
 create mode 100644 c-sharp/Messages/MessageRequest.cs
 create mode 100644 c-sharp/Messages/MessageResponse.cs
 create mode 100644 c-sharp/Messages/MessageType.cs
 create mode 100644 c-sharp/Messages/NetworkConnectorInfo.cs
 create mode 100644 c-sharp/Messages/README.md
 create mode 100644 c-sharp/Messages/RequestType.cs
```
</blockquote></details>

The change looks like a diff in github, too, so it definitely looks like an issue with Reviewable.

**Review by FoolRunning — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/102)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @irahopkinson and @tjcouch-sil)

___
*[`c-sharp/MessageTransports/PapiClient.cs` line 1 at r1](https://reviewable.io/reviews/paranext/paranext-core/102#-NRYoCCM7NHahIZm75u7:-NRYzPnl77uzQAElYawy:bozq8k) ([raw file](https://github.com/paranext/paranext-core/blob/5a96237c4c31ee14b826ea3b5098a8f3aec332d0/c-sharp/MessageTransports/PapiClient.cs#L1)):*
<details><summary><i>Previously, lyonsil wrote…</i></summary><blockquote>

The change looks like a diff in github, too, so it definitely looks like an issue with Reviewable.
</blockquote></details>

Sure enough. I should have checked that first.

**Review by irahopkinson — CHANGES_REQUESTED** [review]
Looking good, just one question.

> Reviewed 23 of 23 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/102#-:-NR_QQfcAPpv6H7YgVQa:bnx5lot)* status: all files reviewed, 1 unresolved discussion (waiting on @lyonsil and @tjcouch-sil)

___
*[`c-sharp/Program.cs` line 25 at r1](https://reviewable.io/reviews/paranext/paranext-core/102#-NR_5oi98pScoiAcnYea:-NR_5oiACPuYowDs9QdS:b9b31mv) ([raw file](https://github.com/paranext/paranext-core/blob/5a96237c4c31ee14b826ea3b5098a8f3aec332d0/c-sharp/Program.cs#L25)):*
> ```Smalltalk
>             return;
>         }
>         Console.WriteLine("Paranext .NET connected");
> ```

FYI: this is currently logged such that we know it is from the `dotnet data provider` so the extra context that you added is not needed but also not an issue:

___
*[`c-sharp/Program.cs` line 41 at r1](https://reviewable.io/reviews/paranext/paranext-core/102#-NR_7-JFC7qkIbVJcvKR:-NR_7-JFC7qkIbVJcvKS:b-dbaaos) ([raw file](https://github.com/paranext/paranext-core/blob/5a96237c4c31ee14b826ea3b5098a8f3aec332d0/c-sharp/Program.cs#L41)):*
> ```Smalltalk
>         bool result = await connection.RegisterRequestHandler(RequestType.AddOne, RequestAddOne);
>         if (!result)
>             return;
> ```

Sorry I'm not familiar enough with C# threads. What happens to the thread that has been started should we take this early return path? Does it get cleaned up appropriately or does it need to be stopped?

**Review by FoolRunning — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/102)* status: all files reviewed, 1 unresolved discussion (waiting on @irahopkinson and @tjcouch-sil)

___
*[`c-sharp/Program.cs` line 41 at r1](https://reviewable.io/reviews/paranext/paranext-core/102#-NR_7-JFC7qkIbVJcvKR:-NRcFxGR7hHpwt5FJCRl:b-l0w5js) ([raw file](https://github.com/paranext/paranext-core/blob/5a96237c4c31ee14b826ea3b5098a8f3aec332d0/c-sharp/Program.cs#L41)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

Sorry I'm not familiar enough with C# threads. What happens to the thread that has been started should we take this early return path? Does it get cleaned up appropriately or does it need to be stopped?
</blockquote></details>

Good catch. I'm fairly certain that since the thread is not marked as being a background thread and has already been started, the thread will continue to run, keeping the process from exiting until the connection is forcibly closed by the server (which will finally end the thread).

**Review by lyonsil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/102)* status: all files reviewed, 1 unresolved discussion (waiting on @irahopkinson and @tjcouch-sil)

___
*[`c-sharp/Program.cs` line 41 at r1](https://reviewable.io/reviews/paranext/paranext-core/102#-NR_7-JFC7qkIbVJcvKR:-NRcQmpyEbRYrROPKekV:b-fuwc56) ([raw file](https://github.com/paranext/paranext-core/blob/5a96237c4c31ee14b826ea3b5098a8f3aec332d0/c-sharp/Program.cs#L41)):*
<details><summary><i>Previously, FoolRunning (Tim Steenwyk) wrote…</i></summary><blockquote>

Good catch. I'm fairly certain that since the thread is not marked as being a background thread and has already been started, the thread will continue to run, keeping the process from exiting until the connection is forcibly closed by the server (which will finally end the thread).
</blockquote></details>

The thread was started in `Program.cs` with the following code:
```
        Thread messageHandlingThread =
            new(
                new ThreadStart(async () =>
                {
                    await connection.HandleMessages();
                    messageHandlingIsComplete.Set();
                })
            );
```

Once the lambda function returns that was given to the `ThreadStart` object, the thread is complete.  So in this case, once `HandleMessages` returns for any reason, we set the event, and the thread complete.  As Tim mentioned the thread could have been marked as a background thread which would not prevent process termination even if the thread was still active.  That didn't seem necessary here and really might not even be desired.

I should note that I think there is a reasonable chance that who actually owns the thread calling `HandleMessages` should change in the future.  In my experience a more typical pattern with something like `PapiClient` is that you call `Connect()` or `Start()` on the client object, and that client object owns its own threading internally.  Then the owner of the client object calls `Stop()` or `Disconnect()` which will internally shut down whatever additional threading was done.  I was attempting to limit just how much code to change for this PR.  I felt I was probably already over the line for what was expected, and there wasn't any urgent need for more significant changes.  An additional thread was really needed here for what we are building, but putting it into the client would have caused even more changes to `PapiClient.cs` which itself was apparently more than Reviewable could handle without treating it as a new file altogether.

**Review by lyonsil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/102)* status: all files reviewed, 1 unresolved discussion (waiting on @irahopkinson and @tjcouch-sil)

___
*[`c-sharp/Program.cs` line 41 at r1](https://reviewable.io/reviews/paranext/paranext-core/102#-NR_7-JFC7qkIbVJcvKR:-NRcUf9V2yUrBTbmjUzg:b7woov7) ([raw file](https://github.com/paranext/paranext-core/blob/5a96237c4c31ee14b826ea3b5098a8f3aec332d0/c-sharp/Program.cs#L41)):*
<details><summary><i>Previously, lyonsil wrote…</i></summary><blockquote>

The thread was started in `Program.cs` with the following code:
```
        Thread messageHandlingThread =
            new(
                new ThreadStart(async () =>
                {
                    await connection.HandleMessages();
                    messageHandlingIsComplete.Set();
                })
            );
```

Once the lambda function returns that was given to the `ThreadStart` object, the thread is complete.  So in this case, once `HandleMessages` returns for any reason, we set the event, and the thread complete.  As Tim mentioned the thread could have been marked as a background thread which would not prevent process termination even if the thread was still active.  That didn't seem necessary here and really might not even be desired.

I should note that I think there is a reasonable chance that who actually owns the thread calling `HandleMessages` should change in the future.  In my experience a more typical pattern with something like `PapiClient` is that you call `Connect()` or `Start()` on the client object, and that client object owns its own threading internally.  Then the owner of the client object calls `Stop()` or `Disconnect()` which will internally shut down whatever additional threading was done.  I was attempting to limit just how much code to change for this PR.  I felt I was probably already over the line for what was expected, and there wasn't any urgent need for more significant changes.  An additional thread was really needed here for what we are building, but putting it into the client would have caused even more changes to `PapiClient.cs` which itself was apparently more than Reviewable could handle without treating it as a new file altogether.
</blockquote></details>

If you think we should take this a step further, I think what I would propose is something like:
- Move thread ownership into `PapiClient`, including changes to how it connects/disconnects
- Make `PapiClient` disposable which will check for live connections and shut them down if `Dispose` is called.
- Move PapiClient into a `using` block so it gets disposed automatically whenever `Main()` returns for any reason.

**Review by irahopkinson — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/102)* status: all files reviewed, 1 unresolved discussion (waiting on @FoolRunning, @lyonsil, and @tjcouch-sil)

___
*[`c-sharp/Program.cs` line 41 at r1](https://reviewable.io/reviews/paranext/paranext-core/102#-NR_7-JFC7qkIbVJcvKR:-NRdmxck9sUZhdlppDgX:b-nb8f4u) ([raw file](https://github.com/paranext/paranext-core/blob/5a96237c4c31ee14b826ea3b5098a8f3aec332d0/c-sharp/Program.cs#L41)):*
<details><summary><i>Previously, lyonsil wrote…</i></summary><blockquote>

Here is a branch with the changes I mentioned above.  I can add this to the PR if you think it's better to include now.
https://github.com/paranext/paranext-core/commit/e7c5e8192838ffc2494c1f02dedf8fdcf01624a6
</blockquote></details>

I do like that code better. I was thinking of a similiar change for the TS - as in making papi the main service (so I'm biased). I'd check with @FoolRunning first though since he's the C# architect.

**Review by irahopkinson — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/102#-:-NRdxI6dAZalMlvINLf_:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @tjcouch-sil)

___
*[`c-sharp/Program.cs` line 41 at r1](https://reviewable.io/reviews/paranext/paranext-core/102#-NR_7-JFC7qkIbVJcvKR:-NRdxD3c-Rqi-B9LBghm:b20dh0x) ([raw file](https://github.com/paranext/paranext-core/blob/5a96237c4c31ee14b826ea3b5098a8f3aec332d0/c-sharp/Program.cs#L41)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

I do like that code better. I was thinking of a similiar change for the TS - as in making papi the main service (so I'm biased). I'd check with @FoolRunning first though since he's the C# architect.
</blockquote></details>

Will resolve this in a folow up PR.

**Pull request merged**
