### PR TITLE
enable theming for Platform

### PR DESCRIPTION
**Pull request by Sebastian-ubs**
This change is [Reviewable](https://reviewable.io/reviews/paranext/paranext-core/1102)

enable overwriting styles for the currently used MUI Toolbar
grafik

--- 

Platform is now prepared for theming (besides the menus).
1. Platform light
Screenshot 2024-09-06 173215

2. Platform dark
Screenshot 2024-09-06 173801

3. Paratext 10 Studio light (current draft theme)
Screenshot 2024-09-06 173338

4. Paratext 10 Studio dark (current draft theme)
Screenshot 2024-09-06 173448

--- 

⚠️Reviewers please note
- Styles are pulled into the editor with a [hack](https://github.com/paranext/paranext-core/blob/49bfa8a9a55a84d0c32d0bde2851056c5b566065/extensions/src/platform-scripture-editor/src/platform-scripture-editor.web-view.tsx#L186)
- all editor styles for now have to be manually overridden with specific enough css selectors for all different states, so this creates the long list of [overrides](https://github.com/paranext/paranext-core/blob/49bfa8a9a55a84d0c32d0bde2851056c5b566065/extensions/src/platform-scripture-editor/src/_editor-overrides.scss). Be aware that a) this can easily break on changes, b) there might be gaps overlooked, c) in case we decide to deviate from the Shadcn styles those have to be revisited again.
- linting does not want to allow to commit any `-webkit-` css property [&rarr; Discord](https://discord.com/channels/1064938364597436416/1281654058486333606). Maybe this can lead to future unintended breaking of the icons.
- The Paratext 10 Style class is supposed to be patched over in [theme.tsx](https://github.com/paranext/paranext-core/blob/49bfa8a9a55a84d0c32d0bde2851056c5b566065/src/renderer/theme.tsx#L1)
- Menus are unchanged for now
- The electron window itself is unchanged for now
- BCV is not yet dark mode ready. It is fixed in https://github.com/paranext/paranext-core/pull/1124

### CODE REVIEW

**Comment by Sebastian-ubs** [comment]
Thank you Ira, yes it was intentional: not much change, just to make the existing toolbar themeable. A preparation to be able to apply the theme globally.

**Comment by Sebastian-ubs** [comment]
*[`lib/platform-bible-react/src/preview/pages/layouts/toolbar.layout.component.tsx` line 7 at r1](https://reviewable.io/reviews/paranext/paranext-core/1102#-O5oLMaF89IccDvf4Nf7:-O5qpjVb8v2YANI_kEWj:bbna4fh) ([raw file](https://github.com/paranext/paranext-core/blob/fb173d3d27b3e4c922e4df6b24758d66b81273c3/lib/platform-bible-react/src/preview/pages/layouts/toolbar.layout.component.tsx#L7)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

nit this can be declared outside the component function. Saves React re-declaring every render.
</blockquote></details>

Thank you. Good to know.
How about the state declaration. Should it also go outside?

**Review by irahopkinson — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/1102)* status: all files reviewed, 1 unresolved discussion (waiting on @Sebastian-ubs)

___
*[`lib/platform-bible-react/src/preview/pages/layouts/toolbar.layout.component.tsx` line 7 at r1](https://reviewable.io/reviews/paranext/paranext-core/1102#-O5oLMaF89IccDvf4Nf7:-O5tEtMA7OCSGFf7Xu4X:b-bjg3gt) ([raw file](https://github.com/paranext/paranext-core/blob/fb173d3d27b3e4c922e4df6b24758d66b81273c3/lib/platform-bible-react/src/preview/pages/layouts/toolbar.layout.component.tsx#L7)):*
<details><summary><i>Previously, Sebastian-ubs wrote…</i></summary><blockquote>

Thank you. Good to know.
How about the state declaration. Should it also go outside?
</blockquote></details>

The state declaration must stay inside the component function since `useState` is a React function. However it is clever and if `defaultScrRef` is declared outside the component function then it knows it can't change and will only update `scrRef` once on initialize.

**Comment by Sebastian-ubs** [comment]
*[`lib/platform-bible-react/src/preview/pages/layouts/toolbar.layout.component.tsx` line 7 at r1](https://reviewable.io/reviews/paranext/paranext-core/1102#-O5oLMaF89IccDvf4Nf7:-O67EwvUBlNlTOczaZaQ:bb7f2mf) ([raw file](https://github.com/paranext/paranext-core/blob/fb173d3d27b3e4c922e4df6b24758d66b81273c3/lib/platform-bible-react/src/preview/pages/layouts/toolbar.layout.component.tsx#L7)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

The state declaration must stay inside the component function since `useState` is a React function. However it is clever and if `defaultScrRef` is declared outside the component function then it knows it can't change and will only update `scrRef` once on initialize.
</blockquote></details>

done

**Review by rolfheij-sil — APPROVED** [review]
Looks impressive!

> Reviewed 3 of 8 files at r1, 16 of 16 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/1102#-:-O6RNPSmAWOhzIpnWYmW:b-6z4ps9)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Review by Sebastian-ubs — COMMENTED** [review]
thank you :-D

> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/1102#-:-O6RUT8q2jPJId0AZzh7:b-62odgr)* status: all files reviewed, 4 unresolved discussions (waiting on @tjcouch-sil)

___
*[`extensions/src/platform-scripture-editor/src/platform-scripture-editor.web-view.tsx` line 187 at r2](https://reviewable.io/reviews/paranext/paranext-core/1102#-O6ROhPX7Ca89wOl0Qys:-O6RUWOwApRRUFxTZO1f:bml6xdk) ([raw file](https://github.com/paranext/paranext-core/blob/6478b24a2f0155fda492308f788371446d7da11c/extensions/src/platform-scripture-editor/src/platform-scripture-editor.web-view.tsx#L187)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

:joy: I wondered how you would do this! Clever :) hopefully we can make this easier and possibly even automatic in the future haha
</blockquote></details>

yep. In case you have an idea, let me know. In theory pulling in the style sheet should be enough if we know the url.
___
*[`src/renderer/theme.tsx` line 1 at r2](https://reviewable.io/reviews/paranext/paranext-core/1102#-O6RPUS7CmjqWFTYmTAP:-O6RUhyzE0-PbKzUOMtE:b-h1mevk) ([raw file](https://github.com/paranext/paranext-core/blob/6478b24a2f0155fda492308f788371446d7da11c/src/renderer/theme.tsx#L1)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

Is default theme supposed to be dark? I suggest maybe we should wait to set dark as default till we have the BC control themed properly. Or are you planning to do that shortly (before demo)?
</blockquote></details>

Yes, I am hoping to fix the bc control before the demo
___
*[`src/renderer/theme.tsx` line  at r2](https://reviewable.io/reviews/paranext/paranext-core/1102#-O6RPMhy2pbwigrqAneV:-O6RUgHtDVTp-rzjUC3o:b-lu5rg2) ([raw file](https://github.com/paranext/paranext-core/blob/6478b24a2f0155fda492308f788371446d7da11c/src/renderer/theme.tsx#L)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

I believe this file should be `theme.ts`, right? No "x" at the end since it isn't a React file
</blockquote></details>

will change that
___
*[`src/renderer/components/docking/dock-layout-wrapper.component.scss` line 210 at r2](https://reviewable.io/reviews/paranext/paranext-core/1102#-O6RQlwMCl1XYLkTHQ1i:-O6RUovy-W_PPL-yBfoh:b-1t5pb0) ([raw file](https://github.com/paranext/paranext-core/blob/6478b24a2f0155fda492308f788371446d7da11c/src/renderer/components/docking/dock-layout-wrapper.component.scss#L210)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

Is the close button invisible now? How will users find it to click it? Does it show up on hovering over the tab or something?
</blockquote></details>

No. It is kind of gray. I was not finding the right value for short here.
___
*[`src/renderer/services/web-view.service-host.ts` line 947 at r2](https://reviewable.io/reviews/paranext/paranext-core/1102#-O6RR4M69AXKgup-woMu:-O6RV4KFEfgbbuh9gnYI:b-qt3po1) ([raw file](https://github.com/paranext/paranext-core/blob/6478b24a2f0155fda492308f788371446d7da11c/src/renderer/services/web-view.service-host.ts#L947)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

This body needs to have `class="${THEME}"` as well, right? Or I guess probably the scrollbar styles and the theme class need to be inserted into the string regardless of if it includes `<html`, so it should be inserted programmatically after this line.
</blockquote></details>

I guess the second one, yes. Will have a look.

**Review by Sebastian-ubs — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/1102)* status: 17 of 19 files reviewed, 1 unresolved discussion (waiting on @rolfheij-sil and @tjcouch-sil)

___
*[`src/renderer/components/docking/dock-layout-wrapper.component.scss` line 210 at r2](https://reviewable.io/reviews/paranext/paranext-core/1102#-O6RQlwMCl1XYLkTHQ1i:-O6Rh6trEtEPwof6wZZn:b43nf2v) ([raw file](https://github.com/paranext/paranext-core/blob/6478b24a2f0155fda492308f788371446d7da11c/src/renderer/components/docking/dock-layout-wrapper.component.scss#L210)):*
<details><summary><i>Previously, Sebastian-ubs wrote…</i></summary><blockquote>

No. It is kind of gray. I was not finding the right value for short here.
</blockquote></details>

done. found and fixed it
___
*[`src/renderer/services/web-view.service-host.ts` line 947 at r2](https://reviewable.io/reviews/paranext/paranext-core/1102#-O6RR4M69AXKgup-woMu:-O6RhAkr-v5IuZZL5-x2:bbtkgfr) ([raw file](https://github.com/paranext/paranext-core/blob/6478b24a2f0155fda492308f788371446d7da11c/src/renderer/services/web-view.service-host.ts#L947)):*
<details><summary><i>Previously, Sebastian-ubs wrote…</i></summary><blockquote>

I guess the second one, yes. Will have a look.
</blockquote></details>

To be honest I don't know at which point in time / code this can be programmatically added. This place looks like it is only creating an html string, not a dom tree, so nothing to interact with like ```javascript
document.head.appendChild(styleSheet)
```
At this place I think it would only be find and replace on the raw html string, which seems not nice, does it?
```

___
*[`src/renderer/theme.tsx` line 1 at r2](https://reviewable.io/reviews/paranext/paranext-core/1102#-O6RPUS7CmjqWFTYmTAP:-O6Rh3vKAmqnQpVek6Gt:b-1802tj) ([raw file](https://github.com/paranext/paranext-core/blob/6478b24a2f0155fda492308f788371446d7da11c/src/renderer/theme.tsx#L1)):*
<details><summary><i>Previously, Sebastian-ubs wrote…</i></summary><blockquote>

Yes, I am hoping to fix the bc control before the demo
</blockquote></details>

done (separate pr)
___
*[`src/renderer/theme.tsx` line  at r2](https://reviewable.io/reviews/paranext/paranext-core/1102#-O6RPMhy2pbwigrqAneV:-O6Rh5ye5rOpXfJctXb8:bb7f2mf) ([raw file](https://github.com/paranext/paranext-core/blob/6478b24a2f0155fda492308f788371446d7da11c/src/renderer/theme.tsx#L)):*
<details><summary><i>Previously, Sebastian-ubs wrote…</i></summary><blockquote>

will change that
</blockquote></details>

done

**Review by tjcouch-sil — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/1102)* status: all files reviewed, 2 unresolved discussions (waiting on @Sebastian-ubs)

___
*[`extensions/src/platform-scripture-editor/src/platform-scripture-editor.web-view.tsx` line 187 at r2](https://reviewable.io/reviews/paranext/paranext-core/1102#-O6ROhPX7Ca89wOl0Qys:-O6RcfRS7ulzVDTILHzx:bw75t40) ([raw file](https://github.com/paranext/paranext-core/blob/6478b24a2f0155fda492308f788371446d7da11c/extensions/src/platform-scripture-editor/src/platform-scripture-editor.web-view.tsx#L187)):*
<details><summary><i>Previously, Sebastian-ubs wrote…</i></summary><blockquote>

yep. In case you have an idea, let me know. In theory pulling in the style sheet should be enough if we know the url.
</blockquote></details>

I don't have any good ideas right off the top of my head. Hopefully another time :)
___
*[`src/renderer/components/docking/dock-layout-wrapper.component.scss` line 210 at r2](https://reviewable.io/reviews/paranext/paranext-core/1102#-O6RQlwMCl1XYLkTHQ1i:-O6Rj2c-E3M429fWLaq2:b-ucfknh) ([raw file](https://github.com/paranext/paranext-core/blob/6478b24a2f0155fda492308f788371446d7da11c/src/renderer/components/docking/dock-layout-wrapper.component.scss#L210)):*
<details><summary><i>Previously, Sebastian-ubs wrote…</i></summary><blockquote>

done. found and fixed it
</blockquote></details>

Thanks!
___
*[`src/renderer/services/web-view.service-host.ts` line 947 at r2](https://reviewable.io/reviews/paranext/paranext-core/1102#-O6RR4M69AXKgup-woMu:-O6Rj85c7dck2tDWgw-0:b-jzefv1) ([raw file](https://github.com/paranext/paranext-core/blob/6478b24a2f0155fda492308f788371446d7da11c/src/renderer/services/web-view.service-host.ts#L947)):*
<details><summary><i>Previously, Sebastian-ubs wrote…</i></summary><blockquote>

To be honest I don't know at which point in time / code this can be programmatically added. This place looks like it is only creating an html string, not a dom tree, so nothing to interact with like ```javascript
document.head.appendChild(styleSheet)
```
At this place I think it would only be find and replace on the raw html string, which seems not nice, does it?
```

</blockquote></details>

Indeed, it's not nice to find/replace on the raw html string, but that's just what we're doing right now. There is an issue to convert all this to use DOMParser instead, which would be a nice solution, but that's more work that is probably best left to another issue.

I'd be glad to pair on this if you'd like a hand :)
___
*[`src/renderer/theme.tsx` line 1 at r2](https://reviewable.io/reviews/paranext/paranext-core/1102#-O6RPUS7CmjqWFTYmTAP:-O6RckSK2sWq3Xz7ftzT:b7fg4b3) ([raw file](https://github.com/paranext/paranext-core/blob/6478b24a2f0155fda492308f788371446d7da11c/src/renderer/theme.tsx#L1)):*
<details><summary><i>Previously, Sebastian-ubs wrote…</i></summary><blockquote>

done (separate pr)
</blockquote></details>

Awesome!! :) thanks!

I pulled your branch down and took a quick look around. I found a few things that are not working with dark theme, and I'm a bit worried about continually finding a bunch of stuff and scrambling to fix before the demo. We may even not find some things before the demo, which would definitely be worse.

Empty checkboxes on the multi-project-select dialog don't show up:


Empty radio button doesn't show up, invisible text on the configure checks webview:


Text collection seems to be completely unaffected by theming for some reason:



I think maybe if we carefully comb through the whole UI and/or run through the entire final script (I don't think we have a final script yet tbh), maybe we can make it happen. Just feels a bit scary with the demo so close. Maybe instead we could pair sometime on making a setting that lets you adjust it and tell people it's there but still in progress...? :)
___
*[`src/renderer/theme.tsx` line  at r2](https://reviewable.io/reviews/paranext/paranext-core/1102#-O6RPMhy2pbwigrqAneV:-O6Rj_dD6J0DWevDv-yR:b-ucfknh) ([raw file](https://github.com/paranext/paranext-core/blob/6478b24a2f0155fda492308f788371446d7da11c/src/renderer/theme.tsx#L)):*
<details><summary><i>Previously, Sebastian-ubs wrote…</i></summary><blockquote>

done
</blockquote></details>

Thanks!

**Review by Sebastian-ubs — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/1102)* status: 10 of 21 files reviewed, 2 unresolved discussions (waiting on @irahopkinson, @rolfheij-sil, and @tjcouch-sil)

___
*[`src/renderer/services/web-view.service-host.ts` line 947 at r2](https://reviewable.io/reviews/paranext/paranext-core/1102#-O6RR4M69AXKgup-woMu:-O6WDwE7BNQ5eyzjQGEU:b-1o6vyb) ([raw file](https://github.com/paranext/paranext-core/blob/6478b24a2f0155fda492308f788371446d7da11c/src/renderer/services/web-view.service-host.ts#L947)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

Indeed, it's not nice to find/replace on the raw html string, but that's just what we're doing right now. There is an issue to convert all this to use DOMParser instead, which would be a nice solution, but that's more work that is probably best left to another issue.

I'd be glad to pair on this if you'd like a hand :)
</blockquote></details>

I have NOT worked on this one. If you like you can, we can together or do it as a separate PR
___
*[`src/renderer/theme.tsx` line 1 at r2](https://reviewable.io/reviews/paranext/paranext-core/1102#-O6RPUS7CmjqWFTYmTAP:-O6WDUXO5i0P_E6heO-u:b-c1hu9f) ([raw file](https://github.com/paranext/paranext-core/blob/6478b24a2f0155fda492308f788371446d7da11c/src/renderer/theme.tsx#L1)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

Awesome!! :) thanks!

I pulled your branch down and took a quick look around. I found a few things that are not working with dark theme, and I'm a bit worried about continually finding a bunch of stuff and scrambling to fix before the demo. We may even not find some things before the demo, which would definitely be worse.

Empty checkboxes on the multi-project-select dialog don't show up:


Empty radio button doesn't show up, invisible text on the configure checks webview:


Text collection seems to be completely unaffected by theming for some reason:



I think maybe if we carefully comb through the whole UI and/or run through the entire final script (I don't think we have a final script yet tbh), maybe we can make it happen. Just feels a bit scary with the demo so close. Maybe instead we could pair sometime on making a setting that lets you adjust it and tell people it's there but still in progress...? :)
</blockquote></details>

Done. I fixed all of them, but switched back to light mode. we can easily switch to dark whenever we like to.
PR for text collection is in https://github.com/paranext/paratext-bible-extensions/pull/34

**Review by rolfheij-sil — DISMISSED** [review]
> Reviewed 1 of 2 files at r3, 1 of 2 files at r4, 11 of 11 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/1102)* status: all files reviewed, 2 unresolved discussions (waiting on @tjcouch-sil)

**Review by tjcouch-sil — COMMENTED** [review]
There is a weird problem I found where flex divs have double scroll buttons, so I fixed that. I get the feeling that this is a "feature", but I don't think we intend for this to happen.

Example:

Before:


After:


> Reviewed 11 of 11 files at r5.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/1102#-:-O6WnnS16RMcCHfw-L5r:b-153ikk)* status: 20 of 21 files reviewed, all discussions resolved (waiting on @rolfheij-sil)

___
*[`src/renderer/services/web-view.service-host.ts` line 947 at r2](https://reviewable.io/reviews/paranext/paranext-core/1102#-O6RR4M69AXKgup-woMu:-O6WnVZH4p1BKh2H3hvf:b-4978ne) ([raw file](https://github.com/paranext/paranext-core/blob/6478b24a2f0155fda492308f788371446d7da11c/src/renderer/services/web-view.service-host.ts#L947)):*
<details><summary><i>Previously, Sebastian-ubs wrote…</i></summary><blockquote>

I have NOT worked on this one. If you like you can, we can together or do it as a separate PR
</blockquote></details>

I took a note to work on this bit another time. If you happen to get to it first, feel free to submit a PR :)
___
*[`src/renderer/theme.tsx` line 1 at r2](https://reviewable.io/reviews/paranext/paranext-core/1102#-O6RPUS7CmjqWFTYmTAP:-O6WJLWt8bagmoJLsFa-:b-ybi3fg) ([raw file](https://github.com/paranext/paranext-core/blob/6478b24a2f0155fda492308f788371446d7da11c/src/renderer/theme.tsx#L1)):*
<details><summary><i>Previously, Sebastian-ubs wrote…</i></summary><blockquote>

Done. I fixed all of them, but switched back to light mode. we can easily switch to dark whenever we like to.
PR for text collection is in https://github.com/paranext/paratext-bible-extensions/pull/34
</blockquote></details>

A W E S O M E. Thank you, Sebastian. You rock!

**Review by rolfheij-sil — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/1102#-:-O6X0uqtCnGFcJlBHtIg:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Review by tjcouch-sil — APPROVED** [review]
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/1102)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Pull request merged**
