### PR TITLE
Implement WebView panels and floats

### PR DESCRIPTION
**Pull request by irahopkinson**
Commits
- Improve layout options on addWebView
- Implement float layout
- Stopped retrying addWebView on actual errors
- Implement panel layout
- Improve tests and DX on error
- Fix `rc-dock` types

Features
- Closed WebView tabs will come back on a restart.
- When adding a WebView, a layout can be specified as **tab** (default), **float** or **panel**.
- Better DX experience since `addWebView` errors show as errors in the browser console.
- Added [ts-mockito](https://github.com/NagRock/ts-mockito) mocking library.
- Added a way to extend and fix `.d.ts` files from packages. See the `src/@types` folder.

The commits have be organised into feature changes so it may be useful to review the commits separately to speedup understanding of the changes.

- - -
This change is [Reviewable](https://reviewable.io/reviews/paranext/paranext-core/173)

### CODE REVIEW

**Review by tjcouch-sil — CHANGES_REQUESTED** [review]
> Reviewed 14 of 14 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/173)* status: all files reviewed, 4 unresolved discussions (waiting on @irahopkinson)

___
*[`src/@types/rc-dock.d.ts` line 4 at r3](https://reviewable.io/reviews/paranext/paranext-core/173#-NV-_Esx--0C-yA_Lp9z:-NV-_Esx--0C-yA_LpA-:b-e0g6xb) ([raw file](https://github.com/paranext/paranext-core/blob/52553031e862dfeee97a36670aeb9c7f99fb7d75/src/%40types/rc-dock.d.ts#L4)):*
> ```XML
> import * as Algorithm from 'rc-dock/lib/Algorithm';
> 
> declare module 'rc-dock' {
> ```

Would you mind putting a comment in here explaining we are writing over rc-dock types to fix them? And/or make a README.md in this `@types` folder explaining that we can put types in here that overwrite library types
___
*[`src/renderer/log-error.model.ts` line 1 at r3](https://reviewable.io/reviews/paranext/paranext-core/173#-NV-_Y1Z8veorWZUnpyv:-NV-_Y1Z8veorWZUnpyw:b-xjv7fi) ([raw file](https://github.com/paranext/paranext-core/blob/52553031e862dfeee97a36670aeb9c7f99fb7d75/src/renderer/log-error.model.ts#L1)):*
> ```XML
> import logger from '@shared/services/logger.service';
> ```

I think this should be moved to the `shared` folder so anyone can use it
___
*[`src/shared/data/web-view.model.ts` line 77 at r3](https://reviewable.io/reviews/paranext/paranext-core/173#-NV-lGPW3GuQsQWfemXp:-NV-lGPW3GuQsQWfemXq:b65dnbx) ([raw file](https://github.com/paranext/paranext-core/blob/52553031e862dfeee97a36670aeb9c7f99fb7d75/src/shared/data/web-view.model.ts#L77)):*
> ```XML
> export interface FloatLayout {
>   type: 'float';
>   floatSize: { width: number; height: number };
> ```

Should this be optional to make it easier to use? Feels like there may be some reasonable defaults.
___
*[`src/shared/data/web-view.model.ts` line 95 at r3](https://reviewable.io/reviews/paranext/paranext-core/173#-NV-lEAl6JBwaybTrBCU:-NV-lEAm0pKE85Xr1Ls4:b-dykp9u) ([raw file](https://github.com/paranext/paranext-core/blob/52553031e862dfeee97a36670aeb9c7f99fb7d75/src/shared/data/web-view.model.ts#L95)):*
> ```XML
> interface PanelLayout {
>   type: 'panel';
>   direction: PanelDirection;
> ```

Should this be optional to make it easier to use? Feels like there may be a reasonable default. I think Paratext by default opens a new panel to the right of existing panels

**Review by tjcouch-sil — COMMENTED** [review]
Thank you for the great work on this! Just a few little things.

> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/173#-:-NV-mWTN8j_LCHS96jKq:b8s04ie)* status: all files reviewed, 4 unresolved discussions (waiting on @irahopkinson)

**Review by irahopkinson — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/173)* status: 9 of 15 files reviewed, 1 unresolved discussion (waiting on @tjcouch-sil)

___
*[`src/@types/rc-dock.d.ts` line 4 at r3](https://reviewable.io/reviews/paranext/paranext-core/173#-NV-_Esx--0C-yA_Lp9z:-NV1sdzx354r9JcExHvU:bc582wd) ([raw file](https://github.com/paranext/paranext-core/blob/52553031e862dfeee97a36670aeb9c7f99fb7d75/src/%40types/rc-dock.d.ts#L4)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

Would you mind putting a comment in here explaining we are writing over rc-dock types to fix them? And/or make a README.md in this `@types` folder explaining that we can put types in here that overwrite library types
</blockquote></details>

Done. Good idea - I added a `README.md`.
___
*[`src/renderer/log-error.model.ts` line 1 at r3](https://reviewable.io/reviews/paranext/paranext-core/173#-NV-_Y1Z8veorWZUnpyv:-NV1supS72aHx66vmU8o:b-1vz4cp) ([raw file](https://github.com/paranext/paranext-core/blob/52553031e862dfeee97a36670aeb9c7f99fb7d75/src/renderer/log-error.model.ts#L1)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

I think this should be moved to the `shared` folder so anyone can use it
</blockquote></details>

I did think about that but I made it only available for the renderer because it doubles up the messages in the logs and wouldn't want that to be happening generally on a throw - only in those cases that we want to alert the developer in the browser console, i.e. renderer only. I've added a comment to clarify this.
___
*[`src/shared/data/web-view.model.ts` line 77 at r3](https://reviewable.io/reviews/paranext/paranext-core/173#-NV-lGPW3GuQsQWfemXp:-NV1uv6w-eoSWdncN7gZ:b-896fix) ([raw file](https://github.com/paranext/paranext-core/blob/52553031e862dfeee97a36670aeb9c7f99fb7d75/src/shared/data/web-view.model.ts#L77)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

Should this be optional to make it easier to use? Feels like there may be some reasonable defaults.
</blockquote></details>

Done.
___
*[`src/shared/data/web-view.model.ts` line 95 at r3](https://reviewable.io/reviews/paranext/paranext-core/173#-NV-lEAl6JBwaybTrBCU:-NV1uxYD7wxb-fb-SB2p:b-896fix) ([raw file](https://github.com/paranext/paranext-core/blob/52553031e862dfeee97a36670aeb9c7f99fb7d75/src/shared/data/web-view.model.ts#L95)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

Should this be optional to make it easier to use? Feels like there may be a reasonable default. I think Paratext by default opens a new panel to the right of existing panels
</blockquote></details>

Done.

**Review by tjcouch-sil — COMMENTED** [review]
> Reviewed 6 of 6 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/173)* status: all files reviewed, 1 unresolved discussion (waiting on @irahopkinson)

___
*[`src/renderer/log-error.model.ts` line 1 at r3](https://reviewable.io/reviews/paranext/paranext-core/173#-NV-_Y1Z8veorWZUnpyv:-NV59qEE5YHrENkPgzdi:b-l2gbi7) ([raw file](https://github.com/paranext/paranext-core/blob/52553031e862dfeee97a36670aeb9c7f99fb7d75/src/renderer/log-error.model.ts#L1)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

I did think about that but I made it only available for the renderer because it doubles up the messages in the logs and wouldn't want that to be happening generally on a throw - only in those cases that we want to alert the developer in the browser console, i.e. renderer only. I've added a comment to clarify this.
</blockquote></details>

(Changed to discussing, not blocking, since I don't actually understand what's going on) I don't get it. If someone uses `LogError`, it should log the error in the logs and in the console then let the code handle the error as normal. Meaning `LogError` is expected to log the error, so people who want to make sure their error is logged can use it. Then whoever catches the error can do whatever they want. I don't understand why this would be a renderer-only mechanism. Do errors already all get logged to console without anyone running a `logger` function? Or how does this error double up?
___
*[`src/renderer/components/docking/paranext-dock-layout.component.tsx` line 220 at r4](https://reviewable.io/reviews/paranext/paranext-core/173#-NV4tdFV-IiAU5PGsTtg:-NV4tdFV-IiAU5PGsTth:bq0ejok) ([raw file](https://github.com/paranext/paranext-core/blob/0f758516897a2d6a79c33040166c7edeaeb22e1f/src/renderer/components/docking/paranext-dock-layout.component.tsx#L220)):*
> ```XML
>         tab,
>         targetTab?.parent as PanelData,
>         layout.direction ?? DEFAULT_PANEL_DIRECTION,
> ```

Can we make these defaults set as defaults in the `addWebView` function in `web-view.service.ts`? That way, the event itself has the correct information in it no matter where you're listening to the event instead of having to implement defaults everywhere that ingests the event. Though I feel strongly about this point, this is in consideration to future-proofing, not fixing, so this is an optional fix.

**Review by irahopkinson — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/173)* status: 13 of 15 files reviewed, all discussions resolved (waiting on @tjcouch-sil)

___
*[`src/renderer/log-error.model.ts` line 1 at r3](https://reviewable.io/reviews/paranext/paranext-core/173#-NV-_Y1Z8veorWZUnpyv:-NV6wAVQArTSHRSkaAz5:b86fcv5) ([raw file](https://github.com/paranext/paranext-core/blob/52553031e862dfeee97a36670aeb9c7f99fb7d75/src/renderer/log-error.model.ts#L1)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

(Changed to discussing, not blocking, since I don't actually understand what's going on) I don't get it. If someone uses `LogError`, it should log the error in the logs and in the console then let the code handle the error as normal. Meaning `LogError` is expected to log the error, so people who want to make sure their error is logged can use it. Then whoever catches the error can do whatever they want. I don't understand why this would be a renderer-only mechanism. Do errors already all get logged to console without anyone running a `logger` function? Or how does this error double up?
</blockquote></details>

E.g. when testing an `unknown layout type`, I get an error in the browser console from the renderer which is what we want to improve the DX:


But we also get that error from the rendered and another one from the extension host for the same throw showing up in the logs:


I was trying to avoid doubling up errors in the logs except from the renderer in cases like this. I'm inferrring that you are saying that won't happen if we use `LogError` outside the renderer or even perhaps outside of an extension from the renderer?
___
*[`src/renderer/components/docking/paranext-dock-layout.component.tsx` line 220 at r4](https://reviewable.io/reviews/paranext/paranext-core/173#-NV4tdFV-IiAU5PGsTtg:-NV706HS-_B-1E_ZJsSr:b-896fix) ([raw file](https://github.com/paranext/paranext-core/blob/0f758516897a2d6a79c33040166c7edeaeb22e1f/src/renderer/components/docking/paranext-dock-layout.component.tsx#L220)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

Can we make these defaults set as defaults in the `addWebView` function in `web-view.service.ts`? That way, the event itself has the correct information in it no matter where you're listening to the event instead of having to implement defaults everywhere that ingests the event. Though I feel strongly about this point, this is in consideration to future-proofing, not fixing, so this is an optional fix.
</blockquote></details>

Done.

**Review by irahopkinson — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/173)* status: 12 of 15 files reviewed, all discussions resolved (waiting on @tjcouch-sil)

___
*[`src/renderer/log-error.model.ts` line 1 at r3](https://reviewable.io/reviews/paranext/paranext-core/173#-NV-_Y1Z8veorWZUnpyv:-NV7426p4w_pSk7LitDp:b-ubh1bu) ([raw file](https://github.com/paranext/paranext-core/blob/52553031e862dfeee97a36670aeb9c7f99fb7d75/src/renderer/log-error.model.ts#L1)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

E.g. when testing an `unknown layout type`, I get an error in the browser console from the renderer which is what we want to improve the DX:


But we also get that error from the rendered and another one from the extension host for the same throw showing up in the logs:


I was trying to avoid doubling up errors in the logs except from the renderer in cases like this. I'm inferrring that you are saying that won't happen if we use `LogError` outside the renderer or even perhaps outside of an extension from the renderer?
</blockquote></details>

I did some testing of using `LogError` in various other places and see that my assumptions were wrong. It only doubles up in the renderer from an extension because both the renderer and the extension host are reporting it to the logs. It's moved into the `shared` folder now. Sorry I got that wrong and thanks for noticing.

**Review by tjcouch-sil — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/173#-:-NVABk-s70qfYne6wizD:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @irahopkinson)

**Review by lyonsil — APPROVED** [review]
> Reviewed 8 of 14 files at r3, 4 of 6 files at r4, 2 of 3 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/173)* status: all files reviewed, 1 unresolved discussion (waiting on @irahopkinson)

___
*[`src/renderer/components/docking/paranext-dock-layout.component.tsx` line 136 at r6](https://reviewable.io/reviews/paranext/paranext-core/173#-NVAXaWq1YMBj74vK7Od:-NVAXaWq1YMBj74vK7Oe:bhsld9h) ([raw file](https://github.com/paranext/paranext-core/blob/509e70be52802f9b3f69a788e7534e714b0843c7/src/renderer/components/docking/paranext-dock-layout.component.tsx#L136)):*
> ```XML
>  * @returns `true` if its a tab or `false` otherwise.
>  */
> function isTab(tab: PanelData | TabData | BoxData | undefined): boolean {
> ```

Is there a property that only exists on TabData?  I see `title` on TabData and nowhere else based on a (potentially naive) search online - https://github.com/ticlo/rc-dock/blob/master/src/DockData.ts#L196.  The `if` statement below looks kind of fragile.

**Comment by irahopkinson** [comment]
*[`src/renderer/components/docking/paranext-dock-layout.component.tsx` line 136 at r6](https://reviewable.io/reviews/paranext/paranext-core/173#-NVAXaWq1YMBj74vK7Od:-NVC5EKr5FMTVFc1jc8V:bu7q5du) ([raw file](https://github.com/paranext/paranext-core/blob/509e70be52802f9b3f69a788e7534e714b0843c7/src/renderer/components/docking/paranext-dock-layout.component.tsx#L136)):*
<details><summary><i>Previously, lyonsil wrote…</i></summary><blockquote>

Is there a property that only exists on TabData?  I see `title` on TabData and nowhere else based on a (potentially naive) search online - https://github.com/ticlo/rc-dock/blob/master/src/DockData.ts#L196.  The `if` statement below looks kind of fragile.
</blockquote></details>

I did the same search as you but somehow missed both `title` and `content` on `TabData`. I'm fixing in a follow-up PR. Thanks for spotting that.

**Pull request merged**
