### PR TITLE
738  Implement falling back to English if a localized string doesn't exist for a language

### PR DESCRIPTION
**Pull request by katherinejensen00**
I am experimenting with doing multiple smaller PR's during the course of a larger task. Here is one to accomplish the first checkbox of 738 to default to the English localization if a localization can't be found for a word in a valid language. (If the language submitted is invalid, there is probably a bigger problem that needs to be addressed and not covered up so an error is currently still thrown in that case which is also how the built in JS internationalization library handles that). I also didn't change the testing file to .ts yet because that made it hard to see the new changes. I will convert it after this pull request is merged.

- - -
This change is [Reviewable](https://reviewable.io/reviews/paranext/paranext-core/763)

### CODE REVIEW

**Review by lyonsil — CHANGES_REQUESTED** [review]
Smaller PRs are definitely easier to review!  I see a couple of small things to consider.

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/763#-:-NqYh8QT37iQi0tYvUwc:b-sawsaw)* status: all files reviewed, 2 unresolved discussions (waiting on @katherinejensen00)

___
*[`src/main/services/localization.service-host.ts` line 24 at r1](https://reviewable.io/reviews/paranext/paranext-core/763#-NqYfBgWCIlxAhKwqICs:-NqYfBgWCIlxAhKwqICt:brr9g5l) ([raw file](https://github.com/paranext/paranext-core/blob/12f40f26d1cb170f0ab41c03963f5b9dd27d40c3/src/main/services/localization.service-host.ts#L24)):*
> ```XML
> }
> 
> function validateLanguageCode(languageCode: string): boolean {
> ```

minor nit: For functions that return booleans, I think we try to name functions `isX()` so the usage looks like `if (isX()) doSomething();`.  Sometimes we might want a function that just throws if there is a problem, and those functions would be more likely named `validateX()`.
___
*[`src/main/services/localization.service-host.ts` line 26 at r1](https://reviewable.io/reviews/paranext/paranext-core/763#-NqYfdZwCDhO6Ck05ivE:-NqYfdZwCDhO6Ck05ivF:b-can4yt) ([raw file](https://github.com/paranext/paranext-core/blob/12f40f26d1cb170f0ab41c03963f5b9dd27d40c3/src/main/services/localization.service-host.ts#L26)):*
> ```XML
> function validateLanguageCode(languageCode: string): boolean {
>   const match = languageCode.match(LANGUAGE_CODE_REGEX) ?? '';
>   return LANGUAGE_CODE_REGEX.test(languageCode) && match[0].length === languageCode.length;
> ```

This is using the regex twice when it really only needs to be used once.  You could simplify this down to:
```typescript
  const match = languageCode.match(LANGUAGE_CODE_REGEX);
  return match && match[0].length === languageCode.length;
```

**Review by katherinejensen00 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/763)* status: all files reviewed, 2 unresolved discussions (waiting on @lyonsil)

___
*[`src/main/services/localization.service-host.ts` line 24 at r1](https://reviewable.io/reviews/paranext/paranext-core/763#-NqYfBgWCIlxAhKwqICs:-NqYiePY9X93Qsctdzgm:b-ay3e70) ([raw file](https://github.com/paranext/paranext-core/blob/12f40f26d1cb170f0ab41c03963f5b9dd27d40c3/src/main/services/localization.service-host.ts#L24)):*
<details><summary><i>Previously, lyonsil (Matt Lyons) wrote…</i></summary><blockquote>

minor nit: For functions that return booleans, I think we try to name functions `isX()` so the usage looks like `if (isX()) doSomething();`.  Sometimes we might want a function that just throws if there is a problem, and those functions would be more likely named `validateX()`.
</blockquote></details>

That makes sense. Thank you for explaining that!
___
*[`src/main/services/localization.service-host.ts` line 26 at r1](https://reviewable.io/reviews/paranext/paranext-core/763#-NqYfdZwCDhO6Ck05ivE:-NqYkGilEQADdm40aww3:b-896fix) ([raw file](https://github.com/paranext/paranext-core/blob/12f40f26d1cb170f0ab41c03963f5b9dd27d40c3/src/main/services/localization.service-host.ts#L26)):*
<details><summary><i>Previously, lyonsil (Matt Lyons) wrote…</i></summary><blockquote>

This is using the regex twice when it really only needs to be used once.  You could simplify this down to:
```typescript
  const match = languageCode.match(LANGUAGE_CODE_REGEX);
  return match && match[0].length === languageCode.length;
```
</blockquote></details>

Done.

**Review by lyonsil — DISMISSED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/763#-:-NqYmB7B9mUeuAPlJDQ9:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

___
*[`src/main/services/localization.service-host.ts` line 26 at r1](https://reviewable.io/reviews/paranext/paranext-core/763#-NqYfdZwCDhO6Ck05ivE:-NqYlNyt95VloCxnV_jo:b-o82t2e) ([raw file](https://github.com/paranext/paranext-core/blob/12f40f26d1cb170f0ab41c03963f5b9dd27d40c3/src/main/services/localization.service-host.ts#L26)):*
<details><summary><i>Previously, katherinejensen00 wrote…</i></summary><blockquote>

Done.
</blockquote></details>

This works, but note that [`match`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/match) returns `null` if it fails, so you don't have to explicitly set the value to something else.  You can just take the result of the call and see if it is [truthy](https://developer.mozilla.org/en-US/docs/Glossary/Truthy) instead of explicitly checking against `undefined`.  What you have works, too, so I'm resolving this discussion.  Just providing the other details as an FYI.

**Review by tjcouch-sil — APPROVED** [review]
Thanks for a nice subdivision of the work!

> Reviewed 1 of 2 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/763#-:-NqZZkcd0cyq1o7uz269:b-wc59p6)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Review by tjcouch-sil — DISMISSED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/763#-:-NrGlnRqAoZSYB0hg4Ge:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Comment by katherinejensen00** [comment]
To fix the bug, I moved to a new branch which led to a new pull request so I am closing this one.

**Pull request closed without merging**
