### PR TITLE
fix styles, preview: add and enhance examples

### PR DESCRIPTION
**Pull request by Sebastian-ubs**
Fixes
- fix card, border +input style in pt darkmode
- fix font style in select component

Examples
- add checkbox and select examples
- fix margin on tab examples page
- add empty inventory table to the pt section
- improve alert and card examples
- remove outdated comment in dropdown example
- add checkboxes to data table example
- comment that Slider and Switch examples wrongly use the MUI component

- - -
This change is [Reviewable](https://reviewable.io/reviews/paranext/paranext-core/1019)

grafik

grafik

grafik

grafik

### CODE REVIEW

**Review by rolfheij-sil — CHANGES_REQUESTED** [review]
Nice work :)

> Reviewed 20 of 21 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/1019#-:-O2BUBld5zPxNOfkApNl:b90cghs)* status: 20 of 21 files reviewed, 4 unresolved discussions (waiting on @Sebastian-ubs)

___
*[`lib/platform-bible-react/src/preview/components/basics/slider.examples.component.tsx` line 8 at r1](https://reviewable.io/reviews/paranext/paranext-core/1019#-O2BTOYt0Ad49enTFkjN:-O2BTOYu4VrUBkiZNEJ4:bzeco6b) ([raw file](https://github.com/paranext/paranext-core/blob/d4eac52c10884c0306adbf528723b7c09235a718/lib/platform-bible-react/src/preview/components/basics/slider.examples.component.tsx#L8)):*
> ```XML
>   return (
>     <>
>       Wrongly using MUI slider right now 😬
> ```

Should we create an issue for swapping the remaining MUI components out for shadcn components?
___
*[`lib/platform-bible-react/src/preview/components/data-sources/data-table-content.tsx` line 2 at r1](https://reviewable.io/reviews/paranext/paranext-core/1019#-O2BTcou1PyGa9v9lFl5:-O2BTcou1PyGa9v9lFl6:bseseiq) ([raw file](https://github.com/paranext/paranext-core/blob/d4eac52c10884c0306adbf528723b7c09235a718/lib/platform-bible-react/src/preview/components/data-sources/data-table-content.tsx#L2)):*
> ```XML
> import Checkbox from '@/components/shadcn-ui/checkbox';
> import { ColumnDef, SortDirection } from '@tanstack/react-table';
> ```

These types should be imported from the DataTable component, not from @tanstack/react-table
___
*[`lib/platform-bible-react/src/preview/components/guide/query.gql` line 1 at r1](https://reviewable.io/reviews/paranext/paranext-core/1019#-O2BTq778UAgR3OdZoHs:-O2BTq778UAgR3OdZoHt:b-c06hsg) ([raw file](https://github.com/paranext/paranext-core/blob/d4eac52c10884c0306adbf528723b7c09235a718/lib/platform-bible-react/src/preview/components/guide/query.gql#L1)):*
> ```GraphQL
> query {
> ```

What does this do? Is it GraphQL? What's it used for? Where is it being used?
___
*[`lib/platform-bible-react/src/preview/components/guide/result.json` line 1 at r1](https://reviewable.io/reviews/paranext/paranext-core/1019#-O2BU42o6vMlHruYB7oR:-O2BU42o6vMlHruYB7oS:b-t497qp) ([raw file](https://github.com/paranext/paranext-core/blob/d4eac52c10884c0306adbf528723b7c09235a718/lib/platform-bible-react/src/preview/components/guide/result.json#L1)):*
> ```JSON
> {
> ```

What is this, and where is it being used?

**Comment by Sebastian-ubs** [comment]
Ouch, indeed some wrong files in there. Thank you

**Comment by Sebastian-ubs** [comment]
Issue to replace mui slider and toggle: https://github.com/paranext/paranext-core/issues/1005
@dewert99 may have plans to replace others!?

**Comment by Sebastian-ubs** [comment]
removed wrongly added files, rebased on main. @rolfheij-sil please review.

**Review by rolfheij-sil — CHANGES_REQUESTED** [review]
> Reviewed 3 of 4 files at r2, 1 of 1 files at r3, 6 of 6 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/1019)* status: all files reviewed, 2 unresolved discussions (waiting on @Sebastian-ubs)

___
*[`lib/platform-bible-react/src/preview/components/basics/slider.examples.component.tsx` line 8 at r1](https://reviewable.io/reviews/paranext/paranext-core/1019#-O2BTOYt0Ad49enTFkjN:-O2U7MwG1o16Kni04T8e:bvtzob7) ([raw file](https://github.com/paranext/paranext-core/blob/d4eac52c10884c0306adbf528723b7c09235a718/lib/platform-bible-react/src/preview/components/basics/slider.examples.component.tsx#L8)):*
<details><summary><i>Previously, rolfheij-sil (Rolf Heij) wrote…</i></summary><blockquote>

Should we create an issue for swapping the remaining MUI components out for shadcn components?
</blockquote></details>

I saw your reply to this in the common section of the review. Maybe reply directly to threads like these next time? :)
___
*[`lib/platform-bible-react/src/preview/components/data-sources/data-table-content.tsx` line 2 at r1](https://reviewable.io/reviews/paranext/paranext-core/1019#-O2BTcou1PyGa9v9lFl5:-O2U7L28BHQHJDN8KczC:bbf0c20) ([raw file](https://github.com/paranext/paranext-core/blob/d4eac52c10884c0306adbf528723b7c09235a718/lib/platform-bible-react/src/preview/components/data-sources/data-table-content.tsx#L2)):*
<details><summary><i>Previously, rolfheij-sil (Rolf Heij) wrote…</i></summary><blockquote>

These types should be imported from the DataTable component, not from @tanstack/react-table
</blockquote></details>

Can you still fix this?

**Review by Sebastian-ubs — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/1019)* status: all files reviewed, 1 unresolved discussion (waiting on @rolfheij-sil)

___
*[`lib/platform-bible-react/src/preview/components/data-sources/data-table-content.tsx` line 2 at r1](https://reviewable.io/reviews/paranext/paranext-core/1019#-O2BTcou1PyGa9v9lFl5:-O2UNeuOCJFJHozbecnF:b6s4dxv) ([raw file](https://github.com/paranext/paranext-core/blob/d4eac52c10884c0306adbf528723b7c09235a718/lib/platform-bible-react/src/preview/components/data-sources/data-table-content.tsx#L2)):*
<details><summary><i>Previously, rolfheij-sil (Rolf Heij) wrote…</i></summary><blockquote>

Can you still fix this?
</blockquote></details>

this import wasn't added by me and seem to be anyhow changed to the one you are requesting by my pull from main, right?

right now it is:



_Code snippet:_
```XML
import {
  ColumnDef,
  SortDirection,
} from '@/components/advanced-components/data-table/data-table.component';
```

**Review by rolfheij-sil — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/1019)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

___
*[`lib/platform-bible-react/src/preview/components/data-sources/data-table-content.tsx` line 2 at r1](https://reviewable.io/reviews/paranext/paranext-core/1019#-O2BTcou1PyGa9v9lFl5:-O2UTJERBPySF0d2HLPg:b-cmnj77) ([raw file](https://github.com/paranext/paranext-core/blob/d4eac52c10884c0306adbf528723b7c09235a718/lib/platform-bible-react/src/preview/components/data-sources/data-table-content.tsx#L2)):*
<details><summary><i>Previously, Sebastian-ubs wrote…</i></summary><blockquote>

this import wasn't added by me and seem to be anyhow changed to the one you are requesting by my pull from main, right?

right now it is:
</blockquote></details>

Yeah that seems to have fixed it. Thanks

**Pull request merged**
