### PR TITLE
Hook up project and user settings tabs

### PR DESCRIPTION
**Pull request by jolierabideau**
Add menu items and data
Add missing localized strings
Add `getLocalizedContributionInfo()` to project settings service
Move `validateSetting()` into `SettingDataProviderEngine`
Remove old settings tab and components

Settings tab
     - Create it
     - Add it to dock
     - Create `ProjectOrUserSettingsList` component
     - Create `ProjectSetting` component
     - Create `Setting` component

platform-bible-react
     - Fix various import statements that were causing errors
     - Create `NavigationContentSearch` component
     - Create `SettingsList`, `SettingsListItem`, `SettingsListHeader` components
     - Make `SearchBar` look like bcv search
     - Add Shadcn `Separator` component
     - Add components to preview
     - Fix error in a preview page
     
platform-bible-utils
     - Move `ensureArray()` to array utils
     - Move `transformAndEnsureRegExpRegExpArray()` to string util
     - Move `transformAndEnsureRegExpArray()` to string util

Screenshot 2024-08-15 at 6 42 36 PM
Screenshot 2024-08-15 at 6 43 15 PM
Screenshot 2024-08-15 at 6 43 24 PM
Screenshot 2024-08-16 at 1 05 00 PM
Screenshot 2024-08-16 at 1 05 17 PM

This change is [Reviewable](https://reviewable.io/reviews/paranext/paranext-core/1070)

### CODE REVIEW

**Review by tjcouch-sil — CHANGES_REQUESTED** [review]
Thanks for all the great work on this! Really excited to have this in! Few things to adjust and a few suggestions.

> Reviewed 47 of 47 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/1070#-:-O4gLDy_9IIAUg-W4JUO:b-pi265f)* status: all files reviewed, 11 unresolved discussions (waiting on @jolierabideau)

___
*[`extensions/src/platform-scripture/contributions/localizedStrings.json` line 5 at r1](https://reviewable.io/reviews/paranext/paranext-core/1070#-O4fKiEl7moMfcpbln_7:-O4fKiEl7moMfcpbln_8:b-3fuk5s) ([raw file](https://github.com/paranext/paranext-core/blob/fa6816e1d756deb50a4b70c19ab268d0eb45ee3d/extensions/src/platform-scripture/contributions/localizedStrings.json#L5)):*
> ```JSON
>   "localizedStrings": {
>     "en": {
>       "%settings_platformScripture_paratext_group_label%": "Scripture Settings",
> ```

After looking at what this settings group is, it seems specific to Paratext 9. Let me know if you have other thoughts, but I'd say let's change it back or maybe even to "Paratext 9-related Settings".
___
*[`lib/platform-bible-react/src/index.ts` line 90 at r1](https://reviewable.io/reviews/paranext/paranext-core/1070#-O4fP6027PXOOCOdLSWV:-O4fP6027PXOOCOdLSWW:b-js6boj) ([raw file](https://github.com/paranext/paranext-core/blob/fa6816e1d756deb50a4b70c19ab268d0eb45ee3d/lib/platform-bible-react/src/index.ts#L90)):*
> ```XML
> 
> export { Input } from './components/shadcn-ui/input';
> export * from './components/shadcn-ui/dropdown-menu';
> ```

Do you want to export your new shadcn components here? I can't keep track of where we are on all this.
___
*[`lib/platform-bible-react/src/components/advanced/settings-components/settings-list.component.tsx` line 67 at r1](https://reviewable.io/reviews/paranext/paranext-core/1070#-O4fTzd390TMZy_uhzkZ:-O4fTzd390TMZy_uhzk_:b-rqgjya) ([raw file](https://github.com/paranext/paranext-core/blob/fa6816e1d756deb50a4b70c19ab268d0eb45ee3d/lib/platform-bible-react/src/components/advanced/settings-components/settings-list.component.tsx#L67)):*
> ```XML
>         <p className="pr-text-sm pr-text-muted-foreground">{loadingMessage}</p>
>       ) : (
>         generateActionComponent()
> ```

Would it work to pass in an element or just use `children`?
___
*[`lib/platform-bible-react/src/components/basics/search-bar.component.tsx` line 31 at r1](https://reviewable.io/reviews/paranext/paranext-core/1070#-O4fUIpQ-o71PyEQsbin:-O4fUIpQ-o71PyEQsbio:b-x005e) ([raw file](https://github.com/paranext/paranext-core/blob/fa6816e1d756deb50a4b70c19ab268d0eb45ee3d/lib/platform-bible-react/src/components/basics/search-bar.component.tsx#L31)):*
> ```XML
>     <Input
>       className={cn(
>         'pr-flex pr-h-10 pr-rounded-md pr-border pr-border-input pr-bg-background pr-px-3 pr-py-2 pr-text-sm pr-ring-offset-background file:pr-border-0 file:pr-bg-transparent file:pr-text-sm file:pr-font-medium placeholder:pr-text-muted-foreground focus-visible:pr-outline-none focus-visible:pr-ring-2 focus-visible:pr-ring-[color:hsl(240,5%,64.9%)] focus-visible:pr-ring-offset-2 disabled:pr-cursor-not-allowed disabled:pr-opacity-50',
> ```

For my learning, where did you get all these classes? Were they already somewhere else and you knew UX would want them here? 

Also is `color:hsl(240,5%,64.9%)` something we use multiple times? I think we have variables set up for various colors; I dunno if we can use them here or if this belongs in a variable. Not a big deal right now, but it could be worth looking into if you want :)
___
*[`lib/platform-bible-react/src/components/shadcn-ui/separator.tsx` line 15 at r1](https://reviewable.io/reviews/paranext/paranext-core/1070#-O4fnQCq1n-lIuf9Vlvl:-O4fnQCq1n-lIuf9Vlvm:bpf80d3) ([raw file](https://github.com/paranext/paranext-core/blob/fa6816e1d756deb50a4b70c19ab268d0eb45ee3d/lib/platform-bible-react/src/components/shadcn-ui/separator.tsx#L15)):*
> ```XML
>     orientation={orientation}
>     className={cn(
>       'pr-shrink-0 pr-bg-border',
> ```

I think this needs `pr-twp` on the front, right?
___
*[`lib/platform-bible-utils/src/array-util.ts` line 16 at r1](https://reviewable.io/reviews/paranext/paranext-core/1070#-O4foiEM0JyjpRgvGAeN:-O4foiEM0JyjpRgvGAeO:bq8y2m8) ([raw file](https://github.com/paranext/paranext-core/blob/fa6816e1d756deb50a4b70c19ab268d0eb45ee3d/lib/platform-bible-utils/src/array-util.ts#L16)):*
> ```XML
>  *   returned.
>  */
> export default function ensureArray<T>(maybeArray: T | T[] | undefined): T[] {
> ```

As much as I hate to say it, we usually... do... unit :vomiting_face: tests :vomiting_face: on our utils stuff. Would recommend

I acknowledge, though, that you didn't actually make this code. You can pass on these unit tests for now if you want.
___
*[`lib/platform-bible-utils/src/string-util.ts` line 590 at r1](https://reviewable.io/reviews/paranext/paranext-core/1070#-O4fotaSEQDkHGjk_T1Q:-O4fotaT9hOsyqDKYb0_:bq8y2m8) ([raw file](https://github.com/paranext/paranext-core/blob/fa6816e1d756deb50a4b70c19ab268d0eb45ee3d/lib/platform-bible-utils/src/string-util.ts#L590)):*
> ```XML
>  *   an empty array is returned.
>  */
> export function transformAndEnsureRegExpRegExpArray(
> ```

As much as I hate to say it, we usually... do... unit :vomiting_face: tests :vomiting_face: on our utils stuff. Would recommend

I acknowledge, though, that you didn't actually make this code. You can pass on these unit tests for now if you want.
___
*[`lib/platform-bible-utils/src/string-util.ts` line 619 at r1](https://reviewable.io/reviews/paranext/paranext-core/1070#-O4fouei1HvtvZ6NWrWG:-O4fouei1HvtvZ6NWrWH:b9e7nmo) ([raw file](https://github.com/paranext/paranext-core/blob/fa6816e1d756deb50a4b70c19ab268d0eb45ee3d/lib/platform-bible-utils/src/string-util.ts#L619)):*
> ```XML
>  * @returns An array of `RegExp` objects. If the input is `undefined`, an empty array is returned.
>  */
> export function transformAndEnsureRegExpArray(
> ```

As much as I hate to say it, we usually... do... unit :vomiting_face: tests :vomiting_face: on our utils stuff. Would recommend

:dizzy_face: 

I acknowledge, though, that you didn't actually make this code. You can pass on these unit tests for now if you want.
___
*[`src/extension-host/services/settings.service-host.ts` line 220 at r1](https://reviewable.io/reviews/paranext/paranext-core/1070#-O4ftO2AA7uxkSSa1dei:-O4ftO2AA7uxkSSa1dej:b54151o) ([raw file](https://github.com/paranext/paranext-core/blob/fa6816e1d756deb50a4b70c19ab268d0eb45ee3d/src/extension-host/services/settings.service-host.ts#L220)):*
> ```XML
> 
>   // eslint-disable-next-line class-methods-use-this
>   async returnLocalizedContributionInfo(): Promise<LocalizedSettingsContributionInfo | undefined> {
> ```

FYI if you were having trouble using `getLocalizedContributionInfo`, you can put `@dataProviderService.decorators.ignore` to get it not to be upset that you have a `get` without a `set`. Not a requirement by any means, but I would suggest considering changing it to `get` if that's why it's called `return`
___
*[`src/renderer/components/docking/platform-dock-layout-storage.util.ts` line 76 at r1](https://reviewable.io/reviews/paranext/paranext-core/1070#-O4fttC97hJqWpyFyCUv:-O4fttC97hJqWpyFyCUw:b-r7myi4) ([raw file](https://github.com/paranext/paranext-core/blob/fa6816e1d756deb50a4b70c19ab268d0eb45ee3d/src/renderer/components/docking/platform-dock-layout-storage.util.ts#L76)):*
> ```XML
>     [TAB_TYPE_DOWNLOAD_UPDATE_PROJECT_DIALOG, loadDownloadUpdateProjectTab],
>     [TAB_TYPE_EXTENSION_MANAGER, loadExtensionManagerTab],
>     [TAB_TYPE_USER_SETTINGS_TAB, loadUserSettingsDialog],
> ```

Since these are tabs and not dialogs, might be helpful to avoid confusion to rename these functions
___
*[`src/renderer/components/settings-tabs/settings-tab.component.tsx` line 96 at r1](https://reviewable.io/reviews/paranext/paranext-core/1070#-O4fw9c94lE0q-0Y_3F_:-O4fw9c94lE0q-0Y_3Fa:bj43a0l) ([raw file](https://github.com/paranext/paranext-core/blob/fa6816e1d756deb50a4b70c19ab268d0eb45ee3d/src/renderer/components/settings-tabs/settings-tab.component.tsx#L96)):*
> ```XML
>       <SettingsTab
>         projectId={typedSavedTabInfo.data.projectId}
>         settingsContributions={typedSavedTabInfo.data.settingsContributions}
> ```

It seems strange that the contributions would be saved as tab data. I suggest possibly getting the contribution info inside the settings tab with `usePromise` or something. Then we don't save a bunch of generated data, and that data doesn't get outdated if the user leaves the tab open across many sessions or something. Probably not a big deal right now though
___
*[`src/renderer/components/settings-tabs/settings-components/project-setting.component.tsx` line 34 at r1](https://reviewable.io/reviews/paranext/paranext-core/1070#-O4g84mf5e6eP89-RyA0:-O4g84mf5e6eP89-RyA1:ba6xw9b) ([raw file](https://github.com/paranext/paranext-core/blob/fa6816e1d756deb50a4b70c19ab268d0eb45ee3d/src/renderer/components/settings-tabs/settings-components/project-setting.component.tsx#L34)):*
> ```XML
>   const [errorMessage, setErrorMessage] = useState<string | undefined>(undefined);
> 
>   const validateProjectSettingValue = async (
> ```

Can this be removed?
___
*[`src/renderer/components/settings-tabs/settings-components/project-setting.component.tsx` line 59 at r1](https://reviewable.io/reviews/paranext/paranext-core/1070#-O4gCqq_7PTKXmr1n99Y:-O4gCqqaD6e2rZO6Eq_1:b-eqvm3b) ([raw file](https://github.com/paranext/paranext-core/blob/fa6816e1d756deb50a4b70c19ab268d0eb45ee3d/src/renderer/components/settings-tabs/settings-components/project-setting.component.tsx#L59)):*
> ```XML
>     }
> 
>     const isValid = await validateProjectSettingValue(settingKey, newValue, setting);
> ```

Could you put a try/catch around this and set the caught error message to the `errorMessage` here? Some validators throw an extension with a specific message
___
*[`src/renderer/components/settings-tabs/settings-components/setting.component.tsx` line 18 at r1](https://reviewable.io/reviews/paranext/paranext-core/1070#-O4gD1p25TYfq_mXS9DC:-O4gD1p25TYfq_mXS9DD:b-fcfgvm) ([raw file](https://github.com/paranext/paranext-core/blob/fa6816e1d756deb50a4b70c19ab268d0eb45ee3d/src/renderer/components/settings-tabs/settings-components/setting.component.tsx#L18)):*
> ```XML
> };
> 
> export default function Setting({ settingKey, label, description, defaultSetting }: SettingProps) {
> ```

Seems this component is almost the same as `ProjectSetting`. Are there any quick small wins you could make regarding factoring some stuff out into hooks or props or shared components so you can repeat less code?
___
*[`src/renderer/services/web-view.service-host.ts` line 1263 at r1](https://reviewable.io/reviews/paranext/paranext-core/1070#-O4gIJWh5gRD7dteXH0Q:-O4gIJWh5gRD7dteXH0R:b-wg14ri) ([raw file](https://github.com/paranext/paranext-core/blob/fa6816e1d756deb50a4b70c19ab268d0eb45ee3d/src/renderer/services/web-view.service-host.ts#L1263)):*
> ```XML
> async function openProjectSettingsTab(webViewId: string): Promise<Layout | undefined> {
>   const settingsTabId = newGuid();
>   const projectIdFromWebView = (await getDockLayout()).getWebViewDefinition(webViewId)?.projectId;
> ```

Prefer `getSavedWebViewDefinition` to have one consistent way to get this info :)
___
*[`src/shared/services/project-settings.service.ts` line 40 at r1](https://reviewable.io/reviews/paranext/paranext-core/1070#-O4gKMoF15t-Ml9lu_Me:-O4gKMoF15t-Ml9lu_Mf:bwh1el6) ([raw file](https://github.com/paranext/paranext-core/blob/fa6816e1d756deb50a4b70c19ab268d0eb45ee3d/src/shared/services/project-settings.service.ts#L40)):*
> ```XML
>   // Map is not being used to return an array
>   // eslint-disable-next-line array-callback-return
>   Object.entries(contributions).map(([extensionName, contributionArray]) => {
> ```

You can use `.forEach` to do the same thing as a `.map` but without returning

**Review by jolierabideau — COMMENTED** [review]
Thanks for the review! Still working on combining project setting and setting components.

> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/1070#-:-O4kGVRM8C3R6gJDOF2Q:b-y6askn)* status: all files reviewed, 5 unresolved discussions (waiting on @tjcouch-sil)

___
*[`extensions/src/platform-scripture/contributions/localizedStrings.json` line 5 at r1](https://reviewable.io/reviews/paranext/paranext-core/1070#-O4fKiEl7moMfcpbln_7:-O4gRWTNAPrhCvTUD3MR:b-896fix) ([raw file](https://github.com/paranext/paranext-core/blob/fa6816e1d756deb50a4b70c19ab268d0eb45ee3d/extensions/src/platform-scripture/contributions/localizedStrings.json#L5)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

After looking at what this settings group is, it seems specific to Paratext 9. Let me know if you have other thoughts, but I'd say let's change it back or maybe even to "Paratext 9-related Settings".
</blockquote></details>

Done.
___
*[`lib/platform-bible-react/src/components/basics/search-bar.component.tsx` line 31 at r1](https://reviewable.io/reviews/paranext/paranext-core/1070#-O4fUIpQ-o71PyEQsbin:-O4gRvNF2pUwGuVmafQg:b-yszsba) ([raw file](https://github.com/paranext/paranext-core/blob/fa6816e1d756deb50a4b70c19ab268d0eb45ee3d/lib/platform-bible-react/src/components/basics/search-bar.component.tsx#L31)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

For my learning, where did you get all these classes? Were they already somewhere else and you knew UX would want them here? 

Also is `color:hsl(240,5%,64.9%)` something we use multiple times? I think we have variables set up for various colors; I dunno if we can use them here or if this belongs in a variable. Not a big deal right now, but it could be worth looking into if you want :)
</blockquote></details>

I copied this from the bcv input. I'm pretty sure that the way the bcv is styled is how UX said they want the inputs to look. But I didn't want to style the default input because we said we were leaving those unstyled, and I'm not sure if that is still what UX wants the inputs to look like.
___
*[`lib/platform-bible-react/src/components/shadcn-ui/separator.tsx` line 15 at r1](https://reviewable.io/reviews/paranext/paranext-core/1070#-O4fnQCq1n-lIuf9Vlvl:-O4gS_Zu89dePHAOyBt7:b-896fix) ([raw file](https://github.com/paranext/paranext-core/blob/fa6816e1d756deb50a4b70c19ab268d0eb45ee3d/lib/platform-bible-react/src/components/shadcn-ui/separator.tsx#L15)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

I think this needs `pr-twp` on the front, right?
</blockquote></details>

Done.
___
*[`src/extension-host/services/settings.service-host.ts` line 220 at r1](https://reviewable.io/reviews/paranext/paranext-core/1070#-O4ftO2AA7uxkSSa1dei:-O4gbRisDUvcuDmHUPfz:b6a08ho) ([raw file](https://github.com/paranext/paranext-core/blob/fa6816e1d756deb50a4b70c19ab268d0eb45ee3d/src/extension-host/services/settings.service-host.ts#L220)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

FYI if you were having trouble using `getLocalizedContributionInfo`, you can put `@dataProviderService.decorators.ignore` to get it not to be upset that you have a `get` without a `set`. Not a requirement by any means, but I would suggest considering changing it to `get` if that's why it's called `return`
</blockquote></details>

Thank you, I used return so I could test it quicker and then forgot.
___
*[`src/renderer/components/settings-tabs/settings-components/project-setting.component.tsx` line 59 at r1](https://reviewable.io/reviews/paranext/paranext-core/1070#-O4gCqq_7PTKXmr1n99Y:-O4kEl-S5GSggecyVE5N:b-896fix) ([raw file](https://github.com/paranext/paranext-core/blob/fa6816e1d756deb50a4b70c19ab268d0eb45ee3d/src/renderer/components/settings-tabs/settings-components/project-setting.component.tsx#L59)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

Could you put a try/catch around this and set the caught error message to the `errorMessage` here? Some validators throw an extension with a specific message
</blockquote></details>

Done.
___
*[`src/renderer/components/settings-tabs/settings-components/setting.component.tsx` line 18 at r1](https://reviewable.io/reviews/paranext/paranext-core/1070#-O4gD1p25TYfq_mXS9DC:-O4kFL8k4ivxcADxXqL5:bx5sc2k) ([raw file](https://github.com/paranext/paranext-core/blob/fa6816e1d756deb50a4b70c19ab268d0eb45ee3d/src/renderer/components/settings-tabs/settings-components/setting.component.tsx#L18)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

Seems this component is almost the same as `ProjectSetting`. Are there any quick small wins you could make regarding factoring some stuff out into hooks or props or shared components so you can repeat less code?
</blockquote></details>

Originally I tried to combine the two, the user and project setting types were just different enough that I was having a lot of trouble trying to type objects. I also could not figure out a way to render a hook conditionally, since I am using `useSetting` and `useProjectSetting`. I am taking a look at combining these now, or at least what I can pull out of it to share like you said.
___
*[`src/shared/services/project-settings.service.ts` line 40 at r1](https://reviewable.io/reviews/paranext/paranext-core/1070#-O4gKMoF15t-Ml9lu_Me:-O4kGQUj68vthj4W1EXO:b-jamngv) ([raw file](https://github.com/paranext/paranext-core/blob/fa6816e1d756deb50a4b70c19ab268d0eb45ee3d/src/shared/services/project-settings.service.ts#L40)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

You can use `.forEach` to do the same thing as a `.map` but without returning
</blockquote></details>

Geez, sorry

**Review by tjcouch-sil — CHANGES_REQUESTED** [review]
Thanks for all the great adjustments! It's looking good! Just a few things left. Note that only one is blocking. If you decide against doing the others, feel free to resolve and move on :)

> Reviewed 22 of 22 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/1070#-:-O4kLxDwDRelAcOuVPMH:bknq2gd)* status: all files reviewed, 2 unresolved discussions (waiting on @jolierabideau)

___
*[`package.json` line 83 at r2](https://reviewable.io/reviews/paranext/paranext-core/1070#-O4kHmpF7MzfJKU6t-IY:-O4kHmpF7MzfJKU6t-IZ:bjbswdp) ([raw file](https://github.com/paranext/paranext-core/blob/73f71e86405a1c00b0f12e052b1bc9639dee9064/package.json#L83)):*
> ```JSON
>     "start:extensions": "cd extensions && npm run watch",
>     "start:preload": "cross-env NODE_ENV=development TS_NODE_TRANSPILE_ONLY=true webpack --config ./.erb/configs/webpack.config.preload.dev.ts",
>     "start:renderer": "DEV_NOISY=true cross-env NODE_ENV=development TS_NODE_TRANSPILE_ONLY=true webpack serve --config ./.erb/configs/webpack.config.renderer.dev.ts",
> ```

Reminder to remove this when you're ready :)
___
*[`lib/platform-bible-react/src/components/basics/search-bar.component.tsx` line 31 at r1](https://reviewable.io/reviews/paranext/paranext-core/1070#-O4fUIpQ-o71PyEQsbin:-O4kLHRv0nuxyunZL6ZA:b-jtvcsf) ([raw file](https://github.com/paranext/paranext-core/blob/fa6816e1d756deb50a4b70c19ab268d0eb45ee3d/lib/platform-bible-react/src/components/basics/search-bar.component.tsx#L31)):*
<details><summary><i>Previously, jolierabideau wrote…</i></summary><blockquote>

I copied this from the bcv input. I'm pretty sure that the way the bcv is styled is how UX said they want the inputs to look. But I didn't want to style the default input because we said we were leaving those unstyled, and I'm not sure if that is still what UX wants the inputs to look like.
</blockquote></details>

I thought we decided we would style the shadcn components however we wanted and not create wrappers over them. I could be remembering incorrectly. If we do not create wrappers, it would be good to go ahead and put this styling on the input itself. If we do create wrappers, it would be good to create a wrapper and use it here and in the bcv input. That way, we don't have this crazy long magic string to copy and paste in multiple places :)
___
*[`src/renderer/components/settings-tabs/settings-components/project-setting.component.tsx` line 59 at r1](https://reviewable.io/reviews/paranext/paranext-core/1070#-O4gCqq_7PTKXmr1n99Y:-O4kJPM_60MVy61PshJH:bmddaz) ([raw file](https://github.com/paranext/paranext-core/blob/fa6816e1d756deb50a4b70c19ab268d0eb45ee3d/src/renderer/components/settings-tabs/settings-components/project-setting.component.tsx#L59)):*
<details><summary><i>Previously, jolierabideau wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Haha I meant "Some validators throw an **exception** with a specific message". Whoops. Thanks for updating!
___
*[`src/renderer/components/settings-tabs/settings-components/project-setting.component.tsx` line 60 at r2](https://reviewable.io/reviews/paranext/paranext-core/1070#-O4kJ3sA50d8Q_mT84eQ:-O4kJ3sA50d8Q_mT84eR:b-t9k7k) ([raw file](https://github.com/paranext/paranext-core/blob/73f71e86405a1c00b0f12e052b1bc9639dee9064/src/renderer/components/settings-tabs/settings-components/project-setting.component.tsx#L60)):*
> ```XML
>       // Error is type unknown and if I type it as string it says it must be any or unknown
>       // eslint-disable-next-line no-type-assertion/no-type-assertion
>       setErrorMessage(error as string);
> ```

This probably works great, but alternatively you can use a util function called `getErrorMessage`. Honestly it's hard to comprehend why it's *so* hard to get information out of errors in TypeScript. But here we are 🤷
___
*[`src/renderer/components/settings-tabs/settings-components/setting.component.tsx` line 18 at r1](https://reviewable.io/reviews/paranext/paranext-core/1070#-O4gD1p25TYfq_mXS9DC:-O4kJitN68_c0x3Dfrpy:b-ikml3i) ([raw file](https://github.com/paranext/paranext-core/blob/fa6816e1d756deb50a4b70c19ab268d0eb45ee3d/src/renderer/components/settings-tabs/settings-components/setting.component.tsx#L18)):*
<details><summary><i>Previously, jolierabideau wrote…</i></summary><blockquote>

Originally I tried to combine the two, the user and project setting types were just different enough that I was having a lot of trouble trying to type objects. I also could not figure out a way to render a hook conditionally, since I am using `useSetting` and `useProjectSetting`. I am taking a look at combining these now, or at least what I can pull out of it to share like you said.
</blockquote></details>

Yeah, unfortunately React really doesn't like it when you use hooks conditionally (even if we know the hook will never change, it just spooks React too much)...

Just an idea (not very well formed), but could it possibly make sense to have some component that both of these use that internally does most of the operations here? So these components could get `setting`, `setSetting`, `validateSettingValue`, and whatever else is different between settings and project settings, then it passes these things into the shared component as props. Then the shared component can do `handleChangeSetting` and `generateComponent`. I'm not totally sure those are independent of setting and project setting, but it's just a hunch :)
___
*[`src/shared/services/project-settings.service.ts` line 40 at r1](https://reviewable.io/reviews/paranext/paranext-core/1070#-O4gKMoF15t-Ml9lu_Me:-O4kL0dl4Cz2QZu-pynp:bxoeajs) ([raw file](https://github.com/paranext/paranext-core/blob/fa6816e1d756deb50a4b70c19ab268d0eb45ee3d/src/shared/services/project-settings.service.ts#L40)):*
<details><summary><i>Previously, jolierabideau wrote…</i></summary><blockquote>

Geez, sorry
</blockquote></details>

No prob :) too many things to keep track of

**Review by jolierabideau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/1070)* status: 42 of 52 files reviewed, 1 unresolved discussion (waiting on @tjcouch-sil)

___
*[`lib/platform-bible-react/src/components/basics/search-bar.component.tsx` line 31 at r1](https://reviewable.io/reviews/paranext/paranext-core/1070#-O4fUIpQ-o71PyEQsbin:-O4l2s9P2TQS2emqcnYM:b-90dzhu) ([raw file](https://github.com/paranext/paranext-core/blob/fa6816e1d756deb50a4b70c19ab268d0eb45ee3d/lib/platform-bible-react/src/components/basics/search-bar.component.tsx#L31)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

I thought we decided we would style the shadcn components however we wanted and not create wrappers over them. I could be remembering incorrectly. If we do not create wrappers, it would be good to go ahead and put this styling on the input itself. If we do create wrappers, it would be good to create a wrapper and use it here and in the bcv input. That way, we don't have this crazy long magic string to copy and paste in multiple places :)
</blockquote></details>

Definitely, you're right I remember we decided on no wrappers. I will make a note to bring this up with Sebastian when he gets back and then I can create a follow-up PR for any style changes.
___
*[`package.json` line 83 at r2](https://reviewable.io/reviews/paranext/paranext-core/1070#-O4kHmpF7MzfJKU6t-IY:-O4pvpP4EnlpKDBOHLQ7:b-896fix) ([raw file](https://github.com/paranext/paranext-core/blob/73f71e86405a1c00b0f12e052b1bc9639dee9064/package.json#L83)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

Reminder to remove this when you're ready :)
</blockquote></details>

Done.

**Review by tjcouch-sil — APPROVED** [review]
:lgtm: woohoo! Thanks for the great work!

> Reviewed 10 of 10 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/1070#-:-O4q0Z4-CqFd5sz954NQ:b-qb8wox)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Pull request merged**
