### PR TITLE
Setup linting rules for .(S)CSS

### LINKED ISSUE #396: Setup linting steps for .(S)CSS files

### PR DESCRIPTION
**Pull request by rolfheij-sil**
Resolves #396

- - -
This change is [Reviewable](https://reviewable.io/reviews/paranext/paranext-core/397)

### CODE REVIEW

**Review by rolfheij-sil — COMMENTED** [review]
We decided to add these linting steps after discovering that `display: 'flex'` caused trouble because it should have been `display: flex`. Unfortunately our new linting steps, that found a lot of issues with our CSS code, were not able to detect and fix this particular issue. I've tried all the [quotes related rules](https://stylelint.io/user-guide/rules/#quotes) in stylelint but none of them seem to tackle it 

> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/397#-:-Ncd0E5GAwLcdsnGLbXG:bhkks7d)* status: 0 of 26 files reviewed, all discussions resolved

**Review by rolfheij-sil — COMMENTED** [review]
Also, the `display: 'flex'` issue was in an extension, and the extension template has no linting configuration set up. Do we want to add those?

> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/397#-:-Ncd55X88EUYq8RWSAG6:b-311rrw)* status: 0 of 26 files reviewed, all discussions resolved

**Review by irahopkinson — CHANGES_REQUESTED** [review]
Good work on this. Just one thing to fix.

Check with @tjcouch-sil about adding linting in to extensions and the template. I would recommend it as it keeps things consistent for maintaining and devloping them both for us and extension developers (and if they don't want them it's easier to remove than to add them in). However IIRC, @tjcouch-sil wanted to keep them lighter which is valid also.

> Reviewed 26 of 26 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/397#-:-NcdRemx-pEwnITW9LJU:bkuwl51)* status: all files reviewed, 1 unresolved discussion (waiting on @rolfheij-sil)

___
*[`extensions/package.json` line 27 at r1](https://reviewable.io/reviews/paranext/paranext-core/397#-NcdPOj46dJRUmhg6NPQ:-NcdPOj46dJRUmhg6NPR:b-2dahac) ([raw file](https://github.com/paranext/paranext-core/blob/74beb7e4b81e3711150f0007880807da5e26fe84/extensions/package.json#L27)):*
> ```JSON
>   "lint-staged": {
>     "*.{js,jsx,ts,tsx}": [
>       "prettier --ignore-path .eslintignore --parser json --write",
> ```

I don't think this should be using `--parser json`. Remove it.

**Review by rolfheij-sil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/397)* status: all files reviewed, 1 unresolved discussion (waiting on @irahopkinson)

___
*[`extensions/package.json` line 27 at r1](https://reviewable.io/reviews/paranext/paranext-core/397#-NcdPOj46dJRUmhg6NPQ:-Nch05-jCEmmRKFHPqLr:b-2owgiu) ([raw file](https://github.com/paranext/paranext-core/blob/74beb7e4b81e3711150f0007880807da5e26fe84/extensions/package.json#L27)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

I don't think this should be using `--parser json`. Remove it.
</blockquote></details>

Oops. That's a copy-paste error. Thanks for spotting it.

**Review by rolfheij-sil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/397)* status: all files reviewed, 4 unresolved discussions (waiting on @irahopkinson and @tjcouch-sil)

___
*[`.prettierignore` line 1 at r2](https://reviewable.io/reviews/paranext/paranext-core/397#-Nch2HVkEY72vYe1ALYp:-Nch6tSI1HF2jdmigc5b:b-896fix) ([raw file](https://github.com/paranext/paranext-core/blob/361a91617f100bf64f43919c4ea237c3d738ba9c/.prettierignore#L1)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

We should probably add `.stylelintignore` that syncs with the other ignore files, too, right?
</blockquote></details>

Done.
___
*[`package.json` line 59 at r2](https://reviewable.io/reviews/paranext/paranext-core/397#-Nch3XFx5_4GmFX1-5vx:-NchIrZaDSXD_13rFtoK:b-or9nka) ([raw file](https://github.com/paranext/paranext-core/blob/361a91617f100bf64f43919c4ea237c3d738ba9c/package.json#L59)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

I would say the general expectation for running a `lint` script is that it would not change files (but maybe we would have another script that would change files). For example, our `test.yml` workflow runs `npm run lint` on the GitHub servers. It would be very strange to make changes there. I also asked ChatGPT for its thoughts, and [it seems to say basically people often have a `lint` script and a `lint-fix` script, but it really is up to the team](https://chat.openai.com/share/1e225cb4-db3e-4315-9378-ec20cd63a943).

I would prefer to have two scripts myself, but I am interested in hearing your and Ira's thoughts as well.

Regarding implementation, it looks like [you might be able to make the npm script pass arguments down to child scripts](https://stackoverflow.com/a/40508801/8535752) by putting a hanging `--` at the end of the command. I wonder if you could make the `lint-fix` script look like `npm run lint -- --fix --write` or something, then have the `lint` script do `npm run lint:scripts -- && npm run lint:styles --` and such. I dunno if you can pass arguments down with multiple scripts like this, but I'm curious to know if it would work.

Note: in `npm`, the `--` argument lets `npm run` know that you're trying to pass following arguments to the script itself, not to `npm run`, so it passes them down.
</blockquote></details>

I created some sort of hybrid solution. Just passing down '--fix' doesnt work for the ts/tsx/js/jsx files since we're using prettier to fix them and eslint to lint them. So there's no one-line solution. But this works fine too, and I hope you like it.

Note that lint:staged is still configured to lint and fix, but I'm pretty sure that is what we want, as we discussed with Ira a few days ago
___
*[`src/renderer/components/docking/paranext-dock-layout.component.css` line 32 at r2](https://reviewable.io/reviews/paranext/paranext-core/397#-Nch34SW7xO1k1To_dlZ:-Nch7wMOD_jtD-us5rFB:bxr9fs) ([raw file](https://github.com/paranext/paranext-core/blob/361a91617f100bf64f43919c4ea237c3d738ba9c/src/renderer/components/docking/paranext-dock-layout.component.css#L32)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

Why are you ignoring this issue? We always comment above ignore lines why we think it is worth ignoring.
</blockquote></details>

Oops. I'm not. It was something I was testing but I forgot to remove the comment

**Review by tjcouch-sil — COMMENTED** [review]
> Reviewed 25 of 25 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/397)* status: all files reviewed, 4 unresolved discussions (waiting on @irahopkinson and @rolfheij-sil)

___
*[`package.json` line 59 at r2](https://reviewable.io/reviews/paranext/paranext-core/397#-Nch3XFx5_4GmFX1-5vx:-NcizLWl8Pu07VCSFDTh:b-1pe5yw) ([raw file](https://github.com/paranext/paranext-core/blob/361a91617f100bf64f43919c4ea237c3d738ba9c/package.json#L59)):*
<details><summary><i>Previously, rolfheij-sil wrote…</i></summary><blockquote>

I created some sort of hybrid solution. Just passing down '--fix' doesnt work for the ts/tsx/js/jsx files since we're using prettier to fix them and eslint to lint them. So there's no one-line solution. But this works fine too, and I hope you like it.

Note that lint:staged is still configured to lint and fix, but I'm pretty sure that is what we want, as we discussed with Ira a few days ago
</blockquote></details>

Awesome. Thank you!
___
*[`extensions/package.json` line 29 at r3](https://reviewable.io/reviews/paranext/paranext-core/397#-Ncizkzj5m9tw-Hlibpy:-Ncizkzj5m9tw-Hlibpz:be9ekqh) ([raw file](https://github.com/paranext/paranext-core/blob/fc6a408c35b1d94f6687f823c475a8513f0b63cf/extensions/package.json#L29)):*
> ```JSON
>   "lint-staged": {
>     "*.{cjs,js,jsx,ts,tsx}": [
>       "prettier --config ../.prettierrc.js --ignore-path .prettierignore --write",
> ```

It would probably be best to create a `.prettierrc.js` file that extends the one in the directory above so we don't have to provide this argument everywhere we want to use prettier. Same with `.stylelintrc.js`. Also do you need to provide the `ignore-path`, or is it functional by default?
___
*[`lib/papi-components/package.json` line 38 at r3](https://reviewable.io/reviews/paranext/paranext-core/397#-Ncj-Dks6QJVhaxt6Nw7:-Ncj-Dks6QJVhaxt6Nw8:b-kgcbjj) ([raw file](https://github.com/paranext/paranext-core/blob/fc6a408c35b1d94f6687f823c475a8513f0b63cf/lib/papi-components/package.json#L38)):*
> ```JSON
>     "lint": "npm run lint:scripts && npm run lint:styles",
>     "lint:scripts": "cross-env NODE_ENV=development eslint --ext .cjs,.js,.jsx,.ts,.tsx --cache .",
>     "lint:styles": "stylelint --config ../../.stylelintrc.js --ignore-path .stylelintignore **/*.{css,scss}",
> ```

Same situation here as above - would probably be best to make these files in this directory and have them extend the parent one.
___
*[`lib/papi-dts/package.json` line 33 at r3](https://reviewable.io/reviews/paranext/paranext-core/397#-Ncj-Vkp65XBvDed7Z0s:-Ncj-Vkp65XBvDed7Z0t:b-kgcbjj) ([raw file](https://github.com/paranext/paranext-core/blob/fc6a408c35b1d94f6687f823c475a8513f0b63cf/lib/papi-dts/package.json#L33)):*
> ```JSON
>     "build:fresh": "npm run build:clean && npm run build",
>     "lint": "cross-env NODE_ENV=development eslint --ext .cjs,.js,.jsx,.ts,.tsx --cache .",
>     "lint-fix": "prettier --config ../../.prettierrc.js --ignore-path .eslintignore --write \"**/*.{ts,tsx,js,jsx}\" && npm run lint",
> ```

Same situation here as above - would probably be best to make these files in this directory and have them extend the parent one.

**Review by irahopkinson — APPROVED** [review]
:lgtm: other than TJ's comments. Thanks for all your good work on our build system.

> Reviewed 25 of 25 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/397#-:-NcstROzCYmHVyM0b2if:b-ed7ek8)* status: all files reviewed, 3 unresolved discussions (waiting on @rolfheij-sil)

**Review by tjcouch-sil — CHANGES_REQUESTED** [review]
> Reviewed 10 of 10 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/397)* status: all files reviewed, 1 unresolved discussion (waiting on @rolfheij-sil)

___
*[`extensions/package.json` line 29 at r3](https://reviewable.io/reviews/paranext/paranext-core/397#-Ncizkzj5m9tw-Hlibpy:-NcxLnb33RINYoBJ3fvT:b-tqorwx) ([raw file](https://github.com/paranext/paranext-core/blob/fc6a408c35b1d94f6687f823c475a8513f0b63cf/extensions/package.json#L29)):*
<details><summary><i>Previously, rolfheij-sil wrote…</i></summary><blockquote>

Unfortunately prettier doesn't support extending configs in that way. And I'd rather not copy the config over to all the directories and expect devs to change all of them everytime they make a change.
</blockquote></details>

Thanks for doing this with stylelint!

I realized while reading [this thread](https://github.com/prettier/prettier/issues/3146) about extending prettier config that this is important because VSCode doesn't allow you to specify a prettier configuration path, so we need to use the default and not provide a config command-line argument. Sorry I didn't consider this before.

Looks like prettier added support for [directly referencing another config (PR)](https://github.com/prettier/prettier/pull/5963) by just having the config file contain a quoted string of the path to the actual config file. Alternatively, to achieve actual extension functionality, you can `require` the config you want to extend and use a normal destructure step as is demonstrated in the explanation of that PR. They chose not to add `extends` in the same way as the other tools because it's a very simple config file and doesn't really need more than the destructure method.

**Review by rolfheij-sil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/397)* status: all files reviewed, 1 unresolved discussion (waiting on @tjcouch-sil)

___
*[`extensions/package.json` line 29 at r3](https://reviewable.io/reviews/paranext/paranext-core/397#-Ncizkzj5m9tw-Hlibpy:-Nd0w0_S8yd-8xR0Jlsc:b-d2jgmj) ([raw file](https://github.com/paranext/paranext-core/blob/fc6a408c35b1d94f6687f823c475a8513f0b63cf/extensions/package.json#L29)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

Thanks for doing this with stylelint!

I realized while reading [this thread](https://github.com/prettier/prettier/issues/3146) about extending prettier config that this is important because VSCode doesn't allow you to specify a prettier configuration path, so we need to use the default and not provide a config command-line argument. Sorry I didn't consider this before.

Looks like prettier added support for [directly referencing another config (PR)](https://github.com/prettier/prettier/pull/5963) by just having the config file contain a quoted string of the path to the actual config file. Alternatively, to achieve actual extension functionality, you can `require` the config you want to extend and use a normal destructure step as is demonstrated in the explanation of that PR. They chose not to add `extends` in the same way as the other tools because it's a very simple config file and doesn't really need more than the destructure method.
</blockquote></details>

Yep, the quoted string thing seems to be working! Thanks for figuring that out!

**Review by tjcouch-sil — APPROVED** [review]
:lgtm: thanks for the hard work and patience!

> Reviewed 6 of 6 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/397#-:-Nd1ZhbC45crSa3TsVXZ:b-hyxj35)* status: :shipit: complete! all files reviewed, all discussions resolved

___
*[`extensions/package.json` line 29 at r3](https://reviewable.io/reviews/paranext/paranext-core/397#-Ncizkzj5m9tw-Hlibpy:-Nd1Zdjt2MIEzlOHz52w:b-jt0dpt) ([raw file](https://github.com/paranext/paranext-core/blob/fc6a408c35b1d94f6687f823c475a8513f0b63cf/extensions/package.json#L29)):*
<details><summary><i>Previously, rolfheij-sil wrote…</i></summary><blockquote>

Yep, the quoted string thing seems to be working! Thanks for figuring that out!
</blockquote></details>

Glad to hear :)

**Pull request merged**
