### PR TITLE
Create stub for extension toggle

### PR DESCRIPTION
**Pull request by jolierabideau**
Originally, I misunderstood what this issue was asking. I thought it was asking for a component similar to [`project-list.component.tsx`](https://github.com/paranext/paranext-core/blob/main/src/renderer/components/docking/project-list.component.tsx) that makes a list of extension cards and instead all it needed is what is now written in `extension-toggle.component.tsx`. 

Included is the expected `ExtensionToggle` component for individual Cards and an `ExtensionList` component that maps extensions to lists. Also a tab I labeled Extension Manager (added as floating tab to the layout) so that it will appear easily for testing, but there is no item for it in the application menu. It is made to look like the mockup found [here](https://www.figma.com/proto/GKofaroTFCjBbfnBHzjbm9/Paranext-Extensions?page-id=430%3A774&type=design&node-id=432-4394&viewport=2015%2C713%2C0.57&t=thZfDIsQgbJwwGlw-1&scaling=min-zoom&starting-point-node-id=432%3A4394).

I can remove the currently unneeded pieces and just push the `extension-toggle.component.tsx/scss` if that is preferred.

- - -
This change is [Reviewable](https://reviewable.io/reviews/paranext/paranext-core/400)

### CODE REVIEW

**Review by tjcouch-sil — APPROVED** [review]
:lgtm: thanks for the hard work on this! I think I read somewhere that you're looking for a good place to put these. What do you think of making a new folder `src/renderer/components/extension-manager` for all these?

> Reviewed 8 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/400#-:-Nd1bVmD78mX3X0MS8qr:bjq485d)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by jolierabideau — COMMENTED** [review]
Sounds good, should I do something like that for the project dialogs as well? 

> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/400#-:-Nd1f8vzBYodrT0SwUx8:b-bmb5lg)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by tjcouch-sil — COMMENTED** [review]
Sure if you'd like to!

> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/400#-:-Nd1o1c4BzIsn-rhCQ09:b-x9nl2a)* status: 0 of 8 files reviewed, all discussions resolved

**Review by tjcouch-sil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/400)* status: 0 of 8 files reviewed, 1 unresolved discussion (waiting on @jolierabideau)

___
*[`src/renderer/components/docking/paranext-dock-layout.component.tsx` line 56 at r2](https://reviewable.io/reviews/paranext/paranext-core/400#-Nd1oO9186AZOZSFSSJK:-Nd1oO9186AZOZSFSSJL:by5l1sw) ([raw file](https://github.com/paranext/paranext-core/blob/0856e813df3e43f28c0d46b83e1746566e4e7cce/src/renderer/components/docking/paranext-dock-layout.component.tsx#L56)):*
> ```XML
>   TAB_TYPE_EXTENSION_MANAGER,
>   loadExtensionManagerTab,
> } from '../extension-manager/extension-manager-tab.component';
> ```

Please make this path (and others in this file if you don't mind - sorry I didn't notice before) an aliased path according to the style guide. Like `@renderer/components/extension-manager/...`

**Review by jolierabideau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/400)* status: 0 of 15 files reviewed, 1 unresolved discussion (waiting on @tjcouch-sil)

___
*[`src/renderer/components/docking/paranext-dock-layout.component.tsx` line 56 at r2](https://reviewable.io/reviews/paranext/paranext-core/400#-Nd1oO9186AZOZSFSSJK:-Nd1t3yi-0lotv9xz0yt:b-896fix) ([raw file](https://github.com/paranext/paranext-core/blob/0856e813df3e43f28c0d46b83e1746566e4e7cce/src/renderer/components/docking/paranext-dock-layout.component.tsx#L56)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

Please make this path (and others in this file if you don't mind - sorry I didn't notice before) an aliased path according to the style guide. Like `@renderer/components/extension-manager/...`
</blockquote></details>

Done.

**Review by tjcouch-sil — APPROVED** [review]
:lgtm:

> Reviewed 6 of 8 files at r2, 9 of 9 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/400#-:-Nd28UVW918V9a1aHqpT:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

___
*[`src/renderer/components/docking/paranext-dock-layout.component.tsx` line 56 at r2](https://reviewable.io/reviews/paranext/paranext-core/400#-Nd1oO9186AZOZSFSSJK:-Nd28LVX1WWRl0DIFiTy:b-ucfknh) ([raw file](https://github.com/paranext/paranext-core/blob/0856e813df3e43f28c0d46b83e1746566e4e7cce/src/renderer/components/docking/paranext-dock-layout.component.tsx#L56)):*
<details><summary><i>Previously, jolierabideau wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Thanks!

**Pull request merged**
