### PR TITLE
add shadcn table

### PR DESCRIPTION
**Pull request by Sebastian-ubs**
grafik

This change is [Reviewable](https://reviewable.io/reviews/paranext/paranext-core/932)

### CODE REVIEW

**Review by rolfheij-sil — COMMENTED** [review]
Please rebuild platform-bible-react and add the dist files :)

> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/932#-:-O-66buJCH9QNFnNQjHB:b-ev716r)* status: 0 of 2 files reviewed, all discussions resolved

**Comment by tombogle** [comment]
I would have appreciated knowing this was coming. My [PR](https://github.com/paranext/paranext-core/pull/912) already has this addition. I haven't looked at the details to know if it is the same as mine or conflicts in some way. Is there a need to add this in a separate PR? (Is some other task waiting on this?)

**Comment by Sebastian-ubs** [comment]
@tombogle I am sorry, this was not supposed to put any preasure on anybody. As it looks like we are basing different things on the table right now, I thought it would be helpful to have it in already, so we can fiddle around with solutions idependently. E.g. I wanted to use it to try different options of showing the warnings you made us aware of.

**Comment by tombogle** [comment]
I had not seen all the discussion in Discord when I wrote that.

**Review by rolfheij-sil — APPROVED** [review]
Note that this basic table is now available inside platform-bible-react to be used by other components, but it's not exposed as part of platform-bible-react. The Adazzle table is currently the only table that is exposed to the outside world from platform-bible-react

> Reviewed 1 of 2 files at r1, 6 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/932#-:-O-GfWzr2Rg1gMRlnSR2:b-elbv2r)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

___
*[`lib/platform-bible-react/.eslintrc.cjs` line 20 at r2](https://reviewable.io/reviews/paranext/paranext-core/932#-O-Gf96d-8ZVMUwtutip:-O-Gf96d-8ZVMUwtutiq:bc2lnv3) ([raw file](https://github.com/paranext/paranext-core/blob/e03b385c800a50757a82c069c38cb21cffe89b30/lib/platform-bible-react/.eslintrc.cjs#L20)):*
> ```JavaScript
>         'import/prefer-default-export': 'off',
>         'react/prop-types': 'off',
>         'react/jsx-props-no-spreading': 'off',
> ```

Yeah I guess this is fine for now. Wondering if @tjcouch-sil has an opinion on this?

**Review by Sebastian-ubs — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/932)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

___
*[`lib/platform-bible-react/.eslintrc.cjs` line 20 at r2](https://reviewable.io/reviews/paranext/paranext-core/932#-O-Gf96d-8ZVMUwtutip:-O-GsFMxAI88llaYPIp8:bqo454e) ([raw file](https://github.com/paranext/paranext-core/blob/e03b385c800a50757a82c069c38cb21cffe89b30/lib/platform-bible-react/.eslintrc.cjs#L20)):*
<details><summary><i>Previously, rolfheij-sil (Rolf Heij) wrote…</i></summary><blockquote>

Yeah I guess this is fine for now. Wondering if @tjcouch-sil has an opinion on this?
</blockquote></details>

as @tjcouch-sil added this in https://github.com/paranext/paranext-core/commit/426d2e0eac3a74783d25e0fb350d932cc8fd9122 I guess he won't have a problem with it ;-)

**Review by tjcouch-sil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/932)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

___
*[`lib/platform-bible-react/.eslintrc.cjs` line 20 at r2](https://reviewable.io/reviews/paranext/paranext-core/932#-O-Gf96d-8ZVMUwtutip:-O-IZg23CThb7e3vUuZ0:b-72f0pe) ([raw file](https://github.com/paranext/paranext-core/blob/e03b385c800a50757a82c069c38cb21cffe89b30/lib/platform-bible-react/.eslintrc.cjs#L20)):*
<details><summary><i>Previously, Sebastian-ubs wrote…</i></summary><blockquote>

as @tjcouch-sil added this in https://github.com/paranext/paranext-core/commit/426d2e0eac3a74783d25e0fb350d932cc8fd9122 I guess he won't have a problem with it ;-)
</blockquote></details>

I'd think we would generally want to change the shadcn files as little as possible, so disabling some eslint rules is fine. As long as we don't disable important rules ;)

**Pull request merged**
