### PR TITLE
Added platform.isEditable, filtered Open Scripture Editor and Open Resource Viewer dialogs by isEditable

### PR DESCRIPTION
**Pull request by tjcouch-sil**
Also added exercising buttons on hello world web view. Both should do the same no matter what project you have selected since a project is a project and a resource is a resource.

image

- - -
This change is [Reviewable](https://reviewable.io/reviews/paranext/paranext-core/903)

### CODE REVIEW

**Review by rolfheij-sil — DISMISSED** [review]
Awesome!
One quick question. I noticed this sentence a few times:
`Projects that are not editable are sometimes called "resources"`
Why the 'sometimes'?

> Reviewed 9 of 9 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/903#-:-NyPCUeS1Mv1ALeI9qtN:baasfav)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Review by lyonsil — CHANGES_REQUESTED** [review]
I can't answer why TJ phrased things like this, but I can envision a situation where you are looking at a non-finalized project that you haven't been granted permissions to edit.

> Reviewed 9 of 9 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/903#-:-NyQlekY9SNKVy7Gu3Fw:b-zg12rz)* status: all files reviewed, 2 unresolved discussions (waiting on @tjcouch-sil)

___
*[`c-sharp/Projects/ParatextProjectDataProvider.cs` line 227 at r1](https://reviewable.io/reviews/paranext/paranext-core/903#-NyQmP627DGx89eGetMf:-NyQmP627DGx89eGetMg:bph1b4m) ([raw file](https://github.com/paranext/paranext-core/blob/d0d82049d8ed3eb7eb30ddc32afaad7a6f1f8e9f/c-sharp/Projects/ParatextProjectDataProvider.cs#L227)):*
> ```Smalltalk
>         return settingValue switch
>         {
>             "T" => ResponseToRequest.Succeeded(true),
> ```

Do we know for sure that the only situation where "T" or "F" could be a valid parameter is as a boolean? It seems like this is a very particular mapping for one parameter value, not a general rule to enshrine into parameter reading/writing for all parameters.
___
*[`extensions/src/platform-scripture-editor/src/main.ts` line 59 at r1](https://reviewable.io/reviews/paranext/paranext-core/903#-NyQnu2W003UPK__Jd4i:-NyQnu2W003UPK__Jd4j:bouvf16) ([raw file](https://github.com/paranext/paranext-core/blob/d0d82049d8ed3eb7eb30ddc32afaad7a6f1f8e9f/extensions/src/platform-scripture-editor/src/main.ts#L59)):*
> ```XML
> 
>     projectForWebView.projectId = await papi.dialogs.selectProject({
>       title: `Open ${isReadOnly ? 'Resource Viewer' : 'Scripture Editor'}`,
> ```

`title` and `prompt` should be converted into localized strings at this point.

**Review by tjcouch-sil — COMMENTED** [review]
I phrased it like that because we don't always call non-editable projects resources. The word project includes editable projects and non-editable projects. I think we probably often use the word project to refer to something we would call a resource. As such, sometimes, but not always, we use the word "resource" for a non-editable project. Is that too confusing? We can always change it. I just didn't want to confuse people further than we already are going to by having these two different words in the first place.

> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/903#-:-NyTUiUHDUQbm-AajEfn:bezvadw)* status: 5 of 29 files reviewed, 2 unresolved discussions (waiting on @lyonsil and @rolfheij-sil)

___
*[`c-sharp/Projects/ParatextProjectDataProvider.cs` line 227 at r1](https://reviewable.io/reviews/paranext/paranext-core/903#-NyQmP627DGx89eGetMf:-NyTVhff9uctnT320ABZ:b-cw8hfs) ([raw file](https://github.com/paranext/paranext-core/blob/d0d82049d8ed3eb7eb30ddc32afaad7a6f1f8e9f/c-sharp/Projects/ParatextProjectDataProvider.cs#L227)):*
<details><summary><i>Previously, lyonsil (Matt Lyons) wrote…</i></summary><blockquote>

Do we know for sure that the only situation where "T" or "F" could be a valid parameter is as a boolean? It seems like this is a very particular mapping for one parameter value, not a general rule to enshrine into parameter reading/writing for all parameters.
</blockquote></details>

Good point! I looked at `Settings.xml` and put in the specific ones that seem to be T or F.
___
*[`extensions/src/platform-scripture-editor/src/main.ts` line 59 at r1](https://reviewable.io/reviews/paranext/paranext-core/903#-NyQnu2W003UPK__Jd4i:-NyTnsO99XJwXyY7_a3g:b-jjzbf) ([raw file](https://github.com/paranext/paranext-core/blob/d0d82049d8ed3eb7eb30ddc32afaad7a6f1f8e9f/extensions/src/platform-scripture-editor/src/main.ts#L59)):*
<details><summary><i>Previously, lyonsil (Matt Lyons) wrote…</i></summary><blockquote>

`title` and `prompt` should be converted into localized strings at this point.
</blockquote></details>

Ah good call. Fixed

**Review by lyonsil — DISMISSED** [review]
:lgtm:

> Reviewed 24 of 24 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/903#-:-NyVqA3YAmdtbv6lrBXb:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

___
*[`c-sharp/Projects/ParatextProjectDataProvider.cs` line 227 at r1](https://reviewable.io/reviews/paranext/paranext-core/903#-NyQmP627DGx89eGetMf:-NyVn5ttDH5Xp6tXFlNk:b-ucfknh) ([raw file](https://github.com/paranext/paranext-core/blob/d0d82049d8ed3eb7eb30ddc32afaad7a6f1f8e9f/c-sharp/Projects/ParatextProjectDataProvider.cs#L227)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

Good point! I looked at `Settings.xml` and put in the specific ones that seem to be T or F.
</blockquote></details>

Thanks!
___
*[`extensions/src/platform-scripture-editor/src/main.ts` line 59 at r1](https://reviewable.io/reviews/paranext/paranext-core/903#-NyQnu2W003UPK__Jd4i:-NyVnGdK1AgArXqfdfbL:b-ucfknh) ([raw file](https://github.com/paranext/paranext-core/blob/d0d82049d8ed3eb7eb30ddc32afaad7a6f1f8e9f/extensions/src/platform-scripture-editor/src/main.ts#L59)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

Ah good call. Fixed
</blockquote></details>

Thanks!

**Review by lyonsil — APPROVED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/903)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Pull request merged**
