### PR TITLE
UI language selector (#1250)

### PR DESCRIPTION
**Pull request by tombogle**
This change is [Reviewable](https://reviewable.io/reviews/paranext/paranext-core/1373)

### CODE REVIEW

**Comment by tombogle** [comment]
There is still a bit of work to populate the languages correctly based on available UI languages, but this implementation might be good enough for a first crack. Anyway, the control and its use in settings can be reviewed.

**Comment by tombogle** [comment]
See follow-on task: #1386

**Review by jolierabideau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/1373)* status: 0 of 24 files reviewed, 1 unresolved discussion (waiting on @tombogle)

___
*[`src/renderer/components/settings-tabs/settings-components/setting.component.tsx` line 200 at r4](https://reviewable.io/reviews/paranext/paranext-core/1373#-ODvM57y7tblRVtwXexd:-ODvM57y7tblRVtwXexe:b-o7ey08) ([raw file](https://github.com/paranext/paranext-core/blob/a16f921dc2531356ba3f42621addc250460607fc/src/renderer/components/settings-tabs/settings-components/setting.component.tsx#L200)):*
> ```XML
>       if (Array.isArray(setting) && settingKey === 'platform.interfaceLanguage') {
>         component = (
>           <UiLanguageSelector
> ```

I was thinking you would want to pass `debouncedHandleChange` to your component so that you can use the built in `interfaceLanguageValidator` from `core-settings-info.data.ts`. You might to make some adjustments to the validator, since you can no longer type.

**Review by lyonsil — CHANGES_REQUESTED** [review]
> Reviewed 5 of 19 files at r1, 7 of 17 files at r2, 7 of 11 files at r3, 5 of 5 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/1373)* status: all files reviewed, 6 unresolved discussions (waiting on @tombogle)

___
*[`lib/platform-bible-react/dist/index.d.ts` line 1458 at r4](https://reviewable.io/reviews/paranext/paranext-core/1373#-ODvR2c67jS5PQfa3e1-:-ODvR2c67jS5PQfa3e10:b-q6ys5d) ([raw file](https://github.com/paranext/paranext-core/blob/a16f921dc2531356ba3f42621addc250460607fc/lib/platform-bible-react/dist/index.d.ts#L1458)):*
> ```XML
> };
> export type UiLanguageSelectorProps = {
> 	/** Full set of known languages to display. */
> ```

Are the property names/keys of this object BCP-47 tags? It would be good to clarify this.

Assuming they are BCP-47 tags, is the intent for this list to only have language codes (first part) or language code plus region code or just whatever we or someone else feels like? Like how does it get worked out whether we'd ever want to put `en` only or `en-GB`, `en-NZ`, `en-US`, etc.? Or `es-ES`, `es-MX`, etc.? It would be interesting to understand who/what populates this list. Assuming it ends up being "the list of all locales, with or without region codes, that we have localization resources for," that makes sense to me. Regardless, it would be good to call this out somewhere.
___
*[`lib/platform-bible-react/src/components/advanced/ui-language-selector.component.tsx` line 103 at r4](https://reviewable.io/reviews/paranext/paranext-core/1373#-ODvW38eDapex579lXYE:-ODvW38eDapex579lXYF:bkwst60) ([raw file](https://github.com/paranext/paranext-core/blob/a16f921dc2531356ba3f42621addc250460607fc/lib/platform-bible-react/src/components/advanced/ui-language-selector.component.tsx#L103)):*
> ```XML
>     setSelectedLanguage(code);
>     if (handlePrimaryLanguageChange) handlePrimaryLanguageChange(code);
>     // REVIEW: Should fallback languages be preserved when primary language changes?
> ```

I would think that yes, changing the primary language would not change the fallback languages. If you filter the new primary from the fallback options, then cycling through different primary choices "eats away" all the fallback choices unless you push the former language choice into the fallback options. Ultimately, though, the right behavior of this function is probably defined by the user experience with the control. There isn't necessarily a "right answer" for a function like this on its own.

A function with a signature that doesn't leave ambiguous questions like this would probably just take a whole array of languages as the input. Then you could check if the primary and/or fallback languages actually changed. This is how we work with the USFM editor control and loading USFM.

No matter what the final decision is, this comment should probably be removed before merging.
___
*[`lib/platform-bible-react/src/components/advanced/ui-language-selector.component.tsx` line 111 at r4](https://reviewable.io/reviews/paranext/paranext-core/1373#-ODw9LPe1wERsueAUfJh:-ODw9LPe1wERsueAUfJi:b-e7c9ht) ([raw file](https://github.com/paranext/paranext-core/blob/a16f921dc2531356ba3f42621addc250460607fc/lib/platform-bible-react/src/components/advanced/ui-language-selector.component.tsx#L111)):*
> ```XML
>   };
> 
>   const getLanguageDisplayName = (lang: string, uiLang: string) => {
> ```

It's a little confusing how `lang` and `uiLang` are different and what they are intended to convey. Could you give them more descriptive names and/or add JSDoc-style comments (e.g., `/** ... docs here */`) to clarify the meaning of the parameters?
___
*[`lib/platform-bible-react/src/components/advanced/ui-language-selector.component.tsx` line 122 at r4](https://reviewable.io/reviews/paranext/paranext-core/1373#-ODv_7MC9CXd8ZpRvGUv:-ODv_7MC9CXd8ZpRvGUw:b6docdn) ([raw file](https://github.com/paranext/paranext-core/blob/a16f921dc2531356ba3f42621addc250460607fc/lib/platform-bible-react/src/components/advanced/ui-language-selector.component.tsx#L122)):*
> ```XML
>   };
> 
>   /*   const handleFallbackLanguageClick = () => {
> ```

I assume this was left in accidentally. Should this be removed?
___
*[`lib/platform-bible-react/src/components/advanced/ui-language-selector.component.tsx` line 167 at r4](https://reviewable.io/reviews/paranext/paranext-core/1373#-ODwA0o_6WSjoBfMl-PH:-ODwA0o_6WSjoBfMl-PI:b-8z0aft) ([raw file](https://github.com/paranext/paranext-core/blob/a16f921dc2531356ba3f42621addc250460607fc/lib/platform-bible-react/src/components/advanced/ui-language-selector.component.tsx#L167)):*
> ```XML
>                 : `${knownUiLanguages.en.autonym}`}
>             </Label>
>             {/* <MultiSelector>
> ```

Is this a placeholder for the fallback language UI to be added later? If so, could you add a quick comment to that end?

**Review by rolfheij-sil — CHANGES_REQUESTED** [review]
Nice work, thanks!

> Reviewed 18 of 19 files at r1, 7 of 17 files at r2, 7 of 11 files at r3, 5 of 5 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/1373#-:-ODv-9ts8Kwd03HMd8x5:b-og7e2z)* status: all files reviewed, 10 unresolved discussions (waiting on @tombogle)

___
*[`lib/platform-bible-react/src/components/advanced/ui-language-selector.component.tsx` line 141 at r4](https://reviewable.io/reviews/paranext/paranext-core/1373#-ODwCjIH2TN_AM2zKomQ:-ODwCjIH2TN_AM2zKomR:b-3wcykt) ([raw file](https://github.com/paranext/paranext-core/blob/a16f921dc2531356ba3f42621addc250460607fc/lib/platform-bible-react/src/components/advanced/ui-language-selector.component.tsx#L141)):*
> ```XML
>         <SelectContent
>           // Need to get over the floating web view z-index 200
>           style={{ zIndex: 250 }}
> ```

Better to use tailwind instead of inline css

`className='tw-z-[250]'` should do it 
___
*[`lib/platform-bible-react/src/components/advanced/ui-language-selector.component.tsx` line 160 at r4](https://reviewable.io/reviews/paranext/paranext-core/1373#-ODwC-_DDEoKyFLAQdTP:-ODwC-_DDEoKyFLAQdTQ:b-isiphm) ([raw file](https://github.com/paranext/paranext-core/blob/a16f921dc2531356ba3f42621addc250460607fc/lib/platform-bible-react/src/components/advanced/ui-language-selector.component.tsx#L160)):*
> ```XML
>             {/* Do not localize or "improve". This label is temporary. */}
>             <Label>
>               Currently:{'\u00A0'}
> ```

Better to do this with a template literal string
```
{`Currently: `}
```

And maybe only render this if fallbackLanguages is not empty?

But I see this might only be a temporary label, so non-blocking
___
*[`src/renderer/components/settings-tabs/settings-components/setting.component.tsx` line 117 at r1](https://reviewable.io/reviews/paranext/paranext-core/1373#-ODotf2dEM9b30CjynwB:-ODotf2dEM9b30CjynwC:b-stwwwo) ([raw file](https://github.com/paranext/paranext-core/blob/47c0c7b20f0076f77adc1ca27b02e8133dbc4faa/src/renderer/components/settings-tabs/settings-components/setting.component.tsx#L117)):*
> ```XML
> }: CombinedSettingProps) {
>   const validateSetting = validateUserSetting || validateProjectSetting;
>   const defaultLanguages: Record<string, LanguageInfo> = {
> ```

This needs to be stable, so it should be moved outside of the component (or wrapped in useMemo)
___
*[`src/renderer/components/settings-tabs/settings-components/setting.component.tsx` line 214 at r1](https://reviewable.io/reviews/paranext/paranext-core/1373#-ODoudzo5csrtzehI8Oj:-ODoudzo5csrtzehI8Ok:b-yoosbc) ([raw file](https://github.com/paranext/paranext-core/blob/47c0c7b20f0076f77adc1ca27b02e8133dbc4faa/src/renderer/components/settings-tabs/settings-components/setting.component.tsx#L214)):*
> ```XML
>             fallbackLanguages={setting.slice(1)}
>             handleLanguageChanges={(newUiLanguages) => {
>               if (!isLoadingLanguages) setSetting(newUiLanguages);
> ```

This might silently fail if the languages are loading. Shouldn't it be more explicit in telling the user that setting new UI languages failed in that case?

**Review by tombogle — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/1373)* status: all files reviewed, 10 unresolved discussions (waiting on @jolierabideau, @lyonsil, and @rolfheij-sil)

___
*[`lib/platform-bible-react/dist/index.d.ts` line 1458 at r4](https://reviewable.io/reviews/paranext/paranext-core/1373#-ODvR2c67jS5PQfa3e1-:-ODx0SS4BZr_VRYVcqeQ:bjcazs8) ([raw file](https://github.com/paranext/paranext-core/blob/a16f921dc2531356ba3f42621addc250460607fc/lib/platform-bible-react/dist/index.d.ts#L1458)):*
<details><summary><i>Previously, lyonsil (Matt Lyons) wrote…</i></summary><blockquote>

Are the property names/keys of this object BCP-47 tags? It would be good to clarify this.

Assuming they are BCP-47 tags, is the intent for this list to only have language codes (first part) or language code plus region code or just whatever we or someone else feels like? Like how does it get worked out whether we'd ever want to put `en` only or `en-GB`, `en-NZ`, `en-US`, etc.? Or `es-ES`, `es-MX`, etc.? It would be interesting to understand who/what populates this list. Assuming it ends up being "the list of all locales, with or without region codes, that we have localization resources for," that makes sense to me. Regardless, it would be good to call this out somewhere.
</blockquote></details>

They are BCP-47 tags. For Chinese, we do specifically expect to have two variants. I doubt we'll have two variants of English in Paratext and its official extensions, but I know Transcelerator has en-GB strings. Brazilian Portuguese is enough different from European Portuguese that it could easily justify a distinct variant. I think the fallback logic already automatically falls back to base variants of the language if the user has chose a specific variant/script. In any case, once we implement the Ui to choose fallbacks, they could make that explicit.
___
*[`lib/platform-bible-react/src/components/advanced/ui-language-selector.component.tsx` line 103 at r4](https://reviewable.io/reviews/paranext/paranext-core/1373#-ODvW38eDapex579lXYE:-ODx1lYd0B_I9rXkahSv:b-n432ak) ([raw file](https://github.com/paranext/paranext-core/blob/a16f921dc2531356ba3f42621addc250460607fc/lib/platform-bible-react/src/components/advanced/ui-language-selector.component.tsx#L103)):*
<details><summary><i>Previously, lyonsil (Matt Lyons) wrote…</i></summary><blockquote>

I would think that yes, changing the primary language would not change the fallback languages. If you filter the new primary from the fallback options, then cycling through different primary choices "eats away" all the fallback choices unless you push the former language choice into the fallback options. Ultimately, though, the right behavior of this function is probably defined by the user experience with the control. There isn't necessarily a "right answer" for a function like this on its own.

A function with a signature that doesn't leave ambiguous questions like this would probably just take a whole array of languages as the input. Then you could check if the primary and/or fallback languages actually changed. This is how we work with the USFM editor control and loading USFM.

No matter what the final decision is, this comment should probably be removed before merging.
</blockquote></details>

I believe this is an open UX question and is not going to be resolved in the first pass. That's why I added the REVIEW comment. Maybe we treat REVIEW comments differently in Platform, but in other software I've worked on, we use them to indicate a potentially important decision for future consideration, not just something to be reviewed as part of a PR.
___
*[`lib/platform-bible-react/src/components/advanced/ui-language-selector.component.tsx` line 111 at r4](https://reviewable.io/reviews/paranext/paranext-core/1373#-ODw9LPe1wERsueAUfJh:-ODwmXgM-yQYwTnPUOc7:b-6395qf) ([raw file](https://github.com/paranext/paranext-core/blob/a16f921dc2531356ba3f42621addc250460607fc/lib/platform-bible-react/src/components/advanced/ui-language-selector.component.tsx#L111)):*
<details><summary><i>Previously, lyonsil (Matt Lyons) wrote…</i></summary><blockquote>

It's a little confusing how `lang` and `uiLang` are different and what they are intended to convey. Could you give them more descriptive names and/or add JSDoc-style comments (e.g., `/** ... docs here */`) to clarify the meaning of the parameters?
</blockquote></details>

Commented
___
*[`lib/platform-bible-react/src/components/advanced/ui-language-selector.component.tsx` line 122 at r4](https://reviewable.io/reviews/paranext/paranext-core/1373#-ODv_7MC9CXd8ZpRvGUv:-ODwk42SEf2an68uuJ2D:b-bltwda) ([raw file](https://github.com/paranext/paranext-core/blob/a16f921dc2531356ba3f42621addc250460607fc/lib/platform-bible-react/src/components/advanced/ui-language-selector.component.tsx#L122)):*
<details><summary><i>Previously, lyonsil (Matt Lyons) wrote…</i></summary><blockquote>

I assume this was left in accidentally. Should this be removed?
</blockquote></details>

Initially, the fallback language selection UI was going to be a button that displayed some kind of popover or dialog. But I think you're right. This commented-out stub isn't very helpful now that we don't have any idea what the UI might be. 
___
*[`lib/platform-bible-react/src/components/advanced/ui-language-selector.component.tsx` line 141 at r4](https://reviewable.io/reviews/paranext/paranext-core/1373#-ODwCjIH2TN_AM2zKomQ:-ODx2DS0-vlXqnmDB7aI:b-e7a1nb) ([raw file](https://github.com/paranext/paranext-core/blob/a16f921dc2531356ba3f42621addc250460607fc/lib/platform-bible-react/src/components/advanced/ui-language-selector.component.tsx#L141)):*
<details><summary><i>Previously, rolfheij-sil (Rolf Heij) wrote…</i></summary><blockquote>

Better to use tailwind instead of inline css

`className='tw-z-[250]'` should do it
</blockquote></details>

Funny. I'm 99% sure I beat my brains out trying this to no avail. Today, I tried it again and it worked just fine.
___
*[`lib/platform-bible-react/src/components/advanced/ui-language-selector.component.tsx` line 160 at r4](https://reviewable.io/reviews/paranext/paranext-core/1373#-ODwC-_DDEoKyFLAQdTP:-ODwj5pZ8H6ZSbVKUkF0:b-pskbhc) ([raw file](https://github.com/paranext/paranext-core/blob/a16f921dc2531356ba3f42621addc250460607fc/lib/platform-bible-react/src/components/advanced/ui-language-selector.component.tsx#L160)):*
<details><summary><i>Previously, rolfheij-sil (Rolf Heij) wrote…</i></summary><blockquote>

Better to do this with a template literal string
```
{`Currently: `}
```

And maybe only render this if fallbackLanguages is not empty?

But I see this might only be a temporary label, so non-blocking
</blockquote></details>

Since English is always the ultimate fallback, there's always something to display if English isn't the UI language. Only just barely useful, but this is just a temporary placeholder.
___
*[`lib/platform-bible-react/src/components/advanced/ui-language-selector.component.tsx` line 167 at r4](https://reviewable.io/reviews/paranext/paranext-core/1373#-ODwA0o_6WSjoBfMl-PH:-ODwjfi77A-ih1Y0uQgN:b-896fix) ([raw file](https://github.com/paranext/paranext-core/blob/a16f921dc2531356ba3f42621addc250460607fc/lib/platform-bible-react/src/components/advanced/ui-language-selector.component.tsx#L167)):*
<details><summary><i>Previously, lyonsil (Matt Lyons) wrote…</i></summary><blockquote>

Is this a placeholder for the fallback language UI to be added later? If so, could you add a quick comment to that end?
</blockquote></details>

Done.
___
*[`src/renderer/components/settings-tabs/settings-components/setting.component.tsx` line 214 at r1](https://reviewable.io/reviews/paranext/paranext-core/1373#-ODoudzo5csrtzehI8Oj:-ODwtfj971Y990fg9rSs:bn034cv) ([raw file](https://github.com/paranext/paranext-core/blob/47c0c7b20f0076f77adc1ca27b02e8133dbc4faa/src/renderer/components/settings-tabs/settings-components/setting.component.tsx#L214)):*
<details><summary><i>Previously, rolfheij-sil (Rolf Heij) wrote…</i></summary><blockquote>

This might silently fail if the languages are loading. Shouldn't it be more explicit in telling the user that setting new UI languages failed in that case?
</blockquote></details>

Originally, I was thinking that if the languages were to load slowly and the user chose one from the default list we wouldn't want to recognize that choice as it could lead to something bad. But at least in the current implementation, the list always seems to be loading with no delay, and now that I've correctly hooked up validation, I think we wouldn't care. Anyway, the choices in the little default list should be valid, so I think the  
___
*[`src/renderer/components/settings-tabs/settings-components/setting.component.tsx` line 200 at r4](https://reviewable.io/reviews/paranext/paranext-core/1373#-ODvM57y7tblRVtwXexd:-ODx2nlm2vhbF9CAwwNX:b-896fix) ([raw file](https://github.com/paranext/paranext-core/blob/a16f921dc2531356ba3f42621addc250460607fc/src/renderer/components/settings-tabs/settings-components/setting.component.tsx#L200)):*
<details><summary><i>Previously, jolierabideau wrote…</i></summary><blockquote>

I was thinking you would want to pass `debouncedHandleChange` to your component so that you can use the built in `interfaceLanguageValidator` from `core-settings-info.data.ts`. You might to make some adjustments to the validator, since you can no longer type.
</blockquote></details>

Done.

**Review by tombogle — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/1373)* status: 15 of 24 files reviewed, 10 unresolved discussions (waiting on @jolierabideau, @lyonsil, and @rolfheij-sil)

___
*[`src/renderer/components/settings-tabs/settings-components/setting.component.tsx` line 117 at r1](https://reviewable.io/reviews/paranext/paranext-core/1373#-ODotf2dEM9b30CjynwB:-OE-BxP8Br7PwvGlBUO9:b-896fix) ([raw file](https://github.com/paranext/paranext-core/blob/47c0c7b20f0076f77adc1ca27b02e8133dbc4faa/src/renderer/components/settings-tabs/settings-components/setting.component.tsx#L117)):*
<details><summary><i>Previously, rolfheij-sil (Rolf Heij) wrote…</i></summary><blockquote>

This needs to be stable, so it should be moved outside of the component (or wrapped in useMemo)
</blockquote></details>

Done.

**Review by rolfheij-sil — DISMISSED** [review]
One more small thing, non-blocking

> Reviewed 8 of 9 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/1373#-:-OE-Ds6lEt1-LGZVF2MS:b-hnexta)* status: all files reviewed, 7 unresolved discussions (waiting on @jolierabideau, @lyonsil, and @tombogle)

___
*[`lib/platform-bible-react/src/components/advanced/ui-language-selector.component.tsx` line 87 at r6](https://reviewable.io/reviews/paranext/paranext-core/1373#-OE-DDJ4-mJf-wgAaTvy:-OE-DDJ4-mJf-wgAaTvz:b-8osnq0) ([raw file](https://github.com/paranext/paranext-core/blob/a757510325e0c5b3155f02053d3740a6f0af9945/lib/platform-bible-react/src/components/advanced/ui-language-selector.component.tsx#L87)):*
> ```XML
>   primaryLanguage = 'en',
>   fallbackLanguages = [],
>   onLanguageChanges,
> ```

nit: onLanguageChanges -> onLanguageChange

**Review by lyonsil — DISMISSED** [review]
Thanks for all the updates! :lgtm: 

> Reviewed 8 of 9 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/1373#-:-OE-VjO9EZsf8VjaZLn6:b-oquue6)* status: all files reviewed, 2 unresolved discussions (waiting on @jolierabideau and @tombogle)

___
*[`lib/platform-bible-react/src/components/advanced/ui-language-selector.component.tsx` line 103 at r4](https://reviewable.io/reviews/paranext/paranext-core/1373#-ODvW38eDapex579lXYE:-OE-T7wY10FL_3ymJaOf:b6uc1c5) ([raw file](https://github.com/paranext/paranext-core/blob/a16f921dc2531356ba3f42621addc250460607fc/lib/platform-bible-react/src/components/advanced/ui-language-selector.component.tsx#L103)):*
<details><summary><i>Previously, tombogle (Tom Bogle) wrote…</i></summary><blockquote>

I believe this is an open UX question and is not going to be resolved in the first pass. That's why I added the REVIEW comment. Maybe we treat REVIEW comments differently in Platform, but in other software I've worked on, we use them to indicate a potentially important decision for future consideration, not just something to be reviewed as part of a PR.
</blockquote></details>

Ok - This is not a convention I've seen used elsewhere, but if it's a normal thing at SIL/UBS that makes sense.

I would still assert that:
1) The right answer for the function will depend on the user experience and how it plays a role in that.
2) Having a function that takes the entire array of primary + fallbacks is a less fragile design as it doesn't leave open questions to address in the future like this.

I'm making this as resolved for this PR since it is waiting on UX input.
___
*[`lib/platform-bible-react/src/components/advanced/ui-language-selector.component.tsx` line 111 at r4](https://reviewable.io/reviews/paranext/paranext-core/1373#-ODw9LPe1wERsueAUfJh:-OE-UPNx5k4-wlQQQl1J:bf0rl6w) ([raw file](https://github.com/paranext/paranext-core/blob/a16f921dc2531356ba3f42621addc250460607fc/lib/platform-bible-react/src/components/advanced/ui-language-selector.component.tsx#L111)):*
<details><summary><i>Previously, tombogle (Tom Bogle) wrote…</i></summary><blockquote>

Commented
</blockquote></details>

Thanks, this is very clear!

**Review by jolierabideau — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/1373)* status: all files reviewed, 1 unresolved discussion (waiting on @tombogle)

**Review by tombogle — COMMENTED** [review]
I'm not sure we'd ever want/need/expect a second control that was also hooked up to the same setting. Certainly an extension could display the control and have it hooked up to some kind of override setting relevant only to that extension. (For example, Transcelerator has separate versions of English questions in British English, but if a user chooses British English for the Transcelerator questions, it doesn't change the default UI language in Paratext.) But maybe you're thinking of the idea of putting an interface language picker on the toolbar as well as having one in the settings...? If we do that, we'll definitely want to keep them in sync. @tjcouch-sil or @lyonsil could probably weigh in on the question of how difficult that would be. Presumably it would be essentially what is needed to also get the UI to be able to be more fully responsive to a change in the UI language. 

> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/1373#-:-OE-t2ByCsGBGrQ1uhUn:b-16fio8)* status: all files reviewed, 1 unresolved discussion (waiting on @rolfheij-sil)

___
*[`lib/platform-bible-react/src/components/advanced/ui-language-selector.component.tsx` line 103 at r4](https://reviewable.io/reviews/paranext/paranext-core/1373#-ODvW38eDapex579lXYE:-OE-visM0Jwg_GNsXdbE:b-82qp6n) ([raw file](https://github.com/paranext/paranext-core/blob/a16f921dc2531356ba3f42621addc250460607fc/lib/platform-bible-react/src/components/advanced/ui-language-selector.component.tsx#L103)):*
<details><summary><i>Previously, lyonsil (Matt Lyons) wrote…</i></summary><blockquote>

Ok - This is not a convention I've seen used elsewhere, but if it's a normal thing at SIL/UBS that makes sense.

I would still assert that:
1) The right answer for the function will depend on the user experience and how it plays a role in that.
2) Having a function that takes the entire array of primary + fallbacks is a less fragile design as it doesn't leave open questions to address in the future like this.

I'm making this as resolved for this PR since it is waiting on UX input.
</blockquote></details>

It may very well be that we should just scrap onPrimaryLanguageChange and onFallbackLanguagesChange entirely. Currently, they are only used in the example. Even if we do that, we'll still need to get the behavior to make sense for the user. My gut feeling is that if the user changes the primary language, they would most likely expect that to clear any fallback languages also. But there could be edge cases where that doesn't make sense.
___
*[`lib/platform-bible-react/src/components/advanced/ui-language-selector.component.tsx` line 87 at r6](https://reviewable.io/reviews/paranext/paranext-core/1373#-OE-DDJ4-mJf-wgAaTvy:-OE-uelx8-hn3_UV-t7R:b-invwb4) ([raw file](https://github.com/paranext/paranext-core/blob/a757510325e0c5b3155f02053d3740a6f0af9945/lib/platform-bible-react/src/components/advanced/ui-language-selector.component.tsx#L87)):*
<details><summary><i>Previously, rolfheij-sil (Rolf Heij) wrote…</i></summary><blockquote>

nit: onLanguageChanges -> onLanguageChange
</blockquote></details>

I made it plural because it covers changes to either the primary language, fallback language(s) or both. Clearly, I was not consistent though, because onFallbackLanguagesChange outs the plural on Languages, not on Changes. Thinking about it critically, the event fires once per "change" (even if that change affects more than one language), so it probably really should be onLanguagesChange, but that sounds weird to my ear. Maybe I should just make it onChange.

**Review by Sebastian-ubs — COMMENTED** [review]
I'm not actually looking for a way to have 2 controls there, just wondering if testing with two controls next to each other, having the same input but not syncing, reveals a problem here...?

> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/1373#-:-OE08Taw-Pe8YjkIRqEM:b-x50lo0)* status: all files reviewed, 1 unresolved discussion (waiting on @rolfheij-sil)

**Review by tombogle — COMMENTED** [review]
Got it. Yes, I see that selectedLanguage and primaryLanguage are being used interchangeably, when there's no actual guarantee that they would be kept in sync. To best illustrate the correct behavior, I think we want three of these controls: two tied together (using the same underlying setting) and one that is independent.

> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/1373#-:-OE0bUug9i3RQRcL65UV:b-4n39vl)* status: 15 of 24 files reviewed, 1 unresolved discussion (waiting on @lyonsil and @rolfheij-sil)

**Review by lyonsil — DISMISSED** [review]
Related to Tom's message where I was tagged, the `useSetting` hook should be used by the webviews that use this control to show the UI language settings. If that is used, then if one UI updates the setting, the other UI should see the change and redraw itself with the new setting. There is no technical problem with showing the same setting in more than one place in the UI.

Having said this, using this hook is not sufficient to remove the need to restart the application when the setting changes. There is a lot of non-React code that cannot use the React hook and for which it is not practical to monitor this one setting. We should require the application to restart when this setting changes.

> Reviewed 9 of 9 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/1373#-:-OE-ywAwBnWIEY8TEIku:bwqzw8g)* status: all files reviewed, 1 unresolved discussion (waiting on @rolfheij-sil)

**Review by rolfheij-sil — APPROVED** [review]
> Reviewed 9 of 9 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/1373)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Review by Sebastian-ubs — COMMENTED** [review]
looks good :-)

> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/1373#-:-OEEr7ai7sKiNW4QLyUy:b-epym3g)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Review by rolfheij-sil — APPROVED** [review]
:lgtm:

> Reviewed 6 of 6 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/1373#-:-OEF3C_XDe9eZSdHkwSF:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Pull request merged**
