### PR TITLE
Replace {unsubscriber, promise} with Promise<UnsubscriberAsync>

### PR DESCRIPTION
**Pull request by lyonsil**
This change is [Reviewable](https://reviewable.io/reviews/paranext/paranext-core/202)

### CODE REVIEW

**Review by irahopkinson — CHANGES_REQUESTED** [review]
Just 2 questions.

> Reviewed 9 of 9 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/202#-:-NW0f_Am4PKjlhNLr6dP:b-m79nm)* status: all files reviewed, 4 unresolved discussions (waiting on @lyonsil)

___
*[`extensions/lib/hello-someone/hello-someone.ts` line 66 at r1](https://reviewable.io/reviews/paranext/paranext-core/202#-NW0Yo1A87luhr5xFUpq:-NW0Yo1A87luhr5xFUpr:bro5w4b) ([raw file](https://github.com/paranext/paranext-core/blob/15348b0ffb5e410a94f584afc71801ca65b7c782/extensions/lib/hello-someone/hello-someone.ts#L66)):*
> ```XML
>   );
> 
>   const unsubPromises: Promise<UnsubscriberAsync>[] = [
> ```

FYI thanks for adding the type here - it makes it easier to understand.
___
*[`extensions/lib/hello-someone/hello-someone.ts` line 70 at r1](https://reviewable.io/reviews/paranext/paranext-core/202#-NW0W1AJAgeBLtGBefb8:-NW0W1AJAgeBLtGBefb9:batv07p) ([raw file](https://github.com/paranext/paranext-core/blob/15348b0ffb5e410a94f584afc71801ca65b7c782/extensions/lib/hello-someone/hello-someone.ts#L70)):*
> ```XML
>       return `Hello ${someone}!`;
>     }),
>     papi.commands.registerCommand('hello-someone.echo-someone-renderer', async (msg: string) => {
> ```

BTW I don't see the advantage in abbreviating this. The un-abbrevaited seems clearer to me.



_Code quote:_
```XML
msg
```
___
*[`extensions/lib/hello-someone/hello-someone.ts` line 86 at r1](https://reviewable.io/reviews/paranext/paranext-core/202#-NW0bZNDEk72N6N3GT3C:-NW0bZNEDcsGoehsAe3-:b-k7058e) ([raw file](https://github.com/paranext/paranext-core/blob/15348b0ffb5e410a94f584afc71801ca65b7c782/extensions/lib/hello-someone/hello-someone.ts#L86)):*
> ```XML
> 
>   return papi.util.aggregateUnsubscriberAsyncs(
>     (await Promise.all(unsubPromises)).concat([greetingsDataProvider.dispose]),
> ```

Err... this looks like it is now unsubscribing from everything before returning rather than returning all the promises it needs to unsubscribe from. Is that the intention here?
___
*[`src/shared/services/network-object.service.ts` line 413 at r1](https://reviewable.io/reviews/paranext/paranext-core/202#-NW0dFLE54vAL8QU4RMu:-NW0dFLE54vAL8QU4RMv:b-dx3u0y) ([raw file](https://github.com/paranext/paranext-core/blob/15348b0ffb5e410a94f584afc71801ca65b7c782/src/shared/services/network-object.service.ts#L413)):*
> ```XML
>           unregisterRequestHandlerPromises.push(
>             // Run the unsubscriber for this registration
>             (await unsubPromises[registrationIndex])(),
> ```

`await` inside a `forEach` so it won't wait outside the `forEach`. Is that the intent?
___
*[`src/shared/services/web-view.service.ts` line 305 at r1](https://reviewable.io/reviews/paranext/paranext-core/202#-NW0evCn9PAkMmIvohn1:-NW0evCn9PAkMmIvohn2:b65855e) ([raw file](https://github.com/paranext/paranext-core/blob/15348b0ffb5e410a94f584afc71801ca65b7c782/src/shared/services/web-view.service.ts#L305)):*
> ```XML
> 
>       // On closing, try to remove command listeners
>       // TODO: should do this on the server when the connection closes or when the server exits as well
> ```

BTW Can this section of the comment be removed since it now appears to do this on the server when a connection closes?



_Code quote:_
```XML
when the connection closes or 
```

**Review by lyonsil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/202)* status: all files reviewed, 4 unresolved discussions (waiting on @lyonsil)

___
*[`extensions/lib/hello-someone/hello-someone.ts` line 70 at r1](https://reviewable.io/reviews/paranext/paranext-core/202#-NW0W1AJAgeBLtGBefb8:-NW2lAGI34fu-6SmItME:b-fgknla) ([raw file](https://github.com/paranext/paranext-core/blob/15348b0ffb5e410a94f584afc71801ca65b7c782/extensions/lib/hello-someone/hello-someone.ts#L70)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

BTW I don't see the advantage in abbreviating this. The un-abbrevaited seems clearer to me.
</blockquote></details>

It was purely about trying to avoid having the code reformatting to add more lines.  `msg` is shorter than `message`, and leaving the type annotation along with the non-abbreviated name forces it over the 100 character line limit.  I very commonly have seen "message" shortened to "msg" in the past and thought it looked nicer to avoid extra breaks and formatting.  I can change it back.  Not a big deal.  I could just remove the type annotations, too, to avoid the line wraps.  I was in a state at one point where I got warnings because VSCode thought the parameter was of type `any`and it didn't like that, so I added the `string` annotation. I think that had something to do with a weird `papi.d.ts` that was arouind temporarily, so the warning will probably go away even without the type annotation.
___
*[`extensions/lib/hello-someone/hello-someone.ts` line 86 at r1](https://reviewable.io/reviews/paranext/paranext-core/202#-NW0bZNDEk72N6N3GT3C:-NW2nwLd4N8WFCyJFtW5:b-2da3el) ([raw file](https://github.com/paranext/paranext-core/blob/15348b0ffb5e410a94f584afc71801ca65b7c782/extensions/lib/hello-someone/hello-someone.ts#L86)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

Err... this looks like it is now unsubscribing from everything before returning rather than returning all the promises it needs to unsubscribe from. Is that the intention here?
</blockquote></details>

`unsubPromises` is of type `Promise<UnsubscriberAsync>[]`.  Resolving the promise should give me the unsubscriber function, not run it, right?  If so, I'm not actually running the unsubscribers here, just getting the functions.  Having said that, I'm not actually getting the functions with `Promise.all`.  I'm just making sure the functions resolve.  I'll need to change this anyway.
___
*[`src/shared/services/network-object.service.ts` line 413 at r1](https://reviewable.io/reviews/paranext/paranext-core/202#-NW0dFLE54vAL8QU4RMu:-NW2nQm47oBfq5rj95DO:b-xg4fzw) ([raw file](https://github.com/paranext/paranext-core/blob/15348b0ffb5e410a94f584afc71801ca65b7c782/src/shared/services/network-object.service.ts#L413)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

`await` inside a `forEach` so it won't wait outside the `forEach`. Is that the intent?
</blockquote></details>

It's good to point this out.  I probably should drop the `await` here because I don't think it does anything.  The old code didn't really wait at the top level either, though, so maybe dropping the `await` will be enough.  I'll look at it more closely.
___
*[`src/shared/services/web-view.service.ts` line 305 at r1](https://reviewable.io/reviews/paranext/paranext-core/202#-NW0evCn9PAkMmIvohn1:-NW2mq8O9F0qhLx7O2Xc:b9t28i9) ([raw file](https://github.com/paranext/paranext-core/blob/15348b0ffb5e410a94f584afc71801ca65b7c782/src/shared/services/web-view.service.ts#L305)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

BTW Can this section of the comment be removed since it now appears to do this on the server when a connection closes?
</blockquote></details>

I will have to look at this more deeply.

FWIW, part of the current service pattern is that sometimes functions are run on servers and clients even though they don't do anything because the API implemented by service providers is the same as the client.  I think we will touch on this in the server/client discussion later today.

**Review by tjcouch-sil — CHANGES_REQUESTED** [review]
Wow, quick and great work on this!! Super excited to put the axe to the root of this one. Thank you very much! Just a couple things.

> Reviewed 9 of 9 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/202#-:-NW2y2Wq0i2DZzWI8sav:b-6utfbb)* status: all files reviewed, 6 unresolved discussions (waiting on @lyonsil)

___
*[`extensions/lib/hello-someone/hello-someone.ts` line 70 at r1](https://reviewable.io/reviews/paranext/paranext-core/202#-NW0W1AJAgeBLtGBefb8:-NW2rP8W0WLqUHekMHgv:bqtmjsc) ([raw file](https://github.com/paranext/paranext-core/blob/15348b0ffb5e410a94f584afc71801ca65b7c782/extensions/lib/hello-someone/hello-someone.ts#L70)):*
<details><summary><i>Previously, lyonsil wrote…</i></summary><blockquote>

It was purely about trying to avoid having the code reformatting to add more lines.  `msg` is shorter than `message`, and leaving the type annotation along with the non-abbreviated name forces it over the 100 character line limit.  I very commonly have seen "message" shortened to "msg" in the past and thought it looked nicer to avoid extra breaks and formatting.  I can change it back.  Not a big deal.  I could just remove the type annotations, too, to avoid the line wraps.  I was in a state at one point where I got warnings because VSCode thought the parameter was of type `any`and it didn't like that, so I added the `string` annotation. I think that had something to do with a weird `papi.d.ts` that was arouind temporarily, so the warning will probably go away even without the type annotation.
</blockquote></details>

Actually you need the type annotation here. `registerCommand` doesn't have any type info assocated with the function you give it, so you have to provide your own. Sorry I missed adding types here - not sure how I missed it. Thanks for adding them! I have no comment on `msg` vs `message`; just clarifying that these type annotations are good.
___
*[`extensions/lib/hello-someone/hello-someone.ts` line 86 at r1](https://reviewable.io/reviews/paranext/paranext-core/202#-NW0bZNDEk72N6N3GT3C:-NW2s7KG-vNzXgFxHH33:b-jr53cq) ([raw file](https://github.com/paranext/paranext-core/blob/15348b0ffb5e410a94f584afc71801ca65b7c782/extensions/lib/hello-someone/hello-someone.ts#L86)):*
<details><summary><i>Previously, lyonsil wrote…</i></summary><blockquote>

`unsubPromises` is of type `Promise<UnsubscriberAsync>[]`.  Resolving the promise should give me the unsubscriber function, not run it, right?  If so, I'm not actually running the unsubscribers here, just getting the functions.  Having said that, I'm not actually getting the functions with `Promise.all`.  I'm just making sure the functions resolve.  I'll need to change this anyway.
</blockquote></details>

I believe this code is correct. `Promise.all` on the `unsubPromises` should return an array of unsubscriber functions, which you concat with the greetings data provider's dispose, then you aggregate and return that array of unsub functions in `activate`. That should be good unless I'm misunderstanding or misreading something.
___
*[`extensions/lib/quick-verse/quick-verse.ts` line 167 at r1](https://reviewable.io/reviews/paranext/paranext-core/202#-NW2t3Qw5AMzchywJXf9:-NW2t3Qw5AMzchywJXfA:blnwlwi) ([raw file](https://github.com/paranext/paranext-core/blob/15348b0ffb5e410a94f584afc71801ca65b7c782/extensions/lib/quick-verse/quick-verse.ts#L167)):*
> ```XML
>   });
> 
>   logger.info('Quick Verse is finished activating!');
> ```

Technically, you should be awaiting the `unsubPromises` before running this log because you don't actually know if everything worked until those promises resolve (meaning you successfully registered the command or whatever else the function was). It would be good to put this log in the right place to help people reading the code to understand what's going on. However, it isn't essential, so you can just remove the log if you prefer. Besides, this pattern will probably change with #54 since you made the context object that goes into extensions' `activate` functions. :)

This applies to all extension files.
___
*[`src/shared/services/network-object.service.ts` line 413 at r1](https://reviewable.io/reviews/paranext/paranext-core/202#-NW0dFLE54vAL8QU4RMu:-NW2uNHaBGLbYtSxsQbv:b-muu45s) ([raw file](https://github.com/paranext/paranext-core/blob/15348b0ffb5e410a94f584afc71801ca65b7c782/src/shared/services/network-object.service.ts#L413)):*
<details><summary><i>Previously, lyonsil wrote…</i></summary><blockquote>

It's good to point this out.  I probably should drop the `await` here because I don't think it does anything.  The old code didn't really wait at the top level either, though, so maybe dropping the `await` will be enough.  I'll look at it more closely.
</blockquote></details>

Yeah, the old code didn't await either. Basically the registration failed, so let's unsub as fast as we can and throw an error as fast as we can. We don't really need to wait for the unsubs to finish before throwing an error. Besides, if unsubbing throws an error, we've lost all hope at that point :joy:
___
*[`src/shared/services/network.service.ts` line 241 at r1](https://reviewable.io/reviews/paranext/paranext-core/202#-NW2v_LP9flKXKfamvm_:-NW2v_LP9flKXKfamvma:bbrvyr3) ([raw file](https://github.com/paranext/paranext-core/blob/15348b0ffb5e410a94f584afc71801ca65b7c782/src/shared/services/network.service.ts#L241)):*
> ```XML
>   handlerType?: RequestHandlerType,
> ): Promise<UnsubscriberAsync>;
> async function registerRequestHandlerUnsafe(
> ```

Great refactor! This simplifies the code here so much :) thanks!!
___
*[`src/shared/services/web-view.service.ts` line 305 at r1](https://reviewable.io/reviews/paranext/paranext-core/202#-NW0evCn9PAkMmIvohn1:-NW2w0vAD5KywsoeJT-t:b-62e8jt) ([raw file](https://github.com/paranext/paranext-core/blob/15348b0ffb5e410a94f584afc71801ca65b7c782/src/shared/services/web-view.service.ts#L305)):*
<details><summary><i>Previously, lyonsil wrote…</i></summary><blockquote>

I will have to look at this more deeply.

FWIW, part of the current service pattern is that sometimes functions are run on servers and clients even though they don't do anything because the API implemented by service providers is the same as the client.  I think we will touch on this in the server/client discussion later today.
</blockquote></details>

Actually I believe this does not work (it threw errors in the console when I had it like this a long time ago before I put `isRenderer` on it). `window` is not available on the server. It is a browser-only thing. There are different things you have to do to run code on closing a node process. I would argue we should put `isRenderer` back in and address this situation as a separate issue in #115
___
*[`src/shared/utils/papi-util.ts` line 55 at r1](https://reviewable.io/reviews/paranext/paranext-core/202#-NW2wbIK6HYhM32yNBDA:-NW2wbIK6HYhM32yNBDB:bfuxu31) ([raw file](https://github.com/paranext/paranext-core/blob/15348b0ffb5e410a94f584afc71801ca65b7c782/src/shared/utils/papi-util.ts#L55)):*
> ```XML
>  * @returns safe version of an unsafe function that returns a promise to an UnsubscriberAsync (meaning it will wait to register until the service is initialized)
>  */
> export const createSafeRegisterFn = <TParam extends Array<unknown>>(
> ```

Do we need this utility function anymore? I would argue this isn't useful anymore. It's very easy to make a safe register function without `UnsubPromiseAsync`s. Just do the following:

```typescript
async function safeRegister(whatever) {
  await initialize();
  return unsafeRegister(whatever);
}
```

This pattern already exists elsewhere, so I suggest we go ahead and use it in places where `createSafeRegisterFn` is currently being used as I feel this utility function is confusing.

That being said, that would be unnecessary additional refactor, so you can do this or not do it. Either way is fine.

**Review by lyonsil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/202)* status: all files reviewed, 4 unresolved discussions (waiting on @irahopkinson and @tjcouch-sil)

___
*[`extensions/lib/hello-someone/hello-someone.ts` line 86 at r1](https://reviewable.io/reviews/paranext/paranext-core/202#-NW0bZNDEk72N6N3GT3C:-NW3AlAA8eCvXBub5YxV:bxrtwqc) ([raw file](https://github.com/paranext/paranext-core/blob/15348b0ffb5e410a94f584afc71801ca65b7c782/extensions/lib/hello-someone/hello-someone.ts#L86)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

I believe this code is correct. `Promise.all` on the `unsubPromises` should return an array of unsubscriber functions, which you concat with the greetings data provider's dispose, then you aggregate and return that array of unsub functions in `activate`. That should be good unless I'm misunderstanding or misreading something.
</blockquote></details>

It's Monday morning. :smile: My brain was better in sync with things on Friday.  Yes, I think this is right.
___
*[`extensions/lib/quick-verse/quick-verse.ts` line 167 at r1](https://reviewable.io/reviews/paranext/paranext-core/202#-NW2t3Qw5AMzchywJXf9:-NW3BuRfBsn5GxJPpUnH:b-896fix) ([raw file](https://github.com/paranext/paranext-core/blob/15348b0ffb5e410a94f584afc71801ca65b7c782/extensions/lib/quick-verse/quick-verse.ts#L167)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

Technically, you should be awaiting the `unsubPromises` before running this log because you don't actually know if everything worked until those promises resolve (meaning you successfully registered the command or whatever else the function was). It would be good to put this log in the right place to help people reading the code to understand what's going on. However, it isn't essential, so you can just remove the log if you prefer. Besides, this pattern will probably change with #54 since you made the context object that goes into extensions' `activate` functions. :)

This applies to all extension files.
</blockquote></details>

Done.
___
*[`src/shared/services/network-object.service.ts` line 413 at r1](https://reviewable.io/reviews/paranext/paranext-core/202#-NW0dFLE54vAL8QU4RMu:-NW3C9KHCc2ibyZo7h8r:b-tha2b3) ([raw file](https://github.com/paranext/paranext-core/blob/15348b0ffb5e410a94f584afc71801ca65b7c782/src/shared/services/network-object.service.ts#L413)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

Yeah, the old code didn't await either. Basically the registration failed, so let's unsub as fast as we can and throw an error as fast as we can. We don't really need to wait for the unsubs to finish before throwing an error. Besides, if unsubbing throws an error, we've lost all hope at that point :joy:
</blockquote></details>

Actually the `await` is needed here.  `unsubPromises` is an array of `Promise<UnsubscriberAsync>`.  We are trying to run the unsubscribers.  So in order to get the unsubscriber, we have to `await` first.  After that we can run it.

Another case of my brain being more on top of things on a Friday afternoon than Monday morning!
___
*[`src/shared/services/web-view.service.ts` line 305 at r1](https://reviewable.io/reviews/paranext/paranext-core/202#-NW0evCn9PAkMmIvohn1:-NW3D9De8Ui-tbMQSKQa:b-b465bw) ([raw file](https://github.com/paranext/paranext-core/blob/15348b0ffb5e410a94f584afc71801ca65b7c782/src/shared/services/web-view.service.ts#L305)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

Actually I believe this does not work (it threw errors in the console when I had it like this a long time ago before I put `isRenderer` on it). `window` is not available on the server. It is a browser-only thing. There are different things you have to do to run code on closing a node process. I would argue we should put `isRenderer` back in and address this situation as a separate issue in #115
</blockquote></details>

The reason I removed the `isRenderer` block here is that we're already inside of an `isRenderer` block (line 295).  The one I removed was redundant unless somehow `isRenderer` can be true on line 295 but false on line 306.  If that can happen, I'm really confused.

Per TJ's comment, I'm not going to look deeper into running this on the server for now since there is a separate issue (115) that TJ points out above.
___
*[`src/shared/utils/papi-util.ts` line 55 at r1](https://reviewable.io/reviews/paranext/paranext-core/202#-NW2wbIK6HYhM32yNBDA:-NW3EBUnDMcLLwkmP2Z-:b5towqt) ([raw file](https://github.com/paranext/paranext-core/blob/15348b0ffb5e410a94f584afc71801ca65b7c782/src/shared/utils/papi-util.ts#L55)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

Do we need this utility function anymore? I would argue this isn't useful anymore. It's very easy to make a safe register function without `UnsubPromiseAsync`s. Just do the following:

```typescript
async function safeRegister(whatever) {
  await initialize();
  return unsafeRegister(whatever);
}
```

This pattern already exists elsewhere, so I suggest we go ahead and use it in places where `createSafeRegisterFn` is currently being used as I feel this utility function is confusing.

That being said, that would be unnecessary additional refactor, so you can do this or not do it. Either way is fine.
</blockquote></details>

I think I'm going to leave this one alone for now since it is being used in a couple of places.  I'd rather keep this refactor scoped as originally intended.

**Review by tjcouch-sil — APPROVED** [review]
:lgtm: Thanks for the hard work!

> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/202#-:-NW4E_JoATdz7CP7B4Tk:b-k3rkdz)* status: all files reviewed, 2 unresolved discussions (waiting on @irahopkinson)

___
*[`src/shared/services/network-object.service.ts` line 413 at r1](https://reviewable.io/reviews/paranext/paranext-core/202#-NW0dFLE54vAL8QU4RMu:-NW4De_V4XE_Cvgz8dYQ:bqhtoi5) ([raw file](https://github.com/paranext/paranext-core/blob/15348b0ffb5e410a94f584afc71801ca65b7c782/src/shared/services/network-object.service.ts#L413)):*
<details><summary><i>Previously, lyonsil wrote…</i></summary><blockquote>

Actually the `await` is needed here.  `unsubPromises` is an array of `Promise<UnsubscriberAsync>`.  We are trying to run the unsubscribers.  So in order to get the unsubscriber, we have to `await` first.  After that we can run it.

Another case of my brain being more on top of things on a Friday afternoon than Monday morning!
</blockquote></details>

It seems we're not actually using the results of those promises anywhere. That's what I was talking about when I said we don't need to wait for these unsubs to finish. Maybe we can talk on Discord to clarify.
___
*[`src/shared/services/web-view.service.ts` line 305 at r1](https://reviewable.io/reviews/paranext/paranext-core/202#-NW0evCn9PAkMmIvohn1:-NW4E94QEmLSE61XaodE:byggsvj) ([raw file](https://github.com/paranext/paranext-core/blob/15348b0ffb5e410a94f584afc71801ca65b7c782/src/shared/services/web-view.service.ts#L305)):*
<details><summary><i>Previously, lyonsil wrote…</i></summary><blockquote>

The reason I removed the `isRenderer` block here is that we're already inside of an `isRenderer` block (line 295).  The one I removed was redundant unless somehow `isRenderer` can be true on line 295 but false on line 306.  If that can happen, I'm really confused.

Per TJ's comment, I'm not going to look deeper into running this on the server for now since there is a separate issue (115) that TJ points out above.
</blockquote></details>

Oh yeah, sorry; didn't see that before. Maybe I copy/pasted it in both places on accident.
___
*[`src/shared/utils/papi-util.ts` line 55 at r1](https://reviewable.io/reviews/paranext/paranext-core/202#-NW2wbIK6HYhM32yNBDA:-NW4EKY36f5KT22ygoa5:b-fpxeno) ([raw file](https://github.com/paranext/paranext-core/blob/15348b0ffb5e410a94f584afc71801ca65b7c782/src/shared/utils/papi-util.ts#L55)):*
<details><summary><i>Previously, lyonsil wrote…</i></summary><blockquote>

I think I'm going to leave this one alone for now since it is being used in a couple of places.  I'd rather keep this refactor scoped as originally intended.
</blockquote></details>

Removing this was part of my mental scope for the refactor, but I didn't write it out ;) this is fine.

**Review by irahopkinson — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/202)* status: all files reviewed, 1 unresolved discussion (waiting on @tjcouch-sil)

___
*[`extensions/lib/hello-someone/hello-someone.ts` line 86 at r1](https://reviewable.io/reviews/paranext/paranext-core/202#-NW0bZNDEk72N6N3GT3C:-NW4mAf38rTLDC35qU95:b-qqo3de) ([raw file](https://github.com/paranext/paranext-core/blob/15348b0ffb5e410a94f584afc71801ca65b7c782/extensions/lib/hello-someone/hello-someone.ts#L86)):*
<details><summary><i>Previously, lyonsil wrote…</i></summary><blockquote>

It's Monday morning. :smile: My brain was better in sync with things on Friday.  Yes, I think this is right.
</blockquote></details>

Thanks, makes sense, I didn't noodle it out enough. I like that logger now happens after all those promises have resolved.
___
*[`src/shared/services/network-object.service.ts` line 413 at r1](https://reviewable.io/reviews/paranext/paranext-core/202#-NW0dFLE54vAL8QU4RMu:-NW4oucg-_buC1BJ6k-F:bj4jlga) ([raw file](https://github.com/paranext/paranext-core/blob/15348b0ffb5e410a94f584afc71801ca65b7c782/src/shared/services/network-object.service.ts#L413)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

It seems we're not actually using the results of those promises anywhere. That's what I was talking about when I said we don't need to wait for these unsubs to finish. Maybe we can talk on Discord to clarify.
</blockquote></details>

As @tjcouch-sil says we don't need to push to `unregisterRequestHandlerPromises` since the array is never used, so that should be removed. However with `forEach` that is now `async` you can't ensure that `rejectedRequestHandlerReasons` is populated before the `throw` below.

**Review by tjcouch-sil — APPROVED** [review]
> Reviewed 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/202)* status: all files reviewed, 1 unresolved discussion (waiting on @irahopkinson)

**Review by irahopkinson — APPROVED** [review]
:lgtm: thanks!

> Reviewed 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/202#-:-NW9TBut9fd9etsk6V3g:brfqlux)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @lyonsil)

**Pull request merged**
