### PR TITLE
security update `@sillsdev/scripture`

### PR DESCRIPTION
**Pull request by irahopkinson**
- also update other npm packages

- - -
This change is [Reviewable](https://reviewable.io/reviews/paranext/paranext-core/780)

### CODE REVIEW

**Review by tjcouch-sil — APPROVED** [review]
:lgtm:

> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/780#-:-NrHbl1gAKa5gAtUo7gl:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Comment by irahopkinson** [comment]
*[`package.json` line 160 at r2](https://reviewable.io/reviews/paranext/paranext-core/780#-NrLPEfq6b4jsVqqFpK3:-NrW_MJZ36VKaRVJFtrc:b23pxr9) ([raw file](https://github.com/paranext/paranext-core/blob/c6cd017f0f3675ca620de31e083b652ce99c447a/package.json#L160)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

What was broken that this fixed? I don't see any occurrences of `core-js` in our code outside this line other than in ignored files (there are a couple of references in built code to things like `core-js/library` and `__core-js_shared__`, whatever those things mean). To my understanding, this package is a polyfill package for some JS features, but it must be imported in order to work.

This package is present in ERB, but I also couldn't find any occurrences of it outside the `package.json` file in that repo either.

I ran `npm run build:types` and ran the software with no problems after running `npm uninstall core-js` and then running `npm i -D core-js@3.36.0`.

Do you know what the problem here was? Do you know if we need `core-js` at all? I wonder if we can remove it. I especially worry that it's pinned to a specific version.
</blockquote></details>

Right, I did what you did at first without issue either. But then do `cd .\lib\platform-bible-react\`, then `npm i`, now try building the types again. I got 181 errors - most of them about "_Duplicate identifiers_" or "_Subsequent property declarations must have the same type_". This is probably fixable but it was more than I wanted to do with a security update and fixing the version prevents the error and alerts us to there being a problem to solve here. So we are definitely using `core-js` and my guess is it's pulled in by settings on `tsconfig.json` such as our values for _target_ and _lib_.

**Review by tjcouch-sil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/780)* status: all files reviewed, 1 unresolved discussion (waiting on @irahopkinson)

___
*[`package.json` line 160 at r2](https://reviewable.io/reviews/paranext/paranext-core/780#-NrLPEfq6b4jsVqqFpK3:-Nrh1xZY0X-6Bs0KG2OJ:bvqasjw) ([raw file](https://github.com/paranext/paranext-core/blob/c6cd017f0f3675ca620de31e083b652ce99c447a/package.json#L160)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

Right, I did what you did at first without issue either. But then do `cd .\lib\platform-bible-react\`, then `npm i`, now try building the types again. I got 181 errors - most of them about "_Duplicate identifiers_" or "_Subsequent property declarations must have the same type_". This is probably fixable but it was more than I wanted to do with a security update and fixing the version prevents the error and alerts us to there being a problem to solve here. So we are definitely using `core-js` and my guess is it's pulled in by settings on `tsconfig.json` such as our values for _target_ and _lib_.
</blockquote></details>

I imagine that is another error due to the removal of `"postinstall": "npm install --ignore-scripts"` in `platform-bible-react`. May have to do with React being present twice. Tom was seeing very similar things. This poorly structured monorepo is becoming quite a nuisance :joy: if only past TJ understood better.

I have been asking to get in an `echo` warning in postinstall stating that you must go run `npm install --ignore-scripts` after running `npm install` in `platform-bible-react`, but it just hasn't gotten in yet.

Does running `npm install` in top level fix the problem?

**Review by irahopkinson — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/780)* status: all files reviewed, 1 unresolved discussion (waiting on @tjcouch-sil)

___
*[`package.json` line 160 at r2](https://reviewable.io/reviews/paranext/paranext-core/780#-NrLPEfq6b4jsVqqFpK3:-Nrh7EqC35k5u3u0hGUN:b2nhswy) ([raw file](https://github.com/paranext/paranext-core/blob/c6cd017f0f3675ca620de31e083b652ce99c447a/package.json#L160)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

I imagine that is another error due to the removal of `"postinstall": "npm install --ignore-scripts"` in `platform-bible-react`. May have to do with React being present twice. Tom was seeing very similar things. This poorly structured monorepo is becoming quite a nuisance :joy: if only past TJ understood better.

I have been asking to get in an `echo` warning in postinstall stating that you must go run `npm install --ignore-scripts` after running `npm install` in `platform-bible-react`, but it just hasn't gotten in yet.

Does running `npm install` in top level fix the problem?
</blockquote></details>

Yes

**Review by tjcouch-sil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/780)* status: all files reviewed, 1 unresolved discussion (waiting on @irahopkinson)

___
*[`package.json` line 160 at r2](https://reviewable.io/reviews/paranext/paranext-core/780#-NrLPEfq6b4jsVqqFpK3:-Nrh7S9F5sBIAXisu7RC:b5velst) ([raw file](https://github.com/paranext/paranext-core/blob/c6cd017f0f3675ca620de31e083b652ce99c447a/package.json#L160)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

Yes
</blockquote></details>

I imagine that probably means removing `core-js` would be fine. But it's not a big deal. If you don't remove it now, it might be worth filing an issue to investigate and thin out our dependencies based on what we're not using. Feel free to resolve this discussion.

If you do end up removing it, would you mind also putting this in both `platform-bible-*` package.json's please...? No prob if you don't.

`"postinstall": "echo WARNING: You must now run cd ../.. npm install --ignore-scripts"`

**Review by irahopkinson — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/780)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

___
*[`package.json` line 160 at r2](https://reviewable.io/reviews/paranext/paranext-core/780#-NrLPEfq6b4jsVqqFpK3:-Nrh9rtg6bw44r-uIUsN:bd6hiex) ([raw file](https://github.com/paranext/paranext-core/blob/c6cd017f0f3675ca620de31e083b652ce99c447a/package.json#L160)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

I imagine that probably means removing `core-js` would be fine. But it's not a big deal. If you don't remove it now, it might be worth filing an issue to investigate and thin out our dependencies based on what we're not using. Feel free to resolve this discussion.

If you do end up removing it, would you mind also putting this in both `platform-bible-*` package.json's please...? No prob if you don't.

`"postinstall": "echo WARNING: You must now run cd ../.. npm install --ignore-scripts"`
</blockquote></details>

Removing `core-js` is out of scope for a security update.

**Pull request merged**
