### PR TITLE
Update npm packages

### PR DESCRIPTION
**Pull request by irahopkinson**
First commit
- most major updates
- minor & patch updates
- ensure `volta` is extended to each `package.json`
- remove unused `package-lock.json` files from each extension
- update linting

Next 5 commits are updates from ERB (electron-react-boilerplate) package which this repo is based on.

The 7th commit fixes the GH test build.

**Note:** It would be good (since lots has changed) if someone else checksout the branch and checks things still work.
- delete `node_modules/electron` before `npm i`

- - -
This change is [Reviewable](https://reviewable.io/reviews/paranext/paranext-core/733)

### CODE REVIEW

**Review by tjcouch-sil — DISMISSED** [review]
Thanks for the hard work on all this! A small question or two as well as a bunch of notes to make the same changes on the template repos.

> Reviewed 50 of 55 files at r1, 1 of 1 files at r2, 2 of 2 files at r3, 8 of 8 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/733#-:-Np1NVlY7vK-I05lwQvw:b-bmiwgr)* status: all files reviewed, 1 unresolved discussion (waiting on @irahopkinson)

___
*[`.eslintrc.js` line 103 at r5](https://reviewable.io/reviews/paranext/paranext-core/733#-Np1N1Zq5DfHaejNYBEA:-Np1N1Zq5DfHaejNYBEB:b1gr2wd) ([raw file](https://github.com/paranext/paranext-core/blob/6a50385704984da747f689619b3893564c7974a0/.eslintrc.js#L103)):*
> ```JavaScript
>     ecmaVersion: 2022,
>     sourceType: 'module',
>     project: './tsconfig.lint.json',
> ```

Do stylelint or prettier run off of the tsconfig? Can we adjust those as well?
___
*[`.stylelintrc.js` line 13 at r5](https://reviewable.io/reviews/paranext/paranext-core/733#-Np1IoDI3RJwOk7bUv-n:-Np1IoDI3RJwOk7bUv-o:b-7j09ui) ([raw file](https://github.com/paranext/paranext-core/blob/967633d7ee278adfb6f2fac8cb3ccbca4c782c3a/.stylelintrc.js#L13)):*
> ```JavaScript
>   rules: {
>     'color-named': null,
>     'function-parentheses-space-inside': null,
> ```

Did you remove this because it isn't a real rule? I can't seem to find information about it anywhere haha if you know what it does, I would be curious to know why you removed it.
___
*[`.erb/configs/webpack.config.renderer.prod.ts` line 133 at r5](https://reviewable.io/reviews/paranext/paranext-core/733#-Np1K2kwCQWhaRFpiuNo:-Np1K2kwCQWhaRFpiuNp:b-el3sjc) ([raw file](https://github.com/paranext/paranext-core/blob/967633d7ee278adfb6f2fac8cb3ccbca4c782c3a/.erb/configs/webpack.config.renderer.prod.ts#L133)):*
> ```XML
>       },
>       isBrowser: false,
>       isDevelopment: process.env.NODE_ENV !== 'production',
> ```

Is there a particular reason to change this or something we should keep in mind moving forward as a result of this change? My current inclination is to say this doesn't actually change anything based on how we're running right now.
___
*[`extensions/.eslintrc.cjs` line 139 at r5](https://reviewable.io/reviews/paranext/paranext-core/733#-Np1LISe1qmT9BDiupUD:-Np1LISe1qmT9BDiupUE:b1xys2q) ([raw file](https://github.com/paranext/paranext-core/blob/6a50385704984da747f689619b3893564c7974a0/extensions/.eslintrc.cjs#L139)):*
> ```JavaScript
>     ecmaVersion: 2022,
>     sourceType: 'module',
>     project: './tsconfig.lint.json',
> ```

Please make this change to both templates as well.
___
*[`extensions/.stylelintrc.cjs` line 13 at r5](https://reviewable.io/reviews/paranext/paranext-core/733#-Np1LnQ75yH0TfzvxqJn:-Np1LnQ75yH0TfzvxqJo:b1xys2q) ([raw file](https://github.com/paranext/paranext-core/blob/967633d7ee278adfb6f2fac8cb3ccbca4c782c3a/extensions/.stylelintrc.cjs#L13)):*
> ```JavaScript
>   rules: {
>     'color-named': null,
>     'function-parentheses-space-inside': null,
> ```

Please make this change to both templates as well.
___
*[`extensions/package.json` line 45 at r5](https://reviewable.io/reviews/paranext/paranext-core/733#-Np1NhqT4a_vsKzcI750:-Np1NhqT4a_vsKzcI751:b-sfxt32) ([raw file](https://github.com/paranext/paranext-core/blob/6a50385704984da747f689619b3893564c7974a0/extensions/package.json#L45)):*
> ```JSON
>     "platform-bible-utils": "file:../lib/platform-bible-utils"
>   },
>   "devDependencies": {
> ```

Please be sure to make the same package updates on both templates.
___
*[`extensions/package.json` line 81 at r5](https://reviewable.io/reviews/paranext/paranext-core/733#-Np1LP_RAJDguNqam6O3:-Np1LP_RAJDguNqam6O4:b-8b8xm) ([raw file](https://github.com/paranext/paranext-core/blob/6a50385704984da747f689619b3893564c7974a0/extensions/package.json#L81)):*
> ```JSON
>     "zip-folder-promise": "^1.2.0"
>   },
>   "volta": {
> ```

Would it be worth putting volta in both templates as well? Seems it might be nice.
___
*[`extensions/tsconfig.lint.json` line 2 at r5](https://reviewable.io/reviews/paranext/paranext-core/733#-Np1LXdMBrbyiMVLbAGy:-Np1LXdMBrbyiMVLbAGz:b1xys2q) ([raw file](https://github.com/paranext/paranext-core/blob/6a50385704984da747f689619b3893564c7974a0/extensions/tsconfig.lint.json#L2)):*
> ```JSON
> {
>   "extends": "./tsconfig",
> ```

Please make this change to both templates as well.

**Review by tjcouch-sil — APPROVED** [review]
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/733)* status: all files reviewed, 1 unresolved discussion (waiting on @irahopkinson)

**Review by tjcouch-sil — COMMENTED** [review]
Just ran it up and everything worked, by the way.

> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/733#-:-Np1UJLO7_4qtCCacml0:bpbjfsf)* status: 61 of 62 files reviewed, 1 unresolved discussion (waiting on @irahopkinson)

**Review by tjcouch-sil — APPROVED** [review]
> Reviewed 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/733)* status: all files reviewed, 1 unresolved discussion (waiting on @irahopkinson)

**Review by tjcouch-sil — APPROVED** [review]
> Reviewed 1 of 1 files at r9, 2 of 2 files at r10, 9 of 9 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/733)* status: all files reviewed, 1 unresolved discussion (waiting on @irahopkinson)

**Review by irahopkinson — COMMENTED** [review]
Thanks.

> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/733#-:-Np1mF5mDswK-aD0wfas:b-ucfkn4)* status: all files reviewed, 4 unresolved discussions (waiting on @irahopkinson)

___
*[`.eslintrc.js` line 103 at r5](https://reviewable.io/reviews/paranext/paranext-core/733#-Np1N1Zq5DfHaejNYBEA:-Np1nqXC2t8_RxdBCLmG:b-62f8cq) ([raw file](https://github.com/paranext/paranext-core/blob/6a50385704984da747f689619b3893564c7974a0/.eslintrc.js#L103)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

Do stylelint or prettier run off of the tsconfig? Can we adjust those as well?
</blockquote></details>

No they don't, AFAIK.
___
*[`.stylelintrc.js` line 13 at r5](https://reviewable.io/reviews/paranext/paranext-core/733#-Np1IoDI3RJwOk7bUv-n:-Np1mNs0E2KXw_x3htsz:befd7ic) ([raw file](https://github.com/paranext/paranext-core/blob/967633d7ee278adfb6f2fac8cb3ccbca4c782c3a/.stylelintrc.js#L13)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

Did you remove this because it isn't a real rule? I can't seem to find information about it anywhere haha if you know what it does, I would be curious to know why you removed it.
</blockquote></details>

This rule was deprecated in `stylelint` v15 and removed in v16 so it had to be deleted. This line was also turning the rule off so we weren't using it.
___
*[`.erb/configs/webpack.config.renderer.prod.ts` line 133 at r5](https://reviewable.io/reviews/paranext/paranext-core/733#-Np1K2kwCQWhaRFpiuNo:-Np1nC1LCOqpPHCX4HKS:b-mbxmun) ([raw file](https://github.com/paranext/paranext-core/blob/967633d7ee278adfb6f2fac8cb3ccbca4c782c3a/.erb/configs/webpack.config.renderer.prod.ts#L133)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

Is there a particular reason to change this or something we should keep in mind moving forward as a result of this change? My current inclination is to say this doesn't actually change anything based on how we're running right now.
</blockquote></details>

This change came from the ERB repo and it seems they figure out the same a you that this will always be `false` in this context so no need to check.
___
*[`extensions/.eslintrc.cjs` line 139 at r5](https://reviewable.io/reviews/paranext/paranext-core/733#-Np1LISe1qmT9BDiupUD:-Np1nZ5k33JsB8NKMmeE:buz14tn) ([raw file](https://github.com/paranext/paranext-core/blob/6a50385704984da747f689619b3893564c7974a0/extensions/.eslintrc.cjs#L139)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

Please make this change to both templates as well.
</blockquote></details>

Will do when this merges.
___
*[`extensions/.stylelintrc.cjs` line 13 at r5](https://reviewable.io/reviews/paranext/paranext-core/733#-Np1LnQ75yH0TfzvxqJn:-Np1ncrm5z1Y-IiYcer5:buz14tn) ([raw file](https://github.com/paranext/paranext-core/blob/967633d7ee278adfb6f2fac8cb3ccbca4c782c3a/extensions/.stylelintrc.cjs#L13)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

Please make this change to both templates as well.
</blockquote></details>

Will do when this merges.
___
*[`extensions/package.json` line 45 at r5](https://reviewable.io/reviews/paranext/paranext-core/733#-Np1NhqT4a_vsKzcI750:-Np1ndwD5xDL2iWRQiAU:buz14tn) ([raw file](https://github.com/paranext/paranext-core/blob/6a50385704984da747f689619b3893564c7974a0/extensions/package.json#L45)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

Please be sure to make the same package updates on both templates.
</blockquote></details>

Will do when this merges.
___
*[`extensions/package.json` line 81 at r5](https://reviewable.io/reviews/paranext/paranext-core/733#-Np1LP_RAJDguNqam6O3:-Np1nh5I14z-ohoNwtib:bmoah18) ([raw file](https://github.com/paranext/paranext-core/blob/6a50385704984da747f689619b3893564c7974a0/extensions/package.json#L81)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

Would it be worth putting volta in both templates as well? Seems it might be nice.
</blockquote></details>

Yes. Will do when this merges.
___
*[`extensions/tsconfig.lint.json` line 2 at r5](https://reviewable.io/reviews/paranext/paranext-core/733#-Np1LXdMBrbyiMVLbAGy:-Np1nlbV3-H1s4Rcnehq:buz14tn) ([raw file](https://github.com/paranext/paranext-core/blob/6a50385704984da747f689619b3893564c7974a0/extensions/tsconfig.lint.json#L2)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

Please make this change to both templates as well.
</blockquote></details>

Will do when this merges.

**Review by tjcouch-sil — APPROVED** [review]
Thanks for letting me know about these things you responded with!

> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/733#-:-Np1oD0l3_ejfchT0R9M:b180t8w)* status: all files reviewed, 4 unresolved discussions (waiting on @irahopkinson)

**Review by tjcouch-sil — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/733)* status: all files reviewed, 4 unresolved discussions (waiting on @irahopkinson)

**Pull request merged**
