### PR TITLE
Fix bug with ChapterRangeSelector and revert prop changes

### PR DESCRIPTION
**Pull request by jolierabideau**
Forever ago, I made a change in a follow up PR for run basic checks dialog that made some props internal state variables. This was not desired, so I reverted that change. Roopa also let me know she was having a problem with not being able to set the chapters with this component, these changes fix that. I removed the mui component, moved `ChapterRangeSelector` to the basics folder, and added it to the preview.

- - -
This change is [Reviewable](https://reviewable.io/reviews/paranext/paranext-core/1109)

### CODE REVIEW

**Review by tjcouch-sil — APPROVED** [review]
:lgtm:

> Reviewed 11 of 11 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/1109#-:-O5swfqL29Io4FdqtrFa:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Review by rolfheij-sil — COMMENTED** [review]
Cool stuff! Have we already figured out why the tests are failing for this? I'd like to have this merged :) I updated the checks list on the configure checks webview (the webview previously known as `run basic checks dialog`), so together with this it would make things very nice!

> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/1109#-:-O7VK0DC9OyxG75Quf7C:bmsld8z)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Review by rolfheij-sil — COMMENTED** [review]
Merging `main` into this branch seems to fix things

> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/1109#-:-O7Vh1-5A_MhGxiGBM8u:bdel3ej)* status: 4 of 12 files reviewed, all discussions resolved (waiting on @tjcouch-sil)

**Review by rolfheij-sil — DISMISSED** [review]
> Reviewed 4 of 11 files at r1, 8 of 8 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/1109)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Review by katherinejensen00 — DISMISSED** [review]
:lgtm:

> Reviewed 4 of 11 files at r1, 8 of 8 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/1109#-:-O7dMwDk5e7xJYysIPjn:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Review by rolfheij-sil — APPROVED** [review]
:lgtm:

> Reviewed 7 of 7 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/1109#-:-O7dP_xP9Nn5hiThsUk3:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Pull request merged**
