### PR TITLE
WebView API

### PR DESCRIPTION
**Pull request by irahopkinson**
- Save and load dock layout
- Add WebView tabs to Dock

- - -
This change is [Reviewable](https://reviewable.io/reviews/paranext/paranext-core/167)

### CODE REVIEW

**Review by tjcouch-sil — DISMISSED** [review]
Thanks for the hard work on this!! Looking forward to having nicer web views!

> Reviewed 19 of 19 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/167#-:-NURikUJ1orK_lZ-Ip-x:bek8zkb)* status: all files reviewed, 2 unresolved discussions (waiting on @irahopkinson)

___
*[`.prettierignore` line 32 at r2](https://reviewable.io/reviews/paranext/paranext-core/167#-NUR_5L-5f2kXr-NUwpv:-NUR_5L-5f2kXr-NUwpw:be1kyrm) ([raw file](https://github.com/paranext/paranext-core/blob/33847fbfcbb36ef31fb7e9cb258cb002507fd952/.prettierignore#L32)):*
> ```ignore
> 
> # vite output
> dist
> ```

Would it be clearer to make this `extensions/dist`? Probably not a big deal.
___
*[`src/shared/data/web-view.model.ts` line 69 at r2](https://reviewable.io/reviews/paranext/paranext-core/167#-NUReTfT2ETbNt7Y3oFG:-NUReTfT2ETbNt7Y3oFH:b-n09jay) ([raw file](https://github.com/paranext/paranext-core/blob/33847fbfcbb36ef31fb7e9cb258cb002507fd952/src/shared/data/web-view.model.ts#L69)):*
> ```XML
> export type WebViewContents = WebViewContentsReact | WebViewContentsHtml;
> 
> export const TYPE_WEBVIEW = 'webview';
> ```

Might be best to keep casing consistent here - `'webView'`

**Review by FoolRunning — CHANGES_REQUESTED** [review]
> Reviewed 19 of 19 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/167)* status: all files reviewed, 5 unresolved discussions (waiting on @irahopkinson)

___
*[`src/renderer/components/docking/paranext-dock-layout.component.tsx` line 45 at r2](https://reviewable.io/reviews/paranext/paranext-core/167#-NURmB063Mh9iZrPYe4K:-NURmB063Mh9iZrPYe4L:b-o6z5sm) ([raw file](https://github.com/paranext/paranext-core/blob/33847fbfcbb36ef31fb7e9cb258cb002507fd952/src/renderer/components/docking/paranext-dock-layout.component.tsx#L45)):*
> ```XML
>   ['tab', createTabPanel],
>   [TYPE_WEBVIEW, createWebViewPanel],
> ]);
> ```

I was expecting that, as part of this task, this map would no longer be hard-coded - i.e. the types and functions would be supplied by the extensions. It worries me that this still seems hard-coded. How are extensions registering their own types?
___
*[`src/renderer/components/docking/paranext-dock-layout.component.tsx` line 72 at r2](https://reviewable.io/reviews/paranext/paranext-core/167#-NURsBwP2b2r-SeGyPlO:-NURsBwP2b2r-SeGyPlP:bx0kday) ([raw file](https://github.com/paranext/paranext-core/blob/33847fbfcbb36ef31fb7e9cb258cb002507fd952/src/renderer/components/docking/paranext-dock-layout.component.tsx#L72)):*
> ```XML
>  * @param savedTabInfo Data that is to be used to create the new tab (comes from rc-dock, typically from disk)
>  */
> function loadTab(savedTabInfo: SavedTabInfo): TabData & SavedTabInfo {
> ```

I feel like I'm missing something. How does a loaded tab get hooked up back to the extension that created it? I expected a bunch of code changes in this file (and other files) to handle extensions providing the web views, but I'm not seeing anything related to that. :thinking: 
___
*[`src/renderer/components/docking/paranext-dock-layout.component.tsx` line 98 at r2](https://reviewable.io/reviews/paranext/paranext-core/167#-NURo2O11-USMUrzlhg7:-NURo2O11-USMUrzlhg8:b-3lc3v) ([raw file](https://github.com/paranext/paranext-core/blob/33847fbfcbb36ef31fb7e9cb258cb002507fd952/src/renderer/components/docking/paranext-dock-layout.component.tsx#L98)):*
> ```XML
>  */
> function onLayoutChange(newLayout: LayoutBase): void {
>   localStorage.setItem(DOCK_LAYOUT_KEY, JSON.stringify(newLayout));
> ```

Does this get called for small changes like changing the splitters or resizing the window? If so, it might be best to only save during shutdown or via user request.
___
*[`src/shared/utils/papi-util.ts` line 213 at r2](https://reviewable.io/reviews/paranext/paranext-core/167#-NURqQAt-Dt3TjIBX4D4:-NURqQAt-Dt3TjIBX4D5:bmngrkt) ([raw file](https://github.com/paranext/paranext-core/blob/33847fbfcbb36ef31fb7e9cb258cb002507fd952/src/shared/utils/papi-util.ts#L213)):*
> ```XML
> export function deserializeRequestType(requestType: string): RequestType {
>   const [category, ...directiveParts] = requestType.split(REQUEST_TYPE_SEPARATOR);
>   const directive = directiveParts.join(REQUEST_TYPE_SEPARATOR);
> ```

Probably worth thinking about doing something more efficient here since this gets called for each request:
https://stackoverflow.com/a/2878746/4953232

**Review by FoolRunning — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/167)* status: all files reviewed, 3 unresolved discussions (waiting on @irahopkinson)

___
*[`src/renderer/components/docking/paranext-dock-layout.component.tsx` line 45 at r2](https://reviewable.io/reviews/paranext/paranext-core/167#-NURmB063Mh9iZrPYe4K:-NUSLhoWDCWCWuJPntXH:b-4hejd1) ([raw file](https://github.com/paranext/paranext-core/blob/33847fbfcbb36ef31fb7e9cb258cb002507fd952/src/renderer/components/docking/paranext-dock-layout.component.tsx#L45)):*
<details><summary><i>Previously, FoolRunning (Tim Steenwyk) wrote…</i></summary><blockquote>

I was expecting that, as part of this task, this map would no longer be hard-coded - i.e. the types and functions would be supplied by the extensions. It worries me that this still seems hard-coded. How are extensions registering their own types?
</blockquote></details>

TJ explained that you both talked and decided to push that part off to another task.
___
*[`src/renderer/components/docking/paranext-dock-layout.component.tsx` line 72 at r2](https://reviewable.io/reviews/paranext/paranext-core/167#-NURsBwP2b2r-SeGyPlO:-NUSLpjvCpOdd-da6Ewi:b32pfqn) ([raw file](https://github.com/paranext/paranext-core/blob/33847fbfcbb36ef31fb7e9cb258cb002507fd952/src/renderer/components/docking/paranext-dock-layout.component.tsx#L72)):*
<details><summary><i>Previously, FoolRunning (Tim Steenwyk) wrote…</i></summary><blockquote>

I feel like I'm missing something. How does a loaded tab get hooked up back to the extension that created it? I expected a bunch of code changes in this file (and other files) to handle extensions providing the web views, but I'm not seeing anything related to that. :thinking: 
</blockquote></details>

TJ explained that you both talked and decided to push that part off to another task.

**Review by irahopkinson — COMMENTED** [review]
I've made 2 changes. I'll merge main in once everyone is happy with it as is and then it will need another review before merge.

> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/167#-:-NUTtyhuAKkoMNSZ51XV:bolmvbm)* status: 16 of 19 files reviewed, 1 unresolved discussion (waiting on @FoolRunning and @tjcouch-sil)

___
*[`.prettierignore` line 32 at r2](https://reviewable.io/reviews/paranext/paranext-core/167#-NUR_5L-5f2kXr-NUwpv:-NUTenG44EKeioZB4xyv:b-rbttca) ([raw file](https://github.com/paranext/paranext-core/blob/33847fbfcbb36ef31fb7e9cb258cb002507fd952/.prettierignore#L32)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

Would it be clearer to make this `extensions/dist`? Probably not a big deal.
</blockquote></details>

I did think about this but `dist` is a common output folder name and should be excluded in general. The comment is to clarify the reason for it being added in the first place rather than specifically to only be for that. I've updated the comment to make that clearer.
___
*[`src/renderer/components/docking/paranext-dock-layout.component.tsx` line 98 at r2](https://reviewable.io/reviews/paranext/paranext-core/167#-NURo2O11-USMUrzlhg7:-NUTgl4o1Lq3NiXg0DD_:b-ez478y) ([raw file](https://github.com/paranext/paranext-core/blob/33847fbfcbb36ef31fb7e9cb258cb002507fd952/src/renderer/components/docking/paranext-dock-layout.component.tsx#L98)):*
<details><summary><i>Previously, FoolRunning (Tim Steenwyk) wrote…</i></summary><blockquote>

Does this get called for small changes like changing the splitters or resizing the window? If so, it might be best to only save during shutdown or via user request.
</blockquote></details>

Yes it does since those are all layout changes.

I would argue against "_via user request_" on UX grounds. Saving of the layout is not something the user should ever have to concern themselves about - it just works™.

It's a little bit tricky to assure you can always get to a save on an electron/web shutdown and I'd prefer all my previous layout adjustments where saved even if it doesn't get to a shutdown, e.g. because of a crash - crashing is bad enough for a user without not remembering all my changes! I would also argue it's premature optimisation since anecdotally I think `localStorage` is fast. I thought I'd better check my assumptions here so I googled it. It's really fast! - see https://gomakethings.com/how-fast-is-vanilla-js-localstorage/.

Do note the `TODO` in JSDoc above. There is a 3rd argument to the `onLayoutChange` method that we could filter saves on. I'll likely investigate that in a follow-up PR.
___
*[`src/shared/data/web-view.model.ts` line 69 at r2](https://reviewable.io/reviews/paranext/paranext-core/167#-NUReTfT2ETbNt7Y3oFG:-NUTq1jD6hQYPs8Zl6up:b-896fix) ([raw file](https://github.com/paranext/paranext-core/blob/33847fbfcbb36ef31fb7e9cb258cb002507fd952/src/shared/data/web-view.model.ts#L69)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

Might be best to keep casing consistent here - `'webView'`
</blockquote></details>

Done.
___
*[`src/shared/utils/papi-util.ts` line 213 at r2](https://reviewable.io/reviews/paranext/paranext-core/167#-NURqQAt-Dt3TjIBX4D4:-NUTqJzf4qlcgTPPWj3p:bf880g0) ([raw file](https://github.com/paranext/paranext-core/blob/33847fbfcbb36ef31fb7e9cb258cb002507fd952/src/shared/utils/papi-util.ts#L213)):*
<details><summary><i>Previously, FoolRunning (Tim Steenwyk) wrote…</i></summary><blockquote>

Probably worth thinking about doing something more efficient here since this gets called for each request:
https://stackoverflow.com/a/2878746/4953232
</blockquote></details>

Actually at the moment, it's not used in requests at all - only `serializeRequestType` is used. And before this PR the code was actually broken as it only returned the `catergory` and the `derective` was always _undefined_. In this PR it's only called by `deserializeTabId` which in turn is only called twice for each WebView at setup.

However, I do agree it can probably be written more efficiently which is one of the main reasons I wrote the tests for it (which I think cover all our requirements). Now someone can refactor it and have confidence it still does everything required. I've moved it forward but didn't feel the need to go the whole way given its current usage. If you still feel strongly about it I can fix it in a follow-up PR.

**Review by tjcouch-sil — DISMISSED** [review]
:lgtm: thanks for the hard work on this!

> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/167#-:-NUY80Rk8XLEjsQYF-XO:bcbj1ey)* status: all files reviewed, 1 unresolved discussion (waiting on @FoolRunning)

**Comment by irahopkinson** [comment]
@FoolRunning  `main` is now merged in and this is ready for final review.

**Review by FoolRunning — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/167)* status: 19 of 20 files reviewed, 1 unresolved discussion (waiting on @irahopkinson and @tjcouch-sil)

___
*[`src/renderer/components/docking/paranext-dock-layout.component.tsx` line 98 at r2](https://reviewable.io/reviews/paranext/paranext-core/167#-NURo2O11-USMUrzlhg7:-NUapJKb-X-oq5FwoLfV:b-j0cls4) ([raw file](https://github.com/paranext/paranext-core/blob/33847fbfcbb36ef31fb7e9cb258cb002507fd952/src/renderer/components/docking/paranext-dock-layout.component.tsx#L98)):*
> Saving of the layout is not something the user should ever have to concern themselves about - it just works™.

Actually, this is actually a feature that UX *will* ask for (since you can do it in Paratext 9). The user can save their current layout to a file and then load that file to restore a particular layout. 

As far as the crashing is concerned, I agree that we should do something, but having it save for every movement of the splitter seems overkill. Paratext 9 saves every 5 minutes and that is usually good enough. And another thought, just because saving it to cached storage is fast, that doesn't mean that running the saving on the docking framework is fast (i.e. creating the object to be saved). However, I guess we can wait to see if it becomes an issue for now.

**Review by irahopkinson — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/167)* status: 19 of 20 files reviewed, 1 unresolved discussion (waiting on @FoolRunning and @tjcouch-sil)

___
*[`src/renderer/components/docking/paranext-dock-layout.component.tsx` line 98 at r2](https://reviewable.io/reviews/paranext/paranext-core/167#-NURo2O11-USMUrzlhg7:-NUcePnuD-bBshsWajtC:b-71e8ge) ([raw file](https://github.com/paranext/paranext-core/blob/33847fbfcbb36ef31fb7e9cb258cb002507fd952/src/renderer/components/docking/paranext-dock-layout.component.tsx#L98)):*
> Actually, this is actually a feature that UX _will_ ask for (since you can do it in Paratext 9). The user can save their current layout to a file and then load that file to restore a particular layout.

For sure, but saving a layout for a latter load is a different feature to this. This is just remembering how you modify your current layout.

> And another thought, just because saving it to cached storage is fast, that doesn't mean that running the saving on the docking framework is fast (i.e. creating the object to be saved).

I'm not sure why you think this would be slow. It doesn't have to create the layout object since that already exists in rc-dock, it just has to get it (and even if it did have to create it I'm not sure why that would be slow either). If any of that is slow we have much bigger problems. Maybe I didn't understand your point?

> However, I guess we can wait to see if it becomes an issue for now.

If you are OK to merge this as is please change your disposition (bottom-right) - this is the last blocking item. If not please tell me how you would like it changed.

**Review by FoolRunning — APPROVED** [review]
> Reviewed 3 of 3 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/167)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @irahopkinson)

___
*[`src/renderer/components/docking/paranext-dock-layout.component.tsx` line 98 at r2](https://reviewable.io/reviews/paranext/paranext-core/167#-NURo2O11-USMUrzlhg7:-NUx7W3jDRQnKFzeiyzn:b-521xp2) ([raw file](https://github.com/paranext/paranext-core/blob/33847fbfcbb36ef31fb7e9cb258cb002507fd952/src/renderer/components/docking/paranext-dock-layout.component.tsx#L98)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

> Actually, this is actually a feature that UX _will_ ask for (since you can do it in Paratext 9). The user can save their current layout to a file and then load that file to restore a particular layout.

For sure, but saving a layout for a latter load is a different feature to this. This is just remembering how you modify your current layout.

> And another thought, just because saving it to cached storage is fast, that doesn't mean that running the saving on the docking framework is fast (i.e. creating the object to be saved).

I'm not sure why you think this would be slow. It doesn't have to create the layout object since that already exists in rc-dock, it just has to get it (and even if it did have to create it I'm not sure why that would be slow either). If any of that is slow we have much bigger problems. Maybe I didn't understand your point?

> However, I guess we can wait to see if it becomes an issue for now.

If you are OK to merge this as is please change your disposition (bottom-right) - this is the last blocking item. If not please tell me how you would like it changed.
</blockquote></details>

I was originally hoping to still see this changed (why it was a blocking comment), but it is true that the object creation is not really an issue so I guess it's fine for now. I'll stop holding this up.

**Review by lyonsil — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/167#-:-NUxkaU21CsPLriVKMAd:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @irahopkinson)

**Pull request merged**
