### PR TITLE
Add the network object status service

### PR DESCRIPTION
**Pull request by lyonsil**
This change is [Reviewable](https://reviewable.io/reviews/paranext/paranext-core/652)

### CODE REVIEW

**Review by irahopkinson — COMMENTED** [review]
Thanks for this good work.

> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/652#-:-NjtVGFy-FWtDCk7A9rj:bx55fv7)* status: all files reviewed, 2 unresolved discussions (waiting on @lyonsil)

___
*[`src/main/main.ts` line 321 at r1](https://reviewable.io/reviews/paranext/paranext-core/652#-NjtGlaN3FYKr8Yk5Zf0:-NjtGlaN3FYKr8Yk5Zf1:b-t2zorj) ([raw file](https://github.com/paranext/paranext-core/blob/66d71031845f6aaec7786e9b98fc7ca9b8e59b68/src/main/main.ts#L321)):*
> ```XML
>   }, 5000);
> 
>   setTimeout(async () => {
> ```

BTW is this debug or intentionally left in?
___
*[`src/shared/services/web-view.service.ts` line 27 at r1](https://reviewable.io/reviews/paranext/paranext-core/652#-NjtV2F65v1rpggRK5mN:-NjtV2F65v1rpggRK5mO:b-unpc1l) ([raw file](https://github.com/paranext/paranext-core/blob/66d71031845f6aaec7786e9b98fc7ca9b8e59b68/src/shared/services/web-view.service.ts#L27)):*
> ```XML
>             NETWORK_OBJECT_NAME_WEB_VIEW_SERVICE,
>             // Wait 30 seconds for the web view service to appear
>             30000,
> ```

This seems like a realy long time to wait at startup. Is there any UI dependent on this?

**Review by tjcouch-sil — COMMENTED** [review]
Looks good! Thanks for the hard work on this! Just a couple things to discuss.

> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/652#-:-NkMB_ke33JrZGxDVQ0P:b7kj40p)* status: all files reviewed, 4 unresolved discussions (waiting on @irahopkinson and @lyonsil)

___
*[`src/main/main.ts` line 69 at r1](https://reviewable.io/reviews/paranext/paranext-core/652#-NkM2gfkBIOCTJLcXWzy:-NkM2gfkBIOCTJLcXWzz:b3s3mag) ([raw file](https://github.com/paranext/paranext-core/blob/66d71031845f6aaec7786e9b98fc7ca9b8e59b68/src/main/main.ts#L69)):*
> ```XML
> 
>   // The network object status service relies on seeing everything else start up later
>   startNetworkObjectStatusService();
> ```

Please add an iife with a `try/catch` or `await` this :) thanks!
___
*[`src/shared/services/network-object-status.service.ts` line 64 at r1](https://reviewable.io/reviews/paranext/paranext-core/652#-NkM9p5T58ZmTBkHNglA:-NkM9p5T58ZmTBkHNglB:bttrk7u) ([raw file](https://github.com/paranext/paranext-core/blob/66d71031845f6aaec7786e9b98fc7ca9b8e59b68/src/shared/services/network-object-status.service.ts#L64)):*
> ```XML
>   // Now check if the needed network object has already been created
>   const existingNetworkObjects = await getAllNetworkObjects();
>   if (existingNetworkObjects[id]) asyncVar.resolveToValue(existingNetworkObjects[id]);
> ```

I think `unsub` should be called here as well, right? And I think `unsub`s might only be able to be called once, so might have to do something about that as well. Not a big deal, but just noticed it offhand.
___
*[`src/shared/services/web-view.service.ts` line 27 at r1](https://reviewable.io/reviews/paranext/paranext-core/652#-NjtV2F65v1rpggRK5mN:-NkMALMeBifugoameUla:b-v4pxln) ([raw file](https://github.com/paranext/paranext-core/blob/66d71031845f6aaec7786e9b98fc7ca9b8e59b68/src/shared/services/web-view.service.ts#L27)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

This seems like a realy long time to wait at startup. Is there any UI dependent on this?
</blockquote></details>

This is probably so long because the frontend takes so long to start the first time you run in development. I doubt there is UI dependent on this other than being dependent on the starting of the renderer process.

I do imagine that we probably will not need something like `waitForNetworkObject` long-term since we will be reading manifests to determine what network objects *should* be available when we start various extensions (lazy loading), but it's fine to have for now since we aren't currently determining available network objects statically. And the network object status service isn't on the `papi`, so we're not committing to providing this to extensions long-term anyway.

**Review by lyonsil — COMMENTED** [review]
@tjcouch-sil made some suggestions related to this PR in the previous PR where the event was added that fires when network objects are created.  So I'm making more changes related to PR feedback that just doesn't happen to be in this particular review discussion.

> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/652#-:-NkSH7SJDiXk4Wy53Uq9:b-i1egzc)* status: 1 of 6 files reviewed, 4 unresolved discussions (waiting on @irahopkinson and @tjcouch-sil)

___
*[`src/main/main.ts` line 69 at r1](https://reviewable.io/reviews/paranext/paranext-core/652#-NkM2gfkBIOCTJLcXWzy:-NkSCszT5FHEd9yJt_Th:b-896fix) ([raw file](https://github.com/paranext/paranext-core/blob/66d71031845f6aaec7786e9b98fc7ca9b8e59b68/src/main/main.ts#L69)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

Please add an iife with a `try/catch` or `await` this :) thanks!
</blockquote></details>

Done.
___
*[`src/main/main.ts` line 321 at r1](https://reviewable.io/reviews/paranext/paranext-core/652#-NjtGlaN3FYKr8Yk5Zf0:-NkSC6g_DfWliGpCPGdN:bw99lji) ([raw file](https://github.com/paranext/paranext-core/blob/66d71031845f6aaec7786e9b98fc7ca9b8e59b68/src/main/main.ts#L321)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

BTW is this debug or intentionally left in?
</blockquote></details>

This was intentionally left in, but I'm fine removing it if that is preferred.  It's in the region labeled `Test network objects`, and what should/shouldn't be there is kind of hand wavy as it will all disappear once we start to produce "real" builds.
___
*[`src/shared/services/network-object-status.service.ts` line 64 at r1](https://reviewable.io/reviews/paranext/paranext-core/652#-NkM9p5T58ZmTBkHNglA:-NkSG-pZAV9s1QPUvKF2:b-f4wtdw) ([raw file](https://github.com/paranext/paranext-core/blob/66d71031845f6aaec7786e9b98fc7ca9b8e59b68/src/shared/services/network-object-status.service.ts#L64)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

I think `unsub` should be called here as well, right? And I think `unsub`s might only be able to be called once, so might have to do something about that as well. Not a big deal, but just noticed it offhand.
</blockquote></details>

The next time a network object is created once the promise has resolved, `unsub` will run.  Is it that bad to leave it until then?  I didn't think it was that big of a deal, and leaving it as-is avoids the problem of running `unsub` it multiple times.
___
*[`src/shared/services/web-view.service.ts` line 27 at r1](https://reviewable.io/reviews/paranext/paranext-core/652#-NjtV2F65v1rpggRK5mN:-NkSGmHQ848ezwGdryAF:b-ybfua) ([raw file](https://github.com/paranext/paranext-core/blob/66d71031845f6aaec7786e9b98fc7ca9b8e59b68/src/shared/services/web-view.service.ts#L27)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

This is probably so long because the frontend takes so long to start the first time you run in development. I doubt there is UI dependent on this other than being dependent on the starting of the renderer process.

I do imagine that we probably will not need something like `waitForNetworkObject` long-term since we will be reading manifests to determine what network objects *should* be available when we start various extensions (lazy loading), but it's fine to have for now since we aren't currently determining available network objects statically. And the network object status service isn't on the `papi`, so we're not committing to providing this to extensions long-term anyway.
</blockquote></details>

It generally takes far less than 30 seconds for the web view service to appear in my experience, but I've seen some long times in the past.  I could just eliminate the timeout altogether and wait as long as it takes, but a 30 second back-stop timeout seemed better than waiting forever.

**Review by tjcouch-sil — DISMISSED** [review]
:lgtm: awesome! Thanks for adding the `NetworkObjectDetails`! That was a nice touch I wasn't expecting as I thought we left off saying we would leave it til rework. I appreciate the hard work on this. Looks good.

> Reviewed 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/652#-:-NkSKlHgDOFCHMGUalu8:bgt4jjz)* status: all files reviewed, 2 unresolved discussions (waiting on @irahopkinson)

___
*[`src/shared/services/network-object-status.service.ts` line 64 at r1](https://reviewable.io/reviews/paranext/paranext-core/652#-NkM9p5T58ZmTBkHNglA:-NkSKUE8-wmev_ntJ0N0:b-l4s65e) ([raw file](https://github.com/paranext/paranext-core/blob/66d71031845f6aaec7786e9b98fc7ca9b8e59b68/src/shared/services/network-object-status.service.ts#L64)):*
<details><summary><i>Previously, lyonsil (Matt Lyons) wrote…</i></summary><blockquote>

The next time a network object is created once the promise has resolved, `unsub` will run.  Is it that bad to leave it until then?  I didn't think it was that big of a deal, and leaving it as-is avoids the problem of running `unsub` it multiple times.
</blockquote></details>

It's fine. This is an internal function haha thanks!

**Review by lyonsil — COMMENTED** [review]
Sorry, I was saying I didn't want to touch anything else on the previous PR.  I think it made sense for this one.

> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/652#-:-NkSL6nc1_OgIoSbRUs-:b-d20mog)* status: all files reviewed, 2 unresolved discussions (waiting on @irahopkinson)

**Pull request merged**
