### PR TITLE
Created MUI-based checkbox component

### PR DESCRIPTION
**Pull request by tombogle**
Solves #123

- - -
This change is [Reviewable](https://reviewable.io/reviews/paranext/paranext-core/130)

### CODE REVIEW

**Review by rolfheij-sil — COMMENTED** [review]
Nice work!

> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/130#-:-NSFbWob2eILxvHcl8j3:bdtx8r6)* status: all files reviewed, 4 unresolved discussions (waiting on @katherinejensen00 and @tombogle)

___
*[`src/renderer/components/papi-components/checkbox.tsx` line 1 at r1](https://reviewable.io/reviews/paranext/paranext-core/130#-NSFZ4_u9fADLekHHLso:-NSFZ4_u9fADLekHHLsp:bbuwzz7) ([raw file](https://github.com/paranext/paranext-core/blob/bc8b2db2676c24534bae887d7c80ce30839a44a2/src/renderer/components/papi-components/checkbox.tsx#L1)):*
> ```XML
> import { Checkbox as MuiCheckBox } from '@mui/material';
> ```

We should be consistent with naming the objects, and either go for `Checkbox` or `CheckBox`. I think `Checkbox` is prefered.
So we should change `MuiCheckBox` to `MuiCheckbox`, and use `papi-checkbox` for our CSS classes
___
*[`src/renderer/components/papi-components/checkbox.tsx` line 17 at r1](https://reviewable.io/reviews/paranext/paranext-core/130#-NSF_0TDCJBf6o5NLADf:-NSF_0TDCJBf6o5NLADg:b-odgs6v) ([raw file](https://github.com/paranext/paranext-core/blob/bc8b2db2676c24534bae887d7c80ce30839a44a2/src/renderer/components/papi-components/checkbox.tsx#L17)):*
> ```XML
>    * If `true`, the component is checked by default.
>    */
>   defaultChecked?: boolean;
> ```

According to our style guide (https://github.com/paranext/paranext/wiki/Code-Style-Guide#typescript-specific-guidelines) this should be something like `isDefaultChecked`

Also, on line 46 this prop is assigned `false` as a default. Please add an `@default` comment for that here
___
*[`src/renderer/components/papi-components/checkbox.tsx` line 44 at r1](https://reviewable.io/reviews/paranext/paranext-core/130#-NSF_kX78NuO8ilXBaTj:-NSF_kX78NuO8ilXBaTk:b-z1sk4b) ([raw file](https://github.com/paranext/paranext-core/blob/bc8b2db2676c24534bae887d7c80ce30839a44a2/src/renderer/components/papi-components/checkbox.tsx#L44)):*
> ```XML
>  */
> function CheckBox({
>   isChecked: checked,
> ```

It's good practice to keep the names of the local variable in sync with the prop names, so you can change this line to `isChecked,` and change the assignment on line 54 to `check={isChecked}
___
*[`src/stories/checkbox.stories.ts` line 9 at r1](https://reviewable.io/reviews/paranext/paranext-core/130#-NSFbqBR6d74Ou4F_Ceo:-NSFbqBR6d74Ou4F_Cep:bcs0bnd) ([raw file](https://github.com/paranext/paranext-core/blob/bc8b2db2676c24534bae887d7c80ce30839a44a2/src/stories/checkbox.stories.ts#L9)):*
> ```XML
>   tags: ['autodocs'],
>   argTypes: {
>     isDisabled: { control: 'boolean' },
> ```

You can also add argtypes for `isChecked`, `isIndeterminate` and `defaultChecked`

**Comment by katherinejensen00** [comment]
I think this is looking pretty good so far. This morning we talked about adding a label and a label position so I will hold off approving it until then, but I don't see anything in the initial check in to change beyond what Rolf already said.

**Review by katherinejensen00 — COMMENTED** [review]
Oops. I put a comment in the wrong place. I think these changes look good and will be ready after Rolf's changes and the label changes we talked about in the standup this morning.

**Comment by tombogle** [comment]
*[`src/stories/checkbox.stories.ts` line 23 at r2](https://reviewable.io/reviews/paranext/paranext-core/130#-NSKWP7XEEmkteazagvD:-NSLZB3xBTA4PXnAl0G8:bbkjr3f) ([raw file](https://github.com/paranext/paranext-core/blob/47ef4b931bf12c2bd6edb36ff5c6cfd4708afd60/src/stories/checkbox.stories.ts#L23)):*
<details><summary><i>Previously, rolfheij-sil wrote…</i></summary><blockquote>

This one isn't initally checked when in my Storybook environment. Is it checked by default in your local environment?
</blockquote></details>

I broke it when I renamed defaultChecked to isDefaultChecked. It's going to take some time to get used to a world where you can break things and only find out at runtime.

**Review by tombogle — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/130)* status: all files reviewed, 3 unresolved discussions (waiting on @rolfheij-sil and @tjcouch-sil)

___
*[`src/stories/checkbox.stories.ts` line 9 at r1](https://reviewable.io/reviews/paranext/paranext-core/130#-NSFbqBR6d74Ou4F_Ceo:-NSL_Yvl8ThX1BtGjVi4:b-896fix) ([raw file](https://github.com/paranext/paranext-core/blob/bc8b2db2676c24534bae887d7c80ce30839a44a2/src/stories/checkbox.stories.ts#L9)):*
<details><summary><i>Previously, rolfheij-sil wrote…</i></summary><blockquote>

I don't see these added yet. And you can also add `labelText` and `className` with control type `text`
</blockquote></details>

Done.

**Comment by tombogle** [comment]
Still TODO:

1. Make label element conditional
2. Expose ability to position label
3. Figure out why the isChecked control in storybook doesn't have any effect.

**Review by rolfheij-sil — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/130#-:-NSpJA-m7Z9yxanT1Ggn:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @tombogle)

**Review by katherinejensen00 — CHANGES_REQUESTED** [review]
This looks pretty good. I just had a quick question for you.

> Reviewed 5 of 5 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/130#-:-NUO_01l58u64nezuG-a:b-9zpxsk)* status: all files reviewed, 1 unresolved discussion (waiting on @tombogle)

___
*[`src/renderer/components/papi-components/checkbox.component.tsx` line 10 at r5](https://reviewable.io/reviews/paranext/paranext-core/130#-NUOYmkQ40855ckSAIg0:-NUOYmkQ40855ckSAIg1:b-2u3rtn) ([raw file](https://github.com/paranext/paranext-core/blob/ddb3c3e96c83664771359bf580969a00a7175941/src/renderer/components/papi-components/checkbox.component.tsx#L10)):*
> ```XML
>    * If `true`, the component is checked.
>    */
>   isChecked?: boolean;
> ```

Should this be optional? Should implementers have to choose a default state or do you think it is better to leave it optional?

**Review by rolfheij-sil — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/130)* status: all files reviewed, 1 unresolved discussion (waiting on @katherinejensen00)

___
*[`src/renderer/components/papi-components/checkbox.component.tsx` line 10 at r5](https://reviewable.io/reviews/paranext/paranext-core/130#-NUOYmkQ40855ckSAIg0:-NUQI7gx028QcqleH84Z:bbkzpjy) ([raw file](https://github.com/paranext/paranext-core/blob/ddb3c3e96c83664771359bf580969a00a7175941/src/renderer/components/papi-components/checkbox.component.tsx#L10)):*
<details><summary><i>Previously, katherinejensen00 wrote…</i></summary><blockquote>

Should this be optional? Should implementers have to choose a default state or do you think it is better to leave it optional?
</blockquote></details>

I think this prop is optional (there's a '?'). In most cases this prop won't be used, as using it makes the checkbox a controlled component.
If users want to set a defaultstate they can use the `isDefaultChecked` prop, which defaults to `false`

**Review by katherinejensen00 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/130)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @tombogle)

___
*[`src/renderer/components/papi-components/checkbox.component.tsx` line 10 at r5](https://reviewable.io/reviews/paranext/paranext-core/130#-NUOYmkQ40855ckSAIg0:-NURZDBH9atoKhUeEUVT:b-dzzlgo) ([raw file](https://github.com/paranext/paranext-core/blob/ddb3c3e96c83664771359bf580969a00a7175941/src/renderer/components/papi-components/checkbox.component.tsx#L10)):*
<details><summary><i>Previously, rolfheij-sil wrote…</i></summary><blockquote>

I think this prop is optional (there's a '?'). In most cases this prop won't be used, as using it makes the checkbox a controlled component.
If users want to set a defaultstate they can use the `isDefaultChecked` prop, which defaults to `false`
</blockquote></details>

That makes sense. Thanks! Then I think leaving it as optional is a good idea. The code looks good to me then.

**Pull request merged**
