### PR TITLE
Add character inventory UI that manages validCharacters and invalidCharacters in project settings

### LINKED ISSUE #880: Checks: Create reusable Inventory dialog
As a member of the translation team, I want to be able to open an inventory dialog that shows me counts of different types that can be used in conjunction with related checks.

Assume we will recreate something similar to what was done in PT9 unless UX has a different design in place.

Examples: 

Image

Image

Image

### PR DESCRIPTION
**Pull request by rolfheij-sil**
Fixes #880 

This change is [Reviewable](https://reviewable.io/reviews/paranext/paranext-core/914)

Inventory to-do's:
- [x] Get projectId from context menu. I assume it's available somewhere in there? It now uses a dialog that let's you select a project as a temporary fix to get a projectId
- [x] Hook up to scripture data (now uses a randomly generated array of characters from a hardcoded list of characters)
- [x] Show occurrences for selected character/item below the data table
- [x] Add filter components above the data table
- [ ] Make inventory modular. It's now hard-coded to be a character inventory, but it should be able to work with other types of data too

Inventory table to-do's:
- [x] Refactor the data table out of the web-view and into its own file. The file is already created (inventory-data-table.component.tsx)
- [x] Fix styling, make it look better
- [x] Make status sortable
- [ ] Disable buttons to set/change status in the header when no row on the table is selected
- [ ] Make row 1 selected by default
- [ ] Make subsequent row selected after updating status (give focus to row below the current one after clicking valid/invalid/undefined)
- [x] Add DataTable showcase to Preview app in platform-bible-react

General table improvements:
- [ ] Implement sticky table header and add prop to enable/disable it
- [x] Compare this new tanstack table to the Adazzle one that's in `lib\platform-bible-react\src\components\table.component.tsx`

General to-do's:
- [ ] Add unit tests
- [x] Check if Shadcn components used in table are properly installed and configured into platform-bible-react (I didn't wrap anything, so we might want to do that, similar to what David did)
- [ ] The book text is just processed as plain text. So USFM markers and whitespace should not be considered for character data. They are now.

Known issues:
- [x] ValidCharacters and InvalidCharacters are cleared from Settings.xml on startup because a useEffect is triggered that passes empty arrays to setSetting. The arrays are validCharacters and invalidCharacters
- [x] The header for the status column sometimes disappears
- [x]  It only works when ValidCharacters and InvalidCharacters are defined in Settings.xml. Make sure it also works when these settings aren't available in the settings file
- [ ] Rapidly changing the status doesn't work. Changes aren't picked up
- [ ] The option to open the inventory is visible in both the Scripture editor and the Resource viewer. It shouldn't be available on the latter
- [ ] Characters aren't properly sorted before they are written to Settings.xml (the default array.sort() method produces a different result than the sorting algorithm that is used in PT9)

### CODE REVIEW

**Comment by rolfheij-sil** [comment]
The character inventory can be opened by clicking the `Inventory: Characters` option under the new `Tools` section in the context menu of the `Scripture editor`.
image

Before selecting any row (i.e. character), the newly opened floating webview will show a list of all characters in the currently selected book
image

When a character is selected, the height of the character table will be limited, and a table with occurences will appear below
image

**Comment by Sebastian-ubs** [comment]
Hey @rolfheij-sil, it looks like you did a good job in using the components with the default styling. With that we have a good basis for looking into what adaptations to the style we want to do later 👍

**Comment by rolfheij-sil** [comment]
I added the filter components as they appear in the Paratext 9.5 build I received

image

The book/chapter/verse scope selector is not working yet. The others work.

**Comment by Sebastian-ubs** [comment]
IMHO it would make a lot of sense to review this PR, do changes according to review, merge it and start new PRs, instead of accumulating more into it.

**Review by lyonsil — CHANGES_REQUESTED** [review]
Lots of great stuff here! I added a few comments. I am not as well versed in some of the React and CSS code, so it would be good to get someone else who has build dialogs in our platform to give it a once over, too.

> Reviewed 32 of 43 files at r1, 1 of 8 files at r2, 9 of 10 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/914#-:-O12PtqaC4CGK_8C-q5l:b-a3vzwm)* status: all files reviewed, 7 unresolved discussions (waiting on @rolfheij-sil)

___
*[`extensions/src/platform-scripture/contributions/localizedStrings.json` line 15 at r4](https://reviewable.io/reviews/paranext/paranext-core/914#-O12H3vr67qCgpdRH1yY:-O12H3vs2f6F3ufNQP7u:b-6m0x8k) ([raw file](https://github.com/paranext/paranext-core/blob/0d12b80b57b30bee2d538618269c57a65f9d2316/extensions/src/platform-scripture/contributions/localizedStrings.json#L15)):*
> ```JSON
>       "%project_settings_platformScripture_validCharacters_label%": "Valid Characters",
>       "%project_settings_platformScripture_validCharacters_description%": "List of characters that are accepted in this project.",
>       "%project_settings_platformScripture_invalidCharacters_label%": "Is Editable",
> ```

Is this a copy paste error from the previously added "Is Editable" setting?
___
*[`extensions/src/platform-scripture/src/character-inventory.web-view.tsx` line 30 at r4](https://reviewable.io/reviews/paranext/paranext-core/914#-O12IWpp9O032gdffnpy:-O12IWpp9O032gdffnpz:b-quad4n) ([raw file](https://github.com/paranext/paranext-core/blob/0d12b80b57b30bee2d538618269c57a65f9d2316/extensions/src/platform-scripture/src/character-inventory.web-view.tsx#L30)):*
> ```XML
>   const projectMetadata = await projectLookup.getMetadataForProject(projectId);
>   const pdp = await projectDataProviders.get('platform.base', projectMetadata.id);
>   return (await pdp.getSetting(`platformScripture.${characterSet}`)).split(' ');
> ```

Does this work properly for surrogate pairs? I suspect it does not but am not 100% sure.
___
*[`extensions/src/platform-scripture/src/character-inventory.web-view.tsx` line 43 at r4](https://reviewable.io/reviews/paranext/paranext-core/914#-O12JJo7CwADQALFuz2E:-O12JJo7CwADQALFuz2F:bh4vvja) ([raw file](https://github.com/paranext/paranext-core/blob/0d12b80b57b30bee2d538618269c57a65f9d2316/extensions/src/platform-scripture/src/character-inventory.web-view.tsx#L43)):*
> ```XML
> };
> 
> const getText = async (
> ```

suggestion - I think this function could be shortened by just having a single `if/else if/else` block based on `scope` and grabs the appropriate text. Then you don't have to have two different `if/else if/else` blocks or do type asserting.
___
*[`extensions/src/platform-scripture/src/character-inventory.web-view.tsx` line 91 at r4](https://reviewable.io/reviews/paranext/paranext-core/914#-O12JfBs-EvsotGOHH3O:-O12JfBs-EvsotGOHH3P:b-trlnrm) ([raw file](https://github.com/paranext/paranext-core/blob/0d12b80b57b30bee2d538618269c57a65f9d2316/extensions/src/platform-scripture/src/character-inventory.web-view.tsx#L91)):*
> ```XML
> ): Promise<CharacterData[]> => {
>   const characterData: CharacterData[] = [];
>   text.split('').forEach((character) => {
> ```

This will [fail on surrogate pairs](https://www.typescriptlang.org/play/?#code/MYewdgzgLgBFCmAPWBeGByAMiEBrQgBuDsOwIJSC8G4BY7gsARmCWOzYOY7NgZjtmB2O4Dwbgv-tWACZIPB-6ANwBYAFDiAbgEMATjGAALORBhoEyAHQQADgBsAllAAU6dAEpREsaEgg98TXpABzY0pUBtAAwBdS+K2EPaOzm4eshCeAIz+VkEhTq7uypGeAExxgeDBDknhqVEAzFk2OYlhKV4ALKUJeZURUQCsdeUNyU2eAGxtdh0FXgDsfbmhnYWeAByjFRNeAJylQA). [Here is a discussion](https://stackoverflow.com/questions/21397316/split-javascript-string-into-array-of-codepoints-taking-into-account-surrogat) of ways to do it.
___
*[`extensions/src/platform-scripture/src/character-inventory.web-view.tsx` line 238 at r4](https://reviewable.io/reviews/paranext/paranext-core/914#-O12NBPf-eK2dW_vK5mo:-O12NBPf-eK2dW_vK5mp:b-u0kybn) ([raw file](https://github.com/paranext/paranext-core/blob/0d12b80b57b30bee2d538618269c57a65f9d2316/extensions/src/platform-scripture/src/character-inventory.web-view.tsx#L238)):*
> ```XML
>           </SelectTrigger>
>           <SelectContent className="pr-font-sans">
>             <SelectItem value="All characters">All characters</SelectItem>
> ```

These should be localizable along with the `SelectContent` values further down. If you want to create a follow up ticket instead of doing it now that's OK.
___
*[`extensions/src/platform-scripture/src/main.ts` line 66 at r4](https://reviewable.io/reviews/paranext/paranext-core/914#-O12NmmI-ZtnIPWSeHIe:-O12NmmI-ZtnIPWSeHIf:b5q6m6b) ([raw file](https://github.com/paranext/paranext-core/blob/0d12b80b57b30bee2d538618269c57a65f9d2316/extensions/src/platform-scripture/src/main.ts#L66)):*
> ```XML
>   return papi.webViews.getWebView(
>     characterInventoryWebViewType,
>     { type: 'float', floatSize: { width: 775, height: 815 } },
> ```

Has UX made any statements about what size we should assume the user's screen to be? Not sure if setting window sizes like this is OK or not.
___
*[`lib/platform-bible-react/src/components/advanced-components/data-table/data-table-pagination.component.tsx` line 46 at r4](https://reviewable.io/reviews/paranext/paranext-core/914#-O12PAbp0nc8y8szLa96:-O12PAbp0nc8y8szLa97:b-wvobnq) ([raw file](https://github.com/paranext/paranext-core/blob/0d12b80b57b30bee2d538618269c57a65f9d2316/lib/platform-bible-react/src/components/advanced-components/data-table/data-table-pagination.component.tsx#L46)):*
> ```XML
>         </div>
>         <div className="pr-flex pr-w-[100px] pr-items-center pr-justify-center pr-text-sm pr-font-medium">
>           Page {table.getState().pagination.pageIndex + 1} of {table.getPageCount()}
> ```

Like another other comment I made in another file, this and other text here should be localizable.

**Review by rolfheij-sil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/914)* status: all files reviewed, 7 unresolved discussions (waiting on @lyonsil)

___
*[`extensions/src/platform-scripture/contributions/localizedStrings.json` line 15 at r4](https://reviewable.io/reviews/paranext/paranext-core/914#-O12H3vr67qCgpdRH1yY:-O1GQ0wj5cYB3fRDZXSx:b-ssecg8) ([raw file](https://github.com/paranext/paranext-core/blob/0d12b80b57b30bee2d538618269c57a65f9d2316/extensions/src/platform-scripture/contributions/localizedStrings.json#L15)):*
<details><summary><i>Previously, lyonsil (Matt Lyons) wrote…</i></summary><blockquote>

Is this a copy paste error from the previously added "Is Editable" setting?
</blockquote></details>

Whoops, I think it is. Fixed it.
___
*[`extensions/src/platform-scripture/src/character-inventory.web-view.tsx` line 30 at r4](https://reviewable.io/reviews/paranext/paranext-core/914#-O12IWpp9O032gdffnpy:-O1GQeVgCY8qfNqkVw9T:b-2qhrkh) ([raw file](https://github.com/paranext/paranext-core/blob/0d12b80b57b30bee2d538618269c57a65f9d2316/extensions/src/platform-scripture/src/character-inventory.web-view.tsx#L30)):*
<details><summary><i>Previously, lyonsil (Matt Lyons) wrote…</i></summary><blockquote>

Does this work properly for surrogate pairs? I suspect it does not but am not 100% sure.
</blockquote></details>

You're right, it doesn't. But now that I'm using our `split` function from platform-bible-utils it should work for surrogate pairs too
___
*[`extensions/src/platform-scripture/src/character-inventory.web-view.tsx` line 43 at r4](https://reviewable.io/reviews/paranext/paranext-core/914#-O12JJo7CwADQALFuz2E:-O1GT2Mx2CXa_QPNxAiY:b-nhhwc7) ([raw file](https://github.com/paranext/paranext-core/blob/0d12b80b57b30bee2d538618269c57a65f9d2316/extensions/src/platform-scripture/src/character-inventory.web-view.tsx#L43)):*
<details><summary><i>Previously, lyonsil (Matt Lyons) wrote…</i></summary><blockquote>

suggestion - I think this function could be shortened by just having a single `if/else if/else` block based on `scope` and grabs the appropriate text. Then you don't have to have two different `if/else if/else` blocks or do type asserting.
</blockquote></details>

I think you're right. I tried to avoid code duplication but I made the code needlessly complicated
___
*[`extensions/src/platform-scripture/src/character-inventory.web-view.tsx` line 91 at r4](https://reviewable.io/reviews/paranext/paranext-core/914#-O12JfBs-EvsotGOHH3O:-O1GTZD-9jBy88eAZ64q:bksa8nz) ([raw file](https://github.com/paranext/paranext-core/blob/0d12b80b57b30bee2d538618269c57a65f9d2316/extensions/src/platform-scripture/src/character-inventory.web-view.tsx#L91)):*
<details><summary><i>Previously, lyonsil (Matt Lyons) wrote…</i></summary><blockquote>

This will [fail on surrogate pairs](https://www.typescriptlang.org/play/?#code/MYewdgzgLgBFCmAPWBeGByAMiEBrQgBuDsOwIJSC8G4BY7gsARmCWOzYOY7NgZjtmB2O4Dwbgv-tWACZIPB-6ANwBYAFDiAbgEMATjGAALORBhoEyAHQQADgBsAllAAU6dAEpREsaEgg98TXpABzY0pUBtAAwBdS+K2EPaOzm4eshCeAIz+VkEhTq7uypGeAExxgeDBDknhqVEAzFk2OYlhKV4ALKUJeZURUQCsdeUNyU2eAGxtdh0FXgDsfbmhnYWeAByjFRNeAJylQA). [Here is a discussion](https://stackoverflow.com/questions/21397316/split-javascript-string-into-array-of-codepoints-taking-into-account-surrogat) of ways to do it.
</blockquote></details>

Using the `split` function from `platform-bible-utils` should fix this :)
___
*[`extensions/src/platform-scripture/src/character-inventory.web-view.tsx` line 238 at r4](https://reviewable.io/reviews/paranext/paranext-core/914#-O12NBPf-eK2dW_vK5mo:-O1GtAlZ20UXNwuTAsaJ:b-886gsx) ([raw file](https://github.com/paranext/paranext-core/blob/0d12b80b57b30bee2d538618269c57a65f9d2316/extensions/src/platform-scripture/src/character-inventory.web-view.tsx#L238)):*
<details><summary><i>Previously, lyonsil (Matt Lyons) wrote…</i></summary><blockquote>

These should be localizable along with the `SelectContent` values further down. If you want to create a follow up ticket instead of doing it now that's OK.
</blockquote></details>

Fixed
___
*[`extensions/src/platform-scripture/src/main.ts` line 66 at r4](https://reviewable.io/reviews/paranext/paranext-core/914#-O12NmmI-ZtnIPWSeHIe:-O1GTqRh1WFb0u1nt0iY:bs4gsmo) ([raw file](https://github.com/paranext/paranext-core/blob/0d12b80b57b30bee2d538618269c57a65f9d2316/extensions/src/platform-scripture/src/main.ts#L66)):*
<details><summary><i>Previously, lyonsil (Matt Lyons) wrote…</i></summary><blockquote>

Has UX made any statements about what size we should assume the user's screen to be? Not sure if setting window sizes like this is OK or not.
</blockquote></details>

No they haven't. I don't know where I got the values from. I'll just delete them for now.
___
*[`lib/platform-bible-react/src/components/advanced-components/data-table/data-table-pagination.component.tsx` line 46 at r4](https://reviewable.io/reviews/paranext/paranext-core/914#-O12PAbp0nc8y8szLa96:-O1GtDNP8tdq5z8wBS0Z:bi4tb8a) ([raw file](https://github.com/paranext/paranext-core/blob/0d12b80b57b30bee2d538618269c57a65f9d2316/lib/platform-bible-react/src/components/advanced-components/data-table/data-table-pagination.component.tsx#L46)):*
<details><summary><i>Previously, lyonsil (Matt Lyons) wrote…</i></summary><blockquote>

Like another other comment I made in another file, this and other text here should be localizable.
</blockquote></details>

I don't think we have localizable strings in `plaftorm-bible-react` yet, and I don't know where to put it and integrate it with the components there. So maybe best to make this a separate issue

**Review by rolfheij-sil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/914)* status: 38 of 43 files reviewed, 8 unresolved discussions (waiting on @lyonsil)

___
*[`extensions/src/platform-scripture/src/character-inventory.web-view.tsx` line 64 at r5](https://reviewable.io/reviews/paranext/paranext-core/914#-O1H8CR74hAlAHwTKwnC:-O1H8CR74hAlAHwTKwnD:b-ramgfc) ([raw file](https://github.com/paranext/paranext-core/blob/726972d54b90b0fa3baeae4eea4465eee477e642/extensions/src/platform-scripture/src/character-inventory.web-view.tsx#L64)):*
> ```XML
>   if (scope === 'verse') {
>     const PDP = await papi.projectDataProviders.get('platformScripture.USFM_Verse', projectId);
>     return PDP.getVerseUSFM(verseRef);
> ```

Does anyone know why this doesn't seem to work?
___
*[`lib/platform-bible-react/src/components/advanced-components/data-table/data-table-pagination.component.tsx` line 46 at r4](https://reviewable.io/reviews/paranext/paranext-core/914#-O12PAbp0nc8y8szLa96:-O1H8-KS9Hl4cYaV6qNm:b-kueyeb) ([raw file](https://github.com/paranext/paranext-core/blob/0d12b80b57b30bee2d538618269c57a65f9d2316/lib/platform-bible-react/src/components/advanced-components/data-table/data-table-pagination.component.tsx#L46)):*
<details><summary><i>Previously, rolfheij-sil (Rolf Heij) wrote…</i></summary><blockquote>

I don't think we have localizable strings in `plaftorm-bible-react` yet, and I don't know where to put it and integrate it with the components there. So maybe best to make this a separate issue
</blockquote></details>

I opened [986](https://github.com/paranext/paranext-core/issues/986)

**Review by lyonsil — DISMISSED** [review]
> Reviewed 5 of 5 files at r5, 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/914)* status: all files reviewed, 1 unresolved discussion (waiting on @tjcouch-sil)

___
*[`extensions/src/platform-scripture/src/character-inventory.web-view.tsx` line 64 at r5](https://reviewable.io/reviews/paranext/paranext-core/914#-O1H8CR74hAlAHwTKwnC:-O1Hh2RI6cMh3BfaMV8D:btr1th4) ([raw file](https://github.com/paranext/paranext-core/blob/726972d54b90b0fa3baeae4eea4465eee477e642/extensions/src/platform-scripture/src/character-inventory.web-view.tsx#L64)):*
<details><summary><i>Previously, rolfheij-sil (Rolf Heij) wrote…</i></summary><blockquote>

Does anyone know why this doesn't seem to work?
</blockquote></details>

`getVerseUSFM` is working for me. If you're still having trouble @tjcouch-sil or I can probably help.
___
*[`lib/platform-bible-react/src/components/advanced-components/data-table/data-table-pagination.component.tsx` line 46 at r4](https://reviewable.io/reviews/paranext/paranext-core/914#-O12PAbp0nc8y8szLa96:-O1HiZosC_HGmw51jcXA:b4c9lyr) ([raw file](https://github.com/paranext/paranext-core/blob/0d12b80b57b30bee2d538618269c57a65f9d2316/lib/platform-bible-react/src/components/advanced-components/data-table/data-table-pagination.component.tsx#L46)):*
<details><summary><i>Previously, rolfheij-sil (Rolf Heij) wrote…</i></summary><blockquote>

I opened [986](https://github.com/paranext/paranext-core/issues/986)
</blockquote></details>

:thumbsup:

**Review by lyonsil — COMMENTED** [review]
> Reviewed 10 of 21 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/914)* status: 37 of 48 files reviewed, 1 unresolved discussion (waiting on @tjcouch-sil)

**Review by tjcouch-sil — APPROVED** [review]
:lgtm: Rolf and I got on a long call and talked through the PR. I didn't look at everything by any means, but it's ready to merge in my opinion. He is doing a follow-up PR with fixes to a few things I noticed.

> Reviewed 24 of 43 files at r1, 1 of 8 files at r2, 1 of 5 files at r5, 1 of 2 files at r6, 21 of 21 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/914#-:-O20kalD3hIh8XVD9gPO:by3aqqv)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

___
*[`extensions/src/platform-scripture/src/character-inventory.web-view.tsx` line 64 at r5](https://reviewable.io/reviews/paranext/paranext-core/914#-O1H8CR74hAlAHwTKwnC:-O20OYqeDHQwreyXnYPY:b4gq6uk) ([raw file](https://github.com/paranext/paranext-core/blob/726972d54b90b0fa3baeae4eea4465eee477e642/extensions/src/platform-scripture/src/character-inventory.web-view.tsx#L64)):*
<details><summary><i>Previously, lyonsil (Matt Lyons) wrote…</i></summary><blockquote>

`getVerseUSFM` is working for me. If you're still having trouble @tjcouch-sil or I can probably help.
</blockquote></details>

Looks like `getVerseUSFM` broke recently. Fix at #1010

**Pull request merged**
