### PR TITLE
Add Toaster, useToast, Sonner and sonner

### PR DESCRIPTION
**Pull request by rolfheij-sil**
This change is [Reviewable](https://reviewable.io/reviews/paranext/paranext-core/1127)

### CODE REVIEW

**Review by Sebastian-ubs — COMMENTED** [review]
@rolfheij-sil I have asked Sameer on one of his last days to ad https://ui.shadcn.com/docs/components/sonner which is based on Toasts, but can stack multiple on top of each other. Please check if it makes sense to use this one instead.

> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/1127#-:-O6V9HkN05_r8DW3ii19:baawuad)* status: 0 of 11 files reviewed, all discussions resolved

**Review by Sebastian-ubs — COMMENTED** [review]
"have" > had

> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/1127#-:-O6V9tr81xWpk5FmxO1T:b40h5uu)* status: 0 of 11 files reviewed, all discussions resolved

**Review by rolfheij-sil — COMMENTED** [review]
Note that there apparently is some naming conflict, which I don't quite understand because no component or function named `Toast` is ever exported from anywhere

> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/1127#-:-O6X30NyDLFX_crUZ7hZ:bj26wee)* status: 0 of 14 files reviewed, all discussions resolved

**Review by rolfheij-sil — COMMENTED** [review]
This naming conflict is now resolved, thanks to @irahopkinson 

> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/1127#-:-O6XCuhN7MLApQr4yJSz:b-qwc9po)* status: 0 of 14 files reviewed, all discussions resolved

**Comment by tjcouch-sil** [comment]
Let's hold out on merging this til after we get a demo branch

**Review by irahopkinson — APPROVED** [review]
:lgtm:

BTW typically its best to only have one of something like this. Why add both toasters? Is it too hard to decide on only one? Does each have features the other doesn't?

> Reviewed 2 of 11 files at r1, 12 of 12 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/1127#-:-O6XIoesArBnbM-xdPaK:b-l4msze)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Review by rolfheij-sil — COMMENTED** [review]
Yeah, I agree. I took a closer look and they seem to be almost exactly the same thing, with the sonner looking slightly nicer and having slightly more features. I've removed the Toast

> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/1127#-:-O6aOWx9Emi5IAWTN404:b-kjwoqa)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Review by irahopkinson — APPROVED** [review]
:lgtm: thanks for all this work

> Reviewed 11 of 11 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/1127#-:-O6alAcpAvmKk-HfjX_e:bgvo76d)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Review by irahopkinson — APPROVED** [review]
:lgtm:

> Reviewed 13 of 13 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/1127#-:-O6vH6wC9yGRw_09vFF4:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Pull request merged**
