### PR TITLE
Fix problems with check result offset calculations and filtering

### PR DESCRIPTION
**Pull request by lyonsil**
This change is [Reviewable](https://reviewable.io/reviews/paranext/paranext-core/1198)

### CODE REVIEW

**Review by rolfheij-sil — APPROVED** [review]
> Reviewed 7 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/1198)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Review by rolfheij-sil — APPROVED** [review]
Awesome, thanks for adding this!
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/1198#-:-O8O3iWECW0CKi2vXE2n:bw8htva)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Review by lyonsil — COMMENTED** [review]
Thanks, Rolf. I realized that I should add some documentation and unit tests for the new utility class. Everything should still work the same as the previous revision.

> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/1198#-:-O8SiJ4y0y2b13vwHN8M:b-hu0kb5)* status: 5 of 9 files reviewed, all discussions resolved (waiting on @rolfheij-sil)

**Review by irahopkinson — DISMISSED** [review]
:lgtm: thanks for adding the tests and comments.

> Reviewed 7 of 7 files at r1, 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/1198#-:-O8YCEVRBzy7ljxnYWeR:b-z2b78d)* status: all files reviewed, 1 unresolved discussion (waiting on @lyonsil)

___
*[`c-sharp/Checks/CheckResultsRecorder.cs` line 127 at r1](https://reviewable.io/reviews/paranext/paranext-core/1198#-O8Y6ioW7u1sZ9NPqRge:-O8Y6ioW7u1sZ9NPqRgf:brpy1hv) ([raw file](https://github.com/paranext/paranext-core/blob/e58869e661631eb4985d6b1c6e404b66634f5611/c-sharp/Checks/CheckResultsRecorder.cs#L127)):*
> ```Smalltalk
>     }
> 
>     public List<CheckRunResult> CheckRunResults { get; } = [];
> ```

Err... shouldn't this declaration be up near the top of the class?

**Review by lyonsil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/1198)* status: 8 of 9 files reviewed, 1 unresolved discussion (waiting on @irahopkinson and @rolfheij-sil)

___
*[`c-sharp/ParatextUtils/UsfmBookIndexer.cs` line 47 at r3](https://reviewable.io/reviews/paranext/paranext-core/1198#-O8b_BJ_36DQXoEH18m-:-O8cCRNq7A_sfEjE3N9O:b-896fix) ([raw file](https://github.com/paranext/paranext-core/blob/bbb36628b72d6ed0f0842cc3fc0e8adb82b6083e/c-sharp/ParatextUtils/UsfmBookIndexer.cs#L47)):*
<details><summary><i>Previously, rolfheij-sil (Rolf Heij) wrote…</i></summary><blockquote>

`in this VerseRef` is not relevant here.
</blockquote></details>

Done.
___
*[`c-sharp/ParatextUtils/UsfmBookIndexer.cs` line 167 at r3](https://reviewable.io/reviews/paranext/paranext-core/1198#-O8bb2KZ-AmL7GC32szh:-O8cApBs5TIIw1q12TQj:bcx4dgz) ([raw file](https://github.com/paranext/paranext-core/blob/bbb36628b72d6ed0f0842cc3fc0e8adb82b6083e/c-sharp/ParatextUtils/UsfmBookIndexer.cs#L167)):*
<details><summary><i>Previously, rolfheij-sil (Rolf Heij) wrote…</i></summary><blockquote>

Wouldn't something like this be cleaner?
https://learn.microsoft.com/en-us/dotnet/api/system.int32.tryparse?view=net-8.0
Or even this maybe, since we know we're dealing with digits
https://learn.microsoft.com/en-us/dotnet/api/system.int32.parse?view=net-8.0
</blockquote></details>

I was trying to not create a new string. If those methods took a starting index into an existing string I would have used one of them.

**Review by irahopkinson — APPROVED** [review]
> Reviewed 1 of 1 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/1198)* status: all files reviewed, 1 unresolved discussion (waiting on @rolfheij-sil)

**Review by rolfheij-sil — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/1198#-:-O8cMzp_BPVK23OoZdJ5:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Pull request merged**
