### PR TITLE
Hooked up Open Text Collection command, multiple related fixes and tweaks

### PR DESCRIPTION
**Pull request by tjcouch-sil**
Menu -> Project -> "Open Text Collection..." now works
image

Also
- Added ability to filter to exclude projects from Select Project and Select Multiple Projects dialogs
- Added ability to specify project IDs to start selected on Select Multiple Projects dialog
- Fixed isSerializable to consider value undefined === no key present
- Fixed C# side not being able to return success with no content (if a book/chapter/verse is not present in a project, `scrText.Parser.GetVerseUsfmText(verseRef)` returns `null`, which was being overwritten to `[]` and causing problems)

- - -
This change is [Reviewable](https://reviewable.io/reviews/paranext/paranext-core/596)

### CODE REVIEW

**Review by lyonsil — CHANGES_REQUESTED** [review]
It will be great to have all of this hooked up!

> Reviewed 15 of 15 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/596#-:-NhgpZ-v29FVnYUOEzOv:b3gir6t)* status: all files reviewed, 3 unresolved discussions (waiting on @tjcouch-sil)

___
*[`c-sharp/MessageHandlers/ResponseToRequest.cs` line 25 at r1](https://reviewable.io/reviews/paranext/paranext-core/596#-Nhgk6w4D-IOjl4cIGoR:-Nhgk6w57t3U-FmgETdR:b-5jxmny) ([raw file](https://github.com/paranext/paranext-core/blob/54070687cf0af6f053c4446a3304981f811265ab/c-sharp/MessageHandlers/ResponseToRequest.cs#L25)):*
> ```Smalltalk
>         // Replace null with an empty list to avoid this confusing behavior.
>         contents ??= new List<object>();
>         return new ResponseToRequest(true, contents);
> ```

Are you certain that other cases where we send back "success" with no contents and the TypeScript side of things actually sees it as success?  Just wanting to double check as I thought this was something deep inside the network layer in our TS code.  It's been many months now, though, and I don't remember for certain.
___
*[`patches/nano-equal+2.0.2.patch` line 5 at r1](https://reviewable.io/reviews/paranext/paranext-core/596#-NhgouxH04QvsG3DUpqg:-NhgouxH04QvsG3DUpqh:b-dvkrgd) ([raw file](https://github.com/paranext/paranext-core/blob/e343dec5844490a1c87a552fe0c572434ef71576/patches/nano-equal%2B2.0.2.patch#L5)):*
> ```Diff
> --- a/node_modules/nano-equal/src/index.js
> +++ b/node_modules/nano-equal/src/index.js
> @@ -56,9 +56,11 @@ function getType(a) {
> ```

I noticed that about a year ago, [nano-equal weekly downloads](https://www.npmjs.com/package/nano-equal) dropped by about 10x.  It's in the hundreds now instead of thousands.  So we're relying on something that is somewhat obscure and patching it.

Given our recent discussions, it feels like we're doubling down on some changes that were based on my application of programming in other languages that don't have a precise equivalent in TS/JS and a miscommunication between the two of us.
___
*[`src/shared/utils/papi-util.ts` line 134 at r1](https://reviewable.io/reviews/paranext/paranext-core/596#-NhglRx_AFo56kXWI87G:-NhglRx_AFo56kXWI87H:bup5mzb) ([raw file](https://github.com/paranext/paranext-core/blob/e343dec5844490a1c87a552fe0c572434ef71576/src/shared/utils/papi-util.ts#L134)):*
> ```XML
>  *
>  */
> export function deepEqual(a: unknown, b: unknown, shouldCompareAcrossIframes = false) {
> ```

Would it be helpful to add a few small unit tests for this?

**Review by lyonsil — CHANGES_REQUESTED** [review]
> Reviewed 15 of 15 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/596)* status: all files reviewed, 3 unresolved discussions (waiting on @tjcouch-sil)

**Review by tjcouch-sil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/596)* status: all files reviewed, 3 unresolved discussions (waiting on @lyonsil)

___
*[`c-sharp/MessageHandlers/ResponseToRequest.cs` line 25 at r1](https://reviewable.io/reviews/paranext/paranext-core/596#-Nhgk6w4D-IOjl4cIGoR:-NhhE1EX1eAaC_QFYnL1:b7zxmom) ([raw file](https://github.com/paranext/paranext-core/blob/54070687cf0af6f053c4446a3304981f811265ab/c-sharp/MessageHandlers/ResponseToRequest.cs#L25)):*
<details><summary><i>Previously, lyonsil (Matt Lyons) wrote…</i></summary><blockquote>

Are you certain that other cases where we send back "success" with no contents and the TypeScript side of things actually sees it as success?  Just wanting to double check as I thought this was something deep inside the network layer in our TS code.  It's been many months now, though, and I don't remember for certain.
</blockquote></details>

Yeah. I had to go through everything to try to get some context as to why this was being set to `[]`. I intended to [make network object `get` messages respond with an array of function names](https://github.com/paranext/paranext-core/blob/e343dec5844490a1c87a552fe0c572434ef71576/src/shared/services/network-object.service.ts#L73), but we have never gotten to that. And now I think a lot of our network object rework plans will change all this anyway. Probably should've just let the throw there throw instead of returning `undefined`, but that's what I decided to do at the time :shrug: so the network object `get` message must return an array with who cares what in it. I think that's why this was changing `null` to `[]`, but that should really only happen in `NetworkObject.HandleGet`, so I moved it there.

In general, [requests don't have any demands put on them regarding the contents](https://github.com/paranext/paranext-core/blob/e343dec5844490a1c87a552fe0c572434ef71576/src/shared/services/network.service.ts#L221); if `success` isn't falsy, it's a success.

**Review by lyonsil — DISMISSED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/596#-:-NhhKkKICA7xqcBjbm8M:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @tjcouch-sil)

**Review by tjcouch-sil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/596)* status: 11 of 20 files reviewed, 2 unresolved discussions (waiting on @lyonsil)

___
*[`src/shared/utils/papi-util.ts` line 134 at r1](https://reviewable.io/reviews/paranext/paranext-core/596#-NhglRx_AFo56kXWI87G:-Nhi5n1xBzgBukLKiAUL:belte0y) ([raw file](https://github.com/paranext/paranext-core/blob/e343dec5844490a1c87a552fe0c572434ef71576/src/shared/utils/papi-util.ts#L134)):*
<details><summary><i>Previously, lyonsil (Matt Lyons) wrote…</i></summary><blockquote>

Would it be helpful to add a few small unit tests for this?
</blockquote></details>

I put in a bunch. Hopefully this will help us if/when we ever go back and tune these up.
___
*[`patches/nano-equal+2.0.2.patch` line 5 at r1](https://reviewable.io/reviews/paranext/paranext-core/596#-NhgouxH04QvsG3DUpqg:-Nhi5VvEAgk8OkQ3sJP3:b-9qf303) ([raw file](https://github.com/paranext/paranext-core/blob/e343dec5844490a1c87a552fe0c572434ef71576/patches/nano-equal%2B2.0.2.patch#L5)):*
<details><summary><i>Previously, lyonsil (Matt Lyons) wrote…</i></summary><blockquote>

I noticed that about a year ago, [nano-equal weekly downloads](https://www.npmjs.com/package/nano-equal) dropped by about 10x.  It's in the hundreds now instead of thousands.  So we're relying on something that is somewhat obscure and patching it.

Given our recent discussions, it feels like we're doubling down on some changes that were based on my application of programming in other languages that don't have a precise equivalent in TS/JS and a miscommunication between the two of us.
</blockquote></details>

We decided to put it back to `stringify === stringify -> parse -> stringify` for now because of various issues with any obvious options.

**Review by lyonsil — APPROVED** [review]
> Reviewed 9 of 9 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/596)* status: :shipit: complete! all files reviewed, all discussions resolved

___
*[`src/shared/utils/papi-util.ts` line 134 at r1](https://reviewable.io/reviews/paranext/paranext-core/596#-NhglRx_AFo56kXWI87G:-NhiB_H82Ujl-mngmiWl:b556ppi) ([raw file](https://github.com/paranext/paranext-core/blob/e343dec5844490a1c87a552fe0c572434ef71576/src/shared/utils/papi-util.ts#L134)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

I put in a bunch. Hopefully this will help us if/when we ever go back and tune these up.
</blockquote></details>

Awesome, thanks!

**Pull request merged**
