### PR TITLE
Quick fix for web view menus getting multiple copies of defaults

### PR DESCRIPTION
**Pull request by tjcouch-sil**
Quick fix for bug in menu combiner:

```
<WARN>Could not add menu contribution for hello-someone: Error: Error when setting the document named hello-someone: Error: Invalid output menu document: [data/webViewMenus/resourceViewer.react/topMenu/items](http://data/webViewMenus/resourceViewer.react/topMenu/items) must NOT have duplicate items (items ## 6 and 8 are identical) [at C:\Users\tj_co\source\repos\paranext-core\src\extension-host\services\extension.service.ts:781:18]
```
```
<WARN>Could not add menu contribution for verse-image-generator: Error: Error when setting the document named verse-image-generator: Error: Invalid output menu document: [data/webViewMenus/resourceViewer.react/topMenu/items](http://data/webViewMenus/resourceViewer.react/topMenu/items) must NOT have duplicate items (items ## 6 and 8 are identical) [at C:\Users\tj_co\source\repos\paranext-core\src\extension-host\services\extension.service.ts:800:18]
```

Seems almost random which menu contribution will throw. Seems it's a problem where the transform final output method runs multiple times on the same document. I don't think changing the `copyDocuments` option had any effect. I'm not sure exactly where the issue comes in, so I just deep cloned the document before changing it for now.

Also added a localized string that belongs with https://github.com/paranext/platform-bible-sample-extensions/pull/1

- - -
This change is [Reviewable](https://reviewable.io/reviews/paranext/paranext-core/861)

### CODE REVIEW

**Review by irahopkinson — CHANGES_REQUESTED** [review]
Just one blocker and a question.

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/861#-:-NviODpE5YnCh8BlyDEA:b6o4j0x)* status: all files reviewed, 2 unresolved discussions (waiting on @tjcouch-sil)

___
*[`assets/localization/eng.json` line 15 at r1](https://reviewable.io/reviews/paranext/paranext-core/861#-NviNnm88dMqV9-B7IjE:-NviNnm88dMqV9-B7IjF:b-pv5d61) ([raw file](https://github.com/paranext/paranext-core/blob/fd905c1d46b4c49e3f4c727e44122b650e304622/assets/localization/eng.json#L15)):*
> ```JSON
>   "mainMenu_openWordList": "Open Word List",
>   "mainMenu_openVerseImageGenerator": "Open Verse Image Generator",
>   "mainMenu_openVerseRefView": "Open Verse Ref View",
> ```

This feels like it doesn't belong in this PR (and you don't mention it in the PR description). Particulalry since we might want to revert this commit in order to properly fix the issue.
___
*[`src/shared/utils/menu-document-combiner.ts` line 370 at r1](https://reviewable.io/reviews/paranext/paranext-core/861#-NviNWBV5uaScCY-00oH:-NviNWBV5uaScCY-00oI:bwiahjv) ([raw file](https://github.com/paranext/paranext-core/blob/fd905c1d46b4c49e3f4c727e44122b650e304622/src/shared/utils/menu-document-combiner.ts#L370)):*
> ```XML
>     // The document given to us should be of this type
>     // eslint-disable-next-line no-type-assertion/no-type-assertion
>     const retVal = deepClone(finalOutput) as PlatformMenus;
> ```

Is there an issue to fix this properly? Since this quick fix will mask the issue we don't want to forget about it.

**Review by lyonsil — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/861)* status: all files reviewed, 2 unresolved discussions (waiting on @irahopkinson and @tjcouch-sil)

___
*[`src/shared/utils/menu-document-combiner.ts` line 370 at r1](https://reviewable.io/reviews/paranext/paranext-core/861#-NviNWBV5uaScCY-00oH:-Nvl_gFj95-Fz471bFex:b-wfmjqk) ([raw file](https://github.com/paranext/paranext-core/blob/fd905c1d46b4c49e3f4c727e44122b650e304622/src/shared/utils/menu-document-combiner.ts#L370)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

Is there an issue to fix this properly? Since this quick fix will mask the issue we don't want to forget about it.
</blockquote></details>

This doesn't feel like the right fix. I am close to updating my other PR. I will look at a cleaner fix after that.

**Review by lyonsil — APPROVED** [review]
:lgtm: 

> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/861#-:-Nvn3KOu6Jp2238NQFqe:bg7igkv)* status: all files reviewed, 1 unresolved discussion (waiting on @irahopkinson)

**Review by irahopkinson — APPROVED** [review]
:lgtm:

> Reviewed 6 of 7 files at r2, 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/861#-:-NvnAxbU1n-8RBnh-LsG:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Pull request merged**
