### PR TITLE
363 create use project data provider hook

### PR DESCRIPTION
**Pull request by katherinejensen00**
This change is [Reviewable](https://reviewable.io/reviews/paranext/paranext-core/546)

### CODE REVIEW

**Comment by lyonsil** [comment]
*[`src/renderer/components/run-basic-checks-dialog/run-basic-checks-tab.component.tsx` line 93 at r2](https://reviewable.io/reviews/paranext/paranext-core/546#-NgZKM8xA7s7BTW-CKF2:-NgZKM8xA7s7BTW-CKF3:byt4ihs) ([raw file](https://github.com/paranext/paranext-core/blob/a8d7aab9f479f412d4407448a43cde1f8aabccf5/src/renderer/components/run-basic-checks-dialog/run-basic-checks-tab.component.tsx#L93)):*
> ```XML
>     useMemo(() => {
>       return async () =>
>         project === undefined ? 'No current project' : project.getVerse(new VerseRef('MAT 4:1'));
> ```

I believe this was recently changed to `getVerseUSFM`.

**Comment by lyonsil** [comment]
*[`src/renderer/components/run-basic-checks-dialog/run-basic-checks-tab.component.tsx` line 88 at r2](https://reviewable.io/reviews/paranext/paranext-core/546#-NgZLB1QANTd9vyR1l2w:-NgZLB1QANTd9vyR1l2x:bfrijom) ([raw file](https://github.com/paranext/paranext-core/blob/a8d7aab9f479f412d4407448a43cde1f8aabccf5/src/renderer/components/run-basic-checks-dialog/run-basic-checks-tab.component.tsx#L88)):*
> ```XML
> 
>   const project = useProjectDataProvider<'ParatextStandard'>(currentProjectId);
>   logger.info(``);
> ```

Is this an accidental leftover from debugging?

**Review by tjcouch-sil — CHANGES_REQUESTED** [review]
Thanks for the hard work! Just a few things to tune up.

> Reviewed 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/546#-:-NgZaxVm4OlisRP_BC-N:bjzfh8j)* status: all files reviewed, 9 unresolved discussions (waiting on @katherinejensen00 and @lyonsil)

___
*[`src/renderer/hooks/create-use-network-object-hook.util.ts` line 7 at r2](https://reviewable.io/reviews/paranext/paranext-core/546#-NgZNZqpCzZop1JJlm2j:-NgZWgQL7WxrFtQbBVKl:bmaisow) ([raw file](https://github.com/paranext/paranext-core/blob/a8d7aab9f479f412d4407448a43cde1f8aabccf5/src/renderer/hooks/create-use-network-object-hook.util.ts#L7)):*
<details><summary><i>Previously, lyonsil (Matt Lyons) wrote…</i></summary><blockquote>

The name of this function confuses me a bit.  Could you add a description of the function to help clarify?  I think this would be the first file added to the "hooks" directory that doesn't define a hook, so we should try to be super clear.
</blockquote></details>

Agreed. Might even be worth making a subdirectory for such higher-order hooks (hook creators? generators? builders? I dunno what to call them really) like `renderer/hooks/hook-generators` or something.
___
*[`src/renderer/hooks/create-use-network-object-hook.util.ts` line 16 at r2](https://reviewable.io/reviews/paranext/paranext-core/546#-NgZMVD78pnwoO0uX_Zs:-NgZXmHa1bMgDsuLagWU:b-5qt59r) ([raw file](https://github.com/paranext/paranext-core/blob/a8d7aab9f479f412d4407448a43cde1f8aabccf5/src/renderer/hooks/create-use-network-object-hook.util.ts#L16)):*
<details><summary><i>Previously, lyonsil (Matt Lyons) wrote…</i></summary><blockquote>

All data providers are network objects, but not all network objects are data providers.  The naming of variables here is a little confusing because it seems to equate the two concepts.  If this function is about network objects, then we should remove all use of "data provider" from it.  If this function is about data providers, then all these variable names and comments should talk about network objects.
</blockquote></details>

You could probably F2 (refactor) most of these variables names to just say "NetworkObject" instead of "DataProvider".

Notes:
- This code was copied from `useDataProvider`, so I think it just needs a bit of renaming things.
- This hook creator really works with any objects that are gotten asynchronously and have `onDidDispose` now that I think about it... But probably 95% of the time we want to do that, we would be getting network objects of some sort. The idea of this hook creator is to allow you to create hooks that tie into the specific set of network objects you want like DPs and PDPs :)
___
*[`src/renderer/hooks/create-use-network-object-hook.util.ts` line 19 at r2](https://reviewable.io/reviews/paranext/paranext-core/546#-NgZMHfgAnzD0rxT7sbB:-NgZXUhOCoR4s0UT-Dim:bfmawt5) ([raw file](https://github.com/paranext/paranext-core/blob/a8d7aab9f479f412d4407448a43cde1f8aabccf5/src/renderer/hooks/create-use-network-object-hook.util.ts#L19)):*
<details><summary><i>Previously, lyonsil (Matt Lyons) wrote…</i></summary><blockquote>

Missing a word between "already" and "a"?
</blockquote></details>

Should be "received" (from the `useDataProvider` diff)
___
*[`src/renderer/hooks/papi-hooks/use-project-data-provider.hook.ts` line 8 at r2](https://reviewable.io/reviews/paranext/paranext-core/546#-NgZZhUSD3894AA8u2at:-NgZZhUSD3894AA8u2au:b-pppb2t) ([raw file](https://github.com/paranext/paranext-core/blob/a8d7aab9f479f412d4407448a43cde1f8aabccf5/src/renderer/hooks/papi-hooks/use-project-data-provider.hook.ts#L8)):*
> ```XML
> /**
>  * Gets a project data provider with specified provider name
>  * @param dataProviderSource string name of the data provider to get OR projectDataProvider (result
> ```

This needs to be rewritten since this parameter is now either the project id or the projectDataProvider. Maybe change "name of the data provider to get" to "ID for the project to get" or something.

While we're at it, it may be good to change the name of this parameter to reflect this as well since it is significantly different than it is in `useDataProvider` (sorry; I said we probably didn't need to rename this parameter before). Maybe change to `projectDataProviderSource`.
___
*[`src/renderer/hooks/papi-hooks/use-project-data-provider.hook.ts` line 14 at r2](https://reviewable.io/reviews/paranext/paranext-core/546#-NgZZrIa2CRuAdAioxCm:-NgZZrIa2CRuAdAioxCn:b-8gw6dd) ([raw file](https://github.com/paranext/paranext-core/blob/a8d7aab9f479f412d4407448a43cde1f8aabccf5/src/renderer/hooks/papi-hooks/use-project-data-provider.hook.ts#L14)):*
> ```XML
>  *  data provider is disposed
>  *
>  * @type `T` - the type of project data provider to return. Use
> ```

This should be rewritten to reflect the generic for this hook. It should say something like this:

@type `ProjectType` the project type for the project to use. The returned project data provider will have the project data provider type associated with this project type.
___
*[`src/renderer/hooks/papi-hooks/use-project-data-provider.hook.ts` line 19 at r2](https://reviewable.io/reviews/paranext/paranext-core/546#-NgZa7TND9ATBz9fGgO2:-NgZa7TO1s4X8p9Q48Bd:b1wo3u6) ([raw file](https://github.com/paranext/paranext-core/blob/a8d7aab9f479f412d4407448a43cde1f8aabccf5/src/renderer/hooks/papi-hooks/use-project-data-provider.hook.ts#L19)):*
> ```XML
>  */
> 
> const useProjectDataProvider = createUseNetworkObjectHook(
> ```

This hook needs to be added to the hooks exposed on the `papi`. You can do that by adding it to `papiHooks` in `src/renderer/hooks/papi-hooks/index.ts`

**Review by katherinejensen00 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/546)* status: 0 of 7 files reviewed, 7 unresolved discussions (waiting on @lyonsil, @tjcouch-sil, and @type)

___
*[`src/renderer/components/run-basic-checks-dialog/run-basic-checks-tab.component.tsx` line 88 at r2](https://reviewable.io/reviews/paranext/paranext-core/546#-NgZLB1QANTd9vyR1l2w:-NgZje1q4Ny1QjZLo093:b-wtkc5u) ([raw file](https://github.com/paranext/paranext-core/blob/a8d7aab9f479f412d4407448a43cde1f8aabccf5/src/renderer/components/run-basic-checks-dialog/run-basic-checks-tab.component.tsx#L88)):*
<details><summary><i>Previously, lyonsil (Matt Lyons) wrote…</i></summary><blockquote>

Is this an accidental leftover from debugging?
</blockquote></details>

Yes, thank you!
___
*[`src/renderer/components/run-basic-checks-dialog/run-basic-checks-tab.component.tsx` line 93 at r2](https://reviewable.io/reviews/paranext/paranext-core/546#-NgZKM8xA7s7BTW-CKF2:-NgZloGC7E-dPNTFWIuO:b-896fix) ([raw file](https://github.com/paranext/paranext-core/blob/a8d7aab9f479f412d4407448a43cde1f8aabccf5/src/renderer/components/run-basic-checks-dialog/run-basic-checks-tab.component.tsx#L93)):*
<details><summary><i>Previously, lyonsil (Matt Lyons) wrote…</i></summary><blockquote>

I believe this was recently changed to `getVerseUSFM`.
</blockquote></details>

Done.
___
*[`src/renderer/components/run-basic-checks-dialog/run-basic-checks-tab.component.tsx` line 95 at r2](https://reviewable.io/reviews/paranext/paranext-core/546#-NgZLSxH-5DxCpNl3QNO:-NgZk19l0IKVp0wwW1Pn:b-ulcfqc) ([raw file](https://github.com/paranext/paranext-core/blob/a8d7aab9f479f412d4407448a43cde1f8aabccf5/src/renderer/components/run-basic-checks-dialog/run-basic-checks-tab.component.tsx#L95)):*
<details><summary><i>Previously, lyonsil (Matt Lyons) wrote…</i></summary><blockquote>

Not a big deal, but I think we'd want something like "Loading" here.
</blockquote></details>

Good call
___
*[`src/renderer/hooks/papi-hooks/use-project-data-provider.hook.ts` line 8 at r2](https://reviewable.io/reviews/paranext/paranext-core/546#-NgZZhUSD3894AA8u2at:-Ng_6iUO8of3Ukoas7VE:bp5xc3a) ([raw file](https://github.com/paranext/paranext-core/blob/a8d7aab9f479f412d4407448a43cde1f8aabccf5/src/renderer/hooks/papi-hooks/use-project-data-provider.hook.ts#L8)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

This needs to be rewritten since this parameter is now either the project id or the projectDataProvider. Maybe change "name of the data provider to get" to "ID for the project to get" or something.

While we're at it, it may be good to change the name of this parameter to reflect this as well since it is significantly different than it is in `useDataProvider` (sorry; I said we probably didn't need to rename this parameter before). Maybe change to `projectDataProviderSource`.
</blockquote></details>

Good points. Those are fixed now.
___
*[`src/renderer/hooks/papi-hooks/use-project-data-provider.hook.ts` line 14 at r2](https://reviewable.io/reviews/paranext/paranext-core/546#-NgZZrIa2CRuAdAioxCm:-Ng_74w3EK2xRptusflL:b-896fix) ([raw file](https://github.com/paranext/paranext-core/blob/a8d7aab9f479f412d4407448a43cde1f8aabccf5/src/renderer/hooks/papi-hooks/use-project-data-provider.hook.ts#L14)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

This should be rewritten to reflect the generic for this hook. It should say something like this:

@type `ProjectType` the project type for the project to use. The returned project data provider will have the project data provider type associated with this project type.
</blockquote></details>

Done.
___
*[`src/renderer/hooks/papi-hooks/use-project-data-provider.hook.ts` line 19 at r2](https://reviewable.io/reviews/paranext/paranext-core/546#-NgZa7TND9ATBz9fGgO2:-Ng_7SZu2Po8N15EqFeE:b-896fix) ([raw file](https://github.com/paranext/paranext-core/blob/a8d7aab9f479f412d4407448a43cde1f8aabccf5/src/renderer/hooks/papi-hooks/use-project-data-provider.hook.ts#L19)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

This hook needs to be added to the hooks exposed on the `papi`. You can do that by adding it to `papiHooks` in `src/renderer/hooks/papi-hooks/index.ts`
</blockquote></details>

Done.
___
*[`src/renderer/hooks/create-use-network-object-hook.util.ts` line 16 at r2](https://reviewable.io/reviews/paranext/paranext-core/546#-NgZMVD78pnwoO0uX_Zs:-Ng_6G_B2-ahtcxR0Pzq:b5qydy8) ([raw file](https://github.com/paranext/paranext-core/blob/a8d7aab9f479f412d4407448a43cde1f8aabccf5/src/renderer/hooks/create-use-network-object-hook.util.ts#L16)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

You could probably F2 (refactor) most of these variables names to just say "NetworkObject" instead of "DataProvider".

Notes:
- This code was copied from `useDataProvider`, so I think it just needs a bit of renaming things.
- This hook creator really works with any objects that are gotten asynchronously and have `onDidDispose` now that I think about it... But probably 95% of the time we want to do that, we would be getting network objects of some sort. The idea of this hook creator is to allow you to create hooks that tie into the specific set of network objects you want like DPs and PDPs :)
</blockquote></details>

You are so right! Thank you

**Review by tjcouch-sil — APPROVED** [review]
:lgtm: thanks for the hard work!

> Reviewed 7 of 7 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/546#-:-Ng_qvg5AXIxyK2_ilm1:bh33jmx)* status: all files reviewed, 4 unresolved discussions (waiting on @lyonsil)

___
*[`src/renderer/hooks/papi-hooks/use-project-data-provider.hook.ts` line 21 at r3](https://reviewable.io/reviews/paranext/paranext-core/546#-Ng_qhtr9V0tf2el7FBk:-Ng_qhtr9V0tf2el7FBl:b68jmxv) ([raw file](https://github.com/paranext/paranext-core/blob/ee95b57f114e34cde52354925a03d6a86bc5738c/src/renderer/hooks/papi-hooks/use-project-data-provider.hook.ts#L21)):*
> ```XML
>   papiFrontendProjectDataProviderService.getProjectDataProvider,
> ) as <ProjectType extends ProjectTypes>(
>   projectDataProviderSource: string | IDataProvider<ProjectDataTypes[ProjectType]> | undefined,
> ```

Just an FYI for anyone looking at this and wondering what's up, I documented why we needed to do this at the bottom of this issue https://github.com/paranext/paranext-core/issues/517

**Review by irahopkinson — APPROVED** [review]
:lgtm:

> Reviewed 7 of 7 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/546#-:-NgaSlM69ewwEGQQtuvl:bnfp4nl)* status: all files reviewed, 4 unresolved discussions (waiting on @lyonsil)

**Review by lyonsil — APPROVED** [review]
> Reviewed 7 of 7 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/546)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
