### PR TITLE
Project settings validators

### PR DESCRIPTION
**Pull request by jolierabideau**
This change is [Reviewable](https://reviewable.io/reviews/paranext/paranext-core/816)

### CODE REVIEW

**Review by tjcouch-sil — CHANGES_REQUESTED** [review]
Thanks for the great work! Just a few things to adjust.

> Reviewed 7 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/816#-:-Nu5PaLv5qZ27Y1IedHQ:bounkut)* status: all files reviewed, 4 unresolved discussions (waiting on @jolierabideau)

___
*[`src/declarations/papi-shared-types.ts` line 176 at r1](https://reviewable.io/reviews/paranext/paranext-core/816#-Nu5MxnzAQoUAToet7F4:-Nu5MxnzAQoUAToet7F5:b-co0pd2) ([raw file](https://github.com/paranext/paranext-core/blob/d8d962c578439803a354704c6c59ed8ea772d5ab/src/declarations/papi-shared-types.ts#L176)):*
> ```XML
>     /**
>      * Set the value of the specified project setting on this project. `setSetting` must call
>      * `papi.projectSettings.isValid` before allowing the setting change.
> ```

Probably best to mention that we expect `setSetting` to throw if the validator failed as in https://github.com/paranext/paranext-core/blob/main/src/main/services/settings.service-host.ts#L124 :)

Also might be good to put these notes about how `setSetting` should be implemented on lower lines so they are distinct from the explanation of what the function does.
___
*[`src/main/services/project-settings.service-host.ts` line 59 at r1](https://reviewable.io/reviews/paranext/paranext-core/816#-Nu5MSsm5LLz3DSmw4Ys:-Nu5MSsm5LLz3DSmw4Yt:b-502f7a) ([raw file](https://github.com/paranext/paranext-core/blob/d8d962c578439803a354704c6c59ed8ea772d5ab/src/main/services/project-settings.service-host.ts#L59)):*
> ```XML
>     }
>     // If there is no validator let the change go through
>     return true;
> ```

I think you need to call the validator request on the network service somewhere around here, right?
___
*[`src/main/services/project-settings.service-host.test.ts` line 30 at r1](https://reviewable.io/reviews/paranext/paranext-core/816#-Nu5OAo-4YwNX3ETi-1F:-Nu5OAo-4YwNX3ETi-1G:b3ycws8) ([raw file](https://github.com/paranext/paranext-core/blob/d8d962c578439803a354704c6c59ed8ea772d5ab/src/main/services/project-settings.service-host.test.ts#L30)):*
> ```XML
> 
> describe('isValid', () => {
>   it('should return true', async () => {
> ```

This test isn't really testing much right now. Can you adjust the validator so you can test actually returning true and false in different situations? Doesn't have to be with `booksPresent`; you can make whatever validator you want :) just want to test that it is successfully passing the input down to the validator and returning the right thing as a result.
___
*[`src/shared/services/project-settings.service.ts` line 45 at r1](https://reviewable.io/reviews/paranext/paranext-core/816#-Nu5OwBH7qLDUJPqHg75:-Nu5OwBH7qLDUJPqHg76:b-rcrw3m) ([raw file](https://github.com/paranext/paranext-core/blob/d8d962c578439803a354704c6c59ed8ea772d5ab/src/shared/services/project-settings.service.ts#L45)):*
> ```XML
>   async registerValidator(key, validator) {
>     await initialize();
>     return networkObject.registerValidator(key, validator);
> ```

Since `registerValidator` is working with a function (can't be passed around the network but has to stay on the local process), you'll actually want the implementation of `registerValidator` here instead of in the host. That way, all the processes will register their validators in their own process appropriately.

**Review by tjcouch-sil — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/816)* status: all files reviewed, 5 unresolved discussions (waiting on @jolierabideau)

___
*[`src/shared/services/project-settings.service.ts` line 39 at r1](https://reviewable.io/reviews/paranext/paranext-core/816#-Nu5PuwO76ntgM32DLxs:-Nu5PuwO76ntgM32DLxt:b-7fwx58) ([raw file](https://github.com/paranext/paranext-core/blob/d8d962c578439803a354704c6c59ed8ea772d5ab/src/shared/services/project-settings.service.ts#L39)):*
> ```XML
>     return networkObject.getDefault(key, projectType);
>   },
>   async isValid(newValue, currentValue, key, allChanges, projectType) {
> ```

I see these arguments are not in the right order anymore. It shouldn't matter theoretically, but the names are now confusing.

You might actually find it is easier to just get rid of this stuff and reimplement this service using the `objectToProxy` pattern we developed after writing this extension. So then the object that gets proxied over would just have `registerValidator` in it similar to the one for settings service.

**Review by jolierabideau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/816)* status: all files reviewed, 5 unresolved discussions (waiting on @tjcouch-sil)

___
*[`src/declarations/papi-shared-types.ts` line 176 at r1](https://reviewable.io/reviews/paranext/paranext-core/816#-Nu5MxnzAQoUAToet7F4:-NuUhXVn2mhteHBg43q0:b-896fix) ([raw file](https://github.com/paranext/paranext-core/blob/d8d962c578439803a354704c6c59ed8ea772d5ab/src/declarations/papi-shared-types.ts#L176)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

Probably best to mention that we expect `setSetting` to throw if the validator failed as in https://github.com/paranext/paranext-core/blob/main/src/main/services/settings.service-host.ts#L124 :)

Also might be good to put these notes about how `setSetting` should be implemented on lower lines so they are distinct from the explanation of what the function does.
</blockquote></details>

Done.
___
*[`src/main/services/project-settings.service-host.ts` line 59 at r1](https://reviewable.io/reviews/paranext/paranext-core/816#-Nu5MSsm5LLz3DSmw4Ys:-NuUk6nQ8zgus7mHQqHt:b1ggew5) ([raw file](https://github.com/paranext/paranext-core/blob/d8d962c578439803a354704c6c59ed8ea772d5ab/src/main/services/project-settings.service-host.ts#L59)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

I think you need to call the validator request on the network service somewhere around here, right?
</blockquote></details>

Done  Yes! Sorry about that, I think I reverted it somehow before I pushed.
___
*[`src/main/services/project-settings.service-host.test.ts` line 30 at r1](https://reviewable.io/reviews/paranext/paranext-core/816#-Nu5OAo-4YwNX3ETi-1F:-NuUoCRm30Qh2QQS89EI:b-896fix) ([raw file](https://github.com/paranext/paranext-core/blob/d8d962c578439803a354704c6c59ed8ea772d5ab/src/main/services/project-settings.service-host.test.ts#L30)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

This test isn't really testing much right now. Can you adjust the validator so you can test actually returning true and false in different situations? Doesn't have to be with `booksPresent`; you can make whatever validator you want :) just want to test that it is successfully passing the input down to the validator and returning the right thing as a result.
</blockquote></details>

Done.
___
*[`src/shared/services/project-settings.service.ts` line 39 at r1](https://reviewable.io/reviews/paranext/paranext-core/816#-Nu5PuwO76ntgM32DLxs:-NuVnnD038Li9TWl-6ce:bb85o9o) ([raw file](https://github.com/paranext/paranext-core/blob/d8d962c578439803a354704c6c59ed8ea772d5ab/src/shared/services/project-settings.service.ts#L39)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

I see these arguments are not in the right order anymore. It shouldn't matter theoretically, but the names are now confusing.

You might actually find it is easier to just get rid of this stuff and reimplement this service using the `objectToProxy` pattern we developed after writing this extension. So then the object that gets proxied over would just have `registerValidator` in it similar to the one for settings service.
</blockquote></details>

Done I think I did the `objectToProxy` correctly here.
___
*[`src/shared/services/project-settings.service.ts` line 45 at r1](https://reviewable.io/reviews/paranext/paranext-core/816#-Nu5OwBH7qLDUJPqHg75:-NuVpWQB5e90ojFxVIm2:beau8j0) ([raw file](https://github.com/paranext/paranext-core/blob/d8d962c578439803a354704c6c59ed8ea772d5ab/src/shared/services/project-settings.service.ts#L45)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

Since `registerValidator` is working with a function (can't be passed around the network but has to stay on the local process), you'll actually want the implementation of `registerValidator` here instead of in the host. That way, all the processes will register their validators in their own process appropriately.
</blockquote></details>

To follow the settings service I put the implementation of `registerValidator` in the model instead of the host, is that the ideal solution? Also, since I moved the implementation of `registerValidator` I broke the host. I am struggling trying to implement `objectToProxy` in the host while still using the implementations of `getDefault` and `isValid`.

**Review by lyonsil — APPROVED** [review]
:lgtm:

> Reviewed 1 of 7 files at r1, 6 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/816#-:-Nuj9tarBZPXfIzDg-cz:bnfp4nl)* status: all files reviewed, 5 unresolved discussions (waiting on @tjcouch-sil)

___
*[`src/shared/services/project-settings.service.ts` line 45 at r1](https://reviewable.io/reviews/paranext/paranext-core/816#-Nu5OwBH7qLDUJPqHg75:-Nuj7FWfBkRuO4cAZl6B:bazj1pk) ([raw file](https://github.com/paranext/paranext-core/blob/d8d962c578439803a354704c6c59ed8ea772d5ab/src/shared/services/project-settings.service.ts#L45)):*
<details><summary><i>Previously, jolierabideau wrote…</i></summary><blockquote>

To follow the settings service I put the implementation of `registerValidator` in the model instead of the host, is that the ideal solution? Also, since I moved the implementation of `registerValidator` I broke the host. I am struggling trying to implement `objectToProxy` in the host while still using the implementations of `getDefault` and `isValid`.
</blockquote></details>

Looking back at what I did for the settings service, I think I put `registerValidator` on the model because we are creating the object to proxy there, and as TJ mentioned we need the `registerValidator` calls to always run in the local process.  That means we couldn't add it later in the shared service. `getDefault` and `isValid` should always flow over the network, though, so those belong only in the host.

**Review by tjcouch-sil — APPROVED** [review]
:lgtm: thanks for the great work on this! Sorry for the delays.

> Reviewed 6 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/816#-:-Nuyy-Tb8K2FVIUqAoe8:bgh6jwl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Pull request merged**
