### PR TITLE
fix MultiSelectComboBox placeholder color

### PR DESCRIPTION
**Pull request by Sebastian-ubs**
MultiSelectComboBox placeholder was wrongly using `muted` instead of `muted-foreground`. Also was not good for hover.
Screenshot 2024-12-06 135000
Screenshot 2024-12-06 135009

Fix is
Screenshot 2024-12-06 134947
Screenshot 2024-12-06 134937
---

Also I would like to
- fix combobox focus indicator color and shape (and maybe when it should appear)
- fix search focus indicator color
- check why search increases in width in pbr review app

image
Screenshot 2024-12-06 134436

- - -
This change is [Reviewable](https://reviewable.io/reviews/paranext/paranext-core/1374)

### CODE REVIEW

**Comment by Sebastian-ubs** [comment]
@rolfheij fyi

**Comment by rolfheij-sil** [comment]
Thanks for taking care of this!
(Also please not that @rolfheij  is my private account, and @rolfheij-sil is my work account 😁 I guess I'll change my private account username at some point)

**Review by rolfheij-sil — DISMISSED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/1374#-:-ODRO-EG4QS14nYxPNTb:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Comment by Sebastian-ubs** [comment]
> @rolfheij is my private account,

sorry 😬

**Review by rolfheij-sil — APPROVED** [review]
No worries! 
:lgtm:

> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/1374#-:-ODpdBUb6PplK2nr-zE1:bajvo6c)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Pull request merged**
