### PR TITLE
Add eslint rules

### PR DESCRIPTION
**Pull request by irahopkinson**
- add eslint rule no-unnecessary-type-assertion
- add eslint rule no-type-assertion
- remove no-non-null-assertion covered by no-non-null-assertion
- also wrapped some overlength comments

Note:
- Don't need a reason to excuse using `as` in tests since you often need to spoof data.
- Most changes are repetative adding of comments to excuse using `as`.
- Some changes remove the need for using `as`.
- One potential bug was found and noted a TODO.
- ~Another one marked as TODO as the reason is unclear why its needed at all.~

- - -
This change is [Reviewable](https://reviewable.io/reviews/paranext/paranext-core/577)

### CODE REVIEW

**Review by rolfheij-sil — APPROVED** [review]
:lgtm:

> Reviewed 58 of 58 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/577#-:-Nh62t2O3pJWdNCwDR6R:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @irahopkinson)

___
*[`lib/papi-dts/papi.d.ts` line 2139 at r1](https://reviewable.io/reviews/paranext/paranext-core/577#-Nh6-MLdEVWCpYb2FHtt:-Nh6-MLdEVWCpYb2FHtu:bgr3ekw) ([raw file](https://github.com/paranext/paranext-core/blob/9acc5e0274057e3412af78b721697541246bc9ca/lib/papi-dts/papi.d.ts#L2139)):*
> ```XML
>   export const addTab: <TData = unknown>(
>     savedTabInfo: SavedTabInfo & {
>       data?: TData | undefined;
> ```

What is happening here? I don't think I'm familiar with this syntax. What does the & do here?

**Review by irahopkinson — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/577)* status: :shipit: complete! all files reviewed, all discussions resolved

___
*[`lib/papi-dts/papi.d.ts` line 2139 at r1](https://reviewable.io/reviews/paranext/paranext-core/577#-Nh6-MLdEVWCpYb2FHtt:-Nh6A_f--dyb6zjBA1en:baivoib) ([raw file](https://github.com/paranext/paranext-core/blob/9acc5e0274057e3412af78b721697541246bc9ca/lib/papi-dts/papi.d.ts#L2139)):*
<details><summary><i>Previously, rolfheij-sil wrote…</i></summary><blockquote>

What is happening here? I don't think I'm familiar with this syntax. What does the & do here?
</blockquote></details>

The `&` unions the 2 types, however `SavedTabInfo` type already has `data`  defined as _unknown_ so this overwrites the type for `data`  to the passed in `TData` type defaulting it to _unknown_ (the orginal type) if it's not specified. This allows us to do `dialog.service-host.ts` L172 specifing that `data` will be type `DialogData` therefore we don't need to use `as` at all.

**Review by lyonsil — APPROVED** [review]
> Reviewed 58 of 58 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/577)* status: all files reviewed, 3 unresolved discussions (waiting on @irahopkinson)

___
*[`src/extension-host/services/papi-backend.service.ts` line 35 at r1](https://reviewable.io/reviews/paranext/paranext-core/577#-Nh7LbPIBsLmYClKIWFz:-Nh7LbPIBsLmYClKIWG-:bjdpa1z) ([raw file](https://github.com/paranext/paranext-core/blob/9acc5e0274057e3412af78b721697541246bc9ca/src/extension-host/services/papi-backend.service.ts#L35)):*
> ```XML
> // 2) We need to provide type assertions for all members so they carry the JSDoc comments on the
> // papi.d.ts file so extension developers see the comments. Please add to all properties you add.
> /* eslint-disable @typescript-eslint/no-unnecessary-type-assertion, no-type-assertion/no-type-assertion */
> ```

This seems like a weird place to put the assertion.  Can we move it to before or after the comments 1-3?
___
*[`src/node/services/node-file-system.service.ts` line 99 at r1](https://reviewable.io/reviews/paranext/paranext-core/577#-Nh7MVo37zkjoeZCRcMZ:-Nh7MVo37zkjoeZCRcM_:bow4j2g) ([raw file](https://github.com/paranext/paranext-core/blob/9acc5e0274057e3412af78b721697541246bc9ca/src/node/services/node-file-system.service.ts#L99)):*
> ```XML
>   const stats = await getStats(uri);
>   // Assert return type.
>   // TODO: this is covering up a potential bug. Make DirectoryEntries properties optional, remove this assert, and fix everything affected.
> ```

What is the bug?  I don't follow what your concern is here.
___
*[`src/renderer/services/papi-frontend.service.ts` line 31 at r1](https://reviewable.io/reviews/paranext/paranext-core/577#-Nh7RqxI2jR4IlLXLhKO:-Nh7RqxI2jR4IlLXLhKP:b-97gfwn) ([raw file](https://github.com/paranext/paranext-core/blob/9acc5e0274057e3412af78b721697541246bc9ca/src/renderer/services/papi-frontend.service.ts#L31)):*
> ```XML
> // 2) We need to provide type assertions for all members so they carry the JSDoc comments on the
> // papi.d.ts file so extension developers see the comments. Please add to all properties you add.
> /* eslint-disable @typescript-eslint/no-unnecessary-type-assertion, no-type-assertion/no-type-assertion */
> ```

Some comment as the other `papi` definition file.  Why are we doing this between 2 and 3 instead of before or after?

**Review by tjcouch-sil — CHANGES_REQUESTED** [review]
Phew! That was huge. Thanks for ALL the hard work on this! Must have taken quite some time. Just one thing to add an error log on, then a couple things I explained a bit more in case you want to tune up the ignore reason (no worries). Thank you!!

> Reviewed 58 of 58 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/577#-:-Nh7auCu0N6UzjMYNsNE:b-2oza80)* status: all files reviewed, 9 unresolved discussions (waiting on @irahopkinson and @lyonsil)

___
*[`extensions/src/hello-someone/hello-someone.ts` line 75 at r1](https://reviewable.io/reviews/paranext/paranext-core/577#-Nh7GmyG-SCwqqxVVgSi:-Nh7GmyG-SCwqqxVVgSj:b-ninrif) ([raw file](https://github.com/paranext/paranext-core/blob/9acc5e0274057e3412af78b721697541246bc9ca/extensions/src/hello-someone/hello-someone.ts#L75)):*
> ```XML
>   getPerson<T extends boolean = true>(
>     name: string,
>     // TODO: I don't actually know why this of type T rather than just a boolean?
> ```

Maybe it has something to do with the return conditional stuff? I don't remember; it's been a while. Sorry :p
___
*[`extensions/src/hello-someone/hello-someone.ts` line 244 at r1](https://reviewable.io/reviews/paranext/paranext-core/577#-Nh7GwLY7UQ_L2PgVM8P:-Nh7GwLY7UQ_L2PgVM8Q:b-zamfsu) ([raw file](https://github.com/paranext/paranext-core/blob/9acc5e0274057e3412af78b721697541246bc9ca/extensions/src/hello-someone/hello-someone.ts#L244)):*
> ```XML
>       ...savedWebView,
>       title: 'People',
>       // Can't use the enum value from a definition file so assert the type from the string literal.
> ```

I've been meaning to remove this enum altogether since it seems enums in the papi aren't going to be very helpful... Or I guess we could alternatively expose this enum on the papi. I dunno... Thoughts?
___
*[`extensions/src/hello-world/web-views/hello-world.web-view.tsx` line 100 at r1](https://reviewable.io/reviews/paranext/paranext-core/577#-Nh7SWNAEqxWnAxxR4kj:-Nh7SWNAEqxWnAxxR4kk:b75wj36) ([raw file](https://github.com/paranext/paranext-core/blob/9acc5e0274057e3412af78b721697541246bc9ca/extensions/src/hello-world/web-views/hello-world.web-view.tsx#L100)):*
> ```XML
>       title: 'Select Hello World Project',
>     }).current,
>     // Assert as string literal type rather than string type.
> ```

I believe we are doing the opposite: type asserting to a general string type from a const string literal type.
___
*[`extensions/webpack/webpack.util.ts` line 73 at r1](https://reviewable.io/reviews/paranext/paranext-core/577#-Nh7SytK-7BYMTMueTkn:-Nh7SytK-7BYMTMueTko:bp2qjn5) ([raw file](https://github.com/paranext/paranext-core/blob/9acc5e0274057e3412af78b721697541246bc9ca/extensions/webpack/webpack.util.ts#L73)):*
> ```XML
> export async function getWebViewEntries(): Promise<webpack.EntryObject> {
>   const tsxWebViews = await getWebViewTsxPaths();
>   const webViewEntries: webpack.EntryObject = Object.fromEntries(
> ```

Is there any particular reason you removed `[string]` from `webpack.EntryObject[string]`? Honestly I don't remember what the difference is at this point.
___
*[`src/client/services/web-socket.factory.ts` line 19 at r1](https://reviewable.io/reviews/paranext/paranext-core/577#-Nh7TyKb1-BbCtFnv4b2:-Nh7TyKb1-BbCtFnv4b3:b-l240ko) ([raw file](https://github.com/paranext/paranext-core/blob/9acc5e0274057e3412af78b721697541246bc9ca/src/client/services/web-socket.factory.ts#L19)):*
> ```XML
>   }
>   const Ws = (await import('@extension-host/services/extension-host-web-socket.model')).default;
>   // Assert the return type.
> ```

The reason this assertion is here is that the `ws` library doesn't give us a websocket object that perfectly mirrors the api of the frontend's build-in `WebSocket`, but it works well enough for our needs so I just type asserted it. In case that helps with fleshing out this type assertion reason :)
___
*[`src/extension-host/services/extension.service.ts` line 280 at r1](https://reviewable.io/reviews/paranext/paranext-core/577#-Nh7Uciu-v4xBUJrDGOV:-Nh7Uciu-v4xBUJrDGOW:byabz4n) ([raw file](https://github.com/paranext/paranext-core/blob/9acc5e0274057e3412af78b721697541246bc9ca/src/extension-host/services/extension.service.ts#L280)):*
> ```XML
>         return settled.value.main !== null;
>       })
>       // Assert the more specific type.
> ```

The reason for type asserting here is that we know that all of these settled promises are fulfilled since we filtered out the unfulfilled ones above
___
*[`src/extension-host/services/extension.service.ts` line 317 at r1](https://reviewable.io/reviews/paranext/paranext-core/577#-Nh7Uxs50RCnzHl_jaSi:-Nh7Uxs50RCnzHl_jaSj:bprbeok) ([raw file](https://github.com/paranext/paranext-core/blob/9acc5e0274057e3412af78b721697541246bc9ca/src/extension-host/services/extension.service.ts#L317)):*
> ```XML
> async function activateExtension(extension: ExtensionInfo): Promise<ActiveExtension> {
>   // Import the extension file. Tell webpack to ignore it because extension files are not in the
>   // bundle and should not be looked up in the bundle. Assert a more ambiguous type.
> ```

This is type asserted to be ambiguous because we don't know if the module is cjs or esmodule iirc. Or something along those lines; it was doing weird things. Or maybe it was that require was doing different things in dev and prod. I don't remember exactly.
___
*[`src/node/services/node-file-system.service.ts` line 99 at r1](https://reviewable.io/reviews/paranext/paranext-core/577#-Nh7MVo37zkjoeZCRcMZ:-Nh7Wa9bD0UKaqLGJCFT:b-6gui02) ([raw file](https://github.com/paranext/paranext-core/blob/9acc5e0274057e3412af78b721697541246bc9ca/src/node/services/node-file-system.service.ts#L99)):*
<details><summary><i>Previously, lyonsil (Matt Lyons) wrote…</i></summary><blockquote>

What is the bug?  I don't follow what your concern is here.
</blockquote></details>

I wonder if the bug is the same bug that someone ran into a while ago and I fixed with that "Fill in each missing EntryType with an empty array" block down there on line 120 ([commit details](https://github.com/paranext/paranext-core/commit/bafbd7ac527544504a3c232195e99c2a5d858900)). Basically the code that uses `readDir` to expect the returned object to have all keys of `EntryType` exist as arrays whether or not there's anything in them.
___
*[`src/renderer/index.tsx` line 57 at r1](https://reviewable.io/reviews/paranext/paranext-core/577#-Nh7XOHA6oJfiKd2325U:-Nh7XOHA6oJfiKd2325V:b-f5539z) ([raw file](https://github.com/paranext/paranext-core/blob/9acc5e0274057e3412af78b721697541246bc9ca/src/renderer/index.tsx#L57)):*
> ```XML
> 
> const container = document.getElementById('root');
> if (container) {
> ```

I asserted here because it's a catastrophic error if `container` doesn't exist. Could we `logger.error` something if this doesn't exist?

**Review by irahopkinson — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/577)* status: all files reviewed, 5 unresolved discussions (waiting on @lyonsil and @tjcouch-sil)

___
*[`extensions/src/hello-someone/hello-someone.ts` line 75 at r1](https://reviewable.io/reviews/paranext/paranext-core/577#-Nh7GmyG-SCwqqxVVgSi:-Nh8RBGmDDTYHp6bAuYC:bn7rm82) ([raw file](https://github.com/paranext/paranext-core/blob/9acc5e0274057e3412af78b721697541246bc9ca/extensions/src/hello-someone/hello-someone.ts#L75)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

Maybe it has something to do with the return conditional stuff? I don't remember; it's been a while. Sorry :p
</blockquote></details>

I'd like to discuss this with you.
___
*[`extensions/src/hello-someone/hello-someone.ts` line 244 at r1](https://reviewable.io/reviews/paranext/paranext-core/577#-Nh7GwLY7UQ_L2PgVM8P:-Nh8DujC7pzcG1-hc3pN:bkqw6m7) ([raw file](https://github.com/paranext/paranext-core/blob/9acc5e0274057e3412af78b721697541246bc9ca/extensions/src/hello-someone/hello-someone.ts#L244)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

I've been meaning to remove this enum altogether since it seems enums in the papi aren't going to be very helpful... Or I guess we could alternatively expose this enum on the papi. I dunno... Thoughts?
</blockquote></details>

We could create a const object to replicate the enum. Would that work from the `papi.d.ts`?
___
*[`extensions/src/hello-world/web-views/hello-world.web-view.tsx` line 100 at r1](https://reviewable.io/reviews/paranext/paranext-core/577#-Nh7SWNAEqxWnAxxR4kj:-Nh8FA7W0tE20UhjeXMo:bbkmhcc) ([raw file](https://github.com/paranext/paranext-core/blob/9acc5e0274057e3412af78b721697541246bc9ca/extensions/src/hello-world/web-views/hello-world.web-view.tsx#L100)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

I believe we are doing the opposite: type asserting to a general string type from a const string literal type.
</blockquote></details>

Opps, swapped it now.
___
*[`extensions/webpack/webpack.util.ts` line 73 at r1](https://reviewable.io/reviews/paranext/paranext-core/577#-Nh7SytK-7BYMTMueTkn:-Nh8FfYKBYd3dB2IvQOR:b-3ropcz) ([raw file](https://github.com/paranext/paranext-core/blob/9acc5e0274057e3412af78b721697541246bc9ca/extensions/webpack/webpack.util.ts#L73)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

Is there any particular reason you removed `[string]` from `webpack.EntryObject[string]`? Honestly I don't remember what the difference is at this point.
</blockquote></details>

I don't know either. This is the type the IDE said `webViewEntries` was before I removed the `as` and given it's also the return type I just went with that which just means the `as` was not necessary. Of course it could mean that `webpack.EntryObject[string]` and `webpack.EntryObject` are only coincidentialy the same type but then the return type and the previous assert would be wrong.
___
*[`src/client/services/web-socket.factory.ts` line 19 at r1](https://reviewable.io/reviews/paranext/paranext-core/577#-Nh7TyKb1-BbCtFnv4b2:-Nh8I6kF7D8QoQvLuXDI:b-qgy4nj) ([raw file](https://github.com/paranext/paranext-core/blob/9acc5e0274057e3412af78b721697541246bc9ca/src/client/services/web-socket.factory.ts#L19)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

The reason this assertion is here is that the `ws` library doesn't give us a websocket object that perfectly mirrors the api of the frontend's build-in `WebSocket`, but it works well enough for our needs so I just type asserted it. In case that helps with fleshing out this type assertion reason :)
</blockquote></details>

Thanks, I updated the comment. Perhaps it might be better to assert the other way around so that nothing is missing from both and then we won't try to use something that is missing from the other, but out of scope here.
___
*[`src/extension-host/services/extension.service.ts` line 280 at r1](https://reviewable.io/reviews/paranext/paranext-core/577#-Nh7Uciu-v4xBUJrDGOV:-Nh8Jafs4m5uLWQ-vFZU:b-dtkdrq) ([raw file](https://github.com/paranext/paranext-core/blob/9acc5e0274057e3412af78b721697541246bc9ca/src/extension-host/services/extension.service.ts#L280)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

The reason for type asserting here is that we know that all of these settled promises are fulfilled since we filtered out the unfulfilled ones above
</blockquote></details>

Done, thanks.
___
*[`src/extension-host/services/extension.service.ts` line 317 at r1](https://reviewable.io/reviews/paranext/paranext-core/577#-Nh7Uxs50RCnzHl_jaSi:-Nh8KGCpCU2Gz1tLFKfJ:b4xtu8q) ([raw file](https://github.com/paranext/paranext-core/blob/9acc5e0274057e3412af78b721697541246bc9ca/src/extension-host/services/extension.service.ts#L317)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

This is type asserted to be ambiguous because we don't know if the module is cjs or esmodule iirc. Or something along those lines; it was doing weird things. Or maybe it was that require was doing different things in dev and prod. I don't remember exactly.
</blockquote></details>

Hmm... from your answer I'd say leave the more 'ambigious' comment as is since your repsonse isn't any clearer :grin: .
___
*[`src/extension-host/services/papi-backend.service.ts` line 35 at r1](https://reviewable.io/reviews/paranext/paranext-core/577#-Nh7LbPIBsLmYClKIWFz:-Nh8L0w65-mSp25HGNID:b-2gvbiq) ([raw file](https://github.com/paranext/paranext-core/blob/9acc5e0274057e3412af78b721697541246bc9ca/src/extension-host/services/papi-backend.service.ts#L35)):*
<details><summary><i>Previously, lyonsil (Matt Lyons) wrote…</i></summary><blockquote>

This seems like a weird place to put the assertion.  Can we move it to before or after the comments 1-3?
</blockquote></details>

It's here right below comment 2 which explains the reason for including it. I'm happy to move it if you think that would be clearer.
___
*[`src/node/services/node-file-system.service.ts` line 99 at r1](https://reviewable.io/reviews/paranext/paranext-core/577#-Nh7MVo37zkjoeZCRcMZ:-Nh8O0cLAg1b2l4UXwzh:beug3al) ([raw file](https://github.com/paranext/paranext-core/blob/9acc5e0274057e3412af78b721697541246bc9ca/src/node/services/node-file-system.service.ts#L99)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

I wonder if the bug is the same bug that someone ran into a while ago and I fixed with that "Fill in each missing EntryType with an empty array" block down there on line 120 ([commit details](https://github.com/paranext/paranext-core/commit/bafbd7ac527544504a3c232195e99c2a5d858900)). Basically the code that uses `readDir` to expect the returned object to have all keys of `EntryType` exist as arrays whether or not there's anything in them.
</blockquote></details>

Right, `DirectoryEntries` declares that the 3 properties defined by `EntryType` will exist. This early return doesn't supply them but worst it declares that they do exist. Thanks for pointing out L120 so I've updated the comment. I can make a separate PR to remove the potential bug.
___
*[`src/renderer/index.tsx` line 57 at r1](https://reviewable.io/reviews/paranext/paranext-core/577#-Nh7XOHA6oJfiKd2325U:-Nh8QU2VAkSQ-T1D75fJ:b-sz0oci) ([raw file](https://github.com/paranext/paranext-core/blob/9acc5e0274057e3412af78b721697541246bc9ca/src/renderer/index.tsx#L57)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

I asserted here because it's a catastrophic error if `container` doesn't exist. Could we `logger.error` something if this doesn't exist?
</blockquote></details>

Good idea to show something more fatal, however I just throw instead since that's the only way to exit from a main script.
___
*[`src/renderer/services/papi-frontend.service.ts` line 31 at r1](https://reviewable.io/reviews/paranext/paranext-core/577#-Nh7RqxI2jR4IlLXLhKO:-Nh8LVIM3e-qFP77voGO:b-2gvbiq) ([raw file](https://github.com/paranext/paranext-core/blob/9acc5e0274057e3412af78b721697541246bc9ca/src/renderer/services/papi-frontend.service.ts#L31)):*
<details><summary><i>Previously, lyonsil (Matt Lyons) wrote…</i></summary><blockquote>

Some comment as the other `papi` definition file.  Why are we doing this between 2 and 3 instead of before or after?
</blockquote></details>

It's here right below comment 2 which explains the reason for including it. I'm happy to move it if you think that would be clearer.

**Review by tjcouch-sil — APPROVED** [review]
:lgtm: great! Thanks for the quick updates!!

> Reviewed 6 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/577#-:-Nh8SwYmB0P6n_eiT7R5:bhs3d07)* status: all files reviewed, 2 unresolved discussions (waiting on @lyonsil)

___
*[`extensions/src/hello-someone/hello-someone.ts` line 244 at r1](https://reviewable.io/reviews/paranext/paranext-core/577#-Nh7GwLY7UQ_L2PgVM8P:-Nh8SAy_5gQ4I1m2ykS3:bnlvl45) ([raw file](https://github.com/paranext/paranext-core/blob/9acc5e0274057e3412af78b721697541246bc9ca/extensions/src/hello-someone/hello-someone.ts#L244)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

We could create a const object to replicate the enum. Would that work from the `papi.d.ts`?
</blockquote></details>

I think they're pretty much the same thing, so I think that would work. I imagine it would probably be worth trying the actual enum if we go that route, though. Either way, I don't think you need to worry about it for this PR; just realized it was still like this...

**Review by lyonsil — DISMISSED** [review]
:lgtm:

> Reviewed 6 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/577#-:-Nh8V_nQ0c41zkBVW_cN:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @irahopkinson)

___
*[`src/extension-host/services/papi-backend.service.ts` line 35 at r1](https://reviewable.io/reviews/paranext/paranext-core/577#-Nh7LbPIBsLmYClKIWFz:-Nh8VRZhEhseP-rx1Fne:b-okba3c) ([raw file](https://github.com/paranext/paranext-core/blob/9acc5e0274057e3412af78b721697541246bc9ca/src/extension-host/services/papi-backend.service.ts#L35)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

It's here right below comment 2 which explains the reason for including it. I'm happy to move it if you think that would be clearer.
</blockquote></details>

I totally missed that.  Makes sense.
___
*[`src/node/services/node-file-system.service.ts` line 99 at r1](https://reviewable.io/reviews/paranext/paranext-core/577#-Nh7MVo37zkjoeZCRcMZ:-Nh8VGPq-_exonsIkWS1:b-eria3x) ([raw file](https://github.com/paranext/paranext-core/blob/9acc5e0274057e3412af78b721697541246bc9ca/src/node/services/node-file-system.service.ts#L99)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

Right, `DirectoryEntries` declares that the 3 properties defined by `EntryType` will exist. This early return doesn't supply them but worst it declares that they do exist. Thanks for pointing out L120 so I've updated the comment. I can make a separate PR to remove the potential bug.
</blockquote></details>

Thanks, that makes sense.  A separate PR to fix sounds good.
___
*[`src/renderer/services/papi-frontend.service.ts` line 31 at r1](https://reviewable.io/reviews/paranext/paranext-core/577#-Nh7RqxI2jR4IlLXLhKO:-Nh8VNz_2st-UCUSi250:b-okba3c) ([raw file](https://github.com/paranext/paranext-core/blob/9acc5e0274057e3412af78b721697541246bc9ca/src/renderer/services/papi-frontend.service.ts#L31)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

It's here right below comment 2 which explains the reason for including it. I'm happy to move it if you think that would be clearer.
</blockquote></details>

I totally missed that.  Makes sense.

**Review by irahopkinson — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/577)* status: 57 of 58 files reviewed, all discussions resolved (waiting on @lyonsil and @tjcouch-sil)

___
*[`extensions/src/hello-someone/hello-someone.ts` line 75 at r1](https://reviewable.io/reviews/paranext/paranext-core/577#-Nh7GmyG-SCwqqxVVgSi:-Nh8nUR5CjMmMCi181yt:b-14pttg) ([raw file](https://github.com/paranext/paranext-core/blob/9acc5e0274057e3412af78b721697541246bc9ca/extensions/src/hello-someone/hello-someone.ts#L75)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

I'd like to discuss this with you.
</blockquote></details>

Fixed up now.

**Review by tjcouch-sil — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/577#-:-Nh8oAFP8qkj6tmc5F2f:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
