### PR TITLE
Prepare the resource viewer to be able to open resource projects

### PR DESCRIPTION
**Pull request by lyonsil**
This PR does everything except provide the correct password for accessing resources. I will add a patch for that to the P10S repo.

This PR includes 2 small cleanup things:
1) In addition to adding a new cspell entry, I updated a few to be lowercase per previous review discussions.
2) When I ran `npm install`, the `package-lock.json` file changed. I'm checking in the latest version of the lock file so that it matches up with `package.json`.

- - -
This change is [Reviewable](https://reviewable.io/reviews/paranext/paranext-core/1271)

### CODE REVIEW

**Review by irahopkinson — CHANGES_REQUESTED** [review]
Thanks for figuring this stuff out.

> Reviewed 6 of 6 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/1271#-:-OB26Cxi9-EgX2Ynwi1W:bwxco8o)* status: all files reviewed, 1 unresolved discussion (waiting on @lyonsil)

___
*[`c-sharp/Projects/DigitalBibleLibrary/DblResourcePasswordProvider.cs` line 9 at r1](https://reviewable.io/reviews/paranext/paranext-core/1271#-OB25UlR7zuctDZCUFgF:-OB25UlSE9mHpYegLeue:b-ubhvq3) ([raw file](https://github.com/paranext/paranext-core/blob/867e9706e571cdb64886e1a70faf6d3b1b1f5625/c-sharp/Projects/DigitalBibleLibrary/DblResourcePasswordProvider.cs#L9)):*
> ```Smalltalk
>     public string GetPassword()
>     {
>         return "This is not the real password, so resources cannot be opened with it.";
> ```

As per my comment on the issue, could we use the dotnet secrets here so at least developers can use resources even in Platform? You could still patch this in PT10S repo and consider GH secrets at a later stage.

**Review by lyonsil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/1271)* status: 5 of 12 files reviewed, 1 unresolved discussion (waiting on @irahopkinson)

___
*[`c-sharp/Projects/DigitalBibleLibrary/DblResourcePasswordProvider.cs` line 9 at r1](https://reviewable.io/reviews/paranext/paranext-core/1271#-OB25UlR7zuctDZCUFgF:-OB73mp1AghCnFDIKLsu:brq3yjc) ([raw file](https://github.com/paranext/paranext-core/blob/867e9706e571cdb64886e1a70faf6d3b1b1f5625/c-sharp/Projects/DigitalBibleLibrary/DblResourcePasswordProvider.cs#L9)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

As per my comment on the issue, could we use the dotnet secrets here so at least developers can use resources even in Platform? You could still patch this in PT10S repo and consider GH secrets at a later stage.
</blockquote></details>

I made some updates per our discussion on this. I will still patch the P10S code.

**Review by irahopkinson — APPROVED** [review]
:lgtm: thanks for this

> Reviewed 7 of 7 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/1271#-:-OB7F6M8Ay2emy_x3S7e:b-r4tcg3)* status: all files reviewed, 1 unresolved discussion (waiting on @lyonsil)

___
*[`c-sharp/Projects/LocalParatextProjects.cs` line 134 at r3](https://reviewable.io/reviews/paranext/paranext-core/1271#-OB7DX-yBkxx2jZ4-Ktj:-OB7DX-yBkxx2jZ4-Ktk:b-dly5pj) ([raw file](https://github.com/paranext/paranext-core/blob/922fbf94faaa38c8fec5d352aa38cb7b562d049e/c-sharp/Projects/LocalParatextProjects.cs#L134)):*
> ```Smalltalk
>     {
>         var retVal = ScrTextCollection.GetById(HexId.FromStr(projectId));
>         if (retVal.IsResourceProject && !RegistrationInfo.DefaultUser.IsValid)
> ```

BTW should this be OR, i.e. `if (retVal.IsResourceProject ||  !RegistrationInfo.DefaultUser.IsValid)`?

**Review by lyonsil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/1271)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

___
*[`c-sharp/Projects/LocalParatextProjects.cs` line 134 at r3](https://reviewable.io/reviews/paranext/paranext-core/1271#-OB7DX-yBkxx2jZ4-Ktj:-OB7Gj0_AjC6eOZHUDn3:b-gc29wm) ([raw file](https://github.com/paranext/paranext-core/blob/922fbf94faaa38c8fec5d352aa38cb7b562d049e/c-sharp/Projects/LocalParatextProjects.cs#L134)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

BTW should this be OR, i.e. `if (retVal.IsResourceProject ||  !RegistrationInfo.DefaultUser.IsValid)`?
</blockquote></details>

AND is the intent. If you're trying a resource project AND you aren't a registered user, too bad. If you're not registered and opening a normal project, that's fine. If you're registered and opening any kind of project, that's fine. It's only the combination of resource (DBL) project and being unregistered that is the problem.

After making the suggested changes with the password class, I pulled most of the changes I want to make in P10S into this project. This meant putting the guards in place to prevent opening resource projects if you aren't registered.

**Pull request merged**
