### PR TITLE
158 Use checkbox and textfield in table

### PR DESCRIPTION
**Pull request by rolfheij-sil**
This change is [Reviewable](https://reviewable.io/reviews/paranext/paranext-core/245)

### CODE REVIEW

**Review by tjcouch-sil — COMMENTED** [review]
Thanks for the hard work on this! I am not sure if I will be here to discuss, so my two comments are not blocking. If you address them, please feel free to resolve them and to let someone else approve of the PR. Looking forward to having this in!

> Reviewed 15 of 15 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/245#-:-NXvtwiT8FCzN9Pzs9N_:b1yk7ah)* status: all files reviewed, 3 unresolved discussions (waiting on @rolfheij-sil)

___
*[`.vscode/tasks.json` line 1 at r1](https://reviewable.io/reviews/paranext/paranext-core/245#-NXu21FI6Il39J2cKEsn:-NXvryUw-VEdxzO1sinJ:btx5hju) ([raw file](https://github.com/paranext/paranext-core/blob/4f00e1676d75589a6a9b604e1b274659ac42e7c2/.vscode/tasks.json#L1)):*
<details><summary><i>Previously, rolfheij-sil wrote…</i></summary><blockquote>

Not sure how this file got added. I think I'd better remove it, right?
</blockquote></details>

Yep, you don't need this file. Thanks! VSCode adds it if you click add missing build dependencies or something. We don't need it, though, as we do these things in npm scripts, which automatically get turned into tasks in VSCode.
___
*[`lib/papi-components/src/table.component.tsx` line 97 at r1](https://reviewable.io/reviews/paranext/paranext-core/245#-NXvtTU5-va6BhOOYZWI:-NXvtTU5-va6BhOOYZWJ:b94sjy5) ([raw file](https://github.com/paranext/paranext-core/blob/4f00e1676d75589a6a9b604e1b274659ac42e7c2/lib/papi-components/src/table.component.tsx#L97)):*
> ```XML
> export type TableSortColumn = SortColumn;
> 
> export function TableTextEditor<R>({
> ```

Can you find a way to provide this as the default `renderEditCell` for each column? So like the default editor is always replaced with this. But then people can still overwrite `renderEditCell` with whatever they want, of course.

Then you won't have to provide it as the `renderEditCell` in all the places the table is used like in `hello-world.web-view.tsx`
___
*[`lib/papi-components/src/table.component.tsx` line 277 at r1](https://reviewable.io/reviews/paranext/paranext-core/245#-NXvtDd02p2zowshYb9A:-NXvtDd02p2zowshYb9B:bf7tedu) ([raw file](https://github.com/paranext/paranext-core/blob/4f00e1676d75589a6a9b604e1b274659ac42e7c2/lib/papi-components/src/table.component.tsx#L277)):*
> ```XML
>   }, [enableSelectColumn, columns]);
> 
>   function renderCheckbox({ onChange, ...props }: RenderCheckboxProps) {
> ```

Can this be moved out of the Table component similar to the TableTextEditor? If it is inside, it will create the function every time Table is rendered, whereas it appears not to have any dependencies inside the Table function. I could be missing something.

**Review by irahopkinson — CHANGES_REQUESTED** [review]
Thanks for finishing the table component!

> Reviewed 15 of 15 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/245#-:-NXxC_124fJtC8IvZIGi:b9o4dr3)* status: all files reviewed, 8 unresolved discussions (waiting on @rolfheij-sil)

___
*[`extensions/lib/hello-world/hello-world.web-view.tsx` line 37 at r1](https://reviewable.io/reviews/paranext/paranext-core/245#-NXx7g5i1mIWnwrZtC_C:-NXx7g5i1mIWnwrZtC_D:bepo7ux) ([raw file](https://github.com/paranext/paranext-core/blob/4f00e1676d75589a6a9b604e1b274659ac42e7c2/extensions/lib/hello-world/hello-world.web-view.tsx#L37)):*
> ```XML
>   const test = useContext(TestContext) || "Context didn't work!! :(";
> 
>   const initializeRows = () => {
> ```

BTW I'm not sure why this isn't just an array literal rather than this function that returns one? Either way you should specify the type as `Row[]`.
___
*[`extensions/lib/hello-world/hello-world.web-view.tsx` line 50 at r1](https://reviewable.io/reviews/paranext/paranext-core/245#-NXx9wnk4eEQqMqGuIyl:-NXx9wnk4eEQqMqGuIym:bjzp4zl) ([raw file](https://github.com/paranext/paranext-core/blob/4f00e1676d75589a6a9b604e1b274659ac42e7c2/extensions/lib/hello-world/hello-world.web-view.tsx#L50)):*
> ```XML
>   const [myState, setMyState] = useState(0);
>   const [rows, setRows] = useState(initializeRows());
>   const [selRows, setSelRows] = useState(new Set<Key>());
> ```

For several names you have used the abbreviation `sel`. Our style guide says to avoid abbreviations.
___
*[`extensions/lib/hello-world/hello-world.web-view.tsx` line 86 at r1](https://reviewable.io/reviews/paranext/paranext-core/245#-NXx8KmU6VzWuTt1brIK:-NXx8KmU6VzWuTt1brIL:b-6ny8qu) ([raw file](https://github.com/paranext/paranext-core/blob/4f00e1676d75589a6a9b604e1b274659ac42e7c2/extensions/lib/hello-world/hello-world.web-view.tsx#L86)):*
> ```XML
>   );
> 
>   type Row = {
> ```

BTW it's best to have local types declared at the top of the file below imports (and before consts). Then they are collected together and if one needs to be exported or moved out into a `.model.ts` file it's already close to where it would be imported.
___
*[`extensions/lib/hello-world/hello-world.web-view.tsx` line 92 at r1](https://reviewable.io/reviews/paranext/paranext-core/245#-NXx92zm1gRVxJm7jET-:-NXx92zm1gRVxJm7jET0:b-ku21ek) ([raw file](https://github.com/paranext/paranext-core/blob/4f00e1676d75589a6a9b604e1b274659ac42e7c2/extensions/lib/hello-world/hello-world.web-view.tsx#L92)):*
> ```XML
>   };
> 
>   const rowsChangeHandler = (changedRows: Row[]): void => {
> ```

BTW this is probably a style preference on my part but these two handlers don't need to be arrow functions since they don't use `this` and the syntax for standard functions are a little cleaner and therefore easier to read.
___
*[`extensions/lib/hello-world/hello-world.web-view.tsx` line 148 at r1](https://reviewable.io/reviews/paranext/paranext-core/245#-NXxDKSo-c2S6i2f_xmk:-NXxDKSp9wD1DiJHs49Y:b-2sm9jv) ([raw file](https://github.com/paranext/paranext-core/blob/4f00e1676d75589a6a9b604e1b274659ac42e7c2/extensions/lib/hello-world/hello-world.web-view.tsx#L148)):*
> ```XML
>         <Slider /> {/* no label available */}
>         <RefSelector scrRef={{ book: 1, chapter: 1, verse: 1 }} handleSubmit={(): void => {}} />
>         <Table<Row>
> ```

BTW this isn't formatted/styled like a table. Is it possible to improve that for this example?

**Review by irahopkinson — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/245)* status: all files reviewed, 9 unresolved discussions (waiting on @rolfheij-sil)

___
*[`extensions/lib/hello-world/hello-world.web-view.tsx` line 157 at r1](https://reviewable.io/reviews/paranext/paranext-core/245#-NXxDv2X7TT6JMw2kVGR:-NXxDv2X7TT6JMw2kVGS:b-dxu88r) ([raw file](https://github.com/paranext/paranext-core/blob/4f00e1676d75589a6a9b604e1b274659ac42e7c2/extensions/lib/hello-world/hello-world.web-view.tsx#L157)):*
> ```XML
>               key: 'title',
>               name: 'Title',
>               renderEditCell: TableTextEditor<Row>,
> ```

BTW the textfield isn't editable - is it meant to be?

**Review by rolfheij-sil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/245)* status: all files reviewed, 5 unresolved discussions (waiting on @irahopkinson and @tjcouch-sil)

___
*[`extensions/lib/hello-world/hello-world.web-view.tsx` line 37 at r1](https://reviewable.io/reviews/paranext/paranext-core/245#-NXx7g5i1mIWnwrZtC_C:-NXyeIrYDMnJwcTfH6H1:bb6un1j) ([raw file](https://github.com/paranext/paranext-core/blob/4f00e1676d75589a6a9b604e1b274659ac42e7c2/extensions/lib/hello-world/hello-world.web-view.tsx#L37)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

BTW I'm not sure why this isn't just an array literal rather than this function that returns one? Either way you should specify the type as `Row[]`.
</blockquote></details>

Done
___
*[`extensions/lib/hello-world/hello-world.web-view.tsx` line 50 at r1](https://reviewable.io/reviews/paranext/paranext-core/245#-NXx9wnk4eEQqMqGuIyl:-NXyeXCP8P4hVyK3wQo_:bb6un1j) ([raw file](https://github.com/paranext/paranext-core/blob/4f00e1676d75589a6a9b604e1b274659ac42e7c2/extensions/lib/hello-world/hello-world.web-view.tsx#L50)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

For several names you have used the abbreviation `sel`. Our style guide says to avoid abbreviations.
</blockquote></details>

Done
___
*[`extensions/lib/hello-world/hello-world.web-view.tsx` line 86 at r1](https://reviewable.io/reviews/paranext/paranext-core/245#-NXx8KmU6VzWuTt1brIK:-NXyehmr2Z5-QGMu40HD:bb6un1j) ([raw file](https://github.com/paranext/paranext-core/blob/4f00e1676d75589a6a9b604e1b274659ac42e7c2/extensions/lib/hello-world/hello-world.web-view.tsx#L86)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

BTW it's best to have local types declared at the top of the file below imports (and before consts). Then they are collected together and if one needs to be exported or moved out into a `.model.ts` file it's already close to where it would be imported.
</blockquote></details>

Done
___
*[`extensions/lib/hello-world/hello-world.web-view.tsx` line 92 at r1](https://reviewable.io/reviews/paranext/paranext-core/245#-NXx92zm1gRVxJm7jET-:-NXyewkCDGpYiUoVXXA_:bfzf832) ([raw file](https://github.com/paranext/paranext-core/blob/4f00e1676d75589a6a9b604e1b274659ac42e7c2/extensions/lib/hello-world/hello-world.web-view.tsx#L92)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

BTW this is probably a style preference on my part but these two handlers don't need to be arrow functions since they don't use `this` and the syntax for standard functions are a little cleaner and therefore easier to read.
</blockquote></details>

I've just removed them entirely and put them as inlines in the Table's props
___
*[`extensions/lib/hello-world/hello-world.web-view.tsx` line 148 at r1](https://reviewable.io/reviews/paranext/paranext-core/245#-NXxDKSo-c2S6i2f_xmk:-NXyf-qH382ZU1XACiz9:b4gqnqh) ([raw file](https://github.com/paranext/paranext-core/blob/4f00e1676d75589a6a9b604e1b274659ac42e7c2/extensions/lib/hello-world/hello-world.web-view.tsx#L148)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

BTW this isn't formatted/styled like a table. Is it possible to improve that for this example?
</blockquote></details>

I've looked into this with TJ a while ago, and it seems that for some reason the CSS file from react-data-grid is not handled properly. I'm looking into this right now.
___
*[`extensions/lib/hello-world/hello-world.web-view.tsx` line 157 at r1](https://reviewable.io/reviews/paranext/paranext-core/245#-NXxDv2X7TT6JMw2kVGR:-NXyfM6o0XGfXHfw1XVS:b-xtg7sy) ([raw file](https://github.com/paranext/paranext-core/blob/4f00e1676d75589a6a9b604e1b274659ac42e7c2/extensions/lib/hello-world/hello-world.web-view.tsx#L157)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

BTW the textfield isn't editable - is it meant to be?
</blockquote></details>

It is editable for me. Have you tried double-clicking? It seems the default behavior requires double clicking the cell to start editing
___
*[`lib/papi-components/src/table.component.tsx` line 97 at r1](https://reviewable.io/reviews/paranext/paranext-core/245#-NXvtTU5-va6BhOOYZWI:-NXyfxUHAsLazzPqt3NX:byv9mlb) ([raw file](https://github.com/paranext/paranext-core/blob/4f00e1676d75589a6a9b604e1b274659ac42e7c2/lib/papi-components/src/table.component.tsx#L97)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

Can you find a way to provide this as the default `renderEditCell` for each column? So like the default editor is always replaced with this. But then people can still overwrite `renderEditCell` with whatever they want, of course.

Then you won't have to provide it as the `renderEditCell` in all the places the table is used like in `hello-world.web-view.tsx`
</blockquote></details>

Unfortunately I don't think we can. I don't see a prop or whatever to do it.
The `DefaultColumnOptions` prop allows you to set a `renderCell`, but I'm quite sure that that is the renderer for the cell when it's NOT being edited.
___
*[`lib/papi-components/src/table.component.tsx` line 277 at r1](https://reviewable.io/reviews/paranext/paranext-core/245#-NXvtDd02p2zowshYb9A:-NXyi5kX9uuKiuSzeJmP:bb6un1j) ([raw file](https://github.com/paranext/paranext-core/blob/4f00e1676d75589a6a9b604e1b274659ac42e7c2/lib/papi-components/src/table.component.tsx#L277)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

Can this be moved out of the Table component similar to the TableTextEditor? If it is inside, it will create the function every time Table is rendered, whereas it appears not to have any dependencies inside the Table function. I could be missing something.
</blockquote></details>

Done

**Review by rolfheij-sil — COMMENTED** [review]
Thanks for reviewing!

> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/245#-:-NXykcbsAM4rqfauEeyn:b-yz40g0)* status: 12 of 15 files reviewed, 5 unresolved discussions (waiting on @irahopkinson and @tjcouch-sil)

**Review by irahopkinson — DISMISSED** [review]
:lgtm:

> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/245#-:-NY0MEpSAP-Rmbxbcts0:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @tjcouch-sil)

___
*[`extensions/lib/hello-world/hello-world.web-view.tsx` line 92 at r1](https://reviewable.io/reviews/paranext/paranext-core/245#-NXx92zm1gRVxJm7jET-:-NY0In0A98RuGlfyCp5H:b-6fbpej) ([raw file](https://github.com/paranext/paranext-core/blob/4f00e1676d75589a6a9b604e1b274659ac42e7c2/extensions/lib/hello-world/hello-world.web-view.tsx#L92)):*
<details><summary><i>Previously, rolfheij-sil wrote…</i></summary><blockquote>

I've just removed them entirely and put them as inlines in the Table's props
</blockquote></details>

Great, a better solution in this case.
___
*[`extensions/lib/hello-world/hello-world.web-view.tsx` line 157 at r1](https://reviewable.io/reviews/paranext/paranext-core/245#-NXxDv2X7TT6JMw2kVGR:-NY0Ks7nEikf6WE5ZliX:b-7uzz80) ([raw file](https://github.com/paranext/paranext-core/blob/4f00e1676d75589a6a9b604e1b274659ac42e7c2/extensions/lib/hello-world/hello-world.web-view.tsx#L157)):*
<details><summary><i>Previously, rolfheij-sil wrote…</i></summary><blockquote>

It is editable for me. Have you tried double-clicking? It seems the default behavior requires double clicking the cell to start editing
</blockquote></details>

Ah, I hadn't tried double-clicking (that I was aware of) but I also hadn't done `npm i` at the repo root. Now I can edit.

**Review by irahopkinson — APPROVED** [review]
:lgtm:

> Reviewed 19 of 19 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/245#-:-NYKqBfu4bxJ9gUAYlHW:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @rolfheij-sil)

___
*[`lib/papi-components/src/checkbox.component.tsx` line 70 at r3](https://reviewable.io/reviews/paranext/paranext-core/245#-NYKnVJ6Bl8TCo0-nQFL:-NYKnVJ6Bl8TCo0-nQFM:bxng3mz) ([raw file](https://github.com/paranext/paranext-core/blob/4f1964315b2636b14490646a9b2504889cc40b46/lib/papi-components/src/checkbox.component.tsx#L70)):*
> ```XML
>   labelPosition = LabelPosition.After,
>   isIndeterminate = false,
>   isDefaultChecked = false,
> ```

BTW I wonder why you removed the default here as it seems like a sensible default to me? We want to be able to have a stand-alone checkbox that isn't disabled without having to set this prop.

**Review by rolfheij-sil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/245)* status: all files reviewed, 1 unresolved discussion (waiting on @irahopkinson)

___
*[`extensions/lib/hello-world/hello-world.web-view.tsx` line 37 at r1](https://reviewable.io/reviews/paranext/paranext-core/245#-NXx7g5i1mIWnwrZtC_C:-NYOb7AP71IzaIxBe9M-:bokfnec) ([raw file](https://github.com/paranext/paranext-core/blob/4f00e1676d75589a6a9b604e1b274659ac42e7c2/extensions/lib/hello-world/hello-world.web-view.tsx#L37)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

This is a tricky one, but I think it needs a couple of adjustments. This is an object that will get recreated every render because it is in the function component. Let's change that:

1. You don't need this object to be created every render (it's just an initial value to set the state to), so let's move this object outside the component. However, now there's another problem. Every time you make a `hello-world.web-view` component now, it will use the same object. So all `hello-world.web-view` objects will share their `rows` state now. Soooo
2. You do actually want this to be a function that returns a unique object every time. That way, each time you create a `hello-world.web-view` component, the `rows` `useState` will run and create a new object for `rows`.

Hope this helps!
</blockquote></details>

Interesting! Done
___
*[`extensions/lib/hello-world/hello-world.web-view.tsx` line 50 at r1](https://reviewable.io/reviews/paranext/paranext-core/245#-NXx9wnk4eEQqMqGuIyl:-NYObDi85on0MzSnPMly:bb6un1j) ([raw file](https://github.com/paranext/paranext-core/blob/4f00e1676d75589a6a9b604e1b274659ac42e7c2/extensions/lib/hello-world/hello-world.web-view.tsx#L50)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

I think now `selectRows` starts with a verb, so it looks like a function. Can we change it to `selectedRows` and `setSelectedRows`?
</blockquote></details>

Done
___
*[`lib/papi-components/src/table.component.tsx` line 97 at r1](https://reviewable.io/reviews/paranext/paranext-core/245#-NXvtTU5-va6BhOOYZWI:-NYOdrA43sdhpnapk-hs:bgimlyj) ([raw file](https://github.com/paranext/paranext-core/blob/4f00e1676d75589a6a9b604e1b274659ac42e7c2/lib/papi-components/src/table.component.tsx#L97)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

I was basically saying do a map over the columns when you're making `cachedColumns` where you add this as the `renderEditCell`. However, I see that, unfortunately, [`renderEditCell` automatically sets the column as `editable` if it is provided unless it is explicitly set to false](https://github.com/adazzle/react-data-grid/blob/c29bf0cd6116584eee71c26c51acc4874c485b45/src/utils/selectedCellUtils.ts#L26). That throws a wrench in my plan...

Actually, I'm seeing now that further research indicates [there isn't a default `renderEditCell`](https://github.com/adazzle/react-data-grid/blob/c29bf0cd6116584eee71c26c51acc4874c485b45/src/EditCell.tsx#L148)... Sigh. Sorry I misunderstood. I think this is a confusing and difficult api (not your fault but adazzle's fault), but I'm gonna say this is fine then.

While we're at it, I will suggest some jsdoc tweaks to make this api a bit clearer.

(After making jsdoc suggestions) ugh, this api is not any clearer now that I have specified how it works in the comments. Can you double check me to make sure I'm right about what I'm saying? Basically `editable` does nothing unless `renderEditCell` is provided, and `editable` only does anything in that case if it is explicitly set to `false` (not a falsy value, but literally the boolean value `false`). I may suggest we split this text field stuff out to another issue if so because that api makes zero sense...

I would expect one of the following:

1. If you set a column (or certain cells in a column via making `editable` a function) as `editable: true`, those columns will be editable, and there is a default editor that is just a text editor. You can specify a `renderEditCell` to change how the editor renders.

2. If you set a column's `renderEditCell`, that column will be editable unless you make `disableEditing` truthy or a function that returns truthy for certain rows, which would make those particular cells not editable.

I think this api is very confusing with the names it has, and I think we should make an issue to change it. Would you mind making an issue if you agree? If you also agree with the changes I suggest, feel free to copy some or all of this comment into the new issue.

Since that issue would change public-facing api, it needs to be evaluated whether it should be an external extension ready issue. Maybe, maybe not.
</blockquote></details>

Agreed, the API is weird. I'll create an issue for it
___
*[`lib/papi-components/src/table.component.tsx` line 60 at r3](https://reviewable.io/reviews/paranext/paranext-core/245#-NYNzKwr-URs7S5lNaMJ:-NYObYNz2Cd4TXhuns_D:bon1htj) ([raw file](https://github.com/paranext/paranext-core/blob/538999a9032f257731d8fd55efa9d8809381a33d/lib/papi-components/src/table.component.tsx#L60)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

Let's change this line to mention that you must set `renderEditCell` in order for this to do anything. Something like:

Used to disable editing for a cell if `renderEditCell` is provided (meaning the column will be editable). Set this explicitly to `false` to turn off editing for this column, or provide a function that explicitly returns `false` for the rows you want not to be editable.
</blockquote></details>

Done. Thanks for writing this
___
*[`lib/papi-components/src/table.component.tsx` line 82 at r3](https://reviewable.io/reviews/paranext/paranext-core/245#-NYNyZDRAo-A_0FRYtHS:-NYObuJ_28Mku2AoW5uv:bb6un1j) ([raw file](https://github.com/paranext/paranext-core/blob/538999a9032f257731d8fd55efa9d8809381a33d/lib/papi-components/src/table.component.tsx#L82)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

Let's change this line to mention that you can set `editable` explicitly to `false` to keep rendering disabled. Something like:

If set, the column is automatically set to be editable unless the `editable` prop is explicitly set to `false`. If `editable` is a function, each row will be set to be editable unless the `editable` function explicitly returns `false` for that row.
</blockquote></details>

Done

**Review by irahopkinson — CHANGES_REQUESTED** [review]
> Reviewed 6 of 6 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/245)* status: all files reviewed, 1 unresolved discussion (waiting on @rolfheij-sil)

___
*[`lib/papi-components/src/checkbox.component.tsx` line 70 at r3](https://reviewable.io/reviews/paranext/paranext-core/245#-NYKnVJ6Bl8TCo0-nQFL:-NYPxPuj6CQEDh7JkBSW:b-xtgcr2) ([raw file](https://github.com/paranext/paranext-core/blob/4f1964315b2636b14490646a9b2504889cc40b46/lib/papi-components/src/checkbox.component.tsx#L70)):*
<details><summary><i>Previously, rolfheij-sil wrote…</i></summary><blockquote>

In the table component I hooked the `isChecked` prop of the checkbox up to the table, and I then got an error message in the console telling me to either use `isChecked` (for a controlled component) or `isDefaultChecked` (for an uncontrolled component).
I didn't touch`isDefaultChecked`anywhere else but here, so I figured setting a default value to `isDefaultChecked` was telling React that this component should be considered an uncontrolled one. And indeed on removing this default the error was resolved.
</blockquote></details>

Thanks, that makes sense.
___
*[`lib/papi-components/src/table.component.tsx` line 50 at r4](https://reviewable.io/reviews/paranext/paranext-core/245#-NYPxyZ9ClMjiv49fH2l:-NYPxyZAD8IN6wqs-8wW:b-9p2y5q) ([raw file](https://github.com/paranext/paranext-core/blob/f47cb41b63dac0c8ef95bddd01e6424a1058cb21/lib/papi-components/src/table.component.tsx#L50)):*
> ```XML
>    * based on grid width and specified widths of other columns
>    */
>   readonly width?: number | string | null;
> ```

Can we get rid of all the ` | null` on all the optional properties here and below? Optional properties already can be `undefined` and we prefer to use `undefined` and not allow `null`. (I think this code was already like this but it would be good to tidy this up.)

**Review by rolfheij-sil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/245)* status: all files reviewed, 1 unresolved discussion (waiting on @irahopkinson)

___
*[`lib/papi-components/src/table.component.tsx` line 50 at r4](https://reviewable.io/reviews/paranext/paranext-core/245#-NYPxyZ9ClMjiv49fH2l:-NYRwLtnDtHkfLWXWKa6:bpp50qi) ([raw file](https://github.com/paranext/paranext-core/blob/f47cb41b63dac0c8ef95bddd01e6424a1058cb21/lib/papi-components/src/table.component.tsx#L50)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

Can we get rid of all the ` | null` on all the optional properties here and below? Optional properties already can be `undefined` and we prefer to use `undefined` and not allow `null`. (I think this code was already like this but it would be good to tidy this up.)
</blockquote></details>

I can remove most of them, but not all of them, as that leads to incompatibility between our definition of Column (`TableColumn`) and `react-data-grid`s definition of `Column`

**Review by irahopkinson — APPROVED** [review]
:lgtm:

> Reviewed 5 of 5 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/245#-:-NYUH4Wl145J21SIpwEa:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @rolfheij-sil)

**Review by tjcouch-sil — COMMENTED** [review]
> Reviewed 1 of 3 files at r2, 1 of 6 files at r4, 5 of 5 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/245)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @rolfheij-sil)

**Review by rolfheij-sil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/245)* status: 13 of 25 files reviewed, 1 unresolved discussion (waiting on @irahopkinson and @tjcouch-sil)

___
*[`lib/papi-components/tsconfig.json` line 8 at r6](https://reviewable.io/reviews/paranext/paranext-core/245#-NYbBHIAEpd-Tn6PpcA5:-NYbBHIAEpd-Tn6PpcA6:bh856g1) ([raw file](https://github.com/paranext/paranext-core/blob/518471a97ab17a2e0f047d8b5dfc6264a3f36519/lib/papi-components/tsconfig.json#L8)):*
> ```jsonc
>     "target": "ESNext",
>     "module": "ESNext",
>     // "types": ["vite/client", "node", "react"],
> ```

I ran into trouble with this line when running `npm run build:papi-components`.
Any ideas?

**Review by tjcouch-sil — COMMENTED** [review]
> Reviewed 1 of 19 files at r3, 12 of 12 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/245)* status: all files reviewed, 1 unresolved discussion (waiting on @rolfheij-sil)

___
*[`lib/papi-components/tsconfig.json` line 8 at r6](https://reviewable.io/reviews/paranext/paranext-core/245#-NYbBHIAEpd-Tn6PpcA5:-NYe_BWV3kq8HxHBthEu:bepccez) ([raw file](https://github.com/paranext/paranext-core/blob/518471a97ab17a2e0f047d8b5dfc6264a3f36519/lib/papi-components/tsconfig.json#L8)):*
<details><summary><i>Previously, rolfheij-sil wrote…</i></summary><blockquote>

I ran into trouble with this line when running `npm run build:papi-components`.
Any ideas?
</blockquote></details>

None at first glance other than what's in Discord - `npm install` in `papi-components` folder. Any luck?

**Review by irahopkinson — CHANGES_REQUESTED** [review]
> Reviewed 12 of 12 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/245)* status: all files reviewed, 1 unresolved discussion (waiting on @rolfheij-sil and @tjcouch-sil)

___
*[`lib/papi-components/tsconfig.json` line 8 at r6](https://reviewable.io/reviews/paranext/paranext-core/245#-NYbBHIAEpd-Tn6PpcA5:-NYoH0pm3XH1jTVw0Jbq:bbjeiti) ([raw file](https://github.com/paranext/paranext-core/blob/518471a97ab17a2e0f047d8b5dfc6264a3f36519/lib/papi-components/tsconfig.json#L8)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

None at first glance other than what's in Discord - `npm install` in `papi-components` folder. Any luck?
</blockquote></details>

I just tried this on your branch after doing an `npm i` in the `papi-components` folder. With this line commented I get 158 errors when building. After removing the comment it builds fine.

**Review by rolfheij-sil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/245)* status: 20 of 25 files reviewed, 1 unresolved discussion (waiting on @irahopkinson and @tjcouch-sil)

___
*[`lib/papi-components/tsconfig.json` line 8 at r6](https://reviewable.io/reviews/paranext/paranext-core/245#-NYbBHIAEpd-Tn6PpcA5:-NYql6tiBw7tj8uKScIX:b-vtwouc) ([raw file](https://github.com/paranext/paranext-core/blob/518471a97ab17a2e0f047d8b5dfc6264a3f36519/lib/papi-components/tsconfig.json#L8)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

I just tried this on your branch after doing an `npm i` in the `papi-components` folder. With this line commented I get 158 errors when building. After removing the comment it builds fine.
</blockquote></details>

Interesting.. If I follow your instructions I can build `papi-components` just fine. But if I then perform an `npm i` in the root directory, I get the same errors that I got before when I try to run `npm run build:papi-components`.

**Review by rolfheij-sil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/245)* status: 20 of 25 files reviewed, 1 unresolved discussion (waiting on @irahopkinson and @tjcouch-sil)

___
*[`lib/papi-components/tsconfig.json` line 8 at r6](https://reviewable.io/reviews/paranext/paranext-core/245#-NYbBHIAEpd-Tn6PpcA5:-NYrFEgA5Fehk9eAwIdY:b8cj6yu) ([raw file](https://github.com/paranext/paranext-core/blob/518471a97ab17a2e0f047d8b5dfc6264a3f36519/lib/papi-components/tsconfig.json#L8)):*
<details><summary><i>Previously, rolfheij-sil wrote…</i></summary><blockquote>

Interesting.. If I follow your instructions I can build `papi-components` just fine. But if I then perform an `npm i` in the root directory, I get the same errors that I got before when I try to run `npm run build:papi-components`.
</blockquote></details>

Also interesting: After running `npm install` from the `papi-components` folder, Storybook doesn't work anymore. It reports 14 errors, all of which have this content: `TypeError
Cannot read properties of null (reading 'useContext')`
After running `npm install` from the root directory Storybook works as it should.

Any ideas? Maybe there is some inconsistency between the `package.json` configurations in the root directory and in the papi-components directory?

**Review by irahopkinson — APPROVED** [review]
:lgtm:

> Reviewed 5 of 5 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/245#-:-NYtt4bk1jdjDA1KzArc:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @rolfheij-sil)

___
*[`lib/papi-components/tsconfig.json` line 8 at r6](https://reviewable.io/reviews/paranext/paranext-core/245#-NYbBHIAEpd-Tn6PpcA5:-NYtraak7ESK6Jdt42zj:b-hlcjw) ([raw file](https://github.com/paranext/paranext-core/blob/518471a97ab17a2e0f047d8b5dfc6264a3f36519/lib/papi-components/tsconfig.json#L8)):*
<details><summary><i>Previously, rolfheij-sil wrote…</i></summary><blockquote>

Also interesting: After running `npm install` from the `papi-components` folder, Storybook doesn't work anymore. It reports 14 errors, all of which have this content: `TypeError
Cannot read properties of null (reading 'useContext')`
After running `npm install` from the root directory Storybook works as it should.

Any ideas? Maybe there is some inconsistency between the `package.json` configurations in the root directory and in the papi-components directory?
</blockquote></details>

Correct, you do have to run `npm i` in the `papi-components` before doing a build there. And because of the way its linked with a file link in the main `package.json` file (until we can make it it's own npm package) you will have to do an `npm i` there in the root after or just delete `lib\papi-components\node_modules\` folder.

**Review by irahopkinson — APPROVED** [review]
BTW because of timezone I would encourgae you to think about if enabling automerge in GH for your PRs might be a good idea.

> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/245#-:-NYtt7sR2rR11F0ixpKP:bmvrly6)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @rolfheij-sil)

**Comment by irahopkinson** [comment]
I elected to merge this for you so it doesn't need to go another round of merging in main when someones elses PR gets in before yours. Hope that is ok.

**Pull request merged**
