### PR TITLE
Reload extensions when they change

### PR DESCRIPTION
**Pull request by irahopkinson**
- Watch extension files and reload extensions (deactivate and reactivate) automaticaly when they change.
- Exclude these files from nodemon in development so watching is the same in dev and production.

- - -
This change is [Reviewable](https://reviewable.io/reviews/paranext/paranext-core/377)

### CODE REVIEW

**Review by rolfheij-sil — APPROVED** [review]
Looks good to me. One small typo in a comment.

> Reviewed 13 of 13 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/377#-:-NbsaoC18IBupRcZh9J3:b82dm71)* status: :shipit: complete! all files reviewed, all discussions resolved

___
*[`src/extension-host/services/extension.service.ts` line 435 at r1](https://reviewable.io/reviews/paranext/paranext-core/377#-Nbs_UXF0xRgaJeHhYWN:-Nbs_UXGC-8DvM_bgC3T:b9fek6d) ([raw file](https://github.com/paranext/paranext-core/blob/0ce572f2c87c673cdf835744e47a840aa62c9594/src/extension-host/services/extension.service.ts#L435)):*
> ```XML
>  * Deactivates an active extension.
>  * @param extensionName - name of the extension.
>  * @returns `true` if the extension deactivates, `false` if it at least one deactivation fails,
> ```

Remove the word `it`

**Review by tjcouch-sil — COMMENTED** [review]
Thanks for the great work on this!! Just a couple things to mention.

> Reviewed 13 of 13 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/377#-:-NbuFiAsCtogEcpnOyBy:b-y6r9a8)* status: all files reviewed, 5 unresolved discussions (waiting on @irahopkinson)

___
*[`src/extension-host/services/extension.service.ts` line 314 at r1](https://reviewable.io/reviews/paranext/paranext-core/377#-NbuGSBW2QvyZyLgFvk_:-NbuGSBW2QvyZyLgFvka:brf4glm) ([raw file](https://github.com/paranext/paranext-core/blob/0ce572f2c87c673cdf835744e47a840aa62c9594/src/extension-host/services/extension.service.ts#L314)):*
> ```XML
>   // bundle and should not be looked up in the bundle
>   // DO NOT REMOVE THE webpackIgnore COMMENT. It is a webpack "Magic Comment" https://webpack.js.org/api/module-methods/#magic-comments
>   const extensionModuleAmbiguous = systemRequire(
> ```

Do we have an issue logged yet on creating our own loader? If not, would you mind making one please?
___
*[`src/extension-host/services/extension.service.ts` line 439 at r1](https://reviewable.io/reviews/paranext/paranext-core/377#-NbuDo134-BO1K2o7PTC:-NbuDo134-BO1K2o7PTD:b-8d0u3l) ([raw file](https://github.com/paranext/paranext-core/blob/0ce572f2c87c673cdf835744e47a840aa62c9594/src/extension-host/services/extension.service.ts#L439)):*
> ```XML
>  */
> async function deactivateExtension(extension: ExtensionInfo): Promise<boolean | undefined> {
>   const isUnsubscribed = await activeExtensions
> ```

I found it extremely difficult to understand what was going wrong when I didn't have all those `logger.error` lines in here. I couldn't tell which extension was not deactivating properly if any of its unsubscribers simply returned false instead of throwing. Or in one case it wasn't even running the unsubscribers, which confused me even more. I'd like to request that you add in at least quite a few of those error logs I had in my branch (I'd prefer to keep even the one inside `runAllUnsubscribers` so you know which is failing. Shouldn't happen often, but it is very helpful when it does happen). Otherwise, it is very difficult to tell what's going wrong when something goes wrong.
___
*[`src/extension-host/services/extension.service.ts` line 445 at r1](https://reviewable.io/reviews/paranext/paranext-core/377#-NbuFpFK6v2qyiM9RD9T:-NbuFpFK6v2qyiM9RD9U:b-xwujgk) ([raw file](https://github.com/paranext/paranext-core/blob/0ce572f2c87c673cdf835744e47a840aa62c9594/src/extension-host/services/extension.service.ts#L445)):*
> ```XML
>   // Delete the extension module from Node's module cache if we previously loaded it.
>   const moduleKey = systemRequire.resolve(getPathFromUri(extension.dirUri));
>   if (moduleKey in systemRequire.cache) delete systemRequire.cache[moduleKey];
> ```

I think I might consider not finding the module in the cache might be concerning enough to log an error and return false here... I dunno; seems like it may be a concerning enough issue to me to warrant considering it to have failed to deactivate. Thoughts?
___
*[`src/extension-host/services/extension.service.ts` line 458 at r1](https://reviewable.io/reviews/paranext/paranext-core/377#-NbuGAn04XwcRDRjVhat:-NbuGAn04XwcRDRjVhau:b3h15bz) ([raw file](https://github.com/paranext/paranext-core/blob/0ce572f2c87c673cdf835744e47a840aa62c9594/src/extension-host/services/extension.service.ts#L458)):*
> ```XML
>   return Promise.all(
>     extensions.map((extension) =>
>       deactivateExtension(extension).catch((e) => {
> ```

Please use `async/await` notation.
___
*[`src/extension-host/services/extension.service.ts` line 459 at r1](https://reviewable.io/reviews/paranext/paranext-core/377#-NbuGEgs4_GPze_DCVFg:-NbuGEgs4_GPze_DCVFh:b-fm6ijk) ([raw file](https://github.com/paranext/paranext-core/blob/0ce572f2c87c673cdf835744e47a840aa62c9594/src/extension-host/services/extension.service.ts#L459)):*
> ```XML
>     extensions.map((extension) =>
>       deactivateExtension(extension).catch((e) => {
>         logger.error(`Extension '${extension.name}' threw while deactivating! ${e}`);
> ```

Can we `await deactivateExtension` and log an error if it fails to deactivate (returns false)?

**Comment by irahopkinson** [comment]
*[`src/extension-host/services/extension.service.ts` line 314 at r1](https://reviewable.io/reviews/paranext/paranext-core/377#-NbuGSBW2QvyZyLgFvk_:-NbwTOH3C8duNskMTpe3:buvgzop) ([raw file](https://github.com/paranext/paranext-core/blob/0ce572f2c87c673cdf835744e47a840aa62c9594/src/extension-host/services/extension.service.ts#L314)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

Do we have an issue logged yet on creating our own loader? If not, would you mind making one please?
</blockquote></details>

Done. See https://github.com/paranext/paranext-core/issues/381.

**Comment by irahopkinson** [comment]
*[`src/extension-host/services/extension.service.ts` line 435 at r1](https://reviewable.io/reviews/paranext/paranext-core/377#-Nbs_UXF0xRgaJeHhYWN:-NbwamK-4Sj9sr1HvAjG:b4j22fg) ([raw file](https://github.com/paranext/paranext-core/blob/0ce572f2c87c673cdf835744e47a840aa62c9594/src/extension-host/services/extension.service.ts#L435)):*
<details><summary><i>Previously, rolfheij-sil wrote…</i></summary><blockquote>

Remove the word `it`
</blockquote></details>

Done. See new PR #382.

**Comment by irahopkinson** [comment]
*[`src/extension-host/services/extension.service.ts` line 439 at r1](https://reviewable.io/reviews/paranext/paranext-core/377#-NbuDo134-BO1K2o7PTC:-NbwVDYd4pcp1kQPtFFK:b-u7bge3) ([raw file](https://github.com/paranext/paranext-core/blob/0ce572f2c87c673cdf835744e47a840aa62c9594/src/extension-host/services/extension.service.ts#L439)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

I found it extremely difficult to understand what was going wrong when I didn't have all those `logger.error` lines in here. I couldn't tell which extension was not deactivating properly if any of its unsubscribers simply returned false instead of throwing. Or in one case it wasn't even running the unsubscribers, which confused me even more. I'd like to request that you add in at least quite a few of those error logs I had in my branch (I'd prefer to keep even the one inside `runAllUnsubscribers` so you know which is failing. Shouldn't happen often, but it is very helpful when it does happen). Otherwise, it is very difficult to tell what's going wrong when something goes wrong.
</blockquote></details>

There could be reasons to log errors but I'm not sure I agree for the reasons you have given. I found it very easy to see what wasn't working and why when I ran the debugger and inspected what was happening (and now we can debug in production as well).  I don't consider logs the first best tool when debugging. Also not activated and/or not registered don't seem like an error to me if you attempt to deactivate an extension it jsut means there is nothing to do. However, I'm happy to hear your thoughts on principles for when to add logs to code? Perhaps continue this in the new PR #382?

**Comment by irahopkinson** [comment]
*[`src/extension-host/services/extension.service.ts` line 445 at r1](https://reviewable.io/reviews/paranext/paranext-core/377#-NbuFpFK6v2qyiM9RD9T:-NbwWlf76X-VTTCAyBiG:b-20ke8u) ([raw file](https://github.com/paranext/paranext-core/blob/0ce572f2c87c673cdf835744e47a840aa62c9594/src/extension-host/services/extension.service.ts#L445)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

I think I might consider not finding the module in the cache might be concerning enough to log an error and return false here... I dunno; seems like it may be a concerning enough issue to me to warrant considering it to have failed to deactivate. Thoughts?
</blockquote></details>

I did originally have code here that threw while I was figuring things out. However, I went to this because I considered the case that it can be triggered to reload before an extension is activated and therefore it might not yet be in the module cache. Also I'm not convinced that if it's not in the cache yet that it really is an error. I think an error might be overkill here but I could be convinced to log a warning? Perhaps continue this in the new PR #382?

**Comment by irahopkinson** [comment]
*[`src/extension-host/services/extension.service.ts` line 458 at r1](https://reviewable.io/reviews/paranext/paranext-core/377#-NbuGAn04XwcRDRjVhat:-NbwZKnl1ZVDJ6LNxlo8:b6n3gab) ([raw file](https://github.com/paranext/paranext-core/blob/0ce572f2c87c673cdf835744e47a840aa62c9594/src/extension-host/services/extension.service.ts#L458)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

Please use `async/await` notation.
</blockquote></details>

Done. Sorry, just copied the `activateExtensions` code without thinking about code style. See new PR #382.

**Comment by irahopkinson** [comment]
*[`src/extension-host/services/extension.service.ts` line 459 at r1](https://reviewable.io/reviews/paranext/paranext-core/377#-NbuGEgs4_GPze_DCVFg:-NbwaOqSBwi-X0W6ts--:b4j22fg) ([raw file](https://github.com/paranext/paranext-core/blob/0ce572f2c87c673cdf835744e47a840aa62c9594/src/extension-host/services/extension.service.ts#L459)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

Can we `await deactivateExtension` and log an error if it fails to deactivate (returns false)?
</blockquote></details>

Done. See new PR #382.

**Pull request merged**
