### PR TITLE
Update styling for input and label component

### PR DESCRIPTION
**Pull request by rolfheij-sil**
This change is [Reviewable](https://reviewable.io/reviews/paranext/paranext-core/1146)

### CODE REVIEW

**Review by jolierabideau — CHANGES_REQUESTED** [review]
Thanks for your work on this!

> Reviewed 19 of 19 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/1146#-:-O7ZeLwl3S2D-XRwRUSn:b7tt6lp)* status: all files reviewed, 1 unresolved discussion (waiting on @rolfheij-sil)

___
*[`lib/platform-bible-react/src/components/shadcn-ui/input.tsx` line 12 at r1](https://reviewable.io/reviews/paranext/paranext-core/1146#-O7ZctS61MdU0LCYu-D4:-O7ZctS76HM3QgnPsylF:b-gi6254) ([raw file](https://github.com/paranext/paranext-core/blob/37cd643f8d9c6103e31d0b3ac1cf1aad1184ef93/lib/platform-bible-react/src/components/shadcn-ui/input.tsx#L12)):*
> ```XML
>         type={type}
>         className={cn(
>           'pr-twp pr-flex pr-rounded-md pr-bg-background pr-px-3 pr-py-2 pr-font-sans pr-text-sm pr-ring-offset-background file:pr-border-0 file:pr-bg-transparent file:pr-text-sm file:pr-font-medium placeholder:pr-text-muted-foreground disabled:pr-cursor-not-allowed disabled:pr-opacity-50',
> ```

Curious why you had to add `pr-font-sans`? In the `index.css` file I added a section that applies `pr-font-sans` when you use `pr-twp` so it should be included. Goes for all the components :)

**Review by rolfheij-sil — COMMENTED** [review]
Thanks for reviewing!

> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/1146#-:-O7_o_lJ7DA6X79I-szc:b-yz40g0)* status: all files reviewed, 1 unresolved discussion (waiting on @jolierabideau)

___
*[`lib/platform-bible-react/src/components/shadcn-ui/input.tsx` line 12 at r1](https://reviewable.io/reviews/paranext/paranext-core/1146#-O7ZctS61MdU0LCYu-D4:-O7_ob4F3k5cyoWnEd_i:beasvzu) ([raw file](https://github.com/paranext/paranext-core/blob/37cd643f8d9c6103e31d0b3ac1cf1aad1184ef93/lib/platform-bible-react/src/components/shadcn-ui/input.tsx#L12)):*
<details><summary><i>Previously, jolierabideau wrote…</i></summary><blockquote>

Curious why you had to add `pr-font-sans`? In the `index.css` file I added a section that applies `pr-font-sans` when you use `pr-twp` so it should be included. Goes for all the components :)
</blockquote></details>

Nice. I wasn't aware of this. I have removed all occurrences of `pr-font-sans` that were redundant. I've pushed them to #1151 though, as I've been updating styles there too. Is that okay?

**Review by jolierabideau — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/1146)* status: all files reviewed, 1 unresolved discussion (waiting on @rolfheij-sil)

___
*[`lib/platform-bible-react/src/components/shadcn-ui/input.tsx` line 12 at r1](https://reviewable.io/reviews/paranext/paranext-core/1146#-O7ZctS61MdU0LCYu-D4:-O7dDHuJ2XxnP3RJM7av:b-5r9ez8) ([raw file](https://github.com/paranext/paranext-core/blob/37cd643f8d9c6103e31d0b3ac1cf1aad1184ef93/lib/platform-bible-react/src/components/shadcn-ui/input.tsx#L12)):*
<details><summary><i>Previously, rolfheij-sil (Rolf Heij) wrote…</i></summary><blockquote>

Nice. I wasn't aware of this. I have removed all occurrences of `pr-font-sans` that were redundant. I've pushed them to #1151 though, as I've been updating styles there too. Is that okay?
</blockquote></details>

Ohhh you removed them in #1151 instead of in this PR? That works for me

**Review by rolfheij-sil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/1146)* status: all files reviewed, 1 unresolved discussion (waiting on @jolierabideau)

___
*[`lib/platform-bible-react/src/components/shadcn-ui/input.tsx` line 12 at r1](https://reviewable.io/reviews/paranext/paranext-core/1146#-O7ZctS61MdU0LCYu-D4:-O7dIMH9DnBwNm7mNG0j:bb77uci) ([raw file](https://github.com/paranext/paranext-core/blob/37cd643f8d9c6103e31d0b3ac1cf1aad1184ef93/lib/platform-bible-react/src/components/shadcn-ui/input.tsx#L12)):*
<details><summary><i>Previously, jolierabideau wrote…</i></summary><blockquote>

Ohhh you removed them in #1151 instead of in this PR? That works for me
</blockquote></details>

Yep!

**Review by tjcouch-sil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/1146)* status: all files reviewed, 2 unresolved discussions (waiting on @jolierabideau and @rolfheij-sil)

___
*[`lib/platform-bible-react/src/components/shadcn-ui/input.tsx` line 12 at r1](https://reviewable.io/reviews/paranext/paranext-core/1146#-O7eiZXL1zNgBq9x21RZ:-O7eiZXL1zNgBq9x21R_:b-e97lmi) ([raw file](https://github.com/paranext/paranext-core/blob/b6e8fb1e6182a6f12142fe1f9d1735f67852e8e4/lib/platform-bible-react/src/components/shadcn-ui/input.tsx#L12)):*
> ```XML
>         type={type}
>         className={cn(
>           'pr-flex pr-h-10 pr-rounded-md pr-bg-background pr-px-3 pr-py-2 pr-text-sm pr-ring-offset-background file:pr-border-0 file:pr-bg-transparent file:pr-text-sm file:pr-font-medium placeholder:pr-text-muted-foreground disabled:pr-cursor-not-allowed disabled:pr-opacity-50',
> ```

What is the consequence of removing `pr-h-10` and why remove it? Did UX suggest/confirm this change? I could see a scenario where UX builds something in Figma not realizing that we changed it here, so they look different in the end. Not that this is likely some big difference, but it led me to think about this possibility.

I kinda wonder if we should comment explaining what we did and why when we make changes to styles inside of shadcn components... Probably would make it easier to notice what changes we made and how to merge properly if we ever pull in updates from shadcn...

**Comment by rolfheij-sil** [comment]
Removing it makes sure that the height of the input if no longer fixed. Because of the `pr-h-10`, the input component would be sized differently then all other shadcn components that we use, giving it a very different look and feel. I didn't discuss this with UX, and the `pr-h-10` seems to be part of the shadcn sources (it wasn't put there by us), so leaving a comment might be a good idea. What do you think?

**Pull request merged**
