### PR TITLE
Word List - Initial implementation

### PR DESCRIPTION
**Pull request by rolfheij-sil**
There's still stuff that I want to improve on, but (mabye?) it looks good enough to demo

image

- - -
This change is [Reviewable](https://reviewable.io/reviews/paranext/paranext-core/591)

### CODE REVIEW

**Review by rolfheij-sil — COMMENTED** [review]
Improvements:
- Get full chapter instead of fetching verses one at a time
- Use useProjectData to get text
- Refactor into standalone extension
- Maybe more

> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/591#-:-NhXZmtd5BQzKEx-Lqot:ba3xnau)* status: 0 of 7 files reviewed, all discussions resolved

**Review by tjcouch-sil — COMMENTED** [review]
Yay!

> Reviewed 7 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/591#-:-NhXcvsg6gfueki0Huc6:bb77rlh)* status: :shipit: complete! all files reviewed, all discussions resolved

**Comment by Sebastian-ubs** [comment]
if you can easily do formatting, using bold text looks better than uppercase

**Comment by rolfheij-sil** [comment]
> if you can easily do formatting, using bold text looks better than uppercase

Agreed, but formatting isn't easy unfortunately. I think it is possible, but it will take some time to figure it out and extent our wrapper to support it

**Comment by ianhewubs** [comment]
If it's possible to add some whitespace below the BCV controls and the upper pane, that would be useful. It helps prevent the user clicking one thing when they were aiming for something else (useful not to do in a demo!)

I'd also be tempted to get the words from the whole book or whole project. There's a stronger use case for that (what does this word look like in other contexts) than for current verse or chapter. Plus it means you end up showing more data. 

I imagine it is beyond current scope to be thinking about providing a control to filter to chapter, verse, book, or project like in PT9. The filter is generally more important than the BCV control in this tool.

**Review by tjcouch-sil — COMMENTED** [review]
Word list per project and per book would be nice :) but we don't currently have a way exposed to get the available books in a project, so it would probably be good to file an issue to make this improvement.

> Reviewed 7 of 7 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/591#-:-NhgUPeJ7Me1pYNPlsu8:b-ab7cei)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request closed without merging**
