### PR TITLE
Allow relative paths for `--extensions`

### PR DESCRIPTION
**Pull request by irahopkinson**
- also misc cleanup

To test in development, add ` --extensions ../paranext-extension-template/dist` (or similar) to the end of the **start:main** script in `package.json`. Otherwise build the app (`npm run package`) and test with that.

- - -
This change is [Reviewable](https://reviewable.io/reviews/paranext/paranext-core/355)

### CODE REVIEW

**Review by lyonsil — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/355)* status: all files reviewed, 5 unresolved discussions (waiting on @irahopkinson)

___
*[`src/extension-host/services/extension.service.ts` line 108 at r1](https://reviewable.io/reviews/paranext/paranext-core/355#-NboEi2E8ErOcFsyx9fA:-NboEi2E8ErOcFsyx9fB:bfywhaq) ([raw file](https://github.com/paranext/paranext-core/blob/084e89c18e731682e1cbda3f9fda1acc0e7ec713/src/extension-host/services/extension.service.ts#L108)):*
> ```XML
>  *  This is expected to be a mixture of directories and ZIP files.
>  */
> async function extensionRootDirectoryContents() {
> ```

This was storing the promise instead of being a function so that it didn't need to be (and probably shouldn't be) evaluated multiple times.  Ideally this would have just stored the strings without a promise, but you can't `await` in main outside of a function.

If we really want to convert this to a function, I think it would be good to make the function name a verb, like `getExtensionDirectoryContents()`.  I know we haven't followed that strictly, but it's nice.
___
*[`src/extension-host/services/extension.service.ts` line 120 at r1](https://reviewable.io/reviews/paranext/paranext-core/355#-NboEy2Q4DMRvU-BhQE-:-NboEy2Q4DMRvU-BhQE0:b6py3zn) ([raw file](https://github.com/paranext/paranext-core/blob/084e89c18e731682e1cbda3f9fda1acc0e7ec713/src/extension-host/services/extension.service.ts#L120)):*
> ```XML
> 
> /** All of the URIs of ZIP files for extensions we want to load */
> async function extensionZipUris(): Promise<Uri[]> {
> ```

This was storing the promise instead of being a function so that it didn't need to be (and probably shouldn't be) evaluated multiple times.  Ideally this would have just stored the strings without a promise, but you can't `await` in main outside of a function.

If we really want to convert this to a function, I think it would be good to make the function name a verb, like `getExtensionZipUris()`.  I know we haven't followed that strictly, but it's nice.
___
*[`src/extension-host/services/extension.service.ts` line 133 at r1](https://reviewable.io/reviews/paranext/paranext-core/355#-NboFX2n3MFbU4lqUPZh:-NboFX2n3MFbU4lqUPZi:bom9dxl) ([raw file](https://github.com/paranext/paranext-core/blob/084e89c18e731682e1cbda3f9fda1acc0e7ec713/src/extension-host/services/extension.service.ts#L133)):*
> ```XML
> 
> /** All of the URIs of extensions to load */
> async function extensionUrisToLoad(): Promise<Uri[]> {
> ```

This is only called once unlike the previous two, so it isn't as big of a deal to convert.  Having said that, it's nice (I think) to keep it parallel with the previous items since they all essentially hold static data once the extension host is started.

If we really want to convert this to a function, I think it would be good to make the function name a verb, like `getExtensionUrisToLoad()`.  I know we haven't followed that strictly, but it's nice.
___
*[`src/extension-host/services/extension.service.ts` line 228 at r1](https://reviewable.io/reviews/paranext/paranext-core/355#-NboFgDWE7KCGGpROxic:-NboFgDX6Oxb6SzjiRWs:brkse8r) ([raw file](https://github.com/paranext/paranext-core/blob/084e89c18e731682e1cbda3f9fda1acc0e7ec713/src/extension-host/services/extension.service.ts#L228)):*
> ```XML
>  */
> // TODO: figure out if we can share this code with webpack.util.ts
> async function getExtensions(): Promise<ExtensionInfo[]> {
> ```

This was storing the promise instead of being a function so that it didn't need to be evaluated multiple times.  Ideally this would have just stored the strings without a promise, but you can't `await` in main outside of a function.
___
*[`src/extension-host/services/extension.service.ts` line 330 at r1](https://reviewable.io/reviews/paranext/paranext-core/355#-NboJ9MpEIcXFdy42HSr:-NboJ9MpEIcXFdy42HSs:b-ik29yz) ([raw file](https://github.com/paranext/paranext-core/blob/084e89c18e731682e1cbda3f9fda1acc0e7ec713/src/extension-host/services/extension.service.ts#L330)):*
> ```XML
>  * @returns unsubscriber that deactivates the extension
>  */
> async function activateExtensions(extensions: ExtensionInfo[]): Promise<ActiveExtension[]> {
> ```

I know @tjcouch-sil has used the pattern of storing a promise to the results to make sure functions don't accidentally get run multiple times.  Is there a reason we might run this multiple times?  If not, why make this change?

**Review by tjcouch-sil — CHANGES_REQUESTED** [review]
This looks like a good improvement! Thanks!

> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/355#-:-NboKonyAWnT1PcjE73Y:bdsh44n)* status: all files reviewed, 6 unresolved discussions (waiting on @irahopkinson and @lyonsil)

___
*[`src/extension-host/services/extension.service.ts` line 113 at r1](https://reviewable.io/reviews/paranext/paranext-core/355#-NboKWAkEhf1-wPuVYxl:-NboKWAkEhf1-wPuVYxm:b-bjpfps) ([raw file](https://github.com/paranext/paranext-core/blob/084e89c18e731682e1cbda3f9fda1acc0e7ec713/src/extension-host/services/extension.service.ts#L113)):*
> ```XML
>       `resources://extensions${globalThis.isPackaged ? '' : '/dist'}`,
>       ...getCommandLineArgumentsGroup(ARG_EXTENSION_DIRS).map(
>         (extensionDirPath) => `file://${path.resolve(extensionDirPath)}`,
> ```

I often have trouble finding where the cwd is in these kinds of situations without documentation. Could you please explain what the working directory is in development and in production (maybe in the Readme)?
___
*[`src/extension-host/services/extension.service.ts` line 228 at r1](https://reviewable.io/reviews/paranext/paranext-core/355#-NboFgDWE7KCGGpROxic:-NboL2lFCsB18Xo2TtH8:bwzpsyd) ([raw file](https://github.com/paranext/paranext-core/blob/084e89c18e731682e1cbda3f9fda1acc0e7ec713/src/extension-host/services/extension.service.ts#L228)):*
<details><summary><i>Previously, lyonsil (Matt Lyons) wrote…</i></summary><blockquote>

This was storing the promise instead of being a function so that it didn't need to be evaluated multiple times.  Ideally this would have just stored the strings without a promise, but you can't `await` in main outside of a function.
</blockquote></details>

In this case, it looks to me like Ira just changed it from an arrow function stored in a const to an actual function, which just affects whether it forms a JavaScript "closure". In this case, the closure isn't relevant since this function doesn't use `this`. I think this is functionally equivalent to what was here before.
___
*[`src/extension-host/services/extension.service.ts` line 330 at r1](https://reviewable.io/reviews/paranext/paranext-core/355#-NboJ9MpEIcXFdy42HSr:-NboLubC2EvplVVuaFYo:b-l3eco5) ([raw file](https://github.com/paranext/paranext-core/blob/084e89c18e731682e1cbda3f9fda1acc0e7ec713/src/extension-host/services/extension.service.ts#L330)):*
<details><summary><i>Previously, lyonsil (Matt Lyons) wrote…</i></summary><blockquote>

I know @tjcouch-sil has used the pattern of storing a promise to the results to make sure functions don't accidentally get run multiple times.  Is there a reason we might run this multiple times?  If not, why make this change?
</blockquote></details>

I think the pattern of making sure a function doesn't get run multiple times is less for the sake of "accidental" runs and more for either "this function is deterministic, so I only need to calculate the output once and just keep returning it" or "I want to be able to call this function a bunch just to ensure it has been run once before I run some other code". I would say neither of these is the case in this situation, so it feels like an unnecessary optimization.

Also, I believe Ira is nearing the end of a rework in which this function will be run multiple times on purpose :)

**Review by lyonsil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/355)* status: all files reviewed, 5 unresolved discussions (waiting on @irahopkinson and @tjcouch-sil)

___
*[`src/extension-host/services/extension.service.ts` line 228 at r1](https://reviewable.io/reviews/paranext/paranext-core/355#-NboFgDWE7KCGGpROxic:-NboR4ZwBbhFO5pKkBJV:b-2bl500) ([raw file](https://github.com/paranext/paranext-core/blob/084e89c18e731682e1cbda3f9fda1acc0e7ec713/src/extension-host/services/extension.service.ts#L228)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

In this case, it looks to me like Ira just changed it from an arrow function stored in a const to an actual function, which just affects whether it forms a JavaScript "closure". In this case, the closure isn't relevant since this function doesn't use `this`. I think this is functionally equivalent to what was here before.
</blockquote></details>

That is the only kind of change made to the two blocked cases I mentioned above.  `getExtensions()` is only run once anyway so it isn't a big deal to make this change, but if it was run run multiple times this change would cause this code to get run multiple times.

**Review by tjcouch-sil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/355)* status: all files reviewed, 5 unresolved discussions (waiting on @irahopkinson and @lyonsil)

___
*[`src/extension-host/services/extension.service.ts` line 228 at r1](https://reviewable.io/reviews/paranext/paranext-core/355#-NboFgDWE7KCGGpROxic:-NbobQ8RDN2z4blQBmWf:bxj5sez) ([raw file](https://github.com/paranext/paranext-core/blob/084e89c18e731682e1cbda3f9fda1acc0e7ec713/src/extension-host/services/extension.service.ts#L228)):*
<details><summary><i>Previously, lyonsil (Matt Lyons) wrote…</i></summary><blockquote>

That is the only kind of change made to the two blocked cases I mentioned above.  `getExtensions()` is only run once anyway so it isn't a big deal to make this change, but if it was run run multiple times this change would cause this code to get run multiple times.
</blockquote></details>

In all three cases you mentioned above this one, the variable was being assigned to the return of an [IIFE](https://developer.mozilla.org/en-US/docs/Glossary/IIFE). Those variables were not functions; they were evaluated values (promises in this case, but that doesn't really matter for the point), and you named them nouns as they appropriately should be. You couldn't run them as functions before, but now he has added `()` because he changed them to functions. You even aptly noted that they should now be verbs because they are now functions.

In this case with `getExtensions` (not in the others), the variable was previously being assigned to an in-line function, not an IIFE, so it was still a function that you need to execute with `()`. It was already named a verb before because it was a function before (and is properly named now because it still is a function). Notice that the use of `getExtensions` in the `initialize` function did not change in this PR whereas the use did change for the other three const IIFE return values that were turned into functions in this PR.

**Review by lyonsil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/355)* status: all files reviewed, 4 unresolved discussions (waiting on @irahopkinson)

___
*[`src/extension-host/services/extension.service.ts` line 228 at r1](https://reviewable.io/reviews/paranext/paranext-core/355#-NboFgDWE7KCGGpROxic:-Nbp_eMZ5WW5en3_sglx:b1xzohp) ([raw file](https://github.com/paranext/paranext-core/blob/084e89c18e731682e1cbda3f9fda1acc0e7ec713/src/extension-host/services/extension.service.ts#L228)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

In all three cases you mentioned above this one, the variable was being assigned to the return of an [IIFE](https://developer.mozilla.org/en-US/docs/Glossary/IIFE). Those variables were not functions; they were evaluated values (promises in this case, but that doesn't really matter for the point), and you named them nouns as they appropriately should be. You couldn't run them as functions before, but now he has added `()` because he changed them to functions. You even aptly noted that they should now be verbs because they are now functions.

In this case with `getExtensions` (not in the others), the variable was previously being assigned to an in-line function, not an IIFE, so it was still a function that you need to execute with `()`. It was already named a verb before because it was a function before (and is properly named now because it still is a function). Notice that the use of `getExtensions` in the `initialize` function did not change in this PR whereas the use did change for the other three const IIFE return values that were turned into functions in this PR.
</blockquote></details>

I never knew that `IIFE` was a formally defined thing.  Thanks for the pointer!

**Review by tjcouch-sil — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/355)* status: all files reviewed, 4 unresolved discussions (waiting on @irahopkinson)

**Review by irahopkinson — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/355)* status: all files reviewed, 3 unresolved discussions (waiting on @lyonsil and @tjcouch-sil)

___
*[`src/extension-host/services/extension.service.ts` line 108 at r1](https://reviewable.io/reviews/paranext/paranext-core/355#-NboEi2E8ErOcFsyx9fA:-Nbpys1K2_Tqgu51SeCw:b-ged95g) ([raw file](https://github.com/paranext/paranext-core/blob/084e89c18e731682e1cbda3f9fda1acc0e7ec713/src/extension-host/services/extension.service.ts#L108)):*
<details><summary><i>Previously, lyonsil (Matt Lyons) wrote…</i></summary><blockquote>

This was storing the promise instead of being a function so that it didn't need to be (and probably shouldn't be) evaluated multiple times.  Ideally this would have just stored the strings without a promise, but you can't `await` in main outside of a function.

If we really want to convert this to a function, I think it would be good to make the function name a verb, like `getExtensionDirectoryContents()`.  I know we haven't followed that strictly, but it's nice.
</blockquote></details>

Probably over-zealous refactoring here. I'll make the changes later if they are really needed. Reverted.
___
*[`src/extension-host/services/extension.service.ts` line 113 at r1](https://reviewable.io/reviews/paranext/paranext-core/355#-NboKWAkEhf1-wPuVYxl:-Nbpz8yN4cHjXNKJ8EgZ:bzhfzj) ([raw file](https://github.com/paranext/paranext-core/blob/084e89c18e731682e1cbda3f9fda1acc0e7ec713/src/extension-host/services/extension.service.ts#L113)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

I often have trouble finding where the cwd is in these kinds of situations without documentation. Could you please explain what the working directory is in development and in production (maybe in the Readme)?
</blockquote></details>

The README doesn't talk about command-line switches at all. I was going to make the necessary changes to our wiki where it talks about this switch once this PR is merged.
___
*[`src/extension-host/services/extension.service.ts` line 120 at r1](https://reviewable.io/reviews/paranext/paranext-core/355#-NboEy2Q4DMRvU-BhQE-:-Nbpz4oEBD8Hm1VST-ct:b-ged95g) ([raw file](https://github.com/paranext/paranext-core/blob/084e89c18e731682e1cbda3f9fda1acc0e7ec713/src/extension-host/services/extension.service.ts#L120)):*
<details><summary><i>Previously, lyonsil (Matt Lyons) wrote…</i></summary><blockquote>

This was storing the promise instead of being a function so that it didn't need to be (and probably shouldn't be) evaluated multiple times.  Ideally this would have just stored the strings without a promise, but you can't `await` in main outside of a function.

If we really want to convert this to a function, I think it would be good to make the function name a verb, like `getExtensionZipUris()`.  I know we haven't followed that strictly, but it's nice.
</blockquote></details>

Probably over-zealous refactoring here. I'll make the changes later if they are really needed. Reverted.
___
*[`src/extension-host/services/extension.service.ts` line 133 at r1](https://reviewable.io/reviews/paranext/paranext-core/355#-NboFX2n3MFbU4lqUPZh:-Nbpz6JP1tWVGCkNt18T:b-ged95g) ([raw file](https://github.com/paranext/paranext-core/blob/084e89c18e731682e1cbda3f9fda1acc0e7ec713/src/extension-host/services/extension.service.ts#L133)):*
<details><summary><i>Previously, lyonsil (Matt Lyons) wrote…</i></summary><blockquote>

This is only called once unlike the previous two, so it isn't as big of a deal to convert.  Having said that, it's nice (I think) to keep it parallel with the previous items since they all essentially hold static data once the extension host is started.

If we really want to convert this to a function, I think it would be good to make the function name a verb, like `getExtensionUrisToLoad()`.  I know we haven't followed that strictly, but it's nice.
</blockquote></details>

Probably over-zealous refactoring here. I'll make the changes later if they are really needed. Reverted.

**Review by tjcouch-sil — APPROVED** [review]
:lgtm: Thanks for the cleanup!

> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/355#-:-NbpzpVO1PB2V2Vxpu2l:b9drxe3)* status: all files reviewed, 2 unresolved discussions (waiting on @lyonsil)

___
*[`src/extension-host/services/extension.service.ts` line 113 at r1](https://reviewable.io/reviews/paranext/paranext-core/355#-NboKWAkEhf1-wPuVYxl:-Nbpzk9jEbLXUG-0aG4f:b-r1vf3m) ([raw file](https://github.com/paranext/paranext-core/blob/084e89c18e731682e1cbda3f9fda1acc0e7ec713/src/extension-host/services/extension.service.ts#L113)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

The README doesn't talk about command-line switches at all. I was going to make the necessary changes to our wiki where it talks about this switch once this PR is merged.
</blockquote></details>

Ok great; that works for me!

**Review by lyonsil — APPROVED** [review]
:lgtm: 

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/355#-:-Nbq-_6h8iJ_NwQa9-Ic:bg7igkv)* status: :shipit: complete! all files reviewed, all discussions resolved

**Comment by irahopkinson** [comment]
*[`src/extension-host/services/extension.service.ts` line 113 at r1](https://reviewable.io/reviews/paranext/paranext-core/355#-NboKWAkEhf1-wPuVYxl:-NbqdeGY2odnPibKijn_:b-89wkkj) ([raw file](https://github.com/paranext/paranext-core/blob/084e89c18e731682e1cbda3f9fda1acc0e7ec713/src/extension-host/services/extension.service.ts#L113)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

Ok great; that works for me!
</blockquote></details>

https://github.com/paranext/paranext-extension-template/wiki/Debugging-Your-Extension-in-the-Production-Application has been updated now. The CWD is always where the app is run from in development or production so paths are relative to where it is run from.

**Pull request merged**
