### PR TITLE
fix components layout + enhance preview app

### PR DESCRIPTION
**Pull request by Sebastian-ubs**
1. fix BCV control (removing requirement to be wrapped in a `pr-flex`
2. fix vertical tabs spacing for any text direction
3. add RTL-LTR toggle to preview app
4. add "guide" section that shows examples of good and bad usage

grafik

This change is [Reviewable](https://reviewable.io/reviews/paranext/paranext-core/931)

### CODE REVIEW

**Review by jolierabideau — CHANGES_REQUESTED** [review]
This is awesome Sebastian! Thanks!

> Reviewed 12 of 13 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/931#-:-O-6RKB7A7uvOEuB9zrd:byasn7v)* status: all files reviewed, 6 unresolved discussions (waiting on @Sebastian-ubs)

___
*[`lib/platform-bible-react/src/preview/direction-toggle.tsx` line 9 at r2](https://reviewable.io/reviews/paranext/paranext-core/931#-O-6JYiRDY1GUKJ-pL65:-O-6JYiRDY1GUKJ-pL66:b-5lknqj) ([raw file](https://github.com/paranext/paranext-core/blob/5514691064538c130ba6c90042616c6356c117a5/lib/platform-bible-react/src/preview/direction-toggle.tsx#L9)):*
> ```XML
> export const DirToggle = React.forwardRef<
>   HTMLButtonElement,
>   ButtonProps & { direction: Direction; setDirection: Dispatch<SetStateAction<Direction>> }
> ```

Same comment about passing a handler instead
___
*[`lib/platform-bible-react/src/preview/direction-toggle.tsx` line 13 at r2](https://reviewable.io/reviews/paranext/paranext-core/931#-O-6KCNvCrfdTkVptMB9:-O-6KCNvCrfdTkVptMBA:b-2x840m) ([raw file](https://github.com/paranext/paranext-core/blob/5514691064538c130ba6c90042616c6356c117a5/lib/platform-bible-react/src/preview/direction-toggle.tsx#L13)):*
> ```XML
>   const oppositeDirection = direction === 'rtl' ? 'ltr' : 'rtl';
>   return (
>     // eslint-disable-next-line no-alert
> ```

When we disable a rule, we add a comment above with an explanation.
___
*[`lib/platform-bible-react/src/preview/direction-toggle.tsx` line 19 at r2](https://reviewable.io/reviews/paranext/paranext-core/931#-O-6JseZ6dw2ghU4awLJ:-O-6JseZ6dw2ghU4awLK:b-2x840m) ([raw file](https://github.com/paranext/paranext-core/blob/5514691064538c130ba6c90042616c6356c117a5/lib/platform-bible-react/src/preview/direction-toggle.tsx#L19)):*
> ```XML
>         setDirection(oppositeDirection);
>       }}
>       // eslint-disable-next-line react/jsx-props-no-spreading
> ```

When we disable a rule, we add a comment above with an explanation.
___
*[`lib/platform-bible-react/src/preview/components/basics.component.tsx` line 39 at r2](https://reviewable.io/reviews/paranext/paranext-core/931#-O-6Ka-q5TBZt2M7-I3R:-O-6Ka-q5TBZt2M7-I3S:betpmn0) ([raw file](https://github.com/paranext/paranext-core/blob/5514691064538c130ba6c90042616c6356c117a5/lib/platform-bible-react/src/preview/components/basics.component.tsx#L39)):*
> ```XML
>           Wrapped
>           <div>
>             {/* eslint-disable-next-line no-alert */}
> ```

Same comment about adding an explanation
___
*[`lib/platform-bible-react/src/preview/components/basics.component.tsx` line 54 at r2](https://reviewable.io/reviews/paranext/paranext-core/931#-O-6KXTB0Bk-S4xnEhO9:-O-6KXTB0Bk-S4xnEhOA:betpmn0) ([raw file](https://github.com/paranext/paranext-core/blob/5514691064538c130ba6c90042616c6356c117a5/lib/platform-bible-react/src/preview/components/basics.component.tsx#L54)):*
> ```XML
>                 <td>variant</td>
>                 <td>
>                   {/* eslint-disable-next-line no-alert */}
> ```

Same comment about adding an explanation
___
*[`lib/platform-bible-react/src/preview/components/guide.component.tsx` line 18 at r2](https://reviewable.io/reviews/paranext/paranext-core/931#-O-6ICddD1SvKhs-84rd:-O-6ICddD1SvKhs-84re:b-nbxhp) ([raw file](https://github.com/paranext/paranext-core/blob/5514691064538c130ba6c90042616c6356c117a5/lib/platform-bible-react/src/preview/components/guide.component.tsx#L18)):*
> ```XML
>   direction,
>   setDirection,
> }: HasDirection & { setDirection: Dispatch<SetStateAction<Direction>> }) {
> ```

I think good practice is to pass a handler that uses `setDirection`, like `const handleChange = ( direction ) =>  { setDirection(direction)  }`, but I'm unsure how big of a deal it is.

**Review by jolierabideau — APPROVED** [review]
Thanks Sebastian!

**Review by jolierabideau — APPROVED** [review]
> Reviewed 8 of 10 files at r3, 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/931)* status: all files reviewed, 6 unresolved discussions (waiting on @Sebastian-ubs)

**Review by Sebastian-ubs — COMMENTED** [review]
> Dismissed @jolierabideau from 6 discussions.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/931)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

___
*[`lib/platform-bible-react/src/preview/direction-toggle.tsx` line 9 at r2](https://reviewable.io/reviews/paranext/paranext-core/931#-O-6JYiRDY1GUKJ-pL65:-O-fpGwB9PR3Buk0_Un_:bb6un1j) ([raw file](https://github.com/paranext/paranext-core/blob/5514691064538c130ba6c90042616c6356c117a5/lib/platform-bible-react/src/preview/direction-toggle.tsx#L9)):*
<details><summary><i>Previously, jolierabideau wrote…</i></summary><blockquote>

Same comment about passing a handler instead
</blockquote></details>

Done
___
*[`lib/platform-bible-react/src/preview/direction-toggle.tsx` line 13 at r2](https://reviewable.io/reviews/paranext/paranext-core/931#-O-6KCNvCrfdTkVptMB9:-O-fpNQR3BdzPY5Ry3p2:bb6un1j) ([raw file](https://github.com/paranext/paranext-core/blob/5514691064538c130ba6c90042616c6356c117a5/lib/platform-bible-react/src/preview/direction-toggle.tsx#L13)):*
<details><summary><i>Previously, jolierabideau wrote…</i></summary><blockquote>

When we disable a rule, we add a comment above with an explanation.
</blockquote></details>

Done
___
*[`lib/platform-bible-react/src/preview/direction-toggle.tsx` line 19 at r2](https://reviewable.io/reviews/paranext/paranext-core/931#-O-6JseZ6dw2ghU4awLJ:-O-fpP5A84kT3iKp-FzP:bb6un1j) ([raw file](https://github.com/paranext/paranext-core/blob/5514691064538c130ba6c90042616c6356c117a5/lib/platform-bible-react/src/preview/direction-toggle.tsx#L19)):*
<details><summary><i>Previously, jolierabideau wrote…</i></summary><blockquote>

When we disable a rule, we add a comment above with an explanation.
</blockquote></details>

Done
___
*[`lib/platform-bible-react/src/preview/components/basics.component.tsx` line 39 at r2](https://reviewable.io/reviews/paranext/paranext-core/931#-O-6Ka-q5TBZt2M7-I3R:-O-fpQW11Db52zFdM07A:bb6un1j) ([raw file](https://github.com/paranext/paranext-core/blob/5514691064538c130ba6c90042616c6356c117a5/lib/platform-bible-react/src/preview/components/basics.component.tsx#L39)):*
<details><summary><i>Previously, jolierabideau wrote…</i></summary><blockquote>

Same comment about adding an explanation
</blockquote></details>

Done
___
*[`lib/platform-bible-react/src/preview/components/basics.component.tsx` line 54 at r2](https://reviewable.io/reviews/paranext/paranext-core/931#-O-6KXTB0Bk-S4xnEhO9:-O-fpRcQ7DcDCT7dwE6b:bb6un1j) ([raw file](https://github.com/paranext/paranext-core/blob/5514691064538c130ba6c90042616c6356c117a5/lib/platform-bible-react/src/preview/components/basics.component.tsx#L54)):*
<details><summary><i>Previously, jolierabideau wrote…</i></summary><blockquote>

Same comment about adding an explanation
</blockquote></details>

Done
___
*[`lib/platform-bible-react/src/preview/components/guide.component.tsx` line 18 at r2](https://reviewable.io/reviews/paranext/paranext-core/931#-O-6ICddD1SvKhs-84rd:-O-fpT6v8qLcz21LUwXe:bb6un1j) ([raw file](https://github.com/paranext/paranext-core/blob/5514691064538c130ba6c90042616c6356c117a5/lib/platform-bible-react/src/preview/components/guide.component.tsx#L18)):*
<details><summary><i>Previously, jolierabideau wrote…</i></summary><blockquote>

I think good practice is to pass a handler that uses `setDirection`, like `const handleChange = ( direction ) =>  { setDirection(direction)  }`, but I'm unsure how big of a deal it is.
</blockquote></details>

Done

**Pull request merged**
