### PR TITLE
Enable webview styles

### PR DESCRIPTION
**Pull request by irahopkinson**
- Build components with vite
  - scripture utils moved to papi-components
- Install "papi-components" package
- Limit C# message length
- Remove `papi.react.components`

- - -
This change is [Reviewable](https://reviewable.io/reviews/paranext/paranext-core/207)

### CODE REVIEW

**Review by tjcouch-sil — CHANGES_REQUESTED** [review]
Thanks for the hard work on this!! Exciting :) Did anything you did fix the webview bundle size?

> Reviewed 51 of 58 files at r1, 7 of 7 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/207#-:-NWNZJqZC-tK6Rxmds6V:by00wad)* status: all files reviewed, 7 unresolved discussions (waiting on @irahopkinson)

___
*[`package.json` line 58 at r2](https://reviewable.io/reviews/paranext/paranext-core/207#-NWNS_nUCPYZvjmkURLv:-NWNS_nUCPYZvjmkURLw:b9yxm9i) ([raw file](https://github.com/paranext/paranext-core/blob/84e2ff74198f94429411e4504b725e0c6d12f6ef/package.json#L58)):*
> ```JSON
>     "csharp:tool:restore": "cd c-sharp && dotnet tool restore",
>     "postinstall": "ts-node .erb/scripts/check-native-dep.js && electron-builder install-app-deps && cd extensions && npm install && cd .. && cross-env NODE_ENV=development TS_NODE_TRANSPILE_ONLY=true webpack --config ./.erb/configs/webpack.config.renderer.dev.dll.ts",
>     "lint": "npm run build:types && npm run build:extensions && cross-env NODE_ENV=development eslint . --ext .js,.jsx,.ts,.tsx && cd lib/papi-dts && npm run lint && cd ../../extensions && npm run lint",
> ```

Do we need to lint `papi-components` here?
___
*[`package.json` line 60 at r2](https://reviewable.io/reviews/paranext/paranext-core/207#-NWNSp6X2Z3h9z8dVbwe:-NWNSp6X2Z3h9z8dVbwf:b9yxm9i) ([raw file](https://github.com/paranext/paranext-core/blob/84e2ff74198f94429411e4504b725e0c6d12f6ef/package.json#L60)):*
> ```JSON
>     "lint": "npm run build:types && npm run build:extensions && cross-env NODE_ENV=development eslint . --ext .js,.jsx,.ts,.tsx && cd lib/papi-dts && npm run lint && cd ../../extensions && npm run lint",
>     "lint:config": "cross-env NODE_ENV=development eslint --print-config .eslintrc.js > .eslintConfig.json",
>     "lint:staged": "npm run build:types && npm run build:extensions && lint-staged -q && cd lib/papi-dts && npm run lint:staged && cd ../../extensions && npm run lint:staged",
> ```

Do we need to lint `papi-components` here?
___
*[`lib/papi-components/.eslintrc` line 5 at r2](https://reviewable.io/reviews/paranext/paranext-core/207#-NWNTkwg8IGLpd_nHpwL:-NWNTkwg8IGLpd_nHpwM:b-aui7pj) ([raw file](https://github.com/paranext/paranext-core/blob/84e2ff74198f94429411e4504b725e0c6d12f6ef/lib/papi-components/.eslintrc#L5)):*
> ```
>   "parser": "@typescript-eslint/parser",
>   "plugins": ["@typescript-eslint", "prettier"],
>   "extends": [
> ```

Is there a reason we're not extending the main eslintrc here? You do have to do some special stuff to override some stuff from the main one. You can see the way it can be extended in `extensions/.eslintrc.cjs` if that's the only problem.
___
*[`lib/papi-components/.gitignore` line 6 at r2](https://reviewable.io/reviews/paranext/paranext-core/207#-NWNUOgTAaCXWed0Xzjm:-NWNUOgTAaCXWed0Xzjn:b-vcojur) ([raw file](https://github.com/paranext/paranext-core/blob/84e2ff74198f94429411e4504b725e0c6d12f6ef/lib/papi-components/.gitignore#L6)):*
> ```ignore
> # production
> build
> # dist # We want these commited so developers don't need to build the package.
> ```

I think this warrants a discussion among the core team. We are building `papi-dts` and extensions on the server, and I expect we would want to do the same here.
___
*[`lib/papi-components/package.json` line 4 at r2](https://reviewable.io/reviews/paranext/paranext-core/207#-NWNVQ380EVavWdiP81c:-NWNVQ380EVavWdiP81d:b-7thnh4) ([raw file](https://github.com/paranext/paranext-core/blob/84e2ff74198f94429411e4504b725e0c6d12f6ef/lib/papi-components/package.json#L4)):*
> ```JSON
>   "name": "papi-components",
>   "version": "0.0.1",
>   "description": "Components available on Paranext's PAPI - package to include styles sheets.",
> ```

Probably should change this description to something like "React components to use in Paranext with matching styles" or something.
___
*[`src/stories/button.stories.tsx` line 2 at r2](https://reviewable.io/reviews/paranext/paranext-core/207#-NWNY51r6Z7Nz56UZnhT:-NWNY51r6Z7Nz56UZnhU:b-o40dl4) ([raw file](https://github.com/paranext/paranext-core/blob/84e2ff74198f94429411e4504b725e0c6d12f6ef/src/stories/button.stories.tsx#L2)):*
> ```XML
> import type { Meta, StoryObj } from '@storybook/react';
> import { Button } from 'papi-components';
> ```

Think we should put this storybook stuff inside `papi-components`? Would you mind making an issue for this?
___
*[`src/stories/table.stories.tsx` line 9 at r2](https://reviewable.io/reviews/paranext/paranext-core/207#-NWNYfah0i1wQ8kRl_Vv:-NWNYfah0i1wQ8kRl_Vw:b-uwifr7) ([raw file](https://github.com/paranext/paranext-core/blob/84e2ff74198f94429411e4504b725e0c6d12f6ef/src/stories/table.stories.tsx#L9)):*
> ```XML
>   TableCopyEvent,
>   TablePasteEvent,
> } from 'papi-components/src/table.component';
> ```

This is a bit of a strange import... Can we import this from `papi-components`?

**Review by irahopkinson — COMMENTED** [review]
No but I did discover that it is controlled by `extensions\vite\vite-web-view.config.ts`. Even when I removed generation of source maps in the `papi-components`, they are brought back by `extensions\vite\vite-web-view.config.ts`. The source maps could be so large because we may not be excluding the actual sources from the maps but I didn't investigate that. But a map could be removed there individually if needed (see [issue comment](https://github.com/paranext/paranext-core/issues/179#issuecomment-1564849596)) but I think we will need to do a prodcution configuration that removes all source maps (but not until next year).

> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/207#-:-NWOYBGP7tiPYbaPHORM:b-tzj61q)* status: 57 of 58 files reviewed, 1 unresolved discussion (waiting on @tjcouch-sil)

___
*[`package.json` line 58 at r2](https://reviewable.io/reviews/paranext/paranext-core/207#-NWNS_nUCPYZvjmkURLv:-NWOWUCq5SQCdKdGlpH8:b-h6wjk5) ([raw file](https://github.com/paranext/paranext-core/blob/84e2ff74198f94429411e4504b725e0c6d12f6ef/package.json#L58)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

Do we need to lint `papi-components` here?
</blockquote></details>

No, since `papi-components` is its own npm package, we lint and build it separately. See my larger comment below.
___
*[`package.json` line 60 at r2](https://reviewable.io/reviews/paranext/paranext-core/207#-NWNSp6X2Z3h9z8dVbwe:-NWOWkZg1ZjOhzrXYkQ2:b-h6wjk5) ([raw file](https://github.com/paranext/paranext-core/blob/84e2ff74198f94429411e4504b725e0c6d12f6ef/package.json#L60)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

Do we need to lint `papi-components` here?
</blockquote></details>

No, since `papi-components` is its own npm package, we lint and build it separately. See my larger comment below.
___
*[`lib/papi-components/.eslintrc` line 5 at r2](https://reviewable.io/reviews/paranext/paranext-core/207#-NWNTkwg8IGLpd_nHpwL:-NWOWnI95W7oYSuvjjp3:b-tnnnx2) ([raw file](https://github.com/paranext/paranext-core/blob/84e2ff74198f94429411e4504b725e0c6d12f6ef/lib/papi-components/.eslintrc#L5)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

Is there a reason we're not extending the main eslintrc here? You do have to do some special stuff to override some stuff from the main one. You can see the way it can be extended in `extensions/.eslintrc.cjs` if that's the only problem.
</blockquote></details>

No, since `papi-components` is its own npm package, we lint and build it separately. See my comment below.
___
*[`lib/papi-components/.gitignore` line 6 at r2](https://reviewable.io/reviews/paranext/paranext-core/207#-NWNUOgTAaCXWed0Xzjm:-NWOb5Mu7n286RE7cpFb:bgx71fq) ([raw file](https://github.com/paranext/paranext-core/blob/84e2ff74198f94429411e4504b725e0c6d12f6ef/lib/papi-components/.gitignore#L6)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

I think this warrants a discussion among the core team. We are building `papi-dts` and extensions on the server, and I expect we would want to do the same here.
</blockquote></details>

I think that `papi-components` is completely different than `papi-dts`. `papi-dts` should never be its own npm package and can change on a minute by minute basis when coding. It therefore needs to be built with everything else. For that reason you could argue that the generated file could/should be ignored from git (but its only one file so fine as is). Because `papi-components` is an npm package (even though it's not published externally yet), changes to it can be made and "published" (currently that means commited but could be ignored from git once we publish to npm) on their own cycle. Happy to have a core team discussion on this.
___
*[`lib/papi-components/package.json` line 4 at r2](https://reviewable.io/reviews/paranext/paranext-core/207#-NWNVQ380EVavWdiP81c:-NWOalcd2QQ-YhJMLVxd:b-896fix) ([raw file](https://github.com/paranext/paranext-core/blob/84e2ff74198f94429411e4504b725e0c6d12f6ef/lib/papi-components/package.json#L4)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

Probably should change this description to something like "React components to use in Paranext with matching styles" or something.
</blockquote></details>

Done.
___
*[`src/stories/button.stories.tsx` line 2 at r2](https://reviewable.io/reviews/paranext/paranext-core/207#-NWNY51r6Z7Nz56UZnhT:-NWOWwbD7gHni96gUB7S:b-r436d7) ([raw file](https://github.com/paranext/paranext-core/blob/84e2ff74198f94429411e4504b725e0c6d12f6ef/src/stories/button.stories.tsx#L2)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

Think we should put this storybook stuff inside `papi-components`? Would you mind making an issue for this?
</blockquote></details>

I thought about that but I think we will want to storybook things outside of `papi-components` such as dock window items and menu components, therefore we want to keep storybook at the app root level. Hopefully we can group things in storybook to organize them as we grow.
___
*[`src/stories/table.stories.tsx` line 9 at r2](https://reviewable.io/reviews/paranext/paranext-core/207#-NWNYfah0i1wQ8kRl_Vv:-NWOXPd9-r5I3KHMrA3J:b-mvh4tu) ([raw file](https://github.com/paranext/paranext-core/blob/84e2ff74198f94429411e4504b725e0c6d12f6ef/src/stories/table.stories.tsx#L9)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

This is a bit of a strange import... Can we import this from `papi-components`?
</blockquote></details>

Yes, this is intentionally left for the extensions team to fix since table wasn't previously included properly. I added the checkbox in this change as another example for them but left the table component as an excercise for them to learn about including components. We need to leave them something to do for issue #158.

**Review by tjcouch-sil — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/207)* status: all files reviewed, 1 unresolved discussion (waiting on @irahopkinson)

___
*[`lib/papi-components/.eslintrc` line 5 at r2](https://reviewable.io/reviews/paranext/paranext-core/207#-NWNTkwg8IGLpd_nHpwL:-NWm24Gl5y0CMLH2pK8S:bhu7xrn) ([raw file](https://github.com/paranext/paranext-core/blob/84e2ff74198f94429411e4504b725e0c6d12f6ef/lib/papi-components/.eslintrc#L5)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

No, since `papi-components` is its own npm package, we lint and build it separately. See my comment below.
</blockquote></details>

Does that mean we shouldn't use the same (or similar) linting rules in `papi-components` as for `paranext-core`? I'm not sure I understand the thought process here. My thought is we might as well reduce duplication and keep configuration tight. Could you explain your thoughts more please? Thanks!
___
*[`lib/papi-components/.gitignore` line 6 at r2](https://reviewable.io/reviews/paranext/paranext-core/207#-NWNUOgTAaCXWed0Xzjm:-NWm-Ui4E6ai0ioqcp_-:b-uyh7fz) ([raw file](https://github.com/paranext/paranext-core/blob/84e2ff74198f94429411e4504b725e0c6d12f6ef/lib/papi-components/.gitignore#L6)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

I think that `papi-components` is completely different than `papi-dts`. `papi-dts` should never be its own npm package and can change on a minute by minute basis when coding. It therefore needs to be built with everything else. For that reason you could argue that the generated file could/should be ignored from git (but its only one file so fine as is). Because `papi-components` is an npm package (even though it's not published externally yet), changes to it can be made and "published" (currently that means commited but could be ignored from git once we publish to npm) on their own cycle. Happy to have a core team discussion on this.
</blockquote></details>

Actually, I think we do want `papi-dts` to be its own published npm package as well. That way, people can develop extensions without needing `paranext-core` installed and built and such. It would be worth having a meeting to figure out how we want these dependencies to look. I will try to set one up soon.
___
*[`src/stories/button.stories.tsx` line 2 at r2](https://reviewable.io/reviews/paranext/paranext-core/207#-NWNY51r6Z7Nz56UZnhT:-NWm1N2W5o9znq070LiF:b9rmzqx) ([raw file](https://github.com/paranext/paranext-core/blob/84e2ff74198f94429411e4504b725e0c6d12f6ef/src/stories/button.stories.tsx#L2)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

I thought about that but I think we will want to storybook things outside of `papi-components` such as dock window items and menu components, therefore we want to keep storybook at the app root level. Hopefully we can group things in storybook to organize them as we grow.
</blockquote></details>

I was thinking two storybooks, one for components and one for normal core stuff. It's not a big deal right now either way, though.
___
*[`src/stories/table.stories.tsx` line 9 at r2](https://reviewable.io/reviews/paranext/paranext-core/207#-NWNYfah0i1wQ8kRl_Vv:-NWm1rOi5_uwxQUk5tNz:b-2slq23) ([raw file](https://github.com/paranext/paranext-core/blob/84e2ff74198f94429411e4504b725e0c6d12f6ef/src/stories/table.stories.tsx#L9)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

Yes, this is intentionally left for the extensions team to fix since table wasn't previously included properly. I added the checkbox in this change as another example for them but left the table component as an excercise for them to learn about including components. We need to leave them something to do for issue #158.
</blockquote></details>

I'm not sure I understand, but I trust your judgment :) would you mind please describing this issue in #158 if you think the changes should be there?

**Review by irahopkinson — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/207)* status: 43 of 59 files reviewed, 1 unresolved discussion (waiting on @tjcouch-sil)

___
*[`lib/papi-components/.eslintrc` line 5 at r2](https://reviewable.io/reviews/paranext/paranext-core/207#-NWNTkwg8IGLpd_nHpwL:-NWo_G901GOgf76ajDYQ:bnm9lyg) ([raw file](https://github.com/paranext/paranext-core/blob/84e2ff74198f94429411e4504b725e0c6d12f6ef/lib/papi-components/.eslintrc#L5)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

Does that mean we shouldn't use the same (or similar) linting rules in `papi-components` as for `paranext-core`? I'm not sure I understand the thought process here. My thought is we might as well reduce duplication and keep configuration tight. Could you explain your thoughts more please? Thanks!
</blockquote></details>

I was thinking since this might be removed from Core eventually then it needed to define its own rules (even if they are a duplicate of core's rules) but since we aren't doing that yet (or even ever), I've extended it off core as you suggest.
___
*[`lib/papi-components/.gitignore` line 6 at r2](https://reviewable.io/reviews/paranext/paranext-core/207#-NWNUOgTAaCXWed0Xzjm:-NWoaHvk1LzMzfPvnRnf:b3yjwxa) ([raw file](https://github.com/paranext/paranext-core/blob/84e2ff74198f94429411e4504b725e0c6d12f6ef/lib/papi-components/.gitignore#L6)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

Actually, I think we do want `papi-dts` to be its own published npm package as well. That way, people can develop extensions without needing `paranext-core` installed and built and such. It would be worth having a meeting to figure out how we want these dependencies to look. I will try to set one up soon.
</blockquote></details>

I think we resolved this at the core meeting. I'm also doing the linting at build time as discussed.
___
*[`src/stories/table.stories.tsx` line 9 at r2](https://reviewable.io/reviews/paranext/paranext-core/207#-NWNYfah0i1wQ8kRl_Vv:-NWoi9CcDx_p5mBGYzKT:bwg1q1c) ([raw file](https://github.com/paranext/paranext-core/blob/84e2ff74198f94429411e4504b725e0c6d12f6ef/src/stories/table.stories.tsx#L9)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

I'm not sure I understand, but I trust your judgment :) would you mind please describing this issue in #158 if you think the changes should be there?
</blockquote></details>

Done. See https://github.com/paranext/paranext-core/issues/158#issuecomment-1571218428

**Review by tjcouch-sil — APPROVED** [review]
:lgtm: Awesome. Thanks for the hard work on this! Just the one thing about eslintrc to follow up, but it's not blocking as I assume you ran the scripts and such after extending. Let's go ahead and get this in. If there are any eslintrc problems, maybe a follow-up PR can solve the problems or something.

> Reviewed 16 of 16 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/207#-:-NWrLcLT8pZ-ZpAgwrP2:b-omfz28)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @irahopkinson)

___
*[`lib/papi-components/.eslintrc` line 5 at r2](https://reviewable.io/reviews/paranext/paranext-core/207#-NWNTkwg8IGLpd_nHpwL:-NWrJ6Bk4eGgR9nxJWVh:b-wdfw46) ([raw file](https://github.com/paranext/paranext-core/blob/84e2ff74198f94429411e4504b725e0c6d12f6ef/lib/papi-components/.eslintrc#L5)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

I was thinking since this might be removed from Core eventually then it needed to define its own rules (even if they are a duplicate of core's rules) but since we aren't doing that yet (or even ever), I've extended it off core as you suggest.
</blockquote></details>

Cool :) I am surprised to see you didn't have to do the webpack disable thing I did in the extensions eslintrc. Do you get any weird errors or warnings in the console related to webpack when linting or building `papi-components` now that you're extending the main eslintrc?
___
*[`lib/papi-components/.gitignore` line 6 at r2](https://reviewable.io/reviews/paranext/paranext-core/207#-NWNUOgTAaCXWed0Xzjm:-NWrJfLZDHfqGDykKg7c:b-b5pdwu) ([raw file](https://github.com/paranext/paranext-core/blob/84e2ff74198f94429411e4504b725e0c6d12f6ef/lib/papi-components/.gitignore#L6)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

I think we resolved this at the core meeting. I'm also doing the linting at build time as discussed.
</blockquote></details>

Yes, here are my notes from the meeting. Decisions in bold:

npm packages inside paranext-core
- build/lint with paranext-core?
  - Tim - everything changing so fast that it would be annoying to publish separately. Once things settle, use published packages. Can we keep up with quick changes on a published package?
  - Alternatively do separate build for papi-dts and publish and then build paranext from that
  - **Since paranext-core depends on papi-components (not other way around as is the case with papi-dts), when changes happen to papi-components, they will have to be built to see any changes in paranext-core. So let's make linting happen on building papi-components and leave it at that (meaning updated build files will be assumed to mean the source has been linted)**
- built code checked in?
  - **Keep it in so we don't have to build every pre-commit and such**
    - Makes it easier for us for now. We can probably remove later when we publish
  - Go ahead and publish since we have people working on it
    - We're not at external extension ready. Those who are working are incidentally doing so

Thanks for following up on these decisions!
___
*[`lib/papi-components/package.json` line 34 at r5](https://reviewable.io/reviews/paranext/paranext-core/207#-NWrL5yX9csC2FHzT8b4:-NWrL5yX9csC2FHzT8b5:b-enp2ox) ([raw file](https://github.com/paranext/paranext-core/blob/4aa228bcd9b9ad4bcbf98de48bd39dfe828c1b04/lib/papi-components/package.json#L34)):*
> ```JSON
>     "build:basic": "tsc && vite build && dts-bundle-generator --config ./dts-bundle-generator.config.ts",
>     "build": "npm run build:basic && npm run format:scripts && npm run lint:scripts && npm run format:styles && npm run lint:styles",
>     "watch": "tsc && vite build --watch",
> ```

I think we may need to be watchful for when devs run `watch` but don't ever build. But I don't have a better solution right now. This will hopefully work just fine for now.
___
*[`src/stories/table.stories.tsx` line 9 at r2](https://reviewable.io/reviews/paranext/paranext-core/207#-NWNYfah0i1wQ8kRl_Vv:-NWrLV9R56PU_cfVRlzd:b87vxor) ([raw file](https://github.com/paranext/paranext-core/blob/84e2ff74198f94429411e4504b725e0c6d12f6ef/src/stories/table.stories.tsx#L9)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

Done. See https://github.com/paranext/paranext-core/issues/158#issuecomment-1571218428
</blockquote></details>

Thank you!! :)

**Comment by irahopkinson** [comment]
*[`lib/papi-components/.eslintrc` line 5 at r2](https://reviewable.io/reviews/paranext/paranext-core/207#-NWNTkwg8IGLpd_nHpwL:-NWstt2BExoOk3P06i8V:b-k1ufo7) ([raw file](https://github.com/paranext/paranext-core/blob/84e2ff74198f94429411e4504b725e0c6d12f6ef/lib/papi-components/.eslintrc#L5)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

Cool :) I am surprised to see you didn't have to do the webpack disable thing I did in the extensions eslintrc. Do you get any weird errors or warnings in the console related to webpack when linting or building `papi-components` now that you're extending the main eslintrc?
</blockquote></details>

Yeah, I first copied everything over. I think what made a difference for me is I added `"root": true,`, after that I removed every setting one at a time to see what was needed and only `alwaysTryTypes` remains.

**Pull request merged**
