### PR TITLE
Replace MUI icon with Lucide icon

### PR DESCRIPTION
**Pull request by rolfheij-sil**
This change is [Reviewable](https://reviewable.io/reviews/paranext/paranext-core/1352)

### CODE REVIEW

**Review by Sebastian-ubs — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/1352)* status: 0 of 4 files reviewed, 1 unresolved discussion (waiting on @rolfheij-sil)

___
*[`src/renderer/components/dialogs/select-multiple-projects.dialog.tsx` line 90 at r1](https://reviewable.io/reviews/paranext/paranext-core/1352#-OCciD_i9lTcuQwZv04G:-OCciD_i9lTcuQwZv04H:b8ja23k) ([raw file](https://github.com/paranext/paranext-core/blob/b36d28f0eb0f1bbcdde2bf7186531d086da46729/src/renderer/components/dialogs/select-multiple-projects.dialog.tsx#L90)):*
> ```XML
>           isCheckable
>         >
>           <FolderOpenIcon className="select-multiple-projects-folder-icon" />
> ```

Why not using tailwind e.g. like `tw-ms-4`? To promote consistency across the ui code, this would be the chance to also remove the rest of the scss files in favor of using tailwind classes.

**Review by rolfheij-sil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/1352)* status: 0 of 4 files reviewed, 1 unresolved discussion (waiting on @Sebastian-ubs)

___
*[`src/renderer/components/dialogs/select-multiple-projects.dialog.tsx` line 90 at r1](https://reviewable.io/reviews/paranext/paranext-core/1352#-OCciD_i9lTcuQwZv04G:-OCd1js0BxGRDiF1p5fW:bdvrftr) ([raw file](https://github.com/paranext/paranext-core/blob/b36d28f0eb0f1bbcdde2bf7186531d086da46729/src/renderer/components/dialogs/select-multiple-projects.dialog.tsx#L90)):*
<details><summary><i>Previously, Sebastian-ubs wrote…</i></summary><blockquote>

Why not using tailwind e.g. like `tw-ms-4`? To promote consistency across the ui code, this would be the chance to also remove the rest of the scss files in favor of using tailwind classes.
</blockquote></details>

AFAIK Tailwind is not available in this part of the code unfortunately. It's only available in extensions and platform-bible-react so far

**Review by tjcouch-sil — APPROVED** [review]
:lgtm:

> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/1352#-:-OCdWLtZ6T_7PH8LXM3S:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @Sebastian-ubs)

___
*[`src/renderer/components/dialogs/select-multiple-projects.dialog.tsx` line 90 at r1](https://reviewable.io/reviews/paranext/paranext-core/1352#-OCciD_i9lTcuQwZv04G:-OCdW6pq73KOrLQYk_gv:br3i9q3) ([raw file](https://github.com/paranext/paranext-core/blob/b36d28f0eb0f1bbcdde2bf7186531d086da46729/src/renderer/components/dialogs/select-multiple-projects.dialog.tsx#L90)):*
<details><summary><i>Previously, rolfheij-sil (Rolf Heij) wrote…</i></summary><blockquote>

AFAIK Tailwind is not available in this part of the code unfortunately. It's only available in extensions and platform-bible-react so far
</blockquote></details>

Indeed. Sadly we can't use tailwind in core code. We don't really make a whole lot of core UI, so I don't know that anyone has reeeeeally missed it all that much up to this point. Definitely not in the scope of this PR to add it.

**Review by rolfheij-sil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/1352)* status: all files reviewed, 1 unresolved discussion (waiting on @Sebastian-ubs)

___
*[`src/renderer/components/dialogs/select-multiple-projects.dialog.tsx` line 90 at r1](https://reviewable.io/reviews/paranext/paranext-core/1352#-OCciD_i9lTcuQwZv04G:-OCeF4Bn89Wie0DhfAu9:b-896fix) ([raw file](https://github.com/paranext/paranext-core/blob/b36d28f0eb0f1bbcdde2bf7186531d086da46729/src/renderer/components/dialogs/select-multiple-projects.dialog.tsx#L90)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

Indeed. Sadly we can't use tailwind in core code. We don't really make a whole lot of core UI, so I don't know that anyone has reeeeeally missed it all that much up to this point. Definitely not in the scope of this PR to add it.
</blockquote></details>

Done.

**Pull request merged**
