### PR TITLE
add a draft Paratext10 theme to preview app

### PR DESCRIPTION
**Pull request by Sebastian-ubs**
This change is [Reviewable](https://reviewable.io/reviews/paranext/paranext-core/985)

used color palette: https://supercolorpalette.com/?scp=G0-hsl-99827A-E7DDD0-FEF4E7-FEFAF1-FFFFFF-D8E9E3-719892-07463D-0A433D-083030-041616-000000-85DBB8-F2F52E-CD3737

# Light Theme

grafik

grafik

grafik

# Dark Theme

grafik

grafik

grafik

### CODE REVIEW

**Comment by Sebastian-ubs** [comment]
Here is what the theme looks like, when applied to Shadcn's theming page

Screenshot 2024-07-05 135054

grafik

**Review by tjcouch-sil — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/985)* status: 0 of 8 files reviewed, 1 unresolved discussion (waiting on @Sebastian-ubs)

___
*[`lib/platform-bible-react/src/preview/icons/paratext-logo.component.tsx` line 1 at r1](https://reviewable.io/reviews/paranext/paranext-core/985#-O1HlKq85U7rUBGrnq_V:-O1HlKq85U7rUBGrnq_W:b-qk2mnq) ([raw file](https://github.com/paranext/paranext-core/blob/e90b16a929349eff3d313b697a012f70516c9606/lib/platform-bible-react/src/preview/icons/paratext-logo.component.tsx#L1)):*
> ```XML
> export default function ParatextLogo() {
> ```

To my understanding, we are not supposed to add this logo in our repos yet - I think the date for doing so is a few weeks out. Additionally, we may not even add this logo in the public repos at all.

**Review by jolierabideau — CHANGES_REQUESTED** [review]
> Reviewed 8 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/985)* status: all files reviewed, 3 unresolved discussions (waiting on @Sebastian-ubs)

___
*[`lib/platform-bible-react/src/preview/theme-toggle.component.tsx` line 64 at r1](https://reviewable.io/reviews/paranext/paranext-core/985#-O1Hmy-m9qTzYphLyV1Z:-O1Hmy-m9qTzYphLyV1_:bu4af8l) ([raw file](https://github.com/paranext/paranext-core/blob/e90b16a929349eff3d313b697a012f70516c9606/lib/platform-bible-react/src/preview/theme-toggle.component.tsx#L64)):*
> ```XML
>           onClick={() =>
>             setTheme(
>               // eslint-disable-next-line no-type-assertion/no-type-assertion
> ```

Missing description comment above this
___
*[`lib/platform-bible-react/src/preview/theme-toggle.component.tsx` line 80 at r1](https://reviewable.io/reviews/paranext/paranext-core/985#-O1Hn24O4qo-MZuwXDzG:-O1Hn24PDo0w0mp56Vkt:bu4af8l) ([raw file](https://github.com/paranext/paranext-core/blob/e90b16a929349eff3d313b697a012f70516c9606/lib/platform-bible-react/src/preview/theme-toggle.component.tsx#L80)):*
> ```XML
>           onClick={() =>
>             setTheme(
>               // eslint-disable-next-line no-type-assertion/no-type-assertion
> ```

Missing description comment above this

**Review by Sebastian-ubs — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/985)* status: 2 of 8 files reviewed, 2 unresolved discussions (waiting on @jolierabideau)

___
*[`lib/platform-bible-react/src/preview/theme-toggle.component.tsx` line 64 at r1](https://reviewable.io/reviews/paranext/paranext-core/985#-O1Hmy-m9qTzYphLyV1Z:-O1I2IhX2H0M86HviltC:b-896fix) ([raw file](https://github.com/paranext/paranext-core/blob/e90b16a929349eff3d313b697a012f70516c9606/lib/platform-bible-react/src/preview/theme-toggle.component.tsx#L64)):*
<details><summary><i>Previously, jolierabideau wrote…</i></summary><blockquote>

Missing description comment above this
</blockquote></details>

Done.
___
*[`lib/platform-bible-react/src/preview/theme-toggle.component.tsx` line 80 at r1](https://reviewable.io/reviews/paranext/paranext-core/985#-O1Hn24O4qo-MZuwXDzG:-O1I2JAT6IeIhq-9IJSj:b-896fix) ([raw file](https://github.com/paranext/paranext-core/blob/e90b16a929349eff3d313b697a012f70516c9606/lib/platform-bible-react/src/preview/theme-toggle.component.tsx#L80)):*
<details><summary><i>Previously, jolierabideau wrote…</i></summary><blockquote>

Missing description comment above this
</blockquote></details>

Done.

**Review by jolierabideau — APPROVED** [review]
> Reviewed 6 of 6 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/985)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Review by tjcouch-sil — APPROVED** [review]
(I did not do a full review, but somehow the wires got crossed such that my comment in Reviewable messed up GitHub and did not resolve my review. Approving to get past my unintentional block)

**Pull request merged**
