### PR TITLE
Read settings from extensions

### LINKED ISSUE #719: User Settings: Read default values from extension JSON
As an extension developer, I want to be able to get settings' values including defaults like interface language so I can stay in sync whether or not the setting has been set.

----

On the settings service:
- Maintain list of all user settings provided by extensions in their manifest files and built into core including default value instead of the list just being hard-coded
- This will include creating a settings combiner like the menu combiner. Validate to make sure the setting is only provided once

Depends on #419, #502 , #718

### PR DESCRIPTION
**Pull request by tjcouch-sil**
Highlights:
- Moved settings service to extension host
- Added settings json schemas and TypeScript types
- Read settings contributions from extensions to get defaults (and groups, labels, and descriptions, but we're not using them yet)
- Added forbidden extension names "platform" and empty string
- Added test hello world setting

Resolves #719

- - -
This change is [Reviewable](https://reviewable.io/reviews/paranext/paranext-core/852)

### CODE REVIEW

**Review by lyonsil — CHANGES_REQUESTED** [review]
> Reviewed 14 of 30 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/852)* status: 14 of 30 files reviewed, 4 unresolved discussions (waiting on @tjcouch-sil)

___
*[`assets/localization/eng.json` line 37 at r1](https://reviewable.io/reviews/paranext/paranext-core/852#-NvJSlel9Lp3bRDhjNWf:-NvJSlel9Lp3bRDhjNWg:by0ygjo) ([raw file](https://github.com/paranext/paranext-core/blob/46ec4be51ca2e5782f744414c04a9fc8059ccde7/assets/localization/eng.json#L37)):*
> ```JSON
>   "settings_platform_verseRef_label": "Current Verse Reference",
>   "settings_platform_interfaceLanguage_label": "Interface Language",
>   "setting_hello-world.group1": "Hello World Settings",
> ```

I know it's not a big deal, but did you mean to use "setting" or "settings"? Also mixing underscore and dash is a little weird. (I know you want to talk about this second thing in general.)
___
*[`lib/platform-bible-react/.vscode/settings.json` line 57 at r1](https://reviewable.io/reviews/paranext/paranext-core/852#-NvJTZ-J4z3DPvZfH6-h:-NvJTZ-J4z3DPvZfH6-i:b-2onnu) ([raw file](https://github.com/paranext/paranext-core/blob/46ec4be51ca2e5782f744414c04a9fc8059ccde7/lib/platform-bible-react/.vscode/settings.json#L57)):*
> ```JSON
>     }
>   ],
>   "jestrunner.jestPath": "../../node_modules\\jest\\bin\\jest.js"
> ```

This looks pretty Windows-specific and will probably break on Linux/Mac. Consider changing to forward slashes.
___
*[`lib/platform-bible-utils/.vscode/settings.json` line 57 at r1](https://reviewable.io/reviews/paranext/paranext-core/852#-NvJTiYq4MLvj7xZzqzU:-NvJTiYq4MLvj7xZzqzV:b5u999b) ([raw file](https://github.com/paranext/paranext-core/blob/46ec4be51ca2e5782f744414c04a9fc8059ccde7/lib/platform-bible-utils/.vscode/settings.json#L57)):*
> ```JSON
>     }
>   ],
>   "jestrunner.jestPath": "../../node_modules\\jest\\bin\\jest.js"
> ```

Same comment as other VS config file
___
*[`lib/platform-bible-utils/src/document-combiner-engine.ts` line 7 at r1](https://reviewable.io/reviews/paranext/paranext-core/852#-NvJU4cp56xveg_Szjzv:-NvJU4cq2XYE8A95U5bj:b-nq5s7j) ([raw file](https://github.com/paranext/paranext-core/blob/46ec4be51ca2e5782f744414c04a9fc8059ccde7/lib/platform-bible-utils/src/document-combiner-engine.ts#L7)):*
> ```XML
> type JsonArrayLike = unknown[];
> 
> export type JsonDocumentLike =
> ```

I don't think we want/intend to support combining JSON documents that aren't of the form `{ [key: string]: unknown }`, do we? What's the value of expanding this?

**Review by tjcouch-sil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/852)* status: 14 of 30 files reviewed, 1 unresolved discussion (waiting on @lyonsil)

___
*[`assets/localization/eng.json` line 37 at r1](https://reviewable.io/reviews/paranext/paranext-core/852#-NvJSlel9Lp3bRDhjNWf:-NvWwWpS52_wlCGLudmM:b-l9465b) ([raw file](https://github.com/paranext/paranext-core/blob/46ec4be51ca2e5782f744414c04a9fc8059ccde7/assets/localization/eng.json#L37)):*
<details><summary><i>Previously, lyonsil (Matt Lyons) wrote…</i></summary><blockquote>

I know it's not a big deal, but did you mean to use "setting" or "settings"? Also mixing underscore and dash is a little weird. (I know you want to talk about this second thing in general.)
</blockquote></details>

I'll change it. I also find it weird to use upper case in these snake_case words, but we can figure all this out later.
___
*[`lib/platform-bible-react/.vscode/settings.json` line 57 at r1](https://reviewable.io/reviews/paranext/paranext-core/852#-NvJTZ-J4z3DPvZfH6-h:-NvWwGcf1S5rGXhMG59a:byaax8k) ([raw file](https://github.com/paranext/paranext-core/blob/46ec4be51ca2e5782f744414c04a9fc8059ccde7/lib/platform-bible-react/.vscode/settings.json#L57)):*
<details><summary><i>Previously, lyonsil (Matt Lyons) wrote…</i></summary><blockquote>

This looks pretty Windows-specific and will probably break on Linux/Mac. Consider changing to forward slashes.
</blockquote></details>

Ah good eye. Thanks!
___
*[`lib/platform-bible-utils/.vscode/settings.json` line 57 at r1](https://reviewable.io/reviews/paranext/paranext-core/852#-NvJTiYq4MLvj7xZzqzU:-NvWwI9Z4jTbMVyh_OMV:bhoipsi) ([raw file](https://github.com/paranext/paranext-core/blob/46ec4be51ca2e5782f744414c04a9fc8059ccde7/lib/platform-bible-utils/.vscode/settings.json#L57)):*
<details><summary><i>Previously, lyonsil (Matt Lyons) wrote…</i></summary><blockquote>

Same comment as other VS config file
</blockquote></details>

Fixed (in my next PR with a bunch of changes from our call the other day)
___
*[`lib/platform-bible-utils/src/document-combiner-engine.ts` line 7 at r1](https://reviewable.io/reviews/paranext/paranext-core/852#-NvJU4cp56xveg_Szjzv:-NvWwxbF1oBIDjB06RuC:byldtdu) ([raw file](https://github.com/paranext/paranext-core/blob/46ec4be51ca2e5782f744414c04a9fc8059ccde7/lib/platform-bible-utils/src/document-combiner-engine.ts#L7)):*
<details><summary><i>Previously, lyonsil (Matt Lyons) wrote…</i></summary><blockquote>

I don't think we want/intend to support combining JSON documents that aren't of the form `{ [key: string]: unknown }`, do we? What's the value of expanding this?
</blockquote></details>

I added array because the contributions for settings can be a settings group or an array of settings groups. I added the others because they constitute the rest of the technical definition of what json values can be and it just feels like it makes sense at this point to add them (see the new test I added as an example of why it feels kinda natural at least to me). I know we discussed some of the high-level point of this class before, so it probably would be good to discuss on a call further.

**Review by lyonsil — CHANGES_REQUESTED** [review]
> Reviewed 12 of 30 files at r1, 15 of 16 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/852)* status: 31 of 32 files reviewed, 6 unresolved discussions (waiting on @tjcouch-sil)

___
*[`lib/platform-bible-utils/src/settings.model.ts` line 6 at r1](https://reviewable.io/reviews/paranext/paranext-core/852#-NvXO4ST7GSOS99_zQrg:-NvXO4ST7GSOS99_zQrh:b-b19bb6) ([raw file](https://github.com/paranext/paranext-core/blob/46ec4be51ca2e5782f744414c04a9fc8059ccde7/lib/platform-bible-utils/src/settings.model.ts#L6)):*
> ```XML
> //----------------------------------------------------------------------------------------------
> 
> import { LocalizeKey, ReferencedItem } from 'menus.model';
> ```

Should these be promoted out of menus?
___
*[`lib/platform-bible-utils/src/settings.model.ts` line 65 at r2](https://reviewable.io/reviews/paranext/paranext-core/852#-NvXV9A5766z-H9OyUcP:-NvXV9A5766z-H9OyUcQ:bccuqqd) ([raw file](https://github.com/paranext/paranext-core/blob/2c5a7ab29e0b7336e6af980ac8260bba2f98b181/lib/platform-bible-utils/src/settings.model.ts#L65)):*
> ```XML
> export interface ModifierExtensionControlled {
>   [k: string]: unknown;
>   $ref?: undefined;
> ```

Is this really what we want to call this property? Is this some unexpected carryover from the original JSON schema?
___
*[`src/shared/utils/settings-document-combiner.ts` line 198 at r1](https://reviewable.io/reviews/paranext/paranext-core/852#-NvXSRF0EvA0oIGnWTKb:-NvXSRF0EvA0oIGnWTKc:bruvurv) ([raw file](https://github.com/paranext/paranext-core/blob/46ec4be51ca2e5782f744414c04a9fc8059ccde7/src/shared/utils/settings-document-combiner.ts#L198)):*
> ```XML
>     if (this.localizedOutputPromise) return this.localizedOutputPromise;
> 
>     if (!this.latestOutput) return undefined;
> ```

This line is a duplicate from a few lines above. It might have just been left by accident, but I'm not sure if you meant to do something else here instead.
___
*[`src/shared/utils/settings-document-combiner.ts` line 276 at r1](https://reviewable.io/reviews/paranext/paranext-core/852#-NvXTNLkBhpdpvAfMAFu:-NvXTNLkBhpdpvAfMAFv:buybf7s) ([raw file](https://github.com/paranext/paranext-core/blob/46ec4be51ca2e5782f744414c04a9fc8059ccde7/src/shared/utils/settings-document-combiner.ts#L276)):*
> ```XML
>   }
> 
>   // We have to implement abstract methods but don't need to use `this`
> ```

Is there value in overriding a method with an empty function? The base method doesn't do anything, either.
___
*[`src/shared/utils/settings-document-combiner.ts` line 286 at r2](https://reviewable.io/reviews/paranext/paranext-core/852#-NvXWHosAYZJz61yUmjW:-NvXWHosAYZJz61yUmjX:b-l7m6j7) ([raw file](https://github.com/paranext/paranext-core/blob/2c5a7ab29e0b7336e6af980ac8260bba2f98b181/src/shared/utils/settings-document-combiner.ts#L286)):*
> ```XML
>   // We don't need `this` on this override method
>   // eslint-disable-next-line class-methods-use-this
>   protected override transformFinalOutputBeforeValidation(
> ```

Similar to the previous function, this override does the exact same thing as the base. You can probably just remove it.

**Review by lyonsil — COMMENTED** [review]
> Reviewed 1 of 16 files at r2.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/852)* status: all files reviewed, 6 unresolved discussions (waiting on @tjcouch-sil)

**Review by tjcouch-sil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/852)* status: 23 of 32 files reviewed, 2 unresolved discussions (waiting on @lyonsil)

___
*[`lib/platform-bible-utils/src/settings.model.ts` line 6 at r1](https://reviewable.io/reviews/paranext/paranext-core/852#-NvXO4ST7GSOS99_zQrg:-NvXkiTyBVDOxJX3Tj3-:b-416zih) ([raw file](https://github.com/paranext/paranext-core/blob/46ec4be51ca2e5782f744414c04a9fc8059ccde7/lib/platform-bible-utils/src/settings.model.ts#L6)):*
<details><summary><i>Previously, lyonsil (Matt Lyons) wrote…</i></summary><blockquote>

Should these be promoted out of menus?
</blockquote></details>

We discussed and decided to leave them until we make the schema overhaul #748
___
*[`lib/platform-bible-utils/src/settings.model.ts` line 65 at r2](https://reviewable.io/reviews/paranext/paranext-core/852#-NvXV9A5766z-H9OyUcP:-NvXnoflChz476TX1OYT:b-sdf1ef) ([raw file](https://github.com/paranext/paranext-core/blob/2c5a7ab29e0b7336e6af980ac8260bba2f98b181/lib/platform-bible-utils/src/settings.model.ts#L65)):*
<details><summary><i>Previously, lyonsil (Matt Lyons) wrote…</i></summary><blockquote>

Is this really what we want to call this property? Is this some unexpected carryover from the original JSON schema?
</blockquote></details>

Changed to `platformType` since this isn't actually the literal field `$ref` from JSON schema but a field to indicate to us what type it is amongst our platform-provided types like `VerseRef` and `Color`. All this is future stuff.
___
*[`src/shared/utils/settings-document-combiner.ts` line 198 at r1](https://reviewable.io/reviews/paranext/paranext-core/852#-NvXSRF0EvA0oIGnWTKb:-NvXoEAI0mojHI8n2di0:b7vb2ah) ([raw file](https://github.com/paranext/paranext-core/blob/46ec4be51ca2e5782f744414c04a9fc8059ccde7/src/shared/utils/settings-document-combiner.ts#L198)):*
<details><summary><i>Previously, lyonsil (Matt Lyons) wrote…</i></summary><blockquote>

This line is a duplicate from a few lines above. It might have just been left by accident, but I'm not sure if you meant to do something else here instead.
</blockquote></details>

Yep, removed. Thanks!
___
*[`src/shared/utils/settings-document-combiner.ts` line 276 at r1](https://reviewable.io/reviews/paranext/paranext-core/852#-NvXTNLkBhpdpvAfMAFu:-NvXkxtWBJ6ehMj1DTUm:brx172j) ([raw file](https://github.com/paranext/paranext-core/blob/46ec4be51ca2e5782f744414c04a9fc8059ccde7/src/shared/utils/settings-document-combiner.ts#L276)):*
<details><summary><i>Previously, lyonsil (Matt Lyons) wrote…</i></summary><blockquote>

Is there value in overriding a method with an empty function? The base method doesn't do anything, either.
</blockquote></details>

Probably worth keeping in case we ever do decide to implement this schema validation.
___
*[`src/shared/utils/settings-document-combiner.ts` line 286 at r2](https://reviewable.io/reviews/paranext/paranext-core/852#-NvXWHosAYZJz61yUmjW:-NvXoTMu-DbYwBklF_6F:ba3dfob) ([raw file](https://github.com/paranext/paranext-core/blob/2c5a7ab29e0b7336e6af980ac8260bba2f98b181/src/shared/utils/settings-document-combiner.ts#L286)):*
<details><summary><i>Previously, lyonsil (Matt Lyons) wrote…</i></summary><blockquote>

Similar to the previous function, this override does the exact same thing as the base. You can probably just remove it.
</blockquote></details>

Removed
___
*[`lib/platform-bible-utils/src/document-combiner-engine.ts` line 7 at r1](https://reviewable.io/reviews/paranext/paranext-core/852#-NvJU4cp56xveg_Szjzv:-NvXm-u7AV-zxnPyFfcP:b-7lrzar) ([raw file](https://github.com/paranext/paranext-core/blob/46ec4be51ca2e5782f744414c04a9fc8059ccde7/lib/platform-bible-utils/src/document-combiner-engine.ts#L7)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

I added array because the contributions for settings can be a settings group or an array of settings groups. I added the others because they constitute the rest of the technical definition of what json values can be and it just feels like it makes sense at this point to add them (see the new test I added as an example of why it feels kinda natural at least to me). I know we discussed some of the high-level point of this class before, so it probably would be good to discuss on a call further.
</blockquote></details>

Removed the primitive data types and modified test as discussed.

**Pull request merged**
