### PR TITLE
Intl utility classes and functions

### PR DESCRIPTION
**Pull request by jolierabideau**
Not sure if `ordinalCompare()` belongs in `intl-util.ts` or `string-util.ts`?

This change is [Reviewable](https://reviewable.io/reviews/paranext/paranext-core/883)

### CODE REVIEW

**Review by irahopkinson — CHANGES_REQUESTED** [review]
:lgtm: with some minor questions

> Reviewed 17 of 17 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/883#-:-NwvNFgBBiGadl5xpMAm:bmlisjl)* status: all files reviewed, 5 unresolved discussions (waiting on @jolierabideau)

___
*[`lib/platform-bible-utils/src/intl-collator.ts` line 33 at r1](https://reviewable.io/reviews/paranext/paranext-core/883#-Nwv9bbm5D7cArPNHf85:-Nwv9bbm5D7cArPNHf86:b-l4y7wb) ([raw file](https://github.com/paranext/paranext-core/blob/ec0ea6d340e5336349b105fce624832b2a618a0c/lib/platform-bible-utils/src/intl-collator.ts#L33)):*
> ```XML
> }
> 
> export default Collator;
> ```

BTW you can just add `export default ` to the beginning of the class declaration (it's only for `const` that we need this separate export pattern). Here and in other files.
___
*[`lib/platform-bible-utils/src/intl-collator.test.ts` line 3 at r1](https://reviewable.io/reviews/paranext/paranext-core/883#-NwvD9-D639uCoO9XYJc:-NwvD9-D639uCoO9XYJd:b-w01y4k) ([raw file](https://github.com/paranext/paranext-core/blob/ec0ea6d340e5336349b105fce624832b2a618a0c/lib/platform-bible-utils/src/intl-collator.test.ts#L3)):*
> ```XML
> import Collator from './intl-collator';
> 
> const testCollator: Collator = new Collator('en-US');
> ```

BTW this is the same as `'en'` and with BCP-47 you use the shortest code possible but perhaps you are being explicit?



_Code quote:_
```XML
en-US
```
___
*[`lib/platform-bible-utils/src/intl-collator.test.ts` line 4 at r1](https://reviewable.io/reviews/paranext/paranext-core/883#-NwvBpnC9DQiA8tppj7a:-NwvBpnC9DQiA8tppj7b:b-lh2dum) ([raw file](https://github.com/paranext/paranext-core/blob/ec0ea6d340e5336349b105fce624832b2a618a0c/lib/platform-bible-utils/src/intl-collator.test.ts#L4)):*
> ```XML
> 
> const testCollator: Collator = new Collator('en-US');
> const STRING1 = 'z';
> ```

It might make it easier to read the tests if these consts are labelled something like `STRING_z` and `STRING_a` or `HIGHER_STRING` and `LOWER_STRING`.
___
*[`lib/platform-bible-utils/src/intl-date-time-format.ts` line 10 at r1](https://reviewable.io/reviews/paranext/paranext-core/883#-NwvE1oh29WdJHbYNVn1:-NwvE1oh29WdJHbYNVn2:b-1sfrd2) ([raw file](https://github.com/paranext/paranext-core/blob/ec0ea6d340e5336349b105fce624832b2a618a0c/lib/platform-bible-utils/src/intl-date-time-format.ts#L10)):*
> ```XML
> 
>   /**
>    * Formats a date according to the locale and formatting option fo this DateTimeFormat object
> ```

typo: for



_Code quote:_
```XML
fo
```
___
*[`lib/platform-bible-utils/src/intl-number-format.ts` line 12 at r1](https://reviewable.io/reviews/paranext/paranext-core/883#-NwvKNH1BTgVEFJ01R54:-NwvKNH1BTgVEFJ01R55:b30m8v2) ([raw file](https://github.com/paranext/paranext-core/blob/ec0ea6d340e5336349b105fce624832b2a618a0c/lib/platform-bible-utils/src/intl-number-format.ts#L12)):*
> ```XML
>    * Formats a number according to the locale and formatting options of this NumberFormat object
>    *
>    * @param value Number or BigIng to format
> ```

typo: BigInt



_Code quote:_
```XML
BigIng
```
___
*[`lib/platform-bible-utils/src/intl-util.test.ts` line 3 at r1](https://reviewable.io/reviews/paranext/paranext-core/883#-NwvMWXmAFK6sa0dgz9i:-NwvMWXmAFK6sa0dgz9j:bwsmdn4) ([raw file](https://github.com/paranext/paranext-core/blob/ec0ea6d340e5336349b105fce624832b2a618a0c/lib/platform-bible-utils/src/intl-util.test.ts#L3)):*
> ```XML
> import getCurrentLocale from './intl-util';
> 
> jest.mock('./intl-date-time-format', () => {
> ```

FYI good job setting these tests up.
___
*[`lib/platform-bible-utils/src/string-util.ts` line 196 at r1](https://reviewable.io/reviews/paranext/paranext-core/883#-Nwv8xjh2P6SUtHpbB5U:-Nwv8xjh2P6SUtHpbB5V:b15n61j) ([raw file](https://github.com/paranext/paranext-core/blob/ec0ea6d340e5336349b105fce624832b2a618a0c/lib/platform-bible-utils/src/string-util.ts#L196)):*
> ```XML
>  *   Positive value if string1 follows string2 in sorting order.
>  */
> export function ordinalCompare(
> ```

FYI FWIW, I think this belongs here.

**Review by jolierabideau — COMMENTED** [review]
Thanks for your review!

> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/883#-:-NwyjhHb7JG22DpU7cWA:b2iy6px)* status: all files reviewed, 4 unresolved discussions (waiting on @irahopkinson)

___
*[`lib/platform-bible-utils/src/intl-collator.test.ts` line 3 at r1](https://reviewable.io/reviews/paranext/paranext-core/883#-NwvD9-D639uCoO9XYJc:-NwyiCNR71H6-fgsqOR1:b-w206xm) ([raw file](https://github.com/paranext/paranext-core/blob/ec0ea6d340e5336349b105fce624832b2a618a0c/lib/platform-bible-utils/src/intl-collator.test.ts#L3)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

BTW this is the same as `'en'` and with BCP-47 you use the shortest code possible but perhaps you are being explicit?
</blockquote></details>

I figured it was pretty much the same, but I saw it in different examples and wasn't aware of the rule.
___
*[`lib/platform-bible-utils/src/intl-collator.test.ts` line 4 at r1](https://reviewable.io/reviews/paranext/paranext-core/883#-NwvBpnC9DQiA8tppj7a:-NwyidLd0GRBxcPBPkBU:b-5pm0nh) ([raw file](https://github.com/paranext/paranext-core/blob/ec0ea6d340e5336349b105fce624832b2a618a0c/lib/platform-bible-utils/src/intl-collator.test.ts#L4)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

It might make it easier to read the tests if these consts are labelled something like `STRING_z` and `STRING_a` or `HIGHER_STRING` and `LOWER_STRING`.
</blockquote></details>

That makes sense. I did STRING_Z because when I did STRING_z I got this error: `Identifier 'STRING\_a' is not in camel case.eslint[camelcase](https://eslint.org/docs/latest/rules/camelcase)`
___
*[`lib/platform-bible-utils/src/intl-date-time-format.ts` line 10 at r1](https://reviewable.io/reviews/paranext/paranext-core/883#-NwvE1oh29WdJHbYNVn1:-NwyjGCDEpuKLZxHwCtF:b-896fix) ([raw file](https://github.com/paranext/paranext-core/blob/ec0ea6d340e5336349b105fce624832b2a618a0c/lib/platform-bible-utils/src/intl-date-time-format.ts#L10)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

typo: for
</blockquote></details>

Done.
___
*[`lib/platform-bible-utils/src/intl-number-format.ts` line 12 at r1](https://reviewable.io/reviews/paranext/paranext-core/883#-NwvKNH1BTgVEFJ01R54:-NwyjM8Y5RZEtlo6zSrY:b-896fix) ([raw file](https://github.com/paranext/paranext-core/blob/ec0ea6d340e5336349b105fce624832b2a618a0c/lib/platform-bible-utils/src/intl-number-format.ts#L12)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

typo: BigInt
</blockquote></details>

Done.
___
*[`lib/platform-bible-utils/src/intl-util.test.ts` line 3 at r1](https://reviewable.io/reviews/paranext/paranext-core/883#-NwvMWXmAFK6sa0dgz9i:-NwyjMtd8aiC8G4Lc1ZA:b-guoso5) ([raw file](https://github.com/paranext/paranext-core/blob/ec0ea6d340e5336349b105fce624832b2a618a0c/lib/platform-bible-utils/src/intl-util.test.ts#L3)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

FYI good job setting these tests up.
</blockquote></details>

Thank you! I'm glad it's correct

**Review by lyonsil — APPROVED** [review]
:lgtm: I added a couple of non-blocking thoughts on tests.

> Reviewed 5 of 17 files at r1, 12 of 12 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/883#-:-NwzJmR73XcAS79oc56K:b-59uz7f)* status: all files reviewed, 6 unresolved discussions (waiting on @irahopkinson and @jolierabideau)

___
*[`lib/platform-bible-utils/src/intl-date-time-format.test.ts` line 3 at r2](https://reviewable.io/reviews/paranext/paranext-core/883#-NwzHAeE0DhsqSTGK38O:-NwzHAeE0DhsqSTGK38P:bom1o62) ([raw file](https://github.com/paranext/paranext-core/blob/ef55b8a709140507b55623e1434378490b1a8d62/lib/platform-bible-utils/src/intl-date-time-format.test.ts#L3)):*
> ```XML
> import DateTimeFormat from './intl-date-time-format';
> 
> const testDateTimeFormatter: DateTimeFormat = new DateTimeFormat('en');
> ```

It's interesting that the default here for `en` is the US-centric view on things. I just checked, and `en-GB` (and presumably other non-US centric views) would result in dates like `25/4/2024`. I'm not saying you need to add tests for both, but for the sake of clarify for our non-US co-workers it might be nice to put `en-US` here instead of `en`. I know Ira suggested the opposite for an earlier test, but I think for sorting all English-speaking countries sort alphabets the same way. Formatting is different.

I wonder what would happen if my computer was configured with a UK locale instead of a US locale. Would the code work the same just saying "en"? I've never tried something like that.
___
*[`lib/platform-bible-utils/src/intl-number-format.test.ts` line 3 at r2](https://reviewable.io/reviews/paranext/paranext-core/883#-NwzIayNBSUuAmG4cG0g:-NwzIayNBSUuAmG4cG0h:b-tqyppd) ([raw file](https://github.com/paranext/paranext-core/blob/ef55b8a709140507b55623e1434378490b1a8d62/lib/platform-bible-utils/src/intl-number-format.test.ts#L3)):*
> ```XML
> import NumberFormat from './intl-number-format';
> 
> const testNumberFormatter: NumberFormat = new NumberFormat('en');
> ```

Same thought as the date formatting tests. I believe some non-US, English speaking countries use different separators than us, like "654.321,987" for the start number below.

**Review by irahopkinson — APPROVED** [review]
:lgtm:

> Reviewed 12 of 12 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/883#-:-Nx-C6Hy1Y4Q_z0onfiP:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

___
*[`lib/platform-bible-utils/src/intl-date-time-format.test.ts` line 3 at r2](https://reviewable.io/reviews/paranext/paranext-core/883#-NwzHAeE0DhsqSTGK38O:-Nx-7zto1K6GheaLICMq:b-ddoomt) ([raw file](https://github.com/paranext/paranext-core/blob/ef55b8a709140507b55623e1434378490b1a8d62/lib/platform-bible-utils/src/intl-date-time-format.test.ts#L3)):*
<details><summary><i>Previously, lyonsil (Matt Lyons) wrote…</i></summary><blockquote>

It's interesting that the default here for `en` is the US-centric view on things. I just checked, and `en-GB` (and presumably other non-US centric views) would result in dates like `25/4/2024`. I'm not saying you need to add tests for both, but for the sake of clarify for our non-US co-workers it might be nice to put `en-US` here instead of `en`. I know Ira suggested the opposite for an earlier test, but I think for sorting all English-speaking countries sort alphabets the same way. Formatting is different.

I wonder what would happen if my computer was configured with a UK locale instead of a US locale. Would the code work the same just saying "en"? I've never tried something like that.
</blockquote></details>

In BCP-47, the `US` part of `en-US` is the region and since `en` is equivalent to `en-US` but not to `en-GB` (or any other `en-<region>`) the results between `en` and `en-GB` are different. My locale is `en-NZ` and the tests all pass for me. I also think it's important for everyone to learn that this is the case and that you are meant to use the shortest form.

It is curious that `en` is equivalent to `en-US` and not `en-GB` since the language came from GB but I think it is because US is the majority culture so we needed to make it simple for you guys :grin:.

**Pull request merged**
