### PR TITLE
Merge PSI functionality into PDPs

### PR DESCRIPTION
**Pull request by lyonsil**
This change is [Reviewable](https://reviewable.io/reviews/paranext/paranext-core/878)

### CODE REVIEW

**Review by irahopkinson — APPROVED** [review]
:lgtm: with a few minor questions

> Reviewed 62 of 62 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/878#-:-Nwg36Ow4XQVGef2yIJ0:b64m8xc)* status: all files reviewed, 4 unresolved discussions (waiting on @lyonsil)

___
*[`c-sharp/Projects/ParatextProjectDataProvider.cs` line 222 at r1](https://reviewable.io/reviews/paranext/paranext-core/878#-NwfxKcHC5zTmrdrz2Ln:-NwfxKcI4s_WgfvQ2Y5E:b-a0e3u1) ([raw file](https://github.com/paranext/paranext-core/blob/990c9a9d9adcbac21c6f447fbaf49eca48298ab0/c-sharp/Projects/ParatextProjectDataProvider.cs#L222)):*
> ```Smalltalk
>         string? errorMessage = null;
>         RunWithinLock(
>         WriteScope.AllSettingsFiles(),
> ```

BTW looks like an indenting issue here.
___
*[`extensions/src/hello-world/src/main.ts` line 185 at r1](https://reviewable.io/reviews/paranext/paranext-core/878#-NwfkHReEAImYG6LJkXO:-NwfkHReEAImYG6LJkXP:bhtb74f) ([raw file](https://github.com/paranext/paranext-core/blob/990c9a9d9adcbac21c6f447fbaf49eca48298ab0/extensions/src/hello-world/src/main.ts#L185)):*
> ```XML
>     'helloWorld',
>     helloWorldProjectDataProviderEngineFactory,
>     async () => {
> ```

BTW you can use the shorter return syntax, i.e. `async () => [],`.
___
*[`lib/platform-bible-utils/src/subset-checking.ts` line 41 at r1](https://reviewable.io/reviews/paranext/paranext-core/878#-NwfmVNS17xIXi3QfFf7:-NwfmVNS17xIXi3QfFf8:b-v7cbbr) ([raw file](https://github.com/paranext/paranext-core/blob/990c9a9d9adcbac21c6f447fbaf49eca48298ab0/lib/platform-bible-utils/src/subset-checking.ts#L41)):*
> ```XML
> 
>     // This only works with arrays of primitives.
>     // If someone cares about checking arrays of objects this needs updating.
> ```

BTW wondering if this should be included as a stated limitation in the TSDoc above?
___
*[`lib/platform-bible-utils/src/subset-checking.test.ts` line 43 at r1](https://reviewable.io/reviews/paranext/paranext-core/878#-NwfpJCzB16a4RUVDYS9:-NwfpJCzB16a4RUVDYSA:bv73xz6) ([raw file](https://github.com/paranext/paranext-core/blob/990c9a9d9adcbac21c6f447fbaf49eca48298ab0/lib/platform-bible-utils/src/subset-checking.test.ts#L43)):*
> ```XML
>   expect(isSubset(objC, objA)).toBeFalsy();
>   expect(isSubset(objA, objB)).toBeTruthy();
>   expect(isSubset(objB, objA)).toBeFalsy();
> ```

BTW wondering why we have a duplicate of the first 2 tests at the end? If it's intentional how about adding a comment?
___
*[`src/shared/services/project-data-provider.service.ts` line 138 at r1](https://reviewable.io/reviews/paranext/paranext-core/878#-NwfsR-mEchbwbfulUf8:-NwfsR-qDcooKsV0eG4d:b-dtubyd) ([raw file](https://github.com/paranext/paranext-core/blob/990c9a9d9adcbac21c6f447fbaf49eca48298ab0/src/shared/services/project-data-provider.service.ts#L138)):*
> ```XML
>     factoryId,
>     factory,
>     PDP_FACTORY_OBJECT_TYPE,
> ```

FYI thanks for removing the magic string.

**Review by lyonsil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/878)* status: 55 of 62 files reviewed, all discussions resolved (waiting on @irahopkinson)

___
*[`c-sharp/Projects/ParatextProjectDataProvider.cs` line 222 at r1](https://reviewable.io/reviews/paranext/paranext-core/878#-NwfxKcHC5zTmrdrz2Ln:-NwjMFBmESWfOqcJiu-7:b-1niwv0) ([raw file](https://github.com/paranext/paranext-core/blob/990c9a9d9adcbac21c6f447fbaf49eca48298ab0/c-sharp/Projects/ParatextProjectDataProvider.cs#L222)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

BTW looks like an indenting issue here.
</blockquote></details>

Indeed. Something about this confuses the auto formatting and it didn't adjust the indent. Fixed.
___
*[`extensions/src/hello-world/src/main.ts` line 185 at r1](https://reviewable.io/reviews/paranext/paranext-core/878#-NwfkHReEAImYG6LJkXO:-NwjMoOq033JdwmSR8JG:b-t00mzi) ([raw file](https://github.com/paranext/paranext-core/blob/990c9a9d9adcbac21c6f447fbaf49eca48298ab0/extensions/src/hello-world/src/main.ts#L185)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

BTW you can use the shorter return syntax, i.e. `async () => [],`.
</blockquote></details>

Nice, thanks for that!
___
*[`lib/platform-bible-utils/src/subset-checking.ts` line 41 at r1](https://reviewable.io/reviews/paranext/paranext-core/878#-NwfmVNS17xIXi3QfFf7:-NwjNSlA4BjTbuJmmOXa:b-vzst0j) ([raw file](https://github.com/paranext/paranext-core/blob/990c9a9d9adcbac21c6f447fbaf49eca48298ab0/lib/platform-bible-utils/src/subset-checking.ts#L41)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

BTW wondering if this should be included as a stated limitation in the TSDoc above?
</blockquote></details>

Yes, that is probably good to call out. Updated.
___
*[`lib/platform-bible-utils/src/subset-checking.test.ts` line 43 at r1](https://reviewable.io/reviews/paranext/paranext-core/878#-NwfpJCzB16a4RUVDYS9:-NwjOeNC2aqfqSNfladO:b-la1zo5) ([raw file](https://github.com/paranext/paranext-core/blob/990c9a9d9adcbac21c6f447fbaf49eca48298ab0/lib/platform-bible-utils/src/subset-checking.test.ts#L43)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

BTW wondering why we have a duplicate of the first 2 tests at the end? If it's intentional how about adding a comment?
</blockquote></details>

Good eye. It was not intentional.

**Review by irahopkinson — APPROVED** [review]
:lgtm:

> Reviewed 7 of 7 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/878#-:-Nwl40U3ASsSF60FifvW:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Review by tjcouch-sil — COMMENTED** [review]
Left some comments here about smaller details that would be good to discuss a bit or quick fix :) thanks!

> Reviewed 55 of 62 files at r1, 7 of 7 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/878#-:-NxpjVTaEItGM1RIZmHv:bg49s1o)* status: all files reviewed, 8 unresolved discussions (waiting on @lyonsil)

___
*[`lib/platform-bible-utils/src/subset-checking.ts` line 6 at r2](https://reviewable.io/reviews/paranext/paranext-core/878#-NxoK0Yv3tRuLTjO9vdZ:-NxoK0Yv3tRuLTjO9vd_:b-mlpl08) ([raw file](https://github.com/paranext/paranext-core/blob/9c75b5aec8516c2ee2dfe48eb1a40bf1b9aae9f4/lib/platform-bible-utils/src/subset-checking.ts#L6)):*
> ```XML
>  * Check if one object is a subset of the other object. "Subset" means that all properties of one
>  * object are present in to the other object, and if they are present that all values of those
>  * properties are deeply equal.
> ```

It is probably worth mentioning that sub-objects are also compared as subsets and maybe adding this detail in the example. I had to read the code to know whether sub-objects were deeply compared or subset-compared.
___
*[`src/declarations/papi-shared-types.ts` line 177 at r2](https://reviewable.io/reviews/paranext/paranext-core/878#-NxoKYeG3DwBAIyZBY0B:-NxoKYeG3DwBAIyZBY0C:b-vsx15v) ([raw file](https://github.com/paranext/paranext-core/blob/53b2534e32e6a40144c6f057de835f58e6cfadac/src/declarations/papi-shared-types.ts#L177)):*
> ```XML
>      * Set the value of the specified project setting on this project.
>      *
>      * Note for implementing: In most cases, `setSetting` should just pass the call through to the
> ```

I think these three removed notes for implementing should be replaced by the notes for implementing that were on the PSI methods with the same names since these methods are now taking the place of and requirements of the respective PSI methods.
___
*[`src/declarations/papi-shared-types.ts` line 395 at r2](https://reviewable.io/reviews/paranext/paranext-core/878#-NxpEGHo43OyoXE-POV6:-NxpEGHo43OyoXE-POV7:b-1v7ivw) ([raw file](https://github.com/paranext/paranext-core/blob/53b2534e32e6a40144c6f057de835f58e6cfadac/src/declarations/papi-shared-types.ts#L395)):*
> ```XML
>        * Set the value of the specified project setting on this project.
>        *
>        * Note for implementing: `setSetting` must call `papi.projectSettings.isValid` before
> ```

I think these removed "note for implementing" comments on each of these are worth moving over to the appropriate comment in `WithProjectDataProviderEngineSettingMethods`
___
*[`src/declarations/papi-shared-types.ts` line 477 at r2](https://reviewable.io/reviews/paranext/paranext-core/878#-NxoKvRG1U9lH5zQdXSP:-NxoKvRG1U9lH5zQdXSQ:b-75cfpu) ([raw file](https://github.com/paranext/paranext-core/blob/53b2534e32e6a40144c6f057de835f58e6cfadac/src/declarations/papi-shared-types.ts#L477)):*
> ```XML
>    * Interpreters.
>    *
>    * WARNING: Each Project Storage Interpreter **must** fulfill certain requirements for its
> ```

I think this removed note should move to `ProjectDataProviders`
___
*[`src/shared/models/project-data-provider-engine.model.ts` line 75 at r2](https://reviewable.io/reviews/paranext/paranext-core/878#-NxpcEorCHjsR6Q3a4iA:-NxpcEorCHjsR6Q3a4iB:ba8kvvo) ([raw file](https://github.com/paranext/paranext-core/blob/53b2534e32e6a40144c6f057de835f58e6cfadac/src/shared/models/project-data-provider-engine.model.ts#L75)):*
> ```XML
>  * provided, so it is not necessary to provide one in order to call `this.notifyUpdate`. However,
>  * TypeScript does not understand that papi will create one as you are writing your Project Data
>  * Provider Engine, so you can avoid type errors with one of the following options:
> ```

I think the information here regarding extending the class that provides `notifyUpdate` is still relevant (whether or not we keep `ProjectDataProviderEngine` - see comments below). Can we keep the options in the new comment? Agreed that mention of the PSI and default settings implementations should be removed.
___
*[`src/shared/models/project-data-provider-engine.model.ts` line 126 at r2](https://reviewable.io/reviews/paranext/paranext-core/878#-NxocTU7BEpcifNRDNFo:-NxocTU7BEpcifNRDNFp:b-7fbg50) ([raw file](https://github.com/paranext/paranext-core/blob/53b2534e32e6a40144c6f057de835f58e6cfadac/src/shared/models/project-data-provider-engine.model.ts#L126)):*
> ```XML
>  * @see {@link IProjectDataProviderEngine} for more information on extending this class.
>  */
> export abstract class ProjectDataProviderEngine<ProjectType extends ProjectTypes>
> ```

Wouldn't we want this here (and on the papi backend) still (but without the `implements` stuff, I suppose)? That way, we can include `notifyUpdate` and keep the ability to emit `Setting` updates according to TypeScript without making users list this weird in-line `Setting` `DataProviderDataType`. It also is a clearer inheritance pattern (My PDPE inherits from papi's PDPE, not papi's DPE). And if we do ever end up adding any method implementations that aren't in `DataProviderEngine`, people are already inheriting from it :)

The following image illustrates what I'm talking about: Intellisense doesn't see the `'Setting'` option because it isn't actually in IPDP's mandatory data types (though the associated settings are required on the interface):


___
*[`src/shared/models/project-data-provider.model.ts` line 37 at r2](https://reviewable.io/reviews/paranext/paranext-core/878#-NxofNf73d_1wX7KAlRt:-NxofNf73d_1wX7KAlRu:bu5klu2) ([raw file](https://github.com/paranext/paranext-core/blob/53b2534e32e6a40144c6f057de835f58e6cfadac/src/shared/models/project-data-provider.model.ts#L37)):*
> ```XML
>  * properly support project settings.
>  *
>  * In most cases, the Project Data Provider only needs to pass the setting calls through to the
> ```

I think we should move the requirements from the old PSIDataTypes explanation of Settings methods here since these PDP Settings methods now have those requirements.
___
*[`src/shared/models/project-storage-interpreter.model.ts` line 94 at r2](https://reviewable.io/reviews/paranext/paranext-core/878#-NxpDqpl4EZ43PhWgkTv:-NxpDqpl4EZ43PhWgkTw:b-k0599n) ([raw file](https://github.com/paranext/paranext-core/blob/53b2534e32e6a40144c6f057de835f58e6cfadac/src/shared/models/project-storage-interpreter.model.ts#L94)):*
> ```XML
>  * ```
>  *
>  * WARNING: Each Project Storage Interpreter **needs** to fulfill the following requirements for its
> ```

I think these comments are worth moving over to the appropriate documentation in PDP mandatory data types

**Review by tjcouch-sil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/878)* status: all files reviewed, 9 unresolved discussions (waiting on @lyonsil)

___
*[`src/shared/services/project-data-provider.service.ts` line 153 at r2](https://reviewable.io/reviews/paranext/paranext-core/878#-Nxptji19Q0rvzPaTMrU:-Nxptji19Q0rvzPaTMrV:bzieziu) ([raw file](https://github.com/paranext/paranext-core/blob/9c75b5aec8516c2ee2dfe48eb1a40bf1b9aae9f4/src/shared/services/project-data-provider.service.ts#L153)):*
> ```XML
>  * ```
>  *
>  * @param projectType Indicates what you expect the `projectType` to be for the project with the
> ```

`projectType` is now used quite significantly instead of just being a sanity check. I think this parameter description needs to be rewritten to reflect its new meaning

**Pull request merged**
