### PR TITLE
Fix race condition in data provider registration

### PR DESCRIPTION
**Pull request by lyonsil**
This change is [Reviewable](https://reviewable.io/reviews/paranext/paranext-core/204)

### CODE REVIEW

**Review by irahopkinson — COMMENTED** [review]
> Reviewed 6 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/204)* status: 6 of 8 files reviewed, 1 unresolved discussion (waiting on @lyonsil)

___
*[`cspell.json` line 45 at r1](https://reviewable.io/reviews/paranext/paranext-core/204#-NWBFEM-5xv3N1AxWypX:-NWBFEM-5xv3N1AxWypY:b-cu5zlt) ([raw file](https://github.com/paranext/paranext-core/blob/6ba013c8a70a3e567d8e354ec44e9b7b2ac862fb/cspell.json#L45)):*
> ```JSON
>     "unsubscriber",
>     "unsubscribers",
>     "waitable"
> ```

Err... this word doesn't appear in our code. Did you use it and then remove it?

**Review by tjcouch-sil — APPROVED** [review]
Interesting solution! Thanks for working hard on this. 
:lgtm:

> Reviewed 8 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/204#-:-NWD2hWM80ahge-_Y6rr:b5oia6s)* status: all files reviewed, 1 unresolved discussion (waiting on @lyonsil)

**Review by lyonsil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/204)* status: 6 of 8 files reviewed, all discussions resolved (waiting on @irahopkinson and @tjcouch-sil)

___
*[`cspell.json` line 45 at r1](https://reviewable.io/reviews/paranext/paranext-core/204#-NWBFEM-5xv3N1AxWypX:-NWDLDyt-8E-LGzObmf0:bb6un1j) ([raw file](https://github.com/paranext/paranext-core/blob/6ba013c8a70a3e567d8e354ec44e9b7b2ac862fb/cspell.json#L45)):*
<details><summary><i>Previously, lyonsil wrote…</i></summary><blockquote>

Ah - in an earlier revision I called the new class I added "WaitableVariable".  I changed it later to "AsyncVariable".  "Waitable" is a real computing term that cspell doesn't seem to know about.  I can remove it, though, since we're not trying to create a full computing lexicon here. :smile:
</blockquote></details>

Done

**Review by tjcouch-sil — APPROVED** [review]
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/204)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @lyonsil)

**Review by irahopkinson — COMMENTED** [review]
Yep, looking good, with some minor questions.

> Reviewed 1 of 8 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/204#-:-NWFAe18DKVcD18WzPk2:b-nw6qbl)* status: all files reviewed, 6 unresolved discussions (waiting on @lyonsil)

___
*[`src/shared/utils/async-variable.ts` line 41 at r2](https://reviewable.io/reviews/paranext/paranext-core/204#-NWF7cGJ2euQr1WTE4X9:-NWF7cGJ2euQr1WTE4XA:b-5sau3y) ([raw file](https://github.com/paranext/paranext-core/blob/7dc5ebf4d646cfb0d18cb206ca35772759d573d1/src/shared/utils/async-variable.ts#L41)):*
> ```XML
>    * @returns the promise for the value to be set
>    */
>   public async getPromise(): Promise<T> {
> ```

BTW This function is not `async` so remove it.
___
*[`src/shared/utils/async-variable.ts` line 41 at r2](https://reviewable.io/reviews/paranext/paranext-core/204#-NWF7ssp3W3Mk9mJSJPA:-NWF7ssp3W3Mk9mJSJPB:b9kqs3x) ([raw file](https://github.com/paranext/paranext-core/blob/7dc5ebf4d646cfb0d18cb206ca35772759d573d1/src/shared/utils/async-variable.ts#L41)):*
> ```XML
>    * @returns the promise for the value to be set
>    */
>   public async getPromise(): Promise<T> {
> ```

BTW Any reason for not using a getter here? I.e.:
```
  public get promise(): Promise<T> {
    return this.promiseToValue;
  }
```
___
*[`src/shared/utils/async-variable.ts` line 52 at r2](https://reviewable.io/reviews/paranext/paranext-core/204#-NWF9lWE8FnSNxnsBW71:-NWF9lWE8FnSNxnsBW72:b-vh4x4y) ([raw file](https://github.com/paranext/paranext-core/blob/7dc5ebf4d646cfb0d18cb206ca35772759d573d1/src/shared/utils/async-variable.ts#L52)):*
> ```XML
>   public resolveToValue(value: T, throwIfAlreadySettled: boolean = false): void {
>     if (this.resolver) {
>       logger.debug(`${this.variableName} is being resolved now`);
> ```

I would log this after the 2 calls below (and change the message) to reduce the chance of race conditions.
___
*[`src/shared/utils/async-variable.ts` line 68 at r2](https://reviewable.io/reviews/paranext/paranext-core/204#-NWFA0dkAPP8UjXVsyrt:-NWFA0dkAPP8UjXVsyru:b-vh4x4y) ([raw file](https://github.com/paranext/paranext-core/blob/7dc5ebf4d646cfb0d18cb206ca35772759d573d1/src/shared/utils/async-variable.ts#L68)):*
> ```XML
>   public rejectWithReason(reason: string, throwIfAlreadySettled: boolean = false): void {
>     if (this.rejecter) {
>       logger.debug(`${this.variableName} is being rejected now`);
> ```

I would log this after the 2 calls below (and change the message) to reduce the chance of race conditions.
___
*[`src/shared/utils/async-variable.ts` line 81 at r2](https://reviewable.io/reviews/paranext/paranext-core/204#-NWF8fvuE5TlbyW4lQzt:-NWF8fvv5mSNcKoD_pMg:b8oyn7h) ([raw file](https://github.com/paranext/paranext-core/blob/7dc5ebf4d646cfb0d18cb206ca35772759d573d1/src/shared/utils/async-variable.ts#L81)):*
> ```XML
>    * @returns whether the variable was already resolved or rejected
>    */
>   public hasSettled(): boolean {
> ```

BTW I would also make this a getter.
___
*[`src/shared/utils/async-variable.test.ts` line 7 at r2](https://reviewable.io/reviews/paranext/paranext-core/204#-NWFAI1r8V4_piQN-VGH:-NWFAI1r8V4_piQN-VGI:br3kuo6) ([raw file](https://github.com/paranext/paranext-core/blob/7dc5ebf4d646cfb0d18cb206ca35772759d573d1/src/shared/utils/async-variable.test.ts#L7)):*
> ```XML
>   const TEST_VALUE: string = 'A1B2C3';
>   const testVariable: AsyncVariable<string> = new AsyncVariable<string>(VARIABLE_NAME);
>   (async () => {
> ```

I feel like you could remove some of the complexity here (2x async self calling functions)  by making the `test` arrow function to be `aysnc`, however that is only a guess.

**Review by lyonsil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/204)* status: all files reviewed, 3 unresolved discussions (waiting on @irahopkinson and @lyonsil)

___
*[`src/shared/utils/async-variable.ts` line 41 at r2](https://reviewable.io/reviews/paranext/paranext-core/204#-NWF7cGJ2euQr1WTE4X9:-NWFJiYW9O49Wb2QmYS_:b-dmsyjh) ([raw file](https://github.com/paranext/paranext-core/blob/7dc5ebf4d646cfb0d18cb206ca35772759d573d1/src/shared/utils/async-variable.ts#L41)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

BTW This function is not `async` so remove it.
</blockquote></details>

Good point - done
___
*[`src/shared/utils/async-variable.ts` line 41 at r2](https://reviewable.io/reviews/paranext/paranext-core/204#-NWF7ssp3W3Mk9mJSJPA:-NWFN8Jl-s6zqAajNgUN:b-mbtunj) ([raw file](https://github.com/paranext/paranext-core/blob/7dc5ebf4d646cfb0d18cb206ca35772759d573d1/src/shared/utils/async-variable.ts#L41)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

BTW Any reason for not using a getter here? I.e.:
```
  public get promise(): Promise<T> {
    return this.promiseToValue;
  }
```
</blockquote></details>

ok - changed to a getter
___
*[`src/shared/utils/async-variable.ts` line 52 at r2](https://reviewable.io/reviews/paranext/paranext-core/204#-NWF9lWE8FnSNxnsBW71:-NWFJq4-7qmVpUXlteXV:buhkt1i) ([raw file](https://github.com/paranext/paranext-core/blob/7dc5ebf4d646cfb0d18cb206ca35772759d573d1/src/shared/utils/async-variable.ts#L52)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

I would log this after the 2 calls below (and change the message) to reduce the chance of race conditions.
</blockquote></details>

I put the log message where I did because if I were debugging something related to this, I'd want to find the "is being resolved now" message and look right after that to see what happens.  If I put the message later, then if something went wrong with the code that was waiting on the promise, the debug message might never print.  I assume nothing really latency sensitive would want to write code using one of these.  Instead this class provides a clear synchronization mechanism between tasks in a way that avoids polling.
___
*[`src/shared/utils/async-variable.ts` line 68 at r2](https://reviewable.io/reviews/paranext/paranext-core/204#-NWFA0dkAPP8UjXVsyrt:-NWFKsUV89zWbw14ke0L:b-ya81ng) ([raw file](https://github.com/paranext/paranext-core/blob/7dc5ebf4d646cfb0d18cb206ca35772759d573d1/src/shared/utils/async-variable.ts#L68)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

I would log this after the 2 calls below (and change the message) to reduce the chance of race conditions.
</blockquote></details>

Same as above
___
*[`src/shared/utils/async-variable.ts` line 81 at r2](https://reviewable.io/reviews/paranext/paranext-core/204#-NWF8fvuE5TlbyW4lQzt:-NWFN48ZAm6TKC-ZEWRi:b-mbtunj) ([raw file](https://github.com/paranext/paranext-core/blob/7dc5ebf4d646cfb0d18cb206ca35772759d573d1/src/shared/utils/async-variable.ts#L81)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

BTW I would also make this a getter.
</blockquote></details>

ok - changed to a getter
___
*[`src/shared/utils/async-variable.test.ts` line 7 at r2](https://reviewable.io/reviews/paranext/paranext-core/204#-NWFAI1r8V4_piQN-VGH:-NWFLHixB21fC7gl0t4F:b-ojiyov) ([raw file](https://github.com/paranext/paranext-core/blob/7dc5ebf4d646cfb0d18cb206ca35772759d573d1/src/shared/utils/async-variable.test.ts#L7)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

I feel like you could remove some of the complexity here (2x async self calling functions)  by making the `test` arrow function to be `aysnc`, however that is only a guess.
</blockquote></details>

I thought the expected way the new class would be used is clear the way this test is currently written.  Can you provide a code snippet of how you think it would be clearer to demonstrate how to use it?  I'm not sure I follow what you have in mind.

**Review by irahopkinson — COMMENTED** [review]
> Reviewed 5 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/204)* status: all files reviewed, 1 unresolved discussion (waiting on @lyonsil)

___
*[`src/shared/utils/async-variable.ts` line 81 at r2](https://reviewable.io/reviews/paranext/paranext-core/204#-NWF8fvuE5TlbyW4lQzt:-NWFQBG8831NKgBJsJpD:bguz51y) ([raw file](https://github.com/paranext/paranext-core/blob/7dc5ebf4d646cfb0d18cb206ca35772759d573d1/src/shared/utils/async-variable.ts#L81)):*
<details><summary><i>Previously, lyonsil (Matt Lyons) wrote…</i></summary><blockquote>

ok - changed to a getter
</blockquote></details>

Great. To follow our boolean naming conventions leave the name as `hasSettled`.
___
*[`src/shared/utils/async-variable.test.ts` line 7 at r2](https://reviewable.io/reviews/paranext/paranext-core/204#-NWFAI1r8V4_piQN-VGH:-NWFSN7w-eeYQq2_0uMw:bv2mbot) ([raw file](https://github.com/paranext/paranext-core/blob/7dc5ebf4d646cfb0d18cb206ca35772759d573d1/src/shared/utils/async-variable.test.ts#L7)):*
<details><summary><i>Previously, lyonsil (Matt Lyons) wrote…</i></summary><blockquote>

I thought the expected way the new class would be used is clear the way this test is currently written.  Can you provide a code snippet of how you think it would be clearer to demonstrate how to use it?  I'm not sure I follow what you have in mind.
</blockquote></details>

Like I said, I was only guessing, so I thought I'd better try it myself since I opened my big mouth :). BTW normally tests are in 3 parts: setup; SUT; checks. These 3 are separated below with new lines.
```typescript
test('wait on other async tasks to set and notify variables', () => {
  const VARIABLE_NAME: string = 'abc';
  const TEST_VALUE: string = 'A1B2C3';
  const testVariable: AsyncVariable<string> = new AsyncVariable<string>(VARIABLE_NAME);
  (async () => {
    await expect(testVariable.promise).resolves.toBe(TEST_VALUE);
  })();
  expect(testVariable.settled).toBeFalsy();

  testVariable.resolveToValue(TEST_VALUE);

  expect(testVariable.settled).toBeTruthy();
});
```

**Review by lyonsil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/204)* status: 5 of 8 files reviewed, all discussions resolved (waiting on @irahopkinson)

___
*[`src/shared/utils/async-variable.ts` line 81 at r2](https://reviewable.io/reviews/paranext/paranext-core/204#-NWF8fvuE5TlbyW4lQzt:-NWFTobK8t8HmMLXKXb3:bb6un1j) ([raw file](https://github.com/paranext/paranext-core/blob/7dc5ebf4d646cfb0d18cb206ca35772759d573d1/src/shared/utils/async-variable.ts#L81)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

Great. To follow our boolean naming conventions leave the name as `hasSettled`.
</blockquote></details>

Done
___
*[`src/shared/utils/async-variable.test.ts` line 7 at r2](https://reviewable.io/reviews/paranext/paranext-core/204#-NWFAI1r8V4_piQN-VGH:-NWFUGXe6_I0vr4b4kCf:b-qonwrc) ([raw file](https://github.com/paranext/paranext-core/blob/7dc5ebf4d646cfb0d18cb206ca35772759d573d1/src/shared/utils/async-variable.test.ts#L7)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

Like I said, I was only guessing, so I thought I'd better try it myself since I opened my big mouth :). BTW normally tests are in 3 parts: setup; SUT; checks. These 3 are separated below with new lines.
```typescript
test('wait on other async tasks to set and notify variables', () => {
  const VARIABLE_NAME: string = 'abc';
  const TEST_VALUE: string = 'A1B2C3';
  const testVariable: AsyncVariable<string> = new AsyncVariable<string>(VARIABLE_NAME);
  (async () => {
    await expect(testVariable.promise).resolves.toBe(TEST_VALUE);
  })();
  expect(testVariable.settled).toBeFalsy();

  testVariable.resolveToValue(TEST_VALUE);

  expect(testVariable.settled).toBeTruthy();
});
```
</blockquote></details>

I pulled the 3 lines out of the async function as you did in your snippet.

In this test, it is important that all of the `expect` lines are correct.  There is a series of steps being followed, and all checks can't be held to the end of the test.

I consider tests to be 2 things:
1) Verification that code is working as expected, and
2) A form of "live documentation" for maintainers and maybe users.

Sometimes I've found that if one is stick tightly to some testing rules (e.g., no more than 1 assert/expect/validation per test), it requires creating so many different tests with similar code that the tests cease to be as useful of "live documentation."  In cases like this, I think it's helpful to be able to assert/expect/validate/etc. a few related things in a single test so that you aren't repeating the same concepts/steps in multiple tests.

I don't think you're suggesting that I break up this test into multiple parts, but I think perhaps you and I are starting from slightly different places.  That's why I laid out my thoughts in more detail here.

**Review by lyonsil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/204)* status: 7 of 8 files reviewed, all discussions resolved (waiting on @irahopkinson)

___
*[`src/shared/utils/async-variable.test.ts` line 22 at r4](https://reviewable.io/reviews/paranext/paranext-core/204#-NWFXgQNBmIVP_TfepOQ:-NWFYTIGDoqxzaSK6O3i:b-hcmbxc) ([raw file](https://github.com/paranext/paranext-core/blob/b79620fdda236bd1b7028276987653bd5d6140de/src/shared/utils/async-variable.test.ts#L22)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

BTW can remove this self-calling `async` also.
</blockquote></details>

yep, good point

**Review by irahopkinson — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/204)* status: 7 of 8 files reviewed, all discussions resolved (waiting on @lyonsil)

___
*[`src/shared/utils/async-variable.test.ts` line 7 at r2](https://reviewable.io/reviews/paranext/paranext-core/204#-NWFAI1r8V4_piQN-VGH:-NWFYRak6QwQG_ugWD90:b-8puc1v) ([raw file](https://github.com/paranext/paranext-core/blob/7dc5ebf4d646cfb0d18cb206ca35772759d573d1/src/shared/utils/async-variable.test.ts#L7)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

I agree with everything you said here.
</blockquote></details>

I was just saying it's helpful to mark the SUT (software under test) in some way. New lines like I did can do it - a comment would also work:
```typescript
// SUT
testVariable.resolveToValue(TEST\_VALUE);
```

**Review by irahopkinson — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/204#-:-NWFZF84BiwcKhD0FTEp:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @lyonsil)

**Comment by irahopkinson** [comment]
*[`src/shared/utils/async-variable.test.ts` line 7 at r2](https://reviewable.io/reviews/paranext/paranext-core/204#-NWFAI1r8V4_piQN-VGH:-NWFz7gsEkj7VeS9eaL0:bh4tqmf) ([raw file](https://github.com/paranext/paranext-core/blob/7dc5ebf4d646cfb0d18cb206ca35772759d573d1/src/shared/utils/async-variable.test.ts#L7)):*
<details><summary><i>Previously, lyonsil (Matt Lyons) wrote…</i></summary><blockquote>

Well, this is also being tested:
```
await expect(testVariable.promise).resolves.toBe(TEST\_VALUE);
```

Is there a pattern the team is trying to follow to call out things like this?  I don't remember ever seeing something like this in tests in the past (here or elsewhere).

Now that I look back at `papi-util.test.ts`, I see there are extra spaces there that I didn't understand.  Perhaps that is what you had in mind, but I didn't realize that until now.

Perhaps we should have a section on tests in the style guide and review it as a group?
</blockquote></details>

To me that is not the SUT call, it's a check (expect to resolve) that happens at the end but is actually setup at the beginning in the setup section to check at the end.

Yes, adding a section in the style guide would be a good idea.

**Pull request merged**
