### PR TITLE
Add multiselect to combobox

### PR DESCRIPTION
**Pull request by rolfheij-sil**
- - -
This change is [Reviewable](https://reviewable.io/reviews/paranext/paranext-core/1325)

### CODE REVIEW

**Comment by Sebastian-ubs** [comment]
*[`lib/platform-bible-react/src/components/basics/combo-box.component.tsx` line 71 at r1](https://reviewable.io/reviews/paranext/paranext-core/1325#-OCE2GwqB9NmjOVNseJQ:-OCE2GwqB9NmjOVNseJR:b-5070v7) ([raw file](https://github.com/paranext/paranext-core/blob/6289f625d1672518ef7602f2436f38ec8c790506/lib/platform-bible-react/src/components/basics/combo-box.component.tsx#L71)):*
> ```XML
>   if (Array.isArray(value)) {
>     if (value.length === 0) return buttonPlaceholder;
>     return value.map((entry) => getOptionLabel(entry)).join(', ');
> ```

In addition to the concatenation of the value (that will soon run out of space), we need another functional parameter that will define the label based on the array input (if provided). Alternatively buttonPlaceholder could be made a function that takes the value as input.

**Comment by jolierabideau** [comment]
Thanks Rolf, this is super useful! Just curious if the UX design for `ComboBox` is that they are always multi-select and we should use a different component like `Select` in other places? I'm working on the new settings design and need a `Dropdown` for the projects that is searchable but not multi-select. I was imagining we could add flags to the `ComboBox` props, and put different functionality like multi-select and clearable behind them.

**Review by Sebastian-ubs — COMMENTED** [review]
Your changes looks good.

I am just wondering if this is the right component to use, or if we need a different filter component that re-assembles the popover and trigger separately.
As in the mockups I can see elements that look more like a shadcn [dropdown menu](https://ui.shadcn.com/docs/components/dropdown-menu).

the popover having a header and a button at the end

hierarchy

categories / sections to separate the list + using a simple button as trigger


> Reviewed 5 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/1325#-:-OCE4VXk2ti6-YfTuXZf:be0qctm)* status: 5 of 7 files reviewed, 1 unresolved discussion (waiting on @rolfheij-sil)

**Review by rolfheij-sil — COMMENTED** [review]
@jolierabideau Thanks! :) I though about adding a `isMultiSelect` bool or something to the combobox, but I figured that when you assign an array to the `value` prop, you want multiselect, and if you assign a single value to it, you don't want multiselect. I don't know what UX wants here. For what you need, you could just use the ComboBox with a non-array as the `value`, right?

@Sebastian-ubs Thanks :) For the first two of your screenshots it seems reasonable to use the dropdown menu component, but for the last one (and the `Type` menu which is very similar in design) I think this combobox is a good candidate.

> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/1325#-:-OCEVNf_6MFAYpQTlKuI:bryy2ja)* status: 5 of 7 files reviewed, 2 unresolved discussions (waiting on @Sebastian-ubs)

___
*[`lib/platform-bible-react/src/components/basics/combo-box.component.tsx` line 71 at r1](https://reviewable.io/reviews/paranext/paranext-core/1325#-OCE2GwqB9NmjOVNseJQ:-OCEVAgbBVWpcS_HhL1e:b-wr2bi7) ([raw file](https://github.com/paranext/paranext-core/blob/6289f625d1672518ef7602f2436f38ec8c790506/lib/platform-bible-react/src/components/basics/combo-box.component.tsx#L71)):*
<details><summary><i>Previously, Sebastian-ubs wrote…</i></summary><blockquote>

In addition to the concatenation of the value (that will soon run out of space), we need another functional parameter that will define the label based on the array input (if provided). Alternatively buttonPlaceholder could be made a function that takes the value as input.

</blockquote></details>

I don't understand what you mean by `another functional parameter that will define the label based on the array input`
___
*[`lib/platform-bible-react/src/components/basics/combo-box.component.tsx` line 135 at r1](https://reviewable.io/reviews/paranext/paranext-core/1325#-OCE7E_16D5Qi9xnDJ7h:-OCEWofV2ARIa0A8tq8Q:b-f13qoq) ([raw file](https://github.com/paranext/paranext-core/blob/6289f625d1672518ef7602f2436f38ec8c790506/lib/platform-bible-react/src/components/basics/combo-box.component.tsx#L135)):*
<details><summary><i>Previously, Sebastian-ubs wrote…</i></summary><blockquote>

please check if this mode still works for keyboard only selection or breaks this
</blockquote></details>

Yep, works perfectly :)

**Comment by jolierabideau** [comment]
@rolfheij-sil That makes sense! Yes, I think that would work

**Review by rolfheij-sil — COMMENTED** [review]
Thanks for the feedback. I added three new props:
- a prop that lets you hide the Chevrons
- a prop that lets you select if you want the values to show up on the button or always want the placeholder to show
- a prop that lets you add an icon on the left.

I think it is still reasonable to keep all of this inside the same component, instead of having multiple very similar combobox-like components in PBR.



> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/1325#-:-OCEbeJD0BJp58AHhit7:b2ihl79)* status: 5 of 7 files reviewed, 1 unresolved discussion (waiting on @Sebastian-ubs)

___
*[`lib/platform-bible-react/src/components/basics/combo-box.component.tsx` line 71 at r1](https://reviewable.io/reviews/paranext/paranext-core/1325#-OCE2GwqB9NmjOVNseJQ:-OCEc1IC1x214NBtGvd_:b-cp5tpx) ([raw file](https://github.com/paranext/paranext-core/blob/6289f625d1672518ef7602f2436f38ec8c790506/lib/platform-bible-react/src/components/basics/combo-box.component.tsx#L71)):*
<details><summary><i>Previously, Sebastian-ubs wrote…</i></summary><blockquote>

a new parameter of type function e.g. "getButtonLabel" (and rename the internal func). So that consumers could implement e.g. a function that shows "Checks (5 selected)".
But maybe even more options are needed, like stated above.
</blockquote></details>

Ah yes, now I understand. I suggest to not add this new feature right now. It's not needed for what I am  currently building.

**Review by rolfheij-sil — COMMENTED** [review]
Added one more prop that lets you control how the popover menu should be aligned. By default it's center aligned, but I see it's start aligned for all the design you posted above @Sebastian-ubs 

> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/1325#-:-OCEip3X26x9SNxz7-EW:b-mu91qq)* status: 0 of 7 files reviewed, 1 unresolved discussion (waiting on @Sebastian-ubs)

**Review by Sebastian-ubs — CHANGES_REQUESTED** [review]
You are right @rolfheij-sil, we should not end up with a lot of very similar components, but also adding a lot of properties to a single component increases the testing matrix and may make usage inconsistent and harder to understand for our users.
One goal of the component library is to have simple components with clearly distinct variances.
Therefore spotting a missing variant could also mean to go back to the designers and say "we do not have this right now. Are you sure we should add this new variant?"
So I suggest talking to agreeing on the component to use before building too many options in or creating similar components.

> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/1325#-:-OCEl9r47Pz-FDhusr70:baxkg78)* status: 0 of 7 files reviewed, all discussions resolved

**Review by rolfheij-sil — COMMENTED** [review]
Yeah, I get what you're saying. I was thinking the other way around though: If I see a UX design, I assume that is what they want me to build, and add new component/variants to achieve that.
This could be something to talk about in the next UX+Dev meeting: a more high level discussion on how to convert a UX design into real code.

For now: Do you want to talk more about this specific component, or can we add these changes to PBR?

> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/1325#-:-OCEvk3fBF3iXAFjAaE0:b-19wmzu)* status: 0 of 7 files reviewed, all discussions resolved (waiting on @Sebastian-ubs)

**Review by Sebastian-ubs — CHANGES_REQUESTED** [review]
Thank you Rolf. I guess the ux design might not have considered with which component this should be implemented. I know that in the past we had agreed to mostly use standard shadncn components and if deviating from it, make sure what the change is. The checks and home/open design however seem to have forgotten about this.
You might have even noticed that also I have contradicted my previous message and only remembered we want less variance later.
> But maybe even more options are needed, like stated above.

So, yes it will be helpful to reiterate on this in the ux-dev meeting.
In general I want to review out components and define which to use when together with Jolie (but unfortunately did not recognize this would be needed now, so did not do it yet).

For this case I would suggest to implement the bare minimum, so that we might not match the design shown, but only the functionality and then discuss it in the ux-dev or as a follow up.
That would mean to remove the newly added
-   a prop that lets you hide the Chevrons
-   a prop that lets you select if you want the values to show up on the button or always want the placeholder to show
-   a prop that lets you add an icon on the left.

> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/1325#-:-OCHmGRS5AKm_h7rukG6:b-xjc27f)* status: 0 of 7 files reviewed, all discussions resolved

**Review by rolfheij-sil — COMMENTED** [review]
Thanks! I'll wait with removing those (or not) until we've talked about it in the UX+Dev meeting. That'll save me some time :)

> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/1325#-:-OCI6IAr3CBs3rzrtUNh:b9164j5)* status: 0 of 7 files reviewed, all discussions resolved (waiting on @Sebastian-ubs)

**Comment by irahopkinson** [comment]
My 2 cents. You could keep the complicated component as the internal implementation detail and only export several wrapper components that simplify the options.

**Review by rolfheij-sil — COMMENTED** [review]
I've finalized the implementation of the multi-select combo box. It's ready to be merged now, so that it can be used in the updated Get Resources design on `1290-v2-resources-and-home-extensions`

> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/1325#-:-ODLGNhlEeKYJ1WGxF1t:bxumgg3)* status: 0 of 18 files reviewed, all discussions resolved (waiting on @Sebastian-ubs)

**Comment by Sebastian-ubs** [comment]
*[`lib/platform-bible-react/src/components/advanced/multi-select-combo-box.tsx` line 53 at r7](https://reviewable.io/reviews/paranext/paranext-core/1325#-ODLL8XcCRVjkGKPixoL:-ODLPEybEPJ_4OGvzfWl:b-8vljpi) ([raw file](https://github.com/paranext/paranext-core/blob/b6f4d631ee3c889480c209757f1b00dc6d6c3ccc/lib/platform-bible-react/src/components/advanced/multi-select-combo-box.tsx#L53)):*
> One issue I see
Rethinking this, it may actually work to change to text-muted with inverting the same logic as below
> selected.length > 0 && selected.length < options.length

**Comment by Sebastian-ubs** [comment]
*[`lib/platform-bible-react/src/components/advanced/multi-select-combo-box.tsx` line 53 at r7](https://reviewable.io/reviews/paranext/paranext-core/1325#-ODLL8XcCRVjkGKPixoL:-ODLPliu-yZACuTnwteq:b-gxjrme) ([raw file](https://github.com/paranext/paranext-core/blob/b6f4d631ee3c889480c209757f1b00dc6d6c3ccc/lib/platform-bible-react/src/components/advanced/multi-select-combo-box.tsx#L53)):*
> One issue I see  

Rethinking this, it may actually work to change to text-muted with inverting the same logic as below  

> selected.length > 0 && selected.length < options.length

**Review by rolfheij-sil — COMMENTED** [review]
Thanks for reviewing

> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/1325#-:-ODLUHSJAgVChGfOtbxB:b-lr058f)* status: all files reviewed, 4 unresolved discussions (waiting on @Sebastian-ubs)

___
*[`lib/platform-bible-react/src/components/advanced/multi-select-combo-box.tsx` line 4 at r7](https://reviewable.io/reviews/paranext/paranext-core/1325#-ODLJ3fT7p8ayGDpD1r8:-ODLPLfPBKG9MG2eyTe8:bb6un1j) ([raw file](https://github.com/paranext/paranext-core/blob/b6f4d631ee3c889480c209757f1b00dc6d6c3ccc/lib/platform-bible-react/src/components/advanced/multi-select-combo-box.tsx#L4)):*
<details><summary><i>Previously, Sebastian-ubs wrote…</i></summary><blockquote>

should import from @components/shadcn-ui/button
Same for the 2 imports below
</blockquote></details>

Done
___
*[`lib/platform-bible-react/src/components/advanced/multi-select-combo-box.tsx` line 23 at r7](https://reviewable.io/reviews/paranext/paranext-core/1325#-ODLJNt0A7cyRdO3AkQ3:-ODLPY5T37YROaVrGIkP:bb6un1j) ([raw file](https://github.com/paranext/paranext-core/blob/b6f4d631ee3c889480c209757f1b00dc6d6c3ccc/lib/platform-bible-react/src/components/advanced/multi-select-combo-box.tsx#L23)):*
<details><summary><i>Previously, Sebastian-ubs wrote…</i></summary><blockquote>

should we rename those to "entries" and "getEntriesCount"?
</blockquote></details>

Done
___
*[`lib/platform-bible-react/src/components/advanced/multi-select-combo-box.tsx` line 53 at r7](https://reviewable.io/reviews/paranext/paranext-core/1325#-ODLL8XcCRVjkGKPixoL:-ODLRXmN3U31-3iisOgX:bhfgpet) ([raw file](https://github.com/paranext/paranext-core/blob/b6f4d631ee3c889480c209757f1b00dc6d6c3ccc/lib/platform-bible-react/src/components/advanced/multi-select-combo-box.tsx#L53)):*
<details><summary><i>Previously, Sebastian-ubs wrote…</i></summary><blockquote>

> One issue I see  

Rethinking this, it may actually work to change to text-muted with inverting the same logic as below  

> selected.length > 0 && selected.length < options.length
</blockquote></details>

Done, I added to logic to have none/all selected placeholder show up muted
___
*[`lib/platform-bible-react/src/components/advanced/multi-select-combo-box.tsx` line 88 at r7](https://reviewable.io/reviews/paranext/paranext-core/1325#-ODLKTUA9xXnUH3efpK7:-ODLSSYPAcZuaLT5rEvI:b-ylfaa0) ([raw file](https://github.com/paranext/paranext-core/blob/b6f4d631ee3c889480c209757f1b00dc6d6c3ccc/lib/platform-bible-react/src/components/advanced/multi-select-combo-box.tsx#L88)):*
<details><summary><i>Previously, Sebastian-ubs wrote…</i></summary><blockquote>

I think this should be optional for a general multi select combobox. Could you add prop for it or should we rename this whole component to something like filter-combobox?
</blockquote></details>

I don't know. Let's just leave it in here for now. If people don't like this, we can always refactor this out into a prop. But I don't want to overcomplicate this component with extra props without good reason
___
*[`lib/platform-bible-react/src/components/advanced/multi-select-combo-box.tsx` line 106 at r7](https://reviewable.io/reviews/paranext/paranext-core/1325#-ODLMQ9S6dBfEFvojKQK:-ODLSxgT-NLz7QhRXbqC:bg7b6uf) ([raw file](https://github.com/paranext/paranext-core/blob/b6f4d631ee3c889480c209757f1b00dc6d6c3ccc/lib/platform-bible-react/src/components/advanced/multi-select-combo-box.tsx#L106)):*
<details><summary><i>Previously, Sebastian-ubs wrote…</i></summary><blockquote>

This is not localizable.
</blockquote></details>

Can we just leave this out then? Or maybe display some icon? I don't think now is the right time to start thinking about localizing basic react components. 
___
*[`lib/platform-bible-react/src/components/basics/combo-box.component.tsx` line 28 at r7](https://reviewable.io/reviews/paranext/paranext-core/1325#-ODLMnHS2j4XakTI_CmV:-ODLTy972RP1l-pEOlK_:bb6un1j) ([raw file](https://github.com/paranext/paranext-core/blob/b6f4d631ee3c889480c209757f1b00dc6d6c3ccc/lib/platform-bible-react/src/components/basics/combo-box.component.tsx#L28)):*
<details><summary><i>Previously, Sebastian-ubs wrote…</i></summary><blockquote>

adjust back to no multi select
</blockquote></details>

Done
___
*[`lib/platform-bible-react/src/components/shadcn-ui/badge.tsx` line 32 at r7](https://reviewable.io/reviews/paranext/paranext-core/1325#-ODLN6pC2IGh778oDtk8:-ODLU4HF20QkF2UshKr6:b-va1ja4) ([raw file](https://github.com/paranext/paranext-core/blob/b6f4d631ee3c889480c209757f1b00dc6d6c3ccc/lib/platform-bible-react/src/components/shadcn-ui/badge.tsx#L32)):*
<details><summary><i>Previously, Sebastian-ubs wrote…</i></summary><blockquote>

It could be nice to include the x button already.
Might be done by adding a onClear prop that would if exists implicitly add a clear button or by explicitly stating both.
</blockquote></details>

The work here is already suffering from a lot of scope creep, let's keep this just as basic as we can. Also we don't generally change shadcn components unless we have to.

**Review by Sebastian-ubs — CHANGES_REQUESTED** [review]
> Reviewed 9 of 9 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/1325)* status: all files reviewed, 2 unresolved discussions (waiting on @rolfheij-sil)

___
*[`lib/platform-bible-react/src/components/advanced/multi-select-combo-box.tsx` line 88 at r7](https://reviewable.io/reviews/paranext/paranext-core/1325#-ODLKTUA9xXnUH3efpK7:-ODLl5VsECxqcgkpdA9s:bb7g85b) ([raw file](https://github.com/paranext/paranext-core/blob/b6f4d631ee3c889480c209757f1b00dc6d6c3ccc/lib/platform-bible-react/src/components/advanced/multi-select-combo-box.tsx#L88)):*
<details><summary><i>Previously, rolfheij-sil (Rolf Heij) wrote…</i></summary><blockquote>

I don't know. Let's just leave it in here for now. If people don't like this, we can always refactor this out into a prop. But I don't want to overcomplicate this component with extra props without good reason
</blockquote></details>

fine
___
*[`lib/platform-bible-react/src/components/advanced/multi-select-combo-box.tsx` line 106 at r7](https://reviewable.io/reviews/paranext/paranext-core/1325#-ODLMQ9S6dBfEFvojKQK:-ODLlOfXDr_j8ebJ0oT6:bfqplxh) ([raw file](https://github.com/paranext/paranext-core/blob/b6f4d631ee3c889480c209757f1b00dc6d6c3ccc/lib/platform-bible-react/src/components/advanced/multi-select-combo-box.tsx#L106)):*
the combobox is exporting a prop
>   commandEmptyMessage =  'No option found',

**Review by Sebastian-ubs — APPROVED** [review]
> Reviewed 6 of 6 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/1325)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

___
*[`lib/platform-bible-react/src/components/shadcn-ui/badge.tsx` line 32 at r7](https://reviewable.io/reviews/paranext/paranext-core/1325#-ODLN6pC2IGh778oDtk8:-ODMI1S93-EzjyvO6CnK:b-p3vieg) ([raw file](https://github.com/paranext/paranext-core/blob/b6f4d631ee3c889480c209757f1b00dc6d6c3ccc/lib/platform-bible-react/src/components/shadcn-ui/badge.tsx#L32)):*
<details><summary><i>Previously, rolfheij-sil (Rolf Heij) wrote…</i></summary><blockquote>

The work here is already suffering from a lot of scope creep, let's keep this just as basic as we can. Also we don't generally change shadcn components unless we have to.
</blockquote></details>

I agree, we could follow up on that later. If to change them or not is an open question still.

**Comment by Sebastian-ubs** [comment]
hurray. Thank you for all the effort you put into this @rolfheij-sil

**Pull request merged**
