### PR TITLE
use the BiblioNexus Foundation shared Scripture editor

### PR DESCRIPTION
**Pull request by irahopkinson**
- add BNF editor package
- remove `usxeditor` package
- add scripts for developers to link the editor locally (without needing to publish)
- improve editor styles

- - -
This change is [Reviewable](https://reviewable.io/reviews/paranext/paranext-core/753)

### CODE REVIEW

**Review by tjcouch-sil — CHANGES_REQUESTED** [review]
Wow!! Awesome :) thanks for the great work. This is really exciting!

> Reviewed 47 of 47 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/753#-:-Nq2ymWP81rWjxTjuTdm:bhqh62m)* status: all files reviewed, 2 unresolved discussions (waiting on @irahopkinson)

___
*[`.erb/configs/webpack.config.renderer.dev.dll.ts` line 24 at r1](https://reviewable.io/reviews/paranext/paranext-core/753#-Nq2vgdN-OEn2QBAC9Ml:-Nq2vgdN-OEn2QBAC9Mm:bktn5gw) ([raw file](https://github.com/paranext/paranext-core/blob/f4fd097741235b702ff6cf2354c15c0218d65a5e/.erb/configs/webpack.config.renderer.dev.dll.ts#L24)):*
> ```XML
>   target: 'electron-renderer',
> 
>   externals: ['fsevents', 'crypto-browserify', '@biblionexus-foundation/platform-editor'],
> ```

Do you know what these dlls are? Looks like maybe they're all our dependencies bundled up ahead of time for speed reasons...? I have always kinda wondered but have never cared enough to investigate haha

Why would we put the editor in? So you can keep up-to-date with the local package instead of bundling in a static version?
___
*[`extensions/src/resource-viewer/src/_editor.scss` line 1 at r1](https://reviewable.io/reviews/paranext/paranext-core/753#-Nq2xG_D6zwO5VNeGBsA:-Nq2xG_D6zwO5VNeGBsB:byummny) ([raw file](https://github.com/paranext/paranext-core/blob/f4fd097741235b702ff6cf2354c15c0218d65a5e/extensions/src/resource-viewer/src/_editor.scss#L1)):*
> ```SCSS
> /* stylelint-disable selector-no-qualifying-type */
> ```

Remind me, please, what is the deal with putting underscore before names of style files? And are these styles not distributed in the editor library?
___
*[`extensions/src/resource-viewer/src/resource-viewer.web-view.scss` line 1 at r1](https://reviewable.io/reviews/paranext/paranext-core/753#-Nq2xnNfA5kXJt6Hac8M:-Nq2xnNfA5kXJt6Hac8N:b-1z62rs) ([raw file](https://github.com/paranext/paranext-core/blob/f4fd097741235b702ff6cf2354c15c0218d65a5e/extensions/src/resource-viewer/src/resource-viewer.web-view.scss#L1)):*
> ```SCSS
> // TODO: replace this `styles` file with one from each Scripture project.
> ```

Might be good to file an issue on this :) thanks for thinking of it!
___
*[`extensions/src/resource-viewer/src/resource-viewer.web-view.tsx` line 42 at r1](https://reviewable.io/reviews/paranext/paranext-core/753#-Nq2yXBq0ibBy-2sFF4o:-Nq2yXBq0ibBy-2sFF4p:bwfu6rf) ([raw file](https://github.com/paranext/paranext-core/blob/f4fd097741235b702ff6cf2354c15c0218d65a5e/extensions/src/resource-viewer/src/resource-viewer.web-view.tsx#L42)):*
> ```XML
>   return (
>     <>
>       <Editor usj={usj} scrRefState={[scrRef, setScrRef]} logger={logger} />
> ```

Is this intentionally read-only? Or where do we use `setUsj` to update the data? Or maybe that's coming later and I should be quiet 😂
___
*[`extensions/src/resource-viewer/src/resource-viewer.web-view.tsx` line 43 at r1](https://reviewable.io/reviews/paranext/paranext-core/753#-Nq2yIku5k1gK1rZyYjV:-Nq2yIku5k1gK1rZyYjW:bq01zl3) ([raw file](https://github.com/paranext/paranext-core/blob/f4fd097741235b702ff6cf2354c15c0218d65a5e/extensions/src/resource-viewer/src/resource-viewer.web-view.tsx#L43)):*
> ```XML
>     <>
>       <Editor usj={usj} scrRefState={[scrRef, setScrRef]} logger={logger} />
>       {/* <pre>{JSON.stringify(usj, undefined, 2)}</pre> */}
> ```

Do we need these commented lines?

**Review by irahopkinson — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/753)* status: 46 of 47 files reviewed, 1 unresolved discussion (waiting on @tjcouch-sil)

___
*[`.erb/configs/webpack.config.renderer.dev.dll.ts` line 24 at r1](https://reviewable.io/reviews/paranext/paranext-core/753#-Nq2vgdN-OEn2QBAC9Ml:-Nq3kk3p73GI3ZKSKa4V:bk1chtx) ([raw file](https://github.com/paranext/paranext-core/blob/f4fd097741235b702ff6cf2354c15c0218d65a5e/.erb/configs/webpack.config.renderer.dev.dll.ts#L24)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

Do you know what these dlls are? Looks like maybe they're all our dependencies bundled up ahead of time for speed reasons...? I have always kinda wondered but have never cared enough to investigate haha

Why would we put the editor in? So you can keep up-to-date with the local package instead of bundling in a static version?
</blockquote></details>

In `package.json` I have added 3 scripts that use `yalc` to locally link in changes from the editor so you can test things before publishing the editor. That didn't work without adding the editor here.
___
*[`extensions/src/resource-viewer/src/_editor.scss` line 1 at r1](https://reviewable.io/reviews/paranext/paranext-core/753#-Nq2xG_D6zwO5VNeGBsA:-Nq3lWUU0twi8VdALHCM:b-253m44) ([raw file](https://github.com/paranext/paranext-core/blob/f4fd097741235b702ff6cf2354c15c0218d65a5e/extensions/src/resource-viewer/src/_editor.scss#L1)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

Remind me, please, what is the deal with putting underscore before names of style files? And are these styles not distributed in the editor library?
</blockquote></details>

The `styles.css` file that comes with a PT9 project has classes with underscores. This file overrides some of those.
___
*[`extensions/src/resource-viewer/src/resource-viewer.web-view.scss` line 1 at r1](https://reviewable.io/reviews/paranext/paranext-core/753#-Nq2xnNfA5kXJt6Hac8M:-Nq3oaa56OJtnHsvtot8:b3uu1yd) ([raw file](https://github.com/paranext/paranext-core/blob/f4fd097741235b702ff6cf2354c15c0218d65a5e/extensions/src/resource-viewer/src/resource-viewer.web-view.scss#L1)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

Might be good to file an issue on this :) thanks for thinking of it!
</blockquote></details>

Good idea, see #754.
___
*[`extensions/src/resource-viewer/src/resource-viewer.web-view.tsx` line 42 at r1](https://reviewable.io/reviews/paranext/paranext-core/753#-Nq2yXBq0ibBy-2sFF4o:-Nq3mM3D7tiRz5eci9Go:b-b86cfp) ([raw file](https://github.com/paranext/paranext-core/blob/f4fd097741235b702ff6cf2354c15c0218d65a5e/extensions/src/resource-viewer/src/resource-viewer.web-view.tsx#L42)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

Is this intentionally read-only? Or where do we use `setUsj` to update the data? Or maybe that's coming later and I should be quiet 😂
</blockquote></details>

Yes, this first version is editable but you can't save it yet. If you want to make it truly readonly (not editable, like it should be for the resource viewer) then use the `isReadonly` property. I'm not doing that yet as this resource viewer is currently writable and that's the easiest place to continue testing the editor.
___
*[`extensions/src/resource-viewer/src/resource-viewer.web-view.tsx` line 43 at r1](https://reviewable.io/reviews/paranext/paranext-core/753#-Nq2yIku5k1gK1rZyYjV:-Nq3okZv2bQ9q5vyULLN:b-inknpb) ([raw file](https://github.com/paranext/paranext-core/blob/f4fd097741235b702ff6cf2354c15c0218d65a5e/extensions/src/resource-viewer/src/resource-viewer.web-view.tsx#L43)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

Do we need these commented lines?
</blockquote></details>

Done, you are right, we don't need them anymore.

**Review by tjcouch-sil — APPROVED** [review]
Yay!! How exciting! I bet everyone would LOVE to see this at the sprint demo today!

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/753#-:-Nq3xOEu5drIa36ub_eP:b-gllxsr)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

___
*[`.erb/configs/webpack.config.renderer.dev.dll.ts` line 24 at r1](https://reviewable.io/reviews/paranext/paranext-core/753#-Nq2vgdN-OEn2QBAC9Ml:-Nq3xKRNBQxLE-IYS3YO:b8jrlvb) ([raw file](https://github.com/paranext/paranext-core/blob/f4fd097741235b702ff6cf2354c15c0218d65a5e/.erb/configs/webpack.config.renderer.dev.dll.ts#L24)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

In `package.json` I have added 3 scripts that use `yalc` to locally link in changes from the editor so you can test things before publishing the editor. That didn't work without adding the editor here.
</blockquote></details>

Neat. Thanks!
___
*[`extensions/src/resource-viewer/src/_editor.scss` line 1 at r1](https://reviewable.io/reviews/paranext/paranext-core/753#-Nq2xG_D6zwO5VNeGBsA:-Nq3wwy_EtMkx_2qDhT5:b-wowk3) ([raw file](https://github.com/paranext/paranext-core/blob/f4fd097741235b702ff6cf2354c15c0218d65a5e/extensions/src/resource-viewer/src/_editor.scss#L1)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

The `styles.css` file that comes with a PT9 project has classes with underscores. This file overrides some of those.
</blockquote></details>

Sorry, I meant the naming convention of putting an underscore at the start of a file name. I don't remember seeing that before, but I remember you mentioned it in a recent PR as well. Was just trying to remember :)
___
*[`extensions/src/resource-viewer/src/resource-viewer.web-view.scss` line 1 at r1](https://reviewable.io/reviews/paranext/paranext-core/753#-Nq2xnNfA5kXJt6Hac8M:-Nq3waGiD6lxnXH6kmjL:b-10zgjg) ([raw file](https://github.com/paranext/paranext-core/blob/f4fd097741235b702ff6cf2354c15c0218d65a5e/extensions/src/resource-viewer/src/resource-viewer.web-view.scss#L1)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

Good idea, see #754.
</blockquote></details>

Thank you!!

**Comment by irahopkinson** [comment]
*[`extensions/src/resource-viewer/src/_editor.scss` line 1 at r1](https://reviewable.io/reviews/paranext/paranext-core/753#-Nq2xG_D6zwO5VNeGBsA:-Nq41Ssa5wspSzMr41oD:b-gigaxu) ([raw file](https://github.com/paranext/paranext-core/blob/f4fd097741235b702ff6cf2354c15c0218d65a5e/extensions/src/resource-viewer/src/_editor.scss#L1)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

Sorry, I meant the naming convention of putting an underscore at the start of a file name. I don't remember seeing that before, but I remember you mentioned it in a recent PR as well. Was just trying to remember :)
</blockquote></details>

Oh right, sorry I was confused because I thought the comment was on the `stylelint-disable` but it's just on the first line of the file (FYI in Reviewable you can dropdown on the filename to have a file level discussion).

An `_` at the front of a SCSS file declares it to be a partial and therefore intended to be combined with other SCSS files in order to use it. E.g. you may declare variables in a `_vars.scss` partial and combine that with another parital that uses those variables. In this case the 2nd partial definitely can't be used on its own. Here the 3 partials are combined together in a particular order inside `resource-viewer.web-view.scss` - project styles are applied first, then styles from the editor and lastly particular overrides for platform.

**Pull request merged**
