### PR TITLE
add id to components

### PR DESCRIPTION
**Pull request by jolierabideau**
Added id prop to all components
Table component was difficult because it would not let me add prop to DataGrid, added it by putting a div around the DataGrid. I also fixed a couple errors I found in the table component. 

- - -
This change is [Reviewable](https://reviewable.io/reviews/paranext/paranext-core/354)

### CODE REVIEW

**Review by tjcouch-sil — CHANGES_REQUESTED** [review]
Thanks for the hard work on this! Just a couple of comments.

> Reviewed 17 of 17 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/354#-:-Nb_qDFYAW3I4muE1glh:bkk7alm)* status: all files reviewed, 2 unresolved discussions (waiting on @jolierabideau)

___
*[`lib/papi-components/src/ref-selector.component.tsx` line 57 at r1](https://reviewable.io/reviews/paranext/paranext-core/354#-Nb_kskt-lMWod1aSAle:-Nb_kskt-lMWod1aSAlf:bbt6afo) ([raw file](https://github.com/paranext/paranext-core/blob/c6647694b94eda11e1c7a7448fb4db0f049491c0/lib/papi-components/src/ref-selector.component.tsx#L57)):*
> ```XML
> 
>   return (
>     <div id={id}>
> ```

Please change this `div` into a `span`. `span`s do not have any styles by default, whereas `div`s have `display: block`, which is likely not what we want for the ref selector.
___
*[`lib/papi-components/src/table.component.tsx` line 327 at r1](https://reviewable.io/reviews/paranext/paranext-core/354#-Nb_lPfX1TPPyYfaOjmm:-Nb_lPfX1TPPyYfaOjmn:bd5cvls) ([raw file](https://github.com/paranext/paranext-core/blob/c6647694b94eda11e1c7a7448fb4db0f049491c0/lib/papi-components/src/table.component.tsx#L327)):*
> ```XML
> 
>   return (
>     <div id={id}>
> ```

Adding a `div` here may have some unintended consequences like making this component harder to style via props. Instead, can we make a patch to the `react-data-grid` package to add the `id` prop and file an issue on their GitHub? They already have a prop called 'data-testid' which does basically what we want to do but with a different name, so it will hopefully be a simple patch.

Essentially, [to make a patch](https://www.npmjs.com/package/patch-package), do these things:

1. Make the changes in the code in the `node_modules` folder. You will want to add `id` similar to how `data-testid` works in each of the following files:

  - `paranext-core/node_modules/react-data-grid/lib/bundle.cjs`
  - `paranext-core/node_modules/react-data-grid/lib/bundle.js`
  - `paranext-core/node_modules/react-data-grid/lib/index.d.ts`

2. From `paranext-core`, run `npx patch-package react-data-grid`.

3. File an issue requesting that this functionality be added on https://github.com/adazzle/react-data-grid/issues

Then I think you're done!

**Review by jolierabideau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/354)* status: all files reviewed, 2 unresolved discussions (waiting on @tjcouch-sil)

___
*[`lib/papi-components/src/ref-selector.component.tsx` line 57 at r1](https://reviewable.io/reviews/paranext/paranext-core/354#-Nb_kskt-lMWod1aSAle:-Nb_qsxWC1bnb3-6X8cY:b-896fix) ([raw file](https://github.com/paranext/paranext-core/blob/c6647694b94eda11e1c7a7448fb4db0f049491c0/lib/papi-components/src/ref-selector.component.tsx#L57)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

Please change this `div` into a `span`. `span`s do not have any styles by default, whereas `div`s have `display: block`, which is likely not what we want for the ref selector.
</blockquote></details>

Done.
___
*[`lib/papi-components/src/table.component.tsx` line 327 at r1](https://reviewable.io/reviews/paranext/paranext-core/354#-Nb_lPfX1TPPyYfaOjmm:-Nba0n_2-QvxKIltacdZ:b-4iqgs3) ([raw file](https://github.com/paranext/paranext-core/blob/c6647694b94eda11e1c7a7448fb4db0f049491c0/lib/papi-components/src/table.component.tsx#L327)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

Adding a `div` here may have some unintended consequences like making this component harder to style via props. Instead, can we make a patch to the `react-data-grid` package to add the `id` prop and file an issue on their GitHub? They already have a prop called 'data-testid' which does basically what we want to do but with a different name, so it will hopefully be a simple patch.

Essentially, [to make a patch](https://www.npmjs.com/package/patch-package), do these things:

1. Make the changes in the code in the `node_modules` folder. You will want to add `id` similar to how `data-testid` works in each of the following files:

  - `paranext-core/node_modules/react-data-grid/lib/bundle.cjs`
  - `paranext-core/node_modules/react-data-grid/lib/bundle.js`
  - `paranext-core/node_modules/react-data-grid/lib/index.d.ts`

2. From `paranext-core`, run `npx patch-package react-data-grid`.

3. File an issue requesting that this functionality be added on https://github.com/adazzle/react-data-grid/issues

Then I think you're done!
</blockquote></details>

Looks like this worked, and patching a package was neat! I added the prop and it appears to be working, but I didn't use the quotes like 'data-testid' because other props like `className` were not in quotes. I am also not quite sure what the quotes mean.

**Review by tjcouch-sil — CHANGES_REQUESTED** [review]
> Reviewed 2 of 7 files at r2, 5 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/354)* status: all files reviewed, 1 unresolved discussion (waiting on @jolierabideau)

___
*[`lib/papi-components/src/ref-selector.component.tsx` line 57 at r1](https://reviewable.io/reviews/paranext/paranext-core/354#-Nb_kskt-lMWod1aSAle:-Nboe7Gh2ANRIDv8F5Ug:bw5hc66) ([raw file](https://github.com/paranext/paranext-core/blob/c6647694b94eda11e1c7a7448fb4db0f049491c0/lib/papi-components/src/ref-selector.component.tsx#L57)):*
<details><summary><i>Previously, jolierabideau wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Great. Thanks!
___
*[`lib/papi-components/src/table.component.tsx` line 327 at r1](https://reviewable.io/reviews/paranext/paranext-core/354#-Nb_lPfX1TPPyYfaOjmm:-NboeO3ZEI-ZPU2_A--g:b-wynoaf) ([raw file](https://github.com/paranext/paranext-core/blob/c6647694b94eda11e1c7a7448fb4db0f049491c0/lib/papi-components/src/table.component.tsx#L327)):*
<details><summary><i>Previously, jolierabideau wrote…</i></summary><blockquote>

Looks like this worked, and patching a package was neat! I added the prop and it appears to be working, but I didn't use the quotes like 'data-testid' because other props like `className` were not in quotes. I am also not quite sure what the quotes mean. 
</blockquote></details>

Great :) good work!!

Putting a prop name in quotes allows you to put characters in the name that are allowed as html attribute names but not as javascript identifiers like `-`. Glad you didn't add quotes as they are unnecessary in this context :)

Did you file an issue with `react-data-grid`? Would be good to link it somewhere in a comment in the code so we can keep track of it. Maybe here would be good.

**Review by jolierabideau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/354)* status: all files reviewed, 1 unresolved discussion (waiting on @tjcouch-sil)

___
*[`lib/papi-components/src/table.component.tsx` line 327 at r1](https://reviewable.io/reviews/paranext/paranext-core/354#-Nb_lPfX1TPPyYfaOjmm:-NbooiM79YDgwTnMmEJI:bwu2uzg) ([raw file](https://github.com/paranext/paranext-core/blob/c6647694b94eda11e1c7a7448fb4db0f049491c0/lib/papi-components/src/table.component.tsx#L327)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

Great :) good work!!

Putting a prop name in quotes allows you to put characters in the name that are allowed as html attribute names but not as javascript identifiers like `-`. Glad you didn't add quotes as they are unnecessary in this context :)

Did you file an issue with `react-data-grid`? Would be good to link it somewhere in a comment in the code so we can keep track of it. Maybe here would be good.
</blockquote></details>

Okay that makes sense! I did file an issue, will add it in the comment above the prop.

**Review by tjcouch-sil — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/354)* status: all files reviewed, 1 unresolved discussion (waiting on @jolierabideau)

___
*[`lib/papi-components/src/table.component.tsx` line 327 at r1](https://reviewable.io/reviews/paranext/paranext-core/354#-Nb_lPfX1TPPyYfaOjmm:-NbpA62L4rMQnM2M_mAJ:bk9w7dw) ([raw file](https://github.com/paranext/paranext-core/blob/c6647694b94eda11e1c7a7448fb4db0f049491c0/lib/papi-components/src/table.component.tsx#L327)):*
<details><summary><i>Previously, jolierabideau wrote…</i></summary><blockquote>

Okay that makes sense! I did file an issue, will add it in the comment above the prop.
</blockquote></details>

Thank you for adding the issue and the comment! But unfortunately this is an internal detail to the implementation of our component, whereas the JSDoc comment on the prop is a published comment that people who use our component library will see. Let's make it not a JSDoc comment. You can either keep it in the same place but put it outside the `/** ... */` comment, or you can put it somewhere else. Whatever is great. Putting it ouside the JSDoc comment looks like this:

```
/**
 *
 * JSDoc comment stuff here that everyone who uses our Table component will see
 *
 */
// stuff that we're secretly adding to the comments just for ourselves internally but others won't see
id?: string;
```

**Review by jolierabideau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/354)* status: 17 of 18 files reviewed, 1 unresolved discussion (waiting on @tjcouch-sil)

___
*[`lib/papi-components/src/table.component.tsx` line 327 at r1](https://reviewable.io/reviews/paranext/paranext-core/354#-Nb_lPfX1TPPyYfaOjmm:-NbpB1FGB-huI0Ibni7m:b-urjjmy) ([raw file](https://github.com/paranext/paranext-core/blob/c6647694b94eda11e1c7a7448fb4db0f049491c0/lib/papi-components/src/table.component.tsx#L327)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

Thank you for adding the issue and the comment! But unfortunately this is an internal detail to the implementation of our component, whereas the JSDoc comment on the prop is a published comment that people who use our component library will see. Let's make it not a JSDoc comment. You can either keep it in the same place but put it outside the `/** ... */` comment, or you can put it somewhere else. Whatever is great. Putting it ouside the JSDoc comment looks like this:

```
/**
 *
 * JSDoc comment stuff here that everyone who uses our Table component will see
 *
 */
// stuff that we're secretly adding to the comments just for ourselves internally but others won't see
id?: string;
```
</blockquote></details>

Done I definitely forgot that so I apologize and thank you.

**Review by tjcouch-sil — APPROVED** [review]
Thanks for getting this wrapped up! :)

> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/354#-:-NbpWNccE94Za7VQDnVj:b-azkjlr)* status: :shipit: complete! all files reviewed, all discussions resolved

___
*[`lib/papi-components/src/table.component.tsx` line 327 at r1](https://reviewable.io/reviews/paranext/paranext-core/354#-Nb_lPfX1TPPyYfaOjmm:-NbpWJfQBSYsUJATztcO:b-5zedrc) ([raw file](https://github.com/paranext/paranext-core/blob/c6647694b94eda11e1c7a7448fb4db0f049491c0/lib/papi-components/src/table.component.tsx#L327)):*
<details><summary><i>Previously, jolierabideau wrote…</i></summary><blockquote>

Done I definitely forgot that so I apologize and thank you.
</blockquote></details>

No worries :) all good. Thanks for the quick fix!

**Pull request merged**
