### PR TITLE
fix direction for many components

### PR DESCRIPTION
**Pull request by Sebastian-ubs**
This change is [Reviewable](https://reviewable.io/reviews/paranext/paranext-core/1049)

### CODE REVIEW

**Comment by Sebastian-ubs** [comment]
Follow up actions:
- https://github.com/paranext/paranext-core/issues/1050
- fix rtl issues for "example layouts"

**Review by irahopkinson — DISMISSED** [review]
:lgtm: Thanks for all these RTL fixes.

> Reviewed 19 of 19 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/1049#-:-O3imkHD2tOxdkN_22iO:b93e0ho)* status: all files reviewed, 1 unresolved discussion (waiting on @Sebastian-ubs)

___
*[`lib/platform-bible-react/src/preview/components/basics/dropdown.examples.component.tsx` line 29 at r2](https://reviewable.io/reviews/paranext/paranext-core/1049#-O3ilLIVEp3nq4UHCi9B:-O3ilLIW5Pb4OvEn-Z14:bfsz43t) ([raw file](https://github.com/paranext/paranext-core/blob/3104b3ab71e888fcface7773e7134b5122106fef/lib/platform-bible-react/src/preview/components/basics/dropdown.examples.component.tsx#L29)):*
> ```XML
>         <DropdownMenuGroup>
>           <DropdownMenuItem>
>             {/* direction not working, TODO added in component */}
> ```

BTW the removal of this comment could easily be missed when it's fixed or does some code need to be changed here too? Since you added a TODO elsewhere consider removing this comment (if no code changes needed here).

**Comment by Sebastian-ubs** [comment]
will need to wait for https://github.com/paranext/paranext-core/pull/1048 to be merged to pull and rebuild again

**Review by Sebastian-ubs — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext-core/1049)* status: 13 of 22 files reviewed, all discussions resolved (waiting on @irahopkinson)

___
*[`lib/platform-bible-react/src/preview/components/basics/dropdown.examples.component.tsx` line 29 at r2](https://reviewable.io/reviews/paranext/paranext-core/1049#-O3ilLIVEp3nq4UHCi9B:-O3lC_gm8R0zGJzMrly3:bb7f2mf) ([raw file](https://github.com/paranext/paranext-core/blob/3104b3ab71e888fcface7773e7134b5122106fef/lib/platform-bible-react/src/preview/components/basics/dropdown.examples.component.tsx#L29)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

BTW the removal of this comment could easily be missed when it's fixed or does some code need to be changed here too? Since you added a TODO elsewhere consider removing this comment (if no code changes needed here).
</blockquote></details>

done

**Pull request merged**
